### PR TITLE
[receiver/kafkareceiver] fix: Kafka receiver blocking shutdown

### LINKED ISSUE #30789: Kafka receiver stuck while shutting down at v0.93.0
### Component(s)

receiver/kafka

## Description
Shutting down kafka receiver got stuck forever while transitioning from `StatusStopping` to `StatusStopped`.

I've debugged this for a while and apparently this is because of `consumeLoop` returns `context canceled` error and do `ReportStatus FatalErrorEvent` at `receiver/kafkareceiver/kafka_receiver.go` between line 163-165. But the `sync.Mutex.Lock()` in `ReportStatus FatalErrorEvent` never gets unlocked (I don't know why), so that the `ReportStatus` for `StatusStopped` stuck forever while trying to acquire the mutex lock.

Also, I've tried to rollback to v0.92.0 and it works well. And traced to issue down to `receiver/kafkareceiver/kafka_receiver.go` at line 164 `c.settings.ReportStatus(component.NewFatalErrorEvent(err))` changed at PR https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/30593 was the cause.

## Steps to Reproduce
Create a collector with `kafkareceiver` factory in it. And have a `receivers.kafka` in the config.

## Expected Result
Should be able to shutdown properly.

## Actual Result
Stuck indefinitely while shutting down with the logs below.

### Collector version

v0.93.0

### Environment information

_No response_

### OpenTelemetry Collector configuration

```yaml
service:
  pipelines:
    traces:
      receivers: [kafka]

receivers:
  kafka:
    brokers:
      - localhost:9092
    encoding: otlp_proto # available encodings are otlp_proto, jaeger_proto, jaeger_json, zipkin_proto, zipkin_json, zipkin_thrift
    initial_offset: earliest # consume messages from the beginning
```

### Log output

```shell
2024-01-26T08:32:45.266+0700	info	kafkareceiver@v0.93.0/kafka_receiver.go:431	Starting consumer group	{"kind": "receiver", "name": "kafka", "data_type": "traces", "partition": 0}
^C2024-01-26T08:32:53.626+0700	info	otelcol@v0.93.0/collector.go:258	Received signal from OS	{"signal": "interrupt"}
2024-01-26T08:32:53.626+0700	info	service@v0.93.0/service.go:179	Starting shutdown...
2024-01-26T08:32:54.010+0700	info	kafkareceiver@v0.93.0/kafka_receiver.go:181	Consumer stopped	{"kind": "receiver", "name": "kafka", "data_type": "traces", "error": "context canceled"}
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by dpaasman00**
#### Description
Fixes an issue where the Kafka receiver would block on shutdown.

There was an earlier fix for this issue [here](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/32720). This does solve the issue, but it was only applied to the traces receiver, not the logs or metrics receiver.

The issue is this go routine in the `Start()` functions for logs and metrics:
```go
go func() {
        if err := c.consumeLoop(ctx, metricsConsumerGroup); err != nil {
		componentstatus.ReportStatus(host, componentstatus.NewFatalErrorEvent(err))
	}
}()
```

The `consumeLoop()` function returns a `context.Canceled` error when `Shutdown()` is called, which is expected. However `componentstatus.ReportStatus()` blocks while attempting to report this error. The reason/bug for this can be found [here](https://github.com/open-telemetry/opentelemetry-collector/issues/9824).

The previously mentioned PR fixed this for the traces receiver by checking if the error returned by `consumeLoop()` is `context.Canceled`:
```go
go func() {
	if err := c.consumeLoop(ctx, consumerGroup); !errors.Is(err, context.Canceled) {
		componentstatus.ReportStatus(host, componentstatus.NewFatalErrorEvent(err))
	}
}()
```

Additionally, this is `consumeLoop()` for the traces receiver, with the logs and metrics versions being identical:
```go
func (c *kafkaTracesConsumer) consumeLoop(ctx context.Context, handler sarama.ConsumerGroupHandler) error {
	for {
		// `Consume` should be called inside an infinite loop, when a
		// server-side rebalance happens, the consumer session will need to be
		// recreated to get the new claims
		if err := c.consumerGroup.Consume(ctx, c.topics, handler); err != nil {
			c.settings.Logger.Error("Error from consumer", zap.Error(err))
		}
		// check if context was cancelled, signaling that the consumer should stop
		if ctx.Err() != nil {
			c.settings.Logger.Info("Consumer stopped", zap.Error(ctx.Err()))
			return ctx.Err()
		}
	}
}
```

This does fix the issue, however the only error that can be returned by `consumeLoop()` is a canceled context. When we create the context and cancel function, we use `context.Background()`:
```go
ctx, cancel := context.WithCancel(context.Background())
```
This context is only used by `consumeLoop()` and the cancel function is only called in `Shutdown()`.

Because `consumeLoop()` can only return a `context.Canceled` error, this PR removes this unused code for the logs, metrics, and traces receivers. Instead, `consumeLoop()` still logs the `context.Canceled` error but it does not return any error and the go routine simply just calls `consumeLoop()`.

Additional motivation for removing the call to `componentstatus.ReportStatus()` is the underlying function called by it, `componentstatus.Report()` says it does not need to be called during `Shutdown()` or `Start()` as the service already does so for the given component, [comment here](https://github.com/open-telemetry/opentelemetry-collector/blob/main/component/componentstatus/status.go#L21-L25). Even if there wasn't a bug causing this call to block, the component still shouldn't call it since it would only be called during `Shutdown()`.

#### Link to tracking issue
Fixes #30789

#### Testing
Tested in a build of the collector with these changes scraping logs from a Kafka instance. When the collector is stopped and `Shutdown()` gets called, the receiver did not block and the collector stopped gracefully as expected.

### CODE REVIEW

**Comment by jsirianni** [comment]
Thanks for taking care of this, it resolves an issue we are seeing in production with a high throughput logs pipeline.

**Review by djaglowski — APPROVED** [review]

**Comment by djaglowski** [comment]
LGTM. @pavolloffay, @MovieStoreGuy, PTAL

File: receiver/kafkareceiver/kafka_receiver.go [hunk 1]
```diff
@@ -315,16 +309,12 @@ func (c *kafkaMetricsConsumer) Start(_ context.Context, host component.Host) err
 			headers: c.headers,
 		}
 	}
-	go func() {
-		if err := c.consumeLoop(ctx, metricsConsumerGroup); err != nil {
-			componentstatus.ReportStatus(host, componentstatus.NewFatalErrorEvent(err))
-		}
-	}()
+	go c.consumeLoop(ctx, metricsConsumerGroup)
```
Comment (MovieStoreGuy) [inline receiver/kafkareceiver/kafka_receiver.go:312]: I am a little nervous that this is creating a routine with no wait means that it could leak routines on shutdown, would this be something you're able to address within this PR?

**Review by MovieStoreGuy — COMMENTED** [review]
One comment from me trying to sneak in some improvements, but the changes seem sensible.

File: receiver/kafkareceiver/kafka_receiver.go (hunk 1 above)
Comment (dpaasman00) [reply receiver/kafkareceiver/kafka_receiver.go:321]: No problem!
