### PR TITLE
[reciever/splunkenterprise]46126 fix adhoc searches

### LINKED ISSUE #46126: [receiver/splunkenterprise] Ad-hoc search based metrics emit an empty record
### Component(s)

receiver/splunkenterprise

## Description
An issue in ad-hoc search based metrics. The logic which handles pagination is causing an extra call to the REST endpoint which retrieves search results causing duplicate metrics to be recorded and emitted.

This was first spotted in a comment [here](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/45409#discussion_r2748189873) and presents itself as extra records with the same recorded value as legitimate metrics but with none of the accompanying attributes.

## Steps to Reproduce
This can be seen easily when using the [golden](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/pkg/golden) package to record a scrape which happens across multiple pages of returned data.

## Expected Result
```yaml
- description: Gauge tracking the indexed license usage per index
            gauge:
              dataPoints:
                - asInt: "101"
                  attributes:
                    - key: splunk.index.name
                      value:
                        stringValue: "some_val1"
                    - key: splunk.splunkd.build
                      value:
                        stringValue: ""
                    - key: splunk.splunkd.version
                      value:
                        stringValue: ""
                  startTimeUnixNano: "1000000"
                  timeUnixNano: "2000000"
                - asInt: "100"
                  attributes:
                    - key: splunk.index.name
                      value:
                        stringValue: some_val2
                    - key: splunk.splunkd.build
                      value:
                        stringValue: ""
                    - key: splunk.splunkd.version
                      value:
                        stringValue: ""
                  startTimeUnixNano: "1000000"
                  timeUnixNano: "2000000"
            name: splunk.license.index.usage
            unit: By
```

## Actual Result
```yaml
- description: Gauge tracking the indexed license usage per index
            gauge:
              dataPoints:
                - asInt: "101"
                  attributes:
                    - key: splunk.index.name
                      value:
                        stringValue: ""
                    - key: splunk.splunkd.build
                      value:
                        stringValue: ""
                    - key: splunk.splunkd.version
                      value:
                        stringValue: ""
                  startTimeUnixNano: "1000000"
                  timeUnixNano: "2000000"
                - asInt: "100"
                  attributes:
                    - key: splunk.index.name
                      value:
                        stringValue: some_val2
                    - key: splunk.splunkd.build
                      value:
                        stringValue: ""
                    - key: splunk.splunkd.version
                      value:
                        stringValue: ""
                  startTimeUnixNano: "1000000"
                  timeUnixNano: "2000000"
            name: splunk.license.index.usage
            unit: By
```

### Collector version

v0.145.0

## Environment
OS: All

### OpenTelemetry Collector configuration

```yaml

```

### Log output

```shell

```

### Additional context

_No response_

### Tip

<sub>[React](https://github.blog/news-insights/product-news/add-reactions-to-pull-requests-issues-and-comments/) with 👍 to help prioritize this issue. Please use comments to provide useful context, avoiding `+1` or `me too`, to help us triage it. Learn more [here](https://opentelemetry.io/community/end-user/issue-participation/).</sub>

### PR DESCRIPTION
**Pull request by shalper2**
#### Description
Fixes a bug where ad-hoc searches would emit some metrics without attributes.

#### Link to tracking issue
Fixes [46126](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/46126)

#### Testing
Unit tests were expanded to better examine the scrape function for a search based metric

### CODE REVIEW

File: receiver/splunkenterprisereceiver/scraper.go [hunk 1]
```diff
@@ -280,7 +281,8 @@ func (s *splunkScraper) scrapeAvgExecLatencyByHost(_ context.Context, now pcommo
 		// the 200 is coming after the first request which provides a jobId to retrieve results
 		if sr.Return == 200 && sr.Jobid != nil {
 			fields = append(fields, sr.Fields...)
-			if sr.count >= sr.TotalCount.Count || sr.offset >= sr.TotalCount.Count {
+			sr.Fields = nil
+			if sr.count >= sr.TotalCount.Count || (sr.offset+sr.count) >= sr.TotalCount.Count {
```
Comment (dmitryax) [inline receiver/splunkenterprisereceiver/scraper.go]: `sr.offset+sr.count` must be always larger than `sr.count`, right? So we don't the first part `sr.count >= sr.TotalCount.Count || `

Comment (shalper2) [reply receiver/splunkenterprisereceiver/scraper.go]: right, nice catch. no longer have to separately account for the case where there is no need for pagination.

**Review by dmitryax — APPROVED** [review]
