### PR TITLE
[receiver/prometheusreceiver] fix stalness tracking

### LINKED ISSUE #43893: [receiver/prometheus] staleness markers aren't reported on failed scrapes after upgrade to 0.307.1
After upgrading Prometheus library to 0.307.1 in https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/43890 staleness markers aren't reported on failed scrapes. This causes some tests to fail. If it's expected the tests should be updated. If not, the issue should be pushed to prometheus project.

### PR DESCRIPTION
**Pull request by krajorama**
#### Description

In the dependency upgrade #43890 there was the PR
https://github.com/prometheus/prometheus/pull/16429 which changed the provisions for staleness tracking. Now the code only does the tracking if the series was successfully appended in storage. This is indicated by a non zero storage reference returned by the appender.

Since we used to return 0 in all cases, the staleness tracking is now broken.

Solution is to return a fake reference of 1, just to indicate success.

Alternative solution would be to make a unique reference for each series label set, but that incurs an overhead which we can avoid.

Performance impact: probably small as the cache should be stable over time - unless targets churn a lot between receiver instances.

Resource utilization: +1 hashmap with series identifier (name+labels) pointing to cache entries. Size related to number of series. `addRef` here: https://github.com/prometheus/prometheus/blob/c8f1de18a7870e5dc99ed50119c194691c41e41c/scrape/scrape.go#L1089

#### Link to tracking issue
Fixes #43893

#### Testing

Un-skip related tests.

### CODE REVIEW

File: exporter/prometheusexporter/end_to_end_test.go [hunk 1]
```diff
@@ -138,7 +138,7 @@ func TestEndToEndSummarySupport(t *testing.T) {
 		`test_scrape_samples_scraped.instance="127.0.0.1:.*",job="otel-collector",otel_scope_name=\"github.com/open-telemetry/opentelemetry-collector-contrib/receiver/prometheusreceiver\",otel_scope_schema_url=\"\",otel_scope_version=\"latest\". 13 .*`,
 		`. HELP test_scrape_series_added The approximate number of new series in this scrape`,
 		`. TYPE test_scrape_series_added gauge`,
-		`test_scrape_series_added.instance="127.0.0.1:.*",job="otel-collector",otel_scope_name=\"github.com/open-telemetry/opentelemetry-collector-contrib/receiver/prometheusreceiver\",otel_scope_schema_url=\"\",otel_scope_version=\"latest\". 13 .*`,
+		`test_scrape_series_added.instance="127.0.0.1:.*",job="otel-collector",otel_scope_name=\"github.com/open-telemetry/opentelemetry-collector-contrib/receiver/prometheusreceiver\",otel_scope_schema_url=\"\",otel_scope_version=\"latest\". (0|13) .*`,
```
Comment (krajorama) [inline exporter/prometheusexporter/end_to_end_test.go:141]: Note to reviewers: now we correctly tracking what series were added to "storage", i.e. successfully processed by the receiver. Which means that the number of series added is only 13 on the first scrape. Debug printf:
```
Running tool: /home/krajo/opt/go/bin/go test -timeout 30s -tags requires_docker,stringlabels -run ^TestEndToEndSummarySupport$ github.com/open-telemetry/opentelemetry-collector-contrib/exporter/prometheusexporter -timeout=5m

number of series added: 13
number of series added: 0
number of series added: 0
number of series added: 0
number of series added: 0
number of series added: 0
number of series added: 0
number of series added: 0
```

Comment (dashpole) [reply exporter/prometheusexporter/end_to_end_test.go:141]: oooh

**Review by dashpole — APPROVED** [review]
