### PR TITLE
loadbalancingexporter: add Start for exporters

### LINKED ISSUE #1621: loadbalancing: "sending_queue" causes OTLP exporter to not work
**Describe the bug**
I'm not quite sure if this is a real bug, but I will describe what I've found.

I set up the otel-agent with loadbalancing exporter as the [README](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/master/exporter/loadbalancingexporter/README.md) suggests. And I trigger a trace report through a simple jaeger-instrumented http app. The otel-collector, which is set up with logging exporter only, and supposed to log spans received to stdout, does not output anything. If I replace the loadbalancing exporter with a plain otlp exporter in otel-agent, everything goes well as expected.

So I guess there is something to do with loadbalancing exporter that make it fail to send the trace data out.

**Steps to reproduce**

1. write a custom distribution with the help of [this tutorial](https://medium.com/opentelemetry/building-your-own-opentelemetry-collector-distribution-42337e994b63).

2. Using the second example in loadbalancing exporter README with a little twist:

```yaml
receivers:
  jaeger/loadbalancer:
    protocols:
      thrift_compact:
        endpoint: localhost:6831
  otlp/loadbalancer:
    protocols:
      grpc:
        endpoint: localhost:55680
  otlp/backend-1:
    protocols:
      grpc:
        endpoint: localhost:55690
  otlp/backend-2:
    protocols:
      grpc:
        endpoint: localhost:55700
  otlp/backend-3:
    protocols:
      grpc:
        endpoint: localhost:55710
  otlp/backend-4:
    protocols:
      grpc:
        endpoint: localhost:55720

processors:

exporters:
  logging:
    loglevel: debug
  otlp:
    insecure: true
    endpoint: localhost:55690
  loadbalancing:
    protocol:
      otlp:
        timeout: 1s
        insecure: true
    resolver:
      static:
        hostnames:
          - localhost:55690
          - localhost:55700
          - localhost:55710
          - localhost:55720

service:
  pipelines:
    traces/loadbalancer:
      receivers:
        - otlp/loadbalancer
        - jaeger/loadbalancer
      processors: []
      exporters:
        - loadbalancing
#        - otlp
        - logging

    traces/backend-1:
      receivers:
        - otlp/backend-1
      processors: []
      exporters:
        - logging

    traces/backend-2:
      receivers:
        - otlp/backend-2
      processors: []
      exporters:
        - logging

    traces/backend-3:
      receivers:
        - otlp/backend-3
      processors: []
      exporters:
        - logging

    traces/backend-4:
      receivers:
        - otlp/backend-4
      processors: []
      exporters:
        - logging
```

3. set up a jaeger-instrumented http app.
4. trigger a http request and check the otel-backend's stdout.

**What did you expect to see?**

Because the same otel-collector acts as both agent and collector, there should be two set of trace data, one is due to the logging exporter in traces/loadbalancer pipeline, and the other is due to the logging exporter in any one of the four traces/backend pipelines.

**What did you see instead?**

Only to find one set of trace data. And If I open otlp exporter and comment out the loadbalancing exporter in the yaml config, I can see two sets of trace data.

**What version did you use?**

I ran the experiment in a go1.14 environment. Here are the package versions:

```
github.com/open-telemetry/opentelemetry-collector-contrib/exporter/loadbalancingexporter v0.14.1-0.20201113203156-50593285c23e
github.com/open-telemetry/opentelemetry-collector-contrib/processor/tailsamplingprocessor v0.14.1-0.20201113203156-50593285c23e
go.opentelemetry.io/collector v0.14.1-0.20201112191733-c6d9a2be2223
```

**What config did you use?**
Config: in *Steps to reproduce* section I've mentioned that.

**Environment**
OS: MacOS 10.15.6
Compiler(if manually compiled): "go 1.14"

**Additional context**

Here are the metrics:

```
# HELP otelcol_exporter_send_failed_spans Number of spans in failed attempts to send to destination.
# TYPE otelcol_exporter_send_failed_spans counter
otelcol_exporter_send_failed_spans{exporter="logging",service_instance_id="2fc3d209-3a14-4954-b484-dfcd43bb793d"} 0
# HELP otelcol_exporter_sent_spans Number of spans successfully sent to destination.
# TYPE otelcol_exporter_sent_spans counter
otelcol_exporter_sent_spans{exporter="logging",service_instance_id="2fc3d209-3a14-4954-b484-dfcd43bb793d"} 2
# HELP otelcol_loadbalancer_backend_latency Response latency in ms for the backends
# TYPE otelcol_loadbalancer_backend_latency histogram
otelcol_loadbalancer_backend_latency_bucket{endpoint="localhost:55720",service_instance_id="2fc3d209-3a14-4954-b484-dfcd43bb793d",le="5"} 2
otelcol_loadbalancer_backend_latency_bucket{endpoint="localhost:55720",service_instance_id="2fc3d209-3a14-4954-b484-dfcd43bb793d",le="10"} 2
otelcol_loadbalancer_backend_latency_bucket{endpoint="localhost:55720",service_instance_id="2fc3d209-3a14-4954-b484-dfcd43bb793d",le="20"} 2
otelcol_loadbalancer_backend_latency_bucket{endpoint="localhost:55720",service_instance_id="2fc3d209-3a14-4954-b484-dfcd43bb793d",le="50"} 2
otelcol_loadbalancer_backend_latency_bucket{endpoint="localhost:55720",service_instance_id="2fc3d209-3a14-4954-b484-dfcd43bb793d",le="100"} 2
otelcol_loadbalancer_backend_latency_bucket{endpoint="localhost:55720",service_instance_id="2fc3d209-3a14-4954-b484-dfcd43bb793d",le="200"} 2
otelcol_loadbalancer_backend_latency_bucket{endpoint="localhost:55720",service_instance_id="2fc3d209-3a14-4954-b484-dfcd43bb793d",le="500"} 2
otelcol_loadbalancer_backend_latency_bucket{endpoint="localhost:55720",service_instance_id="2fc3d209-3a14-4954-b484-dfcd43bb793d",le="1000"} 2
otelcol_loadbalancer_backend_latency_bucket{endpoint="localhost:55720",service_instance_id="2fc3d209-3a14-4954-b484-dfcd43bb793d",le="2000"} 2
otelcol_loadbalancer_backend_latency_bucket{endpoint="localhost:55720",service_instance_id="2fc3d209-3a14-4954-b484-dfcd43bb793d",le="5000"} 2
otelcol_loadbalancer_backend_latency_bucket{endpoint="localhost:55720",service_instance_id="2fc3d209-3a14-4954-b484-dfcd43bb793d",le="+Inf"} 2
otelcol_loadbalancer_backend_latency_sum{endpoint="localhost:55720",service_instance_id="2fc3d209-3a14-4954-b484-dfcd43bb793d"} 0
otelcol_loadbalancer_backend_latency_count{endpoint="localhost:55720",service_instance_id="2fc3d209-3a14-4954-b484-dfcd43bb793d"} 2
# HELP otelcol_loadbalancer_backend_outcome Number of success/failures for each endpoint
# TYPE otelcol_loadbalancer_backend_outcome counter
otelcol_loadbalancer_backend_outcome{endpoint="localhost:55720",service_instance_id="2fc3d209-3a14-4954-b484-dfcd43bb793d",success="true"} 2
# HELP otelcol_loadbalancer_num_backend_updates Number of times the list of backends was updated
# TYPE otelcol_loadbalancer_num_backend_updates counter
otelcol_loadbalancer_num_backend_updates{resolver="static",service_instance_id="2fc3d209-3a14-4954-b484-dfcd43bb793d"} 1
# HELP otelcol_loadbalancer_num_backends Current number of backends in use
# TYPE otelcol_loadbalancer_num_backends gauge
otelcol_loadbalancer_num_backends{resolver="static",service_instance_id="2fc3d209-3a14-4954-b484-dfcd43bb793d"} 4
# HELP otelcol_loadbalancer_num_resolutions Number of times the resolver triggered a new resolutions
# TYPE otelcol_loadbalancer_num_resolutions counter
otelcol_loadbalancer_num_resolutions{resolver="static",service_instance_id="2fc3d209-3a14-4954-b484-dfcd43bb793d",success="true"} 1
# HELP otelcol_process_cpu_seconds Total CPU user and system time in seconds
# TYPE otelcol_process_cpu_seconds gauge
otelcol_process_cpu_seconds{service_instance_id="2fc3d209-3a14-4954-b484-dfcd43bb793d"} 0.19
# HELP otelcol_process_memory_rss Total physical memory (resident set size)
# TYPE otelcol_process_memory_rss gauge
otelcol_process_memory_rss{service_instance_id="2fc3d209-3a14-4954-b484-dfcd43bb793d"} 2.9032448e+07
# HELP otelcol_process_runtime_heap_alloc_bytes Bytes of allocated heap objects (see 'go doc runtime.MemStats.HeapAlloc')
# TYPE otelcol_process_runtime_heap_alloc_bytes gauge
otelcol_process_runtime_heap_alloc_bytes{service_instance_id="2fc3d209-3a14-4954-b484-dfcd43bb793d"} 1.3994184e+07
# HELP otelcol_process_runtime_total_alloc_bytes Cumulative bytes allocated for heap objects (see 'go doc runtime.MemStats.TotalAlloc')
# TYPE otelcol_process_runtime_total_alloc_bytes gauge
otelcol_process_runtime_total_alloc_bytes{service_instance_id="2fc3d209-3a14-4954-b484-dfcd43bb793d"} 1.913936e+07
# HELP otelcol_process_runtime_total_sys_memory_bytes Total bytes of memory obtained from the OS (see 'go doc runtime.MemStats.Sys')
# TYPE otelcol_process_runtime_total_sys_memory_bytes gauge
otelcol_process_runtime_total_sys_memory_bytes{service_instance_id="2fc3d209-3a14-4954-b484-dfcd43bb793d"} 7.3482496e+07
# HELP otelcol_process_uptime Uptime of the process
# TYPE otelcol_process_uptime counter
otelcol_process_uptime{service_instance_id="2fc3d209-3a14-4954-b484-dfcd43bb793d"} 45.009423999999996
# HELP otelcol_receiver_accepted_spans Number of spans successfully pushed into the pipeline.
# TYPE otelcol_receiver_accepted_spans counter
otelcol_receiver_accepted_spans{receiver="jaeger/loadbalancer",service_instance_id="2fc3d209-3a14-4954-b484-dfcd43bb793d",transport="udp_thrift_compact"} 2
# HELP otelcol_receiver_refused_spans Number of spans that could not be pushed into the pipeline.
# TYPE otelcol_receiver_refused_spans counter
otelcol_receiver_refused_spans{receiver="jaeger/loadbalancer",service_instance_id="2fc3d209-3a14-4954-b484-dfcd43bb793d",transport="udp_thrift_compact"}
```
I did check the return values from otlp grpc sender when I use breakpoints to debug, everything looks fine, as we can see the counter values are what we expected. But only to find that otel-backend with logging exporter configured receive nothing.

Is there supposed to be a `otelcol_receiver_accepted_spans` with receiver being "otlp/backend-x"? That will make this more clear.

### PR DESCRIPTION
**Pull request by pkositsyn**
**Description:** 
Fixed a bug with not working loadbalancingexporter with retry queue. Also added sorting for endpoints on backend change (assume it is occasionally missing).

**Link to tracking Issue:** Fixes #1621 

**Testing:**
Added test for endpoints sort

### CODE REVIEW

**Comment by Vemmy124** [comment]
I don't know whether its ok to save host for later usage. @bogdandrutu Please verify that it's legal

**Comment by Vemmy124** [comment]
Also I think this kind of bug is really painful. Can we prevent such things in future? Introduce unified end-to-end test for every new receiver and exporter or something.

**Comment by bogdandrutu** [comment]
@Vemmy124 we don't have any concern for the moment about not keeping a reference to the host. So it is ok.

File: exporter/loadbalancingexporter/exporter.go [hunk 1]
```diff
@@ -120,7 +122,7 @@ func (e *exporterImp) Start(ctx context.Context, host component.Host) error {
 }
 
 func (e *exporterImp) onBackendChanges(resolved []string) {
-	resolved = sort.StringSlice(resolved)
```
Comment (jpkrohling) [inline exporter/loadbalancingexporter/exporter.go:123]: Are you seeing this list unsorted? This should be sorted by the resolver already, so, this call here is just for local safety. In any case, we shouldn't be changing the `resolved` argument.

File: exporter/loadbalancingexporter/exporter.go [hunk 2]
```diff
@@ -146,7 +148,11 @@ func (e *exporterImp) addMissingExporters(ctx context.Context, endpoints []strin
 			cfg := e.buildExporterConfig(endpoint)
 			exp, err := e.exporterFactory.CreateTracesExporter(ctx, e.templateCreateParams, &cfg)
 			if err != nil {
-				e.logger.Warn("failed to create new trace exporter for endpoint", zap.String("endpoint", endpoint))
+				e.logger.Error("failed to create new trace exporter for endpoint", zap.String("endpoint", endpoint), zap.Error(err))
+				continue
+			}
+			if err = exp.Start(ctx, e.host); err != nil {
```
Comment (jpkrohling) [inline exporter/loadbalancingexporter/exporter.go:154]: 🤦🏽 Great catch!

File: exporter/loadbalancingexporter/exporter.go (hunk 1 above)
Comment (Vemmy124) [reply exporter/loadbalancingexporter/exporter.go:123]: What was the purpose of the line I changed? It is not either sort of the strings and not a check that it is sorted. This line literally does nothing at the moment

Comment (jpkrohling) [reply exporter/loadbalancingexporter/exporter.go:123]: Another 🤦🏽, it's casting to the type `StringSlice` instead of actually calling a function that sorts the slice... 

Is the sort required here at all? This list should be sorted already by the backend anyway...

File: exporter/loadbalancingexporter/exporter.go (hunk 2 above)
Comment (ZhengHe-MD) [reply exporter/loadbalancingexporter/exporter.go:154]: that's why enabling sending_queue will prevent spans from being reported. 👍🏽

File: exporter/loadbalancingexporter/exporter.go (hunk 1 above)
Comment (Vemmy124) [reply exporter/loadbalancingexporter/exporter.go:123]: It is sorted in dns resolver but not in static resolver. I would add sort for static resolver and log error here if the slice isn't sorted, because this can lead to some problems that multiple loadbalancers (why not) are not synced in terms of endpoints

Comment (Vemmy124) [reply exporter/loadbalancingexporter/exporter.go:123]: By the way it's a nice feature that the hash is consistent among instances. Given that, there is a real possibility to move loadbalancer to agents instead of putting it to a separate collector. In my opinion it is not hard to support this useful behaviour

Comment (jpkrohling) [reply exporter/loadbalancingexporter/exporter.go:123]: We sort the backends in the DNS resolver because it's easier to determine whether the list changed. One edge case that it solves is that two endpoints resolving to the same angle in the ring would cause undetermined behavior on unsorted lists, so that updates to the same list could yield different results for the same angle. With a sorted list, we have a consistent view in this case as well.

For static backends, we don't need this, as the list is never changing, the view of the ring is always the same.

Comment (Vemmy124) [reply exporter/loadbalancingexporter/exporter.go:123]: If you don't believe, that one can do a mistake by using several exporters with different order of hosts in static resolver config, then I totally agree with you. Otherwise putting one line for sort not much of an issue to do in this PR

Comment (jpkrohling) [reply exporter/loadbalancingexporter/exporter.go:123]: I'd rather have this in a different PR. Keeping one PR per problem is good for sanity :-)

Comment (Vemmy124) [reply exporter/loadbalancingexporter/exporter.go:123]: At least I think that the order of hosts in static resolver config shouldn't affect the behaviour of exporter in any way

Comment (Vemmy124) [reply exporter/loadbalancingexporter/exporter.go:123]: Sure, I'll move these changes to a separate PR

**Comment by Vemmy124** [comment]
@jpkrohling Resolved the issue in the latest commit

**Review by jpkrohling — APPROVED** [review]

**Review by bogdandrutu — APPROVED** [review]
