### PR TITLE
[exporter/prometheusremotewrite] respect integer exemplar values

### LINKED ISSUE #36657: Prometheus remote write does not respect integer exemplar values
### Component(s)

exporter/prometheusremotewrite

## Description
It looks like the prometheus remote write exporter does not export exemplars correctly when the value of the exemplar is an int. [Looking at the code](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/2da211fcf335a8c030fe2359cfff22d37df8d1e3/pkg/translator/prometheusremotewrite/helper.go#L305), it seems to only extract the double value, regardless of whether or not it, or the int value was set.

## Steps to Reproduce
Send metrics with exemplars that have int values, and then some that have double values, where the values != 0.

## Expected Result

Either int value exemplars or double value exemplars are written to the prometheus remote write backend

## Actual Result
Both kinds of exemplars are written, but the "Value" attribute of int exemplars is always 0.

### Collector version

v0.114.0

## Environment
latest otel contrib docker image

### OpenTelemetry Collector configuration

_No response_

### Log output

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by perebaj**
#### Description

Fixing when exemplars receive values that aren't doubles

#### Link to tracking issue
Fixes https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/36657

### CODE REVIEW

File: pkg/translator/prometheusremotewrite/testutils_test.go [hunk 1]
```diff
@@ -212,6 +212,34 @@ func getHistogramDataPointWithExemplars(t *testing.T, time time.Time, value floa
 	return h
 }
 
+// getHistogramDataPointWithExemplarsInt returns a HistogramDataPoint populating the exemplar with an int64 value.
+func getHistogramDataPointWithExemplarsInt(t *testing.T, time time.Time, value int64, traceID string, spanID string, attributeKey string, attributeValue string) pmetric.HistogramDataPoint {
```
Comment (perebaj) [inline pkg/translator/prometheusremotewrite/testutils_test.go:216]: I basically copy/paste the content of this function ⬇️

https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/dd600c17034e1e4cbee80a07274b65777fdf9eda/pkg/translator/prometheusremotewrite/testutils_test.go#L187

But changing the signature to receive an `int64` value instead of a `float64` one. Does this make sense?

I'm also added a comment in the top of the function, but I notice that most of the private functions doesnt have an comment, should I keep it?

Comment (ArthurSens) [reply pkg/translator/prometheusremotewrite/testutils_test.go:216]: Maybe this is a good use case for [generics](https://go.dev/doc/tutorial/generics)?

```go
func getHistogramDataPointWithExemplars[V int64 | float64](t *testing.T, time time.Time, value V, traceID string, spanID string, attributeKey string, attributeValue string) pmetric.HistogramDataPoint {
.
.
.
    switch V.(type) {
    case int64:
        e.SetIntValue(value)
    case float64:
        e.SetDoubleValue(value)
    }
.
.
.
}
```

We could avoid a little bit of code and the change is not thaaaat big to the original function

Comment (perebaj) [reply pkg/translator/prometheusremotewrite/testutils_test.go]: [7644383](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/36688/commits/76443830b483d3f945cf291faa1e68e2a04ca694)

I removed the new helper function that I created, and I added the `generic` that you mentioned in the existing function

**Comment by ArthurSens** [comment]
Nice, the only thing left is a changelog entry. When doing a release of this project we compile all files located in this [folder](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/.chloggen). You can copy one as an example, change it to represent what is being fixed in this PR, and commit :)

File: pkg/translator/prometheusremotewrite/helper.go [hunk 2]
```diff
@@ -301,9 +301,17 @@ func getPromExemplars[T exemplarType](pt T) []prompb.Exemplar {
 		exemplar := pt.Exemplars().At(i)
 		exemplarRunes := 0
 
-		promExemplar := prompb.Exemplar{
-			Value:     exemplar.DoubleValue(),
-			Timestamp: timestamp.FromTime(exemplar.Timestamp().AsTime()),
+		var promExemplar prompb.Exemplar
+		if exemplar.ValueType() == pmetric.ExemplarValueTypeInt {
```
Comment (dashpole) [inline pkg/translator/prometheusremotewrite/helper.go:305]: can we use a `switch` on `exemplar.ValueType()` instead of two if-statements?

Comment (perebaj) [reply pkg/translator/prometheusremotewrite/helper.go]: addressed

[d1eb42d](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/36688/commits/d1eb42d18c4efeefdb1f03f96c2c5a27b899b917)

**Review by dashpole — APPROVED** [review]

**Comment by perebaj** [comment]
Hey guys @ArthurSens @dashpole, feel free to tag me in any kind of issue that you think would be interesting to solve

I'm open to help and learn more about this ecosystem! 🙃

File: pkg/translator/prometheusremotewrite/testutils_test.go [hunk 3]
```diff
@@ -184,11 +184,16 @@ func getTimeSeriesWithSamplesAndExemplars(labels []prompb.Label, samples []promp
 	}
 }
 
-func getHistogramDataPointWithExemplars(t *testing.T, time time.Time, value float64, traceID string, spanID string, attributeKey string, attributeValue string) pmetric.HistogramDataPoint {
+func getHistogramDataPointWithExemplars[V int64 | float64](t *testing.T, time time.Time, value V, traceID string, spanID string, attributeKey string, attributeValue string) pmetric.HistogramDataPoint {
 	h := pmetric.NewHistogramDataPoint()
 
 	e := h.Exemplars().AppendEmpty()
-	e.SetDoubleValue(value)
+	switch v := (interface{})(value).(type) {
```
Comment (evan-bradley) [inline pkg/translator/prometheusremotewrite/testutils_test.go:191]:
```suggestion
	switch v := (any)(value).(type) {
```
Not sure why the formatter didn't catch this, but I'm pretty sure we're standardizing on `any` instead of `interface{}` throughout the repository. Would this work here?

Comment (perebaj) [reply pkg/translator/prometheusremotewrite/testutils_test.go]: @evan-bradley this decision is just related to a style thing or is something else?

Comment (evan-bradley) [reply pkg/translator/prometheusremotewrite/testutils_test.go]: It's stylistic, yeah. I believe `any` and `interface{}` are exactly equivalent, `any` is just a shorter and clearer name.

**Review by evan-bradley — APPROVED** [review]
Thanks @perebaj!

File: pkg/translator/prometheusremotewrite/testutils_test.go (hunk 3 above)
Comment (perebaj) [reply pkg/translator/prometheusremotewrite/testutils_test.go]: Do you think that would be nice to investigate why the lint didn't pop up any constraint about it?
