### PR TITLE
[exporter/prometheus] Expose native histograms

### LINKED ISSUE #33703: [prometheusexporter] Expose native histograms
### Component(s)

exporter/prometheus

## Description

Currently, `prometheusreceiver` [supports](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/receiver/prometheusreceiver/README.md#prometheus-native-histograms) native histograms, but `prometheusexporter` cannot expose them (because Prometheus cannot expose native histograms in text format yet).

## Steps to Reproduce

1. Instrument your code with native histograms
2. Scrape the metrics with `prometheusreceiver` by following the instructions here: https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/f5d54da37ae664e1a0b6934a61d38f1afab5501f/receiver/prometheusreceiver/README.md#prometheus-native-histograms

## Expected Result

`prometheusexporter` should expose native histograms

## Actual Result

Logs via `debugexporter`:
```
{"level":"error","ts":1718965637.50062,"caller":"prometheusexporter@v0.103.0/accumulator.go:94","msg":"failed to translate metric","kind":"exporter","data_type":"metrics","name":"prometheus","data_type":"\u0004","metric_name":"gloo_mesh_translation_time_sec","stacktrace":"github.com/open-telemetry/opentelemetry-collector-contrib/exporter/prometheusexporter.(*lastValueAccumulator).addMetric
\tgithub.com/open-telemetry/opentelemetry-collector-contrib/exporter/prometheusexporter@v0.103.0/accumulator.go:94
github.com/open-telemetry/opentelemetry-collector-contrib/exporter/prometheusexporter.(*lastValueAccumulator).Accumulate
\tgithub.com/open-telemetry/opentelemetry-collector-contrib/exporter/prometheusexporter@v0.103.0/accumulator.go:71
github.com/open-telemetry/opentelemetry-collector-contrib/exporter/prometheusexporter.(*collector).processMetrics
\tgithub.com/open-telemetry/opentelemetry-collector-contrib/exporter/prometheusexporter@v0.103.0/collector.go:88
github.com/open-telemetry/opentelemetry-collector-contrib/exporter/prometheusexporter.(*prometheusExporter).ConsumeMetrics
\tgithub.com/open-telemetry/opentelemetry-collector-contrib/exporter/prometheusexporter@v0.103.0/prometheus.go:85
go.opentelemetry.io/collector/exporter/exporterhelper.(*metricsRequest).Export
\tgo.opentelemetry.io/collector/exporter@v0.103.0/exporterhelper/metrics.go:59
go.opentelemetry.io/collector/exporter/exporterhelper.(*timeoutSender).send
\tgo.opentelemetry.io/collector/exporter@v0.103.0/exporterhelper/timeout_sender.go:49
go.opentelemetry.io/collector/exporter/exporterhelper.(*baseRequestSender).send
\tgo.opentelemetry.io/collector/exporter@v0.103.0/exporterhelper/common.go:37
go.opentelemetry.io/collector/exporter/exporterhelper.(*metricsSenderWithObservability).send
\tgo.opentelemetry.io/collector/exporter@v0.103.0/exporterhelper/metrics.go:158
--
```

### Collector version

v0.103.0

### Environment information

N/A

### OpenTelemetry Collector configuration

```yaml
receivers:
  prometheus:
    config:
      global:
        evaluation_interval: 1m
        scrape_interval: 15s
        scrape_timeout: 15s
        scrape_protocols: [ PrometheusProto, OpenMetricsText1.0.0, OpenMetricsText0.0.1, PrometheusText0.0.4 ]
        scrape_configs:
          <your targets exposing native histograms>
          ...
pipelines:
  metrics/test:
    receivers:
    - prometheus
    exporters:
    - debug
    - prometheus
```

### Log output

```shell
{"level":"error","ts":1718965637.50062,"caller":"prometheusexporter@v0.103.0/accumulator.go:94","msg":"failed to translate metric","kind":"exporter","data_type":"metrics","name":"prometheus","data_type":"\u0004","metric_name":"gloo_mesh_translation_time_sec","stacktrace":"github.com/open-telemetry/opentelemetry-collector-contrib/exporter/prometheusexporter.(*lastValueAccumulator).addMetric
\tgithub.com/open-telemetry/opentelemetry-collector-contrib/exporter/prometheusexporter@v0.103.0/accumulator.go:94
github.com/open-telemetry/opentelemetry-collector-contrib/exporter/prometheusexporter.(*lastValueAccumulator).Accumulate
\tgithub.com/open-telemetry/opentelemetry-collector-contrib/exporter/prometheusexporter@v0.103.0/accumulator.go:71
github.com/open-telemetry/opentelemetry-collector-contrib/exporter/prometheusexporter.(*collector).processMetrics
\tgithub.com/open-telemetry/opentelemetry-collector-contrib/exporter/prometheusexporter@v0.103.0/collector.go:88
github.com/open-telemetry/opentelemetry-collector-contrib/exporter/prometheusexporter.(*prometheusExporter).ConsumeMetrics
\tgithub.com/open-telemetry/opentelemetry-collector-contrib/exporter/prometheusexporter@v0.103.0/prometheus.go:85
go.opentelemetry.io/collector/exporter/exporterhelper.(*metricsRequest).Export
\tgo.opentelemetry.io/collector/exporter@v0.103.0/exporterhelper/metrics.go:59
go.opentelemetry.io/collector/exporter/exporterhelper.(*timeoutSender).send
\tgo.opentelemetry.io/collector/exporter@v0.103.0/exporterhelper/timeout_sender.go:49
go.opentelemetry.io/collector/exporter/exporterhelper.(*baseRequestSender).send
\tgo.opentelemetry.io/collector/exporter@v0.103.0/exporterhelper/common.go:37
go.opentelemetry.io/collector/exporter/exporterhelper.(*metricsSenderWithObservability).send
\tgo.opentelemetry.io/collector/exporter@v0.103.0/exporterhelper/metrics.go:158
--
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by MoreraAlejandro**
## Summary

This PR adds support for OpenTelemetry ExponentialHistogram metrics in the prometheusexporter.
Before this change, the Collector could ingest Prometheus native histograms through prometheusreceiver, convert them into OTel ExponentialHistogram internally, and then fail when re-exposing them through prometheusexporter. In practice, pipelines like:prometheusreceiver -> processors -> prometheusexporter would log translation errors and drop those metrics at export time.
With this PR, prometheusexporter can now handle ExponentialHistogram metrics instead of rejecting them as unsupported, allowing native histogram data to flow end to end through the Collector.

## Problem

The gap fixed here was not on ingestion, but on export. prometheusreceiver already supports scraping Prometheus native histograms and maps them to OTel ExponentialHistogram data points. However, prometheusexporter did not support exporting that metric type, which resulted in errors similar to:

  - unsupported metric type: ExponentialHistogram

That meant users could successfully scrape native histograms into the Collector, but could not expose them again from the Collector using the Prometheus exporter.

## Changes in this PR

  This PR updates prometheusexporter so it can process and expose ExponentialHistogram metrics.

  Concretely, the change does the following:

  - adds handling for pmetric.ExponentialHistogram in the Prometheus exporter translation/export path
  - removes the previous failure mode where exponential histograms were treated as unsupported
  - enables end-to-end support for Prometheus native histogram ingestion followed by Prometheus re-exposition
  - aligns exporter behavior with the metric types that can already be produced internally by the Collector from Prometheus native histogram input

## Behavior Before

  Before this PR:

  - Prometheus native histograms could be scraped by prometheusreceiver
  - those metrics were converted into OTel ExponentialHistogram
  - prometheusexporter failed to translate them
  - the exporter logged errors and the metrics were not exposed

## Behavior After

  After this PR:

  - Prometheus native histograms can still be scraped by prometheusreceiver
  - the resulting OTel ExponentialHistogram metrics are now accepted by prometheusexporter
  - the exporter exposes those metrics instead of failing translation
  - pipelines using native histograms no longer lose those metrics at the exporter boundary

## Why this matters

This closes an interoperability gap in Collector pipelines that both ingest and expose Prometheus metrics. Without this change, native histogram support was only partial: ingestion worked, but re-export did not. This PR makes that flow consistent and allows users to preserve histogram data across Collector pipelines.

## Compatibility / Scope

  This change is additive.

  - Existing supported metric types are unaffected.
  - The behavior changes only for ExponentialHistogram metrics, which previously failed export.
  - Users not using Prometheus native histograms should see no behavior change.
  - Users ingesting native histograms should see failed exports become successful exports.

## Important Note

Prometheus native histogram support depends on protocol/exposition compatibility on the scraping side as well. This PR adds exporter support for the metric type; it does not change the broader Prometheus protocol constraints around how native histograms are represented and negotiated.

## Follow-ups

This PR focuses on enabling support in prometheusexporter. Follow-up work may still be useful in these areas:

  - add or expand end-to-end tests covering prometheusreceiver -> prometheusexporter with native histograms
  - document any protocol/exposition expectations for consumers scraping native histograms from the exporter
  - clarify fallback behavior, if any, when the scraping side does not support native histogram-capable exposition
  - validate and document behavior for edge cases such as sparse buckets, zero bucket handling, exemplars, and schema/scale conversion details

Closes #33703

### CODE REVIEW

**Comment by MoreraAlejandro** [comment]
~This PR is still under development. That is why it contains that amount of logs and stuff. It is still not ready, I'm sharing it so you can have visibility over my work here, but it needs a lot of work~

File: exporter/prometheusexporter/collector.go [hunk 1]
```diff
@@ -180,18 +162,97 @@ func (c *collector) convertMetric(metric pmetric.Metric, resourceAttrs pcommon.M
...
+	if dp.StartTimestamp().AsTime().Unix() > 0 {
+		created = dp.StartTimestamp().AsTime()
 	}
+
+	sumVal := 0.0
+	if dp.HasSum() {
+		sumVal = dp.Sum()
+	}
+
+	m, err := prometheus.NewConstNativeHistogram(
```
Comment (MoreraAlejandro) [inline exporter/prometheusexporter/collector.go:261]: as there is no `NewConstSummaryWithCreatedTimestamp`, I have decided to set timestamp to the zero time. I don't know if this is what I should do, so if anybody has a strong opinion here, I'm open to hear it

File: exporter/prometheusexporter/collector.go [hunk 2]
```diff
@@ -180,18 +162,97 @@ func (c *collector) convertMetric(metric pmetric.Metric, resourceAttrs pcommon.M
...
+
+	// Build metadata/labels first.
+	desc, attributes, err := c.getMetricMetadata(metric, dto.MetricType_HISTOGRAM.Enum(), dp.Attributes(), resourceAttrs, scopeName, scopeVersion, scopeSchemaURL, scopeAttributes)
 	if err != nil {
-		return nil, nil, err
+		return nil, err
+	}
+
+	schema := dp.Scale()
+	if schema < -4 {
```
Comment (MoreraAlejandro) [inline exporter/prometheusexporter/collector.go:233]: I have seen the [exception about the -53 schema](https://prometheus.io/docs/specs/native_histograms/#schema). Should we handle this also in this MR? In that case, I am not fully understanding what I should do here. I guess just creating an Histogram, but not sure where to extract the rest of the information needed though.

**Comment by MoreraAlejandro** [comment]
Could please anybody review this? @dashpole @ArthurSens I'm pinging you since you were the ones assigned to this PR, however feel free to ping/notify whoever you think should be aware of this.

File: exporter/prometheusexporter/accumulator.go [hunk 3]
```diff
@@ -402,3 +474,125 @@ func accumulateHistogramValues(prev, current, dest pmetric.HistogramDataPoint) {
 
 	dest.ExplicitBounds().FromRaw(newer.ExplicitBounds().AsRaw())
 }
+
+func accumulateExponentialHistogramValues(prev, current, dest pmetric.ExponentialHistogramDataPoint) {
+	older := prev
+	newer := current
```
Comment (dashpole) [inline exporter/prometheusexporter/accumulator.go]: nit: Do you need to alias these?  It makes the code below harder to read if there are two names for older/prev or newer/current.

File: exporter/prometheusexporter/accumulator.go [hunk 4]
```diff
@@ -402,3 +474,125 @@ func accumulateHistogramValues(prev, current, dest pmetric.HistogramDataPoint) {
...
+	dest.Negative().BucketCounts().FromRaw(mNegCounts)
+
+	dest.SetZeroCount(prev.ZeroCount() + current.ZeroCount())
+	dest.SetCount(prev.Count() + current.Count())
+
+	zt := prev.ZeroThreshold()
+	if current.ZeroThreshold() > zt {
+		zt = current.ZeroThreshold()
+	}
+	dest.SetZeroThreshold(zt)
```
Comment (dashpole) [inline exporter/prometheusexporter/accumulator.go]: When merging exp histograms with different zero thresholds, you need to remove buckets from the point with the lower threshold if the bucket falls below the new zero threshold.  I.e. if the new zero threshold is 1.0, you would need to take all buckets that fall entirely below 1.0, and move their count into the zero count.

If you don't want to handle that in this PR, you can drop the point if the Zero threshold differs, and add a TODO with a follow-up issue.

File: exporter/prometheusexporter/accumulator.go [hunk 5]
```diff
@@ -402,3 +474,125 @@ func accumulateHistogramValues(prev, current, dest pmetric.HistogramDataPoint) {
...
+
+	if prev.HasSum() || current.HasSum() {
```
Comment (dashpole) [inline exporter/prometheusexporter/accumulator.go]:
```suggestion
	if prev.HasSum() && current.HasSum() {
```

From https://github.com/open-telemetry/opentelemetry-proto/blob/d53c5c6fca40cba8d5d5cc4db0d719a07be927f8/opentelemetry/proto/metrics/v1/metrics.proto#L549:

> Note: Sum should only be filled out when measuring non-negative discrete events, and is assumed to be monotonic over the values of these events. Negative events *can* be recorded, but sum should not be filled out when doing so.  This is specifically to enforce compatibility w/ OpenMetrics, see: https://github.com/prometheus/OpenMetrics/blob/v1.0.0/specification/OpenMetrics.md#histogram

Basically, if one of the points does not have a sum, it means that negative observations are included in the population.  That means we can only fill out the sum if both points have the sum field set.

File: exporter/prometheusexporter/accumulator.go [hunk 6]
```diff
@@ -402,3 +474,125 @@ func accumulateHistogramValues(prev, current, dest pmetric.HistogramDataPoint) {
...
+		case prev.HasMin() && current.HasMin():
+			dest.SetMin(min(prev.Min(), current.Min()))
+		case prev.HasMin():
+			dest.SetMin(prev.Min())
+		case current.HasMin():
+			dest.SetMin(current.Min())
+		}
+	}
+
+	if prev.HasMax() || current.HasMax() {
```
Comment (dashpole) [inline exporter/prometheusexporter/accumulator.go]: nit: I don't think the if-statement is needed, given the switch statements below ("do nothing" is covered by the default case).  Same applies for min above

File: exporter/prometheusexporter/accumulator.go [hunk 7]
```diff
@@ -402,3 +474,125 @@ func accumulateHistogramValues(prev, current, dest pmetric.HistogramDataPoint) {
...
+	last := offset + int32(len(counts)) - 1
+	newOffset := floorDivInt32(first, factor)
+	newLast := floorDivInt32(last, factor)
+	newLen := int(newLast - newOffset + 1)
+	out := make([]uint64, newLen)
+	for i := range counts {
+		k := offset + int32(i)
+		nk := floorDivInt32(k, factor)
+		out[nk-newOffset] += counts[i]
+	}
```
Comment (dashpole) [inline exporter/prometheusexporter/accumulator.go]: It is possible to do this in-place, which avoids allocating another slice.  But what you have is correct, so you can add a TODO if you don't want to do that in this PR.

File: exporter/prometheusexporter/accumulator.go [hunk 8]
```diff
@@ -402,3 +474,125 @@ func accumulateHistogramValues(prev, current, dest pmetric.HistogramDataPoint) {
...
+	return newOffset, out
+}
+
+func mergeBuckets(offsetA int32, countsA []uint64, offsetB int32, countsB []uint64) (int32, []uint64) {
```
Comment (dashpole) [inline exporter/prometheusexporter/accumulator.go:623]: you can probably simplify some of the `if` statements below by returning countsA if countsB is empty, or vice-versa.

File: exporter/prometheusexporter/collector.go (hunk 2 above)
Comment (dashpole) [reply exporter/prometheusexporter/collector.go:233]: You can drop the point and add a TODO if scale is -53 for now.  We should convert those points to fixed-bucket histograms, but that is a significant change.  Those kinds of histograms are called "CBNH", or "custom bucket native histograms"

File: exporter/prometheusexporter/collector.go (hunk 1 above)
Comment (dashpole) [reply exporter/prometheusexporter/collector.go:261]: Why do we need `NewConstSummaryWithCreatedTimestamp`? Do you mean `NewConstNativeHistogramWithCreatedTimestamp`?

Comment (MoreraAlejandro) [reply exporter/prometheusexporter/collector.go:261]: Yep, sorry, that is what I meant

File: exporter/prometheusexporter/accumulator.go (hunk 3 above)
Comment (MoreraAlejandro) [reply exporter/prometheusexporter/accumulator.go]: I'll give it another thought, but yes, agree with you

File: exporter/prometheusexporter/collector.go (hunk 1 above)
Comment (dashpole) [reply exporter/prometheusexporter/collector.go:261]: We should open an issue upstream and ask for it.

File: exporter/prometheusexporter/collector.go [hunk 9]
```diff
@@ -162,13 +162,103 @@ func (c *collector) convertMetric(metric pmetric.Metric, resourceAttrs pcommon.M
...
 	}
 
 	return nil, errUnknownMetricType
 }
 
+// defaultZeroThreshold matches the remote-write translator's default for native histograms
+// when an explicit zero threshold is not provided in the datapoint.
+const (
+	defaultZeroThreshold = 1e-128
+	CBNHScale            = -53
```
Comment (dashpole) [inline exporter/prometheusexporter/collector.go]: can you make this lower-cased so it isn't part of the public API of the package?

File: exporter/prometheusexporter/collector.go (hunk 1 above)
Comment (dashpole) [reply exporter/prometheusexporter/collector.go:261]: Ah, NVM.  Zero should be fine.

**Review by dashpole — APPROVED** [review]

File: exporter/prometheusexporter/collector.go (hunk 9 above)
Comment (MoreraAlejandro) [reply exporter/prometheusexporter/collector.go]: yep, my bad, didn't notice

**Comment by ArthurSens** [comment]
Could take a look at the linting and test failures? Looks like even tests are failing due to bad file formatting 🤔

**Comment by MoreraAlejandro** [comment]
> Could take a look at the linting and test failures? Looks like even tests are failing due to bad file formatting 🤔

I don't know why `make fmt` and `make lint` didn't do the trick. Maybe mismatching versions IDK. Taking a look to the CI now though. Sorry for the noise

**Comment by MoreraAlejandro** [comment]
I am getting errors in the CI about generated data, but I have ran `make generate` and I have no changes. Also the output from `make chlog-validate` is: `PASS: all files in /Users/alejandromorera/Developer/cncf/opentelemetry-collector-contrib-tb/.chloggen/ are valid`. I'll take a look to the CI, but not really understanding what is going on here

**Comment by atoulme** [comment]
`no space left on device` - please rebase off latest main to pick a fix for this issue.

**Comment by ArthurSens** [comment]
Failing tests look unrelated. I'm retriggering them, hoping that it's only a flaky 🤞

**Comment by MoreraAlejandro** [comment]
> Failing tests look unrelated. I'm retriggering them, hoping that it's only a flaky 🤞

Seems it is still failing, I'll take a look this evening. Sorry for the low activity, I've been busy these days

**Comment by ArthurSens** [comment]
I'm pretty sure the scoped tests are not related to the changes in this PR. [I'm seeing them fail in several places](https://cloud-native.slack.com/archives/C07CCCMRXBK/p1764009909606089).

**Comment by ArthurSens** [comment]
Could you rebase on main again, https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/44485 should have done the trick 🤞

**Review by atoulme — APPROVED** [review]
LGTM, approved by codeowner, merging
