### PR TITLE
[pkg/ottl] adapt `mapGetter` to handle nested map items within slices

### LINKED ISSUE #37405: [pkg/ottl] Map literals within slices can not be parsed
### Component(s)

pkg/ottl

## Description

Currently, it is not possible to pass a slice containing map literals to OTTL. This is because the mapGetter returns a `pcommon.Map` instead of a `map[string]any`: https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/8034e0d160b0591a97a8d1618b7062dad2a226ac/pkg/ottl/expression.go#L196-L199

If a map literal then happens to be within a slice, eventually the `pcommon.Slice.FromRaw()` method will be invoked, which however only can handle raw types for its elements: https://github.com/open-telemetry/opentelemetry-collector/blob/6740a28a8003a534c20c2608d760edd015657622/pdata/pcommon/value.go#L134-L178

## Steps to Reproduce

Start the collector with the following config:

```
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
processors:
  transform:
    error_mode: ignore
    trace_statements:
      - context: span
        statements:
          - set(attributes["test"], {"list":[{"foo":"bar"}]})

exporters:
  debug:
    verbosity: detailed

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [transform]
      exporters: [debug]
```

And send some test data to it, e.g. with `telemetrygen`:

```
telemetrygen traces --otlp-insecure --traces 1 --status-code Ok --span-duration 1s
```

## Expected Result

The `test` attribute should be added to the span

## Actual Result

The attribute is not added, due to the following error logged by the collector:

```
ottl/parser.go:365      failed to execute statement     {"kind": "processor", "name": "transform", "pipeline": "traces", "error": "<Invalid value type pcommon.Map>", "statement": "set(attributes[\"test\"], {\"list\":[{\"foo\":\"bar\"}]})"}
```

### Collector version

v0.117.0

## Environment
OS: macOS
Compiler(if manually compiled): go 1.22

### OpenTelemetry Collector configuration

```yaml
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
processors:
  transform:
    error_mode: ignore
    trace_statements:
      - context: span
        statements:
          - set(attributes["test"], {"list":[{"foo":"bar"}]})

exporters:
  debug:
    verbosity: detailed

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [transform]
      exporters: [debug]
```

### Log output

```shell

```

### Additional context

I already have a draft for a fix ready that I can provide

### PR DESCRIPTION
**Pull request by bacherfl**
#### Description

This PR fixes the limitations described in #37405. The recently introduced `ValueExpression` had to be adapted, and will now only return raw types, instead of their `pcommon.Map`/`pcommon.Slice` eqivalents, as suggested in https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/37280#discussion_r1924238467 

#### Link to tracking issue
Fixes #37405 

#### Testing

Adapted and extended the unit and e2e tests

### CODE REVIEW

**Comment by bacherfl** [comment]
Converting back to draft for now, due to https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/37280#discussion_r1925483223

File: pkg/ottl/parser.go [hunk 1]
```diff
@@ -480,6 +481,19 @@ func (p *Parser[K]) ParseValueExpression(raw string) (*ValueExpression[K], error
 	}
 
 	return &ValueExpression[K]{
-		getter: getter,
+		getter: &StandardGetSetter[K]{
```
Comment (edmocosta) [inline pkg/ottl/parser.go:484]: If we end up stick to this approach, considering the `mapGetter` is now returning `pcommon.Map` values, I think we could keep it consistent and remove these changes, so all maps would still be parsed as`pcommon.Map` instead of raw values. I guess it would be a breaking change, though. WDYT?

**Comment by bacherfl** [comment]
@TylerHelmuth @evan-bradley this should be ready for reviews - can you also take a look please?

File: .chloggen/ottl-nested-map-literals.yaml [hunk 2]
```diff
@@ -0,0 +1,27 @@
+# Use this changelog template to create an entry for release notes.
+
+# One of 'breaking', 'deprecation', 'new_component', 'enhancement', 'bug_fix'
+change_type: bug_fix
+
+# The name of the component, or a single word describing the area of concern, (e.g. filelogreceiver)
+component: pkg/ottl
+
+# A brief description of the change.  Surround your text with quotes ("") if it needs to start with a backtick (`).
+note: Fix limitation of map literals within slices not being handled correctly
```
Comment (evan-bradley) [inline .chloggen/ottl-nested-map-literals.yaml:10]:
```suggestion
note: Fix limitation of map literals within slice literals not being handled correctly
```

File: pkg/ottl/e2e/e2e_test.go [hunk 3]
```diff
@@ -1041,6 +1041,22 @@ func Test_e2e_converters(t *testing.T) {
...
+		{
+			statement: `set(attributes["test"], {"list":[{"foo":"bar"}]})`,
+			want: func(tCtx ottllog.TransformContext) {
+				m := tCtx.GetLogRecord().Attributes().PutEmptyMap("test")
+				m2 := m.PutEmptySlice("list").AppendEmpty().SetEmptyMap()
+				m2.PutStr("foo", "bar")
+			},
+		},
+		{
+			statement: `set(attributes, {"list":[{"foo":"bar"}]})`,
```
Comment (evan-bradley) [inline pkg/ottl/e2e/e2e_test.go:1053]: Could you add a test that has top-level slice literals? For example:

```
set(attributes["arr"], [{"list":[{"foo":"bar"}]}, {"bar":"baz"}])
```

File: pkg/ottl/expression.go [hunk 4]
```diff
@@ -180,23 +181,37 @@ type mapGetter[K any] struct {
...
 		if err != nil {
 			return nil, err
 		}
-		switch t := val.(type) {
+		switch typedVal := val.(type) {
 		case pcommon.Map:
-			evaluated[k] = t.AsRaw()
+			target := result.PutEmpty(k).SetEmptyMap()
+			typedVal.CopyTo(target)
+		case []any:
```
Comment (evan-bradley) [inline pkg/ottl/expression.go:194]: Should we handle `pcommon.Slice` or other array types as well?

**Review by evan-bradley — COMMENTED** [review]
Sorry for the long delay @bacherfl. This one is a little tricky, I keep wanting to think long about it and forgetting to come back.

File: pkg/ottl/parser.go (hunk 1 above)
Comment (evan-bradley) [reply pkg/ottl/parser.go:484]: Judging by https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/37280#discussion_r1925483223, we probably need to survey this a bit more to make sure we're either consistent everywhere, or can translate at any given point in the chain. I'm not sure I have a strong opinion here, but it sounds like at a minimum we could potentially use more tests.

Do the same issues apply to slices with `[]any` vs. `pcommon.Slice`?

File: pkg/ottl/expression.go (hunk 4 above)
Comment (bacherfl) [reply pkg/ottl/expression.go:194]: This should not be required here, as internally the `newGetter` will return a `listGetter` for list items, which then returns `[]any`

File: pkg/ottl/parser.go (hunk 1 above)
Comment (bacherfl) [reply pkg/ottl/parser.go:484]: for slices, this issue doesn't apply, as the `listGetter` returns `[]any` as opposed to `pcommon.Slice`:

https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/ee2d1650b814fb3e2f733baa969b1d495ad78c8d/pkg/ottl/expression.go#L164-L176

File: pkg/ottl/expression.go (hunk 4 above)
Comment (bacherfl) [reply pkg/ottl/expression.go:194]: ok seems like there is another nuance to this:  a slice containing map entries will then return a `[]any`, but with `pcommon.Map` entries in it.
Should we maybe reconsider the original idea of returning `map[string]any` in the `mapGetter`, as opposed to `pcommon.Map`? This might be the most straight forward way of achieving consistency, especially because also the `listGetter` returns `[]any`, as opposed to `pcommon.Slice`. @edmocosta FYI

Comment (bacherfl) [reply pkg/ottl/expression.go:194]: I think this case is now also solved. I remembered we still have to use `pcommon.Map` as a return type of the `mapGetter` , as otherwise statements like `set(attributes, {"foo":"bar})` do not work. However the case I mentioned above can be solved in the `ValueExpression` getter. Now all the tests are passing again, including the one mentioned above. I will see if I can add some more test cases though.

File: pkg/ottl/e2e/e2e_test.go [hunk 5]
```diff
@@ -1084,6 +1084,30 @@ func Test_e2e_converters(t *testing.T) {
 				m.PutInt("bar", 5)
 			},
 		},
+		{
+			statement: `set(attributes["test"], {"list":[{"foo":"bar"}]})`,
```
Comment (TylerHelmuth) [inline pkg/ottl/e2e/e2e_test.go:1088]: Can you add some more e2e tests using map literals and slice literals in other functions? That would give me confidence that we're supporting `map[string]any`/`pcommon.Map` and `[]any`/`pcommon.Slice` consistently across the framework.

Comment (bacherfl) [reply pkg/ottl/e2e/e2e_test.go:1088]: sure, will add a couple of tests today

Comment (bacherfl) [reply pkg/ottl/e2e/e2e_test.go:1097]: alright, I have added some more test cases for several functions making use of map structures.
I have also added another test type to the e2e tests that can be used to test a statement sequence to also be able to test the editor functions with map literals

**Review by TylerHelmuth — DISMISSED** [review]

File: pkg/ottl/parser.go (hunk 1 above)
Comment (TylerHelmuth) [reply pkg/ottl/parser.go:484]: I agree with @edmocosta that we should continue returning pcommon.Map

**Comment by atoulme** [comment]
This looks about ready to merge. I think it'd be great to make sure @evan-bradley can review one more time.

**Comment by edmocosta** [comment]
Before merging it, I think we still need to address this https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/37408#discussion_r1983615902, if @evan-bradley agrees, we would need to undo those changes to keep returning pcommon.Map.

File: pkg/ottl/parser.go (hunk 1 above)
Comment (bacherfl) [reply pkg/ottl/parser.go:484]: Alright, I now changed it again to return pcommon.Map

**Review by TylerHelmuth — APPROVED** [review]

File: pkg/ottl/parser.go [hunk 6]
```diff
@@ -480,6 +481,35 @@ func (p *Parser[K]) ParseValueExpression(raw string) (*ValueExpression[K], error
...
+					m := pcommon.NewMap()
+					if err := m.FromRaw(v); err != nil {
+						return nil, err
+					}
+					return m, nil
+				case []any:
+					for index, elem := range v {
+						// make sure also nested maps within a slice are returned in their raw form
+						if m, ok := elem.(pcommon.Map); ok {
+							v[index] = m.AsRaw()
```
Comment (edmocosta) [inline pkg/ottl/parser.go:501]: Do we need to use raw values here? I might be wrong but I think it'd work with `pcommon.Map` as well, which I think would be ideal to keep it consistent.

File: pkg/ottl/parser.go [hunk 7]
```diff
@@ -480,6 +481,35 @@ func (p *Parser[K]) ParseValueExpression(raw string) (*ValueExpression[K], error
...
+						}
+					}
+					s := pcommon.NewSlice()
```
Comment (edmocosta) [inline pkg/ottl/parser.go:504]: I guess returning an `pcommon.Slice` here would be a breaking change, since the original behavior was returning `[]any`. I'm wondering if we should address the slices inconsistencies here or in a separate PR, maybe by changing the `listGetter` for example.

File: pkg/ottl/parser.go [hunk 8]
```diff
@@ -480,6 +481,35 @@ func (p *Parser[K]) ParseValueExpression(raw string) (*ValueExpression[K], error
...
 	return &ValueExpression[K]{
-		getter: getter,
+		getter: &StandardGetSetter[K]{
+			Getter: func(ctx context.Context, tCtx K) (any, error) {
+				val, err := getter.Get(ctx, tCtx)
+				if err != nil {
+					return nil, err
+				}
+				switch v := val.(type) {
+				case map[string]any:
```
Comment (edmocosta) [inline pkg/ottl/parser.go:491]: I'm not sure if this condition is still possible, considering the mapGetter now only returns `pcommon.Map`

File: pkg/ottl/parser.go (hunk 6 above)
Comment (bacherfl) [reply pkg/ottl/parser.go:501]: Just tried it out and this is required - if we want to make sure to return a `pcommon.Slice` and thus convert an `[]any` using the `FromRaw()` function we must ensure that the `[]any` does not contain any `pcommon.Maps` - otherwise the `FromRaw` function will return an error as it cannot handle `pcommon.Map` elements within the slice

Comment (edmocosta) [reply pkg/ottl/parser.go:501]: Oh I see, it works at parsing/evaluation level but not with this function giving it's wrapping the results into an `pcommon.Slice`.

To make it work with only `pcommon.Map` we would need a similar `mapGetter`'s implementation here or changing the `listGetter` to return `pcommon.Slice`, avoiding using the `FromRaw` function to parse `pcommon.Map` values, like we're doing with maps in this PR.

In that case, I think https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/37408#discussion_r1987742310 makes sense, and I'd rather have consistent `pcommon.Map` values inside raw slices (which is the same type it's already returning), than changing it now to `pcommon.Slice` with raw maps, and later having to break the API again to make maps inside `pcommon.Slice` consistent (`pcommon.Map`).

@TylerHelmuth @evan-bradley WDYT?

File: pkg/ottl/parser.go (hunk 7 above)
Comment (bacherfl) [reply pkg/ottl/parser.go]: Alright, I have reverted the change for the slices again to keep returning `[]any` for now. If needed we can do the adaptation of the listGetter in a separate PR

File: pkg/ottl/parser.go (hunk 6 above)
Comment (TylerHelmuth) [reply pkg/ottl/parser.go]: Agreed

**Review by edmocosta — APPROVED** [review]

**Comment by atoulme** [comment]
@evan-bradley please review and merge if ok?
