### PR TITLE
[exporter/elasticsearch] Fix routing of collector self-telemetry into Elasticsearch data streams

### LINKED ISSUE #42679: [exporter/elasticsearch] Broken routing of collector self-telemetry
### Component(s)

exporter/elasticsearch

## Description

With the document routing [described in here](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/exporter/elasticsearchexporter#elasticsearch-document-routing) the ES exporter applies this regex: `/receiver/(\w*receiver)` to the scope name to retrieve the `data_stream.dataset`.

This leads to unintended doc routing, when the scope name contains the substring `receiver/receiver`.
For example, the collector's self-telemetry for receivers is being reported with the scope name `go.opentelemetry.io/collector/receiver/receiverhelper`, this leads to corresponding metrics being routed to `metrics-receiver.otel-default` while all the other self-telemetry metrics land in `metrics-generic.otel-default`.

## Steps to Reproduce

[Enable self-telemetry on the collector](https://opentelemetry.io/docs/collector/internal-telemetry/#activate-internal-telemetry-in-the-collector) and observe the metrics in Elasticsearch.

## Expected Result

Ideally, we'd have dedicated routing for self-telemetry metrics, e.g. all metrics with the scope names ...
- `go.opentelemetry.io/collector/receiver/receiverhelper`
- `go.opentelemetry.io/collector/processor/processorhelper`
- `go.opentelemetry.io/collector/exporter/exporterhelper`

... landing in something like `metrics-collectortelemetry.otel-default`.

Also, maybe changing the regex `/receiver/(\w*receiver)` to `/receiver/(\w+receiver)` would make sense, as that would enforce that there's actually a receiver name and it would not match the substring `receiver/receiver` anymore.

## Actual Result

See above description.

### Collector version

0.133.0

### Environment information

_No response_

### OpenTelemetry Collector configuration

```yaml
receivers:
  # Receiver for platform specific log files
  filelog/platformlogs:
    include: [ /var/log/*.log ]
    retry_on_failure:
      enabled: true
    start_at: end
    storage: file_storage

  # Receiver for CPU, Disk, Memory, and Filesystem metrics
  hostmetrics/system:
    collection_interval: 30s
    scrapers:
      filesystem:
      memory:
        metrics:
          system.memory.utilization:
            enabled: true
      network:
      processes:
      load:
  
  # OTLP Receiver for self-metrics
  otlp/self:
    protocols:
      grpc:
      http:

extensions:
  file_storage:
    directory: ...

processors:
  resourcedetection:
    detectors: ["system"]
    system:
      hostname_sources: ["os"]
      resource_attributes:
        host.name:
          enabled: true
        host.id:
          enabled: false
        host.arch:
          enabled: true
        host.ip:
          enabled: true
        host.mac:
          enabled: true
        host.cpu.vendor.id:
          enabled: true
        host.cpu.family:
          enabled: true
        host.cpu.model.id:
          enabled: true
        host.cpu.model.name:
          enabled: true
        host.cpu.stepping:
          enabled: true
        host.cpu.cache.l2.size:
          enabled: true
        os.description:
          enabled: true
        os.type:
          enabled: true
  attributes/dataset:
    actions:
      - key: event.dataset
        from_attribute: data_stream.dataset
        action: upsert

exporters:
  elasticsearch/otel:
    endpoints: [ "..." ]
    api_key: ...
    mapping:
      mode: otel

service:
  extensions: [file_storage]
  pipelines:
    metrics/hostmetrics:
      receivers: [hostmetrics/system]
      processors: [resourcedetection, attributes/dataset]
      exporters: [elasticsearch/otel]
    logs/platformlogs:
      receivers: [filelog/platformlogs]
      processors: [resourcedetection]
      exporters: [elasticsearch/otel]
    metrics/self:
      receivers: [otlp/self]
      exporters: [elasticsearch/otel]
  telemetry:
    metrics:
      readers:
        - periodic:
            exporter:
              otlp:
                protocol: http/protobuf
                endpoint: http://localhost:4318
```

### Log output

```shell

```

### Additional context

_No response_

### Tip

<sub>[React](https://github.blog/news-insights/product-news/add-reactions-to-pull-requests-issues-and-comments/) with 👍 to help prioritize this issue. Please use comments to provide useful context, avoiding `+1` or `me too`, to help us triage it. Learn more [here](https://opentelemetry.io/community/end-user/issue-participation/).</sub>

### PR DESCRIPTION
**Pull request by AlexanderWert**
#### Description
Makes the internal collector telemetry to be routed to the `collectortelemetry` dataset in Elasticsearch.

#### Link to tracking issue
Fixes #42679

### CODE REVIEW

File: exporter/elasticsearchexporter/data_stream_router.go [hunk 1]
```diff
@@ -187,6 +195,9 @@ func routeRecord(
 		if submatch := receiverRegex.FindStringSubmatch(scope.Name()); len(submatch) > 0 {
 			receiverName := submatch[1]
 			dataset = receiverName
+		} else if selfTelemetryScopeNames[scope.Name()] {
+			// For collector self-telemetry, use a fixed dataset name
+			dataset = collectorSelfTelemetryDataStreamDataset
 		}
```
Comment (carsonip) [inline exporter/elasticsearchexporter/data_stream_router.go]: nit: is it easier to do self telemetry exact match before the regex match? i.e. swapping the `if` and `else if`. Then we can avoid other regex bugs down the line, or even skip the regex change in this PR.

**Review by carsonip — APPROVED** [review]
thanks, change lgtm. 1 nit.

**Review by carsonip — APPROVED** [review]
also missing a changelog

File: exporter/elasticsearchexporter/attribute.go
Comment (florianl) [inline exporter/elasticsearchexporter/attribute.go:1]: As this is a user facing change, maybe we should add a chlog.

File: exporter/elasticsearchexporter/data_stream_router.go [hunk 2]
```diff
@@ -180,11 +188,14 @@ func routeRecord(
...
 	if !datasetExists {
-		// Receiver-based routing
-		// For example, hostmetricsreceiver (or hostmetricsreceiver.otel in the OTel output mode)
-		// for the scope name
-		// github.com/open-telemetry/opentelemetry-collector-contrib/receiver/hostmetricsreceiver/internal/scraper/cpuscraper
-		if submatch := receiverRegex.FindStringSubmatch(scope.Name()); len(submatch) > 0 {
+		if selfTelemetryScopeNames[scope.Name()] {
+			// For collector self-telemetry, use a fixed dataset name
+			dataset = collectorSelfTelemetryDataStreamDataset
+		} else if submatch := receiverRegex.FindStringSubmatch(scope.Name()); len(submatch) > 0 {
```
Comment (florianl) [inline exporter/elasticsearchexporter/data_stream_router.go]: FindStringSubmatch is often the cause for heavy allocations. An alternative could look like this:

```
loc := receiverRegex.FindStringIndex(scope.Name())
if len(loc) == 0 {
   continue
}
receiverName := scope.Name()[loc[0]:loc[1]])
```

**Review by carsonip — APPROVED** [review]
thanks!

File: exporter/elasticsearchexporter/data_stream_router.go (hunk 2 above)
Comment (AlexanderWert) [reply exporter/elasticsearchexporter/data_stream_router.go]: That doesn't work because `FindStringIndex` returns the position of the entire regex, but we need to extract the capture group.

e.g. as we need to match the regex `/receiver/(\w+receiver)`, with a scope name `github.com/open-telemetry/opentelemetry-collector-contrib/receiver/hostmetricsreceiver/internal/scraper/cpuscraper` we get a dataset `/receiver/hostmetricsreceiver` instead of `hostmetricsreceiver`

Comment (florianl) [reply exporter/elasticsearchexporter/data_stream_router.go]: sorry for the mix. It should be `FindStringSubmatchIndex` instead of `FindStringIndex`.

Here is an example https://go.dev/play/p/yYFA8L1FEAb

Comment (AlexanderWert) [reply exporter/elasticsearchexporter/data_stream_router.go]: perfect, that works, thanks!

**Review by florianl — APPROVED** [review]

**Review by carsonip — APPROVED** [review]

**Review by mx-psi — APPROVED** [review]
