### PR TITLE
[processor/k8sattributes] Fix node/ns labels/annotations extraction

### LINKED ISSUE #28837: [processor/k8sattributes] Labels/annotations extraction relies on presence of node/namespace attributes
Extraction of k8s namespace or node labels/annotation is only possible if users configure extraction of `k8s.namespace.name` or `k8s.node.name` attributes.

It should be possible to extract namespace or node labels/annotation without `k8s.namespace.name` or `k8s.node.name` attributes.

### PR DESCRIPTION
**Pull request by dmitryax**
Set attributes from namespace/node labels or annotations even if `k8s.namespace.name` and `k8s.node.name` are not extracted.

Fixes https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/28837

### CODE REVIEW

**Comment by dmitryax** [comment]
Failing CI check is fixed in https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/28840

File: processor/k8sattributesprocessor/processor_test.go [hunk 1]
```diff
@@ -727,6 +727,78 @@ func TestProcessorAddLabels(t *testing.T) {
 	}
 }
 
+func TestAddNamespaceLabels(t *testing.T) {
```
Comment (fatsheep9146) [inline processor/k8sattributesprocessor/processor_test.go:730]: Should we also add a test `TestAddNodeLabels`?

Comment (dmitryax) [reply processor/k8sattributesprocessor/processor_test.go:730]: Sure, added

**Review by TylerHelmuth — APPROVED** [review]
