### PR TITLE
[receiver/github] fix queue span lengths caused by GitHub event timestamp bug

### LINKED ISSUE #39824: [receiver/github] queue spans sometimes show negative durations leading to long span times
### Component(s)

receiver/github

## Description

Relates to #39020 

The same behavior that was fixed in #39020 now shows up for Queue Spans ([see this comment](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/39020#issuecomment-2842664787)). 

After investigation, Arian determined that it was extremely intermittent. We investigated and realized this is a bug in GitHub on the event side where the created time may be a second later than the started at time from the event.

Need to create a workaround for this in the code. Wanted to open this issue to track the fix I'll be pushing. 

### Collector version

v0.124.0

## Environment
All 

### OpenTelemetry Collector configuration

```yaml
Any basic GitHub receiver tracing config.
```

### Log output

```shell

```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by adrielp**
#### Description

GitHub events from skipped jobs sometimes have the createdAt timestamp to be AFTER the startedAt timestamp. This causes the created span to having a time of some crazy long time, while the duration attribute is negative. This change accounts for that inconsistent behavior from GitHub and adds the corresponding tests.

#### Link to tracking issue
Fixes #39824

#### Testing

Added the tests in the source code.

#### Documentation

Minor comment around the codeblock for context of why.

### CODE REVIEW

File: receiver/githubreceiver/trace_event_handling.go [hunk 1]
```diff
@@ -385,13 +386,25 @@ func (gtr *githubTracesReceiver) createJobQueueSpan(
...
+	// GitHub sometimes reports the createdAt value as being a second after the
+	// startedAt value which results in unreal times in duration. To work around
+	// this we set the duration to 0 and the start/end spans to the started
+	// time in that event. Otherwise we calculate the time properly and set the
+	// span start time as the created time.
+	created := pcommon.NewTimestampFromTime(event.GetWorkflowJob().GetCreatedAt().Time)
+	started := pcommon.NewTimestampFromTime(event.GetWorkflowJob().GetStartedAt().Time)
+	time := time.Duration(0)
+
+	span.SetStartTimestamp(started)
```
Comment (crobert-1) [inline receiver/githubreceiver/trace_event_handling.go:398]: Nit, feel free to drop: Can we have the default case be first here, and then the "error handling" (accounting for the GitHub bug) be inside the `if` statement? It took me a while to make sure I was following the comment and logic here.

**Review by crobert-1 — APPROVED** [review]

**Review by VihasMakwana — APPROVED** [review]

File: receiver/githubreceiver/trace_event_handling.go (hunk 1 above)
Comment (adrielp) [reply receiver/githubreceiver/trace_event_handling.go]: No, totally fair call out. In my effort to think about a guarding conditional, my brain reversed the wrong thing. Just pushed an update, hopefully this is clearer.

**Review by crobert-1 — APPROVED** [review]
