### PR TITLE
[chore] Fix tools for windows 11 arm

### LINKED ISSUE #43625: receiver/datadog: windows 11 scoped tests fail
### Component(s)

receiver/datadog

### Describe the issue you're reporting

unclear to me if this is a failure in the receiver or in the setup of the test on windows 11

```
C:/a/opentelemetry-collector-contrib/opentelemetry-collector-contrib/.tools/golangci-lint run
level=warning msg="[runner] Can't run linter goanalysis_metalinter: inspect: failed to load package datadogreceiver: could not load export data: no export data for \"github.com/open-telemetry/opentelemetry-collector-contrib/receiver/datadogreceiver\""
level=warning msg="[runner/exclusion_paths] The pattern \"third_party\" match no issues"
level=warning msg="[runner/exclusion_rules] Skipped 0 issues by rules: [Text: \"cachedBytes\", Path: \"pagefile.go\", Linters: \"unused\"]"
level=warning msg="[runner/exclusion_rules] Skipped 0 issues by rules: [Path: \"third_party\", Linters: \"gci, gofumpt\"]"
level=error msg="Running error: can't run linter goanalysis_metalinter\ninspect: failed to load package datadogreceiver: could not load export data: no export data for \"github.com/open-telemetry/opentelemetry-collector-contrib/receiver/datadogreceiver\""
make[1]: *** [../Makefile.Common:282: lint] Error 3
```

See https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/18576820044/job/53007189566?pr=43611 for more details

### Tip

<sub>[React](https://github.blog/news-insights/product-news/add-reactions-to-pull-requests-issues-and-comments/) with 👍 to help prioritize this issue. Please use comments to provide useful context, avoiding `+1` or `me too`, to help us triage it. Learn more [here](https://opentelemetry.io/community/end-user/issue-participation/).</sub>

### PR DESCRIPTION
**Pull request by pjanotti**
Fix #43625

[Updated to correctly describe the problem]

The tools used in the `lint` target need to build the component and per manual tests the component fails to build if `go build` tries to use `CGO`

The issue didn't show up previously because the build and test workflow on Windows ARM already sets the environment variable `CGO_ENABLED` to `0`. The fix here is to adopt the same approach and disable `CGO` for `windows-11-arm`.

For safety I will do a bogus change to trigger a run of the case that exposed the issue.

### CODE REVIEW

**Comment by pjanotti** [comment]
🤔 we are "gomoddownloading" for `scoped-tests` if go cache was not found, I don't think we should do that ... anyway, separate issue

**Comment by pjanotti** [comment]
Hum, it still failed, looking...

**Comment by pjanotti** [comment]
This [CI failure](https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/18605025722/job/53054020686?pr=43633#step:9:1) is the same as https://github.com/open-telemetry/opentelemetry-collector/issues/12422

**Comment by pjanotti** [comment]
I want one more run with the bogus change to confirm that things are green... will remove right after it.

**Review by atoulme — APPROVED** [review]

File: receiver/datadogreceiver/config.go [hunk 1]
```diff
@@ -32,7 +32,7 @@ const (
 
 type Config struct {
 	confighttp.ServerConfig `mapstructure:",squash"`
-	// ReadTimeout of the http server
+	// ReadTimeout of the http server - bogus comment to trigger scoped-test, to be reverted before merge.
```
Comment (atoulme) [inline receiver/datadogreceiver/config.go]: putting a comment up to remind ourselves to remove this comment

**Review by songy23 — APPROVED** [review]
