### PR TITLE
[receiver/collectd] Initialize StartTimestamp for cumulative metrics

### LINKED ISSUE #6303: collectd receiver – "The start time must be before the end time"
**Describe the bug**

OpenTelemetry is returning the following error (this is one example among other distribution type system metrics being received from Collectd):

```
ERROR        collectdreceiver/receiver.go:179        unable to process metrics        {"component_kind": "receiver", "component_type": "collectd", "component_name": "collectd", "error": "rpc error: code = InvalidArgument desc = Field timeSeries[4].points[0].interval.start_time had an invalid value of \"2021-11-14T17:14:08.026-08:00\": The start time must be before the end time (2021-11-14T17:14:08.026-08:00) for the non-gauge metric 'custom.googleapis.com/<some-name>/processes/fork_rate'."}
```

**Steps to reproduce**
Configure Collectd using the http_write plugin pointing it to the otel-contrib collectd receiver.

**What did you expect to see?**
Distribution type metrics being received and in this case, sent to GCP Cloud Monitoring (stackdriver exporter)

**What did you see instead?**
The error shown above in the OTel logs. 

**What version did you use?**
OTel contrib version: "v0.18.0"
Collectd version: 5.8.0

**What config did you use?**

* OpenTelemetry config

```
extensions:
  health_check:
receivers:
  collectd:
    config:
exporters:
  prometheus:
    endpoint: ":24445"
  stackdriver:
    project: "<some project>"
    endpoint: "monitoring.googleapis.com:443"
    metric:
      prefix: "custom.googleapis.com/<some_name>/"
      skip_create_descriptor: false
    retry_on_failure:
    number_of_workers: 3
service:
  extensions: [health_check]
  pipelines:
    metrics/monitoringatcorp:
      receivers: [collectd]
      exporters: [prometheus,stackdriver]
```

* Collectd `http_write` config:

```
LoadPlugin write_http
<Plugin write_http>
    <Node "example">
          URL "localhost:8081"
          Format "json"
    </Node>
</Plugin>
```

**Environment**
OS: Red Hat Enterprise Linux Server release 7.9 (Maipo)

**Additional context**

Here the json message (corresponding to the error shown above) sent out by collectd out of the wire:

```
        Object
            Member Key: values
                Array
                    Number value: 77263073
                Key: values
            Member Key: dstypes
                Array
                    String value: derive
                Key: dstypes
            Member Key: dsnames
                Array
                    String value: value
                Key: dsnames
            Member Key: time
                Number value: 1636938428.026
                Key: time
            Member Key: interval
                Number value: 60.000
                Key: interval
            Member Key: host
                String value: <some hostname>
                Key: host
            Member Key: plugin
                String value: processes
                Key: plugin
            Member Key: plugin_instance
                String value: 
                Key: plugin_instance
            Member Key: type
                String value: fork_rate
                Key: type
            Member Key: type_instance
                String value: 
                Key: type_instance
```

### PR DESCRIPTION
**Pull request by guilledipa**
**Description:**

Fixing a bug – OTel is currently returning the following error `The start time must be before the end time` when handling cumulative type metrics. This PR initializes `TimeSeries.StartTimestamp` by setting this value to Collectd `Interval` number of seconds before the `Point.Timestamp`.

**Link to tracking Issue:**

Fixes #6303

**Testing:** 

```
$ go test -run ^(TestDecodeEvent|TestDecodeMetrics|TestLabelsFromName)$ github.com/open-telemetry/opentelemetry-collector-contrib/receiver/collectdreceiver
```

No new test-cases added. I modified the test case `df_complex.free` to accept a non `nil` `StartTimestamp` value.

### CODE REVIEW

File: receiver/collectdreceiver/collectd.go [hunk 1]
```diff
@@ -59,6 +59,13 @@ func (r *collectDRecord) protoTime() *timestamppb.Timestamp {
 	return timestamppb.New(ts)
 }
 
+func (r *collectDRecord) startTimestamp(mdType metricspb.MetricDescriptor_Type) *timestamppb.Timestamp {
+	if mdType == metricspb.MetricDescriptor_CUMULATIVE_DISTRIBUTION || mdType == metricspb.MetricDescriptor_CUMULATIVE_DOUBLE || mdType == metricspb.MetricDescriptor_CUMULATIVE_INT64 {
+		return timestamppb.New(time.Unix(0, int64(float64(time.Second)**r.Time)-int64(float64(time.Second)**r.Interval)))
```
Comment (bogdandrutu) [inline receiver/collectdreceiver/collectd.go:64]: Something I don't like about "**" can you please refactor the code to avoid that?

Comment (guilledipa) [reply receiver/collectdreceiver/collectd.go]: Thanks @bogdandrutu! I committed a change that should improve the readability of this code. Let me know if it looks better.

**Comment by bogdandrutu** [comment]
@owais please review since you own that component.

**Comment by guilledipa** [comment]
Hi @owais friendly ping, hopefully this will remove the `stale` label.

**Comment by guilledipa** [comment]
@bogdandrutu would it be possible to add `open-telemetry/collector-contrib-approver` as a reviewer?

**Comment by jpkrohling** [comment]
@owais, would you like to review this one, as the codeowner for the component?

File: receiver/collectdreceiver/collectd.go [hunk 2]
```diff
@@ -59,6 +59,13 @@ func (r *collectDRecord) protoTime() *timestamppb.Timestamp {
 	return timestamppb.New(ts)
 }
 
+func (r *collectDRecord) startTimestamp(mdType metricspb.MetricDescriptor_Type) *timestamppb.Timestamp {
```
Comment (jpkrohling) [inline receiver/collectdreceiver/collectd.go:62]: I think this function deserves a test of its own.

**Comment by jpkrohling** [comment]
@guilledipa, are you still interested in this one?

**Comment by guilledipa** [comment]
@jpkrohling thanks for the review! I'm still interested in this PR (Sorry I was slow to respond during the holiday season). I'll create test cases for `startTimestamp()` and update the thread :)

**Comment by jpkrohling** [comment]
> Sorry I was slow to respond during the holiday season

No need to be sorry. Be proud that you were able to disconnect during the holidays ;-)

>I'll create test cases for startTimestamp() and update the thread :)

Ping me when it's ready.

File: receiver/collectdreceiver/collectd.go (hunk 2 above)
Comment (guilledipa) [reply receiver/collectdreceiver/collectd.go:62]: @jpkrohling Thank you very much!! PTAL

I've added test cases for this method. The cases are quite trivial, however, *I think* we should have good coverage for the function as it is being exercised not only in the newly added cases, but also indirectly in `TestDecodeMetrics()`.

**Review by jpkrohling — APPROVED** [review]

**Comment by guilledipa** [comment]
@jpkrohling I missed a test-case in `receiver_test.go` which I missed in my last commits. Also made nit changes to `collectd_test.go`

Sorry for the extra hop and thanks again for the prompt review.

ptal :)

**Comment by jpkrohling** [comment]
Tests started but it looks like this does need a changelog entry.

**Review by owais — APPROVED** [review]

**Comment by owais** [comment]
Sorry for the delayed response due to my vacation. Going forward I don't think I'll have the time to maintain this component and I haven't touched it in a long time. It would be great if we could find another owner for this.

**Comment by jpkrohling** [comment]
@bogdandrutu, do you think this does not need an entry in the changelog? Looks like a change in behavior for the current users of the component.

**Review by jpkrohling — APPROVED** [review]
