### PR TITLE
[processor/tailsampling] Honor final decision for late arriving spans

### LINKED ISSUE #14760: [processor/tailsamplingprocessor] Late arriving spans can get different final decision from original
## Description

I have a situation where spans for a trace are not sampled during the first decision point, but late arriving spans for the same trace are. This only reproduces for late arriving spans and only under certain conditions:

## Steps to Reproduce

If the sampler is configured with a mix containing at least 1 string attribute policy, with invert match = true and another policy.

```
  tail_sampling:
    decision_wait: 5s
    policies:
    - name: ignore_traces_with_http_target
      type: string_attribute
      string_attribute:
        enabled_regex_matching: true
        invert_match: true
        key: http.target
        values:
        - alive$
    - name: sample_traces_from_service_namespaces
      type: string_attribute
      string_attribute:
        enabled_regex_matching: true
        key: service.namespace
        values:
        - ^foobar$
```

If you start a trace and send one span that causes the policies to evaluate to:
policies[0] = InvertSampled
policies[1] = NotSampled

then wait for the configured decision time, and send another span to complete the trace, the first span will be unsampled while the second one will be, which is not correct.

I sent two spans from a dotnet host that look like this:

```csharp
    Console.WriteLine("Hit any key to generate a new trace.");
    Console.ReadLine();
    Console.WriteLine("Trace started...");

    using var activity = source.StartActivity(
        "HTTP GET",
        ActivityKind.Server);
    activity?.SetTag($"http.url", "http://localhost/bar");
    activity?.SetTag($"http.method", "GET");
    activity?.SetTag($"http.path", "/bar");

    using var subActivity1 = source.StartActivity(
        "HTTP GET",
        ActivityKind.Client);
    subActivity1?.SetTag($"http.url", "http://localhost/foo");
    subActivity1?.SetTag($"http.method", "GET");
    subActivity1?.SetTag($"http.path", "/foo");
    subActivity1?.Dispose();

    Console.WriteLine("Hit any key to complete the trace...");
    Console.ReadLine();
    Console.WriteLine("Trace complete.\n.\n");
```
The span generated from subActivity1 is delivered immediately, and after the decision wait time expires, produces the policy evaluations above. The trace's final decision is NotSampled. After completing the trace, the final span is delivered and immediately sampled and forwarded along.

## Expected Result

Late arriving spans always get the same initial final decision, which in this case is NotSampled (if that is correct).

## Actual Result

Late arriving spans do not always get the same initial final decision.

### Collector version

v0.61.0

## Environment
OS: Ubuntu 20.04

### OpenTelemetry Collector configuration

```yaml
exporters:
  logging:
    loglevel: debug
processors:
  tail_sampling:
    decision_wait: 5s
    policies:
    - name: ignore_traces_with_http_target
      type: string_attribute
      string_attribute:
        enabled_regex_matching: true
        invert_match: true
        key: http.target
        values:
        - alive$
    - name: sample_traces_from_service_namespaces
      type: string_attribute
      string_attribute:
        enabled_regex_matching: true
        key: service.namespace
        values:
        - ^testhost$
receivers:
  otlp/sampler:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
service:
  pipelines:
    traces:
      exporters:
      - logging
      processors:
      - tail_sampling
      receivers:
      - otlp/sampler
  telemetry:
    logs:
      level: DEBUG
```

### Log output

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by pcwiese**
**Description:**
When dealing with traces that have already been evaluated, use the final decision instead of trying using the individual decisions by the policies.

**Link to tracking Issue:**
Close https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/14760

**Testing:**
A new test was added that matches the bug repro

**Documentation:**
None

### CODE REVIEW

File: processor/tailsamplingprocessor/processor.go [hunk 1]
```diff
@@ -356,43 +357,30 @@ func (tsp *tailSamplingSpanProcessor) processTraces(resourceSpans ptrace.Resourc
...
-					tsp.logger.Warn("Error sending late arrived spans to destination",
-						zap.String("policy", p.name),
+				if err := tsp.nextConsumer.ConsumeTraces(tsp.ctx, traceTd); err != nil {
+					tsp.logger.Warn(
+						"Error sending late arrived spans to destination",
 						zap.Error(err))
 				}
-			case sampling.NotSampled:
+			} else if finalDecision == sampling.NotSampled {
 				stats.Record(tsp.ctx, statLateSpanArrivalAfterDecision.M(int64(time.Since(actualData.DecisionTime)/time.Second)))
```
Comment (pcwiese) [inline processor/tailsamplingprocessor/processor.go:380]: Seems like this would be incrementing per policy, which doesn't seem correct to me...

File: processor/tailsamplingprocessor/processor.go [hunk 2]
```diff
@@ -356,43 +357,30 @@ func (tsp *tailSamplingSpanProcessor) processTraces(resourceSpans ptrace.Resourc
...
+		} else {
+			actualData.Unlock()
+			if finalDecision == sampling.Sampled {
 				// Forward the spans to the policy destinations
 				traceTd := ptrace.NewTraces()
 				appendToTraces(traceTd, resourceSpans, spans)
-				if err := tsp.nextConsumer.ConsumeTraces(p.ctx, traceTd); err != nil {
-					tsp.logger.Warn("Error sending late arrived spans to destination",
-						zap.String("policy", p.name),
+				if err := tsp.nextConsumer.ConsumeTraces(tsp.ctx, traceTd); err != nil {
```
Comment (pcwiese) [inline processor/tailsamplingprocessor/processor.go:374]: We lose the matching policy context here. Not sure if that is important or not...

**Review by jpkrohling — APPROVED** [review]

File: processor/tailsamplingprocessor/processor.go (hunk 2 above)
Comment (jpkrohling) [reply processor/tailsamplingprocessor/processor.go:376]: I think it's fine, given that we are acting on the whole set instead of individual policies.
