### PR TITLE
[receiver/filelog] Fix issue where flushed tokens could be truncated

### LINKED ISSUE #35042: Long lines are unexpectedly split into multiple OTEL Log records
### Component(s)

pkg/stanza/fileconsumer, receiver/filelog

## Description

When using the filelog receiver, any lines that are longer than the default buffer size (16KB) will be split into multiple log records instead of one single log record.

## Steps to Reproduce

1. Create simple default filelog receiver config
2. Ingest a file that has a line length that is greater than 16KB)

## Expected Result

Lines longer than 16KB gets emitted as one single OTEL Log record

## Actual Result

Lines longer than 16KB get emitted as multiple OTEL Log records, each record getting split at the 16KB boundary.

### Collector version

v0.108.0

## Environment
OS: Archlinux
Compiler(if manually compiled): go 1.23.0

### OpenTelemetry Collector configuration

```yaml
receivers:
  filelog:
    start_at: beginning
    include:
      - "/tmp/metrics_101089747.json"

exporters:
  debug:
    verbosity: detailed
service:
  pipelines:
    logs/raw:
      receivers:
        - filelog
      exporters:
        - debug
```

### Log output

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by djaglowski**
Fixes #35042 (and #32100 again)

The issue affected unterminated logs of particular lengths. Specifically, longer than our internal `scanner.DefaultBufferSize` (16kB) and shorter than `max_log_size`.

The failure mode was described in #32100 but was apparently only fixed in some circumstances. I believe this is a more robust fix. I'll articulate the exact failure mode again here:
1. During a poll cycle, `reader.ReadToEnd` is called. Within this, a scanner is created which starts with a default buffer size. The buffer is filled, but no terminator is found. Therefore the scanner resizes the buffer to accommodate more data, hoping to find a terminator. Eventually, the buffer is large enough to contain all content until EOF, but still no terminator was found. At this time, the flush timer has not expired, so `reader.ReadToEnd` returns without emitting anything.
2. During the _next_ poll cycle, `reader.ReadToEnd` creates a new scanner, also with default buffer size. The first time is looks for a terminator, it of course doesn't find one, but at this time the flush timer has expired. Therefore, instead of resizing the buffer and continuing to look for a terminator, it just emits what it has.

What should happen instead is the scanner continues to resize the buffer to find as much of the unterminated token as possible before emitting it. Therefore, this fix introduces a simple layer into the split func stack which allows us to reason about unterminated tokens more carefully. It captures the length of unterminated tokens and ensures that when we recreate a scanner, we will start with a buffer size that is appropriate to read the same content as last time, plus one additional byte. The extra byte allows us to check if new content has been added, in which case we will resume resizing. If no new content is found, the flusher will emit the entire unterminated token as one.

### CODE REVIEW

**Comment by djaglowski** [comment]
Depends on #37596

File: pkg/stanza/fileconsumer/internal/reader/factory.go [hunk 1]
```diff
@@ -100,9 +111,10 @@ func (f *Factory) NewReaderFromMetadata(file *os.File, m *Metadata) (r *Reader,
 		r.Offset = info.Size()
 	}
 
-	flushFunc := m.FlushState.Func(f.SplitFunc, f.FlushTimeout)
+	tokenLenFunc := m.TokenLenState.Func(f.SplitFunc)
+	flushFunc := m.FlushState.Func(tokenLenFunc, f.FlushTimeout)
```
Comment (VihasMakwana) [inline pkg/stanza/fileconsumer/internal/reader/factory.go:115]: Please correct me if I'm wrong, but I'm confused. Wouldn't the flush function timeout, regardless of buffer resizing?

Comment (djaglowski) [reply pkg/stanza/fileconsumer/internal/reader/factory.go:115]: The timer would indeed be expired. What this change does though, it makes sure that the token we're passing into the flush function is at least as long as the one we passed in previously.

Example:

Poll 1: Buffer starts at 16kB, grows to 20kB, finds no terminator. Flush hasn't expired, so we return. (At this point, the tokenlen function has captured knowledge that there is 20kB of unterminated content at the EOF.

Poll 2: We see that there was 20kB unterminated content left after the previous poll, so we initialize the scanner with a 20kB buffer. This means it will read the entire token on the first try. The timer has expired, so we flush the token.

The fix here is that we are avoiding the situation where Poll 2 starts with a 16kB buffer and ends up flushing only a 16kB token.

Comment (VihasMakwana) [reply pkg/stanza/fileconsumer/internal/reader/factory.go:115]: Okay now I understand.
So, instead of resizing the buffer for x times, we configure it to be of "potential length" at the beginning, and we will atleast read "potential length" amount of data.

Comment (djaglowski) [reply pkg/stanza/fileconsumer/internal/reader/factory.go:115]: That's the idea. I think the name of the field could be clearer. `MinimumLength` is better because it conveys that we know the next token will be at least that long. I'll push the update shortly.

**Review by VihasMakwana — APPROVED** [review]

**Review by andrzej-stencel — APPROVED** [review]
