### PR TITLE
[receiver/kafka]Protect partition lost/revoke callback against unassigned groups

### LINKED ISSUE #40920: kafkareceiver with franz go enabled leads to panic for `OnPartitionLost`
### Component(s)

receiver/kafka

## Description
Panic being observed in logs for the receiver when `UseFranzGo` feature flag is turned on.

## Steps to Reproduce
N/A

## Expected Result
No panic

## Actual Result
Panicing in partition lost callback

### Collector version

de465d285ea1

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

### OpenTelemetry Collector configuration

```yaml
    receivers:
      kafka:
        brokers:
          - <redacted>
        tls:
          <redacted>
        logs:
          topic: <redacted>
          encoding: "otlp_proto"
        metrics:
          topic: <redacted>
          encoding: "otlp_proto"
        traces:
          topic: <redacted>
          encoding: "otlp_proto"
        group_id: <redacted>
        client_id: <redacted>
        session_timeout: "45s"
        heartbeat_interval: "5s"
        min_fetch_size: 819200
        max_fetch_size: 5e+07
        default_fetch_size: 5e+07
        max_fetch_wait: "10s"
        autocommit:
          enable: true
          interval: "1s"
        message_marking:
          after: true
          on_error: true
        error_backoff:
          enabled: true
          initial_interval: "100ms"
          max_interval: "5s"
          max_elapsed_time: "30s"
          multiplier: 2
          randomization_factor: 0.5


    connectors:
      signaltometrics:
        <redacted>

    exporters:
      kafka:
        brokers:
          - <redacted>
        metrics:
          encoding: "otlp_proto"
        sending_queue:
          enabled: false
        tls:
          <redacted>
        client_id: <redacted>

    service:
      extensions: []
      telemetry:
        <redacted>


      pipelines:
        traces:
          receivers: [kafka]
          processors: []
          exporters: [signaltometrics]
        metrics:
          receivers: [kafka]
          processors: []
          exporters: [signaltometrics]
        logs:
          receivers: [kafka]
          processors: []
          exporters: [signaltometrics]
        metrics/apm:
          receivers: [signaltometrics]
          processors: []
          exporters: [kafka]
```

The collector is running with the args:

```
            - '--feature-gates=exporter.kafkaexporter.UseFranzGo,receiver.kafkareceiver.UseFranzGo'
```

### Log output

```shell
panic: runtime error: invalid memory address or nil pointer dereference [signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x212bdc8] goroutine 5854 [running]: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/kafkareceiver.(*franzConsumer).lost(0x4000769080, {0x4e3fce0, 0x4000546780}, 0x1ec37a8?, 0x40010600c0, 0x0) github.com/open-telemetry/opentelemetry-collector-contrib/receiver/kafkareceiver@v0.128.1-0.20250623222603-de465d285ea1/consumer_franz.go:382 +0x318 github.com/open-telemetry/opentelemetry-collector-contrib/receiver/kafkareceiver.(*franzConsumer).Start.func1({0x4e3fce0?, 0x4000546780?}, 0x4000d10540?, 0x35?) github.com/open-telemetry/opentelemetry-collector-contrib/receiver/kafkareceiver@v0.128.1-0.20250623222603-de465d285ea1/consumer_franz.go:134 +0x44 github.com/twmb/franz-go/pkg/kgo.(*consumer).initGroup.func2({0x4e3fce0, 0x4000546780}, 0x40004d9008, 0x40010e3d10) github.com/twmb/franz-go@v1.18.1/pkg/kgo/consumer_group.go:342 +0x320 github.com/twmb/franz-go/pkg/kgo.(*groupConsumer).revoke(0x400089f400, 0x0, 0x40010e3d10, 0x0) github.com/twmb/franz-go@v1.18.1/pkg/kgo/consumer_group.go:716 +0x904 github.com/twmb/franz-go/pkg/kgo.(*assignRevokeSession).prerevoke.func1() github.com/twmb/franz-go@v1.18.1/pkg/kgo/consumer_group.go:776 +0x84 created by github.com/twmb/franz-go/pkg/kgo.(*assignRevokeSession).prerevoke in goroutine 128 github.com/twmb/franz-go@v1.18.1/pkg/kgo/consumer_group.go:773 +0x84
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by lahsivjar**
#### Description

The `OnPartitionLost` function can be called without the group ever being assigned ([ref](https://pkg.go.dev/github.com/twmb/franz-go/pkg/kgo#OnPartitionsLost)). However, the kafka receiver code didn't protect against this. The PR adds a check to protect against this case. Quoting from the linked docs for `OnPartitionLost`:

```
OnPartitionsLost sets the function to be called on "fatal" group errors, such as IllegalGeneration, UnknownMemberID, and authentication failures. This function differs from [OnPartitionsRevoked](https://pkg.go.dev/github.com/twmb/franz-go/pkg/kgo#OnPartitionsRevoked) in that it is unlikely that commits will succeed when partitions are outright lost, whereas commits likely will succeed when revoking partitions.

Because this function is called on any fatal group error, it is possible for this function to be called without the group ever being joined.
```

#### Link to tracking issue
Fixes https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/40920

#### Testing
Since the test is a callback, I can't think of a good way to test it other than coding the exact scenario which I think would be too brittle.

#### Documentation
Added godoc comments for clarity.

### CODE REVIEW

File: receiver/kafkareceiver/consumer_franz.go [hunk 1]
```diff
@@ -377,16 +377,22 @@ func (c *franzConsumer) lost(ctx context.Context, _ *kgo.Client,
...
-			go func() {
-				defer wg.Done()
-				pc.wg.Wait()
-			}()
+			pc, ok := c.assignments[tp]
+			// For fatal true, called from OnPartitionLost, we need to ensure
+			// that the assignments exist as OnPartitionLost is called on any
+			// fatal group errors and thus it is possible that this method is
+			// called without the group ever joining and getting assigned.
+			if !fatal || (fatal && ok) {
```
Comment (lahsivjar) [inline receiver/kafkareceiver/consumer_franz.go]: [**For reviewers**] I also considered just short-circuting the loop for `fatal` but it could also have assignemnts and in that case we should delete and stop them so I went ahead with the current logic of checking if assignment exists if fatal is true and assuming assignment exists if fatal is false.

**Review by crobert-1 — COMMENTED** [review]
Is there any way to add tests for this case?

**Comment by axw** [comment]
I agree that a test is in order, if this is something that can happen in the wild. Otherwise we won't know if we regress.

> Since the test is a callback, I can't think of a good way to test it other than coding the exact scenario which I think would be too brittle.

What would that look like? Can you implement something and we can debate it?

**Comment by lahsivjar** [comment]
I discovered that even `OnPartitionRevoked` can result in this panic ([details here](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/40920#issuecomment-3008625086)). I have been able to reproduce this locally by using the default cooperative rebalancing strategy and just deleting the topic once the partitions are assigned

> What would that look like? Can you implement something and we can debate it?

I tried using Kfake first, but it didn't lead to the same panic as it didn't have the same behaviour. I have added a test for `lost` directly in [this commit](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/40921/commits/8da7be8d0f21da117c2fdd685ba674a68ec87ea8) - not the most elegant as it uses a hard-coded scenario of lost getting called twice but it does catch the issue. Happy to hear other ideas.

File: .chloggen/40920-fix-franzgo-panic.yaml [hunk 2]
```diff
@@ -0,0 +1,27 @@
+# Use this changelog template to create an entry for release notes.
+
+# One of 'breaking', 'deprecation', 'new_component', 'enhancement', 'bug_fix'
+change_type: bug_fix
+
+# The name of the component, or a single word describing the area of concern, (e.g. filelogreceiver)
+component: kafkareceiver
+
+# A brief description of the change.  Surround your text with quotes ("") if it needs to start with a backtick (`).
+note: Protect OnPartitionLost callback against unassigned groups
```
Comment (lahsivjar) [inline .chloggen/40920-fix-franzgo-panic.yaml]:
```suggestion
note: Protect partition lost/revoke callback against unassigned groups
```

**Review by axw — APPROVED** [review]
I don't love testing private methods directly like this, but if we can't force it with kfake then I suppose this is the best option. Thanks for the fix!

**Comment by lahsivjar** [comment]
Thanks @axw! Completely agree about the test, if I find a better solution to test I will create a followup PR.

**Review by andrzej-stencel — APPROVED** [review]
