### PR TITLE
[chore][receiver/prometheusreceiver]: fix Openmetrics tests

### LINKED ISSUE #42376: [receiver/prometheusreceiver]: Report for failed tests on main
Auto-generated report for `__run` job build.

Link to failed build: https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/17339418097

#### Test Failures
-  `TestOpenMetricsPositive/histogram_exemplars`
```
=== RUN   TestOpenMetricsPositive/histogram_exemplars
    metrics_receiver_open_metrics_test.go:54: 
        	Error Trace:	/home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/receiver/prometheusreceiver/metrics_receiver_open_metrics_test.go:54
        	            				/home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/receiver/prometheusreceiver/metrics_receiver_helper_test.go:831
        	Error:      	"5" is not greater than "5"
        	Test:       	TestOpenMetricsPositive/histogram_exemplars
--- FAIL: TestOpenMetricsPositive/histogram_exemplars (0.00s)

```
-  `TestOpenMetricsPositive`
```
=== RUN   TestOpenMetricsPositive
--- FAIL: TestOpenMetricsPositive (6.09s)

```

**Note**: Information about any subsequent build failures that happen while
this issue is open, will be added as comments with more information to this issue.

### PR DESCRIPTION
**Pull request by krajorama**
#### Description

The current test doesn't actually work most of the time as it only asserts on having scraped series when there's a single set of resource metrics in the result.

Most of the times scrape is so fast it does two scrapes, the second being unsuccessful and having "up" == 0 and metrics stale in it.

I've fixed the assert function to always actually assert.

Consequences:

Some histogram test cases don't match the implementation where we ignore such histograms that lack the Count field. Since the tests aren't about missing Count, I've fixed them.

Some test cases are valid but don't have series in them, so those need a different assert.

We could consider adding a test case for missing count.

#### Link to tracking issue
Fixes #42376

#### Testing
Unit tests.

#### Documentation
N/A

### CODE REVIEW

File: receiver/prometheusreceiver/metrics_receiver_open_metrics_test.go [hunk 1]
```diff
@@ -45,14 +46,24 @@ var skippedTests = map[string]struct{}{
 	"bad_exemplars_on_unallowed_samples_3": {}, "bad_exemplars_on_unallowed_metric_types_2": {},
 }
 
-func verifyPositiveTarget(t *testing.T, _ *testData, mds []pmetric.ResourceMetrics) {
+var positiveTestsWithOutSeries = []string{"null_byte", "empty_metadata"}
```
Comment (ArthurSens) [inline receiver/prometheusreceiver/metrics_receiver_open_metrics_test.go]:
```suggestion
var positiveTestsWithoutSeries = []string{"null_byte", "empty_metadata"}
```

nit

**Review by ArthurSens — COMMENTED** [review]
I'm struggling to understand how this test suddenly started to fail constantly.

The file hasn't been touched for at least 5 months, and the test itself hasn't been touched for the last 4 years 🤔

**Comment by krajorama** [comment]
> I'm struggling to understand how this test suddenly started to fail constantly.
> 
> The file hasn't been touched for at least 5 months, and the test itself hasn't been touched for the last 4 years 🤔

I'm sure it's a timing issue. When I added a bit more waiting the test went into the branch where it didn't actually assert and thus didn't fail.

Not sure what changed the timing though.

**Comment by ArthurSens** [comment]
Weird 😅

**Review by ArthurSens — APPROVED** [review]

**Comment by mx-psi** [comment]
This failed again on main, see #42430
