### PR TITLE
[receiver/splunkhec] HEC metrics accepts empty string Event

### LINKED ISSUE #38464: [receiver/splunkhec] Metrics ingestion behavior is not consistent with Splunk Cloud/Enterprise
### Component(s)

receiver/splunkhec

## Description
Currently, there is inconsistent behavior between splunkhecreceiver vs splunk enterprise/cloud on metrics ingestion support. Ideally, hecreceiver should align with splunk enterprise/cloud.

The current [documentation](https://docs.splunk.com/Documentation/Splunk/9.4.0/Metrics/GetMetricsInOther#Send_data_to_a_metrics_index_over_HTTP) says `Metrics data, which requires an event field set to metric.`, but this is not accurate and we are working with splunk doc team to update this.

The `event` field can be optional

## Steps to Reproduce
1. create a metric event
2. do not set `event` field at all
3. send to splunkhecreceiver

## Expected Result
1. data is accepted

## Actual Result
1. data is rejected with 400

### Collector version

latest

### Environment information

N/A

### OpenTelemetry Collector configuration

```yaml

```

### Log output

```shell

```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by timannguyen**
#### Description

Splunk HEC metrics accepts metrics when `"event": ""`. This aligns with Splunk HEC behavior

#### Link to tracking issue
Fixes [38464](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/38464)

#### Testing

Unit tests

### CODE REVIEW

**Comment by atoulme** [comment]
Please add a changelog. `make chlog-new` will create a template for this.

File: internal/splunk/common.go [hunk 1]
```diff
@@ -66,7 +66,7 @@ type Event struct {
 
 // IsMetric returns true if the Splunk event is a metric.
 func (e *Event) IsMetric() bool {
-	return e.Event == HecEventMetricType || (e.Event == nil && len(e.GetMetricValues()) > 0)
+	return e.Event == HecEventMetricType || ((e.Event == nil || e.Event == "") && len(e.GetMetricValues()) > 0)
```
Comment (splunkericl) [inline internal/splunk/common.go:69]: Can you test against splunk if this is the correct check? I was told: `As tested out, the event field is optional. When presented, it can also be any string and does not have to be of value metric. A possible way of updating this would be to change`

**Review by atoulme — APPROVED** [review]
