### PR TITLE
[processor/k8sattributes]: fix pod_association for container.id

### LINKED ISSUE #40745: [processor/k8sattributesprocessor] pod_association not working for source: container.id
### Expected result

Associate and enrich ResourceProfile.Attribute with additional k8s information based on container.id.

### Component(s)

processor/k8sattributes

### What happened?

Using the container ID starting with `581f3ac4` as an example.

This container ID is known by kubectl:
```
$ kubectl get pods --all-namespaces -o jsonpath='{range .items[*]}{range .status.containerStatuses[*]}{.containerID}{"\n"}{end}{end}' | grep 581f3ac4745d68495d71651b76e5ff19f42be92323c25d9281120d3594931a88
containerd://581f3ac4745d68495d71651b76e5ff19f42be92323c25d9281120d3594931a88
```

From debug logs of `k8sattributes` one can also tell, that it was detected in some way:
```
2025-06-16T14:09:37.044163599Z 2025-06-16T14:09:37.044Z	debug	k8sattributesprocessor@v0.128.0/processor.go:143	evaluating pod identifier	{"resource": {"service.instance.id": "851203be-4a32-4115-aa09-bb73bfe7e1d8", "service.name": "otelcol-ebpf-profiler", "service.version": "0.128.0"}, "otelcol.component.id": "k8sattributes", "otelcol.component.kind": "processor", "otelcol.pipeline.id": "profiles", "otelcol.signal": "profiles", "value": [{"Source":{"From":"resource_attribute","Name":"container.id"},"Value":"581f3ac4745d68495d71651b76e5ff19f42be92323c25d9281120d3594931a88"},{"Source":{"From":"","Name":""},"Value":""},{"Source":{"From":"","Name":""},"Value":""},{"Source":{"From":"","Name":""},"Value":""}]}
```

But looking at the debug output of the exporter, resource attributes were not enriched based on the container.id:
```
[..]
2025-06-16T14:09:37.081041887Z ResourceProfiles #3
2025-06-16T14:09:37.081046047Z Resource SchemaURL: https://opentelemetry.io/schemas/1.6.1
2025-06-16T14:09:37.081047762Z Resource attributes:
2025-06-16T14:09:37.081049321Z      -> container.id: Str(581f3ac4745d68495d71651b76e5ff19f42be92323c25d9281120d3594931a88)
2025-06-16T14:09:37.081050896Z      -> host.name: Str(otelcol-profiler-2bgb5)
2025-06-16T14:09:37.081052521Z      -> os.type: Str(linux)
2025-06-16T14:09:37.081053973Z ScopeProfiles #0
[..]
```

### Collector version

v0.128.0

### OpenTelemetry Collector configuration

```yaml
receivers:
  profiling:
    SamplesPerSecond: 19

processors:
  resourcedetection:
    detectors: [ system ]
    system:
      hostname_sources: [ "os" ]
      resource_attributes:
        host.id:
          enabled: true
        host.name:
          enabled: true
        os.type:
          enabled: true
  k8sattributes:
    auth_type: "serviceAccount"
    passthrough: false
    filter:
      # only retrieve pods running on the same node as the collector
      node_from_env_var: KUBERNETES_NODE_NAME
    extract:
      # The attributes provided in 'metadata' will be added to associated resources
      metadata:
        - k8s.pod.name
        - k8s.pod.uid
        - k8s.deployment.name
        - k8s.namespace.name
        - k8s.node.name
        - k8s.pod.start_time
        - service.namespace
        - service.name
        - service.version
        - service.instance.id
      labels:
        # This label extraction rule takes the value 'app.kubernetes.io/component' label and maps it to the 'app.label.component' attribute which will be added to the associated resources
        - tag_name: app.label.component
          key: app.kubernetes.io/component
          from: pod
      otel_annotations: true 
    pod_association:
      - sources:
          # This rule associates all resources containing the 'container.id' attribute with the matching pods. If this attribute is not present in the resource, this rule will not be able to find the matching pod.
          - from: resource_attribute
            name: container.id

exporters:
  debug:
    verbosity: detailed

service:
  telemetry:
    logs:
      level: debug  # Set the global logging level to debug
  pipelines:
    profiles:
      receivers: [ profiling ]
      processors: [ resourcedetection, k8sattributes ]
      exporters: [ debug ]
```

### Log output

```shell

```

### Additional context

<details>
<summary> used manifest.yaml </summary>

```
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/warn: privileged
  name: otelcol-profiler
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: otelcol-profiler
  namespace: otelcol-profiler
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  - pods
  - namespaces
  - endpoints
  - services
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - replicasets
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: otelcol-profiler
  namespace: otelcol-profiler
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: otelcol-profiler
subjects:
- kind: ServiceAccount
  name: otelcol-profiler
  namespace: otelcol-profiler
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  namespace: otelcol-profiler
  name: otelcol-profiler
spec:
  selector:
    matchLabels:
      app: otelcol-profiler
  template:
    metadata:
    spec:
      hostPID: true
      containers:
        - name: otelcol-profiler
          image: flehner/testing:20250616011
          securityContext:
            procMount: "Unmasked"
            privileged: true
            capabilities:
              add:
                - SYS_ADMIN
          resources:
            limits:
              memory: 500Mi
              cpu: "2"
            requests:
              memory: 500Mi
              cpu: "2"
          env:
            - name: KUBERNETES_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          volumeMounts:
            - name: debugfs
              mountPath: /sys/kernel/debug
      serviceAccountName: otelcol-profiler
      volumes:
        - name: debugfs
          hostPath:
            path: /sys/kernel/debug
            type: Directory
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: otelcol-profiler
  namespace: otelcol-profiler

```

</details>

### PR DESCRIPTION
**Pull request by florianl**
#### Description

When setting pod_association to container.id it can not match at the moment, as it will look up pod.Attributes and fail to match. Update getIdentifiersFromAssoc() to generate PodIdentifier also from pod.Containers.ByID. This then also covers the case, where a single k8s.pod.UID covers multiple container.ids.

#### Link to tracking issue

Fixes https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/40745

### CODE REVIEW

File: processor/k8sattributesprocessor/internal/kube/client.go [hunk 1]
```diff
@@ -999,6 +1003,7 @@ func (c *WatchClient) getIdentifiersFromAssoc(pod *Pod) []PodIdentifier {
 					break
 				}
 				ret[i] = PodIdentifierAttributeFromSource(source, pod.Address)
+				gotPodConnection = true
```
Comment (florianl) [inline processor/k8sattributesprocessor/internal/kube/client.go]: Bug that I noticed while writing the test. We don't want duplicate entries for `PodIdentifierAttributeFromSource(source, pod.Address)`.

File: processor/k8sattributesprocessor/internal/kube/client.go [hunk 2]
```diff
@@ -1008,18 +1013,23 @@ func (c *WatchClient) getIdentifiersFromAssoc(pod *Pod) []PodIdentifier {
 					attr = pod.Name
 				case string(conventions.K8SPodUIDKey):
 					attr = pod.PodUID
+					gotPodUID = true
```
Comment (florianl) [inline processor/k8sattributesprocessor/internal/kube/client.go]: Bug that I noticed while writing the test. We don't want duplicate entries for `K8SPodUIDKey`.

File: processor/k8sattributesprocessor/internal/kube/client.go [hunk 3]
```diff
@@ -1028,21 +1038,37 @@ func (c *WatchClient) getIdentifiersFromAssoc(pod *Pod) []PodIdentifier {
...
+				// As there can be multiple container.IDs per pod,
+				// one PodIdentifier is added per container.ID.
+				cIDs := maps.Keys(pod.Containers.ByID)
+				for cID := range cIDs {
+					retCpy := ret
+					retCpy[retID4containerID] = PodIdentifierAttributeFromSource(AssociationSource{
+						From: ResourceSource,
+						Name: string(conventions.ContainerIDKey),
+					}, cID)
+					ids = append(ids, retCpy)
```
Comment (dmitryax) [inline processor/k8sattributesprocessor/internal/kube/client.go:1047]: Not sure if this will work when pod attributes are defined _after_ `container.id` given that we drop the rest here.
```
    pod_association:
      - sources:
          - from: resource_attribute
            name: container.id
          - from: resource_attribute
            name: k8s.pod.name
```

File: processor/k8sattributesprocessor/internal/kube/client.go (hunk 1 above)
Comment (dmitryax) [reply processor/k8sattributesprocessor/internal/kube/client.go]: Can you please move this to a separate PR if it's unrelated. It's unclear what specific problem does it resolve

File: processor/k8sattributesprocessor/internal/kube/client.go (hunk 3 above)
Comment (florianl) [reply processor/k8sattributesprocessor/internal/kube/client.go:1047]: For this case, there is the testcase called `multiple associations` where a pod attribute is defined after `container.id`.

File: processor/k8sattributesprocessor/internal/kube/client.go (hunk 1 above)
Comment (florianl) [reply processor/k8sattributesprocessor/internal/kube/client.go]: Removed from this PR as requested with https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/40841/commits/e8d8ba11dc33a8534e520626a4c2c5ef98202ffb

File: processor/k8sattributesprocessor/internal/kube/client.go (hunk 2 above)
Comment (florianl) [reply processor/k8sattributesprocessor/internal/kube/client.go]: Removed from this PR as requested in https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/40841#discussion_r2159349047 with https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/40841/commits/e8d8ba11dc33a8534e520626a4c2c5ef98202ffb

File: processor/k8sattributesprocessor/internal/kube/client.go (hunk 3 above)
Comment (dmitryax) [reply processor/k8sattributesprocessor/internal/kube/client.go:1047]: Oh right. We are doing it outside of the loop 👍

**Review by dmitryax — APPROVED** [review]
