### PR TITLE
[chore][exporter/elasticsearch] Fix flaky lru time based test

### LINKED ISSUE #42310: [exporter/elasticsearchexporter/internal/lru]: Report for failed tests on main
Auto-generated report for `__run_3` job build.

Link to failed build: https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/17288205471

#### Test Failures
-  `TestLRUSetLifeTime`
```
=== RUN   TestLRUSetLifeTime
    lruset_test.go:57: 
        	Error Trace:	D:/a/opentelemetry-collector-contrib/opentelemetry-collector-contrib/exporter/elasticsearchexporter/internal/lru/lruset_test.go:57
        	            				D:/a/opentelemetry-collector-contrib/opentelemetry-collector-contrib/exporter/elasticsearchexporter/internal/lru/lruset.go:40
        	            				D:/a/opentelemetry-collector-contrib/opentelemetry-collector-contrib/exporter/elasticsearchexporter/internal/lru/lruset_test.go:56
        	Error:      	Should be true
        	Test:       	TestLRUSetLifeTime
--- FAIL: TestLRUSetLifeTime (0.55s)

```

**Note**: Information about any subsequent build failures that happen while
this issue is open, will be added as comments with more information to this issue.

### PR DESCRIPTION
**Pull request by carsonip**
#### Description

Fix flaky lru time based test

#### Link to tracking issue
Fixes #42310

### CODE REVIEW

File: exporter/elasticsearchexporter/internal/lru/lruset_test.go [hunk 1]
```diff
@@ -1,10 +1,13 @@
 // Copyright The OpenTelemetry Authors
 // SPDX-License-Identifier: Apache-2.0
 
+//go:build goexperiment.synctest
```
Comment (songy23) [inline exporter/elasticsearchexporter/internal/lru/lruset_test.go]: JFYI I believe adding this Go build tag effectively skips this test in CIs, because CIs only run tests with no tags

**Review by songy23 — APPROVED** [review]

File: exporter/elasticsearchexporter/internal/lru/lruset_test.go (hunk 1 above)
Comment (carsonip) [reply exporter/elasticsearchexporter/internal/lru/lruset_test.go]: hmm, that is unfortunate. In that case I can try to make it less flaky, but CI on windows always have these kind of slow test issues

**Comment by songy23** [comment]
needs to fix linter

**Review by songy23 — APPROVED** [review]

**Comment by mx-psi** [comment]
Looks like we had another instance of this after this PR was merged, see #42413
