### PR TITLE
[processor/k8sattributes] Support name:tag@digest image name format

### LINKED ISSUE #36131: [processor/k8sattributes] Support `name:tag@digest` image name format
### Component(s)

processor/k8sattributes

## Description

For better integrity guarantees we've started using `name:tag@digest` image reference format (e.g. `alpine:3.19@sha256:ae65dbf8749a7d4527648ccee1fa3deb6bfcae34cbc30fc67aa45c44dcaa90ee`).

It doesn't seem to be part of OCI image spec, but many projects use it (for example [Karpenter](https://github.com/aws/karpenter-provider-aws/blob/main/charts/karpenter/templates/_helpers.tpl#L72)).

## Steps to Reproduce

- Deploy Pod with image `alpine:3.19@sha256:ae65dbf8749a7d4527648ccee1fa3deb6bfcae34cbc30fc67aa45c44dcaa90ee`
- Create collector with `k8sattributes` processor:
```yaml
processors:
  k8sattributes: 
    extract:
      metadata:
      - k8s.node.name
      - k8s.deployment.name
      - k8s.replicaset.name
      - k8s.daemonset.name
      - k8s.job.name
      - k8s.cronjob.name
      - k8s.statefulset.name
      - k8s.container.name
      - container.image.name
      - container.image.tag
```
- Observe telemetry metadata

## Expected Result

```yaml
container.image.name: alpine
container.image.tag: 3.19
```

## Actual Result

```yaml
container.image.name: alpine:3.19@sha
container.image.tag: ae65dbf8749a7d4527648ccee1fa3deb6bfcae34cbc30fc67aa45c44dcaa90ee
```

So basically split happens on last colon, not the first one.

### Collector version

0.107.0

## Environment
K8s: 1.29

### OpenTelemetry Collector configuration

_No response_

### Log output

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by spiffyy99**
#### Description
Fixed issue with `k8sattributesprocessor` where digest is not properly separated from tag if both are present. used official docker library to perform parsing.

#### Link to tracking issue
Fixes https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/36131

#### Testing
unit tests
integration/e2e tests

#### Documentation
N/A. Fields are already described correctly, this is simply fixing parsing logic

### CODE REVIEW

File: processor/k8sattributesprocessor/internal/kube/client.go [hunk 1]
```diff
@@ -643,16 +661,14 @@ func (c *WatchClient) extractPodContainersAttributes(pod *api_v1.Pod) PodContain
...
-				if nameTagSep > 0 {
-					container.ImageName = spec.Image[:nameTagSep]
-				} else {
-					container.ImageName = spec.Image
+			name, tag, err := parseNameAndTagFromImage(spec.Image)
+			if err == nil {
+				if c.Rules.ContainerImageName {
+					container.ImageName = name
+				}
+				if c.Rules.ContainerImageTag {
```
Comment (ChrsMark) [inline processor/k8sattributesprocessor/internal/kube/client.go:669]: 👍🏽 

Since we are on it, I also wonder if we should override the `ImageTag` from the container's status in case it is available.
See https://github.com/kubernetes/api/blob/v0.32.0-alpha.3/core/v1/types.go#L3047-L3055.

File: processor/k8sattributesprocessor/internal/kube/client.go [hunk 2]
```diff
@@ -643,16 +661,14 @@ func (c *WatchClient) extractPodContainersAttributes(pod *api_v1.Pod) PodContain
 	if c.Rules.ContainerImageName || c.Rules.ContainerImageTag {
 		for _, spec := range append(pod.Spec.Containers, pod.Spec.InitContainers...) {
 			container := &Container{}
-			nameTagSep := strings.LastIndex(spec.Image, ":")
-			if c.Rules.ContainerImageName {
-				if nameTagSep > 0 {
-					container.ImageName = spec.Image[:nameTagSep]
-				} else {
-					container.ImageName = spec.Image
+			name, tag, err := parseNameAndTagFromImage(spec.Image)
```
Comment (ChrsMark) [inline processor/k8sattributesprocessor/internal/kube/client.go:664]: Could we reflect this logic in the documentation as well? Something like what was described at https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/36131#issuecomment-2452475338

**Review by ChrsMark — COMMENTED** [review]
Thank's for working on this @spiffyy99!

I think the fix is in the right direction but I left some concerns.

File: processor/k8sattributesprocessor/e2e_test.go [hunk 3]
```diff
@@ -816,7 +818,7 @@ func TestE2E_NamespacedRBACNoPodIP(t *testing.T) {
 				"k8s.container.name":           newExpectedValue(equal, "telemetrygen"),
 				"container.image.name":         newExpectedValue(equal, "ghcr.io/open-telemetry/opentelemetry-collector-contrib/telemetrygen"),
 				"container.image.repo_digests": newExpectedValue(shouldnotexist, ""),
-				"container.image.tag":          newExpectedValue(equal, "latest"),
+				"container.image.tag":          newExpectedValue(shouldnotexist, ""),
```
[the remark this answers is not in the document]
Comment (spiffyy99) [reply processor/k8sattributesprocessor/e2e_test.go:821]: oh good point. i'll add handling for this back. this definitely would've been a regression

**Comment by spiffyy99** [comment]
thanks for the review christos.

File: processor/k8sattributesprocessor/internal/kube/client.go (hunk 1 above)
Comment (spiffyy99) [reply processor/k8sattributesprocessor/internal/kube/client.go:669]: sorry, don't think I understand this point? i don't see any field `ImageTag` in `ContainerStatus`?

File: processor/k8sattributesprocessor/e2e_test.go (hunk 3 above)
[the remark this answers is not in the document]
Comment (spiffyy99) [reply processor/k8sattributesprocessor/e2e_test.go:821]: actually looking at the code, we didn't assume this before. I can add this assertion in easily, though. Since it fits the `docker pull` behavior: https://docs.docker.com/reference/cli/docker/image/pull/#pull-an-image-from-docker-hub

File: processor/k8sattributesprocessor/e2e_test.go [hunk 4]
```diff
@@ -504,7 +505,7 @@ func TestE2E_NamespacedRBAC(t *testing.T) {
 				"k8s.container.name":           newExpectedValue(equal, "telemetrygen"),
 				"container.image.name":         newExpectedValue(equal, "ghcr.io/open-telemetry/opentelemetry-collector-contrib/telemetrygen"),
 				"container.image.repo_digests": newExpectedValue(regex, "ghcr.io/open-telemetry/opentelemetry-collector-contrib/telemetrygen@sha256:[0-9a-fA-f]{64}"),
-				"container.image.tag":          newExpectedValue(equal, "latest"),
+				"container.image.tag":          newExpectedValue(shouldnotexist, ""),
```
[the remark this answers is not in the document]
Comment (spiffyy99) [reply processor/k8sattributesprocessor/e2e_test.go:508]: yep, described here as well: https://docs.docker.com/reference/cli/docker/image/pull/#pull-an-image-from-docker-hub

File: processor/k8sattributesprocessor/internal/kube/client.go (hunk 2 above)
Comment (spiffyy99) [reply processor/k8sattributesprocessor/internal/kube/client.go:664]: done

File: processor/k8sattributesprocessor/e2e_test.go (hunk 4 above)
[the remark this answers is not in the document]
Comment (spiffyy99) [reply processor/k8sattributesprocessor/e2e_test.go:508]: actually, there's an edge case here i realized. for this image we have a digest but no tag. in this case docker won't assume `latest `. 

so the logic should look like this: attempt to parse the tag. if no tag, check if a digest exists. if so, return. if not, assume latest as the tag.

File: processor/k8sattributesprocessor/internal/kube/client.go (hunk 1 above)
Comment (ChrsMark) [reply processor/k8sattributesprocessor/internal/kube/client.go:676]: I was referring to [`Image`](https://github.com/kubernetes/api/blob/dc555a599a635e3247477cb88d7ecdc5727311e8/core/v1/types.go#L3051) but checking it again it can also take a `sha:digest` as value so this would complex things. We could evaluate this in the future but let's leave it out for now.

File: processor/k8sattributesprocessor/e2e_test.go (hunk 4 above)
[the remark this answers is not in the document]
Comment (ChrsMark) [reply processor/k8sattributesprocessor/e2e_test.go:508]: > so the logic should look like this: attempt to parse the tag. if no tag, check if a digest exists. if so, return. if not, assume latest as the tag.

That makes sense!

File: processor/k8sattributesprocessor/e2e_test.go (hunk 3 above)
[the remark this answers is not in the document]
Comment (ChrsMark) [reply processor/k8sattributesprocessor/e2e_test.go:821]: Ah right, the test had `ghcr.io/open-telemetry/opentelemetry-collector-contrib/telemetrygen:latest` that's why it was `latest` in the test. 

I'm fine with what was described at https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/36145/files#r1832085419.

**Review by ChrsMark — COMMENTED** [review]
Overall looks good. Could we add a section in the docs describing the logic from https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/36145/files#r1832085419?

File: processor/k8sattributesprocessor/documentation.md [hunk 5]
```diff
@@ -4,33 +4,33 @@
 
 ## Resource Attributes
 
-| Name | Description | Values | Enabled |
-| ---- | ----------- | ------ | ------- |
+| Name | Description                                                                                                                                           | Values | Enabled |
```
Comment (ChrsMark) [inline processor/k8sattributesprocessor/documentation.md:7]: That file is automatically generated by the `metadata.yaml`. Please apply the edits at https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/3f9f88b8316345dd0cfc535ae1543e8412899cea/processor/k8sattributesprocessor/metadata.yaml#L109 and run `make generate` to update the `documentation.md` properly.

Comment (spiffyy99) [reply processor/k8sattributesprocessor/documentation.md]: done!

File: processor/k8sattributesprocessor/e2e_test.go [hunk 6]
```diff
@@ -503,9 +504,8 @@ func TestE2E_NamespacedRBAC(t *testing.T) {
 				"k8s.labels.app":               newExpectedValue(equal, "telemetrygen-"+testID+"-traces-deployment"),
 				"k8s.container.name":           newExpectedValue(equal, "telemetrygen"),
 				"container.image.name":         newExpectedValue(equal, "ghcr.io/open-telemetry/opentelemetry-collector-contrib/telemetrygen"),
-				"container.image.repo_digests": newExpectedValue(regex, "ghcr.io/open-telemetry/opentelemetry-collector-contrib/telemetrygen@sha256:[0-9a-fA-f]{64}"),
-				"container.image.tag":          newExpectedValue(equal, "latest"),
-				"container.id":                 newExpectedValue(exist, ""),
+				"container.image.repo_digests": newExpectedValue(regex, "ghcr.io/open-telemetry/opentelemetry-collector-contrib/telemetrygen@sha256:[0-9a-fA-f]{64}"), "container.image.tag": newExpectedValue(shouldnotexist, ""),
```
Comment (ChrsMark) [inline processor/k8sattributesprocessor/e2e_test.go:507]: nit: could you please split these 2 fields in different lines? (same for the tests bellow)

**Review by ChrsMark — APPROVED** [review]
LGTM. Thank's @spiffyy99!

@TylerHelmuth please take a look

File: processor/k8sattributesprocessor/e2e_test.go (hunk 6 above)
Comment (spiffyy99) [reply processor/k8sattributesprocessor/e2e_test.go:507]: oops, must have missed that

**Comment by spiffyy99** [comment]
@dmitryax @fatsheep9146 @TylerHelmuth could one of you take a look at this? thanks!

File: processor/k8sattributesprocessor/internal/kube/client.go [hunk 7]
```diff
@@ -666,6 +666,30 @@ func removeUnnecessaryPodData(pod *api_v1.Pod, rules ExtractionRules) *api_v1.Po
 	return &transformedPod
 }
 
+// parseAttributesFromImage parses the image name and tag for differently-formatted image names.
+// returns "latest" as the default if tag not present. also checks if the image contains a digest.
+// if it does, no latest tag is assumed.
+func parseNameAndTagFromImage(image string) (name, tag string, err error) {
```
Comment (rogercoll) [inline processor/k8sattributesprocessor/internal/kube/client.go:672]: Should we use the already available internal [docker.ParseImageName](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/internal/common/docker/images.go#L23) function instead?

I would prefer to all components use the same strategy for common functionalities. Note that the shared function cannot parse images with digest at the moment and should be fixed beforehand: https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/36279

Comment (ChrsMark) [reply processor/k8sattributesprocessor/internal/kube/client.go:672]: Having a single implementation makes sense.
Also I think the package should be renamed to `container` and not `docker` since it doesn't only cover docker.

**Review by TylerHelmuth — COMMENTED** [review]
@spiffyy99 your updates to the test give me confidence that we set the new attribute correctly, but are there still tests for `latest` or `v0.112.0` (tests for when no digest is used)?

File: processor/k8sattributesprocessor/internal/kube/client.go (hunk 7 above)
Comment (TylerHelmuth) [reply processor/k8sattributesprocessor/internal/kube/client.go:672]: @spiffyy99 I was gonna merge this before the release but now I want to make our test coverage is still handling when no digest is set. If you get to using `docker.ParseImageName` before this is merged I'll close the issue.

File: processor/k8sattributesprocessor/README.md [hunk 8]
```diff
@@ -193,7 +193,8 @@ the processor associates the received trace to the pod, based on the connection
     "k8s.pod.name": "telemetrygen-pod",
     "k8s.pod.uid": "038e2267-b473-489b-b48c-46bafdb852eb",
     "container.image.name": "telemetrygen",
-    "container.image.tag": "latest"
+    "container.image.tag": "0.112.0", 
+    "container.image.repo_digests": "ghcr.io/open-telemetry/opentelemetry-collector-contrib/telemetrygen@sha256:b248ef911f93ae27cbbc85056d1ffacc87fd941bbdc2ffd951b6df8df72b8096"
```
Comment (TylerHelmuth) [inline processor/k8sattributesprocessor/README.md:197]: @spiffyy99 the metadata.yaml needs updated with this new attribute. Also higher up in this README where we list the container attributes the processor can add.

Comment (TylerHelmuth) [inline processor/k8sattributesprocessor/README.md:197]: @ChrsMark is [container.image.repo_digests](https://github.com/open-telemetry/semantic-conventions/blob/main/docs/attributes-registry/container.md#container-image-repo-digests) supposed to be a list of strings?

Comment (spiffyy99) [reply processor/k8sattributesprocessor/README.md:197]: https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/processor/k8sattributesprocessor/metadata.yaml#L106 it seems like it's already here.

Comment (spiffyy99) [reply processor/k8sattributesprocessor/README.md:197]: https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/processor/k8sattributesprocessor/metadata.yaml#L106

that's interesting. it does say it's a slice here. but all of the tests (including before this MR was made) generate a single string. maybe a documentation error?

File: processor/k8sattributesprocessor/internal/kube/client.go (hunk 7 above)
Comment (spiffyy99) [reply processor/k8sattributesprocessor/internal/kube/client.go:672]: sure, I can update.

**Comment by spiffyy99** [comment]
> @spiffyy99 your updates to the test give me confidence that we set the new attribute correctly, but are there still tests for `latest` or `v0.112.0` (tests for when no digest is used)?

@TylerHelmuth yes, there are tests with only the version, and no version.

https://github.com/spiffyy99/opentelemetry-collector-contrib/blob/fix-k8s-image-parsing/processor/k8sattributesprocessor/internal/kube/client_test.go#L1496-L1513

this is also in the e2e tests. we have cases with no tag or digest, tag only, digest only, and both.

File: processor/k8sattributesprocessor/internal/kube/client.go (hunk 7 above)
Comment (spiffyy99) [reply processor/k8sattributesprocessor/internal/kube/client.go:672]: actually, looking at this further, wouldn't it be better to use the official docker api code for things like this? i'm sure this regex is correct as well but I'd think that the official one is a better practice (reference.Parse).

another option is we can update `docker.ParseImageName` to use `reference.Parse`, but it seems like that function is used in a bunch

i'm not the one maintaining this though, so I don't feel strongly. just pointing it out

File: processor/k8sattributesprocessor/README.md (hunk 8 above)
Comment (ChrsMark) [reply processor/k8sattributesprocessor/README.md:197]: It is a list of strings yes. It should be fixed in that example.

It is also a list of strings in the test at https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/7ff7d1e6fbe0cca7a59f9fe3b69e38b28a7e7361/processor/k8sattributesprocessor/processor_test.go#L1209 (as it should be).

@spiffyy99 could you share in which tests it is a single string?

File: processor/k8sattributesprocessor/internal/kube/client.go [hunk 9]
```diff
@@ -666,6 +666,30 @@ func removeUnnecessaryPodData(pod *api_v1.Pod, rules ExtractionRules) *api_v1.Po
 	return &transformedPod
 }
 
+// parseAttributesFromImage parses the image name and tag for differently-formatted image names.
+// returns "latest" as the default if tag not present. also checks if the image contains a digest.
+// if it does, no latest tag is assumed.
```
Comment (fatsheep9146) [inline processor/k8sattributesprocessor/internal/kube/client.go:671]: some small nits
// parseNameAndTagFromImage parses the image name and tag for differently-formatted image names.
// returns "latest" as the default if tag not present. It also checks if the image contains a digest,
// if it does, no latest tag is assumed.

Comment (spiffyy99) [reply processor/k8sattributesprocessor/internal/kube/client.go:671]: updated

File: processor/k8sattributesprocessor/README.md (hunk 8 above)
Comment (ChrsMark) [reply processor/k8sattributesprocessor/README.md]: I think this check can just catch the slice case as well. See https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/5ce01a357fcc0f1ed47112c9e2b5165f02c751f9/processor/k8sattributesprocessor/e2e_test.go#L1200-L1204.

https://go.dev/play/p/Lq2hbyPl4cj

So I would say that since the example of this PR is updated now we should be fine.

Comment (spiffyy99) [reply processor/k8sattributesprocessor/README.md]: thanks for clarifying.

**Review by TylerHelmuth — APPROVED** [review]

**Comment by zarbis** [comment]
@spiffyy99 thanks for the fix!
