### PR TITLE
[processor/transform] Add enum capabilities to grammar and contexts

### LINKED ISSUE #10349: [processor/transform] Improve processor's ability to handle enums
The transform processor currently has messy support for fields that are enums in the protobufs.  Some fields, like `metric.aggregation_temporality`, use the numeric representation in some functions but a string representation in others.  Other fields are accessed using pdata representation that don't allow comparison with the query language's parse fields.  For example, the where clause `... where kind == 2` does not work because `kind` is returned for comparison as an int32 but `2` is interpreted by the parser as an `int64`

The processor as a whole needs a solution for handling enums.  Some enums, like `severity_number`, should be able to be interacted with via the numeric representation so that comparisons like `<` and `>` can be used, but should also be able to be represented as a string for readability. Others enums, such as `aggregation_temporality` might only ever needs represented as a string.

All fields should be usable in a condition.  At the moment comparisons's of literal values in a condition are always string, int64, or float64, so we need a way to access enums so that they are comparable with at least one of these types.

I've reviewed the access functions for each signal and identified this fields as needing dealt with

**Traces**
- `kind`:  Currently accessed as an int32 so does not work in conditions.  Should it be accessible as a string?
- `status.code`:  Currently accessed as an int32 so does not work in conditions.  Should it be accessible as a string?

**Metrics**
- `metric.type`: Currently accessed as a string.  This field isn't a enum in the protos but is represented as a numeric in pdata so adding it here to be reviewed.
- `metric.aggregation_temporality`:  Accessed as a int64, but that makes it hard to interpret queries.  Should be allowed to use a string representation ("unspecified, "delta", and "cumulative").
- `flags`: Accessed as a uint32 so doesn't work in comparison.  Should it be accessible as a string?

**Logs**
- `severity_number`: Accessed as an int32 so doesn't work in conditions.  Should it be accessible as a string?

**Additional context**
There are other fields that have access bugs when being used in a condition, but I will open a separate issue for those.

### PR DESCRIPTION
**Pull request by TylerHelmuth**
**Description:** 
This PR adds to the grammar the ability to handle enums.  All Enums are int64.   Enums are always used as native int64s in Conditions to ensure comparison between either an Enum or an int64 works as expected. If a function wants to use an Enum as a parameter, it must use the Enum type. 

Contexts must supply a ParseEnum function that will attempt to parse a path as an enum.  This allows contexts to define their own symbol tables.

All contexts' enum accessors have been updated to Get and Set enums as int64s.

**Link to tracking Issue:** 
Fixes #10349

**Testing:** 
Updated and added unit tests.

**Documentation:**
Updated README

### CODE REVIEW

File: processor/transformprocessor/internal/common/parser.go [hunk 1]
```diff
@@ -107,7 +107,7 @@ func (n *IsNil) Capture(_ []string) error {
 	return nil
 }
 
-func ParseQueries(statements []string, functions map[string]interface{}, pathParser PathExpressionParser) ([]Query, error) {
+func ParseQueries(statements []string, functions map[string]interface{}, pathParser PathExpressionParser, enumParser EnumParser) ([]Query, error) {
```
Comment (anuraaga) [inline processor/transformprocessor/internal/common/parser.go:110]: Should pathParser and enumParser be merged into a single interface?

Comment (TylerHelmuth) [reply processor/transformprocessor/internal/common/parser.go:110]: I had that originally but I wanted a way interact with Enums without having to use Getters or Setters, which PathParser returns. Since Enums are static I wanted a way to return them directly from the Contexts.

**Review by anuraaga — APPROVED** [review]

**Review by djaglowski — APPROVED** [review]
