### PR TITLE
[pkg/stanza] Register missing operators

### LINKED ISSUE #26452: [receivers/tcplog] - syslog_parser not registered
### Component(s)

pkg/stanza

## Steps to Reproduce

I use OpenTelemetry Collector Builder (ocb) with this config for receivers:
```
receivers:
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/tcplogreceiver v0.84.0
```
I use syslog_parser operator in the collector config for tcplog receiver:
```
  tcplog:
    listen_address: 0.0.0.0:12345
    operators:
    - id: syslogparser
      protocol: rfc3164
      type: syslog_parser
```

I'm able to build collector with ocb and Golang 1.21 successfully, but my collector is not able to start. It produces error:
```
023/09/02 00:11:35 collector server run finished with error: failed to get config: cannot unmarshal the configuration: 1 error(s) decoding:

* error decoding 'receivers': error reading configuration for "tcplog": 1 error(s) decoding:

* error decoding 'operators[0]': unsupported type 'syslog_parser'
```

## Expected Result

syslog_parser operator is available

### Collector version

v0.84.0

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

### OpenTelemetry Collector configuration

_No response_

### Log output

_No response_

### Additional context

Workaround is to replace broken version, with my patched version:
```
replaces:
  - github.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza v0.84.0 => github.com/jangaraj/opentelemetry-collector-contrib/pkg/stanza v0.84.1
```

### PR DESCRIPTION
**Pull request by jangaraj**
**Description:** 
Registering missing operators, which may be a causing a problem, when OCB is used and missed operators are used in the OTEL collector config.

**Link to tracking Issue:** fixes #26452 

**Testing:** NA

**Documentation:** NA

I'm not sure if input operators make sense. In theory there can be case, where users may need multiple inputs (e.g. syslog, journald) in one receiver, so they probably should be also registered.

### CODE REVIEW

**Review by djaglowski — COMMENTED** [review]
Thanks for the fix @jangaraj.

Although I agree we need to add all parsers and transformers, we have intentionally omitted all input operators because these are presented as receivers. Similarly, we have included only the output operators which have been specifically requested for a use case.

File: pkg/stanza/adapter/register.go [hunk 1]
```diff
@@ -4,13 +4,16 @@
 package adapter // import "github.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza/adapter"
 
 import (
-	_ "github.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza/operator/output/file" // Register parsers and transformers for stanza-based log receivers
+	_ "github.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza/operator/output/drop"  // Register parsers and transformers for stanza-based log receivers
+	_ "github.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza/operator/output/file"
```
Comment (djaglowski) [inline pkg/stanza/adapter/register.go:8]:
```suggestion
	_ "github.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza/operator/output/file"  // Register parsers and transformers for stanza-based log receivers
```

**Review by djaglowski — APPROVED** [review]

**Comment by djaglowski** [comment]
@jangaraj, please add a changelog entry. To do this, run `make chlog-new` and fill in the generated file.

**Review by songy23 — APPROVED** [review]
