### PR TITLE
[receiver/simpleprometheus] Pass labels configuration to Prometheus properly

### LINKED ISSUE #40722: [receiver/simpleprometheus] Labels are being added incorrectly in configuration
### Component(s)

receiver/simpleprometheus

## Description

From investigation, I believe the simpleprometheus receiver has a bug with how it's passing the `label` to the Prometheus receiver's configuration. This issue was introduced in `v0.127.0`. This functionality has been working, but was technically wrong before this release. Change in behavior of the Prometheus receiver has simply exposed this issue, and it's now a bug.

**Source of issue:**
This was exposed by a [Prometheus upgrade PR](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/40103), specifically the `PromConfig.Reload` functionality. Inside the `PromConfig.Reload` there's a call to `yaml.Unmarshal`, which doesn't unmarshal the values in the [form they're being passed](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/fdf4cfbc6883340bea685bc8cb22971eb5aef6d7/receiver/simpleprometheusreceiver/receiver.go#L132-L133). 

Prometheus has its own [MarshalYaml function](https://github.com/prometheus/prometheus/blob/4aee718013c52bef1ccb336bcc21886336e6252e/discovery/targetgroup/targetgroup.go#L68) that is only taking the `model.Address` label value for the targets YAML entry. This marshalling functionality hasn't been changed in a long time, it looks like it just wasn't being exercised by this code path until now.

This was working before the upgrade PR because labels are being added to the target in the [TargetsFromGroup method](https://github.com/prometheus/prometheus/blob/4aee718013c52bef1ccb336bcc21886336e6252e/scrape/target.go#L537) which has no filtering based on label name (so any label found will be added to the target's list of labels) The target's labels are then used in [mutateReportSampleLabels](https://github.com/prometheus/prometheus/blob/4aee718013c52bef1ccb336bcc21886336e6252e/scrape/scrape.go#L721) to add to the current metric's labels.

**Proposed Solution:**
[Original two lines](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/fdf4cfbc6883340bea685bc8cb22971eb5aef6d7/receiver/simpleprometheusreceiver/receiver.go#L132-L133)

Proposed new lines:
```
					Targets: []model.LabelSet{{model.AddressLabel: model.LabelValue(cfg.Endpoint)}},
					Labels:  labels,
```
This would align the purpose and functionality of the [static_config](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#static_config).

## Steps to Reproduce

Run the collector with the provided configuration

## Expected Result

Contents from `v0.126.0`:
```
Metric #2
Descriptor:
     -> Name: scrape_duration_seconds
     -> Description: Duration of the scrape
     -> Unit: s
     -> DataType: Gauge
NumberDataPoints #0
Data point attributes:
     -> example_label: Str(example_value)
StartTimestamp: 1970-01-01 00:00:00 +0000 UTC
Timestamp: 2025-06-13 22:27:53.531 +0000 UTC
Value: 0.001685
```

## Actual Result

Results from `v0.127.0`:
```
Metric #1
Descriptor:
     -> Name: scrape_duration_seconds
     -> Description: Duration of the scrape
     -> Unit: s
     -> DataType: Gauge
NumberDataPoints #0
StartTimestamp: 1970-01-01 00:00:00 +0000 UTC
Timestamp: 2025-06-13 22:31:02.968 +0000 UTC
Value: 0.003895
```

### Collector version

`v0.127.0`

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

### OpenTelemetry Collector configuration

```yaml
receivers:
  prometheus_simple:
    collection_interval: 1s
    labels:
      example_label: example_value

exporters:
  debug:
    verbosity: detailed

service:
  pipelines:
    metrics:
      receivers: [prometheus_simple]
      exporters: [debug]
```

### Log output

```shell

```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by crobert-1**
#### Description
Provides fix as described in the issue. The original issue was the the receiver was not properly configuring the Prometheus receiver, which this is a wrapper for. This change is to simply pass the labels under the `Labels` Prometheus receiver option, rather than under `Target`.

#### Link to tracking issue
Fixes #40722

#### Testing
Manually tested on CLI. There aren't good tests for this component, shown by this bug not being caught earlier. If anyone has any ideas for good ways to add tests here, I'd be happy to add them.

### CODE REVIEW

File: receiver/simpleprometheusreceiver/receiver.go [hunk 1]
```diff
@@ -112,7 +112,6 @@ func getPrometheusConfig(cfg *Config) (*prometheusreceiver.Config, error) {
 	for k, v := range cfg.Labels {
 		labels[model.LabelName(k)] = model.LabelValue(v)
 	}
-	labels[model.AddressLabel] = model.LabelValue(cfg.Endpoint)
```
Comment (crobert-1) [inline receiver/simpleprometheusreceiver/receiver.go:115]: This label is added to `Targets` as it was before, we're just directly setting it now.

**Review by jvoravong — APPROVED** [review]

**Review by atoulme — APPROVED** [review]
