### PR TITLE
[prometheusremotewriteexporter] Drop prometheus exemplar labels when the max length is exceeded

### LINKED ISSUE #8352: [prometheusremotewriteexporter] exemplars can exceed the maximum number of allowed characters.
**Describe the bug**
As described in the [OpenMetrics Specification for Exemplars](https://github.com/OpenObservability/OpenMetrics/blob/main/specification/OpenMetrics.md#exemplars):

> The combined length of the label names and values of an Exemplar's LabelSet MUST NOT exceed 128 UTF-8 character code points. Other characters in the text rendering of an exemplar such as ",= are not included in this limit for implementation simplicity and for consistency between the text and proto formats.

The [OpenTelemetry Prometheus conversion Specification](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification%2Fmetrics%2Fdatamodel.md#exemplars-2) requires:

> filtered_attributes MUST be added as labels on the OpenMetrics exemplar unless they would exceed the OpenMetrics [limit on characters](https://github.com/OpenObservability/OpenMetrics/blob/main/specification/OpenMetrics.md#exemplars).

We currently accept all filtered attributes on PRW exemplars: https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/488e70172c662f1c32a9ef4e6245c9e650e57327/pkg/translator/prometheusremotewrite/helper.go#L353-L362.

Instead, we should drop filtered attributes if it would exceed the character limit.

### PR DESCRIPTION
**Pull request by dashpole**
**Description:**
Fixes https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/8352.  This follows the OTLP -> Prometheus specification for [handling exemplar labels](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification%2Fmetrics%2Fdatamodel.md#exemplars-2).

**Testing:**

Added a unit test

### CODE REVIEW

File: pkg/translator/prometheusremotewrite/helper.go [hunk 1]
```diff
@@ -350,16 +353,22 @@ func getPromExemplars(pt pdata.HistogramDataPoint) []prompb.Exemplar {
 			Timestamp: timestamp.FromTime(exemplar.Timestamp().AsTime()),
 		}
 
+		exemplarChars := 0
 		exemplar.FilteredAttributes().Range(func(key string, value pdata.AttributeValue) bool {
+			val := value.AsString()
+			exemplarChars += len(key) + len(val)
```
Comment (mx-psi) [inline pkg/translator/prometheusremotewrite/helper.go:359]: Being very nitpicky here but: `len` returns the number of bytes, not UTF-8 code points (see e.g. https://go.dev/play/p/_9lpGqY2gkc from https://pkg.go.dev/unicode/utf8#RuneCountInString), so at least for `val` you need to use `utf8.RuneCountInString`

Comment (Aneurysm9) [reply pkg/translator/prometheusremotewrite/helper.go:359]: Good catch.  This is probably safe since bytes must be >= runes, but would be good to not drop data unnecessarily.

File: pkg/translator/prometheusremotewrite/helper_test.go [hunk 2]
```diff
@@ -425,6 +425,16 @@ func Test_getPromExemplars(t *testing.T) {
 				},
 			},
 		},
+		{
+			"too_many_characters_drops_labels",
```
Comment (Aneurysm9) [inline pkg/translator/prometheusremotewrite/helper_test.go:429]: Maybe add a test here where rune count is less than byte count and byte count is >128.

Comment (dashpole) [reply pkg/translator/prometheusremotewrite/helper_test.go]: done

File: pkg/translator/prometheusremotewrite/helper.go (hunk 1 above)
Comment (dashpole) [reply pkg/translator/prometheusremotewrite/helper.go]: done

**Review by Aneurysm9 — APPROVED** [review]

**Review by mx-psi — APPROVED** [review]

**Review by pmm-sumo — APPROVED** [review]
