### PR TITLE
fix: role_arn support in AWSCloudWatch and AWSEmf exporters

### LINKED ISSUE #42115: AWSCloudWatch and awsemf exporters do not support role_arn AWS STS auth
### Component(s)

exporter/awscloudwatchlogs

## Description

The role_arn support was removed from cloudwach exporter in 
https://github.com/open-telemetry/opentelemetry-collector-contrib/commit/99934f4368c4f084621c7758decbd0ed95035b17#diff-f44af95874288433fb5e94e9bbb285bcced86e0a67770e04c30d3eb219401194

## Steps to Reproduce

Create a collector with awscloudwatch exporter and role_arn. 

### Collector version

0.132.0 or main/HEAD

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

### OpenTelemetry Collector configuration

```yaml
apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: my-otel-collector
spec:
  # ... other OpenTelemetry Collector configuration ...

  # This is where you add environment variables
  env:
    - name: AWS_ENDPOINT_URL_CLOUDWATCHLOGS
      value: "https://add-cloudwatch-endpoint-here"
  
  # Ensure you remove the 'endpoint' from the exporter config if you're using the env var
  config: |
    exporters:
      awscloudwatchlogs:
        role_arn: arn:aws:iam::<masked account number>:role/CloudWatchAgentServer-CrossAccountSharingRole
        log_group_name: "/aws/rosa/logs/sb-replica-rosa-01"
        log_stream_name: ${NODE_NAME}
        log_retention: 3
        region: me-central-1
        # IMPORTANT: Remove the 'endpoint' field here
        # endpoint: https://.  <-- REMOVE THIS LINE
    # ... rest of your collector config ..
```

### Log output

```shell
2025-07-22T12:02:16.466Z        info    internal/retry_sender.go:133    Exporting failed. Will retry the request after interval.        {"resource": {}, "otelcol.component.id": "awscloudwatchlogs", "otelcol.component.kind": "exporter", "otelcol.signal": "logs", "error": "error flushing logs: operation error CloudWatch Logs: PutLogEvents, https response error StatusCode: 400, RequestID: 388627df-8a4b-4c17-a0b1-7901b57a0261, api error AccessDeniedException: User: arn:aws:sts::<account>:assumed-role/sb-rep-rosa-01-account-Worker-Role/<masked> is not authorized to perform: logs:PutLogEvents on resource: arn:aws:logs:me-central-1:<account>:log-group:/aws/rosa/logs/sb-replica-rosa-01:log-stream:<masked>.me-central-1.compute.internal because no identity-based policy allows the logs:PutLogEvents action", "interval": "34.613421457s"}
```

### Additional context

_No response_

### Tip

<sub>[React](https://github.blog/news-insights/product-news/add-reactions-to-pull-requests-issues-and-comments/) with 👍 to help prioritize this issue. Please use comments to provide useful context, avoiding `+1` or `me too`, to help us triage it. Learn more [here](https://opentelemetry.io/community/end-user/issue-participation/).</sub>

### PR DESCRIPTION
**Pull request by yaten2302**
#### Description

This PR attempts to fix re-add the support of `role_arn` in AWSCloudWatch and AWSEmf exporters.
The support was present in aws-go-sdk-v1, but broke while moving to v2.

#### Link to tracking issue
Fixes #42115

### CODE REVIEW

File: internal/aws/awsutil/conn.go [hunk 1]
```diff
@@ -103,6 +105,21 @@ func GetAWSConfig(ctx context.Context, logger *zap.Logger, settings *AWSSessionS
 		return aws.Config{}, err
 	}
 
+	if settings.RoleARN != "" {
```
Comment (axw) [inline internal/aws/awsutil/conn.go:117]: Is it possible to add a test for this? e.g. by mocking both the STS and the CloudWatch API

It was broken once before, adding a test will help avoid breaking it once again

**Review by axw — COMMENTED** [review]
I'm afraid I don't have enough expertise in the AWS SDK to know if this is right. A few things that may help:
 - documenting how you have tested this
 - adding unit tests
 - linking the old code related to assume role, that was working with aws-sdk-go

**Comment by yaten2302** [comment]
@axw , addressing your comments:

1. I haven't tested this component, because, while I was going through the codebase for v1 and comparing the aws go sdk v1 and v2 changes in the docs, I found that there were some internal changes made as a result of which we would now require to mention about the `RoleARN` explicitly (in v2).
2. I'll add the unit tests. This would require refactoring of the [`GetAWSConfig`](https://github.com/yaten2302/opentelemetry-collector-contrib/blob/fix/support-for-role_arn-in-cloud-watch/internal/aws/awsutil/conn.go#L88).
3. Previously (till version 0.123), this `GetAWSConfig` func was named as [`GetAWSConfigSession`](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/release/v0.123.x/internal/aws/awsutil/conn.go#L110-L161). And if we check the [`148th line`](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/release/v0.123.x/internal/aws/awsutil/conn.go#L148) of this func, we've `cn.newAWSSession(logger, cfg.RoleARN, cfg.ExternalID, awsRegion)`. In this, we're passing the `cfg.RoleARN`. But, this support was removed in v2. So, now we need to explicitly mention that in our func. This has also been implemented in [`AWSKinesisExporter (aws-go-sdk-v2)`](https://github.com/yaten2302/opentelemetry-collector-contrib/blob/fix/support-for-role_arn-in-cloud-watch/exporter/awskinesisexporter/exporter.go). If we check from lines - [65-73](https://github.com/yaten2302/opentelemetry-collector-contrib/blob/fix/support-for-role_arn-in-cloud-watch/exporter/awskinesisexporter/exporter.go#L65-L73).

File: internal/aws/awsutil/conn.go (hunk 1 above)
Comment (yaten2302) [reply internal/aws/awsutil/conn.go:117]: I'll add the unit tests for this 👍

**Comment by axw** [comment]
> This has also been implemented in [AWSKinesisExporter (aws-go-sdk-v2)](https://github.com/yaten2302/opentelemetry-collector-contrib/blob/fix/support-for-role_arn-in-cloud-watch/exporter/awskinesisexporter/exporter.go). If we check from lines - [65-73](https://github.com/yaten2302/opentelemetry-collector-contrib/blob/fix/support-for-role_arn-in-cloud-watch/exporter/awskinesisexporter/exporter.go#L65-L73).

Thanks @yaten2302. Based on that, assuming it works for Kinesis, I suppose the code change is fine. If nothing else, a little bit of manual testing would be good.

**Comment by yaten2302** [comment]
@axw , I was trying to refactor the `GetAWSConfig()` func, so for this I was checking the docs and all.
So, should I go ahead with the adding the unit tests or manual testing would serve the purpose?

**Comment by axw** [comment]
@yaten2302 in my opinion, a manual test is the minimum requirement. Adding a unit test would be great too, but given the simplicity and precedent for this code I personally wouldn't block on it.

Put another way: I'd like to see evidence of manual testing. Your choice on whether you add a unit test, unless someone else feels strongly.

**Comment by yaten2302** [comment]
@axw , if I've understood this correctly, then, manual testing is a must for this PR, so that it doesn't breaks in future, right?
I also haven't used this component or AWSCloudWatch. So, maybe we can ask those folks who actually depend this component.
But, is manual testing (on real logs/data on AWS cloud-watch or emf), really possible locally?

WDYT?

**Comment by axw** [comment]
> if I've understood this correctly, then, manual testing is a must for this PR, so that it doesn't breaks in future, right?

Manual testing is just to make sure the change does what you intended. That code can unintentionally removed or broken, so it doesn't prevent future breakage.

Automated tests will help prevent future breakage. Ideally you should have some [functional tests](https://en.wikipedia.org/wiki/Functional_testing) that would fail if the `role_arn` support breaks.

> I also haven't used this component or AWSCloudWatch. So, maybe we can ask those folks who actually depend this component.

Maybe @pavolloffay?

> But, is manual testing (on real logs/data on AWS cloud-watch or emf), really possible locally?

I don't see why not. If it's not possible, or not practical, you could also run the collector in an EC2 instance.

File: .chloggen/fix_support-for-role_arn-in-cloud-watch.yaml [hunk 2]
```diff
@@ -0,0 +1,27 @@
+# Use this changelog template to create an entry for release notes.
+
+# One of 'breaking', 'deprecation', 'new_component', 'enhancement', 'bug_fix'
+change_type: "breaking"
+
+# The name of the component, or a single word describing the area of concern, (e.g. filelogreceiver)
+component: "awscloudwatchlogexporter"
```
Comment (pavolloffay) [inline .chloggen/fix_support-for-role_arn-in-cloud-watch.yaml]: please list here all affected components: these two are missing: `awsemfexporter`, `awsxrayexporter`

File: .chloggen/fix_support-for-role_arn-in-cloud-watch.yaml [hunk 3]
```diff
@@ -0,0 +1,27 @@
...
+
+# A brief description of the change.  Surround your text with quotes ("") if it needs to start with a backtick (`).
+note: "re-add support for `role_arn` in `awscloudwatchlogexporter` and `awsemfexporter`."
```
Comment (pavolloffay) [inline .chloggen/fix_support-for-role_arn-in-cloud-watch.yaml]: Fix support for `role_arn` (STS, short-lived token authentication).

File: internal/aws/awsutil/conn.go (hunk 1 above)
Comment (pavolloffay) [reply internal/aws/awsutil/conn.go:117]: They suggest using mocking https://docs.aws.amazon.com/sdk-for-go/v2/developer-guide/unit-testing.html 

but I am not sure this can validate the auth mechanism.

**Comment by pavolloffay** [comment]
If anyone wants to test this I have built a docker image `pavolloffay/otelcol-contrib:fix-aws-rolearn2`

**Comment by yaten2302** [comment]
Hi @pavolloffay , for [this comment](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/42541#discussion_r2332563923), I'm refactoring the `GetAWSConfig` func and then we'll be able to unit test that code. We can pass an `stsClient` into the func and `nil` if `role_arn` isn't mentioned. And according to that, we can unit test this code.

Have I got your point correctly?

**Comment by yaten2302** [comment]
Also, thanks for the docker img. For manually testing this, can I deploy this on [localstack](https://www.localstack.cloud/) and test it out if it's working or not?

**Comment by pavolloffay** [comment]
Our QE test the cloudwatch logs exporter with this fix and it works. Thanks for putting this together!

**Review by andrzej-stencel — COMMENTED** [review]
Thanks @yaten2302 for the contribution, much appreciated. Also thank you everyone involved in testing this manually.

We should have a unit test for this if possible.

Other than that, can we get the eyes of some AWS subject matter experts on this before merging? @mxiamxia @Aneurysm9 can you take a look as codeowners?

**Comment by yaten2302** [comment]
Hi @andrzej-stencel @pavolloffay , thanks for the reviews, I'll push the unit tests for this change soon 👍

File: .chloggen/fix_support-for-role_arn-in-cloud-watch.yaml (hunk 3 above)
Comment (yaten2302) [reply .chloggen/fix_support-for-role_arn-in-cloud-watch.yaml]: Updated this!

File: .chloggen/fix_support-for-role_arn-in-cloud-watch.yaml (hunk 2 above)
Comment (yaten2302) [reply .chloggen/fix_support-for-role_arn-in-cloud-watch.yaml]: Done!!

**Comment by yaten2302** [comment]
@andrzej-stencel @pavolloffay , wanted to ask here that, after [this](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/42541/commits/52b0d2238713d0d9925be5058c2be5c00581a473) commit, there're a lot of failing tests because, I added a new param in the `GetAWSConfig()` func. So, should I go ahead with the refactor or should I revert back to previous commit?
This refactor was made as an attempt to add the unit tests. Though, we've checked the docker img of the collector and which is working fine, just wanted your reviews on this that should I go ahead with writing the tests and the further refactor or revert to prev commits in which there're no new params?

File: internal/aws/awsutil/conn.go [hunk 4]
```diff
@@ -83,7 +89,7 @@ func getProxyURL(finalProxyAddress string) (*url.URL, error) {
 }
 
 // GetAWSConfig returns AWS config instance.
-func GetAWSConfig(ctx context.Context, logger *zap.Logger, settings *AWSSessionSettings) (aws.Config, error) {
+func GetAWSConfig(ctx context.Context, logger *zap.Logger, settings *AWSSessionSettings, stsClient STSClient) (aws.Config, error) {
```
Comment (axw) [inline internal/aws/awsutil/conn.go]: It looks like you added the stsClient parameter so the client can be mocked, but you're only mocking it in this package.

I suggest you revert this one, and introduce a new unexported method for testing the STS part within this package. That would keep the API clean for the exporters.

File: .chloggen/fix_support-for-role_arn-in-cloud-watch.yaml [hunk 5]
```diff
@@ -0,0 +1,27 @@
+# Use this changelog template to create an entry for release notes.
+
+# One of 'breaking', 'deprecation', 'new_component', 'enhancement', 'bug_fix'
+change_type: "breaking"
```
Comment (axw) [inline .chloggen/fix_support-for-role_arn-in-cloud-watch.yaml]: Why is this a breaking change?

File: internal/aws/awsutil/conn.go (hunk 4 above)
Comment (yaten2302) [reply internal/aws/awsutil/conn.go]: Okay, I got this.
For testing purposes, I'll add another func for this, which will accept the stsClient. By that, we'll be able to unit test this code👍

File: .chloggen/fix_support-for-role_arn-in-cloud-watch.yaml (hunk 5 above)
Comment (yaten2302) [reply .chloggen/fix_support-for-role_arn-in-cloud-watch.yaml]: The `role_arn` support was breaking👀?

Comment (yaten2302) [reply .chloggen/fix_support-for-role_arn-in-cloud-watch.yaml]: Or maybe this can be put under `bug fix`?

Comment (axw) [reply .chloggen/fix_support-for-role_arn-in-cloud-watch.yaml]: Yes, `bug_fix` is appropriate here. `breaking` means that your change breaks something.

Comment (yaten2302) [reply .chloggen/fix_support-for-role_arn-in-cloud-watch.yaml]: done 👍

**Review by pavolloffay — APPROVED** [review]

File: internal/aws/awsutil/conn.go (hunk 1 above)
Comment (yaten2302) [reply internal/aws/awsutil/conn.go:117]: Added the unit tests 👍

File: internal/aws/awsutil/conn.go (hunk 4 above)
Comment (yaten2302) [reply internal/aws/awsutil/conn.go]: Made the changes 👍

**Comment by yaten2302** [comment]
I want to ask here that the `awsxray_test.go` tests are failing in the CI, but locally (on my device), everything is working fine.
<br>
image

**Comment by pavolloffay** [comment]
It seems they pass here as well no?

**Comment by yaten2302** [comment]
In CI, it's failing. But on locally it's working fine.
Is there some other behaviour on your side?

File: internal/aws/awsutil/conn_test.go [hunk 6]
```diff
@@ -4,14 +4,118 @@
...
+	"github.com/aws/aws-sdk-go-v2/credentials/stscreds"
+	"github.com/aws/aws-sdk-go-v2/service/sts"
+	"github.com/aws/aws-sdk-go-v2/service/sts/types"
 	"github.com/stretchr/testify/assert"
 	"go.uber.org/zap"
 )
 
+type STSAPI interface {
+	AssumeRole(ctx context.Context, params *sts.AssumeRoleInput, optFns ...func(*sts.Options)) (*sts.AssumeRoleOutput, error)
+}
```
Comment (axw) [inline internal/aws/awsutil/conn_test.go]: This is exactly the same as https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/credentials/stscreds#AssumeRoleAPIClient, could you use that?

File: internal/aws/awsutil/conn_test.go [hunk 7]
```diff
@@ -4,14 +4,118 @@
...
+
+type mockSTS struct{}
+
+type ConfigLoader func(ctx context.Context, optFns ...func(*config.LoadOptions) error) (aws.Config, error)
+
+func GetAWSConfigHelper(
```
Comment (axw) [inline internal/aws/awsutil/conn_test.go]: I guess you added this because of https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/42541#discussion_r2347640759? This isn't what I meant - I'll clarify.

First of all, what's the point of tests: they're to tell you whether the code provided by awsutil is working as expected. GetAWSConfigHelper is a _copy_ of the code that clients of awsutil use, so how would you know if the code is broken?

Now, what I actually meant was to refactor GetAWSConfig in conn.go so it calls another (unexported) function that has the STS client as a parameter, or perhaps a function to obtain an STS client. You should end up with something like:

```go
func GetAWSConfig(ctx context.Context, logger *zap.Logger, settings *AWSSessionSettings) (aws.Config, error) {
    getSTSClient := func(cfg aws.Config) (stscreds.AssumeRoleAPIClient) {
        return sts.NewFromConfig(cfg)
    }
    return getAWSConfig(ctx, logger, settings, getSTSClient)
}

func getAWSConfig(
    ctx context.Context,
    logger *zap.Logger,
    settings *AWSSessionSettings,
    func getAssumeRoleAPIClient(aws.Config) (stscreds.AssumeRoleAPIClient),
) (aws.Config, error) {
    ...
    if settings.RoleARN != "" {
        assumeRoleAPIClient := getAssumeRoleAPIClient(cfg)
        ...
}
```

Then you can write a test that calls the unexported getAWSConfig function directly, injecting a mock AssumeRoleAPIClient.

Comment (yaten2302) [reply internal/aws/awsutil/conn_test.go]: Made the change 👍

File: internal/aws/awsutil/conn_test.go (hunk 6 above)
Comment (yaten2302) [reply internal/aws/awsutil/conn_test.go]: Ig we don't require this anymore in the updated tests.

**Review by axw — APPROVED** [review]

**Review by pavolloffay — APPROVED** [review]

**Comment by pavolloffay** [comment]
Could someone merge this PR?
