### PR TITLE
Fix scrape error metric for splunkenterprisereceiver

### LINKED ISSUE #38691: otel scraper error metrics broken for splunkenterprise receiver
### The purpose and use-cases of the new component

My team needs an error metric in order to build an alert that tells us when our receiver is not healthy

### Example configuration for the component

This new metric is not enabled by default, so if a team wants to use it they will have to add it to their configuration.

### Telemetry data types supported

metrics

### Code Owner(s)

me (Kaitlin Barrer)

### Sponsor (optional)

_No response_

### Additional context

In splunketnerprisereceiver, if the scrape method has any errors on any of its scrape targets, it returns a [combined error](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/receiver/splunkenterprisereceiver/scraper.go#L129). We would expect to see `otelcol_scraper_errored_metric_points` increment when this happens (defined in the main opentelemetry-collector repo [here](https://github.com/open-telemetry/opentelemetry-collector/blob/ced2880d495cb48503d337fb8971d1cee5d2fe13/scraper/scraperhelper/obs_metrics.go#L64), but it's not, making errors difficult to detect.

### PR DESCRIPTION
**Pull request by kkburr**
#### Description
Fixing a bug:
In splunkenterprisereceiver, if the scrape method has any errors on any of its scrape targets, it should return a [combined error](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/receiver/splunkenterprisereceiver/scraper.go#L129). We would expect to see `otelcol_scraper_errored_metric_points `increment (defined in the main opentelemetry-collector repo [here](https://github.com/open-telemetry/opentelemetry-collector/blob/ced2880d495cb48503d337fb8971d1cee5d2fe13/scraper/scraperhelper/obs_metrics.go#L64). For the splunkenterprise receiver, it does not. This PR fixes that bug.

#### Link to tracking issue
Fixes https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/38691

#### Testing
- added unit test
- tested in splunk environment

Scrape errors (bad configuration)
Screenshot 2025-04-09 at 3 49 59 PM

No Scrape errors
Screenshot 2025-04-09 at 3 39 05 PM

Scrape errors (some scrapes succeed; one fails)
Screenshot 2025-04-09 at 3 27 41 PM

#### Documentation

I did not add any documentation for this change.

### CODE REVIEW

**Review by greatestusername — APPROVED** [review]
TY for sticking with this, determining root cause, and contributing a fix with additional testing! 🖖

**Review by shalper2 — APPROVED** [review]

File: receiver/splunkenterprisereceiver/scraper.go [hunk 1]
```diff
@@ -67,7 +67,7 @@ func errorListener(ctx context.Context, eQueue <-chan error, eOut chan<- *scrape
 				eOut <- errs
 				return
 			}
-			errs.Add(err)
+			errs.AddPartial(1, err)
```
Comment (dehaansa) [inline receiver/splunkenterprisereceiver/scraper.go:70]: In my understanding, the value provided to AddPartial is intended to represent metrics that failed to scrape. 

As I believe different scrape functions in the receiver could result in different numbers of missed metrics, could this pattern be enhanced to send an object with both error & count on eQueue, providing the ability to more accurately count the partial failures?

Comment (kkburr) [reply receiver/splunkenterprisereceiver/scraper.go:70]: I believe this code does accurately capture the number of failed scrapes per scrape cycle.

**Review by MovieStoreGuy — APPROVED** [review]

**Review by atoulme — APPROVED** [review]
