### PR TITLE
[receiver/elasticsearch] Fix nil panic on non-linux systems

### LINKED ISSUE #30140: Bug with Elasticsearch receiver
### Component(s)

Elasticsearch Receiver

## Description
I tried running the Elasticsearch receiver with the OpenTelemetry Collector but it kept returning errors.

## Steps to Reproduce
I followed the exact steps and used the sample for the Elasticsearch receiver in the receiver repo.

## Expected Result
To successfully scrape metrics from my running Elasticsearch cluster

## Actual Result
```
Users-MacBook-Pro-2:otelcol-contrib deimos$ ./otelcol-contrib --config ./config.yml
2023-12-17T22:54:15.523+0100    info    service@v0.91.0/telemetry.go:86 Setting up own telemetry...
2023-12-17T22:54:15.525+0100    info    service@v0.91.0/telemetry.go:203        Serving Prometheus metrics      {"address": "localhost:8888", "level": "Basic"}
2023-12-17T22:54:15.527+0100    info    service@v0.91.0/service.go:145  Starting otelcol-contrib...     {"Version": "0.91.0", "NumCPU": 12}
2023-12-17T22:54:15.527+0100    info    extensions/extensions.go:34     Starting extensions...
2023-12-17T22:54:15.536+0100    info    service@v0.91.0/service.go:171  Everything is ready. Begin running and processing data.
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x4a4b641]

goroutine 63 [running]:
github.com/open-telemetry/opentelemetry-collector-contrib/receiver/elasticsearchreceiver.(*elasticsearchScraper).scrapeNodeMetrics(0xc00284c880, {0x9734dc0, 0xc001f13830}, 0xc002b87cd8?, 0xc002bf7cd8)
        github.com/open-telemetry/opentelemetry-collector-contrib/receiver/elasticsearchreceiver@v0.91.0/scraper.go:138 +0x6c1
github.com/open-telemetry/opentelemetry-collector-contrib/receiver/elasticsearchreceiver.(*elasticsearchScraper).scrape(0xc00284c880, {0x9734dc0, 0xc001f13830})
        github.com/open-telemetry/opentelemetry-collector-contrib/receiver/elasticsearchreceiver@v0.91.0/scraper.go:76 +0x105
go.opentelemetry.io/collector/receiver/scraperhelper.ScrapeFunc.Scrape(...)
        go.opentelemetry.io/collector/receiver@v0.91.0/scraperhelper/scraper.go:20
go.opentelemetry.io/collector/receiver/scraperhelper.(*controller).scrapeMetricsAndReport(0xc002122b40)
        go.opentelemetry.io/collector/receiver@v0.91.0/scraperhelper/scrapercontroller.go:197 +0x16b
go.opentelemetry.io/collector/receiver/scraperhelper.(*controller).startScraping.func1()
        go.opentelemetry.io/collector/receiver@v0.91.0/scraperhelper/scrapercontroller.go:172 +0xd1
created by go.opentelemetry.io/collector/receiver/scraperhelper.(*controller).startScraping in goroutine 1
        go.opentelemetry.io/collector/receiver@v0.91.0
```
        
I also used a later version, 0.89 but it was the same thing.

### Collector version

v0.91 and v0.89

## Environment
OS: mac

### OpenTelemetry Collector configuration

```yaml
receivers:
  elasticsearch:
    metrics:
      elasticsearch.node.fs.disk.available:
        enabled: false
    nodes: ["Users-MacBook-Pro-2.local"]
    skip_cluster_metrics: true
    indices: [".geoip_databases"]
    endpoint: http://localhost:9200
    username: xxxxxx
    password: xxxxxx
    collection_interval: 10s

processors:
  batch:
    send_batch_size: 1000
    timeout: 10s

exporters:
  otlp:
    endpoint: "ingest.{region}.signoz.cloud:443"
    tls:
      insecure: false
    timeout: 20s
    headers:
      "signoz-access-token": "xxxxx"

service:
  telemetry:
    metrics:
      address: localhost:8888
  pipelines:
    metrics:
      receivers: [elasticsearch]
      processors: [batch]
      exporters: [otlp]
```

### Log output

```shell
Users-MacBook-Pro-2:otelcol-contrib deimos$ ./otelcol-contrib --config ./config.yml
2023-12-17T22:54:15.523+0100    info    service@v0.91.0/telemetry.go:86 Setting up own telemetry...
2023-12-17T22:54:15.525+0100    info    service@v0.91.0/telemetry.go:203        Serving Prometheus metrics      {"address": "localhost:8888", "level": "Basic"}
2023-12-17T22:54:15.527+0100    info    service@v0.91.0/service.go:145  Starting otelcol-contrib...     {"Version": "0.91.0", "NumCPU": 12}
2023-12-17T22:54:15.527+0100    info    extensions/extensions.go:34     Starting extensions...
2023-12-17T22:54:15.536+0100    info    service@v0.91.0/service.go:171  Everything is ready. Begin running and processing data.
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x4a4b641]

goroutine 63 [running]:
github.com/open-telemetry/opentelemetry-collector-contrib/receiver/elasticsearchreceiver.(*elasticsearchScraper).scrapeNodeMetrics(0xc00284c880, {0x9734dc0, 0xc001f13830}, 0xc002b87cd8?, 0xc002bf7cd8)
        github.com/open-telemetry/opentelemetry-collector-contrib/receiver/elasticsearchreceiver@v0.91.0/scraper.go:138 +0x6c1
github.com/open-telemetry/opentelemetry-collector-contrib/receiver/elasticsearchreceiver.(*elasticsearchScraper).scrape(0xc00284c880, {0x9734dc0, 0xc001f13830})
        github.com/open-telemetry/opentelemetry-collector-contrib/receiver/elasticsearchreceiver@v0.91.0/scraper.go:76 +0x105
go.opentelemetry.io/collector/receiver/scraperhelper.ScrapeFunc.Scrape(...)
        go.opentelemetry.io/collector/receiver@v0.91.0/scraperhelper/scraper.go:20
go.opentelemetry.io/collector/receiver/scraperhelper.(*controller).scrapeMetricsAndReport(0xc002122b40)
        go.opentelemetry.io/collector/receiver@v0.91.0/scraperhelper/scrapercontroller.go:197 +0x16b
go.opentelemetry.io/collector/receiver/scraperhelper.(*controller).startScraping.func1()
        go.opentelemetry.io/collector/receiver@v0.91.0/scraperhelper/scrapercontroller.go:172 +0xd1
created by go.opentelemetry.io/collector/receiver/scraperhelper.(*controller).startScraping in goroutine 1
        go.opentelemetry.io/collector/receiver@v0.91.0
```

### Additional context

Before changing the node section to this:
    nodes: ["Users-MacBook-Pro-2.local"]
    
I used what was already in the repo.

### PR DESCRIPTION
**Pull request by djaglowski**
Fixes #30140

### CODE REVIEW

File: receiver/elasticsearchreceiver/scraper.go [hunk 1]
```diff
@@ -135,8 +135,10 @@ func (r *elasticsearchScraper) scrapeNodeMetrics(ctx context.Context, now pcommo
 		r.mb.RecordElasticsearchNodeFsDiskFreeDataPoint(now, info.FS.Total.FreeBytes)
 		r.mb.RecordElasticsearchNodeFsDiskTotalDataPoint(now, info.FS.Total.TotalBytes)
 
-		r.mb.RecordElasticsearchNodeDiskIoReadDataPoint(now, info.FS.IOStats.Total.ReadBytes)
-		r.mb.RecordElasticsearchNodeDiskIoWriteDataPoint(now, info.FS.IOStats.Total.WriteBytes)
+		if info.FS.IOStats != nil {
+			r.mb.RecordElasticsearchNodeDiskIoReadDataPoint(now, info.FS.IOStats.Total.ReadBytes)
+			r.mb.RecordElasticsearchNodeDiskIoWriteDataPoint(now, info.FS.IOStats.Total.WriteBytes)
+		}
```
Comment (atoulme) [inline receiver/elasticsearchreceiver/scraper.go:141]: Worth documenting in the metric description that it is Linux only?

Comment (djaglowski) [reply receiver/elasticsearchreceiver/scraper.go:141]: Good idea. Added.

**Review by codeboten — APPROVED** [review]
