### PR TITLE
[chore] Fix TestConnectorConsume/incomplete_traces_with_virtual_server_span failures on Windows

### LINKED ISSUE #34792: [connector/servicegraph] Broken test: TestConnectorConsume/incomplete_traces_with_virtual_server_span
### Component(s)

connector/servicegraph

### Describe the issue you're reporting

https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/10493207856/job/29066610265?pr=34791#step:6:377

```
=== FAIL: . TestConnectorConsume/incomplete_traces_with_virtual_server_span (0.00s)
    logger.go:146: 2024-08-21T16:00:30.028Z	INFO	Started servicegraphconnector

=== FAIL: . TestConnectorConsume (0.02s)
panic: runtime error: index out of range [0] with length 0 [recovered]
	panic: runtime error: index out of range [0] with length 0

goroutine 20 [running]:
testing.tRunner.func1.2({0x14143aa00, 0xc0002542a0})
	C:/hostedtoolcache/windows/go/1.22.6/x64/src/testing/testing.go:1631 +0x3f7
testing.tRunner.func1()
	C:/hostedtoolcache/windows/go/1.22.6/x64/src/testing/testing.go:1634 +0x6b6
panic({0x14143aa00?, 0xc0002542a0?})
	C:/hostedtoolcache/windows/go/1.22.6/x64/src/runtime/panic.go:770 +0x132
go.opentelemetry.io/collector/pdata/pmetric.MetricSlice.At(...)
	C:/Users/runneradmin/go/pkg/mod/go.opentelemetry.io/collector/pdata@v1.13.1-0.20240816132030-9fd84668bb02/pmetric/generated_metricslice.go:56
github.com/open-telemetry/opentelemetry-collector-contrib/connector/servicegraphconnector.TestConnectorConsume.func2(0xc000154340, {0xc000009050?, 0xc00016a15c?})
	D:/a/opentelemetry-collector-contrib/opentelemetry-collector-contrib/connector/servicegraphconnector/connector_test.go:120 +0x2a7
github.com/open-telemetry/opentelemetry-collector-contrib/connector/servicegraphconnector.TestConnectorConsume.func5(0xc000154340)
	D:/a/opentelemetry-collector-contrib/opentelemetry-collector-contrib/connector/servicegraphconnector/connector_test.go:189 +0x482
testing.tRunner(0xc000154340, 0xc000124dc0)
	C:/hostedtoolcache/windows/go/1.22.6/x64/src/testing/testing.go:1689 +0x21f
created by testing.(*T).Run in goroutine 14
	C:/hostedtoolcache/windows/go/1.22.6/x64/src/testing/testing.go:1742 +0x826

DONE 13 tests, 2 failures in 27.027s
```

### PR DESCRIPTION
**Pull request by pjanotti**
**Description:**
The failure is due to similar case as explained at https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/32715#issuecomment-2105414369

This is a quick fix that just adds a delay to ensure that the test is passing on Windows.

**Link to tracking Issue:**
Fixes #34792

**Testing:**
Local Windows test run.

**Documentation:**
N/A

### CODE REVIEW

**Review by crobert-1 — APPROVED** [review]

File: connector/servicegraphconnector/connector_test.go [hunk 1]
```diff
@@ -183,6 +183,7 @@ func TestConnectorConsume(t *testing.T) {
 			assert.NoError(t, conn.ConsumeTraces(context.Background(), tc.sampleTraces))
 
 			// Force collection
+			time.Sleep(time.Second) // On Windows timing doesn't tick forward quickly for the store data to expire, force a wait before expiring.
```
Comment (jpkrohling) [inline connector/servicegraphconnector/connector_test.go:186]: Is there any other way to wait on a condition, instead of waiting on time? This would increase every single CI run by 1s. Doesn't sound much, but it's a lot of computing resources if we account for all matrices and executions...

**Review by jpkrohling — CHANGES_REQUESTED** [review]

File: connector/servicegraphconnector/connector_test.go (hunk 1 above)
Comment (pjanotti) [reply connector/servicegraphconnector/connector_test.go:186]: I agree with this, but, this test is failing at a very high rate on Windows runs - we need a quick fix. The proper way to do this is by using a clock that you can control on tests, like it was done for other components, e.g.: https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/34128.

A harder case that even with a clock may not be enough is when the component being tested starts nested goroutines. On Windows the scheduling of them tend to be vary a lot and in many cases the expected goroutine didn't run yet when the test already expects that to happen.

Comment (pjanotti) [reply connector/servicegraphconnector/connector_test.go:186]: Some context https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/32715#issuecomment-2105414369

Comment (pjanotti) [reply connector/servicegraphconnector/connector_test.go:186]: That said we can limit the scope of the delay to where it is needed in practice: Windows.

Comment (pjanotti) [reply connector/servicegraphconnector/connector_test.go]: If we agree with this approach for the time being I will open a follow up issue so it can be eventually removed.

Comment (jpkrohling) [reply connector/servicegraphconnector/connector_test.go]: Sounds good to me.

**Review by jpkrohling — APPROVED** [review]

**Review by atoulme — APPROVED** [review]
I don't like it but let's get a green build

**Comment by pjanotti** [comment]
> I don't like it but let's get a green build

Fair, me neither, the goal is to get Windows CI reliably passing. I will open an follow up issue so we can eventually remove the sleep.

File: connector/servicegraphconnector/connector_test.go (hunk 1 above)
Comment (pjanotti) [reply connector/servicegraphconnector/connector_test.go]: Follow-up issue #34819 34819

**Comment by crobert-1** [comment]
_Added `ready to merge`, pending passing tests._
