### PR TITLE
[exporter/prometheusremotewrite] fix snappy double alloc

### LINKED ISSUE #34273: [exporter/prometheusremotewrite] Double allocation in execute function due to snappy buffer size mismatch
### Component(s)

exporter/prometheusremotewrite

## Description

We observed extra allocations in the execute function due to a mismatch between the buffer size passed into snappy and the buffer size that snappy needs to handle the worst case compression outcome.

Specifically this code in snappy generates a buffer size > the size of the input buffer:
https://github.com/golang/snappy/blob/master/encode.go#L24

But the buffer allocated and passed into snappy is only equal to the size of our input buffer:
https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/exporter/prometheusremotewriteexporter/exporter.go#L277

Therefore snappy ends up allocating an extra buffer and the buffer allocated by prometheus remote write is unused.

Solution is to just not pre-allocate the buffer and pass nil which is valid per the snappy documentation.

This double allocation is responsible for ~10% of overall allocations in our otel collector after fixing 
https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/34269
dfce1b99-8998-422e-a9e6-ccc5f6401393

## Steps to Reproduce

Use go tool pprof to profile memory allocations of the prometheus remote write exporter

## Expected Result

Compression allocates a single buffer to handle the export

## Actual Result

We allocate an extra buffer in execute which then does not get used by the snappy function.

### Collector version

v0.101.0

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

### OpenTelemetry Collector configuration

_No response_

### Log output

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by ben-childs-docusign**
**Description:** <Describe what has changed.>

Snappy Encode function is not using the buffer passed in by prometheus remote write as it is too small. Removing this unused buffer allocation and just passing nil. Snappy will allocate the required buffers.

**Link to tracking Issue:** <Issue number if applicable>
Fixes https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/34273

**Testing:** <Describe what testing was performed and which tests were added.>
Ran existing unit tests which cover this code

Ran this in our integration environment and verified reduced allocations.
Before:
dfce1b99-8998-422e-a9e6-ccc5f6401393

After: 
image

**Documentation:** <Describe the documentation added.>
Updated changelog

### CODE REVIEW

File: exporter/prometheusremotewriteexporter/exporter.go [hunk 1]
```diff
@@ -274,8 +274,7 @@ func (prwe *prwExporter) execute(ctx context.Context, writeReq *prompb.WriteRequ
 	if errMarshal != nil {
 		return consumererror.NewPermanent(errMarshal)
 	}
-	buf := make([]byte, len(data), cap(data))
-	compressedData := snappy.Encode(buf, data)
+	compressedData := snappy.Encode(nil, data)
```
Comment (rapphil) [inline exporter/prometheusremotewriteexporter/exporter.go:277]: this is an awesome finding! thanks! Can you add a comment here about it so that nobody thinks about removing this in the future?

File: .chloggen/bc--optimizesnappybufferallocation.yaml [hunk 2]
```diff
@@ -0,0 +1,27 @@
+# Use this changelog template to create an entry for release notes.
+
+# One of 'breaking', 'deprecation', 'new_component', 'enhancement', 'bug_fix'
+change_type: bug_fix
```
Comment (rapphil) [inline .chloggen/bc--optimizesnappybufferallocation.yaml:4]: I would say that this is not a bug because it is not affecting the functionality. This is an enhancement.

File: exporter/prometheusremotewriteexporter/exporter.go (hunk 1 above)
Comment (rapphil) [inline exporter/prometheusremotewriteexporter/exporter.go:277]:
```suggestion
        // If we don't pass a bugger large enough, Snappy Encode function will not use it and instead will allocate a new buffer.
        // Therefore we always let Snappy decide the size of the buffer.
	compressedData := snappy.Encode(nil, data)
```

File: .chloggen/bc--optimizesnappybufferallocation.yaml [hunk 3]
```diff
@@ -0,0 +1,27 @@
...
+
+# The name of the component, or a single word describing the area of concern, (e.g. filelogreceiver)
+component: exporter/prometheusremotewrite
+
+# A brief description of the change.  Surround your text with quotes ("") if it needs to start with a backtick (`).
+note: Remove unused buffer allocation from prometheus remote write execute function
```
Comment (rapphil) [inline .chloggen/bc--optimizesnappybufferallocation.yaml:10]: Should we frame this more as an enhancement? Something like: "Reduce unnecessary memory allocation by removing buffer that was not used by Snappy encoding function."

**Comment by rapphil** [comment]
There are a few approval steps that are failing, can you take a look to make sure that they are not related to this change or require merging from mainline?

**Review by rapphil — APPROVED** [review]

File: exporter/prometheusremotewriteexporter/exporter.go [hunk 4]
```diff
@@ -274,8 +274,9 @@ func (prwe *prwExporter) execute(ctx context.Context, writeReq *prompb.WriteRequ
 	if errMarshal != nil {
 		return consumererror.NewPermanent(errMarshal)
 	}
-	buf := make([]byte, len(data), cap(data))
-	compressedData := snappy.Encode(buf, data)
+	// If we don't pass a bugger large enough, Snappy Encode function will not use it and instead will allocate a new buffer.
```
Comment (mwear) [inline exporter/prometheusremotewriteexporter/exporter.go:277]:
```suggestion
	// If we don't pass a buffer large enough, Snappy Encode function will not use it and instead will allocate a new buffer.
```

**Review by mwear — APPROVED** [review]

**Comment by ben-childs-docusign** [comment]
@mwear , @rapphil thanks for the review - whats the next step to get this merged? I checked the latest build failure and it seems to be a transformprocessor unit test which isn't impacted by this change afaict.

**Comment by rapphil** [comment]
@ben-childs-docusign , It is possible that it is a flaky test. can you take a look into other PRs that were created recently and check if the tests are failing there as well? Is your branch updated with regards to main?  As next steps, I think @mwear can add the `ready to merge` label and then some maintainer will pick it for merging.

**Review by dmitryax — APPROVED** [review]
