### PR TITLE
[receiver/hostmetrics] Do not fail to start if a performance counter is unavailable

### LINKED ISSUE #14032: [receiver/hostmetrics/disk] When running on windows, receiver crashes collector when perf counter is unavailable
**Describe the bug**
Running on Windows, the collector fails to start up [if the "LogicalDisk" performance counter is not available](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/aa298997cb19718ee267fdc7f969573a594698f2/receiver/hostmetricsreceiver/internal/scraper/diskscraper/disk_scraper_windows.go#L105).

**Steps to reproduce**
Run collector w/ a user that does not have access to the performance counter. (User belongs to neither Administrators nor Performance Monitor Users group.)

**What did you expect to see?**
The collector should start up successfully and run. The scraper should return an error from the scraper funciton.

**What version did you use?**
Windows 10

**Additional context**
Although this error may be essentially permanent, I do not believe it should cause the collector to crash during startup because this pattern causes the collector to be fragile. To illustrate the point, consider a collector that runs 20 scrapers, each of which may crash the collector during startup if their respective target is not available.

### PR DESCRIPTION
**Pull request by BinaryFissionGames**
**Description:**
* Previously, if a performance counter was not available, the collector would fail to start. This change makes it so that it will start, but fail to scrape if the counter is not available.

**Link to tracking Issue:** Resolves #14032

**Testing:**
* Changed initialize failure test case
* Tested manually on a system where a performance counter was not available

### CODE REVIEW

**Comment by BinaryFissionGames** [comment]
cc @dmitryax @djaglowski

File: receiver/hostmetricsreceiver/internal/perfcounters/perfcounter_scraper.go [hunk 1]
```diff
@@ -55,7 +63,8 @@ func (p *PerfLibScraper) Initialize(objects ...string) error {
 	for _, name := range objects {
 		index := nameTable.LookupIndex(name)
 		if index == 0 {
-			return fmt.Errorf("Failed to retrieve perf counter object %q", name)
+			p.logger.Error("Failed to retrieve perf counter object, performance data from this object will fail to be scraped", zap.String("counter", name))
```
Comment (dmitryax) [inline receiver/hostmetricsreceiver/internal/perfcounters/perfcounter_scraper.go:66]: Shouldn't we log the error and don't attempt the scraping after that? I believe there is no way that the counter get available after the initialization, right? We can update the state here to reduce the number of objects to scrape in that case

Comment (BinaryFissionGames) [reply receiver/hostmetricsreceiver/internal/perfcounters/perfcounter_scraper.go:66]: I'm trying to envision what this would look like. You're correct, once the counter is unavailable, it can't later become available.

I think I tended away from skipping scraping because there could potentially be multiple objects specified to `Initialize`, and it might make sense to "partially" scrape in those instances. But it looks like all instances where this struct is used, only use a single object here currently, so no failure here would end up being partial.

So maybe it makes sense to keep the error returned here, and just make scrape a no-op if `Initialize` errors due to the object not being available?
Thoughts on that approach?

Comment (djaglowski) [reply receiver/hostmetricsreceiver/internal/perfcounters/perfcounter_scraper.go:66]: It is a good point that all occurrences of `Initialize` are only taking one object, but I think there's a solution that generalizes to either case (one or multiple objects):
- When _all_ objects fail to initialized, follow Dmitrii's suggestion to not scrape at all and update state
- When some (but not all), objects fail to initialize, scrape what we can and return partial error

Initialize could return a partial error when appropriate and this can be used to determine behavior of the scraper. WDYT?

Comment (BinaryFissionGames) [reply receiver/hostmetricsreceiver/internal/perfcounters/perfcounter_scraper.go:66]: I'll work on implementing something similar to that.

Comment (BinaryFissionGames) [reply receiver/hostmetricsreceiver/internal/perfcounters/perfcounter_scraper.go]: Changed the behavior to match the following:
* PerfLibScraper returns a partial error if any objects fail to initialize
  * objects that do not fail to initialize are still valid to be scraped, and are still set up appropriately
* For the current scrapers, any initialize error indicates a complete inability to scrape, so they skip their scrape step and do a no-op on scrape.
* On init, an error is printed if the Initialize function fails, indicating that the failing scraper will not scrape metrics.

**Review by djaglowski — APPROVED** [review]
This looks good to me.

File: receiver/hostmetricsreceiver/internal/perfcounters/perfcounter_scraper.go (hunk 1 above)
Comment (djaglowski) [reply receiver/hostmetricsreceiver/internal/perfcounters/perfcounter_scraper.go]: I think Dmitrii's point has been addressed so I'm resolving this.
