### PR TITLE
[exporter/elasticsearch] Add sanitization utils for datastream fields

### LINKED ISSUE #34285: [exporter/elasticsearch] Data stream routing does not sanitize values
### Component(s)

exporter/elasticsearch

## Description

Data stream attributes are not sanitized, resulting in non-compliant data stream names. Sanitization should be implemented according to https://www.elastic.co/guide/en/ecs/current/ecs-data_stream.html. There is also an [implementation of DS fields sanitization in ES](https://github.com/elastic/elasticsearch/blob/33d63fa9c2fc3afb9184f31e2681942cfd8dc7fd/modules/ingest-common/src/main/java/org/elasticsearch/ingest/common/RerouteProcessor.java#L203-L206), but in this implementation there is in incorrect handling of an edge case where string limit should be 100 unicode characters instead of 100 bytes.

## Steps to Reproduce

Supply a value with `-` in resource attributes `data_stream.dataset` or `data_stream.namespace`

## Expected Result

The value is sanitized so that the resulting data stream does not contain `-`

## Actual Result

The resulting data stream contains `-`.

### Collector version

v0.105.0

### Environment information

_No response_

### OpenTelemetry Collector configuration

_No response_

### Log output

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by rubvs**
**Description:** Adds util functions to sanitize data stream fields

**Link to tracking Issue:** Fixes https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/34285

**Testing:** Added unit tests

### CODE REVIEW

File: exporter/elasticsearchexporter/data_stream_router.go [hunk 1]
```diff
@@ -44,7 +44,10 @@ func routeWithDefaults(defaultDSType string) func(
 			}
 		}
 
-		// Receiver-based routing
+		dataset = sanitizeDataStreamDataset(dataset)
+		namespace = sanitizeDataStreamNamespace(namespace)
```
Comment (carsonip) [inline exporter/elasticsearchexporter/data_stream_router.go:48]: Let's do it right at the end when we put things together, on line 65-66, to cover receiver based routing edge cases

File: exporter/elasticsearchexporter/data_stream_router.go [hunk 2]
```diff
@@ -44,7 +44,10 @@ func routeWithDefaults(defaultDSType string) func(
...
+
+    // Receiver-based routing
 		// For example, hostmetricsreceiver (or hostmetricsreceiver.otel in the OTel output mode)
```
Comment (carsonip) [inline exporter/elasticsearchexporter/data_stream_router.go:51]: nit: indent
```suggestion
		// Receiver-based routing
		// For example, hostmetricsreceiver (or hostmetricsreceiver.otel in the OTel output mode)
```

File: exporter/elasticsearchexporter/util.go [hunk 3]
```diff
@@ -6,11 +6,49 @@ package elasticsearchexporter // import "github.com/open-telemetry/opentelemetry
...
+
+// Sanitize the datastream fields (dataset, namespace) to apply restrictions
+// as outlined in https://www.elastic.co/guide/en/ecs/current/ecs-data_stream.html
+func sanitizeDataStreamNamespace(field string) string {
+	field = strings.Map(replaceReservedRune(disallowedNamespaceRunes), field)
+	if len(field) > maxDataStreamBytes {
+		return field[:maxDataStreamBytes]
+	}
+	return field
+}
```
Comment (carsonip) [inline exporter/elasticsearchexporter/util.go:41]: I missed this in the apm-data PR. It'll be clearer if you can refactor this into 3 funcs, `sanitizeDataStreamDataset` and `sanitizeDataStreamNamespace` with the original signature, which calls a new `sanitizeDataStreamField(field, disallowed)` func that does all the work. Like currying in javascript.

This also enables `replaceReservedRune` func to be inlined

File: exporter/elasticsearchexporter/exporter_test.go [hunk 4]
```diff
@@ -226,12 +230,12 @@ func TestExporterLogs(t *testing.T) {
 		})
 		logs := newLogsWithAttributes(
 			map[string]any{
-				dataStreamDataset: "record.dataset",
+				dataStreamDataset: "record.dataset" + disallowedDatasetRunes,
```
Comment (carsonip) [inline exporter/elasticsearchexporter/exporter_test.go:233]: ditto
```suggestion
				dataStreamDataset: "record.dataset.-\\/*?\"<>| ,#:",
```

File: exporter/elasticsearchexporter/exporter_test.go [hunk 5]
```diff
@@ -226,12 +230,12 @@ func TestExporterLogs(t *testing.T) {
...
 			},
 			nil,
 			map[string]any{
 				dataStreamDataset:   "resource.dataset",
-				dataStreamNamespace: "resource.namespace",
+				dataStreamNamespace: "resource.namespace" + disallowedNamespaceRunes,
```
Comment (carsonip) [inline exporter/elasticsearchexporter/exporter_test.go:238]: ditto
```suggestion
				dataStreamNamespace: "resource.namespace.-\\/*?\"<>| ,#:",
```

File: exporter/elasticsearchexporter/exporter_test.go [hunk 6]
```diff
@@ -216,7 +217,10 @@ func TestExporterLogs(t *testing.T) {
 		server := newESTestServer(t, func(docs []itemRequest) ([]itemResponse, error) {
 			rec.Record(docs)
 
-			assert.Equal(t, "logs-record.dataset-resource.namespace", actionJSONToIndex(t, docs[0].Action))
+			ds := "record.dataset" + strings.Repeat("_", len(disallowedDatasetRunes))
+			ns := "resource.namespace" + strings.Repeat("_", len(disallowedNamespaceRunes))
+
+			assert.Equal(t, fmt.Sprintf("logs-%s-%s", ds, ns), actionJSONToIndex(t, docs[0].Action))
```
Comment (carsonip) [inline exporter/elasticsearchexporter/exporter_test.go:223]: As exporter_test is like a e2e test for the exporter, I don't expect it to have too much knowledge of private variables of data stream router. There's also an added benefit that it will catch a change if someone fat fingered to delete `-` in `disallowedNamespaceRunes`.
```suggestion
			assert.Equal(t, "logs-record.dataset._______________-resource.namespace.-______________", actionJSONToIndex(t, docs[0].Action))
```

File: exporter/elasticsearchexporter/util.go [hunk 7]
```diff
@@ -6,11 +6,49 @@ package elasticsearchexporter // import "github.com/open-telemetry/opentelemetry
...
+
+func replaceReservedRune(disallowedRunes string) func(r rune) rune {
+	return func(r rune) rune {
+		if strings.ContainsRune(disallowedRunes, r) {
+			return '_'
+		}
+		return unicode.ToLower(r)
+	}
+}
+
```
Comment (carsonip) [inline exporter/elasticsearchexporter/util.go:51]: these sanitization funcs sit better in data_stream_router.go than util.go

File: exporter/elasticsearchexporter/exporter_test.go [hunk 8]
```diff
@@ -216,7 +217,10 @@ func TestExporterLogs(t *testing.T) {
 		server := newESTestServer(t, func(docs []itemRequest) ([]itemResponse, error) {
 			rec.Record(docs)
 
-			assert.Equal(t, "logs-record.dataset-resource.namespace", actionJSONToIndex(t, docs[0].Action))
+			ds := "record.dataset" + strings.Repeat("_", len(disallowedDatasetRunes))
```
Comment (carsonip) [inline exporter/elasticsearchexporter/exporter_test.go:220]: I'm a little hesitant about only updating this test in exporter_test. We should either update the equiv test for logs, metrics, and traces, or do not update at all.

**Review by carsonip — COMMENTED** [review]
Thanks, looks good functionality wise. A couple of minor comments.

**Comment by rubvs** [comment]
@carsonip I have improved the `sanitizeDataStreamField` to leverage inlining. I also merged the `.otel` suffix extension into the sanitization check, since I have to take the extension into account when doing the 100 char check. Let me know if you approve this approach.

**Comment by rubvs** [comment]
I also added a test to `model_test.go`. I do not know if this is needed, but I think it won't hurt to add it either.

File: exporter/elasticsearchexporter/data_stream_router.go [hunk 9]
```diff
@@ -6,12 +6,45 @@ package elasticsearchexporter // import "github.com/open-telemetry/opentelemetry
...
 
+const (
+	maxDataStreamBytes       = 100
+	disallowedNamespaceRunes = "\\/*?\"<>| ,#:"
+	disallowedDatasetRunes   = "-\\/*?\"<>| ,#:"
+)
+
+// Sanitize the datastream fields (dataset, namespace) to apply restrictions
+// as outlined in https://www.elastic.co/guide/en/ecs/current/ecs-data_stream.html
+func sanitizeDataStreamField(field, disallowed string, otel bool) string {
```
Comment (carsonip) [inline exporter/elasticsearchexporter/data_stream_router.go:25]:
```suggestion
func sanitizeDataStreamField(field, disallowed, appendSuffix string) string {
```

File: exporter/elasticsearchexporter/data_stream_router.go [hunk 10]
```diff
@@ -53,15 +86,13 @@ func routeWithDefaults(defaultDSType string) func(
 			dataset = receiverName
 		}
 
-		// The naming convention for datastream is expected to be "logs-[dataset].otel-[namespace]".
-		// This is in order to match the built-in logs-*.otel-* index template.
-		if otel {
-			dataset += ".otel"
-		}
+		dataset = sanitizeDataStreamField(dataset, disallowedDatasetRunes, otel)
+		namespace = sanitizeDataStreamField(namespace, disallowedNamespaceRunes, false)
```
Comment (carsonip) [inline exporter/elasticsearchexporter/data_stream_router.go:90]:
```suggestion
		namespace = sanitizeDataStreamField(namespace, disallowedNamespaceRunes, "")
```

File: exporter/elasticsearchexporter/data_stream_router.go [hunk 11]
```diff
@@ -53,15 +86,13 @@ func routeWithDefaults(defaultDSType string) func(
 			dataset = receiverName
 		}
 
-		// The naming convention for datastream is expected to be "logs-[dataset].otel-[namespace]".
-		// This is in order to match the built-in logs-*.otel-* index template.
-		if otel {
-			dataset += ".otel"
-		}
+		dataset = sanitizeDataStreamField(dataset, disallowedDatasetRunes, otel)
```
Comment (carsonip) [inline exporter/elasticsearchexporter/data_stream_router.go:89]: set the otel dataset suffix here
```suggestion
		dataset = sanitizeDataStreamField(dataset, disallowedDatasetRunes, datasetSuffix)
```

File: exporter/elasticsearchexporter/data_stream_router.go [hunk 12]
```diff
@@ -6,12 +6,45 @@ package elasticsearchexporter // import "github.com/open-telemetry/opentelemetry
...
+
+// Sanitize the datastream fields (dataset, namespace) to apply restrictions
+// as outlined in https://www.elastic.co/guide/en/ecs/current/ecs-data_stream.html
+func sanitizeDataStreamField(field, disallowed string, otel bool) string {
+	// For Dataset, the naming convention for datastream is expected to be "logs-[dataset].otel-[namespace]".
+	// This is in order to match the built-in logs-*.otel-* index template.
+	var suffix string
+	if otel {
+		suffix += ".otel"
+	}
```
Comment (carsonip) [inline exporter/elasticsearchexporter/data_stream_router.go:31]: move this back out of sanitization func, so that this func doesn't need to know about otel.

**Review by carsonip — COMMENTED** [review]
nice catch about the otel suffix! a comment about refactoring

File: exporter/elasticsearchexporter/data_stream_router.go (hunk 9 above)
Comment (carsonip) [reply exporter/elasticsearchexporter/data_stream_router.go:25]: also please update the comment of this func, to say that suffix will be added after truncation, not before.

**Review by carsonip — APPROVED** [review]
lgtm, thanks

**Review by lahsivjar — APPROVED** [review]

**Review by carsonip — APPROVED** [review]

File: exporter/elasticsearchexporter/data_stream_router.go [hunk 13]
```diff
@@ -6,12 +6,39 @@ package elasticsearchexporter // import "github.com/open-telemetry/opentelemetry
...
 var receiverRegex = regexp.MustCompile(`/receiver/(\w*receiver)`)
 
+const (
+	maxDataStreamBytes       = 100
+	disallowedNamespaceRunes = "\\/*?\"<>| ,#:"
+	disallowedDatasetRunes   = "-\\/*?\"<>| ,#:"
+)
+
+// Sanitize the datastream fields (dataset, namespace) to apply restrictions
+// as outlined in https://www.elastic.co/guide/en/ecs/current/ecs-data_stream.html
```
Comment (crobert-1) [inline exporter/elasticsearchexporter/data_stream_router.go:24]: If I understand, it looks like datastream names are required to follow [index naming restrictions](https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-create-index.html#indices-create-api-path-params), which introduces more limits as well. Should we add those requirements as well, or are they irrelevant? (We can add more restrictions later, just bringing this up to ensure we're not missing anything).

File: exporter/elasticsearchexporter/data_stream_router.go [hunk 14]
```diff
@@ -6,12 +6,39 @@ package elasticsearchexporter // import "github.com/open-telemetry/opentelemetry
...
+	"unicode"
 
 	"go.opentelemetry.io/collector/pdata/pcommon"
 )
 
 var receiverRegex = regexp.MustCompile(`/receiver/(\w*receiver)`)
 
+const (
+	maxDataStreamBytes       = 100
+	disallowedNamespaceRunes = "\\/*?\"<>| ,#:"
```
[the remark this answers is not in the document]
Comment (carsonip) [reply exporter/elasticsearchexporter/data_stream_router.go:19]: Thanks for digging into the spec. You're right that the ecs docs disallow `-` in both dataset and namespace, but we are actually working on https://github.com/elastic/ecs/issues/2388 to fix the inconsistency. At a minimum, allowing `-` would make elasticsearchexporter align with the apm-server and Elasticsearch implementation. If it turns out `-` needs to be disallowed in namespace, we'll make a follow up change.

File: exporter/elasticsearchexporter/data_stream_router.go (hunk 13 above)
Comment (rubvs) [reply exporter/elasticsearchexporter/data_stream_router.go:24]: Hi @crobert-1. This is a "tricky" one. Thanks for the comment.

The datastream name is composed of `{data_stream.type}-{data_stream.dataset}-{data_stream.namespace}`. Here the `data_stream.type` restrictions are derived from the ES index restrictions, see [Restrictions on Values](https://github.com/elastic/ecs/blob/main/rfcs/text/0009-data_stream-fields.md)

Moreover, a lot of the index name restrictions are implicit in `data_stream.type`. For example, the `logs`, `traces`, and `metrics` prefixes are hardcoded into `data_stream.type`, making it impossible for the name to start with `.` or `..`.

**Review by carsonip — APPROVED** [review]

File: exporter/elasticsearchexporter/data_stream_router.go (hunk 13 above)
Comment (crobert-1) [reply exporter/elasticsearchexporter/data_stream_router.go:24]: That makes sense, I appreciate the clarification!

**Review by crobert-1 — APPROVED** [review]

**Review by carsonip — APPROVED** [review]

**Review by andrzej-stencel — COMMENTED** [review]
Shouldn't this be documented?

**Comment by rubvs** [comment]
> Shouldn't this be documented?

Hi @andrzej-stencel, I've updated the readme of ES exported to reference the restriction docs. Let me know if this suffices, or if you think I should articulate things differently.

**Review by carsonip — APPROVED** [review]

**Review by andrzej-stencel — APPROVED** [review]

**Comment by andrzej-stencel** [comment]
> > Shouldn't this be documented?
> 
> I've updated the readme of ES exporter to reference the restriction docs. Let me know if this suffices, or if you think I should articulate things differently.

Thanks @rubvs, this is better than nothing. Ideally the docs would mention that the restricted characters will be replaced with underscores `_`.
