### PR TITLE
Adopt dynamic docker stats functionality

### LINKED ISSUE #957: Docker Stats Receiver is not enabled
**Describe the bug**
This is related to PR #495. It looks like docker stats receiver is not enabled in cmd/components.go . I am not sure if it was intentional or we missed the the below logic by accident. Please enable the receiver.  

```
diff --git a/cmd/otelcontribcol/components.go b/cmd/otelcontribcol/components.go
index 6f2a3109..81cc726f 100644
--- a/cmd/otelcontribcol/components.go
+++ b/cmd/otelcontribcol/components.go
@@ -52,6 +52,8 @@ import (
        "github.com/open-telemetry/opentelemetry-collector-contrib/receiver/splunkhecreceiver"
        "github.com/open-telemetry/opentelemetry-collector-contrib/receiver/statsdreceiver"
        "github.com/open-telemetry/opentelemetry-collector-contrib/receiver/wavefrontreceiver"
+       "github.com/open-telemetry/opentelemetry-collector-contrib/receiver/dockerstatsreceiver"
+
 )
 
 func components() (component.Factories, error) {
@@ -90,6 +92,7 @@ func components() (component.Factories, error) {
                statsdreceiver.NewFactory(),
                awsxrayreceiver.NewFactory(),
                splunkhecreceiver.NewFactory(),
+               dockerstatsreceiver.NewFactory(),
        }
        for _, rcv := range factories.Receivers {
                receivers = append(receivers, rcv)
```

**Steps to reproduce**

The build from the latest commit when loaded with the below config 
`./otelcontribcol --config otel-config.yml`

throws the following error
```
otel-collector_1  | {"level":"info","ts":1599247061.6296563,"caller":"service/telemetry.go:106","msg":"Serving Prometheus metrics","address":":8888","legacy_metrics":false,"new_metrics":true,"level":3,"service.instance.id":"33fd869b-e9cc-4ae7-8bfc-9b1272906c1f"}
otel-collector_1  | {"level":"info","ts":1599247061.6300523,"caller":"service/service.go:277","msg":"Loading configuration..."}
otel-collector_1  | Error: cannot load configuration: unknown receivers type "docker_stats" for docker_stats
otel-collector_1  | 2020/09/04 19:17:41 application run finished with error: cannot load configuration: unknown receivers type "docker_stats" for docker_stats
```

**What did you expect to see?**

OTel Controller comes up fine and docker stats shows up as expected.

**What did you see instead?**
OTel Collector stops because it cannot recognize `docker_stats` receiver

**What version did you use?**
Version: (commit: c1463db848fb7c83096190b32afb8af)

**What config did you use?**

```
receivers:
  docker_stats:
    endpoint:
    collection_interval: 60s
    provide_per_core_cpu_metrics: true

exporters:
  file:
    path: ./filename.json

service:
  pipelines:
    metrics:
      receivers: [docker_stats]
      exporters: [file]
```
**Environment**
Compiler(if manually compiled): Ran `make docker-otelcontribcol`

**Additional context**
I posted the diff in the components.go that makes the collector work. Happy to submit a PR but I wanted to make sure if docker_stats receiver was not included purposefully 

PS: Great Addition to the list of receivers!

### PR DESCRIPTION
**Pull request by rmfitzpatrick**
**Description:**
Adding a feature - Adds a core docker event loop to allow the collector to monitor docker stats for containers that were not running during the initialization of the receiver.  ~~Also sources the docker stats receiver as a top level component.~~

**Link to tracking Issue:** ~~resolves https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/957~~

**Testing:** Includes additional unit and integration tests.  Also adds a remove container feature to the test container helpers to assist in verifying dynamic container monitoring.

**Documentation:** will add to changelog

### CODE REVIEW

**Comment by rmfitzpatrick** [comment]
Load test failures shouldn't be relevant to these changes.

File: cmd/otelcontribcol/components.go [hunk 1]
```diff
@@ -41,6 +41,7 @@ import (
 	"github.com/open-telemetry/opentelemetry-collector-contrib/receiver/awsxrayreceiver"
 	"github.com/open-telemetry/opentelemetry-collector-contrib/receiver/carbonreceiver"
 	"github.com/open-telemetry/opentelemetry-collector-contrib/receiver/collectdreceiver"
+	"github.com/open-telemetry/opentelemetry-collector-contrib/receiver/dockerstatsreceiver"
```
Comment (bogdandrutu) [inline cmd/otelcontribcol/components.go:44]: Please split the adding the component to the binary, vs other changes to the component in separate PRs.

File: internal/common/testing/container/container.go [hunk 2]
```diff
@@ -79,7 +80,7 @@ func New(t *testing.T) *Containers {
 		t.Fatalf("failed creating docker client from environment: %v", err)
 	}
 
-	ctx := &Containers{cli: cli, t: t}
+	ctx := &Containers{cli: cli, runningContainers: make(map[ID]Container), t: t}
```
Comment (bogdandrutu) [inline internal/common/testing/container/container.go:83]: Does "Containers" need to be public?

File: internal/common/testing/container/container.go [hunk 3]
```diff
@@ -36,7 +37,7 @@ type ID string
 // Containers holds the set of running containers during the test.
 type Containers struct {
 	cli               client.CommonAPIClient
-	runningContainers []ID
+	runningContainers map[ID]Container
```
Comment (bogdandrutu) [inline internal/common/testing/container/container.go:40]: Does "Container" need to be public?

Comment (rmfitzpatrick) [reply internal/common/testing/container/container.go:40]: this is inherited from https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/306, but I think it's preferable to be exported since it's the return type of `StartImage` and a parameter for the proposed `RemoveContainer`

File: cmd/otelcontribcol/components.go (hunk 1 above)
Comment (rmfitzpatrick) [reply cmd/otelcontribcol/components.go:44]: It appears to be common practice for new components to be included here out of the gate.  If this is a policy we need to enforce I think it should be clearly documented or even warrant automation.

File: internal/common/testing/container/container.go (hunk 2 above)
Comment (rmfitzpatrick) [reply internal/common/testing/container/container.go:83]: again, not introduced in this PR but our golangci-lint suggests it should be:
```
exported func New returns unexported type *github.com/open-telemetry/opentelemetry-collector-contrib/internal/common/testing/container.containers, which can be annoying to use
```

File: cmd/otelcontribcol/components.go (hunk 1 above)
Comment (rmfitzpatrick) [reply cmd/otelcontribcol/components.go]: removed

**Comment by tigrannajaryan** [comment]
@bogdandrutu assigned to you since you already reviewed.

File: receiver/dockerstatsreceiver/docker.go [hunk 4]
```diff
@@ -194,6 +194,61 @@ func (dc *dockerClient) toStatsJSON(
 	return &statsJSON, nil
 }
 
+func (dc *dockerClient) ContainerEventLoop(ctx context.Context) {
```
Comment (bogdandrutu) [inline receiver/dockerstatsreceiver/docker.go:197]: The context you use is incorrect, because it is derived from the `Start` call which may be canceled as part of ensuring start of the components happens with a deadline as an example.

So you need to use either a separate channel for cancelation or derive the context from background.

Comment (bogdandrutu) [reply receiver/dockerstatsreceiver/docker.go:197]: No. Start context can have associated a deadline to ensure the collector starts in x seconds (and by doing that it is always recommend to cancel the context even if the request finish successfully). So that will cancel the loop which is not expected. I will add a comment to the Start interface that context cannot be saved or used in any async work

File: receiver/dockerstatsreceiver/docker.go [hunk 5]
```diff
@@ -194,6 +194,61 @@ func (dc *dockerClient) toStatsJSON(
...
+					if container, ok := dc.inspectedContainerIsOfInterest(ctx, event.ID); ok {
+						dc.persistContainer(container)
+					}
+				}
+
+				lastTime = time.Unix(0, event.TimeNano)
+			case err := <-errCh:
+				// We are only interested when the context hasn't been canceled
+				if ctx.Err() == nil {
+					dc.logger.Error("Error watching docker container events", zap.Error(err))
```
[the remark this answers is not in the document]
Comment (rmfitzpatrick) [reply receiver/dockerstatsreceiver/docker.go:243]: iirc from the cli event code it's from invalid json responses or general errors from the daemon, as long as we constrain to be errors unrelated to the parent context being closed.

File: receiver/dockerstatsreceiver/docker.go (hunk 4 above)
Comment (rmfitzpatrick) [reply receiver/dockerstatsreceiver/docker.go:197]: Thanks, it's unclear to me how that context should or shouldn't be used otherwise.

File: receiver/dockerstatsreceiver/docker.go [hunk 6]
```diff
@@ -194,6 +194,61 @@ func (dc *dockerClient) toStatsJSON(
...
+func (dc *dockerClient) ContainerEventLoop(ctx context.Context) {
+	filters := dfilters.NewArgs([]dfilters.KeyValuePair{
+		{Key: "type", Value: "container"},
+		{Key: "event", Value: "destroy"},
+		{Key: "event", Value: "die"},
+		{Key: "event", Value: "pause"},
+		{Key: "event", Value: "stop"},
+		{Key: "event", Value: "start"},
+		{Key: "event", Value: "unpause"},
+		{Key: "event", Value: "update"},
```
[the remark this answers is not in the document]
Comment (rmfitzpatrick) [reply receiver/dockerstatsreceiver/docker.go:206]: It doesn't appear so:
```
delete.go
	daemon.LogContainerEvent(container, "destroy")
monitor.go
	daemon.LogContainerEventWithAttributes(c, "die", attributes)
	daemon.LogContainerEvent(c, "start")
	daemon.LogContainerEvent(c, "pause")
	daemon.LogContainerEvent(c, "unpause")
pause.go
	daemon.LogContainerEvent(container, "pause")
restart.go
	daemon.LogContainerEvent(container, "restart")
start.go
	daemon.LogContainerEvent(container, "start")
stop.go
	daemon.LogContainerEvent(container, "stop")
unpause.go
	daemon.LogContainerEvent(container, "unpause")
update.go
	daemon.LogContainerEvent(container, "update")
```

File: receiver/dockerstatsreceiver/docker.go (hunk 4 above)
Comment (bogdandrutu) [reply receiver/dockerstatsreceiver/docker.go:197]: Trying to clarify this: https://github.com/open-telemetry/opentelemetry-collector/pull/1754

File: receiver/dockerstatsreceiver/docker.go (hunk 5 above)
[the remark this answers is not in the document]
Comment (tigrannajaryan) [reply receiver/dockerstatsreceiver/docker.go:243]: I am not sure I understand your reply.
If it is a transient error it would be nice to add a comment explaining it in the code to make it clear why we keep running the loop. It is not apparent looking at the code.

File: receiver/dockerstatsreceiver/docker.go [hunk 7]
```diff
@@ -194,6 +194,61 @@ func (dc *dockerClient) toStatsJSON(
...
+						zap.String("id", event.ID),
+						zap.String("action", event.Action),
+					)
+
+					if container, ok := dc.inspectedContainerIsOfInterest(ctx, event.ID); ok {
+						dc.persistContainer(container)
+					}
+				}
+
+				lastTime = time.Unix(0, event.TimeNano)
```
[the remark this answers is not in the document]
Comment (rmfitzpatrick) [reply receiver/dockerstatsreceiver/docker.go]: It's a streaming api but I'm not sure in order events are guaranteed.  Added max.

File: receiver/dockerstatsreceiver/docker.go [hunk 8]
```diff
@@ -194,6 +194,61 @@ func (dc *dockerClient) toStatsJSON(
...
+			case err := <-errCh:
+				// We are only interested when the context hasn't been canceled
+				if ctx.Err() == nil {
+					dc.logger.Error("Error watching docker container events", zap.Error(err))
+					time.Sleep(3 * time.Second)
```
[the remark this answers is not in the document]
Comment (rmfitzpatrick) [reply receiver/dockerstatsreceiver/docker.go]: good catch, updated.

File: receiver/dockerstatsreceiver/docker.go (hunk 5 above)
[the remark this answers is not in the document]
Comment (rmfitzpatrick) [reply receiver/dockerstatsreceiver/docker.go:247]: If the docker daemon were to temporarily refuse/drop connections or restart it seems that recovering would be preferable to logging an error and halting most dynamic update functionality.  Otherwise only the containers that are running from the beginning of the collector lifetime will be monitored.  Is the added comment ok?

File: receiver/dockerstatsreceiver/docker.go [hunk 9]
```diff
@@ -216,8 +271,17 @@ func (dc *dockerClient) persistContainer(containerJSON *dtypes.ContainerJSON) {
...
 	cid := containerJSON.ID
+	if !containerJSON.State.Running || containerJSON.State.Paused {
+		dc.logger.Debug("Docker container not running.  Will not persist.", zap.String("id", cid))
+		dc.removeContainer(cid)
+		return
+	}
+
 	dc.logger.Debug("Monitoring Docker container", zap.String("id", cid))
+	dc.containersLock.Lock()
+	defer dc.containersLock.Unlock()
```
[the remark this answers is not in the document]
Comment (rmfitzpatrick) [reply receiver/dockerstatsreceiver/docker.go:295]: I agree and think we could collapse container management to another type if/when additional client functionality is required.

File: internal/common/testing/container/container_integration_test.go [hunk 10]
```diff
@@ -53,9 +54,22 @@ func TestContainerIntegration(t *testing.T) {
...
 	require.True(t, client.IsErrNotFound(err), "inspect error should have been of type not found")
 }
+
+func TestRemoveContainerIntegration(t *testing.T) {
+	con := New(t)
+	nginx := con.StartImage("docker.io/library/nginx:1.17", WithPortReady(80))
+
+	err := con.RemoveContainer(nginx)
+	require.NoError(t, err)
+	require.Zero(t, len(con.runningContainers))
```
[the remark this answers is not in the document]
Comment (rmfitzpatrick) [reply internal/common/testing/container/container_integration_test.go:71]: good idea, updated.

**Review by tigrannajaryan — COMMENTED** [review]
LGTM.

@bogdandrutu you had comments, are you OK to merge or you still have questions?

**Comment by bogdandrutu** [comment]
@tigrannajaryan my main concerns were addressed, I had not look in more details but I trust you did :)

**Comment by rmfitzpatrick** [comment]
@tigrannajaryan is this ok to land?

**Review by tigrannajaryan — APPROVED** [review]
