### PR TITLE
[receiver/opencensus] refactor the code for maintenance and lifecycle tests

### LINKED ISSUE #31643: [receiver/opencensus] Flaky test TestComponentLifecycle
```
=== Failed
make[2]: *** [../../Makefile.Common:131: test-with-cover] Error 3
=== FAIL: . TestComponentLifecycle/metrics-shutdown (0.00s)
    generated_component_test.go:50: 
        	Error Trace:	/home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/receiver/opencensusreceiver/generated_component_test.go:50
        	Error:      	Received unexpected error:
make[1]: *** [Makefile:165: receiver/opencensusreceiver] Error 2
make: *** [Makefile:117: gotest-with-cover] Error 2
        	            	failed to bind to address "0.0.0.0:55678": listen tcp 0.0.0.0:55678: bind: address already in use
        	Test:       	TestComponentLifecycle/metrics-shutdown

=== FAIL: . TestComponentLifecycle/traces-shutdown (0.00s)

=== FAIL: . TestComponentLifecycle (0.00s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x129e5fc]
```
Seems like there is some port conflict for opencensusreceiver in CI. Not sure but maybe parallel builds?

_Originally posted by @pepperkick in https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/31622#issuecomment-1982347975_

### PR DESCRIPTION
**Pull request by atoulme**
**Description:**
Simplify the code of the opencensus receiver to make it more maintainable, reduce leaks and pass lifecycle tests.

**Link to tracking Issue:**
Fixes #31643

### CODE REVIEW

**Comment by atoulme** [comment]
@open-telemetry/collector-contrib-approvers please review

File: receiver/opencensusreceiver/opencensus.go [hunk 1]
```diff
@@ -81,184 +74,134 @@ func newOpenCensusReceiver(
...
-}
+	startWG.Wait()
 
-func (ocr *ocReceiver) grpcServer(host component.Host) (*grpc.Server, error) {
-	ocr.mu.Lock()
-	defer ocr.mu.Unlock()
+	opts := []grpc.DialOption{grpc.WithTransportCredentials(insecure.NewCredentials()), grpc.WithBlock()}
+	if err := agenttracepb.RegisterTraceServiceHandlerFromEndpoint(c, ocr.gatewayMux, endpoint, opts); err != nil {
+		return err
+	}
```
Comment (dmitryax) [inline receiver/opencensusreceiver/opencensus.go:168]: Just curious why this has to be moved after the Serve() calls?

**Review by dmitryax — APPROVED** [review]

**Review by fatsheep9146 — APPROVED** [review]
