### PR TITLE
change OR to AND logic for filtering logs

### LINKED ISSUE #11439: [processor/attributes] log_severity_texts does not filter
**Describe the bug**
log_severity_texts filter simply doesn't work
tried the example here and doesn't work either : 
https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/processor/attributesprocessor/testdata/config.yaml

For example :

```
    attributes:
        include:
            match_type: strict
            log_severity_texts: [ "TRACE" ]
        actions:
            -   key: should_exclude
                action: upsert
                value: true
```

should_exclude is added to every log instead of traces only.

**Steps to reproduce**
Use log_severity_texts to filter the attribute processor.

**What did you expect to see?**
Attribute processor to be filtered.

**What did you see instead?**
Attribute processor to be applied always.

**What version did you use?**
otel/opentelemetry-collector-contrib:0.53.0

**What config did you use?**

```
receivers:
  otlp:
    protocols:
      http:
        cors:
          allowed_origins: [
            #OMITTED
          ]

processors:
    memory_limiter:
        check_interval: 5s
        limit_mib: 448
        spike_limit_mib: 64
    batch:
        send_batch_size: 48
        send_batch_max_size: 48
        timeout: 15s
    attributes:
        include:
            match_type: strict
            log_severity_texts: [ "TRACE" ]
        actions:
            -   key: should_exclude
                action: upsert
                value: true
    filter:
        logs:
            exclude:
                match_type: strict
                record_attributes:
                    - key: should_exclude
                      value: true

exporters:
    logging:
        loglevel: debug
        sampling_initial: 2
    otlp:
        endpoint: tempo-eu-west-0.grafana.net:443
        headers:
            authorization: Basic #OMITTED
            
    prometheusremotewrite:
        endpoint: https://prometheus-prod-01-eu-west-0.grafana.net/api/prom/push
        headers:
            authorization: Basic #OMITTED
            
    loki:
        endpoint: https://logs-prod-eu-west-0.grafana.net/loki/api/v1/push
        headers:
            authorization: Basic #OMITTED
        format: json
        labels:
            attributes:
                container_name: ""
                source: ""
            resource:
                host.name: "hostname"

extensions:
    health_check:

service:
  extensions: [health_check]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [otlp]
    metrics:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [prometheusremotewrite]
    logs:
      receivers: [otlp]
      processors: [attributes, filter]
      exporters: [logging]
```

### PR DESCRIPTION
**Pull request by zeitlinger**
change OR to AND logic for filtering logs - as desribed, and as is done for span filtering

Fixes https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/11439

### CODE REVIEW

File: internal/coreinternal/processor/filterlog/filterlog.go [hunk 1]
```diff
@@ -90,11 +90,11 @@ func NewMatcher(mp *filterconfig.MatchProperties) (Matcher, error) {
 // supported to have more than one of these specified, and all specified must
 // evaluate to true for a match to occur.
 func (mp *propertiesMatcher) MatchLogRecord(lr plog.LogRecord, resource pcommon.Resource, library pcommon.InstrumentationScope) bool {
-	if lr.Body().Type() == pcommon.ValueTypeString && mp.bodyFilters != nil && mp.bodyFilters.Matches(lr.Body().StringVal()) {
-		return true
+	if lr.Body().Type() == pcommon.ValueTypeString && mp.bodyFilters != nil && !mp.bodyFilters.Matches(lr.Body().StringVal()) {
+		return false
 	}
-	if mp.severityTextFilters != nil && mp.severityTextFilters.Matches(lr.SeverityText()) {
-		return true
```
Comment (dmitryax) [inline internal/coreinternal/processor/filterlog/filterlog.go:97]: Why this didn't work for https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/11439 before?

**Review by dmitryax — COMMENTED** [review]
I see what's fixed in this PR, but I don't understand how it fixes https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/11439

File: internal/coreinternal/processor/filterlog/filterlog.go (hunk 1 above)
Comment (zeitlinger) [reply internal/coreinternal/processor/filterlog/filterlog.go:97]: if the severity didn't match, it would simply go to the next check (attributes) - and this would match (empty expected attributes means it always matches).

I've added a missing test case that reproduced this behavior.

Comment (dmitryax) [reply internal/coreinternal/processor/filterlog/filterlog.go:97]: Makes sense. Thanks for clarifying!

**Review by dmitryax — APPROVED** [review]
