### PR TITLE
[exporter/datadogexporter] Handle monotonic metrics client-side

### LINKED ISSUE #1688: [datadog exporter] Counter metrics are being sent as Gauges
**Describe the bug**
Counter metrics are incorrectly being reported to Datadog as Gauge metrics

**Steps to reproduce**
Create a `LongCounter` metric.  Send it to datadog using the exporter.

**What did you expect to see?**
I expected to see delta values sent to datadog such that in the Datadog UI each datapoint represents the count within that interval.

**What did you see instead?**
 I see a monotonically increasing chart for the metric.

**What version did you use?**
Version: v0.11.0

**What config did you use?**
Config: 
```yaml
receivers:
  otlp:
    protocols:
      grpc:

processors:
  batch:
    timeout: 10s

exporters:
  logging:
    logLevel: debug
  datadog:
    api:
      key: xxx

service:
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging, datadog]
```

**Environment**
OS: Manjaro Linux

**Additional context**
It seems that this shoudl be mapped as a `monotonic_count` from [these docs](https://docs.datadoghq.com/integrations/guide/prometheus-metrics/).

You can see from the code that `Gauge` and `Counter` metrics are treated identically.  This seems incorrect
```go
				case pdata.MetricDataTypeIntGauge:
					datapoints = mapIntMetrics(md.Name(), md.IntGauge().DataPoints())
				case pdata.MetricDataTypeDoubleGauge:
					datapoints = mapDoubleMetrics(md.Name(), md.DoubleGauge().DataPoints())
				case pdata.MetricDataTypeIntSum:
					// Ignore aggregation temporality; report raw values
					datapoints = mapIntMetrics(md.Name(), md.IntSum().DataPoints())
				case pdata.MetricDataTypeDoubleSum:
					// Ignore aggregation temporality; report raw values
					datapoints = mapDoubleMetrics(md.Name(), md.DoubleSum().DataPoints())
```

### PR DESCRIPTION
**Pull request by mx-psi**
**Description:** 

- For cumulative monotonic metrics we now calculate the rate and send this to Datadog's backend instead of the raw value. An option to disable this behavior has been added to the configuration

**Link to tracking Issue:** fixes #1688

**Testing:** 

- Added relevant unit tests. 
- Tested with opentelemetry-go and checked the rate sent was correct for different push frecuencies.
- Tested with statsdreceiver: found bug #1789
- Tested with hostmetrics receiver and compared with Datadog Agent:
    * Pattern looks similar (ddagent is more smooth because of the 10s flush interval)
    * Units look different but I haven't given a close look at the code to see if they do the same gopsutil calls

**Documentation:** 

- Started configuration settings table in the README. 
  Documented new configuration options in the usual places.

**Additional context**

Datadog's backend normalizes intervals for counter metrics to a whole number of seconds, thus it is not suitable here because of the possibility of sub-second intervals. An alternative is to send the raw diffs as a gauge, but I think it's then just better to send the raw increasing value and let the user manage it according to their preferences.

### CODE REVIEW

File: exporter/datadogexporter/factory.go [hunk 1]
```diff
@@ -59,6 +59,8 @@ func createDefaultConfig() configmodels.Exporter {
 			TCPAddr: confignet.TCPAddr{
 				Endpoint: "", // set during config sanitization
 			},
+			SendMonotonic: true,
```
Comment (mx-psi) [inline exporter/datadogexporter/factory.go:62]: This is technically a breaking change. Should we add a warning and wait for one release until we actually enable this?

File: exporter/datadogexporter/metrics_translator.go [hunk 2]
```diff
@@ -39,9 +41,30 @@ func getTags(labels pdata.StringMap) []string {
...
+		return md.DoubleSum().AggregationTemporality() == pdata.AggregationTemporalityCumulative &&
+			md.DoubleSum().IsMonotonic()
+	}
+	return false
+}
+
+// metricDimensionsToMapKey maps name and tags to a string to use as an identifier
+// The tags order does not matter
+func metricDimensionsToMapKey(name string, tags []string) string {
+	const separator string = "}{" // These are invalid in tags
```
Comment (mx-psi) [inline exporter/datadogexporter/metrics_translator.go:60]: I think it is rather unlikely that something bad happens here but this could be a problem if someone uses arbitrary values in tags. We could use some different separator if there is any that we know for sure can't be in tags (even arbitrary ones)

File: exporter/datadogexporter/metrics_translator.go [hunk 3]
```diff
@@ -63,6 +85,89 @@ func mapDoubleMetrics(name string, slice pdata.DoubleDataPointSlice) []datadog.M
...
+			cnt := c.(intCounter)
+
+			// We calculate the time-normalized delta
+			dx := float64(p.Value() - cnt.value)
+			dt := float64(ts-cnt.ts) / 1e9
+
+			if dt <= 0 {
+				// We were given a point older than the one in memory so we drop it
+				// We keep the existing point in memory since it is the most recent
+				continue
```
Comment (mx-psi) [inline exporter/datadogexporter/metrics_translator.go:114]: Can this actually happen or are timeseries always ordered? I could not find anything relevant in the spec.

File: exporter/datadogexporter/factory.go (hunk 1 above)
Comment (bogdandrutu) [reply exporter/datadogexporter/factory.go:62]: Up to you

**Review by bogdandrutu — APPROVED** [review]

File: exporter/datadogexporter/metrics_translator_test.go [hunk 4]
```diff
@@ -81,6 +148,259 @@ func TestMapDoubleMetrics(t *testing.T) {
...
+		expected[i] = metrics.NewRate(metricName, uint64(seconds(i+1)), val, []string{})
+	}
+
+	prevPts := newTTLMap()
+	output := mapDoubleMonotonicMetrics(metricName, prevPts, slice)
+
+	assert.ElementsMatch(t, expected, output)
+}
+
+func TestMapDoubleMonotonicDifferentDimension(t *testing.T) {
```
Comment (KSerrania) [inline exporter/datadogexporter/metrics_translator_test.go:313]: Nit:
```suggestion
func TestMapDoubleMonotonicDifferentDimensions(t *testing.T) {
```

**Review by KSerrania — APPROVED** [review]
Left a few nits, but otherwise this looks good to me.

File: exporter/datadogexporter/factory.go (hunk 1 above)
Comment (mx-psi) [reply exporter/datadogexporter/factory.go:62]: We discussed this internally at Datadog and want to enable this from the start.

**Comment by mx-psi** [comment]
@bogdandrutu This is ready to merge

**Review by kbrockhoff — APPROVED** [review]

**Review by bogdandrutu — APPROVED** [review]

File: exporter/datadogexporter/metrics_translator.go [hunk 5]
```diff
@@ -40,9 +42,30 @@ func getTags(labels pdata.StringMap) []string {
...
+// isCumulativeMonotonic checks if a metric is a cumulative monotonic metric
+func isCumulativeMonotonic(md pdata.Metric) bool {
+	switch md.DataType() {
+	case pdata.MetricDataTypeIntSum:
+		return md.IntSum().AggregationTemporality() == pdata.AggregationTemporalityCumulative &&
+			md.IntSum().IsMonotonic()
+	case pdata.MetricDataTypeDoubleSum:
+		return md.DoubleSum().AggregationTemporality() == pdata.AggregationTemporalityCumulative &&
+			md.DoubleSum().IsMonotonic()
+	}
```
Comment (sirianni) [inline exporter/datadogexporter/metrics_translator.go:54]: @mx-psi - Am I reading this correctly that if the client is already exporting metrics to the collector as `AGGREGATION_TEMPORALITY_DELTA` then they will be sent to datadog as is?

Comment (mx-psi) [reply exporter/datadogexporter/metrics_translator.go:54]: Yes, the cases for the current types are:
- For delta metrics the raw value is sent as a gauge
- For cumulative non-monotonic metrics, the raw value is sent as a gauge
- For cumulative monotonic metrics, the rate between the previous datapoint and the next one is calculated and is sent as a rate (this is what this PR does)

Comment (sirianni) [reply exporter/datadogexporter/metrics_translator.go:54]: > Would you expect it to be sent differently?

Nope, that makes sense.  I just wanted to confirm because we have configured our apps to export metrics via OTLP using `DeltaExportKindSelector`.  This was to work around #1688 but also because we have some internal metrics pipelines that rely on metrics being emitted as deltas as well.
```go
	pusher := push.New(
		basic.New(
			simple.NewWithExactDistribution(),
			metric.DeltaExportKindSelector(),
		),
```

Thanks for the quick reply!

Comment (mx-psi) [reply exporter/datadogexporter/metrics_translator.go:54]: Awesome, glad this makes sense to you :)
