### PR TITLE
Use the new scrape config endpoint for the prometheus receiver

### LINKED ISSUE #14597: Prometheus Receiver failing on using target allocator's scrape config
## Description
This is an issue to track the collector changes as a part of [this bug](https://github.com/open-telemetry/opentelemetry-operator/issues/1106)

## Steps to Reproduce
Found in the above issue.

## Expected Result
The prometheus receiver's target allocator configuration populates new jobs for the collector.

## Actual Result
errors in the above version

### Collector version

0.60.0

## Environment
OS: Kubernetes

### OpenTelemetry Collector configuration

```yaml
receivers:
      prometheus:
        config: 
          global:
            scrape_interval: 30s
          scrape_configs:
            - job_name: dummy
              static_configs:
                - targets:
                    - 127.0.0.1:8888
        target_allocator:
          endpoint: http://ta-test-targetallocator
          interval: 30s
          collector_id: ${POD_NAME}
          http_sd_config:
            refresh_interval: 60s
    exporters:
      prometheus:
        endpoint: :9100
        enable_open_metrics: true
        resource_to_telemetry_conversion:
          enabled: true
    service:
      pipelines:
        metrics:
          receivers:
            - prometheus
          exporters:
            - prometheus
      telemetry:
        metrics:
          address: 0.0.0.0:8888
```

### Log output

```shell
2022-09-16T16:59:34.907Z	info	service/telemetry.go:115	Setting up own telemetry...
2022-09-16T16:59:34.908Z	info	service/telemetry.go:156	Serving Prometheus metrics	{"address": "0.0.0.0:8888", "level": "basic"}
2022-09-16T16:59:34.910Z	info	service/service.go:112	Starting otelcol...	{"Version": "0.60.0", "NumCPU": 4}
2022-09-16T16:59:34.910Z	info	extensions/extensions.go:42	Starting extensions...
2022-09-16T16:59:34.910Z	info	pipelines/pipelines.go:74	Starting exporters...
2022-09-16T16:59:34.910Z	info	pipelines/pipelines.go:78	Exporter is starting...	{"kind": "exporter", "data_type": "metrics", "name": "prometheus"}
2022-09-16T16:59:34.910Z	info	pipelines/pipelines.go:82	Exporter started.	{"kind": "exporter", "data_type": "metrics", "name": "prometheus"}
2022-09-16T16:59:34.910Z	info	pipelines/pipelines.go:86	Starting processors...
2022-09-16T16:59:34.910Z	info	pipelines/pipelines.go:98	Starting receivers...
2022-09-16T16:59:34.910Z	info	pipelines/pipelines.go:102	Receiver is starting...	{"kind": "receiver", "name": "prometheus", "pipeline": "metrics"}
2022-09-16T16:59:34.911Z	info	pipelines/pipelines.go:106	Receiver started.	{"kind": "receiver", "name": "prometheus", "pipeline": "metrics"}
2022-09-16T16:59:34.911Z	info	service/service.go:129	Everything is ready. Begin running and processing data.
2022-09-16T16:59:39.911Z	error	scrape/scrape.go:488	Creating target failed	{"kind": "receiver", "name": "prometheus", "pipeline": "metrics", "scrape_pool": "/jobs/serviceMonitor%2Fdefault%2Fsm-test%2F0/targets", "error": "instance 0 in group http://ta-test-targetallocator/jobs/serviceMonitor%2Fdefault%2Fsm-test%2F0/targets?collector_id=ta-test-collector-0:1: scrape interval cannot be 0", "errorVerbose": "scrape interval cannot be 0\ngithub.com/prometheus/prometheus/scrape.PopulateLabels\n\tgithub.com/prometheus/prometheus@v0.38.0/scrape/target.go:446\ngithub.com/prometheus/prometheus/scrape.TargetsFromGroup\n\tgithub.com/prometheus/prometheus@v0.38.0/scrape/target.go:504\ngithub.com/prometheus/prometheus/scrape.(*scrapePool).Sync\n\tgithub.com/prometheus/prometheus@v0.38.0/scrape/scrape.go:486\ngithub.com/prometheus/prometheus/scrape.(*Manager).reload.func1\n\tgithub.com/prometheus/prometheus@v0.38.0/scrape/manager.go:222\nruntime.goexit\n\truntime/asm_amd64.s:1571\ninstance 0 in group http://ta-test-targetallocator/jobs/serviceMonitor%2Fdefault%2Fsm-test%2F0/targets?collector_id=ta-test-collector-0:1\ngithub.com/prometheus/prometheus/scrape.TargetsFromGroup\n\tgithub.com/prometheus/prometheus@v0.38.0/scrape/target.go:506\ngithub.com/prometheus/prometheus/scrape.(*scrapePool).Sync\n\tgithub.com/prometheus/prometheus@v0.38.0/scrape/scrape.go:486\ngithub.com/prometheus/prometheus/scrape.(*Manager).reload.func1\n\tgithub.com/prometheus/prometheus@v0.38.0/scrape/manager.go:222\nruntime.goexit\n\truntime/asm_amd64.s:1571"}
github.com/prometheus/prometheus/scrape.(*scrapePool).Sync
	github.com/prometheus/prometheus@v0.38.0/scrape/scrape.go:488
github.com/prometheus/prometheus/scrape.(*Manager).reload.func1
	github.com/prometheus/prometheus@v0.38.0/scrape/manager.go:222
2022-09-16T16:59:39.911Z	error	scrape/scrape.go:488	Creating target failed	{"kind": "receiver", "name": "prometheus", "pipeline": "metrics", "scrape_pool": "/jobs/dummy/targets", "error": "instance 0 in group http://ta-test-targetallocator/jobs/dummy/targets?collector_id=ta-test-collector-0:0: scrape interval cannot be 0", "errorVerbose": "scrape interval cannot be 0\ngithub.com/prometheus/prometheus/scrape.PopulateLabels\n\tgithub.com/prometheus/prometheus@v0.38.0/scrape/target.go:446\ngithub.com/prometheus/prometheus/scrape.TargetsFromGroup\n\tgithub.com/prometheus/prometheus@v0.38.0/scrape/target.go:504\ngithub.com/prometheus/prometheus/scrape.(*scrapePool).Sync\n\tgithub.com/prometheus/prometheus@v0.38.0/scrape/scrape.go:486\ngithub.com/prometheus/prometheus/scrape.(*Manager).reload.func1\n\tgithub.com/prometheus/prometheus@v0.38.0/scrape/manager.go:222\nruntime.goexit\n\truntime/asm_amd64.s:1571\ninstance 0 in group http://ta-test-targetallocator/jobs/dummy/targets?collector_id=ta-test-collector-0:0\ngithub.com/prometheus/prometheus/scrape.TargetsFromGroup\n\tgithub.com/prometheus/prometheus@v0.38.0/scrape/target.go:506\ngithub.com/prometheus/prometheus/scrape.(*scrapePool).Sync\n\tgithub.com/prometheus/prometheus@v0.38.0/scrape/scrape.go:486\ngithub.com/prometheus/prometheus/scrape.(*Manager).reload.func1\n\tgithub.com/prometheus/prometheus@v0.38.0/scrape/manager.go:222\nruntime.goexit\n\truntime/asm_amd64.s:1571"}
github.com/prometheus/prometheus/scrape.(*scrapePool).Sync
	github.com/prometheus/prometheus@v0.38.0/scrape/scrape.go:488
github.com/prometheus/prometheus/scrape.(*Manager).reload.func1
	github.com/prometheus/prometheus@v0.38.0/scrape/manager.go:222
2022-09-16T16:59:39.911Z	error	scrape/scrape.go:488	Creating target failed	{"kind": "receiver", "name": "prometheus", "pipeline": "metrics", "scrape_pool": "/jobs/serviceMonitor%2Fdefault%2Fsm-test%2F0/targets", "error": "instance 0 in group http://ta-test-targetallocator/jobs/serviceMonitor%2Fdefault%2Fsm-test%2F0/targets?collector_id=ta-test-collector-0:0: scrape interval cannot be 0", "errorVerbose": "scrape interval cannot be 0\ngithub.com/prometheus/prometheus/scrape.PopulateLabels\n\tgithub.com/prometheus/prometheus@v0.38.0/scrape/target.go:446\ngithub.com/prometheus/prometheus/scrape.TargetsFromGroup\n\tgithub.com/prometheus/prometheus@v0.38.0/scrape/target.go:504\ngithub.com/prometheus/prometheus/scrape.(*scrapePool).Sync\n\tgithub.com/prometheus/prometheus@v0.38.0/scrape/scrape.go:486\ngithub.com/prometheus/prometheus/scrape.(*Manager).reload.func1\n\tgithub.com/prometheus/prometheus@v0.38.0/scrape/manager.go:222\nruntime.goexit\n\truntime/asm_amd64.s:1571\ninstance 0 in group http://ta-test-targetallocator/jobs/serviceMonitor%2Fdefault%2Fsm-test%2F0/targets?collector_id=ta-test-collector-0:0\ngithub.com/prometheus/prometheus/scrape.TargetsFromGroup\n\tgithub.com/prometheus/prometheus@v0.38.0/scrape/target.go:506\ngithub.com/prometheus/prometheus/scrape.(*scrapePool).Sync\n\tgithub.com/prometheus/prometheus@v0.38.0/scrape/scrape.go:486\ngithub.com/prometheus/prometheus/scrape.(*Manager).reload.func1\n\tgithub.com/prometheus/prometheus@v0.38.0/scrape/manager.go:222\nruntime.goexit\n\truntime/asm_amd64.s:1571"}
github.com/prometheus/prometheus/scrape.(*scrapePool).Sync
	github.com/prometheus/prometheus@v0.38.0/scrape/scrape.go:488
github.com/prometheus/prometheus/scrape.(*Manager).reload.func1
	github.com/prometheus/prometheus@v0.38.0/scrape/manager.go:222
```

### Additional context

This issue is solely for tracking the collector changes required to make this work.

### PR DESCRIPTION
**Pull request by jaronoff97**
**Description:**
This PR fixes issue 1106 in the operator which relates to the collector failing to get scrape config jobs from the target allocator. Before this is merged [this pr](https://github.com/open-telemetry/opentelemetry-operator/pull/1124) needs to be merged which adds this new endpoint.

**Link to tracking Issue:**
https://github.com/open-telemetry/opentelemetry-operator/issues/1106

**Testing:**
This was tested by running a custom collector in a kubernetes cluster with the changes in the operator and target allocator. You can see the collector pulling expected jobs from the target allocator here.

Screen Shot 2022-09-28 at 6 50 49 PM

**Documentation:** <Describe the documentation added.>

Closes https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/14597

### CODE REVIEW

File: receiver/prometheusreceiver/metrics_receiver.go [hunk 1]
```diff
@@ -92,36 +114,48 @@ func (r *pReceiver) Start(_ context.Context, host component.Host) error {
...
 	return nil
 }
 
+func (r *pReceiver) initTargetAllocator(allocConf *targetAllocator, baseCfg *config.Config) {
+	r.settings.Logger.Info("Starting target allocator discovery")
+	// immediately sync jobs and not wait for the first tick
+	savedHash, err := r.syncTargetAllocator(uint64(0), allocConf, baseCfg)
+	if err != nil {
+		r.settings.Logger.Error(err.Error())
+		return
```
Comment (kristinapathak) [inline receiver/prometheusreceiver/metrics_receiver.go:131]: Should `initTargetAllocator()` return an error when this fails?  Previously, the go routine would continue to try calling `syncTargetAllocator()`, even if an error occurred the first time.

File: receiver/prometheusreceiver/config.go [hunk 2]
```diff
@@ -165,8 +165,8 @@ func (cfg *Config) Validate() error {
 }
 
 func (cfg *Config) validatePromConfig(promConfig *promconfig.Config) error {
-	if len(promConfig.ScrapeConfigs) == 0 {
-		return errors.New("no Prometheus scrape_configs")
+	if len(promConfig.ScrapeConfigs) == 0 && cfg.TargetAllocator == nil {
```
Comment (moh-osman3) [inline receiver/prometheusreceiver/config.go:168]: Wondering why is an empty scrape config valid if `cfg.TargetAllocator != nil`?

File: receiver/prometheusreceiver/metrics_receiver.go [hunk 3]
```diff
@@ -92,36 +110,51 @@ func (r *pReceiver) Start(_ context.Context, host component.Host) error {
...
 
+func (r *pReceiver) initTargetAllocator(allocConf *targetAllocator, baseCfg *config.Config) error {
+	r.settings.Logger.Info("Starting target allocator discovery")
+	// immediately sync jobs and not wait for the first tick
+	savedHash, err := r.syncTargetAllocator(uint64(0), allocConf, baseCfg)
+	if err != nil {
+		return err
+	}
+	r.targetAllocatorIntervalTicker = time.NewTicker(allocConf.Interval)
+	go func() {
```
Comment (moh-osman3) [inline receiver/prometheusreceiver/metrics_receiver.go:132]: Wondering why the decision to pull this into its own function and move the `go func() {` block down after the call to `r.syncTargetAllocator`?

**Review by moh-osman3 — COMMENTED** [review]
Just a couple general questions I have.

File: receiver/prometheusreceiver/config.go (hunk 2 above)
Comment (jaronoff97) [reply receiver/prometheusreceiver/config.go:168]: We want to allow someone to specify only a target allocator to pull its configuration from rather than a target allocator and a job with some dummy data so that the collector can be run. 

Better said – some collectors may only want to use configuration from the target allocator's scrape_configs endpoint and nothing else.

File: receiver/prometheusreceiver/metrics_receiver.go (hunk 3 above)
Comment (jaronoff97) [reply receiver/prometheusreceiver/metrics_receiver.go:132]: That's to pull jobs before the scrape manager has a chance to begin so that as soon as the collector's scraping begins, it already has targets from the target allocator. It also means we'll fail fast if the target allocator isn't up and healthy.

File: receiver/prometheusreceiver/metrics_receiver.go [hunk 4]
```diff
@@ -41,33 +46,46 @@ const (
 	gcIntervalDelta   = 1 * time.Minute
 )
 
+// closeOnce ensures that the scrape manager is started after the discovery manager
+type closeOnce struct {
+	C     chan struct{}
```
Comment (moh-osman3) [inline receiver/prometheusreceiver/metrics_receiver.go:51]: Would it be worthwhile to rename `C` to something more descriptive? like `channel` or `discoveryStartedChannel`

File: receiver/prometheusreceiver/metrics_receiver.go [hunk 5]
```diff
@@ -92,36 +110,51 @@ func (r *pReceiver) Start(_ context.Context, host component.Host) error {
...
 }
 
+func (r *pReceiver) initTargetAllocator(allocConf *targetAllocator, baseCfg *config.Config) error {
+	r.settings.Logger.Info("Starting target allocator discovery")
+	// immediately sync jobs and not wait for the first tick
+	savedHash, err := r.syncTargetAllocator(uint64(0), allocConf, baseCfg)
+	if err != nil {
+		return err
+	}
+	r.targetAllocatorIntervalTicker = time.NewTicker(allocConf.Interval)
```
Comment (moh-osman3) [inline receiver/prometheusreceiver/metrics_receiver.go:131]: Should this ticker be local to the go routine in the line below?

File: receiver/prometheusreceiver/metrics_receiver.go [hunk 6]
```diff
@@ -92,36 +110,51 @@ func (r *pReceiver) Start(_ context.Context, host component.Host) error {
...
+	go func() {
+		<-r.reloadReady.C
```
Comment (moh-osman3) [inline receiver/prometheusreceiver/metrics_receiver.go:133]: Wondering what is writing to this channel that we're reading from here?

**Review by moh-osman3 — COMMENTED** [review]
A few more followup questions for my understanding.

File: receiver/prometheusreceiver/metrics_receiver.go (hunk 4 above)
Comment (jaronoff97) [reply receiver/prometheusreceiver/metrics_receiver.go:51]: iirc this is a go convention, but I definitely can make this more clear.

File: receiver/prometheusreceiver/metrics_receiver.go (hunk 6 above)
Comment (jaronoff97) [reply receiver/prometheusreceiver/metrics_receiver.go:133]: We're closing the channel after all the components have been initialized [here](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/14464/files/a46743edad8c4c67e2a19cb67722966d252c3ade#diff-8172ccc732b059ffa8d9d8858643701e32c90c3d3ab8b6697fa74ca1c8c09fb5R119)

File: receiver/prometheusreceiver/metrics_receiver.go [hunk 7]
```diff
@@ -257,6 +312,7 @@ func gcInterval(cfg *config.Config) time.Duration {
 func (r *pReceiver) Shutdown(context.Context) error {
 	r.cancelFunc()
 	r.scrapeManager.Stop()
+	r.reloadReady.Close()
```
Comment (dashpole) [inline receiver/prometheusreceiver/metrics_receiver.go:315]: I don't think this is necessary.  You don't need to close channels on shutdown for them to be GC'd (this would be neccessary if closing the channel causes things waiting on the channel to shut down.

File: receiver/prometheusreceiver/metrics_receiver.go [hunk 8]
```diff
@@ -92,36 +98,57 @@ func (r *pReceiver) Start(_ context.Context, host component.Host) error {
...
+
+func (r *pReceiver) startTargetAllocator(allocConf *targetAllocator, baseCfg *config.Config) error {
+	r.settings.Logger.Info("Starting target allocator discovery")
+	// immediately sync jobs and not wait for the first tick
+	savedHash, err := r.syncTargetAllocator(uint64(0), allocConf, baseCfg)
+	if err != nil {
+		return err
+	}
+	go func() {
+		r.targetAllocatorIntervalTicker = time.NewTicker(allocConf.Interval)
```
Comment (dashpole) [inline receiver/prometheusreceiver/metrics_receiver.go:122]: Can we not store targetAllocatorIntervalTicker on the pReceiver?  It only appears to be accessed in Shutdown().  Instead, we could just stop the ticker in the `case <-r.targetAllocatorStop` case.

(I believe it is possible to race on this if Start() and Shutdown() are called concurrently)

File: receiver/prometheusreceiver/metrics_receiver.go [hunk 9]
```diff
@@ -259,6 +309,7 @@ func (r *pReceiver) Shutdown(context.Context) error {
 	r.scrapeManager.Stop()
 	if r.targetAllocatorIntervalTicker != nil {
 		r.targetAllocatorIntervalTicker.Stop()
+		r.targetAllocatorStop <- true
```
Comment (dashpole) [inline receiver/prometheusreceiver/metrics_receiver.go:312]: it seems like it would be safe to close the channel here, which is more idiomatic.  I don't believe shutdown is invoked more than once.

File: receiver/prometheusreceiver/metrics_receiver.go [hunk 10]
```diff
@@ -43,31 +48,31 @@ const (
...
 func newPrometheusReceiver(set component.ReceiverCreateSettings, cfg *Config, next consumer.Metrics) *pReceiver {
 	pr := &pReceiver{
-		cfg:      cfg,
-		consumer: next,
-		settings: set,
+		cfg:                 cfg,
+		consumer:            next,
+		settings:            set,
+		configLoaded:        make(chan struct{}),
+		targetAllocatorStop: make(chan bool, 1),
```
Comment (dashpole) [inline receiver/prometheusreceiver/metrics_receiver.go:70]: This can just be a chan struct without a capacity

**Review by dashpole — APPROVED** [review]
LGTM otherwise

**Review by dashpole — APPROVED** [review]

**Review by codeboten — APPROVED** [review]
