### PR TITLE
Fix config evaluation of regexps in receiver creator

### LINKED ISSUE #39163: [collector] [receiver/k8s_observer] filelog/regex_parser configuration do not work as expected
### Component(s)

_No response_

## Description

We are testing the `k8s_observer` as a replacement for the `filelog` receiver. We have found that a configuration that works with the `filelog` receiver has a different behavior with the `k8s_observer` the regexp used does not match.

## Steps to Reproduce

I have prepared two configurations that show both case, these configuration deploy an Apache pod and the OpenTelemetry collector configured to show the log document in the logs with the debug exported. You can see that the parse of the same log passes in the `filelog` receiver and does not match in the `k8s_observer` receiver.

Filelog receiver configuration in the OpenTelemetry Collector

```yaml
    filelog:
      include:
        - /var/log/pods/*_apache*/*/*.log
      start_at: end
      operators:
        - type: container
          id: container-parser
        - id: apache-logs
          type: regex_parser
          regex: ^(?P<source_ip>\d+\.\d+.\d+\.\d+)\s+-\s+-\s+\[(?P<timestamp_log>\d+/\w+/\d+:\d+:\d+:\d+\s+\+\d+)\]\s"(?P<http_method>\w+)\s+(?P<http_path>.*)\s+(?P<http_version>.*)"\s+(?P<http_code>\d+)\s+(?P<http_size>\d+)$
```

* [Filelog environment test case](https://github.com/kuisathaverat/otel-playground/blob/main/test-filelog/README.md)

k8s_observer Configuration in the pod annotations

```yaml
    io.opentelemetry.discovery.logs.apache/enabled: "true"
    io.opentelemetry.discovery.logs.apache/config: |
      include:
        - /var/log/pods/*_apache*/*/*.log
      start_at: end
      operators:
        - type: container
          id: container-parser
        - id: apache-logs
          type: regex_parser
          regex: ^(?P<source_ip>\d+\.\d+.\d+\.\d+)\s+-\s+-\s+\[(?P<timestamp_log>\d+/\w+/\d+:\d+:\d+:\d+\s+\+\d+)\]\s"(?P<http_method>\w+)\s+(?P<http_path>.*)\s+(?P<http_version>.*)"\s+(?P<http_code>\d+)\s+(?P<http_size>\d+)$
```

* [k8s_observer environment test case](https://github.com/kuisathaverat/otel-playground/blob/main/test-k8s_observer/README.md)

## Expected Result

The same parse results in both cases; all the attributes are parsed from the log and added to the document.

```log
2025-04-04T15:00:54.799Z        info    ResourceLog #0
Resource SchemaURL:
Resource attributes:
     -> k8s.container.name: Str(apache)
     -> k8s.namespace.name: Str(oteldemo-oanrf-default)
     -> k8s.pod.name: Str(apache-7b8dc8dc56-wfwtf)
     -> k8s.container.restart_count: Str(0)
     -> k8s.pod.uid: Str(30639f85-44b3-4438-80ae-99a1297e742b)
ScopeLogs #0
ScopeLogs SchemaURL:
InstrumentationScope
LogRecord #0
ObservedTimestamp: 2025-04-04 15:00:54.52243288 +0000 UTC
Timestamp: 2025-04-04 15:00:54.514243451 +0000 UTC
SeverityText:
SeverityNumber: Unspecified(0)
Body: Str(10.1.46.1 - - [04/Apr/2025:15:00:54 +0000] "GET / HTTP/1.1" 200 45)
Attributes:
     -> log.file.path: Str(/var/log/pods/oteldemo-oanrf-default_apache-7b8dc8dc56-wfwtf_30639f85-44b3-4438-80ae-99a1297e742b/apache/0.log)
     -> log.iostream: Str(stdout)
     -> logtag: Str(F)
     -> http_code: Str(200)
     -> timestamp_log: Str(04/Apr/2025:15:00:54 +0000)
     -> http_method: Str(GET)
     -> http_path: Str(/)
     -> http_version: Str(HTTP/1.1)
     -> http_size: Str(45)
     -> source_ip: Str(10.1.46.1)
```

## Actual Result

The regexp does not match in the `k8s_observer` use case.

```log
2025-04-04T15:17:23.861Z        error   helper/transformer.go:122       Failed to process entry {"name": "filelog/308d875f-50e6-49ae-8a54-731e425f2e0e_apache/receiver_creator/logs{endpoint=\"10.1.46.13\"}/k8s_observer/308d875f-50e6-49ae-8a54-731e425f2e0e/apache", "operator_id": "apache-logs", "operator_type": "regex_parser", "error": "regex pattern does not match", "action": "send", "entry.timestamp": "2025-04-04T15:17:23.856Z", "log.file.path": "/var/log/pods/oteldemo-oanrf-default_apache-6d8c49ff46-9mftt_308d875f-50e6-49ae-8a54-731e425f2e0e/apache/0.log", "log.iostream": "stdout", "logtag": "F"}
```

### Collector version

0.123.0

## Environment
OS: k8s container docker.io/otel/opentelemetry-collector-contrib:latest

### OpenTelemetry Collector configuration

```yaml
exporters:
    # Debug exporter to see the logs in the console
    debug:
      verbosity: detailed
  extensions:
    # Kubernetes observer to discover the pods, nodes, services and ingresses
    k8s_observer:
      observe_pods: true
      observe_nodes: true
      observe_services: true
      observe_ingresses: true
    # Health check extension to check the health of the collector
    health_check:
      endpoint: ${env:MY_POD_IP}:13133
  receivers:
    # Receiver to watch the pods and discover the logs
    receiver_creator/logs:
      watch_observers: [k8s_observer]
      discovery:
        enabled: true
      receivers:
    # Disable the default receivers
    prometheus: null
    zipkin: null
  service:
    # Disable the default telemetry
    telemetry: {}
    # Enable the health check extension
    # and the k8s observer extension
    extensions: [k8s_observer, health_check]
    # Define the pipelines for the logs
    pipelines:
      # Disable the default pipelines
      metrics: null
      traces: null
      # Define the logs pipeline
      logs:
        receivers:
          - receiver_creator/logs
        processors:
          - batch
        exporters:
          - debug
```

### Log output

```shell
2025-04-04T15:17:23.861Z        error   helper/transformer.go:122       Failed to process entry {"name": "filelog/308d875f-50e6-49ae-8a54-731e425f2e0e_apache/receiver_creator/logs{endpoint=\"10.1.46.13\"}/k8s_observer/308d875f-50e6-49ae-8a54-731e425f2e0e/apache", "operator_id": "apache-logs", "operator_type": "regex_parser", "error": "regex pattern does not match", "action": "send", "entry.timestamp": "2025-04-04T15:17:23.856Z", "log.file.path": "/var/log/pods/oteldemo-oanrf-default_apache-6d8c49ff46-9mftt_308d875f-50e6-49ae-8a54-731e425f2e0e/apache/0.log", "log.iostream": "stdout", "logtag": "F"}
github.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza/operator/helper.(*TransformerOperator).HandleEntryError
        github.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza@v0.123.0/operator/helper/transformer.go:122
github.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza/operator/helper.(*ParserOperator).ParseWith
        github.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza@v0.123.0/operator/helper/parser.go:142
github.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza/operator/helper.(*ParserOperator).ProcessWithCallback
        github.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza@v0.123.0/operator/helper/parser.go:111
github.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza/operator/helper.(*ParserOperator).ProcessWith
        github.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza@v0.123.0/operator/helper/parser.go:98
github.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza/operator/parser/regex.(*Parser).Process
        github.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza@v0.123.0/operator/parser/regex/parser.go:35
github.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza/operator/helper.(*WriterOperator).Write
        github.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza@v0.123.0/operator/helper/writer.go:73
github.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza/operator/parser/container.(*Parser).consumeEntries
        github.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza@v0.123.0/operator/parser/container/parser.go:298
github.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza/operator/helper.(*BatchingLogEmitter).flusher
        github.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza@v0.123.0/operator/helper/emitter.go:171
2025-04-04T15:17:23.862Z        error   container/parser.go:300 failed to write entry   {"name": "filelog/308d875f-50e6-49ae-8a54-731e425f2e0e_apache/receiver_creator/logs{endpoint=\"10.1.46.13\"}/k8s_observer/308d875f-50e6-49ae-8a54-731e425f2e0e/apache", "operator_id": "container-parser", "operator_type": "container", "error": "regex pattern does not match"}
github.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza/operator/parser/container.(*Parser).consumeEntries
        github.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza@v0.123.0/operator/parser/container/parser.go:300
github.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza/operator/helper.(*BatchingLogEmitter).flusher
        github.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza@v0.123.0/operator/helper/emitter.go:171
2025-04-04T15:17:23.980Z        info    Logs    {"resource logs": 2, "log records": 2}
2025-04-04T15:17:23.980Z        info    ResourceLog #0
Resource SchemaURL:
Resource attributes:
     -> k8s.container.restart_count: Str(0)
     -> k8s.pod.uid: Str(308d875f-50e6-49ae-8a54-731e425f2e0e)
     -> k8s.container.name: Str(apache)
     -> k8s.namespace.name: Str(oteldemo-oanrf-default)
     -> k8s.pod.name: Str(apache-6d8c49ff46-9mftt)
ScopeLogs #0
ScopeLogs SchemaURL:
InstrumentationScope
LogRecord #0
ObservedTimestamp: 2025-04-04 15:17:23.863873858 +0000 UTC
Timestamp: 2025-04-04 15:17:23.856663589 +0000 UTC
SeverityText:
SeverityNumber: Unspecified(0)
Body: Str(10.1.46.1 - - [04/Apr/2025:15:17:23 +0000] "GET / HTTP/1.1" 200 45)
Attributes:
     -> log.iostream: Str(stdout)
     -> logtag: Str(F)
     -> log.file.path: Str(/var/log/pods/oteldemo-oanrf-default_apache-6d8c49ff46-9mftt_308d875f-50e6-49ae-8a54-731e425f2e0e/apache/0.log)
Trace ID:
Span ID:
Flags: 0
ResourceLog #1
Resource SchemaURL:
Resource attributes:
     -> k8s.container.name: Str(apache)
     -> k8s.namespace.name: Str(oteldemo-oanrf-default)
     -> k8s.pod.name: Str(apache-6d8c49ff46-9mftt)
     -> k8s.container.restart_count: Str(0)
     -> k8s.pod.uid: Str(308d875f-50e6-49ae-8a54-731e425f2e0e)
     -> container.id: Str(ed1cd5fb4ae33458cfa34d984d84000d65661442c5144aeb07c4e0372ce27848)
     -> container.image.name: Str(docker.io/bitnami/apache:2.4.63-debian-12-r7)
ScopeLogs #0
ScopeLogs SchemaURL:
InstrumentationScope
LogRecord #0
ObservedTimestamp: 2025-04-04 15:17:23.861723778 +0000 UTC
Timestamp: 2025-04-04 15:17:23.856663589 +0000 UTC
SeverityText:
SeverityNumber: Unspecified(0)
Body: Str(10.1.46.1 - - [04/Apr/2025:15:17:23 +0000] "GET / HTTP/1.1" 200 45)
Attributes:
     -> log.file.path: Str(/var/log/pods/oteldemo-oanrf-default_apache-6d8c49ff46-9mftt_308d875f-50e6-49ae-8a54-731e425f2e0e/apache/0.log)
     -> log.iostream: Str(stdout)
     -> logtag: Str(F)
Trace ID:
Span ID:
Flags: 0
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by ChrsMark**
#### Description

This PR fixes how escaped backticks are handled as part of the receiver creator's template config evaluation. 

The [docs](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/receiver/receivercreator/README.md#configuration) mention ```Dynamic values are surrounded by backticks (`). If a literal backtick is needed use \` to escape it. Dynamic values can be used with static values in which case they are concatenated```.

An example can be found in the testcase: https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/2a7d1228c0853fe0583b244b517ab3b9101e8d22/receiver/receivercreator/config_expansion_test.go#L48

Hence we need to explicitly check for the backticks at https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/e818a4cd0817668ad9fe96e287066f04053419ab/receiver/receivercreator/config_expansion.go#L41-L46  and properly handle them.

This bug had a result of making regular expressions defined in template configurations invalid as the original issue surfaced.

#### Link to tracking issue
Fixes https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/39163

#### Testing

Added unit tests.

This PR can be tested manually using the reproduction steps from https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/39163.

#### Documentation

~

### CODE REVIEW

File: receiver/receivercreator/config_expansion.go [hunk 1]
```diff
@@ -34,16 +34,22 @@ func evalBackticksInConfigValue(configValue string, env observer.EndpointEnv) (a
...
 	for i := 0; i < len(configValue); i++ {
 		switch configValue[i] {
 		case '\\':
 			if i+1 == len(configValue) {
 				return nil, errors.New(`encountered escape (\) without value at end of expression`)
 			}
-			output.WriteByte(configValue[i+1])
-			i++
+			if string(configValue[i+1]) != "`" {
+				if exprStartIndex == -1 {
```
Comment (dmitryax) [inline receiver/receivercreator/config_expansion.go:46]: What if user needs to have an escaped \` outside of the expression? That should be supported as well, right?

File: receiver/receivercreator/config_expansion.go [hunk 2]
```diff
@@ -34,16 +34,22 @@ func evalBackticksInConfigValue(configValue string, env observer.EndpointEnv) (a
...
 	// inside or outside of expressions.
 	for i := 0; i < len(configValue); i++ {
 		switch configValue[i] {
 		case '\\':
 			if i+1 == len(configValue) {
 				return nil, errors.New(`encountered escape (\) without value at end of expression`)
 			}
-			output.WriteByte(configValue[i+1])
-			i++
+			if string(configValue[i+1]) != "`" {
```
Comment (dmitryax) [inline receiver/receivercreator/config_expansion.go:45]: Not sure why we need to cast to string here
```suggestion
			if configValue[i+1] != '`' {
```

File: receiver/receivercreator/config_expansion.go (hunk 1 above)
Comment (ChrsMark) [reply receiver/receivercreator/config_expansion.go:46]: Yeap, it is supported. I also added a more explicit test case for this.

With this check what we don't support is preserving the backslash literal inside an expression. This seems to be something we don't need?

Comment (dmitryax) [reply receiver/receivercreator/config_expansion.go:46]: I don't get why should we treat it differently between outside and inside the expression? It seems like we should keep it the same

Comment (ChrsMark) [reply receiver/receivercreator/config_expansion.go:46]: I could not think of why we would need an escape literal inside an expression, but trying that I found out that it's not  supported/allowed by https://github.com/expr-lang/expr hence we cannot evaluate such expressions at https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/v0.124.1/receiver/receivercreator/config_expansion.go#L59.

See https://go.dev/play/p/1xEg9ZNwlT0.

In any case, with the current implementation we preserve `\` inside expressions too (I was wrong before). An expression is evaluated all together at https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/v0.124.1/receiver/receivercreator/config_expansion.go#L51-L67. However, as I mentioned before such an expression will fail to be evaluated by `expr-lang`.

**Comment by ChrsMark** [comment]
Hey @dmitryax, any chance we could move forward with this?

**Review by dmitryax — APPROVED** [review]

File: receiver/receivercreator/config_expansion.go (hunk 1 above)
Comment (dmitryax) [reply receiver/receivercreator/config_expansion.go:46]: Ok sounds good to me
