### PR TITLE
[exporter/coralogix] Fix rate limit internal counter

### LINKED ISSUE #40811: [exporter/coralogix] Fix counter reset for rate limit feature
### Component(s)

exporter/coralogix

## Description
The rate limit feature has a counter that ensures the rate limiter feature is not enabled until reaching the threshold. This counter should be reset if at least one request is performed successfully.

Currently the counter is being reset  before the success.

### Collector version

0.128.0

### Environment information

_No response_

### OpenTelemetry Collector configuration

```yaml

```

### Log output

```shell

```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by iblancasa**
#### Description
- Fix internal counter for the rate limiter feature
- Added some E2E tests that can be run with a proper API key
- Added new tests to handle this situation

#### Link to tracking issue
Fixes #40811

##### Manual test

This is the [output log](https://github.com/user-attachments/files/20802604/output.txt). You will be able to see how:
1. The exporter tries to send data
2. The rate limit mechanism is enabled
3. Every try to send data will print an error explaining when the rate limiting started
4. After the duration, the exporter tries to send data again
5. The rate limit feature is enabled again

Configuration used:
```
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "localhost:4317"
exporters:
  coralogix:
    domain: "eu2.coralogix.com"
    private_key: "${env:CORALOGIX_PRIVATE_KEY_LOW_QUOTA}"
    application_name: "MyBusinessEnvironment"
    subsystem_name: "MyBusinessSystem"

    rate_limiter:
      enabled: true
      threshold: 5
      duration: 10s

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [coralogix]
```

##### E2E test
Log output [e2e_output.log](https://github.com/user-attachments/files/20802689/e2e_output.log)

### CODE REVIEW

**Comment by iblancasa** [comment]
@povilasv @douglascamata

**Review by douglascamata — APPROVED** [review]

**Review by povilasv — APPROVED** [review]

File: exporter/coralogixexporter/e2e_test.go [hunk 1]
```diff
@@ -0,0 +1,246 @@
+// Copyright The OpenTelemetry Authors
+// SPDX-License-Identifier: Apache-2.0
+
+package coralogixexporter
```
Comment (braydonk) [inline exporter/coralogixexporter/e2e_test.go:6]: While the environment variable checks will already guard these tests from being run, it is still general practice throughout the codebase to guard E2E test files with the `e2e` build tag like so: https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/f3acb5e455ca9be51ef47228e2da44446b92c569/processor/k8sattributesprocessor/e2e_test.go#L4

File: exporter/coralogixexporter/logs_client_test.go [hunk 2]
```diff
@@ -463,7 +461,22 @@ func TestLogsExporter_PushLogs_Performance(t *testing.T) {
...
+			testLogRecord := testSl.LogRecords().AppendEmpty()
+			testLogRecord.Body().SetStr("test log message")
+			testLogRecord.SetTimestamp(pcommon.NewTimestampFromTime(time.Now()))
+			testLogRecord.SetSeverityText("INFO")
+
+			errPush := exp.pushLogs(context.Background(), testLogs)
+			return errPush == nil
+		}, 3*time.Second, 100*time.Millisecond, "Rate limit should reset within 3 seconds")
+
+		mockSrv.recvCount = 0
```
Comment (braydonk) [inline exporter/coralogixexporter/logs_client_test.go:482]: Would it help to check the value of `mockSrv.recvCount` before resetting it again?

File: exporter/coralogixexporter/e2e_test.go (hunk 1 above)
Comment (iblancasa) [reply exporter/coralogixexporter/e2e_test.go:6]: Oh good. Didn't know about this. Thanks!

**Comment by iblancasa** [comment]
@open-telemetry/collector-contrib-approvers can we merge this? The code owners already approved the changes.
Thanks

**Review by braydonk — APPROVED** [review]

**Review by ChrsMark — APPROVED** [review]
