### PR TITLE
fix(receiver/prometheusremotewrite): count target_info samples in PRW response stats

### LINKED ISSUE #45150: [receiver/prometheusremotewrite] - returning failedSampleCount to Prometheus when sending unmatched target_info
### Component(s)

_No response_

## Description

receiver/prometheusremotewrite appears to be returning failed sample messages back to prometheus when prometheus remote writes target_info not otherwise in the payload.  Not 100% sure that is accurate - but something close to this is happening

## Steps to Reproduce

running:
prometheus v3.8.1
opentelemetry-collector-contrib 0.142.0

prometheus config:
```
remote_write:
  - url: "http://otel-collector:9090/api/v1/write"
    protobuf_message: io.prometheus.write.v2.Request
    write_relabel_configs:
      - source_labels: [__name__, _generated]
        regex: "target_info;.*|.*;true"
        action: keep

```
The important bit is I am sending target_info and only a subset of my other metrics (matching label "_generated" to "true".

otel collector config:
```
  prometheusremotewrite:
    endpoint: 0.0.0.0:9090
```

## Expected Result
no errors
my '_generated' data is coming through fine and getting resource info populated.

## Actual Result

Every minute I am getting an error from prometheus that looks like this:
`time=2025-12-24T19:01:25.692Z level=ERROR source=queue_manager.go:1707 msg="non-recoverable error" component=remote remote_name=33a275 url=http://otel-collector:9090/api/v1/write failedSampleCount=4 failedHistogramCount=0 failedExemplarCount=0 err="sent v2 request with 4 samples, 0 histograms and 0 exemplars; got 2xx, but PRW 2.0 response header statistics indicate 0 samples, 0 histograms and 0 exemplars were accepted; assumining failure e.g. the target only supports PRW 1.0 prometheus.WriteRequest, but does not check the Content-Type header correctly"
`

Note - when I change my config to not include target_info the errors disappear (though - as expected - I no longer get resource attributes)

### Collector version

0.142.0

## Environment
0.142.0 on x86 via docker

### OpenTelemetry Collector configuration

```yaml
prometheusremotewrite:
    endpoint: 0.0.0.0:9090
```

### Log output

```shell

```

### Additional context

_No response_

### Tip

<sub>[React](https://github.blog/news-insights/product-news/add-reactions-to-pull-requests-issues-and-comments/) with 👍 to help prioritize this issue. Please use comments to provide useful context, avoiding `+1` or `me too`, to help us triage it. Learn more [here](https://opentelemetry.io/community/end-user/issue-participation/).</sub>

### PR DESCRIPTION
**Pull request by Naman-B-Parlecha**
This is due to target_info not being counted in samples leading to miss match count as mentioned in the [commet](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/45150#issuecomment-3786969251)
 

#### Link to tracking issue
Fixes #45150 

#### Testing
Added Sub-Test in TestTranslateV2 with 
- `service with only target_info metric` to verify stats are counted when target_info
- Verified exising test `service with target_info metric` passes

### CODE REVIEW

File: receiver/prometheusremotewritereceiver/receiver.go [hunk 1]
```diff
@@ -342,6 +342,9 @@ func (prw *prometheusRemoteWriteReceiver) translateV2(_ context.Context, req *wr
 			snapshot := pmetric.NewResourceMetrics()
 			attrs.CopyTo(snapshot.Resource().Attributes())
 			prw.rmCache.Add(hashed, snapshot)
+			// target_info is not stored as a metric but PRW requires the response
+			// to report all received samples, including target_info, to avoid a stats mismat
```
Comment (dashpole) [inline receiver/prometheusremotewritereceiver/receiver.go]:
```suggestion
			// to report all received samples, including target_info, to avoid a stats mismatch
```

**Review by dashpole — APPROVED** [review]

**Review by krajorama — APPROVED** [review]
LGTM

**Review by ArthurSens — COMMENTED** [review]
Could you add a BUGFIX changelog entry? After that, it should be ready to merge :)

**Comment by Naman-B-Parlecha** [comment]
@ArthurSens Done :)
Thanks!!

File: .chloggen/47108.yaml [hunk 2]
```diff
@@ -1,24 +1,21 @@
 # Use this changelog template to create an entry for release notes.
 
 # One of 'breaking', 'deprecation', 'new_component', 'enhancement', 'bug_fix'
-change_type: deprecation
+change_type: bug_fix
 
 # The name of the component, or a single word describing the area of concern, (e.g. receiver/filelog)
-component: receiver/awsfirehose
+component: receiver/prometheusremotewrite
```
Comment (songy23) [inline .chloggen/47108.yaml]:
```suggestion
component: receiver/prometheus_remote_write
```
