### PR TITLE
Fix k8s resolver parsing so loadbalancing exporter works with service FQDNs

### LINKED ISSUE #44472: Backend creation not succeeding with k8s resolver
### Component(s)

exporter/loadbalancing

## Description

Using the loadbalancing exporter configured with the k8s resolver to the FQDN of a OpenTelemetry Collector statefulset headless service, the exporter is continually logging the error message:

```txt
couldn't find the exporter for the endpoint ""
```

This seems to be linked to https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/43960 and https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/43950. 

If I configure the collector using the dns resolver and the same service FQDN the collector works as expected

## Steps to Reproduce

Configure the collector using the loadbalancing exporter and the k8s resolver as below.

## Expected Result

The opentelemetry collector exports to the collector with the given service FQDN.

## Actual Result

Errors are continually logged as below.

### Collector version

v0.140.0

## Environment
Running on k8s with image: https://hub.docker.com/layers/otel/opentelemetry-collector-k8s/0.140.0

### OpenTelemetry Collector configuration

```yaml
exporters:
  loadbalancing:
    protocol:
      otlp:
        timeout: 10s
        tls:
          ca_file: /etc/otel/tls/ca.crt
          insecure: false
    resolver:
      k8s:
        ports:
        - 4317
        return_hostnames: true
        service: otelsampler.test.svc.cluster.local
        timeout: 10s
    routing_key: traceID
extensions:
  basicauth/server:
    htpasswd:
      inline: |
        ${env:OTEL_USER}:${env:OTEL_PASS}
  health_check:
    endpoint: ${env:MY_POD_IP}:13133
processors:
  memory_limiter:
    check_interval: 1s
    limit_percentage: 95
    spike_limit_percentage: 5
receivers:
  otlp:
    protocols:
      grpc:
        auth: null
        endpoint: ${env:MY_POD_IP}:4317
        include_metadata: true
        tls:
          cert_file: /etc/otel/tls/tls.crt
          key_file: /etc/otel/tls/tls.key
  prometheus:
    config:
      scrape_configs:
      - job_name: opentelemetry-collector
        scrape_interval: 10s
        static_configs:
        - targets:
          - ${env:MY_POD_IP}:8888
service:
  extensions:
  - basicauth/server
  - health_check
  pipelines:
    traces:
      exporters:
      - loadbalancing
      processors:
      - memory_limiter
      receivers:
      - otlp
  telemetry:
    logs:
      encoding: json
      level: info
    metrics:
      readers:
      - pull:
          exporter:
            prometheus:
              host: ${env:MY_POD_IP}
              port: 8888
```

### Log output

```shell
{"level":"error","ts":"2025-11-24T09:05:15.271Z","caller":"internal/base_exporter.go:114","msg":"Exporting failed. Rejecting data.","resource":{"service.instance.id":"941469d8-304f-4f77-a086-584f9cb6965a","service.name":"otelcol-k8s","service.version":"0.140.1"},"otelcol.component.id":"loadbalancing","otelcol.componen
t.kind":"exporter","otelcol.signal":"traces","error":"couldn't find the exporter for the endpoint \"\"","rejected_items":4,"stacktrace":"go.opentelemetry.io/collector/exporter/exporterhelper/internal.(*BaseExporter).Send\n\tgo.opentelemetry.io/collector/exporter/exporterhelper@v0.140.0/internal/base_exporter.go:114\ng
o.opentelemetry.io/collector/exporter/exporterhelper/internal.NewTracesRequest.newConsumeTraces.func1\n\tgo.opentelemetry.io/collector/exporter/exporterhelper@v0.140.0/internal/new_request.go:123\ngo.opentelemetry.io/collector/consumer.ConsumeTracesFunc.ConsumeTraces\n\tgo.opentelemetry.io/collector/consumer@v1.46.0/t
races.go:27\ngo.opentelemetry.io/collector/service/internal/refconsumer.refTraces.ConsumeTraces\n\tgo.opentelemetry.io/collector/service@v0.140.0/internal/refconsumer/traces.go:29\ngo.opentelemetry.io/collector/processor/processorhelper.NewTraces.func1\n\tgo.opentelemetry.io/collector/processor/processorhelper@v0.140.
0/traces.go:71\ngo.opentelemetry.io/collector/consumer.ConsumeTracesFunc.ConsumeTraces\n\tgo.opentelemetry.io/collector/consumer@v1.46.0/traces.go:27\ngo.opentelemetry.io/collector/service/internal/refconsumer.refTraces.ConsumeTraces\n\tgo.opentelemetry.io/collector/service@v0.140.0/internal/refconsumer/traces.go:29\n
go.opentelemetry.io/collector/processor/processorhelper.NewTraces.func1\n\tgo.opentelemetry.io/collector/processor/processorhelper@v0.140.0/traces.go:71\ngo.opentelemetry.io/collector/consumer.ConsumeTracesFunc.ConsumeTraces\n\tgo.opentelemetry.io/collector/consumer@v1.46.0/traces.go:27\ngo.opentelemetry.io/collector/
service/internal/refconsumer.refTraces.ConsumeTraces\n\tgo.opentelemetry.io/collector/service@v0.140.0/internal/refconsumer/traces.go:29\ngo.opentelemetry.io/collector/consumer.ConsumeTracesFunc.ConsumeTraces\n\tgo.opentelemetry.io/collector/consumer@v1.46.0/traces.go:27\ngo.opentelemetry.io/collector/internal/fanoutc
onsumer.(*tracesConsumer).ConsumeTraces\n\tgo.opentelemetry.io/collector/internal/fanoutconsumer@v0.140.0/traces.go:60\ngo.opentelemetry.io/collector/receiver/otlpreceiver/internal/trace.(*Receiver).Export\n\tgo.opentelemetry.io/collector/receiver/otlpreceiver@v0.140.0/internal/trace/otlp.go:42\ngo.opentelemetry.io/co
llector/pdata/ptrace/ptraceotlp.rawTracesServer.Export\n\tgo.opentelemetry.io/collector/pdata@v1.46.0/ptrace/ptraceotlp/grpc.go:87\ngo.opentelemetry.io/collector/pdata/internal/otelgrpc.traceServiceExportHandler.func1\n\tgo.opentelemetry.io/collector/pdata@v1.46.0/internal/otelgrpc/trace_service.go:72\ngo.opentelemetr
y.io/collector/config/configgrpc.(*ServerConfig).getGrpcServerOptions.enhanceWithClientInformation.func9\n\tgo.opentelemetry.io/collector/config/configgrpc@v0.140.0/configgrpc.go:576\ngo.opentelemetry.io/collector/pdata/internal/otelgrpc.traceServiceExportHandler\n\tgo.opentelemetry.io/collector/pdata@v1.46.0/internal
/otelgrpc/trace_service.go:74\ngoogle.golang.org/grpc.(*Server).processUnaryRPC\n\tgoogle.golang.org/grpc@v1.76.0/server.go:1431\ngoogle.golang.org/grpc.(*Server).handleStream\n\tgoogle.golang.org/grpc@v1.76.0/server.go:1842\ngoogle.golang.org/grpc.(*Server).serveStreams.func2.1\n\tgoogle.golang.org/grpc@v1.76.0/serve
r.go:1061"}
```

### Additional context

_No response_

### Tip

<sub>[React](https://github.blog/news-insights/product-news/add-reactions-to-pull-requests-issues-and-comments/) with 👍 to help prioritize this issue. Please use comments to provide useful context, avoiding `+1` or `me too`, to help us triage it. Learn more [here](https://opentelemetry.io/community/end-user/issue-participation/).</sub>

### PR DESCRIPTION
**Pull request by iblancasa**
#### Link to tracking issue
Fixes #44472

#### Testing
 Added some tests and manual testing.

### CODE REVIEW

**Review by paulojmdias — APPROVED** [review]

File: exporter/loadbalancingexporter/resolver_k8s.go [hunk 1]
```diff
@@ -87,10 +87,10 @@ func newK8sResolver(clt kubernetes.Interface,
 		timeout = defaultListWatchTimeout
 	}
 
-	nAddr := strings.SplitN(service, ".", 2)
-	name, namespace := nAddr[0], "default"
-	if len(nAddr) > 1 {
-		namespace = nAddr[1]
+	parts := strings.Split(service, ".")
```
Comment (odubajDT) [inline exporter/loadbalancingexporter/resolver_k8s.go:91]: Thanks for the fix, according to the changes you made, the loadbalancing exporter should work correctly (even without your fix), when using the standard `<svcName>.<namespace>` domain name format of the headless service. I am still experiencing the same issue even when using the `collector-backend.default` in the [config mentioned in the issue](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/44472#issuecomment-3574901170). Am I missing something here? Thanks!

Comment (iblancasa) [reply exporter/loadbalancingexporter/resolver_k8s.go:91]: Let me retest with that and see if I missed something during the fix.

Comment (iblancasa) [reply exporter/loadbalancingexporter/resolver_k8s.go:91]: I just reran with the provided config against a local kind cluster using a collector build that includes the FQDN parsing fix. With `telemetrygen` driving 50 traces through a port-forward, both backend pods received traffic and `kubectl logs deploy/lb-collector` never produced the `couldn’t find the exporter for the endpoint ""` error. So, I think, `<svc>.<namespace>` now works as expected.

The front collector’s service account must be allowed to `list/watch` `endpointslices` in the namespace. Without the RBAC role binding, the informer never populates and the ring stays empty, which yields the same error message even with a correct service string.

**Review by odubajDT — APPROVED** [review]

**Comment by atoulme** [comment]
@rlankfo please review as codeowner

**Review by rlankfo — APPROVED** [review]
looks good to me!

File: exporter/loadbalancingexporter/resolver_k8s_test.go [hunk 2]
```diff
@@ -257,6 +257,54 @@ func TestK8sResolve(t *testing.T) {
 	}
 }
 
+func TestK8sResolveWithServiceFQDN(t *testing.T) {
+	serviceName := "lb"
+	namespace := "custom"
+	serviceFQDN := fmt.Sprintf("%s.%s.svc.cluster.local", serviceName, namespace)
```
Comment (rlankfo) [inline exporter/loadbalancingexporter/resolver_k8s_test.go:263]: it's not a major concern to me but unresolvable domains will still work here, something like this for example: `name.namespace.foo.bar.baz`

**Comment by iblancasa** [comment]
Is there anything else pending here?

**Comment by iblancasa** [comment]
@open-telemetry/collector-contrib-approvers anything else here?

**Review by VihasMakwana — APPROVED** [review]
