### PR TITLE
[extension/jaegerremotesampling] fix: wait for autoUpdateStrategies in Close function

### LINKED ISSUE #37275: [flaky test][extension/jaegerremotesampling] TestAutoUpdateStrategyWithFile is flaky on Windows
### Component(s)

extension/jaegerremotesampling

### Describe the issue you're reporting

Multiple hits in different runs:

- https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/12798321201/job/35682107423#step:8:198
- https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/12798321201/job/35682107635#step:8:198
- https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/12811229135/job/35720110479#step:8:203
- https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/12813334359/job/35727171630#step:8:203

```terminal
=== FAIL: internal/source/filesource TestAutoUpdateStrategyWithFile (0.03s)
    filesource_test.go:382: 
        	Error Trace:	D:/a/opentelemetry-collector-contrib/opentelemetry-collector-contrib/extension/jaegerremotesampling/internal/source/filesource/filesource_test.go:382
        	            				D:/a/opentelemetry-collector-contrib/opentelemetry-collector-contrib/extension/jaegerremotesampling/internal/source/filesource/filesource_test.go:422
        	Error:      	Received unexpected error:
        	            	remove C:\Users\RUNNER~1\AppData\Local\Temp\for_go_test_1706118286.json: The process cannot access the file because it is being used by another process.
        	Test:       	TestAutoUpdateStrategyWithFile

=== FAIL: internal/source/filesource TestAutoUpdateStrategyWithFile (re-run 1) (0.03s)
    filesource_test.go:382: 
        	Error Trace:	D:/a/opentelemetry-collector-contrib/opentelemetry-collector-contrib/extension/jaegerremotesampling/internal/source/filesource/filesource_test.go:382
        	            				D:/a/opentelemetry-collector-contrib/opentelemetry-collector-contrib/extension/jaegerremotesampling/internal/source/filesource/filesource_test.go:422
        	Error:      	Received unexpected error:
        	            	remove C:\Users\RUNNER~1\AppData\Local\Temp\for_go_test_3754742530.json: The process cannot access the file because it is being used by another process.
        	Test:       	TestAutoUpdateStrategyWithFile

```

### PR DESCRIPTION
**Pull request by ary82**
#### Description
Add a waitGroup to strategyProvider struct that waits for autoUpdateStrategies in the Close function

#### Link to tracking issue
Fixes #37275

### CODE REVIEW

File: extension/jaegerremotesampling/internal/source/filesource/filesource.go [hunk 1]
```diff
@@ -156,6 +160,9 @@ func (h *samplingProvider) samplingStrategyLoader(strategiesFile string) strateg
 }
 
 func (h *samplingProvider) autoUpdateStrategies(ctx context.Context, interval time.Duration, loader strategyLoader) {
+	h.wg.Add(1)
```
Comment (yurishkuro) [inline extension/jaegerremotesampling/internal/source/filesource/filesource.go:163]: Add() should be called outside of the goroutine itself, otherwise you can get to a race condition where Close and Wait succeed before goroutine starts.

**Review by yurishkuro — APPROVED** [review]

**Review by pjanotti — APPROVED** [review]
