### PR TITLE
[receiver/hostmetrics] Cheaper parent PID and number of threads retrieval on Windows

### LINKED ISSUE #32947: HostMetrics process scraper high CPU usage during collection on Windows Server 2019
### Component(s)

receiver/hostmetrics

## Description

Otel Collector running on Windows Server 2019 was observed to have high CPU spikes (3-7%) each time the hostmetrics receiver collection process ran which was set to an interval of 1 minute.

image

After testing the issue was narrowed down to the `process` scraper. The following shows the Otel collector CPU usage when only the `process` scraper is enabled. 

image

After reenabling all other hostmetrics scrapers except for the `process` scraper, we can see the magnitude of the CPU spikes come down significantly (<0.5%).

Screenshot 2024-04-30 at 2 24 55 PM

## Steps to Reproduce

On a machine running Windows Server 2019, download the `v0.94` version of Otel collector from https://github.com/open-telemetry/opentelemetry-collector-releases/releases/tag/v0.94.0.

Modify the `config.yaml` to enable the hostmetrics `process` scraper and set the collection interval (see config attached to the issue for an example).

Run the otel collector exe

Monitor the CPU usage of the otel collector on Task Manager or graph the usage using perfmon 

## Expected Result

CPU usage comparable to observed levels on Linux collectors (<0.5%)

## Actual Result

CPU spikes to 3-7%

### Collector version

v0.93.0

## Environment
OS: Windows Server 2019

### OpenTelemetry Collector configuration

```yaml
receivers:
  hostmetrics:
    collection_interval: 1m
    scrapers:
      cpu:
        metrics:
          system.cpu.utilization:
            enabled: true
      disk:
      load:
      filesystem:
        metrics:
          system.filesystem.utilization:
            enabled: true
      memory:
        metrics:
          system.memory.utilization:
            enabled: true
      network:
      paging:
        metrics:
          system.paging.utilization:
            enabled: true
      processes:
      process:
        mute_process_exe_error: true
        metrics:
          process.cpu.utilization:
            enabled: true
          process.memory.utilization:
            enabled: true
  docker_stats:
    collection_interval: 1m
    metrics:
      container.cpu.throttling_data.periods:
        enabled: true
      container.cpu.throttling_data.throttled_periods:
        enabled: true
      container.cpu.throttling_data.throttled_time:
        enabled: true
  prometheus:
    config:
      scrape_configs:
        - job_name: $InstanceId/otel-self-metrics-collector-$Region
          scrape_interval: 1m
          static_configs:
            - targets: ['0.0.0.0:9999']
  otlp:
    protocols:
      grpc:
      http:

exporters:
  debug:
    verbosity: normal
  otlp:
    endpoint: <endpoint>

processors:
  memory_limiter:
    check_interval: 1s
    limit_mib: 500
    spike_limit_mib: 100
  batch:
    send_batch_size: 8192
    send_batch_max_size: 8192
    timeout: 2000ms
  filter:
    metrics:
      exclude:
        match_type: strict
        metric_names:
          # comment a metric to remove from exclusion rule
          - otelcol_exporter_queue_capacity
          - otelcol_exporter_enqueue_failed_spans
          - otelcol_exporter_enqueue_failed_log_records
          - otelcol_exporter_enqueue_failed_metric_points
          - otelcol_exporter_send_failed_metric_points
          - otelcol_process_runtime_heap_alloc_bytes
          - otelcol_process_runtime_total_alloc_bytes
          - otelcol_processor_batch_timeout_trigger_send
          - otelcol_process_runtime_total_sys_memory_bytes
          - otelcol_process_uptime
          - otelcol_scraper_errored_metric_points
          - otelcol_scraper_scraped_metric_points
          - scrape_samples_scraped
          - scrape_samples_post_metric_relabeling
          - scrape_series_added
          - scrape_duration_seconds
          # - up
  resourcedetection:
    detectors: ec2, env, system
    ec2:
      tags:
        - ^Environment$
    system:
      hostname_sources: ["os"]
      resource_attributes:
        host.id:
          enabled: true

extensions:
  health_check:
  pprof:
  zpages:

service:
  telemetry:
    metrics:
      level: detailed
      address: 0.0.0.0:9999
  extensions: [pprof, zpages, health_check]
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [debug, otlp]
      processors: [memory_limiter, batch, resourcedetection]
    metrics:
      receivers: [otlp, hostmetrics, prometheus]
      exporters: [debug, otlp]
      processors: [memory_limiter, batch, resourcedetection, filter]
    logs:
      receivers: [otlp]
      exporters: [debug, otlp]
      processors: [memory_limiter, batch, resourcedetection]
```

### Log output

_No response_

### Additional context

Additional details: Windows 2019 was running on an m5x.large EC2

### PR DESCRIPTION
**Pull request by pjanotti**
(To replace PR #35337)

Reduces the cost of getting number of threads and parent process ID by calling `CreateToolhelp32Snapshot` to do process enumeration. The data returned by this function already includes the number of threads and parent process ID - and avoiding calling `CreateToolhelp32Snapshot` for every enumerated process.

Fix #32947

```terminal
> go  test -benchmem -run=^$ -bench ^BenchmarkGetProcessMetadata$ -benchtime 10s
goos: windows
goarch: amd64
pkg: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/hostmetricsreceiver/internal/scraper/processscraper
cpu: Intel(R) Core(TM) Ultra 7 165H
BenchmarkGetProcessMetadata/Old-IncludeParentPid-22                    3        3928594600 ns/op        28357514 B/op      13029 allocs/op
BenchmarkGetProcessMetadata/New-IncludeParentPid-22                  171          69861262 ns/op        28222817 B/op      12591 allocs/op
BenchmarkGetProcessMetadata/Old-ExcludeParentPid-22                  172          68011864 ns/op        28232550 B/op      12614 allocs/op
BenchmarkGetProcessMetadata/New-ExcludeParentPid-22                  169          72172583 ns/op        28351193 B/op      12647 allocs/op
PASS
ok      github.com/open-telemetry/opentelemetry-collector-contrib/receiver/hostmetricsreceiver/internal/scraper/processscraper  81.722s
> go  test -benchmem -run=^$ -bench ^BenchmarkGetProcessMetadata$ -benchtime 30s
goos: windows
goarch: amd64
pkg: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/hostmetricsreceiver/internal/scraper/processscraper
cpu: Intel(R) Core(TM) Ultra 7 165H
BenchmarkGetProcessMetadata/Old-IncludeParentPid-22                    8        4115364238 ns/op        28797698 B/op      13220 allocs/op
BenchmarkGetProcessMetadata/New-IncludeParentPid-22                  514          70165003 ns/op        28702086 B/op      12800 allocs/op
BenchmarkGetProcessMetadata/Old-ExcludeParentPid-22                  552          70230804 ns/op        28558975 B/op      12750 allocs/op
BenchmarkGetProcessMetadata/New-ExcludeParentPid-22                  504          73404366 ns/op        28507275 B/op      12707 allocs/op
PASS
ok      github.com/open-telemetry/opentelemetry-collector-contrib/receiver/hostmetricsreceiver/internal/scraper/processscraper  170.587s
```

image

### CODE REVIEW

**Comment by braydonk** [comment]
Thank you for making this PR @pjanotti! It was helpful for me to understand what you meant; I didn't realize `CreateToolhelp32Snapshot` could be used in this way. This is awesome, I like it a lot better than what I did.

Comparing to the [performance data I posted in the other PR](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/35337#issuecomment-2680386097), here's a `pprof` profile pulled using a similar setup.
[config](https://gist.github.com/braydonk/c974abe2dca153239115f9a6abfd5cff)
[profile](https://pprof.me/c39ce8add79eeb3b9a19a881907bd090/?profileType=profile%253Acpu%253Ananoseconds%253Acpu%253Ananoseconds%253Adelta&color_by=filename)

I accidentally removed old builds of my PR, but based on the profile I'm not sure it's particularly necessary to do a perfmon comparison; the profile shows this PR is either the same or better without increasing WMI usage.

File: receiver/hostmetricsreceiver/internal/scraper/processscraper/process_scraper.go [hunk 1]
```diff
@@ -271,14 +271,17 @@ func (s *processScraper) getProcessMetadata(ctx context.Context) ([]*processMeta
 			continue
 		}
 
-		parentPid, err := parentPid(ctx, handle, pid)
-		if err != nil {
-			errs.AddPartial(0, fmt.Errorf("error reading parent pid for process %q (pid %v): %w", executable.name, pid, err))
+		parentProcessID := int32(0)
+		if !s.config.ExcludeParentPid {
```
Comment (braydonk) [inline receiver/hostmetricsreceiver/internal/scraper/processscraper/process_scraper.go:275]: I think you're right that we don't need a specific config for this. I would like to still make the check conditional, but we can make it conditional on whether the `process.parent_pid` resource attribute is enabled or not.

While on Windows with the new process enumeration method getting ppid no longer costs anything, on other platforms it will still be the old style of doing a certain operation per-process. It's cheap on other platforms, but as a matter of principle I do think any work this scraper does should be conditional on whether the user actually enabled that attribute/metric.

**Review by braydonk — COMMENTED** [review]
I'm not sure what your plan is for integrating this, but here's my thoughts.

* The existing `getProcessHandlesInternal` function gets renamed `getProcessHandlesGopsutil`
* `getProcessHandlesInternal` becomes a new function in each `process_scraper_*.go` platform specific file. Most just shell out to `getProcessHandlesGopsutil`, whereas on Windows it will be the contents of `getProcessHandlesInternalNew` from this PR
* Debatably, this might be enough of a deviation in behaviour to constitute a featuregate. I think this is safe enough that it could start as a Beta featuregate. If we do go with a featuregate, `getProcessHandlesInternal` in `process_scraper_windows.go` would check if the featuregate enabled, and if it's not then shell out to `getProcessHandlesGopsutil`.

I think with those things in place, the PR would be ready to come out of draft.

File: receiver/hostmetricsreceiver/internal/scraper/processscraper/process_metadata_benchmark_test.go [hunk 2]
```diff
@@ -0,0 +1,71 @@
+// Copyright The OpenTelemetry Authors
+// SPDX-License-Identifier: Apache-2.0
+
+//go:build windows
+
+package processscraper
```
Comment (pjanotti) [inline receiver/hostmetricsreceiver/internal/scraper/processscraper/process_metadata_benchmark_test.go:6]: This file could be removed when we remove the featureflag to fallback to the old behavior.

File: receiver/hostmetricsreceiver/internal/scraper/processscraper/get_process_handles_windows.go [hunk 3]
```diff
@@ -0,0 +1,84 @@
...
+	"fmt"
+	"unsafe"
+
+	"github.com/shirou/gopsutil/v4/process"
+	"go.opentelemetry.io/collector/featuregate"
+	"golang.org/x/sys/windows"
+)
+
+var useNewGetProcessHandles = featuregate.GlobalRegistry().MustRegister(
+	"hostmetrics.process.OnWindowsUseNewGetProcesses",
```
Comment (braydonk) [inline receiver/hostmetricsreceiver/internal/scraper/processscraper/get_process_handles_windows.go:19]: I'm not sure if we have a naming convention for these, but I think usually we don't capitalize the first letter, so it would be `onWindowsUseNewGetProcesses`. I'm not sure if that's a hard and fast rule written somewhere or not.

File: receiver/hostmetricsreceiver/internal/scraper/processscraper/get_process_handles_windows.go [hunk 4]
```diff
@@ -0,0 +1,84 @@
...
+	featuregate.StageBeta,
+	featuregate.WithRegisterDescription("If disabled, the scraper will use the legacy implementation to retrieve process handles."),
+)
+
+func getGopsutilProcessHandles(ctx context.Context) (processHandles, error) {
```
Comment (braydonk) [inline receiver/hostmetricsreceiver/internal/scraper/processscraper/get_process_handles_windows.go:24]: I think this function needs to be somewhere else; this file is build constrained on `GOOS` being `windows`, but is then used in `process_scraper.go` which is not under the same constraint. Maybe move this to `process.go`?

Comment (pjanotti) [reply receiver/hostmetricsreceiver/internal/scraper/processscraper/get_process_handles_windows.go:24]: There is [`get_process_handles_others.go`](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/38589/files#diff-e5aa3065e388b30939320aa1a375542f2a777b6029d8e6689038995c10941c63) that is the same as the old implementation and built for all non-Windows platforms.

File: receiver/hostmetricsreceiver/internal/scraper/processscraper/get_process_handles_windows.go (hunk 3 above)
Comment (pjanotti) [reply receiver/hostmetricsreceiver/internal/scraper/processscraper/get_process_handles_windows.go]: 4ae28a72d33acffdc48bc6442b29d4d52e3cafbc

**Review by braydonk — APPROVED** [review]

File: receiver/hostmetricsreceiver/internal/scraper/processscraper/process_scraper.go [hunk 5]
```diff
@@ -250,7 +250,7 @@ func (s *processScraper) getProcessMetadata(ctx context.Context) ([]*processMeta
 		}
 
 		command, err := getProcessCommand(ctx, handle)
-		if err != nil {
+		if err != nil && !s.config.MuteProcessAllErrors {
```
Comment (dmitryax) [inline receiver/hostmetricsreceiver/internal/scraper/processscraper/process_scraper.go:253]: Why do we add muting here  but the related change on line 277 still unmuted? Maybe remove this from this PR to fix consistently separately?

Comment (pjanotti) [reply receiver/hostmetricsreceiver/internal/scraper/processscraper/process_scraper.go]: d43aa79684

**Review by dmitryax — APPROVED** [review]
