### PR TITLE
[receiver/prometheus] add feature flag to be able to disable Prometheus setting to fix high CPU for openmetrics

### LINKED ISSUE #40245: Increased CPU usage after upgrading to 0.121.0
### Component(s)

receiver/prometheus

### What happened?

Originally reported here: #38904 

After upgrading from `0.117.0` to `0.126.0` I've noticed roughly 5-10 times increase in CPU usage.
I've narrowed down regression to be in version `0.121.0`.

Some additional info:
- I run `logs`, `metrics` and `traces` collectors as separate OTECOLs via otel-operator
- This issue is present ONLY in `metrics` collector

Here is CPU profile:
Image

Memory:
Image

Goroutines:

Image

### Collector version

0.121.0

## Environment
EKS 1.31

### OpenTelemetry Collector configuration

```yaml
config:
  connectors:
    forward/all: {}
  exporters:
    debug/detailed:
      sampling_initial: 5
      sampling_thereafter: 100
      verbosity: detailed
    debug/normal:
      verbosity: normal
    otlphttp:
      auth:
        authenticator: basicauth/client
      compression: gzip
      endpoint: <REDACTED>
  extensions:
    basicauth/client:
      client_auth:
        password: ${OTEL_GW_PASSWORD}
        username: ${OTEL_GW_USERNAME}
    health_check:
      endpoint: 0.0.0.0:13133
      path: /
    pprof:
      endpoint: 0.0.0.0:1777
  processors:
    attributes:
      actions:
      - action: upsert
        key: cluster
        value: <REDACTED>
      - action: upsert
        key: alerting_tier
        value: "1"
    batch:
      send_batch_max_size: 5000
      send_batch_size: 2000
    memory_limiter:
      check_interval: 1s
      limit_percentage: 80
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: 0.0.0.0:4317
        http:
          endpoint: 0.0.0.0:4318
    prometheus:
      config:
        scrape_configs:
        - job_name: dummy
          static_configs:
          - targets:
            - 127.0.0.1:8888
  service:
    extensions:
    - basicauth/client
    - health_check
    - pprof
    pipelines:
      metrics/forward:
        receivers:
        - otlp
        - prometheus
        processors:
        - memory_limiter
        - attributes
        exporters:
        - forward/all
      metrics/otlp:
        receivers:
        - forward/all
        processors:
        - batch
        exporters:
        - otlphttp
```

### Log output

```shell

```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by gracewehner**
#### Description
The PR #36660 enabled the setting in the scrape manager `EnableCreatedTimestampZeroIngestion` by default. This enabled the [Prometheus feature flag](https://prometheus.io/docs/prometheus/latest/feature_flags/#created-timestamps-zero-injection) by the same name. In Prometheus, when this is set to true, [a call to a new function](https://github.com/prometheus/prometheus/blob/1d9dfde9894f0c82b809b70aa5f9cecab25b8fea/scrape/scrape.go#L1770-L1799) CreatedTimestamp() is run. 

This currently isn't implemented for the Prometheus parser but is for the OpenMetrics parser and [has a comment](https://github.com/prometheus/prometheus/blob/main/model/textparse/openmetricsparse.go#L287) that it may use additional CPU and memory resources. We are seeing a 10x increase in CPU usage when there's a high volume of metrics scraped with this scenario.

This PR puts the setting in the scrape manager behind a feature gate that allows it to be disabled.

#### Link to tracking issue
Fixes #40245

#### Testing
Tested with a custom build with this change.

#### Documentation
Documentation about the feature gate exists [here](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/receiver/prometheusreceiver/README.md#getting-started).

### CODE REVIEW

**Comment by gracewehner** [comment]
Accidentally opened early

**Review by bragi92 — APPROVED** [review]

File: receiver/prometheusreceiver/metrics_receiver.go [hunk 1]
```diff
@@ -190,7 +190,7 @@ func (r *pReceiver) initPrometheusComponents(ctx context.Context, logger *slog.L
 		HTTPClientOptions: []commonconfig.HTTPClientOption{
 			commonconfig.WithUserAgent(r.settings.BuildInfo.Command + "/" + r.settings.BuildInfo.Version),
 		},
-		EnableCreatedTimestampZeroIngestion: true,
+		EnableCreatedTimestampZeroIngestion: useCreatedMetricGate.IsEnabled(),
```
Comment (ridwanmsharif) [inline receiver/prometheusreceiver/metrics_receiver.go:193]: > This PR puts the setting in the scrape manager behind the same feature gate that the [Prometheus Receiver has](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/receiver/prometheusreceiver/README.md#getting-started):
--feature-gates=receiver.prometheusreceiver.UseCreatedMetric

Is this true? It looks like the two feature flags are somewhat different.

The `receiver.prometheusreceiver.UseCreatedMetric` flag seems to be controlling how the adjuster should be treating timestamps and whether the adjuster should ignore it (context: https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/17498)

And the prometheus feature flag you linked looks like it controls whether Created timestamps are injected as 0 valued samples (context: https://prometheus.io/docs/prometheus/latest/feature_flags/#created-timestamps-zero-injection)

They feel orthogonal from one another. I recommend either adding a comment to clarify why we're tie-ing the two together (i.e. it feels like to me that it is valuable to independently only adjust the adjuster feature flag without the 0 inestion one), or we should create a new feature flag for this behaviour to match the one in prometheus.

I prefer the latter option

File: receiver/prometheusreceiver/README.md [hunk 2]
```diff
@@ -68,6 +68,11 @@ prometheus --config.file=prom.yaml
 ```shell
 "--feature-gates=receiver.prometheusreceiver.UseCreatedMetric"
 ```
+- `receiver.prometheusreceiver.EnableCreatedTimestampZeroIngestion`: Enables the Prometheus feature flag [created-timestamps-zero-injection](https://prometheus.io/docs/prometheus/latest/feature_flags/#created-timestamps-zero-injection). Currently, this behaviour is enabled by default. To disable it, use the following feature gate option:
```
Comment (ridwanmsharif) [inline receiver/prometheusreceiver/README.md:71]: Since prometheus doesn't do this by default, we shouldn't either: https://github.com/prometheus/prometheus/blob/24057883a14c597d70f46612e4b8fb5c9ad58d62/cmd/prometheus/main.go#L265-L266

**Review by ridwanmsharif — APPROVED** [review]
LGTM modulo the default setting

**Review by ArthurSens — COMMENTED** [review]
Alright, code changes look good (after addressing Ridwan's comment) but could we implement a test with the new feature flag?

This is mostly to guarantee that future PRs don't break the behavior you're adding here :)

**Comment by gracewehner** [comment]
Thanks @ridwanmsharif @ArthurSens addressed both of your feedback

File: receiver/prometheusreceiver/README.md [hunk 3]
```diff
@@ -68,6 +68,11 @@ prometheus --config.file=prom.yaml
 ```shell
 "--feature-gates=receiver.prometheusreceiver.UseCreatedMetric"
 ```
+- `receiver.prometheusreceiver.EnableCreatedTimestampZeroIngestion`: Enables the Prometheus feature flag [created-timestamps-zero-injection](https://prometheus.io/docs/prometheus/latest/feature_flags/#created-timestamps-zero-injection). Currently, this behaviour is disabled by default. To enable it, use the following feature gate option:
+
+```shell
+"--feature-gates=receiver.prometheusreceiver.-EnableCreatedTimestampZeroIngestion"
```
Comment (ArthurSens) [inline receiver/prometheusreceiver/README.md]:
```suggestion
"--feature-gates=receiver.prometheusreceiver.EnableCreatedTimestampZeroIngestion"
```

The minus character will keep the gate disabled

**Review by ArthurSens — COMMENTED** [review]
Oh, sorry for not being clear, the test is not about checking if the options are set correctly, but rather that we correctly parse created lines when the feature flag is true/false.


We have several tests in `metrics_receiver.go` that parse a string that resembles a /metrics endpoint and has a `validateFunc` that will verify if the output is correct. Could you write one similar, but with the created lines and with feature gate on/off?

Here is one example[[1](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/6e092c15c0e640a087f122c7cd490cb07bc714ea/receiver/prometheusreceiver/metrics_receiver_test.go#L1543-L1557)]. You'll just need to change the input string and validation function.

**Review by dashpole — APPROVED** [review]

**Comment by gracewehner** [comment]
No problem, thanks @ArthurSens I added those tests in too

File: receiver/prometheusreceiver/README.md [hunk 4]
```diff
@@ -68,6 +68,11 @@ prometheus --config.file=prom.yaml
 ```shell
 "--feature-gates=receiver.prometheusreceiver.UseCreatedMetric"
 ```
+- `receiver.prometheusreceiver.EnableCreatedTimestampZeroIngestion`: Enables the Prometheus feature flag [created-timestamps-zero-injection](https://prometheus.io/docs/prometheus/latest/feature_flags/#created-timestamps-zero-injection). Currently, this behaviour is disabled by default. To enable it, use the following feature gate option:
```
Comment (krajorama) [inline receiver/prometheusreceiver/README.md]: nit: might want to mention why we disable it :)

File: receiver/prometheusreceiver/metrics_receiver.go [hunk 5]
```diff
@@ -234,6 +223,23 @@ func (r *pReceiver) initPrometheusComponents(ctx context.Context, logger *slog.L
...
+	opts := &scrape.Options{
+		PassMetadataInContext: true,
+		ExtraMetrics:          r.cfg.ReportExtraScrapeMetrics,
+		HTTPClientOptions: []commonconfig.HTTPClientOption{
+			commonconfig.WithUserAgent(r.settings.BuildInfo.Command + "/" + r.settings.BuildInfo.Version),
+		},
+		EnableCreatedTimestampZeroIngestion: enableCreatedTimestampZeroIngestionGate.IsEnabled(),
+	}
+
+	if enableNativeHistogramsGate.IsEnabled() {
```
Comment (krajorama) [inline receiver/prometheusreceiver/metrics_receiver.go]: nit: not sure why I wrote it in a separate `if`, probably to have smaller diff. I think it can be moved into the `opts` init as well above.

**Review by krajorama — APPROVED** [review]

File: receiver/prometheusreceiver/README.md (hunk 4 above)
Comment (gracewehner) [reply receiver/prometheusreceiver/README.md]: Thanks addressed both of your comments

**Review by ArthurSens — APPROVED** [review]
We can probably improve the readability of those tests, but it doesn't need to be in this PR. Thanks!
