### PR TITLE
[processor/deltatocumulative]: do not drop Gauge, Summary

### LINKED ISSUE #35284: [processor/deltatocumulative] Incorrectly dropping gauge metrics
### Component(s)

processor/deltatocumulative

### What happened?

I expected the `deltatocumulative` to ignore gauge metrics, however it is filtering them.

This was previously a latent issue, but with https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/34979 it is now impacting functionality.

```golang
	metrics.Filter(md, func(m metrics.Metric) bool {
		var n int
		switch m.Type() {
		case pmetric.MetricTypeSum:
			sum := m.Sum()
			if sum.AggregationTemporality() == pmetric.AggregationTemporalityDelta {
				err := streams.Apply(metrics.Sum(m), p.sums.aggr.Aggregate)
				errs = errors.Join(errs, err)
				sum.SetAggregationTemporality(pmetric.AggregationTemporalityCumulative)
			}
			n = sum.DataPoints().Len()
		case pmetric.MetricTypeHistogram:
			hist := m.Histogram()
			if hist.AggregationTemporality() == pmetric.AggregationTemporalityDelta {
				err := streams.Apply(metrics.Histogram(m), p.hist.aggr.Aggregate)
				errs = errors.Join(errs, err)
				hist.SetAggregationTemporality(pmetric.AggregationTemporalityCumulative)
			}
			n = hist.DataPoints().Len()
		case pmetric.MetricTypeExponentialHistogram:
			expo := m.ExponentialHistogram()
			if expo.AggregationTemporality() == pmetric.AggregationTemporalityDelta {
				err := streams.Apply(metrics.ExpHistogram(m), p.expo.aggr.Aggregate)
				errs = errors.Join(errs, err)
				expo.SetAggregationTemporality(pmetric.AggregationTemporalityCumulative)
			}
			n = expo.DataPoints().Len()
		}
		return n > 0
	})
```

### Collector version

v0.109.0

### PR DESCRIPTION
**Pull request by tombrk**
**Description:**
As an oversight, https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/33286 not only started dropping metrics without datapoints, but also all Gauges and Summaries.
This change correctly passes those types through unaltered.

**Link to tracking Issue:** Fixes #35284 

**Testing:** `TestIgnore` was added _before_ fixing. It fails on current main, passes after this change

**Documentation:** not needed

### CODE REVIEW

**Review by ArthurSens — APPROVED** [review]
thanks!

File: processor/deltatocumulativeprocessor/processor_test.go [hunk 1]
```diff
@@ -282,3 +284,27 @@ func stream() SumBuilder {
...
+	in := open("in.yaml")
+	out := open("out.yaml")
+
+	ctx := context.Background()
+
+	err := proc.ConsumeMetrics(ctx, in)
+	require.NoError(t, err)
+
+	if diff := compare.Diff([]pmetric.Metrics{out}, sink.AllMetrics()); diff != "" {
+		t.Fatal(diff)
```
Comment (jpkrohling) [inline processor/deltatocumulativeprocessor/processor_test.go:308]: t.Fatal? Why not "assert.Fail()", as the other ones? Or `assert.Len(t, "", compare.Diff(...))` ?

**Review by jpkrohling — APPROVED** [review]
I'm approving, as without this the component is barely usable. Tests can be improved on a follow-up PR.
