### PR TITLE
[receiver/awsfirehose] Fix decoding for OTLP-formatted metrics

### LINKED ISSUE #39462: Unmarshal error for OTLP-formatted metrics from cross-account observability enabled CloudWatch metric streams
### Component(s)

receiver/awsfirehose

## Description

We are seeing the following errors when sending metrics from AWS Firehose to an OpenTelemetry Collector with the `awsfirehose` receiver:
```
error    awsfirehosereceiver@v0.122.0/receiver.go:225    Unable to consume records    {"otelcol.component.id": "awsfirehose", "otelcol.component.kind": "Receiver", "otelcol.signal": "metrics", "error": "unable to unmarshal input: unexpected EOF"}
```

We have a Firehose stream that receives OTLP_v1 encoded metrics via Direct PUT from a CloudWatch metric stream with [cross-account observability](https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/CloudWatch-Unified-Cross-Account.html) enabled (that is a _monitoring_ account whose metrics originate from other _source_ accounts within the same region) and forwards metrics to an OpenTelemetry collector with an `awsfirehose` receiver.
Oddly, this issue only occurs when the CloudWatch metric stream has cross-account observability enabled. This hints that the request payload is too large and gets truncated in transit from the CloudWatch metric stream through the Firehose stream to the OpenTelemetry collector, especially considering the very similar issue #38736. Perhaps, metric events that are originate from cross-account enabled CloudWatch metric streams are more verbose than CloudWatch metric streams without cross-account enabled. Nonetheless, the receiver should be able to handle requests that contain standard-size metric events (i.e., metrics without any transformations) from CloudWatch metric streams with cross-account observability enabled.

## Steps to Reproduce

(Apologies in advance for screenshots. The AWS services were configured in UI as we are still exploring this design for feasibility before committing to any infrastructure-as-code.)

**CloudWatch Metric Stream configuration**
Image
(Note the `Monitoring Account` label in the top-right corner, which allows the account to enable cross-account observability and adds the _Include source account metrics_ toggle option. This can be easily configured following [this AWS document](https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/CloudWatch-Unified-Cross-Account-Setup.html#CloudWatch-Unified-Cross-Account-Setup-overview).)

**AWS Firehose configuration**
Image
The source for the stream is Direct PUT (see the CloudWatch metric stream configuration above that shows the destination is set to this Firehose stream) and the destination is an HTTP endpoint, which is an exposed endpoint of an OpenTelemetry collector. Most importantly, note that we are using the maximum buffer size (64MiB) for Firehose and even using (gzip) compression (though it doesn't make a difference since the errors occur whether compression is on or off). 

## Expected Result

`awsfirehose` receiver should be able to handle large incoming requests without error.

### Collector version

v0.122.1

## Environment
**Helm chart:** opentelemetry-collector v0.120.0
**Kubernetes:** v1.30.10

### OpenTelemetry Collector configuration

```yaml
opentelemetry-collector:
  config:
    extensions:
      health_check: {}
      oauth2client:
        client_id: ${env:id}
        client_secret: ${env:secret}
        token_url: ...
        scopes: ...
    receivers:
      awsfirehose:
        endpoint: ${env:MY_POD_IP}:4433
        encoding: otlp_v1
        tls:
          cert_file: /etc/tls/tls.crt
          key_file: /etc/tls/tls.key
    exporters:
      debug: {}
    service:
      extensions:
        - oauth2client
        - health_check
      pipelines:
        metrics:
          receivers:
            - awsfirehose
          exporters:
            - debug
  ports:
    aws-firehose:
      enabled: true
      containerPort: 4433
      servicePort: 4433
      hostPort: 4433
      protocol: TCP
...
```

### Log output

```shell
2025-04-16T18:52:02.469Z    error    awsfirehosereceiver@v0.122.0/receiver.go:225    Unable to consume records    {"otelcol.component.id": "awsfirehose", "otelcol.component.kind": "Receiver", "otelcol.signal": "metrics", "error": "unable to unmarshal input: unexpected EOF"}
github.com/open-telemetry/opentelemetry-collector-contrib/receiver/awsfirehosereceiver.(*firehoseReceiver).ServeHTTP                                                                  
     github.com/open-telemetry/opentelemetry-collector-contrib/receiver/awsfirehosereceiver@v0.122.0/receiver.go:225                                     
2025-04-16T18:52:06.482Z    error    awsfirehosereceiver@v0.122.0/receiver.go:225    Unable to consume records    {"otelcol.component.id": "awsfirehose", "otelcol.component.kind": "Receiver", "otelcol.signal": "metrics", "error": "unable to unmarshal input: unexpected EOF"} 
github.com/open-telemetry/opentelemetry-collector-contrib/receiver/awsfirehosereceiver.(*firehoseReceiver).ServeHTTP                                                             
     github.com/open-telemetry/opentelemetry-collector-contrib/receiver/awsfirehosereceiver@v0.122.0/receiver.go:225                                                          
```

### PR DESCRIPTION
**Pull request by constanca-m**
#### Description

Fix decoding for OTLP-formatted metrics. The unmarshaler for OTLP-formatted metrics uses the [awscloudwatchmetricstreamsencodingextension](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/extension/encoding/awscloudwatchmetricstreamsencodingextension) to unmarshal the metrics, instead of a custom unmarshaler.

#### Link to tracking issue
Fixes #39462.

#### Testing

Unit tests fixed.

#### Documentation

README updated with a warning.

### CODE REVIEW

File: receiver/awsfirehosereceiver/internal/unmarshaler/otlpmetricstream/unmarshaler_test.go [hunk 1]
```diff
@@ -4,117 +4,84 @@
...
+
 	testCases := map[string]struct {
-		record             []byte
-		wantResourceCount  int
-		wantMetricCount    int
-		wantDatapointCount int
-		wantErr            string
+		record                  []byte
+		expectedMetricsFilename string
+		wantErr                 string
```
Comment (constanca-m) [inline receiver/awsfirehosereceiver/internal/unmarshaler/otlpmetricstream/unmarshaler_test.go:51]: These are the same unit tests as before. I have just put them in files so we can compare the metrics to each other, instead of the length of metrics / data points.

File: receiver/awsfirehosereceiver/README.md
Comment (axw) [inline receiver/awsfirehosereceiver/README.md:1]: Is there precedent for including this in the collector READMEs? I'd rather just add it to the changelog.

File: receiver/awsfirehosereceiver/metrics_receiver.go [hunk 2]
```diff
@@ -69,8 +69,10 @@ func (c *metricsConsumer) Start(_ context.Context, host component.Host) error {
 		// TODO: make cwmetrics an encoding extension
 		c.unmarshaler = cwmetricstream.NewUnmarshaler(c.settings.Logger, c.settings.BuildInfo)
 	case otlpmetricstream.TypeStr:
-		// TODO: make otlp_v1 an encoding extension
-		c.unmarshaler = otlpmetricstream.NewUnmarshaler(c.settings.Logger, c.settings.BuildInfo)
+		var err error
+		if c.unmarshaler, err = otlpmetricstream.NewUnmarshaler(ctx); err != nil {
```
Comment (axw) [inline receiver/awsfirehosereceiver/metrics_receiver.go:73]: Should we create the encoding extension directly here? Then we can use the receiver.Settings for creating the extension.Settings

File: receiver/awsfirehosereceiver/internal/unmarshaler/otlpmetricstream/unmarshaler.go [hunk 3]
```diff
@@ -4,73 +4,57 @@
...
-		}
-		req.Metrics().ResourceMetrics().MoveAndAppendTo(md.ResourceMetrics())
+// NewUnmarshaler creates a new instance of the aws cloudwatch metric streams
+// encoding extension unmarshaler for the OpenTelemetry record format.
+func NewUnmarshaler(ctx context.Context) (pmetric.Unmarshaler, error) {
+	f := awscloudwatchmetricstreamsencodingextension.NewFactory()
+	extensionID := component.NewID(f.Type())
+	ext, err := f.Create(ctx, extension.Settings{
+		ID: extensionID,
+	}, &awscloudwatchmetricstreamsencodingextension.Config{
```
Comment (axw) [inline receiver/awsfirehosereceiver/internal/unmarshaler/otlpmetricstream/unmarshaler.go:43]: This means there's no telemetry settings or BuildInfo being passed in right? Doesn't seem ideal. I think we should create the extension in the receiver code, and delete internal/unmarshaler/otlpmetricstream.

File: receiver/awsfirehosereceiver/internal/unmarshaler/otlpmetricstream/unmarshaler_test.go (hunk 1 above)
Comment (axw) [reply receiver/awsfirehosereceiver/internal/unmarshaler/otlpmetricstream/unmarshaler_test.go:51]: We have coverage in the encoding extension, do we even need all these tests? I would be inclined to delete the internal unmarshaler and use the encoding extension directly, and add a test at the top level to make sure the encoding is wired up correctly. Just enough to very it can decode OTLP metrics -- it doesn't need to cover all the paths of the encoding extension.

**Review by axw — COMMENTED** [review]
@constanca-m I think we may as well delete some more code, let me know what you think.

File: receiver/awsfirehosereceiver/README.md
Comment (constanca-m) [reply receiver/awsfirehosereceiver/README.md:1]: I am not aware of it. I will remove it then.

File: receiver/awsfirehosereceiver/internal/unmarshaler/otlpmetricstream/unmarshaler_test.go (hunk 1 above)
Comment (constanca-m) [reply receiver/awsfirehosereceiver/internal/unmarshaler/otlpmetricstream/unmarshaler_test.go:51]: I agree that it is redundant, I kept it to make the change easier. I will remove it.

**Review by axw — APPROVED** [review]
LGTM! Thank you.

File: receiver/awsfirehosereceiver/internal/unmarshaler/otlpmetricstream/unmarshaler.go (hunk 3 above)
Comment (constanca-m) [reply receiver/awsfirehosereceiver/internal/unmarshaler/otlpmetricstream/unmarshaler.go]: We have to change the `BuildInfo` to not use the scope name from the receiver. But since the scope name is coming from the internal package of the encoding extension, we would have to hardcode it here. WDYT?

Comment (constanca-m) [reply receiver/awsfirehosereceiver/internal/unmarshaler/otlpmetricstream/unmarshaler.go]: Sorry @axw, I was wrong!! The scope name is correct, since we define it directly on the unmarshaler from the `metadata` there.

Comment (constanca-m) [reply receiver/awsfirehosereceiver/internal/unmarshaler/otlpmetricstream/unmarshaler.go]: https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/58d4ce9f27658578f202c966d0d19f3b4e73a58e/extension/encoding/awscloudwatchmetricstreamsencodingextension/opentelemetry_unmarshaler.go#L54-L55

Comment (axw) [reply receiver/awsfirehosereceiver/internal/unmarshaler/otlpmetricstream/unmarshaler.go]: Ah yes :) No worries, thanks for clarifying.

**Comment by atoulme** [comment]
Please resolve conflicts and mark ready to review again.

**Comment by atoulme** [comment]
Please resolve conflicts and mark ready for review again.

**Comment by constanca-m** [comment]
@atoulme @mx-psi Can you merge this once you have the time? Otherwise, I need to keep updating the PR every week for the conflicts.

**Review by atoulme — APPROVED** [review]
