### PR TITLE
Fix flaky prom remote write exporter concurrency test

### LINKED ISSUE #37104: [test] Test_PushMetricsConcurrent fails on Windows 2025 GH runner
### Component(s)

exporter/prometheusremotewrite

### Describe the issue you're reporting

Detected via #37025 - the test is failing consistently on the Windows 2025 GH runner. Opening this issue so we can enable tests on Windows 2025 while this test failure is investigated.

Related to #37024

### PR DESCRIPTION
**Pull request by pjanotti**
Fix #37104

This is more an artifact of the test firing an unbounded number of go routines each one making its own HTTP request. Although keepalive is enabled by default the code ends up not re-using many of the connections causing the many connections to end up in a TIME_WAIT state. In order to avoid this the test now limits the number of concurrent requests and has a small change to the actual code to facilitate re-use of existing TCP connections used by the HTTP client.

Although there is a change to non-test code I don't consider this a bug worth changelog because no user of the component should reach such high burst of "push metrics" in any reasonable production scenario.

### CODE REVIEW

File: exporter/prometheusremotewriteexporter/exporter_concurrency_test.go [hunk 1]
```diff
@@ -137,15 +134,22 @@ func Test_PushMetricsConcurrent(t *testing.T) {
 		resp, checkRequestErr := http.Get(server.URL)
 		require.NoError(c, checkRequestErr)
 		assert.NoError(c, resp.Body.Close())
-	}, 5*time.Second, 100*time.Millisecond)
+	}, 15*time.Second, 100*time.Millisecond)
 
 	var wg sync.WaitGroup
 	wg.Add(n)
+	maxConcurrentGoroutines := runtime.NumCPU() * 4
```
Comment (pjanotti) [inline exporter/prometheusremotewriteexporter/exporter_concurrency_test.go:141]: If there are still failures on this test it may be necessary to reduce even further the amount of concurrency allowed here.

**Review by dashpole — APPROVED** [review]
