### PR TITLE
[pkg/stanza] Fix Windows UNC network path handling in filelog receiver

### LINKED ISSUE #44401: Windows network path in filelog receiver
### Component(s)

receiver/filelog

## Description
Log file from application is on network path. psexec -i -u [username] powershell.exe shows that network drive is accesible i can "cat" the file. Also logs show that application can list the directory content and read file name but it's unable to parse it.

## Steps to Reproduce
Network share path in file log configuration, ie

receivers:
  filelog:
    include:
      - \\networkShare2\BLAM\Logs\stdout_*

## Expected Result
Read file

## Actual Result
Can't read file

### Collector version

0.139.0

## Environment
OS: Windows Server 2022 Standard
otelcol-contrib_0.139.0_windows_x64.msi

### OpenTelemetry Collector configuration

```yaml
receivers:
  filelog:
    include:
      - \\networkShare2\BLAM\Logs\stdout_*
    start_at: beginning
    include_file_name: true
    include_file_path: true
    operators:
      - type: regex_parser
        regex: '^(?<timestamp>\d{2}\.\d{2}\.\d{4} \d{2}:\d{2}:\d{2}):\s*(?<message>.*)$'
        parse_from: body
        timestamp:
          parse_from: attributes.timestamp
          layout: '%m.%d.%Y %H:%M:%S'

exporters:
  azuremonitor:
    connection_string: "tadamtadam"
    
processors:
  batch:
    send_batch_size: 500
    send_batch_max_size: 5000
    timeout: 5s

service:
  telemetry:
    metrics:
      level: none
    logs:
      level: info
      encoding: json
      output_paths: ["C:\\Program Files\\OpenTelemetry Collector\\otel.log"]
      error_output_paths: ["C:\\Program Files\\OpenTelemetry Collector\\otel-error.log"]
  pipelines:
    logs:
      receivers: [filelog]
      processors: [batch]
      exporters: [azuremonitor]
```

### Log output

```shell
{"level":"info","ts":"2025-11-19T18:01:16.293+0100","caller":"otelconftelemetry/metrics.go:24","msg":"Internal metrics telemetry disabled","resource":{"service.instance.id":"7c1d75b1-d505-4061-9314-63ad876c9e9b","service.name":"otelcol-contrib","service.version":"0.139.0"}}
{"level":"info","ts":"2025-11-19T18:01:16.294+0100","caller":"service@v0.139.0/service.go:222","msg":"Starting otelcol-contrib...","resource":{"service.instance.id":"7c1d75b1-d505-4061-9314-63ad876c9e9b","service.name":"otelcol-contrib","service.version":"0.139.0"},"Version":"0.139.0","NumCPU":4}
{"level":"info","ts":"2025-11-19T18:01:16.294+0100","caller":"extensions/extensions.go:40","msg":"Starting extensions...","resource":{"service.instance.id":"7c1d75b1-d505-4061-9314-63ad876c9e9b","service.name":"otelcol-contrib","service.version":"0.139.0"}}
{"level":"info","ts":"2025-11-19T18:01:16.294+0100","caller":"adapter/receiver.go:41","msg":"Starting stanza receiver","resource":{"service.instance.id":"7c1d75b1-d505-4061-9314-63ad876c9e9b","service.name":"otelcol-contrib","service.version":"0.139.0"},"otelcol.component.id":"filelog","otelcol.component.kind":"receiver","otelcol.signal":"logs"}
{"level":"info","ts":"2025-11-19T18:01:16.315+0100","caller":"service@v0.139.0/service.go:245","msg":"Everything is ready. Begin running and processing data.","resource":{"service.instance.id":"7c1d75b1-d505-4061-9314-63ad876c9e9b","service.name":"otelcol-contrib","service.version":"0.139.0"}}
{"level":"error","ts":"2025-11-19T18:01:16.517+0100","caller":"fileconsumer/file.go:181","msg":"Failed to open file","resource":{"service.instance.id":"7c1d75b1-d505-4061-9314-63ad876c9e9b","service.name":"otelcol-contrib","service.version":"0.139.0"},"otelcol.component.id":"filelog","otelcol.component.kind":"receiver","otelcol.signal":"logs","component":"fileconsumer","error":"open \\networkShare2\\BLAM\\Logs\\stdout_46_2025.log: The system cannot find the path specified.","stacktrace":"github.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza/fileconsumer.(*Manager).makeFingerprint\n\tgithub.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza@v0.139.0/fileconsumer/file.go:181\ngithub.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza/fileconsumer.(*Manager).makeReaders\n\tgithub.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza@v0.139.0/fileconsumer/file.go:208\ngithub.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza/fileconsumer.(*Manager).consume\n\tgithub.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza@v0.139.0/fileconsumer/file.go:158\ngithub.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza/fileconsumer.(*Manager).poll\n\tgithub.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza@v0.139.0/fileconsumer/file.go:140\ngithub.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza/fileconsumer.(*Manager).startPoller.func1\n\tgithub.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza@v0.139.0/fileconsumer/file.go:110"}
{"level":"error","ts":"2025-11-19T18:01:16.718+0100","caller":"fileconsumer/file.go:181","msg":"Failed to open file","resource":{"service.instance.id":"7c1d75b1-d505-4061-9314-63ad876c9e9b","service.name":"otelcol-contrib","service.version":"0.139.0"},"otelcol.component.id":"filelog","otelcol.component.kind":"receiver","otelcol.signal":"logs","component":"fileconsumer","error":"open \\networkShare2\\BLAM\\Logs\\stdout_46_2025.log: The system cannot find the path specified.","stacktrace":"github.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza/fileconsumer.(*Manager).makeFingerprint\n\tgithub.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza@v0.139.0/fileconsumer/file.go:181\ngithub.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza/fileconsumer.(*Manager).makeReaders\n\tgithub.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza@v0.139.0/fileconsumer/file.go:208\ngithub.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza/fileconsumer.(*Manager).consume\n\tgithub.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza@v0.139.0/fileconsumer/file.go:158\ngithub.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza/fileconsumer.(*Manager).poll\n\tgithub.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza@v0.139.0/fileconsumer/file.go:140\ngithub.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza/fileconsumer.(*Manager).startPoller.func1\n\tgithub.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza@v0.139.0/fileconsumer/file.go:110"}
```

### Additional context

_No response_

### Tip

<sub>[React](https://github.blog/news-insights/product-news/add-reactions-to-pull-requests-issues-and-comments/) with 👍 to help prioritize this issue. Please use comments to provide useful context, avoiding `+1` or `me too`, to help us triage it. Learn more [here](https://opentelemetry.io/community/end-user/issue-participation/).</sub>

### PR DESCRIPTION
**Pull request by paulojmdias**
#### Description

Fixes Windows UNC network path handling in the filelog receiver. The receiver could list files from UNC paths (`\\server\share\logs\*.log`) but failed to open them because paths become corrupted (losing one backslash) between file discovery and opening. The fix converts UNC paths to Windows extended-length format (`\\?\UNC\server\share\path`) which bypasses path parsing issues and provides reliable file access for network shares.

#### Link to tracking issue
Fixes #44401

#### Testing

Personally tested in a Windows VM, trying to read logs from a network share.

Added tests for Windows path validation.

### CODE REVIEW

**Comment by andrzej-stencel** [comment]
Would love to also have @pjanotti take a look if possible 🙏

File: pkg/stanza/fileconsumer/file_windows.go [hunk 1]
```diff
@@ -7,8 +7,43 @@ package fileconsumer // import "github.com/open-telemetry/opentelemetry-collecto
...
+		return path, false
+	}
+
+	// Convert proper UNC paths (\\server\share) to extended-length format
+	if len(path) >= 2 && path[0] == '\\' && path[1] == '\\' {
+		return `\\?\UNC\` + filepath.Clean(path[2:]), false
+	}
+
+	// Handle corrupted UNC path that lost one backslash (\server\share)
+	// This can happen after certain path operations
```
Comment (pjanotti) [inline pkg/stanza/fileconsumer/file_windows.go]: Something like `\<dir>\<dir>\*.log` is a valid path on the current disk and it is possible that this will trigger errors.

Do you understand why the code is removing the double backslash in certain cases? It seems that this is the root of the issue.

File: pkg/stanza/fileconsumer/file_windows_test.go [hunk 2]
```diff
@@ -0,0 +1,58 @@
...
+		},
+		{
+			name:     "Already extended UNC path",
+			input:    `\\?\UNC\server\share\file.txt`,
+			expected: `\\?\UNC\server\share\file.txt`,
+		},
+		{
+			name:     "Corrupted UNC path (single backslash)",
+			input:    `\networkShare2\BLAM\Logs\stdout_46_2025.log`,
+			expected: `\\?\UNC\networkShare2\BLAM\Logs\stdout_46_2025.log`,
```
Comment (pjanotti) [inline pkg/stanza/fileconsumer/file_windows_test.go]: As mentioned on the other comment this can actually be a valid local path and likely will cause a different bug.

**Review by pjanotti — CHANGES_REQUESTED** [review]
Oi @paulojmdias - there is a specific path pattern that I'm worried. Per description it seems that there is some code prior to `os.Open` that can remove double backslashes and fixing that seems a safer fix. The issue is that `\<dir>\*.log` is a valid local path and currently that will be converted to a UNC path.

The safest fix is to avoid the incorrect removal of double backslashes - basically the code should preserve double backslashes when they are on the beginning of the path.

**Review by pjanotti — APPROVED** [review]
Thanks @paulojmdias!

**Comment by paulojmdias** [comment]
Thanks @pjanotti but I found another issue.

I'll move to draft until I fix it and I will ask you review again after 🙏

**Comment by pjanotti** [comment]
@paulojmdias do you know where the corruption is happening?

**Comment by paulojmdias** [comment]
@pjanotti I've improved the fix into the `finder` package where doublestar corrupts the paths, using the original pattern as the source of truth.

So, if the user configured a UNC path (`\\server\share\*.log`), we detect the double backslash in the pattern and restore it when doublestar returns a corrupted match. If they configured a local path (`\Logs\App\*.log` or `C:\...`), we leave it unchanged.

I've tested both UNC paths and local paths like your example in a Windows VM, and added test coverage to prevent regressions.

PTAL, and let me know if it makes sense to you. Marked again as ready for review

File: pkg/stanza/fileconsumer/file.go [hunk 3]
```diff
@@ -176,9 +176,14 @@ func (m *Manager) consume(ctx context.Context, paths []string) {
...
-	file, err := os.Open(path) // #nosec - operator must read in files defined by user
+	// Normalize the path to handle Windows UNC paths correctly
+	normalizedPath, wasCorrupted := normalizePath(path)
+	if wasCorrupted {
+		m.set.Logger.Debug("Detected and repaired corrupted UNC path", zap.String("original_path", path), zap.String("normalized_path", normalizedPath))
+	}
+	file, err := os.Open(normalizedPath) // #nosec - operator must read in files defined by user
 	if err != nil {
-		m.set.Logger.Error("Failed to open file", zap.Error(err))
+		m.set.Logger.Error("Failed to open file", zap.Error(err), zap.String("original_path", path), zap.String("normalized_path", normalizedPath))
```
Comment (pjanotti) [inline pkg/stanza/fileconsumer/file.go:186]: 👍🏼

**Review by pjanotti — APPROVED** [review]

**Comment by paulojmdias** [comment]
@andrzej-stencel could you please take a look ? 🙏

**Review by andrzej-stencel — APPROVED** [review]
Thank you @pjanotti for your review! And thanks @paulojmdias for the dilligence with this contribution.
