### PR TITLE
[chore][pkg/stanza] Fix goroutine leak in regex parser

### LINKED ISSUE #31093: [pkg/stanza/operator/parser/regex] Leaking goroutine when cache size is set to non-zero
### Component(s)

pkg/stanza

### Describe the issue you're reporting

While working on adding `goleak` checks to the `pkg/stanza/operator/parser/regex` package as a part of #30438, I found the following leak:
```
=== RUN   TestMemory
=== RUN   TestMemory/basic
--- PASS: TestMemory (0.00s)
    --- PASS: TestMemory/basic (0.00s)
PASS
goleak: Errors on successful test run: found unexpected goroutines:
[Goroutine 20 in state sleep, with time.Sleep on top of the stack:
time.Sleep(0x12a05f200)
	/usr/local/go/src/runtime/time.go:195 +0x125
github.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza/operator/parser/regex.(*atomicLimiter).init.func1.1()
	/Users/crobert/dev/opentelemetry-collector-contrib/pkg/stanza/operator/parser/regex/cache.go:162 +0xf8
created by github.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza/operator/parser/regex.(*atomicLimiter).init.func1 in goroutine 19
	/Users/crobert/dev/opentelemetry-collector-contrib/pkg/stanza/operator/parser/regex/cache.go:157 +0x56
]
```
(More tests are failing, but this is a good basic example of the leak)

The `regex` parser [has an in-memory cache](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/dcf66ce0a5a9a9cf804ce045fdef8d1401cc4d7c/pkg/stanza/operator/parser/regex/regex.go#L83) that starts an atomic rate limiter [upon initialization](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/dcf66ce0a5a9a9cf804ce045fdef8d1401cc4d7c/pkg/stanza/operator/parser/regex/cache.go#L30). This rate limiter [runs in a background goroutine indefinitely](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/dcf66ce0a5a9a9cf804ce045fdef8d1401cc4d7c/pkg/stanza/operator/parser/regex/cache.go#L157), without any way to stop it.

We need to add a `Stop` method that can be called during components' shutdown that properly stops this goroutine.

### PR DESCRIPTION
**Pull request by djaglowski**
Fixes https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/31093

### CODE REVIEW

File: pkg/stanza/operator/parser/regex/cache.go [hunk 1]
```diff
@@ -154,14 +161,21 @@ var _ limiter = &atomicLimiter{count: &atomic.Uint64{}}
 func (l *atomicLimiter) init() {
 	// start the reset go routine once
 	l.start.Do(func() {
+		l.done = make(chan struct{})
```
Comment (mx-psi) [inline pkg/stanza/operator/parser/regex/cache.go:164]: nit: I guess I would have expected this to happen within `newStartedAtomicLimiter`

**Review by mx-psi — APPROVED** [review]

**Review by crobert-1 — APPROVED** [review]
Thanks for fixing this!

File: pkg/stanza/operator/parser/regex/cache.go (hunk 1 above)
Comment (djaglowski) [reply pkg/stanza/operator/parser/regex/cache.go]: Good call. I had it there initially but moved it because of one test with a strange setup. I've moved it back and handled the test differently.

**Review by mx-psi — APPROVED** [review]
