### PR TITLE
[cmd/telemetrygen] fix status-code args default value

### LINKED ISSUE #25849: Flaky e2e tests: failed to receive 128 entries
### Component(s)

_No response_

### Describe the issue you're reporting

```
=== RUN   TestE2E
    e2e_test.go:495: 
        	Error Trace:	/home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/processor/k8sattributesprocessor/e2e_test.go:495
        	            				/home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/processor/k8sattributesprocessor/e2e_test.go:83
        	Error:      	Condition never satisfied
        	Test:       	TestE2E
        	Messages:   	failed to receive 128 entries,  received 0 metrics, 0 traces, 0 logs in 3 minutes
W08[16](https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/5884286401/job/15958943828#step:14:17) 22:23:04.[17](https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/5884286401/job/15958943828#step:14:18)9271   [19](https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/5884286401/job/15958943828#step:14:20)566 warnings.go:70] child pods are preserved by default when jobs are deleted; set propagationPolicy=Background to remove them or set propagationPolicy=Orphan to suppress this warning
W0816 22:23:04.380233   19566 warnings.go:70] child pods are preserved by default when jobs are deleted; set propagationPolicy=Background to remove them or set propagationPolicy=Orphan to suppress this warning
W0816 [22](https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/5884286401/job/15958943828#step:14:23):[23](https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/5884286401/job/15958943828#step:14:24):04.578882   19566 warnings.go:70] child pods are preserved by default when jobs are deleted; set propagationPolicy=Background to remove them or set propagationPolicy=Orphan to suppress this warning
--- FAIL: TestE2E (194.01s)
```

https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/5884286401/job/15958943828#step:14:218
https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/5883079006/job/15955266680#step:14:218
https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/5883974046/job/15958005648#step:14:218
https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/5883677972/job/15957116822#step:14:215
https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/5883554071/job/15956758376#step:14:218

### PR DESCRIPTION
**Pull request by fatsheep9146**
**Description:** 
Fix #25849

after adding more logs for failed telemetrygen pod, I found traces-job keeps failing with the error log 

```
Error: expected `status-code` to be one of (Unset, Error, Ok) or (0, 1, 2), got "Unset" instead
```

here is a failed run https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/5899236967/job/16005926116

I thinks this bug is brought in by the pr #24673 , the default value `Unset` for arg `status-code` is not a legal one, the legal one is `"Unset"`

### CODE REVIEW

File: cmd/telemetrygen/internal/traces/config.go [hunk 1]
```diff
@@ -26,7 +26,7 @@ func (c *Config) Flags(fs *pflag.FlagSet) {
 	fs.IntVar(&c.NumTraces, "traces", 1, "Number of traces to generate in each worker (ignored if duration is provided)")
 	fs.BoolVar(&c.PropagateContext, "marshal", false, "Whether to marshal trace context via HTTP headers")
 	fs.StringVar(&c.ServiceName, "service", "telemetrygen", "Service name to use")
-	fs.StringVar(&c.StatusCode, "status-code", "Unset", "Status code to use for the spans, one of (Unset, Error, Ok) or the equivalent integer (0,1,2)")
+	fs.StringVar(&c.StatusCode, "status-code", "", "Status code to use for the spans, one of (Unset, Error, Ok) or the equivalent integer (0,1,2)")
```
Comment (TylerHelmuth) [inline cmd/telemetrygen/internal/traces/config.go:29]: Should we provide a legal default value, like `0`?

Comment (fatsheep9146) [reply cmd/telemetrygen/internal/traces/config.go:29]: Ok, I test `0` locally. It is legal.

Comment (fatsheep9146) [reply cmd/telemetrygen/internal/traces/config.go]: Done

**Comment by fatsheep9146** [comment]
I think this pr can fix the #25849 , but may not fix all the problems.

**Review by songy23 — APPROVED** [review]
LGTM

File: cmd/telemetrygen/internal/traces/config.go [hunk 2]
```diff
@@ -26,7 +26,7 @@ func (c *Config) Flags(fs *pflag.FlagSet) {
 	fs.IntVar(&c.NumTraces, "traces", 1, "Number of traces to generate in each worker (ignored if duration is provided)")
 	fs.BoolVar(&c.PropagateContext, "marshal", false, "Whether to marshal trace context via HTTP headers")
 	fs.StringVar(&c.ServiceName, "service", "telemetrygen", "Service name to use")
-	fs.StringVar(&c.StatusCode, "status-code", "Unset", "Status code to use for the spans, one of (Unset, Error, Ok) or the equivalent integer (0,1,2)")
+	fs.StringVar(&c.StatusCode, "status-code", "0", "Status code to use for the spans, one of (Unset, Error, Ok) or the equivalent integer (0,1,2)")
```
Comment (codeboten) [inline cmd/telemetrygen/internal/traces/config.go:29]: I'm confused by why Unset doesn't work, can you open a separate issue to address this?

**Review by codeboten — APPROVED** [review]

File: cmd/telemetrygen/internal/traces/config.go (hunk 2 above)
Comment (fatsheep9146) [reply cmd/telemetrygen/internal/traces/config.go:29]: Ok, I will open a seperate pr.
