### PR TITLE
[receiver/prometheus] fix: use prometheus default config when no config given

### LINKED ISSUE #16538: Prometheus receiver panics if no configuration is given
### Component(s)

receiver/prometheus

## Description
Run the OpenTelemetry Collector with a prometheus receiver with no configuration settings. The collector panics.

## Expected Result
No panic - an error with a meaningful message and a exit code 1.

## Actual Result
Panics, see output

### Collector version

0.66.0

## Environment
OS: Mac OS X

### OpenTelemetry Collector configuration

```yaml
receivers:
    prometheus:
    otlp:
        protocols:
            grpc:
              endpoint: 0.0.0.0:4317

exporters:
    logging:

processors:
    batch:

extensions:
    health_check:
      endpoint: 0.0.0.0:13133
    pprof:
      endpoint: :1888
    zpages:
      endpoint: :55679

service:
    extensions: [pprof, zpages, health_check]
    pipelines:
      metrics:
        receivers: [prometheus]
        processors: [batch]
        exporters: [logging]
```

### Log output

```shell
2022-11-30T02:35:13.837Z        info    prometheusreceiver@v0.66.0/metrics_receiver.go:254      Starting discovery manager      {"kind": "receiver", "name": "prometheus", "pipeline": "metrics"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x2dfe84d]

goroutine 1 [running]:
github.com/open-telemetry/opentelemetry-collector-contrib/receiver/prometheusreceiver.gcInterval(...)
        /builds/o11y-gdi/splunk-otel-collector-releaser/.go/pkg/mod/github.com/open-telemetry/opentelemetry-collector-contrib/receiver/prometheusreceiver@v0.66.0/metrics_receiver.go:302
github.com/open-telemetry/opentelemetry-collector-contrib/receiver/prometheusreceiver.(*pReceiver).initPrometheusComponents(0xc0010078c0, {0x590d698?, 0xc001372300?}, {0x59111e0?, 0xc000fa26a8}, {0x58cd140, 0xc0007331c0?})
        /builds/o11y-gdi/splunk-otel-collector-releaser/.go/pkg/mod/github.com/open-telemetry/opentelemetry-collector-contrib/receiver/prometheusreceiver@v0.66.0/metrics_receiver.go:273 +0x16d
github.com/open-telemetry/opentelemetry-collector-contrib/receiver/prometheusreceiver.(*pReceiver).Start(0xc0010078c0, {0x4f1c2f0?, 0xc000134000?}, {0x59111e0, 0xc000fa26a8})
        /builds/o11y-gdi/splunk-otel-collector-releaser/.go/pkg/mod/github.com/open-telemetry/opentelemetry-collector-contrib/receiver/prometheusreceiver@v0.66.0/metrics_receiver.go:89 +0xce
go.opentelemetry.io/collector/service/internal/pipelines.(*Pipelines).StartAll(0xc000f55630, {0x590d6d0, 0xc000134000}, {0x59111a8?, 0xc000fdb7a0})
        /builds/o11y-gdi/splunk-otel-collector-releaser/.go/pkg/mod/go.opentelemetry.io/collector@v0.66.0/service/internal/pipelines/pipelines.go:103 +0x452
go.opentelemetry.io/collector/service.(*service).Start(0xc0000d1680, {0x590d6d0, 0xc000134000})
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by ymtdzzz**
**Description:**
Fix #16538 . Current implementation doesn't take into consideration of the config's `GlobalConfig` can be `nil`. ( Ex. https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/receiver/prometheusreceiver/metrics_receiver.go#L302 )
When no configuration given, I made to use [prometheus' default configuration](https://github.com/prometheus/prometheus/blob/main/config/config.go#L144-L148) to avoid panic.

**Testing:**
- Add an additional assertion to `TestCreateReceiver()` to make sure that `GlobalConfig` can't be `nil`

**Documentation:**
No docs added.

### CODE REVIEW

File: receiver/prometheusreceiver/factory.go [hunk 1]
```diff
@@ -54,5 +55,9 @@ func createMetricsReceiver(
 	cfg component.Config,
 	nextConsumer consumer.Metrics,
 ) (component.MetricsReceiver, error) {
-	return newPrometheusReceiver(set, cfg.(*Config), nextConsumer, featuregate.GetRegistry()), nil
+	c := cfg.(*Config)
+	if c.PrometheusConfig == nil {
```
Comment (dashpole) [inline receiver/prometheusreceiver/factory.go:59]: should we do this in createDefaultConfig instead?  That way we still get global defaults even if the config itself is set.

Comment (ymtdzzz) [reply receiver/prometheusreceiver/factory.go]: thanks for your review, @dashpole . I made a change to move this to `createDefaultConfig()` .

File: receiver/prometheusreceiver/factory.go [hunk 2]
```diff
@@ -45,6 +46,9 @@ func NewFactory() component.ReceiverFactory {
 func createDefaultConfig() component.Config {
 	return &Config{
 		ReceiverSettings: config.NewReceiverSettings(component.NewID(typeStr)),
+		PrometheusConfig: &promconfig.Config{
+			GlobalConfig: promconfig.DefaultGlobalConfig,
+		},
```
Comment (dashpole) [inline receiver/prometheusreceiver/factory.go:51]:
```suggestion
		PrometheusConfig: &promconfig.DefaultConfig
```

Comment (ymtdzzz) [reply receiver/prometheusreceiver/factory.go:51]: @dashpole 
suggested change will fail the tests because the struct `promconfig.DefaultConfig` directed by the pointer will be shared through the test (and it seems to be modified in [here](https://github.com/ymtdzzz/opentelemetry-collector-contrib/blob/3d0d925f1722fc5ded544bd02953c4fbd564b6bd/receiver/prometheusreceiver/config.go#L280) ).

test fail logs (with debug print)
```
$ go test -race -timeout 30
0s --tags="" -run 'TestRejectUnsupportedPrometheusFeatures|TestNonExistentAuthCredentialsFile' ./... -v
=== RUN   TestRejectUnsupportedPrometheusFeatures
--- PASS: TestRejectUnsupportedPrometheusFeatures (0.01s)
=== RUN   TestNonExistentAuthCredentialsFile
want(prefix): error checking authorization credentials file "/nonexistentauthcredentialsfile"
got: unsupported features:
	alert_config.alertmanagers
	alert_config.relabel_configs
	remote_read
	remote_write
	rule_files
    config_test.go:188: 
        	Error Trace:	/home/ymtdzzz/development/github.com/ymtdzzz/opentelemetry-collector-contrib/receiver/prometheusreceiver/config_test.go:188
        	Error:      	Should be true
        	Test:       	TestNonExistentAuthCredentialsFile
--- FAIL: TestNonExistentAuthCredentialsFile (0.00s)
FAIL
FAIL	github.com/open-telemetry/opentelemetry-collector-contrib/receiver/prometheusreceiver	0.109s
testing: warning: no tests to run
PASS
ok  	github.com/open-telemetry/opentelemetry-collector-contrib/receiver/prometheusreceiver/internal	(cached) [no tests to run]
FAIL
```

to pass the tests (and avoid the risk of conflicts), we should create new one in every `createDefaultConfig()` calls.

```golang
	return &Config{
		ReceiverSettings: config.NewReceiverSettings(component.NewID(typeStr)),
		PrometheusConfig: &promconfig.Config{
			GlobalConfig: promconfig.DefaultGlobalConfig,
		},
	}
// Or
	pdcfg := promconfig.DefaultConfig
	return &Config{
		ReceiverSettings: config.NewReceiverSettings(component.NewID(typeStr)),
		PrometheusConfig: &pdcfg,
	}
```

Comment (dashpole) [reply receiver/prometheusreceiver/factory.go:51]: Does the same apply to the current code if someone overrides `GlobalConfig` in their config?

Comment (ymtdzzz) [reply receiver/prometheusreceiver/factory.go:51]: @dashpole 

> if someone overrides `GlobalConfig` in their config?

In that case, only parameters specified in their config will be overridden but `promconfig.DefaultGlobalConfig` itself will not be modified because it's not a pointer.
In fact, `Unmarshal()` is called only once at startup, so this "conflict" seems to be a test-only issue.

config:
```yaml
receivers:
  prometheus:
    config:
      global:
        scrape_interval: 10m
      scrape_configs:
        - job_name: 'otel-collector'
          scrape_interval: 5s
          static_configs:
            - targets: ['0.0.0.0:8888']
```

result of `Unmarshal()`:

```
otel-col  | ======= before unmarshall =======
otel-col  | config: &{{{{prometheus } <nil>}} global:
otel-col  |   scrape_interval: 1m
otel-col  |   scrape_timeout: 10s
otel-col  |   evaluation_interval: 1m
otel-col  |  0s 0 false  <nil> <nil>}
otel-col  | -----------
otel-col  | promconfig.DefaultGlobalConfig: global:
otel-col  |   scrape_interval: 1m
otel-col  |   scrape_timeout: 10s
otel-col  |   evaluation_interval: 1m

otel-col  | ======= after unmarshall =======
otel-col  | config: &{{{{prometheus } <nil>}} global:
otel-col  |   scrape_interval: 10m // overridden by config
otel-col  |   scrape_timeout: 10s
otel-col  |   evaluation_interval: 1m
otel-col  | scrape_configs:
otel-col  | - job_name: otel-collector
otel-col  |   honor_timestamps: true
otel-col  |   scrape_interval: 5s
otel-col  |   scrape_timeout: 5s
otel-col  |   metrics_path: /metrics
otel-col  |   scheme: http
otel-col  |   follow_redirects: true
otel-col  |   enable_http2: true
otel-col  |   static_configs:
otel-col  |   - targets:
otel-col  |     - 0.0.0.0:8888
otel-col  |  0s 0 false  <nil> map[global:map[scrape_interval:10m] scrape_configs:[map[job_name:otel-collector scrape_interval:5s static_configs:[map[targets:[0.0.0.0:8888]]]]]]}
otel-col  | -----------
otel-col  | promconfig.DefaultGlobalConfig: global: // not modified
otel-col  |   scrape_interval: 1m
otel-col  |   scrape_timeout: 10s
otel-col  |   evaluation_interval: 1m
```

Comment (dashpole) [reply receiver/prometheusreceiver/factory.go:51]: Thanks for checking.

**Review by dashpole — APPROVED** [review]

**Review by codeboten — COMMENTED** [review]
Please rebase

**Comment by ymtdzzz** [comment]
@codeboten 
rebase done!

**Review by atoulme — APPROVED** [review]
Changes look good! Thank you for the fix. It looks like the build timed out, you'll need to force push to get it to build again.

**Review by Aneurysm9 — APPROVED** [review]
