### PR TITLE
[processor/transform] Fix basic config cache access

### LINKED ISSUE #38926: Valid processor config yields unexpected results
### Component(s)

processor/transform

## Description

The transform documentation mentions in the [Basic Config](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/processor/transformprocessor/README.md#basic-config) section that `log_statements` is a list consisting out of the individual expressions as strings.

This format, at least in my particular test, yields unexpected (and therefor wrong) results. It seems that for every line of the input file, a log is generated but each log has the content of the line of the `input.log` file

When the same configuration is converted to the [advanced configuration](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/processor/transformprocessor/README.md#advanced-config) style results are correct.

It is unclear where the difference comes from.

## Steps to Reproduce

create file `input.log` with following content:
```json
{"product": {"id": 1}, "proxy": {"id": 2}, "log": "first log"}
{"product": {"id": 10}, "proxy": {"id": 20}, "log": "second log"}
{"product": {"id": 10}, "proxy": {"id": 20}, "log": "third log"}
```
Apply the below mentioned configuration. 

### working processor config
Replace the `processors` section of the broken config with this and the result is what is expected.

```yaml
processors:
  transform/log:
    error_mode: propagate
    log_statements:
      - statements:
        - merge_maps(log.cache, ParseJSON(log.body), "upsert") where IsMatch(log.body, "^\\{")
        - set(log.body, log.cache["log"])
```

## Expected Result
`output.log` contains:

```json
{
  "resourceLogs": [
    {
      "resource": {},
      "scopeLogs": [
        {
          "scope": {},
          "logRecords": [
            {
              "observedTimeUnixNano": "1742847852280836180",
              "body": {
                "stringValue": "first log"
              },
              "attributes": [
                {
                  "key": "log.file.name",
                  "value": {
                    "stringValue": "input.log"
                  }
                }
              ],
              "traceId": "",
              "spanId": ""
            },
            {
              "observedTimeUnixNano": "1742847852280843519",
              "body": {
                "stringValue": "second log"
              },
              "attributes": [
                {
                  "key": "log.file.name",
                  "value": {
                    "stringValue": "input.log"
                  }
                }
              ],
              "traceId": "",
              "spanId": ""
            },
            {
              "observedTimeUnixNano": "1742847852280844952",
              "body": {
                "stringValue": "third log"
              },
              "attributes": [
                {
                  "key": "log.file.name",
                  "value": {
                    "stringValue": "input.log"
                  }
                }
              ],
              "traceId": "",
              "spanId": ""
            }
          ]
        }
      ]
    }
  ]
}
```

## Actual Result
`output.log` contains: 

```json
{
  "resourceLogs": [
    {
      "resource": {},
      "scopeLogs": [
        {
          "scope": {},
          "logRecords": [
            {
              "observedTimeUnixNano": "1742846994264031175",
              "body": {
                "stringValue": "third log"
              },
              "attributes": [
                {
                  "key": "log.file.name",
                  "value": {
                    "stringValue": "input.log"
                  }
                }
              ],
              "traceId": "",
              "spanId": ""
            },
            {
              "observedTimeUnixNano": "1742846994264052451",
              "body": {
                "stringValue": "third log"
              },
              "attributes": [
                {
                  "key": "log.file.name",
                  "value": {
                    "stringValue": "input.log"
                  }
                }
              ],
              "traceId": "",
              "spanId": ""
            },
            {
              "observedTimeUnixNano": "1742846994264054274",
              "body": {
                "stringValue": "third log"
              },
              "attributes": [
                {
                  "key": "log.file.name",
                  "value": {
                    "stringValue": "input.log"
                  }
                }
              ],
              "traceId": "",
              "spanId": ""
            }
          ]
        }
      ]
    }
  ]
}
```

### Collector version

v0.120.0 and latest

## Environment
official docker images

```
$ docker images
REPOSITORY                             TAG       IMAGE ID       CREATED       SIZE
otel/opentelemetry-collector-contrib   latest    49ab54809761   5 days ago    329MB
otel/opentelemetry-collector-contrib   0.120.0   c67f607546f4   4 weeks ago   315MB
```

### OpenTelemetry Collector configuration
(causes the faulty results)

```yaml
receivers:
  filelog:
    type: file_input
    include:
      - /input.log
    start_at: beginning

processors:
  transform/log:
    error_mode: propagate
    log_statements:
      - merge_maps(log.cache, ParseJSON(log.body), "upsert") where IsMatch(log.body, "^\\{")
      - set(log.body, log.cache["log"])

exporters:
  file/local:
    path: ./output.log

service:
  pipelines:
    logs:
      receivers:
        - filelog
      processors:
        - transform/log
      exporters:
        - file/local
```

### Log output

```shell
n/a
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by edmocosta**
#### Description

This PR removes the shared cache logic we introduced to support Basic Config statements, and changes the approach to group all Basic config statements together into the same sharing-cache `common.ContextStatements`, embracing the limitation of not being able to infer the context depending on the user's statements (similar to the advanced config). 
To help with that limitation, the context inferrer validation was improved, and it now returns specific errors that better describe why it couldn't infer a valid context.

This PR also introduces a **breaking change**, that consists in forcing users to use either basic or advanced configuration, for example, mixed configurations like the following won't be valid anymore, and it will require users to use only one style:

```yaml
log_statements:
 - set(resource.attributes["foo"], "foo")
 - statements:
   - set(resource.attributes["bar"], "bar")
```

---
Another PR will be open for removing the `WithCache` option from all OTTL contexts.

#### Link to tracking issue
Fixes https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/38926

#### Testing
Unit tests

#### Documentation
Updated README

### CODE REVIEW

File: processor/transformprocessor/config.go [hunk 1]
```diff
@@ -93,17 +92,25 @@ func (c *Config) Unmarshal(conf *confmap.Conf) error {
...
+		for _, value := range values {
+			// Array of strings means it's a basic configuration style
 			if reflect.TypeOf(value).Kind() == reflect.String {
-				stmts = append(stmts, map[string]any{"statements": []any{value}})
-				flatContextStatements[fieldName] = append(flatContextStatements[fieldName], i)
+				basicStatements = append(basicStatements, value)
 			} else {
-				stmts = append(stmts, value)
+				if len(basicStatements) > 0 {
+					return errors.New("mixed configuration styles are not supported, please use either Basic or Advanced configurations")
```
Comment (TylerHelmuth) [inline processor/transformprocessor/config.go:103]:
```suggestion
					return errors.New("configuring multiple configuration styles is not supported, please use only Basic configuration or only Advanced configuration")
```

**Review by TylerHelmuth — COMMENTED** [review]
@edmocosta can you add a new test somewhere, either in the transformprocessor or OTTL's e2e tests, for

```yaml
log_statements:
      - merge_maps(log.cache, ParseJSON(log.body), "upsert") where IsMatch(log.body, "^\\{")
      - set(log.body, log.cache["log"])
```

**Comment by edmocosta** [comment]
Hi @TylerHelmuth, thanks for reviewing, I've added a few tests that although are using different statements, does check the exactly same condition.

**Review by TylerHelmuth — APPROVED** [review]
