### PR TITLE
[chore] fix flaky ssh receiver tests

### LINKED ISSUE #18536: Flaky test: sshreceiver/TestScraper
### Component(s)

receiver/sshcheck

### Describe the issue you're reporting

See https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/4164947978/jobs/7207502717#step:9:4149

```
=== RUN   TestScraper/metrics_golden
    scraper_test.go:134: 
        	Error Trace:	/home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/receiver/sshcheckreceiver/scraper_test.go:134
        	Error:      	Received unexpected error:
        	            	resource "map[]": scope "otelcol/sshcheckreceiver": number of metrics doesn't match expected: 2, actual: 3
        	Test:       	TestScraper/metrics_golden
=== RUN   TestScraper/metrics_golden_sftp
    scraper_test.go:134: 
        	Error Trace:	/home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/receiver/sshcheckreceiver/scraper_test.go:134
        	Error:      	Received unexpected error:
        	            	resource "map[]": scope "otelcol/sshcheckreceiver": number of metrics doesn't match expected: 4, actual: 5
        	Test:       	TestScraper/metrics_golden_sftp
=== RUN   TestScraper/cannot_authenticate
    scraper_test.go:134: 
        	Error Trace:	/home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/receiver/sshcheckreceiver/scraper_test.go:134
        	Error:      	Received unexpected error:
        	            	resource "map[]": scope "otelcol/sshcheckreceiver": number of metrics doesn't match expected: 2, actual: 3
        	Test:       	TestScraper/cannot_authenticate
=== RUN   TestScraper/invalid_endpoint
    scraper_test.go:134: 
        	Error Trace:	/home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/receiver/sshcheckreceiver/scraper_test.go:134
        	Error:      	Received unexpected error:
        	            	resource "map[]": scope "otelcol/sshcheckreceiver": number of metrics doesn't match expected: 2, actual: 3
        	Test:       	TestScraper/invalid_endpoint
--- FAIL: TestScraper (4.89s)
```

### LINKED ISSUE #19473: [sshcheckreceiver] Flaky test
### Component(s)

receiver/sshcheck

### What happened?

See https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/4402181833/jobs/7709087497
```
=== RUN   TestScraper/metrics_golden
    scraper_test.go:133: 
        	Error Trace:	/home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/receiver/sshcheckreceiver/scraper_test.go:133
        	Error:      	Received unexpected error:
        	            	resource "map[]": scope "otelcol/sshcheckreceiver": number of metrics doesn't match expected: 2, actual: 3
        	Test:       	TestScraper/metrics_golden
=== RUN   TestScraper/metrics_golden_sftp
    scraper_test.go:133: 
        	Error Trace:	/home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/receiver/sshcheckreceiver/scraper_test.go:133
        	Error:      	Received unexpected error:
        	            	resource "map[]": scope "otelcol/sshcheckreceiver": number of metrics doesn't match expected: 4, actual: 5
        	Test:       	TestScraper/metrics_golden_sftp
=== RUN   TestScraper/cannot_authenticate
    scraper_test.go:133: 
        	Error Trace:	/home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/receiver/sshcheckreceiver/scraper_test.go:133
        	Error:      	Received unexpected error:
        	            	resource "map[]": scope "otelcol/sshcheckreceiver": number of metrics doesn't match expected: 2, actual: 3
        	Test:       	TestScraper/cannot_authenticate
=== RUN   TestScraper/invalid_endpoint
    scraper_test.go:133: 
        	Error Trace:	/home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/receiver/sshcheckreceiver/scraper_test.go:133
        	Error:      	Received unexpected error:
        	            	resource "map[]": scope "otelcol/sshcheckreceiver": number of metrics doesn't match expected: 2, actual: 3
        	Test:       	TestScraper/invalid_endpoint
--- FAIL: TestScraper (5.46s)
    --- FAIL: TestScraper/metrics_golden (0.00s)
    --- FAIL: TestScraper/metrics_golden_sftp (0.00s)
    --- FAIL: TestScraper/cannot_authenticate (0.00s)
    --- FAIL: TestScraper/invalid_endpoint (0.00s)
```

### Collector version

latest

### Environment information

_No response_

### OpenTelemetry Collector configuration

_No response_

### Log output

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by codeboten**
Use the port mapping rather than the hardcoded port 2222.

Fixes #18536
Fixes #19473

### CODE REVIEW

File: receiver/sshcheckreceiver/scraper_test.go [hunk 1]
```diff
@@ -64,9 +65,17 @@ func setupSSHServer(t *testing.T) *opensshContainer {
 		Started:          true,
 	})
 	require.NoError(t, err)
+	require.NotNil(t, container)
 
-	endpoint, err := container.PortEndpoint(ctx, "2222", "")
+	mappedPort, err := container.MappedPort(ctx, "2222")
+	print(mappedPort)
```
Comment (atoulme) [inline receiver/sshcheckreceiver/scraper_test.go:71]:
```suggestion
```

**Review by codeboten — COMMENTED** [review]
Thanks @atoulme

**Review by atoulme — APPROVED** [review]
