### PR TITLE
[cmd/opampsupervisor] Fix restart delay when agent process exits unexpectedly

### LINKED ISSUE #27891: Restart delay not working when agent process exits unexpectedly
### Component(s)

cmd/opampsupervisor

## Description

When the supervisor fails to start the collector, it will log that it will restart the collector in a bit, but it doesn't actually wait 5s to restart and instead logs the message over and over.

## Steps to Reproduce

Send a bad config from an OpAMP server to the supervisor. The collector will fail to start and exit. The supervisor will be caught in a tight loop logging that it will "restart in a bit..."

## Expected Result

The supervisor will wait 5s and then attempt to restart the collector.

## Actual Result

The supervisor logs this message over and over.

```
2023-10-18T21:51:28.581-0400	DEBUG	supervisor/supervisor.go:619	Agent process exited unexpectedly. Will restart in a bit...	{"pid": 46996, "exit_code": 1}
2023-10-18T21:51:28.581-0400	DEBUG	supervisor/supervisor.go:619	Agent process exited unexpectedly. Will restart in a bit...	{"pid": 46996, "exit_code": 1}
2023-10-18T21:51:28.581-0400	DEBUG	supervisor/supervisor.go:619	Agent process exited unexpectedly. Will restart in a bit...	{"pid": 46996, "exit_code": 1}
2023-10-18T21:51:28.581-0400	DEBUG	supervisor/supervisor.go:619	Agent process exited unexpectedly. Will restart in a bit...	{"pid": 46996, "exit_code": 1}
2023-10-18T21:51:28.581-0400	DEBUG	supervisor/supervisor.go:619	Agent process exited unexpectedly. Will restart in a bit...	{"pid": 46996, "exit_code": 1}
2023-10-18T21:51:28.581-0400	DEBUG	supervisor/supervisor.go:619	Agent process exited unexpectedly. Will restart in a bit...	{"pid": 46996, "exit_code": 1}
2023-10-18T21:51:28.581-0400	DEBUG	supervisor/supervisor.go:619	Agent process exited unexpectedly. Will restart in a bit...	{"pid": 46996, "exit_code": 1}
2023-10-18T21:51:28.581-0400	DEBUG	supervisor/supervisor.go:619	Agent process exited unexpectedly. Will restart in a bit...	{"pid": 46996, "exit_code": 1}
2023-10-18T21:51:28.581-0400	DEBUG	supervisor/supervisor.go:619	Agent process exited unexpectedly. Will restart in a bit...	{"pid": 46996, "exit_code": 1}
2023-10-18T21:51:28.581-0400	DEBUG	supervisor/supervisor.go:619	Agent process exited unexpectedly. Will restart in a bit...	{"pid": 46996, "exit_code": 1}
```

### Collector version

05ec3a2

## Environment
OS: m1 Mac
Compiler(if manually compiled): go1.21.3 darwin/arm64

### OpenTelemetry Collector configuration

_No response_

### Log output

_No response_

### Additional context

Based on a quick review of the code, when the Commander watch() method closes the `doneCh`, the Supervisor gets stuck in `case <-s.commander.Done()` as the closed channel will continue to produce signals.

Tested using the OpAMP Agent Extension PR
https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/16594

### PR DESCRIPTION
**Pull request by srikanthccv**
**Description:**

Reset should called only on stopped or expired timers with drained channels. If the timer already expired (and the channel was not cleared) it reads from the timer's channel to clear it.

**Link to tracking Issue:** Fixes https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/27891

**Testing:** <Describe what testing was performed and which tests were added.>

**Documentation:** <Describe the documentation added.>

### CODE REVIEW

File: cmd/opampsupervisor/supervisor/commander/commander.go [hunk 1]
```diff
@@ -52,6 +55,13 @@ func (c *Commander) Start(ctx context.Context) error {
 		return nil
 	}
 
+	if len(c.doneCh) > 0 {
+		<-c.doneCh
+	}
+	if len(c.exitCh) > 0 {
+		<-c.exitCh
+	}
```
Comment (BinaryFissionGames) [inline cmd/opampsupervisor/supervisor/commander/commander.go:63]: This might not be safe in concurrent situations (e.g. the len check passes, but some other goroutine receives between the len check and the receive)

Instead, I think we could just do a non-blocking receive and ditch the `if` statement here:
```go
select {
  case <-c.exitCh:
  default:
}
```

File: cmd/opampsupervisor/supervisor/commander/commander.go [hunk 2]
```diff
@@ -52,6 +55,13 @@ func (c *Commander) Start(ctx context.Context) error {
 		return nil
 	}
 
+	if len(c.doneCh) > 0 {
+		<-c.doneCh
+	}
```
Comment (BinaryFissionGames) [inline cmd/opampsupervisor/supervisor/commander/commander.go:60]: is draining the done channel necessary here? It seems like this channel is remade later in this function.

File: cmd/opampsupervisor/supervisor/commander/commander.go [hunk 3]
```diff
@@ -39,6 +40,8 @@ func NewCommander(logger *zap.Logger, cfg *config.Agent, args ...string) (*Comma
 		cfg:     cfg,
 		args:    args,
 		running: &atomic.Int64{},
+		doneCh:  make(chan struct{}, 1),
```
Comment (BinaryFissionGames) [inline cmd/opampsupervisor/supervisor/commander/commander.go:43]: I'm noticing that the channel is made buffered here, but in Start it's recreated as an unbuffered channel, I think it should be consistent (should the channel be initialized here or just in Start?)

File: cmd/opampsupervisor/supervisor/commander/commander.go (hunk 2 above)
Comment (srikanthccv) [reply cmd/opampsupervisor/supervisor/commander/commander.go:60]: Thanks for pointing out. It was supposed to be removed.

File: cmd/opampsupervisor/supervisor/commander/commander.go (hunk 1 above)
Comment (srikanthccv) [reply cmd/opampsupervisor/supervisor/commander/commander.go:63]: I am not sure if this has to be concurrent safe, If so, I think there might be other things to look into as well.

Comment (BinaryFissionGames) [reply cmd/opampsupervisor/supervisor/commander/commander.go]: Good point, I just assumed it was meant to be concurrent safe due to the use of atomics. 

I think the use of the `running` variable has to be re-examined at some point, because right now it's definitely not concurrent safe.

**Review by BinaryFissionGames — APPROVED** [review]
Tested this out, it resolves the issue.

File: cmd/opampsupervisor/supervisor/commander/commander.go [hunk 4]
```diff
@@ -52,6 +55,19 @@ func (c *Commander) Start(ctx context.Context) error {
 		return nil
 	}
 
+	if len(c.doneCh) > 0 {
```
Comment (evan-bradley) [inline cmd/opampsupervisor/supervisor/commander/commander.go:58]:
```suggestion
	// Drain channels in case there are no listeners that
	// drained messages from previous runs.
	if len(c.doneCh) > 0 {
```

File: cmd/opampsupervisor/supervisor/commander/commander.go (hunk 3 above)
Comment (evan-bradley) [inline cmd/opampsupervisor/supervisor/commander/commander.go:43]:
```suggestion
		// Buffer channels so we can send messages without blocking on listeners.
		doneCh:  make(chan struct{}, 1),
```

**Review by evan-bradley — APPROVED** [review]
Really excited to have this fixed, thanks.

I think the way we're handling channels is the best we can do, but looks a little funny. I just added a few suggestions to explain why we're doing what we are. If anyone else has ideas for more idiomatic ways to make these behave sensibly, I'm open to other suggestions.
