### PR TITLE
[receiver/postgresql] Fix race condition when capturing errors

### LINKED ISSUE #23026: [receiver/postgresql] Data race in integration test
https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/5152433056/jobs/9278601236?pr=23025

```
2023/06/02 06:25:04 github.com/testcontainers/testcontainers-go - Connected to docker: 
  Server Version: 20.10.24+azure-1
  API Version: 1.41
  Operating System: Ubuntu 22.04.2 LTS
  Total Memory: 6943 MB
2023/06/02 06:25:04 🐳 Creating container for image docker.io/testcontainers/ryuk:0.4.0
2023/06/02 06:25:04 ✅ Container created: e03fdd721822
2023/06/02 06:25:04 🐳 Starting container: e03fdd7[218](https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/5152433056/jobs/9278601236?pr=23025#step:5:219)22
2023/06/02 06:25:04 🚧 Waiting for container id e03fdd721822 image: docker.io/testcontainers/ryuk:0.4.0
2023/06/02 06:25:04 ✅ Container started: e03fdd721822
2023/06/02 06:25:13 🐳 Creating container for image 
2023/06/02 06:25:13 ✅ Container created: 3a1361361c3e
2023/06/02 06:25:13 🐳 Starting container: 3a1361361c3e
2023/06/02 06:25:13 🚧 Waiting for container id 3a1361361c3e image: d47de94e-3639-4174-a20f-75ac3da7457d:dcbec011-b335-4fb6-a8c0-1e37ca7fc95d
2023/06/02 06:25:17 ✅ Container started: 3a1361361c3e
2023/06/02 06:25:20 🐳 Terminating container: 3a1361361c3e
2023/06/02 06:25:20 🚫 Container terminated: 3a1361361c3e
2023/06/02 06:25:25 🐳 Creating container for image 
2023/06/02 06:25:25 ✅ Container created: 43e03206e0ce
2023/06/02 06:25:25 🐳 Starting container: 43e03206e0ce
2023/06/02 06:25:25 🚧 Waiting for container id 43e03206e0ce image: b28c110f-915b-421f-a30b-73f74c15689c:2cec60e6-4e6f-4a67-b5b9-fbdd831452ce
2023/06/02 06:25:25 ✅ Container started: 43e03206e0ce
==================
WARNING: DATA RACE
Read at 0x00c000246480 by goroutine 324:
  go.opentelemetry.io/collector/receiver/scrapererror.(*ScrapeErrors).AddPartial()
      /home/runner/go/pkg/mod/go.opentelemetry.io/collector/receiver@v0.78.3-0.20230525165144-87dd85a6c034/scrapererror/scrapeerror.go:18 +0x30a
  github.com/open-telemetry/opentelemetry-collector-contrib/receiver/postgresqlreceiver.(*postgreSQLScraper).retrieveDatabaseSize()
      /home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/receiver/postgresqlreceiver/scraper.go:333 +0x2b3
  github.com/open-telemetry/opentelemetry-collector-contrib/receiver/postgresqlreceiver.(*postgreSQLClient).getDatabaseSize()
      /home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/receiver/postgresqlreceiver/client.go:189 +0x10c
  github.com/open-telemetry/opentelemetry-collector-contrib/receiver/postgresqlreceiver.(*postgreSQLScraper).retrieveDatabaseSize()
      /home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/receiver/postgresqlreceiver/scraper.go:330 +0x113
  github.com/open-telemetry/opentelemetry-collector-contrib/receiver/postgresqlreceiver.(*postgreSQLScraper).retrieveDBMetrics.func2()
      /home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/receiver/postgresqlreceiver/scraper.go:128 +0x10b

Previous write at 0x00c000246480 by goroutine 323:
  go.opentelemetry.io/collector/receiver/scrapererror.(*ScrapeErrors).AddPartial()
      /home/runner/go/pkg/mod/go.opentelemetry.io/collector/receiver@v0.78.3-0.20230525165144-87dd85a6c034/scrapererror/scrapeerror.go:18 +0x244
  go.opentelemetry.io/collector/receiver/scraperhelper.(*controller).scrapeMetricsAndReport()
      /home/runner/go/pkg/mod/go.opentelemetry.io/collector/receiver@v0.78.3-0.20230525165144-87dd85a6c034/scraperhelper/scrapercontroller.go:198 +0x34d
  go.opentelemetry.io/collector/receiver/scraperhelper.(*controller).startScraping.func1()
      /home/runner/go/pkg/mod/go.opentelemetry.io/collector/receiver@v0.78.3-0.20230525165144-87dd85a6c034/scraperhelper/scrapercontroller.go:180 +0x184
  github.com/open-telemetry/opentelemetry-collector-contrib/receiver/postgresqlreceiver.(*postgreSQLScraper).collectWalAge()
      /home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/receiver/postgresqlreceiver/scraper.go:289 +0xa1
  github.com/open-telemetry/opentelemetry-collector-contrib/receiver/postgresqlreceiver.(*postgreSQLScraper).scrape()
      /home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/receiver/postgresqlreceiver/scraper.go:110 +0xafe
  github.com/open-telemetry/opentelemetry-collector-contrib/receiver/postgresqlreceiver.(*postgreSQLScraper).collectBGWriterStats()
      /home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/receiver/postgresqlreceiver/scraper.go:[220](https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/5152433056/jobs/9278601236?pr=23025#step:5:221) +0xa1
  github.com/open-telemetry/opentelemetry-collector-contrib/receiver/postgresqlreceiver.(*postgreSQLScraper).scrape()
      /home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/receiver/postgresqlreceiver/scraper.go:109 +0xac4
  github.com/open-telemetry/opentelemetry-collector-contrib/receiver/postgresqlreceiver.(*postgreSQLScraper).collectIndexes()
      /home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/receiver/postgresqlreceiver/scraper.go:197 +0xc4
  github.com/open-telemetry/opentelemetry-collector-contrib/receiver/postgresqlreceiver.(*postgreSQLScraper).scrape()
      /home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/receiver/postgresqlreceiver/scraper.go:105 +0x11db
  github.com/open-telemetry/opentelemetry-collector-contrib/receiver/postgresqlreceiver.(*postgreSQLScraper).collectTables()
      /home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/receiver/postgresqlreceiver/scraper.go:156 +0x2d7
  github.com/open-telemetry/opentelemetry-collector-contrib/receiver/postgresqlreceiver.(*postgreSQLClient).getBlocksReadByTable()
      /home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/receiver/postgresqlreceiver/client.go:293 +0xc4
  github.com/open-telemetry/opentelemetry-collector-contrib/receiver/postgresqlreceiver.(*postgreSQLScraper).collectTables()
      /home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/receiver/postgresqlreceiver/scraper.go:151 +0xc1
  github.com/open-telemetry/opentelemetry-collector-contrib/receiver/postgresqlreceiver.(*postgreSQLScraper).scrape()
      /home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/receiver/postgresqlreceiver/scraper.go:102 +0x1164
  github.com/open-telemetry/opentelemetry-collector-contrib/receiver/postgresqlreceiver.(*postgreSQLScraper).collectIndexes()
      /home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/receiver/postgresqlreceiver/scraper.go:197 +0xc4
  github.com/open-telemetry/opentelemetry-collector-contrib/receiver/postgresqlreceiver.(*postgreSQLScraper).scrape()
      /home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/receiver/postgresqlreceiver/scraper.go:105 +0x11db
  github.com/open-telemetry/opentelemetry-collector-contrib/receiver/postgresqlreceiver.(*postgreSQLScraper).collectTables()
      /home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/receiver/postgresqlreceiver/scraper.go:156 +0x2d7
  github.com/open-telemetry/opentelemetry-collector-contrib/receiver/postgresqlreceiver.(*postgreSQLClient).getBlocksReadByTable()
      /home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/receiver/postgresqlreceiver/client.go:293 +0xc4
  github.com/open-telemetry/opentelemetry-collector-contrib/receiver/postgresqlreceiver.(*postgreSQLScraper).collectTables()
      /home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/receiver/postgresqlreceiver/scraper.go:151 +0xc1
  github.com/open-telemetry/opentelemetry-collector-contrib/receiver/postgresqlreceiver.(*postgreSQLScraper).scrape()
      /home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/receiver/postgresqlreceiver/scraper.go:102 +0x1164
  github.com/open-telemetry/opentelemetry-collector-contrib/receiver/postgresqlreceiver.(*postgreSQLScraper).scrape-fm()
      <autogenerated>:1 +0x4d
  go.opentelemetry.io/collector/receiver/scraperhelper.ScrapeFunc.Scrape()
      /home/runner/go/pkg/mod/go.opentelemetry.io/collector/receiver@v0.78.3-0.20[230](https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/5152433056/jobs/9278601236?pr=23025#step:5:231)525165144-87dd85a6c034/scraperhelper/scraper.go:20 +0x6f
  go.opentelemetry.io/collector/receiver/scraperhelper.(*baseScraper).Scrape()
      <autogenerated>:1 +0x29
  go.opentelemetry.io/collector/receiver/scraperhelper.(*controller).scrapeMetricsAndReport()
      /home/runner/go/pkg/mod/go.opentelemetry.io/collector/receiver@v0.78.3-0.20230525165144-87dd85a6c034/scraperhelper/scrapercontroller.go:198 +0x34d
  go.opentelemetry.io/collector/receiver/scraperhelper.(*controller).startScraping.func1()
      /home/runner/go/pkg/mod/go.opentelemetry.io/collector/receiver@v0.78.3-0.20230525165144-87dd85a6c034/scraperhelper/scrapercontroller.go:180 +0x184
==================
2023/06/02 06:25:31 🐳 Terminating container: 43e03206e0ce
2023/06/02 06:25:31 🚫 Container terminated: 43e03206e0ce
2023/06/02 06:25:37 🐳 Creating container for image 
2023/06/02 06:25:37 ✅ Container created: ec333a3df04e
2023/06/02 06:25:37 🐳 Starting container: ec333a3df04e
2023/06/02 06:25:37 🚧 Waiting for container id ec333a3df04e image: 0c69a77c-a99b-430f-[873](https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/5152433056/jobs/9278601236?pr=23025#step:5:874)3-ada5680c5ed2:aedfb3e8-671b-47d2-b40d-f13c8415fd94
2023/06/02 06:25:41 ✅ Container started: ec333a3df04e
2023/06/02 06:25:44 🐳 Terminating container: ec333a3df04e
2023/06/02 06:25:44 🚫 Container terminated: ec333a3df04e
--- FAIL: TestIntegration (41.77s)
    --- FAIL: TestIntegration/multi_db (11.18s)
        testing.go:1319: race detected during execution of test
    testing.go:1319: race detected during execution of test
FAIL
```

### PR DESCRIPTION
**Pull request by djaglowski**
Resolves #23026 

Much of the scraping is handled by goroutines, but we were aggregating errors onto a non-threadsafe struct. I've wrapped the struct to make it threadsafe.

### CODE REVIEW

File: receiver/postgresqlreceiver/integration_test.go [hunk 1]
```diff
@@ -1,9 +1,6 @@
 // Copyright The OpenTelemetry Authors
 // SPDX-License-Identifier: Apache-2.0
 
-//go:build integration
-// +build integration
-
```
Comment (dmitryax) [inline receiver/postgresqlreceiver/integration_test.go:6]: We need a better way to run tests locally without removing it :)

Comment (djaglowski) [reply receiver/postgresqlreceiver/integration_test.go:6]: I'll follow up https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/22808 by proposing to rename the make target. I never remember the name offhand.

**Review by dmitryax — APPROVED** [review]

File: receiver/postgresqlreceiver/integration_test.go (hunk 1 above)
Comment (atoulme) [reply receiver/postgresqlreceiver/integration_test.go]: Screenshot 2023-06-02 at 10 05 27 AM
I end up checking that box in my IDE, though it looks like you run this test from CLI? I hope it helps.
