### PR TITLE
[translator/jaeger] For HTTP status codes in the 4xx range span status MUST be left unset in case of SpanKind.SERVER

### LINKED ISSUE #8273: jaeger span is in error if tag error=false AND http.status_code >=400
**Describe the bug**
If I have a tag http.status_code >=400 _and_ a tag error=false on my Span, a tag error=true gets added (so I now have two attributes error with one true and one false) and the overall status of the span switches to error with a tag otel.status_code = ERROR  
Short story: In my app, I don't want client errors to popup as span errors, I want that only for server errors, so I set the error tag explicitly and wish it to be respected at all times.

1. We don't want the http status to override an error explicitly set to false: this is a bug in my opinion and does not seem intended. 
    -  The bug is I think in [here](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/579334c559a687b6c41341b62e55a60732a2329c/pkg/translator/jaeger/jaegerproto_to_traces.go#L204) where stuff is set only if error=true
    - I may provide a PR for this but I don't have time before end of March so if you want to take care of it, thanks!
2.  There are no docs describing the behavior of automatically relying on the http status code to determine if the span is in error or not. The [README.md](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/receiver/jaegerreceiver/README.md) should have a section at the end describing the translations performed.
3.  There are no logs in the collector showing why the translation was performed, maybe in debug/info log there needs to be something, because here it took me a while to realize that http.status_code=400 was the culprit.

**Environment**
jaeger-client-cpp 0.6.0 -> otelcol-contrib 0.45.0 on jaeger receiver thrift_compact

### PR DESCRIPTION
**Pull request by frzifus**
Signed-off-by: Benedikt Bongartz <bongartz@klimlive.de>

**Description:** <Describe what has changed.>

This pr prevents the status code from being overwritten if the x error active is set to false.

**Link to tracking Issue:** <Issue number if applicable>
- Closes #8273

**Testing:** <Describe what testing was performed and which tests were added.>

-  Updated existing unit tests

**Documentation:** <Describe the documentation added.>
- Followed [specification/semantic_conventions/status](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/semantic_conventions/http.md#status)

### CODE REVIEW

File: pkg/translator/jaeger/jaegerproto_to_traces_test.go [hunk 1]
```diff
@@ -417,6 +417,15 @@ func TestSetInternalSpanStatus(t *testing.T) {
 			status:           errorStatus,
 			attrsModifiedLen: 1,
 		},
+		{
+			name: "do not set error if http.status_code >= 400 and error tag is set to false",
```
Comment (jpkrohling) [inline pkg/translator/jaeger/jaegerproto_to_traces_test.go:421]: I think the actual condition should be: we should not set any error tag if one is already present. The status code shouldn't matter. For instance, if we get a "200" but there's an "error=true" set by something else, we should respect that.

Comment (ecourreges-orange) [reply pkg/translator/jaeger/jaegerproto_to_traces_test.go:421]: I agree @jpkrohling that's what I wished for when I filed the issue.

**Comment by frzifus** [comment]
mh.. i did like to reopen this pr. But it seems ive no permission to do so. 

could you help @jpkrohling ?

File: pkg/translator/jaeger/jaegerproto_to_traces.go [hunk 2]
```diff
@@ -274,16 +274,17 @@ func setInternalSpanStatus(attrs pcommon.Map, dest ptrace.SpanStatus) {
 	statusExists := false
 
 	if errorVal, ok := attrs.Get(tracetranslator.TagError); ok {
+		statusCode = ptrace.StatusCodeOk
 		if errorVal.BoolVal() {
```
Comment (dmitryax) [inline pkg/translator/jaeger/jaegerproto_to_traces.go:278]: What if the attribute value is not of the boolean type? In this solution, we always take it as `error=false` which might be incorrect. I believe we should ignore any non-boolean values here. WDYT?

File: pkg/translator/jaeger/jaegerproto_to_traces.go [hunk 3]
```diff
@@ -274,16 +274,17 @@ func setInternalSpanStatus(attrs pcommon.Map, dest ptrace.SpanStatus) {
 	statusExists := false
 
 	if errorVal, ok := attrs.Get(tracetranslator.TagError); ok {
```
Comment (dmitryax) [inline pkg/translator/jaeger/jaegerproto_to_traces.go:276]: I would rather add type check here
```suggestion
	if errorVal, ok := attrs.Get(tracetranslator.TagError); ok && errorVal.Type() == pcommon.ValueTypeBool  {
```

**Review by dmitryax — COMMENTED** [review]
@frzifus thanks for the fix. could you please respond to the comments and rebase?

**Comment by frzifus** [comment]
ups seems my rebase messed things up...

File: pkg/translator/jaeger/jaegerproto_to_traces.go (hunk 2 above)
Comment (frzifus) [reply pkg/translator/jaeger/jaegerproto_to_traces.go]: sounds valid. i placed there an additional condition. :+1:

**Comment by dmitryax** [comment]
@frzifus it needs another rebase. Also please add a change log entry in `.chloggen`

File: pkg/translator/jaeger/jaegerproto_to_traces.go [hunk 4]
```diff
@@ -258,22 +258,24 @@ func jTagsToInternalAttributes(tags []model.KeyValue, dest pcommon.Map) {
 	}
 }
 
-func setInternalSpanStatus(attrs pcommon.Map, dest ptrace.SpanStatus) {
+func setInternalSpanStatus(attrs pcommon.Map, span ptrace.Span) {
+	dest := span.Status()
```
Comment (dmitryax) [inline pkg/translator/jaeger/jaegerproto_to_traces.go:262]: Why changing the signature?

Comment (frzifus) [reply pkg/translator/jaeger/jaegerproto_to_traces.go:262]: As far as i understood the spec, we doint set en error based on the http status code if the span kind is server.
`For HTTP status codes in the 4xx range span status MUST be left unset in case of SpanKind.SERVER and MUST be set to Error in case of SpanKind.CLIENT.`

So we do need to ignore things here, right?
https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/12753/files#diff-79ad71b7ff1af223e5f80a4d1865ea75dc8db830e0ffbda369be65d104fe9a65R311

File: pkg/translator/jaeger/jaegerproto_to_traces.go [hunk 5]
```diff
@@ -302,7 +304,11 @@ func setInternalSpanStatus(attrs pcommon.Map, dest ptrace.Status) {
 		// Fallback to introspecting if this span represents a failed HTTP
 		// request or response, but again, only do so if the `error` tag was
 		// not set to true and no explicit status was sent.
-		if code, err := getStatusCodeFromHTTPStatusAttr(httpCodeAttr); err == nil {
+		// For HTTP status codes in the 4xx range span status MUST be left unset
+		// in case of SpanKind.SERVER and MUST be set to Error in case of SpanKind.CLIENT.
+		// For HTTP status codes in the 5xx range, as well as any other code the client
+		// failed to interpret, span status MUST be set to Error.
+		if code, err := getStatusCodeFromHTTPStatusAttr(httpCodeAttr); span.Kind() == ptrace.SpanKindClient && err == nil {
```
Comment (dmitryax) [inline pkg/translator/jaeger/jaegerproto_to_traces.go:311]: I don't think it's correct logic here. Now we don't set error if span kind is server even for 5xx, but according to the spec we should, right? You can pass span kind to `getStatusCodeFromHTTPStatusAttr` and use it as condition only for 4xx codes.

File: pkg/translator/jaeger/jaegerproto_to_traces.go (hunk 4 above)
Comment (dmitryax) [reply pkg/translator/jaeger/jaegerproto_to_traces.go:262]: Makes sense now. Added another commend related to that

**Comment by dmitryax** [comment]
Please add a changelog entry

File: pkg/translator/jaeger/jaegerproto_to_traces.go [hunk 6]
```diff
@@ -258,22 +258,24 @@ func jTagsToInternalAttributes(tags []model.KeyValue, dest pcommon.Map) {
...
 
-	if errorVal, ok := attrs.Get(tracetranslator.TagError); ok {
+	if errorVal, ok := attrs.Get(tracetranslator.TagError); ok && errorVal.Type() == pcommon.ValueTypeBool {
+		statusCode = ptrace.StatusCodeOk
 		if errorVal.Bool() {
 			statusCode = ptrace.StatusCodeError
-			attrs.Remove(tracetranslator.TagError)
-			statusExists = true
+		}
+		attrs.Remove(tracetranslator.TagError)
```
Comment (jpkrohling) [inline pkg/translator/jaeger/jaegerproto_to_traces.go:272]: We should _not_ remove an attribute that has been explicitly added before us. Perhaps this is a 200 but an error occurred (the application might not be quite following REST principles).

The spec is a bit ambiguous here, as it states that it "must be left unset", but in this case, it was already set by something else (perhaps manually by developers? or using the attributes processor?).

File: pkg/translator/jaeger/jaegerproto_to_traces.go [hunk 7]
```diff
@@ -258,22 +258,24 @@ func jTagsToInternalAttributes(tags []model.KeyValue, dest pcommon.Map) {
...
 
-func setInternalSpanStatus(attrs pcommon.Map, dest ptrace.Status) {
+func setInternalSpanStatus(attrs pcommon.Map, span ptrace.Span) {
+	dest := span.Status()
 	statusCode := ptrace.StatusCodeUnset
 	statusMessage := ""
 	statusExists := false
 
-	if errorVal, ok := attrs.Get(tracetranslator.TagError); ok {
+	if errorVal, ok := attrs.Get(tracetranslator.TagError); ok && errorVal.Type() == pcommon.ValueTypeBool {
```
Comment (jpkrohling) [inline pkg/translator/jaeger/jaegerproto_to_traces.go:267]: If we do *not* see an error flag, we should try to calculate one, if it would yield to "true". What I have in mind is:

- if there's an error flag already, skip this logic altogether
- if the status code is >= 500 and there's no status code, set one to true

https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/semantic_conventions/http.md#status

File: pkg/translator/jaeger/jaegerproto_to_traces_test.go [hunk 8]
```diff
@@ -416,6 +416,15 @@ func TestSetInternalSpanStatus(t *testing.T) {
 			status:           errorStatus,
 			attrsModifiedLen: 1,
 		},
+		{
+			name: "do not set any error tag if one is already present",
+			attrs: map[string]interface{}{
+				tracetranslator.TagError:            true,
+				conventions.AttributeHTTPStatusCode: 404,
+			},
+			status:           errorStatus,
```
Comment (jpkrohling) [inline pkg/translator/jaeger/jaegerproto_to_traces_test.go:425]: I must have read the code wrongly, as I would have expected this test to have failed. Given this test passes, the behavior is validated. The only other case that needs to be tested (in another PR perhaps?) is to set the error tag if the status code is greater than 500 and no error tag is set yet.

File: pkg/translator/jaeger/jaegerproto_to_traces.go (hunk 7 above)
Comment (dmitryax) [reply pkg/translator/jaeger/jaegerproto_to_traces.go:267]: this is already being done below, that's why we have `statusExists` flag

File: pkg/translator/jaeger/jaegerproto_to_traces.go (hunk 6 above)
Comment (dmitryax) [reply pkg/translator/jaeger/jaegerproto_to_traces.go:272]: @jpkrohling So far we have been interchangeably treating jaeger `error` tag and OTel `StatusCode` in jaeger receiver/exporter with the exception that it worked only with error=true in the receiver due to the bug fixed in this PR. We set `error` jaeger tag back from the OTel `StatusCode` in the exporter https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/7e904d87e53c5051b1eed1b2bd5b96788b16a645/pkg/translator/jaeger/traces_to_jaegerproto.go#L192. If we leave the `error` tag as an additional OTel attribute, I believe it'll result into duplicated jaeger `error` tag in the exporter. The correctness tests will also likely fail.

I'd suggest to keep the existing behavior and remove the tag but submit a separate issue where we discuss if it needs to be removed. PR to that issue would need to be applied to both receiver and exporter. WDYT?

Comment (frzifus) [reply pkg/translator/jaeger/jaegerproto_to_traces.go]: the changes got reverted.

**Comment by frzifus** [comment]
Hi @dmitryax @jpkrohling, I have tried to address your comments. However, I am not sure if I have understood the conversions here correctly. Therefore, please review my changes carefully. :see_no_evil:. Would be very thankful for further feedback/guidance.

**Review by jpkrohling — APPROVED** [review]
I believe this is correct now.

**Comment by jpkrohling** [comment]
@dmitryax, would you like to take a final look, or can I merge it as is?

File: pkg/translator/jaeger/jaegerproto_to_traces.go [hunk 9]
```diff
@@ -258,12 +258,13 @@ func jTagsToInternalAttributes(tags []model.KeyValue, dest pcommon.Map) {
...
 		if errorVal.Bool() {
 			statusCode = ptrace.StatusCodeError
 			attrs.Remove(tracetranslator.TagError)
```
Comment (dmitryax) [inline pkg/translator/jaeger/jaegerproto_to_traces.go:270]: I don't believe this solution fully resolves the original bug. I think the OTel code must be always set if `error` tag is present, doesn't matter whether tag value is `true` or `false`. Similar to how it was done in the original solution. @jpkrohling please let me know if it makes sense.

```suggestion
		statusExists = true
		statusCode = ptrace.StatusCodeOk
		if errorVal.Bool() {
			statusCode = ptrace.StatusCodeError
			attrs.Remove(tracetranslator.TagError)
```

Comment (jpkrohling) [reply pkg/translator/jaeger/jaegerproto_to_traces.go:270]: That makes sense, but if I remember correctly, Jaeger interprets the presence of the error tag as an indication of error, no matter the value of the attribute. So, "error=false" means, to Jaeger, that an error occurred. I would argue that for this package, we should leave the data in a state that is semantically equivalent between the formats, even if it means removing this value.

Comment (dmitryax) [reply pkg/translator/jaeger/jaegerproto_to_traces.go:270]: Thanks for providing your feedback. In that case, the current fix is somehow in between. If Jaeger treats `error=false` as an error, https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/8273 is not a bug but an expected behavior. I'm good with the current solution.

**Review by dmitryax — APPROVED** [review]
