### PR TITLE
[exporter/elasticsearch] Handle edge cases in metrics grouping causing TSDB version_conflict_engine_exception

### LINKED ISSUE #38083: [exporter/elasticsearch] Sort and deduplicate attributes for metrics grouping
### Component(s)

exporter/elasticsearch

## Description

ECS and OTel mapping modes implement metrics grouping. They hash the attributes in the order as they are in the attribute maps. However, in the edge case where 2 set of attributes have the same key value pairs but in different orders, they will generate different hash, which will in turn create 2 documents for the same set of dimensions, resulting in version_conflict_engine_exception from TSDB.

OTel mode attributes need to be sorted. ECS mode attributes need to be sorted and deduplicated as attributes at different level are all propagated up to the top level.

### Collector version

v0.120.0

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

### OpenTelemetry Collector configuration

```yaml

```

### Log output

```shell

```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by carsonip**
#### Description

Fix 2 edge cases where metrics grouping were not done correctly.
 1. In ecs mode, metric grouping now considers data point attributes overwriting resource attributes.
 2. In ecs and otel mode, attributes are now sorted before hashing. Metrics with attributes but in different order are now grouped together.

Implementation:

- sort attributes
- split up resource, scope and dp hash computation for otel mode to avoid sorting and rehashing

#### Link to tracking issue
Fixes #38083

#### Testing

Added unit tests

### CODE REVIEW

File: exporter/elasticsearchexporter/metric_grouping.go [hunk 1]
```diff
@@ -35,30 +39,59 @@ func newDataPointHasher(mode MappingMode) dataPointHasher {
...
+}
 
-	mapHashExcludeReservedAttrs(hasher, resource.Attributes())
+func (h ecsDataPointHasher) hashCombined(resource pcommon.Resource, _ pcommon.InstrumentationScope, dp datapoints.DataPoint) uint32 {
+	merged := pcommon.NewMap()
+	merged.EnsureCapacity(resource.Attributes().Len() + dp.Attributes().Len())
+	resource.Attributes().CopyTo(merged)
+	// scope attributes are ignored in ECS mode
+	for k, v := range dp.Attributes().All() {
+		_ = merged.PutEmpty(k).FromRaw(v.AsRaw())
```
Comment (carsonip) [inline exporter/elasticsearchexporter/metric_grouping.go:66]: [to reviewer] There's no generic `map.Put` function and I'm reluctant to add a per-type switch case here, as it will not support new types if there's one in the future.

File: .chloggen/elasticsearchexporter_handle-metric-grouping-edge-cases.yaml [hunk 2]
```diff
@@ -0,0 +1,29 @@
...
+# A brief description of the change.  Surround your text with quotes ("") if it needs to start with a backtick (`).
+note: Handle edge cases in metrics grouping causing TSDB version_conflict_engine_exception
+
+# Mandatory: One or more tracking issues related to the change. You can use the PR number here if no issue exists.
+issues: [38083]
+
+# (Optional) One or more lines of additional information to render under the primary note.
+# These lines will be padded with 2 spaces and then inserted directly into the document.
+# Use pipe (|) for multiline entries.
+subtext: Fix 2 edge cases where metrics grouping were not done correctly.
```
Comment (lahsivjar) [inline .chloggen/elasticsearchexporter_handle-metric-grouping-edge-cases.yaml:18]:
```suggestion
subtext: Fix 2 edge cases where metrics grouping were not done correctly:
```

File: exporter/elasticsearchexporter/metric_grouping.go [hunk 3]
```diff
@@ -69,14 +102,23 @@ func (h otelDataPointHasher) hashDataPoint(resource pcommon.Resource, scope pcom
...
 
-// mapHashExcludeReservedAttrs is mapHash but ignoring some reserved attributes.
+func (h otelDataPointHasher) hashCombined(_ pcommon.Resource, _ pcommon.InstrumentationScope, _ datapoints.DataPoint) uint32 {
+	return 0
+}
+
+// mapHashSortedExcludeReservedAttrs is mapHash but ignoring some reserved attributes and is independent of order in Map.
 // e.g. index is already considered during routing and DS attributes do not need to be considered in hashing
-func mapHashExcludeReservedAttrs(hasher hash.Hash, m pcommon.Map, extra ...string) {
+func mapHashSortedExcludeReservedAttrs(hasher hash.Hash, m pcommon.Map, extra ...string) {
```
Comment (lahsivjar) [inline exporter/elasticsearchexporter/metric_grouping.go:116]: Did we consider using common libraries like:

https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/pkg/pdatautil/hash.go
https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/internal/exp/metrics/identity

for the hash calculations? I think almost all the functions here could be replaced by existing hash options. For the exclusion of `DataStream*` attributes we could create a custom hash option.

File: exporter/elasticsearchexporter/metric_grouping.go [hunk 4]
```diff
@@ -35,30 +39,59 @@ func newDataPointHasher(mode MappingMode) dataPointHasher {
...
+func (h ecsDataPointHasher) hashResource(_ pcommon.Resource) uint32 {
+	return 0
+}
+
+func (h ecsDataPointHasher) hashScope(_ pcommon.InstrumentationScope) uint32 {
+	return 0
+}
+
+func (h ecsDataPointHasher) hashDataPoint(_ datapoints.DataPoint) uint32 {
+	return 0
```
Comment (lahsivjar) [inline exporter/elasticsearchexporter/metric_grouping.go:57]: **nit**: This feels a bit misleading for the API. As an API user, calling hashScope, I would expect to get the hash of the instrumentation scope - using the hash or not should be controlling which hash to keep.

File: exporter/elasticsearchexporter/metric_grouping.go [hunk 5]
```diff
@@ -69,14 +102,23 @@ func (h otelDataPointHasher) hashDataPoint(resource pcommon.Resource, scope pcom
...
 	hasher.Write([]byte(dp.Metric().Unit()))
 
-	mapHashExcludeReservedAttrs(hasher, dp.Attributes(), elasticsearch.MappingHintsAttrKey)
+	mapHashSortedExcludeReservedAttrs(hasher, dp.Attributes(), elasticsearch.MappingHintsAttrKey)
 
 	return hasher.Sum32()
 }
 
-// mapHashExcludeReservedAttrs is mapHash but ignoring some reserved attributes.
+func (h otelDataPointHasher) hashCombined(_ pcommon.Resource, _ pcommon.InstrumentationScope, _ datapoints.DataPoint) uint32 {
```
Comment (lahsivjar) [inline exporter/elasticsearchexporter/metric_grouping.go:110]: **nit**: This also same as above, feels a bit misleading.

File: exporter/elasticsearchexporter/metric_grouping.go (hunk 4 above)
Comment (carsonip) [reply exporter/elasticsearchexporter/metric_grouping.go:57]: this is my shot at the following requirements
- ecs hashes differently from otel as data point attributes and resource attributes are propagated to the root level
- hashing of resource should be done per-resource, scope done per-scope, to avoid rehashing and sorting resource attributes and scope attributes per-data point.
- (not a strict requirement) avoid leaking ecs vs otel difference to exporter level

Comment (carsonip) [reply exporter/elasticsearchexporter/metric_grouping.go:57]: I guess the key to the discussion here is where to put the line between exporter logic and metrics grouping logic. Welcome any suggestions

Comment (lahsivjar) [reply exporter/elasticsearchexporter/metric_grouping.go:57]: I think the root of the issue is that the mapping mode is leaking in the hashing logic. What do you think about making the `dataPointGroupKey` aware of the mapping mode and calculate the key based on that. So, for example: for `ecs` mode, it will populate the combined hash key only, whereas for `otel` mode it will populate resource and scope keys? This will also mean that we will only need `DataPointHasher`.

Comment (lahsivjar) [reply exporter/elasticsearchexporter/metric_grouping.go:57]: Additionally, check https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/39309/files#r2039284735 - maybe we can remove the `*DataPointHasher` completely but this is up to further discussion.

Comment (carsonip) [reply exporter/elasticsearchexporter/metric_grouping.go:57]: > What do you think about making the dataPointGroupKey aware of the mapping mode and calculate the key based on that. So, for example: for ecs mode, it will populate the combined hash key only, whereas for otel mode it will populate resource and scope keys? This will also mean that we will only need DataPointHasher.

Let's say there exist a function call `getGroupKey(mode string) dataPointGroupKey`, doesn't it mean that it needs to be called per data point? Won't we lose the optimization to avoid sorting and rehashing resource and scope attributes?

File: exporter/elasticsearchexporter/metric_grouping.go (hunk 3 above)
Comment (carsonip) [reply exporter/elasticsearchexporter/metric_grouping.go:116]: Probably not able to use identity directly, since some fields are used but are not TSDB dimensions, e.g. schema url.

pdatautil hash, on the other hand, looks good and will get rid of a lot of the hashing code we have. Still need to look into how to achieve exclusions. I think we'll be better off creating a map and passing it in, instead of writing an Option which means reimplementing all the funcs in pdatautil hash because they are private.

File: exporter/elasticsearchexporter/metric_grouping.go (hunk 4 above)
Comment (lahsivjar) [reply exporter/elasticsearchexporter/metric_grouping.go:57]: > Won't we lose the optimization to avoid sorting and rehashing resource and scope attributes?

We can just have an interface to update the `dataPointGroupKey`, something like `UpdateWithScope`, `UpdateWithDatapoint`...

File: exporter/elasticsearchexporter/metric_grouping.go (hunk 3 above)
Comment (carsonip) [reply exporter/elasticsearchexporter/metric_grouping.go:119]: > I think we'll be better off creating a map and passing it in

which will involve a fair bit of copying

Comment (lahsivjar) [reply exporter/elasticsearchexporter/metric_grouping.go:119]: > Probably not able to use identity directly, since some fields are used but are not TSDB dimensions, e.g. schema url.

I thought so, the identity is a bit rigid.

> Still need to look into how to achieve exclusions

We can implement a new [HashOption](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/9bb671ca7ab3a9e0861d068f15b146aaa55766c2/pkg/pdatautil/hash.go#L35) (in elasticsearch-exporter for now) - something like `WithMapExclusions(m pcommon.Map, excludedKeys ...string) HashOption`

Comment (lahsivjar) [reply exporter/elasticsearchexporter/metric_grouping.go:119]: > instead of writing an Option which means reimplementing all the funcs in pdatautil hash because they are private

Ah, right!!! I didn't see the comment. Maybe, add a TODO for exporter and create a PR in pdatautil to have this function?

File: exporter/elasticsearchexporter/metric_grouping.go (hunk 4 above)
Comment (carsonip) [reply exporter/elasticsearchexporter/metric_grouping.go]: This is great advice. I've moved hash key to the grouping file to avoid leaking the implementation to exporter.

File: exporter/elasticsearchexporter/metric_grouping.go (hunk 3 above)
Comment (carsonip) [reply exporter/elasticsearchexporter/metric_grouping.go]: Added a TODO, shouldn't be a blocker for this PR.

File: .chloggen/elasticsearchexporter_handle-metric-grouping-edge-cases.yaml (hunk 2 above)
Comment (carsonip) [reply .chloggen/elasticsearchexporter_handle-metric-grouping-edge-cases.yaml:18]: colon is special in yaml :cold_sweat:

File: exporter/elasticsearchexporter/internal/metricgroup/hasher.go [hunk 6]
```diff
@@ -0,0 +1,133 @@
...
+	"github.com/open-telemetry/opentelemetry-collector-contrib/exporter/elasticsearchexporter/internal/datapoints"
+	"github.com/open-telemetry/opentelemetry-collector-contrib/exporter/elasticsearchexporter/internal/elasticsearch"
+)
+
+// HashKey is a struct for comparing data point identity.
+type HashKey struct {
+	resourceHash uint32
+	scopeHash    uint32
+	dpHash       uint32
+}
```
Comment (lahsivjar) [inline exporter/elasticsearchexporter/internal/metricgroup/hasher.go:22]: My initial idea was to not have `{ecs, otel}DataPointHasher` at all and build the hash update logic in the `HashKey` but I think we can discuss that in the follow-up PR when the pdatautil has the method for hashing map with exclude keys.

File: exporter/elasticsearchexporter/internal/metricgroup/hasher.go [hunk 7]
```diff
@@ -0,0 +1,133 @@
...
+
+	timestampBuf := make([]byte, 8)
+	binary.LittleEndian.PutUint64(timestampBuf, uint64(h.dp.Timestamp()))
+	hasher.Write(timestampBuf)
+
+	mapHashSortedExcludeReservedAttrs(hasher, merged)
+
+	return HashKey{
+		dpHash: hasher.Sum32(),
+	}
```
Comment (lahsivjar) [inline exporter/elasticsearchexporter/internal/metricgroup/hasher.go:77]: **nit**: Can we unify the behaviour of `HashKey` for both the datapoint hashers? Currently, the ECS one is doing hash calculation in the `HashKey` method whereas the OTel one does it on `Update`.

**Review by lahsivjar — APPROVED** [review]
Mostly LGTM, just some minor comments.

File: exporter/elasticsearchexporter/metric_grouping.go (hunk 4 above)
Comment (lahsivjar) [reply exporter/elasticsearchexporter/metric_grouping.go]: Thanks!

File: exporter/elasticsearchexporter/internal/metricgroup/hasher.go (hunk 7 above)
Comment (carsonip) [reply exporter/elasticsearchexporter/internal/metricgroup/hasher.go:77]: The reason for splitting into separate ecs and otel hashers, and that they perform the hashing at Update vs HashKey is that
- otel should not recompute resource and scope hash on every data point change, because it is wasteful
- ecs _has_ to do so because data point attributes overwrites resource attributes

File: exporter/elasticsearchexporter/internal/metricgroup/hasher.go (hunk 6 above)
Comment (carsonip) [reply exporter/elasticsearchexporter/internal/metricgroup/hasher.go:22]: See https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/39309#discussion_r2041853809

File: exporter/elasticsearchexporter/internal/metricgroup/hash.go [hunk 8]
```diff
@@ -0,0 +1,90 @@
...
+	"go.opentelemetry.io/collector/pdata/pcommon"
+
+	"github.com/open-telemetry/opentelemetry-collector-contrib/exporter/elasticsearchexporter/internal/elasticsearch"
+)
+
+// mapHashSortedExcludeReservedAttrs is mapHash but ignoring some reserved attributes and is independent of order in Map.
+// e.g. index is already considered during routing and DS attributes do not need to be considered in hashing
+//
+// TODO(carsonip): use opentelemetry-collector-contrib/pkg/pdatautil/hash.go when it can optionally exclude attributes
+// We could have used it now but it'll involve creating a new Map and copying things over.
```
[the remark this answers is not in the document]
Comment (carsonip) [reply exporter/elasticsearchexporter/internal/metricgroup/hash.go:22]: https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/39377

File: exporter/elasticsearchexporter/internal/metricgroup/hasher.go (hunk 6 above)
Comment (lahsivjar) [reply exporter/elasticsearchexporter/internal/metricgroup/hasher.go:22]: Hmm, this is a bit different than that comment. I was thinking that once we have the hasher methods in the pdatautil, we could remove the `DataPointHasher` completely and build an API around HashKey (assuming pdata is hierarchical) to calculate the hashes. We can discuss this at a later point.

File: exporter/elasticsearchexporter/internal/metricgroup/hasher.go (hunk 7 above)
Comment (lahsivjar) [reply exporter/elasticsearchexporter/internal/metricgroup/hasher.go:77]: What I meant was that in ECS mode, we can calculate the hash on the update datapoint method. Since, the datastructure is hierarchical, when we get a new resource or scope, the DP attribute can be cleared. On a new Datapoint, the hash can be calculated (as done in the OTel hasher).

It is not a blocker, so maybe revisit this as a follow-up after pdatautil updates are done.

**Review by lahsivjar — APPROVED** [review]
Feel free to merge, we can address/further discuss the other points in the follow-up.

File: exporter/elasticsearchexporter/internal/metricgroup/hasher.go (hunk 7 above)
Comment (carsonip) [reply exporter/elasticsearchexporter/internal/metricgroup/hasher.go:77]: > new resource or scope, the DP attribute can be cleared. On a new Datapoint, the hash can be calculated (as done in the OTel hasher).

I didn't consider this initially as this imposes an implicit requirement on the order of calling Update functions.

Comment (lahsivjar) [reply exporter/elasticsearchexporter/internal/metricgroup/hasher.go:77]: > I didn't consider this initially as this imposes an implicit requirement on the order of calling Update functions

Hmm, but there is an order inherent with pdata. I was thinking of building `HashKey` with a similar interface as https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/internal/exp/metrics/identity where we will define the hierarchy in the interface.

**Review by andrzej-stencel — APPROVED** [review]
