### PR TITLE
[receiver/receivercreator]  Log config at debug level since it could contain sensitive info

### LINKED ISSUE #38163: receivercreator logs the entire config including passwords in clear text
### Component(s)

receiver/receivercreator

## Description
When starting a new receiver, the receiver creator logs the config used, including the password in clear text.
See [observerhandler.go#L201](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/receiver/receivercreator/observerhandler.go#L201).
Note: the `postgresql` receiver uses a `configopaque.String` (see [config.go#L33](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/release/0.119.x/receiver/postgresqlreceiver/config.go#L33)).

## Steps to Reproduce
In Kubernetes, deploy a collector configured as follow
 
- using the `k8sobserver` to "observe" the creation of new pods
- using the receiver creator to create ` postgresql` receiver. Configure the password in the template (using a secret e.g.). 

Deploy a new PostgreSQL cluster to be discovered by the receivercreator

Check the collector's logs, the password appears in clear text

This is how we discovered this issue, but there are certainly easier ways of reproducing it.

## Expected Result
Password, private keys, ... are redacted.

## Actual Result
password is shown in clear text.

### Collector version

0.119.0

## Environment
Kubernetes 
Zalando's PostgreSQL operator

### OpenTelemetry Collector configuration

```yaml
extensions:
  k8s_observer:
    auth_type: serviceAccount
    observe_pods: true

receivers:
  jaeger: null
  prometheus: null
  zipkin: null
  otlp: null

  receiver_creator:
    watch_observers: [k8s_observer]
    receivers:
      postgresql:
        rule: type == "pod" && annotations['o11y_type'] == "postgresql"
        config:
          endpoint: '`endpoint`:5432'
          username: ${PG_USERNAME}
          password: ${PG_PWD}
          metrics:
            postgresql.database.locks:
              enabled: true
            postgresql.deadlocks:
              enabled: true
            postgresql.sequential_scans:
              enabled: true
            postgresql.temp_files:
              enabled: true
            postgresql.wal.delay:
              enabled: true


service:
  extensions:
    - k8s_observer
    - health_check
  pipelines:
    metrics:
      receivers:
        - receiver_creator
      exporters:
        - debug

    logs: null
    traces: null
```

### Log output

```shell
{
    "level": "info",
    "ts": "2025-02-24T16:15:03.664Z",
    "caller": "receivercreator@v0.119.0/observerhandler.go:201",
    "msg": "starting receiver",
    "kind": "receiver",
    "name": "receiver_creator",
    "data_type": "metrics",
    "name": "postgresql",
    "endpoint": "<redacted>",
    "endpoint_id": "k8s_observer/<redacted>",
    "config": {
        "endpoint": "`endpoint`:5432",
        "metrics": {
            "postgresql.database.locks": {
                "enabled": true
            },
            "postgresql.deadlocks": {
                "enabled": true
            },
            "postgresql.sequential_scans": {
                "enabled": true
            },
            "postgresql.temp_files": {
                "enabled": true
            },
            "postgresql.wal.delay": {
                "enabled": true
            }
        },
        "password": "<here, there's a real password>",
        "username": "<here, there's a real username>"
    }
}
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by khushijain21**
#### Description
See Title 

#### Link to tracking issue
Fixes https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/38163

### CODE REVIEW

**Review by bogdan-st — APPROVED** [review]

**Review by paulojmdias — APPROVED** [review]

File: receiver/receivercreator/observerhandler.go [hunk 1]
```diff
@@ -206,8 +206,7 @@ func (obs *observerHandler) startReceiver(template receiverTemplate, env observe
 	obs.params.Logger.Info("starting receiver",
 		zap.String("name", template.id.String()),
 		zap.String("endpoint", e.Target),
-		zap.String("endpoint_id", string(e.ID)),
-		zap.Any("config", resolvedConfig))
+		zap.String("endpoint_id", string(e.ID)))
```
Comment (ChrsMark) [inline receiver/receivercreator/observerhandler.go]: I wonder if we should redact instead since the generated configuration can be useful in general for debugging purposes.

Example: https://github.com/elastic/beats/blob/main/libbeat/autodiscover/autodiscover.go#L218C50-L218C61 using https://github.com/elastic/elastic-agent-libs/blob/c5fb280e644b4c3c3676684b6d47a1761e2f23ae/config/config.go#L376-L378

Comment (khushijain21) [reply receiver/receivercreator/observerhandler.go]: I moved resolved config to debug level for general debugging. Let me know what you think

File: receiver/receivercreator/observerhandler.go [hunk 2]
```diff
@@ -207,7 +207,9 @@ func (obs *observerHandler) startReceiver(template receiverTemplate, env observe
 		zap.String("name", template.id.String()),
 		zap.String("endpoint", e.Target),
 		zap.String("endpoint_id", string(e.ID)),
-		zap.Any("config", resolvedConfig))
+	)
+
+	obs.params.Logger.Debug("starting receiver with resolved config", zap.Any("config", resolvedConfig))
```
Comment (ChrsMark) [inline receiver/receivercreator/observerhandler.go:213]:
```suggestion
        # TODO: we should consider about applying sensitive data redaction
	obs.params.Logger.Debug("starting receiver with resolved config", zap.Any("config", resolvedConfig))
```

**Review by ChrsMark — APPROVED** [review]

File: receiver/receivercreator/observerhandler.go [hunk 3]
```diff
@@ -207,7 +207,10 @@ func (obs *observerHandler) startReceiver(template receiverTemplate, env observe
 		zap.String("name", template.id.String()),
 		zap.String("endpoint", e.Target),
 		zap.String("endpoint_id", string(e.ID)),
-		zap.Any("config", resolvedConfig))
+	)
+
+        # TODO: we should consider about applying sensitive data redaction
```
Comment (ChrsMark) [inline receiver/receivercreator/observerhandler.go]:
```suggestion
        // TODO: we should consider about applying sensitive data redaction
```

**Comment by ChrsMark** [comment]
@khushijain21 it seems my suggestion broke the linter because of wrong indentation? Could you re-run the format please?

**Review by ChrsMark — APPROVED** [review]
