### PR TITLE
[processor/resourcedetection] Fetch CPU info only if required

### LINKED ISSUE #33768: [resourcedetection] windows: Error 'failed getting host cpuinfo: context deadline exceeded'
### Component(s)

processor/resourcedetection, processor/resourcedetection/internal/system

## Description
After introduction of the host cpuinfo attributes in #26533, the `system` resource detection can fail catastrophically on Windows hosts, resulting in **ALL** configured `system` resource attributes (Host name, Host ID, OS type, OS description ...) to become unavailable in all pipelines where the instance of `resourcedection` processor is used.

The cause is a combination of:
1. `cpuinfo` attribute collection is **ALWAYS** running on the processor's `Start()` phase, regardless of whether the cpuinfo attributes are configured to be added into the resource attributes.
2. The newly included external dependency introduced by the `cpuinfo` work in #26533 uses a mechanism (WMI [^1]) for retrieving the CPU info that can often fail with a timeout (hence, the `context deadline exceeded` error).

The issue is more likely to happen when the Otel collector starts up during host boot up (e.g. as a service launched by a service manager) as opposed to launching the Otel collector on demand after the Windows host is already running.
This due to parallelization of startup tasks (services) in the Operating System.

## Steps to Reproduce

1. Stop and disable the `winmgmgt` windows service to simulate the failure condition of not being able to collect the CPU Info: `sc config winmgmt start= disabled` and `net stop winmgmt`
2. Run Otel Collector with a config that includes the `system` resourcedetection with at least one of the configs enabled (e.g. Host ID) in a pipeline.
3. Observe Otel Collector's logs

## Expected Result
Otel Collector's logs contains the requested attribute in the resourcedetection processor's logs (e.g. Host ID)

e.g.
```
2024-06-26T13:31:37.391+1000    info    internal/resourcedetection.go:125       began detecting resource information   {"kind": "processor", "name": "resourcedetection", "pipeline": "traces"}
2024-06-26T13:31:38.698+1000    info    internal/resourcedetection.go:139       detected resource information   {"kind": "processor", "name": "resourcedetection", "pipeline": "traces", "resource": {"host.id":"5ac27508-7835-40fd-a8e3-541bb69b8f70","host.name":"DESKTOP-RHABMHR","os.type":"windows","service.name":"windows-dev"}}
```

## Actual Result
Otel Collector's logs contain the error message `'failed getting host cpuinfo:` 

(**NOTE**:  the simulated failure condition of completely disabling `winmgmt` produces a slightly different exception instead of the `'context deadline exceeded'` error from a production system)

The requested attributes (e.g. Host ID) are missing from the resourcedetection processor's logs

e.g.
```
2024-06-26T13:38:26.012+1000    warn    internal/resourcedetection.go:130       failed to detect resource       {"kind": "processor", "name": "resourcedetection", "pipeline": "traces", "error": "failed getting host cpuinfo: Exception occurred. (The service cannot be started, either because it is disabled or because it has no enabled devices associated with it. )"}
2024-06-26T13:38:26.012+1000    info    internal/resourcedetection.go:139       detected resource information   {"kind": "processor", "name": "resourcedetection", "pipeline": "traces", "resource": {"service.name":"windows-dev"}}
```

[^1]: https://github.com/shirou/gopsutil/blob/e74324b6a726997ce756b8f79dbbd7a3a0999ba0/cpu/cpu_windows.go#L98-L127

### Collector version

v0.103.1

## Environment
OS: Windows (10, 11, 2019, 2022)

### OpenTelemetry Collector configuration

```yaml
receivers:
  otlp:
    protocols:
      grpc:
      http:
processors:
  resourcedetection:
    detectors:
      - system
      - env
    system:
      resource_attributes:
        host.id:
          enabled: true
exporters:
  logging:
service:
  pipelines:
    traces:
      receivers:
        - otlp
      processors:
        - resourcedetection
      exporters:
        - logging
```

### Log output

```shell
2024-06-26T13:38:26.012+1000    warn    internal/resourcedetection.go:130       failed to detect resource       {"kind": "processor", "name": "resourcedetection", "pipeline": "traces", "error": "failed getting host cpuinfo:
```

### Additional context

There should have been a **Breaking Change** note in the ChangeLog that makes all users of the `resourcedetection` processor aware of the newly introduced hard dependency on the `winmgmt` service.

### LINKED ISSUE #33771: [resourcedetection] cpuinfo ignores the configured timeout in the resourcedetection processor
### Component(s)

processor/resourcedetection, processor/resourcedetection/internal/system

## Description
The host cpuinfo attributes introduced in  #26533 use the `cpu.Info()` call from `gopsutil`.

`cpu.Info()` ignores any timeouts that a user configures in the resourcedetection processor, as it is simply calling `cpu.InfoWithContext(context.Background)`  [^1]

```
func Info() ([]InfoStat, error) {
	return InfoWithContext(context.Background())
}
```

## Steps to Reproduce

N/A - A repro would require a really elaborate set up with a reliable way of slowing down COM calls in windows. Outside of production systems, I don't know how to artificially slow down COM calls ...

## Expected Result

cpuinfo honors the configured timeout as configured by the user.

## Actual Result

cpuinfo disregards the configured timeout as configured by the user.

[^1]: https://github.com/shirou/gopsutil/blob/master/cpu/cpu_windows.go#L92-L94

### Collector version

v0.103.1

## Environment
OS: Windows (10, 11, 2019, 2022)

### OpenTelemetry Collector configuration

```yaml
receivers:
  otlp:
    protocols:
      grpc:
      http:
processors:
  resourcedetection:
    timeout: 60s
    detectors:
      - system
      - env
    system:
      resource_attributes:
        host.id:
          enabled: true
exporters:
  logging:
service:
  pipelines:
    traces:
      receivers:
        - otlp
      processors:
        - resourcedetection
      exporters:
        - logging
```

### Log output

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by ChrsMark**
**Description:** <Describe what has changed.>

This PR changes the system resource detector so as to only try to fetch the CPU info when required. The CPU info attributes are disabled by default so we should only fetch this information when at least one of those is enabled.

**Link to tracking Issue:** <Issue number if applicable> https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/33768

**Testing:** <Describe what testing was performed and which tests were added.> Added unti-tests

**Documentation:** <Describe the documentation added.> ~

/cc @mx-psi

### CODE REVIEW

File: internal/metadataproviders/system/metadata.go [hunk 1]
```diff
@@ -69,6 +70,9 @@ type Provider interface {
 
 	// HostMACs returns the host's MAC addresses
 	HostMACs() ([]net.HardwareAddr, error)
+
+	// CPUInfo returns the host's CPU info
+	CPUInfo() ([]cpu.InfoStat, error)
```
Comment (mx-psi) [inline internal/metadataproviders/system/metadata.go:75]: Let's pass the context here so that we can address #33771 as well

**Review by mx-psi — APPROVED** [review]

**Comment by mx-psi** [comment]
@cwegener will wait until end of week to merge this in case you want to leave a review :)
