### PR TITLE
[receiver/mongodbatlas] Dont panic on inaccessible file storage

### LINKED ISSUE #19191: [receiver/mongodbatlas] Panic in collecting event logs
### Component(s)

receiver/mongodbatlas

## Description
The MongoDB Atlas receiver is panicking when storage client fails to init.

## Steps to Reproduce
Create a config with file_storage that the user running the collector doesn't have access to.

## Expected Result
Graceful failure with an error message

## Actual Result
Panic

```
invalid memory address or nil pointer dereference. Panic stacktrace: goroutine 91 [running]:
runtime/debug.Stack()
    /opt/hostedtoolcache/go/1.19.6/x64/src/runtime/debug/stack.go:24 +0x65
github.com/observiq/observiq-otel-collector/collector.(*collector).Run.func1.1()
    /home/runner/work/observiq-otel-collector/observiq-otel-collector/collector/collector.go:114 +0x5d
panic({0x55a7e60, 0xaaa9370})
    /opt/hostedtoolcache/go/1.19.6/x64/src/runtime/panic.go:884 +0x212
github.com/open-telemetry/opentelemetry-collector-contrib/receiver/mongodbatlasreceiver.(*eventsReceiver).checkpoint(0xc00124e320, {0x6fa40d8, 0xc0000d2280})
    /home/runner/go/pkg/mod/github.com/open-telemetry/opentelemetry-collector-contrib/receiver/mongodbatlasreceiver@v0.72.0/events.go:235 +0x90
github.com/open-telemetry/opentelemetry-collector-contrib/receiver/mongodbatlasreceiver.(*eventsReceiver).Shutdown(0xc00124e320, {0x6fa40d8, 0xc0000d2280})
    /home/runner/go/pkg/mod/github.com/open-telemetry/opentelemetry-collector-contrib/receiver/mongodbatlasreceiver@v0.72.0/events.go:117 +0x85
github.com/open-telemetry/opentelemetry-collector-contrib/receiver/mongodbatlasreceiver.(*combinedLogsReceiver).Shutdown(0xc00124b398, {0x6fa40d8, 0xc0000d2280})
    /home/runner/go/pkg/mod/github.com/open-telemetry/opentelemetry-collector-contrib/receiver/mongodbatlasreceiver@v0.72.0/combined_logs.go:73 +0xdd
go.opentelemetry.io/collector/service.(*pipelinesGraph).ShutdownAll(0x0?, {0x6fa40d8, 0xc0000d2280})
    /home/runner/go/pkg/mod/go.opentelemetry.io/collector@v0.72.0/service/graph.go:296 +0xc9
go.opentelemetry.io/collector/service.(*Service).Shutdown(0xc00019a600, {0x6fa40d8, 0xc0000d2280})
    /home/runner/go/pkg/mod/go.opentelemetry.io/collector@v0.72.0/service/service.go:172 +0xd9
go.opentelemetry.io/collector/otelcol.(*Collector).setupConfigurationComponents(0xc000a26300, {0x6fa40d8, 0xc0000d2280})
    /home/runner/go/pkg/mod/go.opentelemetry.io/collector@v0.72.0/otelcol/collector.go:183 +0x628
go.opentelemetry.io/collector/otelcol.(*Collector).Run(0xc000a26300, {0x6fa40d8, 0xc0000d2280})
    /home/runner/go/pkg/mod/go.opentelemetry.io/collector@v0.72.0/otelcol/collector.go:207 +0x65
github.com/observiq/observiq-otel-collector/collector.(*collector).Run.func1()
    /home/runner/work/observiq-otel-collector/observiq-otel-collector/collector/collector.go:131 +0xc5
created by github.com/observiq/observiq-otel-collector/collector.(*collector).Run
    /home/runner/work/observiq-otel-collector/observiq-otel-collector/collector/collector.go:107 +0x512
","stacktrace":"main.main
    /home/runner/work/observiq-otel-collector/observiq-otel-collector/cmd/collector/main.go:113
runtime.main
    /opt/hostedtoolcache/go/1.19.6/x64/src/runtime/proc.go:250
```

### Collector version

v0.72.0

### Environment information

_No response_

### OpenTelemetry Collector configuration

```yaml
receivers:
  mongodbatlas:
    public_key: $MONGODB_ATLAS_PUBLIC_KEY
    private_key: $MONGODB_ATLAS_PRIVATE_KEY
    events:
      projects:
        - name: "Login PoC Sandbox"
          exclude_clusters:
          - "ccs-audit"
      poll_interval: 30s
      types: []
    storage: file_storage

extensions:
  file_storage:
    directory: /folder_no_perms/ # don't have permissions to write to this folder

exporters:
  logging:

service:
  extensions: [file_storage]
  pipelines:
    logs:
      receivers:
      - mongodbatlas
      exporters:
      - logging
```

### Log output

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by schmikei**
**Description:** On the start function of the events receiver we can fail and return an error, shutdown still gets called which had the potential to nil pointer exception because Start never finished.

**Link to tracking Issue:** Resolves #19191

**Testing:** 

Behavior before:

```
{"level":"fatal","ts":"2023-03-03T10:41:26.398-0500","caller":"collector/main.go:113","msg":"RunService returned error","error":"failed to start service: failed while starting collector: collector panicked with error: runtime error: invalid memory address or nil pointer dereference. Panic stacktrace: goroutine 44 [running]:\nruntime/debug.Stack()\n\t/usr/local/opt/go/libexec/src/runtime/debug/stack.go:24 +0x65\ngithub.com/observiq/observiq-otel-collector/collector.(*collector).Run.func1.1()\n\t/Users/keithschmitt/go-workspace/src/github.com/observiq/observiq-collector/collector/collector.go:114 +0x5d\npanic({0x105001ac0, 0x10a3a1e10})\n\t/usr/local/opt/go/libexec/src/runtime/panic.go:884 +0x212\ngithub.com/open-telemetry/opentelemetry-collector-contrib/receiver/mongodbatlasreceiver.(*eventsReceiver).checkpoint(0xc000eca820, {0x10698b4f8, 0xc000c76740})\n\t/Users/keithschmitt/go/pkg/mod/github.com/open-telemetry/opentelemetry-collector-contrib/receiver/mongodbatlasreceiver@v0.72.0/events.go:235 +0x90\ngithub.com/open-telemetry/opentelemetry-collector-contrib/receiver/mongodbatlasreceiver.(*eventsReceiver).Shutdown(0xc000eca820, {0x10698b4f8, 0xc000c76740})\n\t/Users/keithschmitt/go/pkg/mod/github.com/open-telemetry/opentelemetry-collector-contrib/receiver/mongodbatlasreceiver@v0.72.0/events.go:117 +0x85\ngithub.com/open-telemetry/opentelemetry-collector-contrib/receiver/mongodbatlasreceiver.(*combinedLogsReceiver).Shutdown(0xc000ecde78, {0x10698b4f8, 0xc000c76740})\n\t/Users/keithschmitt/go/pkg/mod/github.com/open-telemetry/opentelemetry-collector-contrib/receiver/mongodbatlasreceiver@v0.72.0/combined_logs.go:73 +0xdd\ngo.opentelemetry.io/collector/service.(*pipelinesGraph).ShutdownAll(0x0?, {0x10698b4f8, 0xc000c76740})\n\t/Users/keithschmitt/go/pkg/mod/go.opentelemetry.io/collector@v0.72.0/service/graph.go:296 +0xc9\ngo.opentelemetry.io/collector/service.(*Service).Shutdown(0xc0003add80, {0x10698b4f8, 0xc000c76740})\n\t/Users/keithschmitt/go/pkg/mod/go.opentelemetry.io/collector@v0.72.0/service/service.go:172 +0xd9\ngo.opentelemetry.io/collector/otelcol.(*Collector).setupConfigurationComponents(0xc000c7a000, {0x10698b4f8, 0xc000c76740})\n\t/Users/keithschmitt/go/pkg/mod/go.opentelemetry.io/collector@v0.72.0/otelcol/collector.go:183 +0x628\ngo.opentelemetry.io/collector/otelcol.(*Collector).Run(0xc000c7a000, {0x10698b4f8, 0xc000c76740})\n\t/Users/keithschmitt/go/pkg/mod/go.opentelemetry.io/collector@v0.72.0/otelcol/collector.go:207 +0x65\ngithub.com/observiq/observiq-otel-collector/collector.(*collector).Run.func1()\n\t/Users/keithschmitt/go-workspace/src/github.com/observiq/observiq-collector/collector/collector.go:131 +0xc5\ncreated by github.com/observiq/observiq-otel-collector/collector.(*collector).Run\n\t/Users/keithschmitt/go-workspace/src/github.com/observiq/observiq-collector/collector/collector.go:107 +0x512\n","stacktrace":"main.main\n\t/Users/keithschmitt/go-workspace/src/github.com/observiq/observiq-collector/cmd/collector/main.go:113\nruntime.main\n\t/usr/local/opt/go/libexec/src/runtime/proc.go:250"}
```

Behavior after (desired):

```
otelcontribcol...	{"Version": "0.71.0-dev", "NumCPU": 12}
2023-03-03T10:54:52.086-0500	info	extensions/extensions.go:41	Starting extensions...
2023-03-03T10:54:52.086-0500	info	extensions/extensions.go:44	Extension is starting...	{"kind": "extension", "name": "file_storage"}
2023-03-03T10:54:52.086-0500	info	extensions/extensions.go:48	Extension started.	{"kind": "extension", "name": "file_storage"}
2023-03-03T10:54:52.086-0500	info	service/service.go:166	Starting shutdown...
2023-03-03T10:54:52.086-0500	info	extensions/extensions.go:55	Stopping extensions...
2023-03-03T10:54:52.086-0500	info	service/service.go:180	Shutdown complete.
Error: cannot start pipelines: failed to get storage client: open tmp/receiver_mongodbatlas_: permission denied
2023/03/03 10:54:52 collector server run finished with error: cannot start pipelines: failed to get storage
```

**Documentation:** New changelog entry

### CODE REVIEW

**Comment by schmikei** [comment]
@djaglowski since you helped me write this, when you have a moment do you mind taking a peek at this?

File: receiver/mongodbatlasreceiver/events.go [hunk 1]
```diff
@@ -228,6 +228,11 @@ func (er *eventsReceiver) transformEvents(now pcommon.Timestamp, events []*mongo
 }
 
 func (er *eventsReceiver) checkpoint(ctx context.Context) error {
+	// if storageClient was never set, we shouldn't try to checkpoint
+	if er.storageClient == nil {
```
Comment (djaglowski) [inline receiver/mongodbatlasreceiver/events.go:232]: If `Start` completes successfully, this is never nil, so we only need to check this during shutdown.

Comment (djaglowski) [reply receiver/mongodbatlasreceiver/events.go:232]: Alternately, we can initialize the client to `storage.NewNowClient` and not have to worry about the check at all.

**Review by djaglowski — APPROVED** [review]
