### PR TITLE
[exporter/datadog] Upgrade `exporter.datadogexporter.UseLogsAgentExporter` feature flag to beta

### LINKED ISSUE #34366: [exporter/datadog] incorrect `service.name` transformation
### Component(s)

exporter/datadog

### What happened?

I wrote up everything in https://github.com/DataDog/opentelemetry-mapping-go/issues/356 since that's where the issue actually lies but Datadog Support requested that I open an issue on this repository instead. I'm going out of office starting tomorrow so I wanted to get this in beforehand. I'll come back and transfer the content over nicely to this issue when I'm back.

### Collector version

latest

### Environment information

N/A

### OpenTelemetry Collector configuration

```yaml
processors:
  transform:
    log_statements:
      - context: log
        statements:
          - set(attributes["service.name"], "sudomateo")
          - set(attributes["ddtags"], "source:sudomateo")
```

### Log output

```shell
N/A
```

### Additional context

N/A

### PR DESCRIPTION
**Pull request by liustanley**
**Description:** <Describe what has changed.>

Use Datadog Agent logs pipeline by default for exporting logs to Datadog. Upgrades `exporter.datadogexporter.UseLogsAgentExporter` feature flag to beta.

Note: if users have `logs::dump_payloads` enabled in their config after upgrading, an error will be raised because this config option cannot be used with the logs agent exporter: https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/f1aadc6c9c5d117eb61898cd2f1969a279a7f80e/exporter/datadogexporter/config.go#L658

**Link to tracking Issue:** <Issue number if applicable>
Fixes https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/34366 and introduces general performance improvements.

**Testing:** <Describe what testing was performed and which tests were added.>

**Documentation:** <Describe the documentation added.>

### CODE REVIEW

File: exporter/datadogexporter/factory_test.go [hunk 1]
```diff
@@ -123,67 +123,6 @@ func TestCreateDefaultConfig(t *testing.T) {
 	assert.NoError(t, componenttest.CheckConfigStruct(cfg))
 }
 
-// Test that the factory creates the default configuration
-func TestCreateDefaultConfigLogsAgent(t *testing.T) {
```
Comment (songy23) [inline exporter/datadogexporter/factory_test.go:127]: Why is this test removed?

**Review by songy23 — APPROVED** [review]
One nit, LGTM otherwise

File: exporter/datadogexporter/factory_test.go (hunk 1 above)
Comment (liustanley) [reply exporter/datadogexporter/factory_test.go:127]: We added this test when the logs agent feature flag created a different default config, but now the default configs are the same with or without the logs agent feature gate.

**Comment by mx-psi** [comment]
> Note: if users have logs::dump_payloads enabled in their config after upgrading, an error will be raised because this config option cannot be used with the logs agent exporter:

This is a breaking change and we should list it in the changelog. 

Do we intend to provide this functionality in the future? Or is this just not going to be supported?

**Comment by liustanley** [comment]
> > Note: if users have logs::dump_payloads enabled in their config after upgrading, an error will be raised because this config option cannot be used with the logs agent exporter:
> 
> This is a breaking change and we should list it in the changelog.
> 
> Do we intend to provide this functionality in the future? Or is this just not going to be supported?

I don't think there's a corresponding feature/config option in the logs agent, so we were going to leave it unless someone wants to request it as a feature. I believe `logs::dump_payloads` is only used in debugging.

File: .chloggen/stanley.liu_logs-agent-beta-breaking.yaml [hunk 2]
```diff
@@ -0,0 +1,27 @@
...
+# A brief description of the change.  Surround your text with quotes ("") if it needs to start with a backtick (`).
+note: The `logs::dump_payloads` config option is invalid when the Datadog Agent logs pipeline is enabled (now enabled by default).
+
+# Mandatory: One or more tracking issues related to the change. You can use the PR number here if no issue exists.
+issues: [34420]
+
+# (Optional) One or more lines of additional information to render under the primary note.
+# These lines will be padded with 2 spaces and then inserted directly into the document.
+# Use pipe (|) for multiline entries.
+subtext: An error will be raised if `logs::dump_payloads` is set while the Datadog Agent logs pipeline is enabled. To avoid this error, remove the `logs::dump_payloads` config option or disable the `exporter.datadogexporter.UseLogsAgentExporter` feature gate.
```
Comment (mx-psi) [inline .chloggen/stanley.liu_logs-agent-beta-breaking.yaml:18]: We intend to have the feature gate as stable at some point, so we should make that clear
```suggestion
subtext: An error will be raised if `logs::dump_payloads` is set while the Datadog Agent logs pipeline is enabled. To avoid this error, remove the `logs::dump_payloads` config option or temporarily disable the `exporter.datadogexporter.UseLogsAgentExporter` feature gate.
```

**Comment by songy23** [comment]
On hold until 0.108 release as discussed offline

**Review by mx-psi — DISMISSED** [review]
Blocking merge until v0.108.0

**Review by mx-psi — APPROVED** [review]
