### PR TITLE
[exporter/bmchelix] fix distinct datapoints merged into a single metric payload

### LINKED ISSUE #40991: [exporter/bmchelix] distinct datapoints are merged into a single metric payload
### Component(s)

exporter/bmchelix

## Description

The `bmchelix` exporter merged multiple datapoints into the same metric object (`BMCHelixOMMetric`) even though each datapoint had different attributes (e.g., `entityName`, `instanceName`, etc.). This resulted in a single metric with multiple samples that should have been split into distinct metrics per datapoint, each reflecting its own unique entity identity.

## Steps to Reproduce

1. Emit an OpenTelemetry metric (e.g., `nt_services_servicestatus`) with multiple datapoints, each containing distinct attributes such as:

   * `entityName`
   * `instanceName`
   * `id`
2. Observe the resulting payload from the `bmchelix` exporter.

Example output:

```json
[{
  "labels": {
      "entityId": "OTEL:WIN-P03F6KRGOLO:windows_services:SERVICES_SessionEnv",
      "entityName": "SERVICES_SessionEnv",
      "entityTypeId": "windows_services",
      "fqdn": "WIN-P03F6KRGOLO",
      "host.name": "WIN-P03F6KRGOLO",
      "hostType": "server",
      "hostname": "WIN-P03F6KRGOLO",
      "id": "SERVICES_SessionEnv",
      "instanceName": "Remote Desktop Configuration",
  },
  "samples": [
    { "value": 1, "timestamp": 1750928911000 },
    { "value": 0, "timestamp": 1750928911000 },
    ...
  ]
}]
```
> All samples were grouped under the same metric, even though they refer to different Windows services.

## Expected Result

Each datapoint with distinct identifying attributes should result in an independent `BMCHelixOMMetric` object, ensuring correct entity resolution on the BMC Helix side.

```json
[
{
  "labels": {
      "entityId": "OTEL:WIN-P03F6KRGOLO:windows_services:SERVICES_SessionEnv",
      "entityName": "SERVICES_SessionEnv",
      "entityTypeId": "windows_services",
      "fqdn": "WIN-P03F6KRGOLO",
      "host.name": "WIN-P03F6KRGOLO",
      "hostType": "server",
      "hostname": "WIN-P03F6KRGOLO",
      "id": "SERVICES_SessionEnv",
      "instanceName": "Remote Desktop Configuration",
  },
  "samples": [
    { "value": 1, "timestamp": 1750928911000 }
  ]
},
{
  "labels": {
      "entityId": "OTEL:WIN-P03F6KRGOLO:windows_services:SERVICES_Spooler",
      "entityName": "SERVICES_Spooler",
      "entityTypeId": "windows_services",
      "fqdn": "WIN-P03F6KRGOLO",
      "host.name": "WIN-P03F6KRGOLO",
      "hostType": "server",
      "hostname": "WIN-P03F6KRGOLO",
      "id": "SERVICES_Spooler",
      "instanceName": "Print Spooler",
  },
  "samples": [
    { "value": 0, "timestamp": 1750928911000 }
  ]
},
]
```

## Actual Result

Multiple datapoints were incorrectly merged under one metric, causing loss of per-entity distinction and incorrect payload semantics.

### Collector version

0.128.0

## Environment

OS: All (Windows, Unix, etc.)

### OpenTelemetry Collector configuration

```yaml
#═══════════════════════════════════════════════════
# INPUTS
#═══════════════════════════════════════════════════
receivers:
  # OTLP
  # Receives data via gRPC or HTTP using OTLP format. For additional information on the OTLP receiver:
  # https://github.com/open-telemetry/opentelemetry-collector/tree/main/receiver/otlpreceiver
  otlp:
    protocols:
      grpc:
        max_recv_msg_size_mib: 100
        endpoint: localhost:4317

#═══════════════════════════════════════════════════
# PROCESSING
#═══════════════════════════════════════════════════
processors:

  transform/hardware_for_helix:

    metric_statements:
    ...
  # memory_limiter
  # Limits the memory usage of the collector. For additional information on the memory limiter:
  # https://github.com/open-telemetry/opentelemetry-collector/tree/main/processor/memorylimiterprocessor
  memory_limiter:
    check_interval: 5s
    limit_mib: 2000
    spike_limit_mib: 400

  # batch
  # Processes and sends data in batches of 10s. For additional information on the batch processor:
  # https://github.com/open-telemetry/opentelemetry-collector/tree/main/processor/batchprocessor
  batch:
    timeout: 10s
    send_batch_size: 100
    send_batch_max_size: 100

#═══════════════════════════════════════════════════
# OUTPUT
#═══════════════════════════════════════════════════
exporters:
  bmchelix:
    endpoint: https://sentry2-itom-poc.onbmc.com
    api_key: <api-key>

#═══════════════════════════════════════════════════
# EXTRAS
#═══════════════════════════════════════════════════
extensions:
  # healthcheck
  # https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/extension/healthcheckextension
  health_check:

#═══════════════════════════════════════════════════
# ACTUAL COLLECTOR PIPELINE DESCRIPTION
#═══════════════════════════════════════════════════
service:
  telemetry:
    logs:
      level: debug
  extensions: [health_check, basicauth]
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [memory_limiter, batch, transform/hardware_for_helix] 
      exporters: [bmchelix]
```

### Log output

```shell

```

### Additional context

_No response_

### Tip

<sub>[React](https://github.blog/news-insights/product-news/add-reactions-to-pull-requests-issues-and-comments/) with 👍 to help prioritize this issue. Please use comments to provide useful context, avoiding `+1` or `me too`, to help us triage it. Learn more [here](https://opentelemetry.io/community/end-user/issue-participation/).</sub>

### PR DESCRIPTION
**Pull request by NassimBtk**
#### Description
This pull request addresses a bug in the `bmchelixexporter` component where distinct datapoints were being merged into a single metric payload. The changes include updates to the metric conversion logic, test cases, and the addition of a changelog entry.

### Bug Fix: Handling of Distinct Datapoints

* **Metric Conversion Logic Update**:
  - Replaced `createHelixMetric` with `createHelixMetrics` to generate individual `BMCHelixOMMetric` payloads for each datapoint instead of merging them into one. This ensures distinct datapoints are preserved. (`exporter/bmchelixexporter/internal/operationsmanagement/metrics_producer.go`)
  - Introduced `createSingleDatapointMetric` to handle the creation of metrics at the datapoint level. (`exporter/bmchelixexporter/internal/operationsmanagement/metrics_producer.go`)

* **Test Case Enhancements**:
  - Updated `TestProduceHelixPayload` to validate the creation of separate metrics for distinct datapoints. Added multiple datapoints in mock data and adjusted expected payload accordingly. (`exporter/bmchelixexporter/internal/operationsmanagement/metrics_producer_test.go`)

### Documentation and Changelog

* **Changelog Entry**:
  - Added a changelog entry to document the bug fix, specifying the change type as `bug_fix` and providing a brief description of the issue and resolution. (`.chloggen/bmchelixexporter_fix_datapoints_merge.yaml`)

#### Link to tracking issue
Fixes #40991

#### Testing

All entities are now automatically detected:
image

Metric sent successfully
image

### CODE REVIEW

File: exporter/bmchelixexporter/internal/operationsmanagement/metrics_producer.go [hunk 1]
```diff
@@ -106,12 +110,44 @@ func appendMetricWithParentEntity(helixMetrics []BMCHelixOMMetric, helixMetric B
...
+			dp := metric.Gauge().DataPoints().At(i)
+			metricPayload, err := mp.createSingleDatapointMetric(dp, metric, resourceAttrs)
+			if err != nil {
+				mp.logger.Warn("Failed to create Helix metric from datapoint", zap.Error(err))
+				continue
+			}
+			helixMetrics = append(helixMetrics, *metricPayload)
+		}
+	default:
+		return nil, fmt.Errorf("unsupported metric type %s", metric.Type())
```
Comment (bertysentry) [inline exporter/bmchelixexporter/internal/operationsmanagement/metrics_producer.go:148]: Maybe a "warning" is enough for this. It's normal to discard unsupported metrics.

**Review by bertysentry — APPROVED** [review]

File: exporter/bmchelixexporter/internal/operationsmanagement/metrics_producer.go (hunk 1 above)
Comment (NassimBtk) [reply exporter/bmchelixexporter/internal/operationsmanagement/metrics_producer.go:148]: Yes, `Errorf` formats the message using a format specifier and returns it as a value that implements the `error` interface. In this context, the caller logs it as a warning, so this behavior should be good.

File: exporter/bmchelixexporter/internal/operationsmanagement/metrics_producer.go [hunk 2]
```diff
@@ -61,13 +61,17 @@ func (mp *MetricsProducer) ProduceHelixPayload(metrics pmetric.Metrics) ([]BMCHe
...
+					mp.logger.Warn("Failed to create Helix metrics", zap.Error(err))
 					continue
 				}
 
-				helixMetrics = appendMetricWithParentEntity(helixMetrics, *newHelixMetric, containerParentEntities)
+				// Loop through the newly created metrics and append them to the helixMetrics slice
+				// while also creating parent entities for container metrics
+				for _, m := range newMetrics {
+					helixMetrics = appendMetricWithParentEntity(helixMetrics, m, containerParentEntities)
+				}
```
Comment (MovieStoreGuy) [inline exporter/bmchelixexporter/internal/operationsmanagement/metrics_producer.go:79]: It might be worth checking the size of the slice here to see if you need to grow the underlying capacity?

Save on additional reallocations.

File: exporter/bmchelixexporter/internal/operationsmanagement/metrics_producer.go [hunk 3]
```diff
@@ -106,12 +110,44 @@ func appendMetricWithParentEntity(helixMetrics []BMCHelixOMMetric, helixMetric B
 	return append(helixMetrics, helixMetric)
 }
 
-// createHelixMetric converts a single OpenTelemetry metric into a BMCHelixOMMetric payload
-func (mp *MetricsProducer) createHelixMetric(metric pmetric.Metric, resourceAttrs map[string]string) (*BMCHelixOMMetric, error) {
+// createHelixMetrics converts each OpenTelemetry datapoint into an individual BMCHelixOMMetric
+func (mp *MetricsProducer) createHelixMetrics(metric pmetric.Metric, resourceAttrs map[string]string) ([]BMCHelixOMMetric, error) {
+	var helixMetrics []BMCHelixOMMetric
```
Comment (MovieStoreGuy) [inline exporter/bmchelixexporter/internal/operationsmanagement/metrics_producer.go:120]: This currently is stack allocated, and could escape to the heap (which I imagine it would).

To save on potentially costly allocations, it might be worth to assign the capacity upfront?

File: exporter/bmchelixexporter/internal/operationsmanagement/metrics_producer.go [hunk 4]
```diff
@@ -106,12 +110,44 @@ func appendMetricWithParentEntity(helixMetrics []BMCHelixOMMetric, helixMetric B
...
+
+	switch metric.Type() {
+	case pmetric.MetricTypeSum:
+		for i := 0; i < metric.Sum().DataPoints().Len(); i++ {
+			dp := metric.Sum().DataPoints().At(i)
+			metricPayload, err := mp.createSingleDatapointMetric(dp, metric, resourceAttrs)
+			if err != nil {
+				mp.logger.Warn("Failed to create Helix metric from datapoint", zap.Error(err))
+				continue
+			}
```
Comment (MovieStoreGuy) [inline exporter/bmchelixexporter/internal/operationsmanagement/metrics_producer.go:132]: I wonder in this scenario should there be a metric to help track this event?

My concern is that people look at logs once they are aware of something being wrong, and this could hide from the user for a long time.

Comment (NassimBtk) [reply exporter/bmchelixexporter/internal/operationsmanagement/metrics_producer.go:132]: Yes, it’s feasible, but it would require some restructuring to determine where exactly the metric should be attached, particularly which monitor (with entityId, entityName and entityTypeId) and host it relates to. I’d prefer to handle this in a separate dedicated issue.

File: exporter/bmchelixexporter/internal/operationsmanagement/metrics_producer.go (hunk 2 above)
Comment (NassimBtk) [reply exporter/bmchelixexporter/internal/operationsmanagement/metrics_producer.go:79]: Yes, let's use `slices.Grow` to increase the slice's capacity if necessary.

**Review by MovieStoreGuy — APPROVED** [review]
