### PR TITLE
[receiver/prometheusremotewritereceiver] accept unspecified histograms

### LINKED ISSUE #41840: [receiver/prometheusremotewrite] Prometheus remote_write to prometheusremotewritereceiver fails with METRIC_TYPE_UNSPECIFIED
### Component(s)

receiver/prometheusremotewrite

## Description

Hi! I'm trying to forward metrics from Prometheus to OpenTelemetry Collector using the prometheusremotewritereceiver. Prometheus is receiving metrics via remote_write from several sources (mainly vmagent and prometheus-agent), then forwarding them to Otel Collector.

```mermaid
flowchart TD
    vma1(vmagent-01)
    vma2(vmagent-02)
    pa1(prometheus-agent-01)
    prometheus(Prometheus)
    otg(Otel Collector Gateway)
    prwr["Prometheus Remote<br>Write Receiver"]
    vma1 -->|Remote Write| prometheus
    vma2 -->|Remote Write| prometheus
    pa1  -->|Remote Write| prometheus
    prometheus -->|Remote Write| prwr
    prwr <--> otg
```
However, when Prometheus sends these metrics to Otel Collector, the collector rejects them with the following error: `METRIC_TYPE_UNSPECIFIED`

This happens for many metrics — the rejected type is always `METRIC_TYPE_UNSPECIFIED`

#### Prometheus config:
```yaml
global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

remote_write:
  - url: "http://192.168.138.91:32411/api/v1/write"
    name: "Remote write to Otelcol gateway"
    protobuf_message: io.prometheus.write.v2.Request
```

#### Collector config (relevant part):
```yaml
receivers:
  prometheusremotewrite:
    endpoint: 192.168.138.91:32411
  otlp:
    protocols:
      grpc:
        endpoint: 192.168.138.91:5555
      http:
        endpoint: 192.168.138.91:32412
``` 

## Expected Result
Metrics should be successfully forwarded from Prometheus to the OpenTelemetry Collector, even if the metrics were originally written to Prometheus via remote_write (e.g., by prometheus-agent or vmagent).

## Actual Result
The `prometheusremotewritereceiver` component rejects incoming metrics from Prometheus with `METRIC_TYPE_UNSPECIFIED` errors.

Example log output from Prometheus:
```
level=ERROR component=remote remote_name="Remote write to Otelcol gateway"
err="server returned HTTP status 400 Bad Request:
unsupported metric type \"METRIC_TYPE_UNSPECIFIED\" for metric \"angie_slabs_pages_slots_used\""
```

Let me know if you’d like me to provide full debug logs or a test environment to reproduce the issue.

### Collector version

0.131.1

## Environment
OS: Ubuntu 24.04
Compiler: go version go1.24.4 linux/amd64

### OpenTelemetry Collector configuration

```yaml

```

### Log output

```shell
Aug 07 13:33:01 test-monit-01 prometheus[186361]: time=2025-08-07T13:33:01.437+03:00 level=ERROR source=queue_manager.go:1668 msg="non-recoverable error" component=remote remote_name="Remote write to Otelcol gateway" url=http://192.168.138.91:32411/api/v1/write failedSampleCount=3995 failedHistogramCount=0 failedExemplarCount=0 err="server returned HTTP status 400 Bad Request: unsupported metric type \"METRIC_TYPE_UNSPECIFIED\" for metric \"node_network_mtu_bytes\"\nunsupported metric type \"METRIC_TYPE_UNSPECIFIED\" for metric \"node_network_mtu_bytes\"\nunsupported metric type \"METRIC_TYPE_UNSPECIFIED\" for metric \"node_network_mtu_bytes\"\nunsupported metric type \"METRIC_TYPE_UNSPECIFIED\" for metric \"node_network_mtu_bytes\"\nunsupported metric type \"METRIC_TYPE_UNSPECIFIED\" for metric \"node_network_mtu_bytes\"\nunsupported metric type \"METRIC_TYPE_UNSPECIFIED\" for metric \"node_network_name_assign_type\"\nunsupported metric type \"METRIC_TYPE_UNSPECIFIED\" for metric \"node_network_name_assign_type\"\nunsupported metric type \"METRIC_TYPE_UNSPECIFIED\" for metric \"node_network_name_assign_type\"\nunsupported metric type \"METRIC_TYPE_UNSPECIFIED\" for metric \"node_network_name_assign_type\"\nunsupported metric type \"METRIC_TYPE_UNSPECIFIED\" for metric \"node_network_name_assign_type\"\nunsupported metric type \"METRIC_TYPE_UNSPECIFIED\" for metric \"node_network_name_assign_type\"\nunsupported metric type \"METRIC_TYPE"

Aug 07 13:35:12 test-monit-01 prometheus[186361]: time=2025-08-07T13:35:12.942+03:00 level=ERROR source=queue_manager.go:1668 msg="non-recoverable error" component=remote remote_name="Remote write to Otelcol gateway" url=http://192.168.138.91:32411/api/v1/write failedSampleCount=3995 failedHistogramCount=0 failedExemplarCount=0 err="server returned HTTP status 400 Bad Request: unsupported metric type \"METRIC_TYPE_UNSPECIFIED\" for metric \"node_disk_filesystem_info\"\nunsupported metric type \"METRIC_TYPE_UNSPECIFIED\" for metric \"node_disk_filesystem_info\"\nunsupported metric type \"METRIC_TYPE_UNSPECIFIED\" for metric \"node_disk_filesystem_info\"\nunsupported metric type \"METRIC_TYPE_UNSPECIFIED\" for metric \"node_disk_filesystem_info\"\nunsupported metric type \"METRIC_TYPE_UNSPECIFIED\" for metric \"node_disk_filesystem_info\"\nunsupported metric type \"METRIC_TYPE_UNSPECIFIED\" for metric \"node_disk_flush_requests_time_seconds_total\"\nunsupported metric type \"METRIC_TYPE_UNSPECIFIED\" for metric \"node_disk_flush_requests_time_seconds_total\"\nunsupported metric type \"METRIC_TYPE_UNSPECIFIED\" for metric \"node_disk_flush_requests_time_seconds_total\"\nunsupported metric type \"METRIC_TYPE_UNSPECIFIED\" for metric \"node_disk_flush_requests_time_seconds_total\"\nunsupported metric type \"METRIC_TYPE_UNSPECIFIED\" for metric \"node_disk_flush_requests_time_seconds_total\"\nunsupported metric type \"METRIC_TYPE_UNSPECI"
```

## Additional context
In Prometheus, when using remote_write, metric types are not explicitly defined — they are inferred based on the metric’s structure and behavior. This might be the reason why the receiver is unable to handle them.

As far as I understand, the OpenTelemetry Collector might expect the metric type to be explicitly set, which Prometheus does not do for remote_write — especially if the metrics were ingested into Prometheus via remote_write themselves (e.g., from prometheus-agent, vmagent, etc.)

### Tip

<sub>[React](https://github.blog/news-insights/product-news/add-reactions-to-pull-requests-issues-and-comments/) with 👍 to help prioritize this issue. Please use comments to provide useful context, avoiding `+1` or `me too`, to help us triage it. Learn more [here](https://opentelemetry.io/community/end-user/issue-participation/).</sub>

### PR DESCRIPTION
**Pull request by jelly-afk**
#### Description
prometheusremote write receiver now accepts histogram with unspecified metric type.

#### Link to tracking issue
Fixes #41840 

#### Testing
Added two test cases in the TestTranslateV2 test function to test unspecified histograms.

### CODE REVIEW

File: receiver/prometheusremotewritereceiver/receiver.go [hunk 1]
```diff
@@ -513,6 +514,12 @@ func (prw *prometheusRemoteWriteReceiver) processHistogramTimeSeries(
 				hist.SetAggregationTemporality(pmetric.AggregationTemporalityCumulative)
 			}
 			metricCache[metricIDHash] = histMetric
+			switch ts.Metadata.Type {
+			case writev2.Metadata_METRIC_TYPE_HISTOGRAM:
+				histMetric.Metadata().PutStr(prometheus.MetricMetadataTypeKey, "histogram")
+			default:
```
Comment (perebaj) [inline receiver/prometheusremotewritereceiver/receiver.go]: isn't not missing this case -> writev2.Metadata_METRIC_TYPE_UNSPECIFIED

**Comment by VihasMakwana** [comment]
@jelly-afk Could you please fix the CI?

**Review by VihasMakwana — APPROVED** [review]
Looks good. Needs a codeowner review to be `ready-to-merge`

File: receiver/prometheusremotewritereceiver/receiver.go [hunk 2]
```diff
@@ -513,6 +514,13 @@ func (prw *prometheusRemoteWriteReceiver) processHistogramTimeSeries(
 				hist.SetAggregationTemporality(pmetric.AggregationTemporalityCumulative)
 			}
 			metricCache[metricIDHash] = histMetric
+			switch ts.Metadata.Type {
+			case writev2.Metadata_METRIC_TYPE_HISTOGRAM:
+				histMetric.Metadata().PutStr(prometheus.MetricMetadataTypeKey, "histogram")
+			case writev2.Metadata_METRIC_TYPE_UNSPECIFIED:
+				histMetric.Metadata().PutStr(prometheus.MetricMetadataTypeKey, "unknown")
+			default:
+			}
```
Comment (perebaj) [inline receiver/prometheusremotewritereceiver/receiver.go:526]: Maybe the default case should return an error? This because we are talking about a not listed case/

File: receiver/prometheusremotewritereceiver/receiver_test.go [hunk 3]
```diff
@@ -1410,6 +1412,158 @@ func TestTranslateV2(t *testing.T) {
...
+					"job",
+					"test",
+					"instance",
+					"localhost:8080",
+					"seconds",
+					"Test NHCB histogram",
+				},
+				Timeseries: []writev2.TimeSeries{
+					{
+						LabelsRefs:       []uint32{1, 2, 3, 4, 5, 6}, // __name__=test_hncb_histogram, job=test, instance=localhost:8080
```
Comment (perebaj) [inline receiver/prometheusremotewritereceiver/receiver_test.go]: I think that this comment doesn't help us a lot. WDYT?
```suggestion
						LabelsRefs:       []uint32{1, 2, 3, 4, 5, 6}, 
						instance=localhost:8080
```

File: receiver/prometheusremotewritereceiver/receiver_test.go [hunk 4]
```diff
@@ -1410,6 +1412,158 @@ func TestTranslateV2(t *testing.T) {
...
+				Symbols: []string{
+					"",
+					"__name__",
+					"test_hncb_histogram",
+					"job",
+					"test",
+					"instance",
+					"localhost:8080",
+					"seconds",
+					"Test NHCB histogram",
```
Comment (perebaj) [inline receiver/prometheusremotewritereceiver/receiver_test.go]: Can we follow the same pattern as the other test cases?
```suggestion
					"",
					"__name__", "test_hncb_histogram", // 1, 2
					"job", "test", // 3, 4
					"instance", "localhost:8080", // 5, 6
					"seconds", "Test NHCB histogram", // 7, 8
```

Maybe accepting this change, the linter will break.

File: receiver/prometheusremotewritereceiver/receiver.go (hunk 2 above)
Comment (perebaj) [reply receiver/prometheusremotewritereceiver/receiver.go:526]: @ArthurSens or @dashpole do you have a different opinion about it?

**Review by perebaj — COMMENTED** [review]
Just some nits. But many thanks for that effort!

File: receiver/prometheusremotewritereceiver/receiver.go (hunk 2 above)
Comment (jelly-afk) [reply receiver/prometheusremotewritereceiver/receiver.go:526]: We shouldn't encounter any other metric types here, as we have already validated the types [here](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/44091/files#diff-e26ac1e595473c2a7f1cf349aee9b1cceced9c8f9c4615b08be8b9e551edfcd9R344)

`if ts.Metadata.Type == writev2.Metadata_METRIC_TYPE_HISTOGRAM || ts.Metadata.Type == writev2.Metadata_METRIC_TYPE_UNSPECIFIED && len(ts.Histograms) > 0 `

So it can only be either a histogram or an unspecified histogram.

Comment (perebaj) [reply receiver/prometheusremotewritereceiver/receiver.go:526]: What do you think if we add a comment under the default option with this info? Saying that as we are only dealing with histograms inside the `processHistogramTimeSeries` we don't need to define a behavior for this option.

Comment (jelly-afk) [reply receiver/prometheusremotewritereceiver/receiver.go:526]: Sounds good.

**Review by ArthurSens — APPROVED** [review]
LGTM, thank you :)
