### PR TITLE
[cmd/telemetrygen] remove reliance on JSON unmarshalling for status code string

### LINKED ISSUE #25906: [cmd/telemetrygen] default value `Unset` of args `status-code` is illegal
### Component(s)

cmd/telemetrygen

## Description

the default value `Unset` of args `status-code` is not legal.

```
Error: expected `status-code` to be one of (Unset, Error, Ok) or (0, 1, 2), got "Unset" instead
```

## Steps to Reproduce

do not specify the args `status-code` to start `telemetrygen traces`

## Expected Result

do not fail 

### Collector version

0.83.0

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

### OpenTelemetry Collector configuration

_No response_

### Log output

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by jmsnll**
**Description:** 

Removes the use of JSON Unmarshalling when determining the provided trace status code.

The existing implementation allowed both status code and status strings to be set using the command line flag `--status-code` without issue however it's not obvious that the default command line value must be a JSON string as encountered in #25906

I've replaced the existing code with a switch-case statement which is more explicit. Additionally, the code now checks the lowercase version of the provided string, enabling support for mixed-case inputs such as `--status-code unset` and `--status-code Unset` flags.

I'm undecided if this is actually better or required since we now understand the original cause of the issue.

Example usage is now:

```
telemetrygen traces --otlp-insecure --traces 1 --status-code 0 # unset
telemetrygen traces --otlp-insecure --traces 1 --status-code 1 # error
telemetrygen traces --otlp-insecure --traces 1 --status-code 2 # ok 
telemetrygen traces --otlp-insecure --traces 1 --status-code unset
telemetrygen traces --otlp-insecure --traces 1 --status-code error
telemetrygen traces --otlp-insecure --traces 1 --status-code ok
```

**Link to tracking Issue:** Fixes #25906

**Testing:** 

Added additional test cases and implemented sub-tests as the tests were quitting after the first falsified case.

**Documentation:** No updates to documentation.

### CODE REVIEW

File: cmd/telemetrygen/internal/traces/traces.go [hunk 1]
```diff
@@ -123,13 +124,18 @@ func Run(c *Config, logger *zap.Logger) error {
 	}
 
 	var statusCode codes.Code
-	if c.StatusCode == "" {
+
+	switch strings.ToLower(c.StatusCode) {
+	case "0", "unset", "":
```
Comment (jmsnll) [inline cmd/telemetrygen/internal/traces/traces.go:129]: I was going to use `codes.Unset.String()` here but went for hard coding the values since they are unlikely to change and its easier to read when having the mixed case functionality.

**Review by codeboten — APPROVED** [review]
Thanks @jmsnll for fixing this 👍🏻

**Review by fatsheep9146 — CHANGES_REQUESTED** [review]
Thanks for contribution! 
I think we'd better merge this after https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/26668 is merged, in order to double check is pr is valid.

**Review by mx-psi — APPROVED** [review]

**Review by fatsheep9146 — APPROVED** [review]

**Comment by fatsheep9146** [comment]
> > I merged #26668, @fatsheep9146 can you take another look?
> 
> Thanks, I just merged the main to see if the check is passed @mx-psi
> 
> After all checks are passed, I will approve the pr.

All related checks are passed, I approved the pr @mx-psi
