### PR TITLE
[processor/groupbyattrs] Updated metric copy to take into consideration custom properties for …

### LINKED ISSUE #9981: prometheusremotewrite exporter doesn't work well with groupbyattrs processor?
**Describe the bug**
When enable `groupbyattrs` processor in metrics pipeine and use `prometheusremotewrite` exporter, it fails during prometheus translator at [here](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/pkg/translator/prometheusremotewrite/metrics_to_prw.go#L64-L65) probably because flag like`pmetric.MetricAggregationTemporalityCumulative` was removed by `groupbyattrs` processor.

**Steps to reproduce**
Please use the given config to reproduce this error `Permanent error: invalid temporality and type combination`

**What did you expect to see?**
things to work while having these 2 components in a pipeline

**What did you see instead?**
```
2022-05-12T22:46:09.098+0800    error   exporterhelper/queued_retry.go:183      Exporting failed. The error is not retryable. Dropping data.    {"kind": "exporter", "name": "prometheusremotewrite", "error": "Permanent error: invalid temporality and type combination; invalid temporality and type combination; invalid temporality and type combination; invalid temporality and type combination; Permanent error: Permanent error: remote write returned HTTP status 404 Not Found; err = <nil>: 404 page not found\n", "errorCauses": [{"error": "Permanent error: invalid temporality and type combination; invalid temporality and type combination; invalid temporality and type combination; invalid temporality and type combination"}, {"error": "Permanent error: Permanent error: remote write returned HTTP status 404 Not Found; err = <nil>: 404 page not found\n"}], "dropped_items": 15}
```

**What version did you use?**
Version: v0.50.0

**What config did you use?**
Config: (e.g. the yaml config file)
```yaml
receivers:
  prometheus:
    config:
      scrape_configs:
        - job_name: kubernetes-cadvisor-metrics
          static_configs:
            - targets:
                - localhost:8888
              labels:
                k: v

exporters:
  prometheusremotewrite:
    endpoint: http://localhost:8888


processors:
  groupbyattrs:
    keys:
      - k

service:
  telemetry:
    logs:
      level: debug
    metrics:
      level: detailed
      address: 127.0.0.1:8888
  pipelines:
    metrics:
      receivers: [prometheus]
      processors: [groupbyattrs]
      exporters: [ prometheusremotewrite]
```

**Environment**
OS: MacOS 12.3.1
Compiler(if manually compiled): go 1.17.8

**Additional context**

### PR DESCRIPTION
**Pull request by crobertson-conga**
…Histogram, ExponentialHistogram and Sum type metrics.

**Description:** 
Fixing a bug by copying over source temporality change

**Link to tracking Issue:** [9087](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/9087)

**Testing:**
Updated tests for the processor to have a histogram metric type.

**Documentation:** <Describe the documentation added.>\

Fixes: https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/9981

### CODE REVIEW

**Comment by pmm-sumo** [comment]
Thank you for the contribution @crobertson-conga Before we can proceed you need to sign the CLA first. [Contributing guide](https://github.com/open-telemetry/community/blob/main/CONTRIBUTING.md) has the details on that

File: processor/groupbyattrsprocessor/processor.go [hunk 1]
```diff
@@ -219,6 +219,20 @@ func getMetricInInstrumentationLibrary(ilm pdata.ScopeMetrics, searchedMetric pd
...
+
+	case pdata.MetricDataTypeHistogram:
+		metric.Histogram().SetAggregationTemporality(searchedMetric.Histogram().AggregationTemporality())
+
+	case pdata.MetricDataTypeExponentialHistogram:
+		metric.ExponentialHistogram().SetAggregationTemporality(searchedMetric.ExponentialHistogram().AggregationTemporality())
+
+	case pdata.MetricDataTypeSum:
+		metric.Sum().SetAggregationTemporality(searchedMetric.Sum().AggregationTemporality())
+
```
[the remark this answers is not in the document]
Comment (crobertson-conga) [reply processor/groupbyattrsprocessor/processor.go:236]: Good idea, updated PR to reflect this.

**Comment by crobertson-conga** [comment]
Took me a bit to get the CLA approved, but that is now in place.

File: processor/groupbyattrsprocessor/processor.go [hunk 2]
```diff
@@ -222,6 +222,29 @@ func getMetricInInstrumentationLibrary(ilm pmetric.ScopeMetrics, searchedMetric
...
+		metric.ExponentialHistogram().SetAggregationTemporality(searchedMetric.ExponentialHistogram().AggregationTemporality())
+
+	case pmetric.MetricDataTypeSum:
+		metric.Sum().SetAggregationTemporality(searchedMetric.Sum().AggregationTemporality())
+
+	case pmetric.MetricDataTypeGauge:
+	case pmetric.MetricDataTypeSummary:
+
+	default:
+		gap.logger.Error("Unhandled metric data type.",
```
Comment (pmm-sumo) [inline processor/groupbyattrsprocessor/processor.go:241]: Since this can be logged a lot if happens, I think it would be good to ensure we don't cause flood here. One solution is to [copy approach similar to this one](https://github.com/open-telemetry/opentelemetry-collector/blob/main/exporter/exporterhelper/queued_retry.go#L61-L78)

**Review by pmm-sumo — DISMISSED** [review]
Added one more comment on logging but I think it's not a blocker. 

Also seems something is off with recent pdata change. Linter and unittest fail. For the latter the error is:
```
FAIL	github.com/open-telemetry/opentelemetry-collector-contrib/processor/groupbyattrsprocessor [setup failed]
Error: processor_test.go:26:2: missing go.sum entry for module providing package go.opentelemetry.io/collector/model/pdata (imported by github.com/open-telemetry/opentelemetry-collector-contrib/processor/groupbyattrsprocessor); to add:
```

Second pair of eyes would be helpful :) Perhaps @jpkrohling could you look as well?

File: processor/groupbyattrsprocessor/processor.go (hunk 2 above)
Comment (pmm-sumo) [reply processor/groupbyattrsprocessor/processor.go:241]: To add further context, I think the components are using the logger defined here: https://github.com/open-telemetry/opentelemetry-collector/blob/main/service/internal/telemetrylogs/logger.go#L31-L34 - so we're already somewhat covered

File: processor/groupbyattrsprocessor/processor_test.go [hunk 3]
```diff
@@ -17,10 +17,13 @@ package groupbyattrsprocessor
 import (
 	"context"
 	"fmt"
+	"math/rand"
+	"sort"
 	"testing"
 	"time"
 
 	"github.com/stretchr/testify/assert"
+	"go.opentelemetry.io/collector/model/pdata"
```
Comment (pmm-sumo) [inline processor/groupbyattrsprocessor/processor_test.go:26]: I think this is no longer being used

File: processor/groupbyattrsprocessor/processor_test.go [hunk 4]
```diff
@@ -139,6 +142,62 @@ func someComplexMetrics(withResourceAttrIndex bool, rmCount int, ilmCount int, d
 	return metrics
 }
 
+func someComplexHistogramMetrics(withResourceAttrIndex bool, rmCount int, ilmCount int, dataPointCount int, histogramSize int) pdata.Metrics {
```
Comment (pmm-sumo) [inline processor/groupbyattrsprocessor/processor_test.go:145]: I believe the return type should be `pmetric.Metric`

Comment (crobertson-conga) [reply processor/groupbyattrsprocessor/processor_test.go]: Fixed

**Review by pmm-sumo — APPROVED** [review]

File: processor/groupbyattrsprocessor/processor.go (hunk 2 above)
Comment (jpkrohling) [reply processor/groupbyattrsprocessor/processor.go:241]: That's still a lot and meant only as a general protection. Given that we know this can happen a lot, we should really just log it once per data dimension (metric name? some resource attribute?).

**Review by jpkrohling — COMMENTED** [review]
Metrics aren't my strongest side, not sure I can really judge the business here.

File: processor/groupbyattrsprocessor/processor.go (hunk 2 above)
Comment (crobertson-conga) [reply processor/groupbyattrsprocessor/processor.go:241]: The only way this happens is if there is a brand new metric type introduced into the ecosystem....and that metric type gets used by a target system with the groupbyattrs. I can move it, but I think a noisy error might be good, especially with the sampling already in place at a higher level.

Or I guess another way is if somehow a None metric type gets through here? but that's probably indicative of a bigger issue.

**Comment by crobertson-conga** [comment]
Is there anything else that needs to be done on this in order to get this in the next release?

**Comment by pmm-sumo** [comment]
> Is there anything else that needs to be done on this in order to get this in the next release?

I think @jpkrohling [comment](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/9088#discussion_r853321552) needs to be addressed. I think that copy/pasting (or even better adding it to some common package) [the sampled logger](https://github.com/open-telemetry/opentelemetry-collector/blob/main/exporter/exporterhelper/queued_retry.go#L61-L78) is the simplest solution

**Comment by crobertson-conga** [comment]
Okay, I think I've done all the needed things for this now.

**Comment by crobertson-conga** [comment]
Is there anything else that needs to be done here?

**Comment by pmm-sumo** [comment]
> Is there anything else that needs to be done here?

We could use another pair of eyes :) Not sure if @jpkrohling will manage to take a look today, if not, maybe one of the other @open-telemetry/collector-contrib-approvers could help?

File: processor/groupbyattrsprocessor/processor.go [hunk 5]
```diff
@@ -222,6 +222,29 @@ func getMetricInInstrumentationLibrary(ilm pmetric.ScopeMetrics, searchedMetric
...
+	switch metric.DataType() {
+
+	case pmetric.MetricDataTypeHistogram:
+		metric.Histogram().SetAggregationTemporality(searchedMetric.Histogram().AggregationTemporality())
+
+	case pmetric.MetricDataTypeExponentialHistogram:
+		metric.ExponentialHistogram().SetAggregationTemporality(searchedMetric.ExponentialHistogram().AggregationTemporality())
+
+	case pmetric.MetricDataTypeSum:
+		metric.Sum().SetAggregationTemporality(searchedMetric.Sum().AggregationTemporality())
```
Comment (dmitryax) [inline processor/groupbyattrsprocessor/processor.go:235]: Can you add setting of `IsMonotonic` field here as well?

File: processor/groupbyattrsprocessor/processor.go (hunk 2 above)
Comment (dmitryax) [reply processor/groupbyattrsprocessor/processor.go:241]: This must be a unreachable part of the code. `getMetricInInstrumentationLibrary -> getGroupedMetricsFromAttributes` are called from cases related particular data type in `processMetrics`. So this seems to be not the right place to catch invalid metrics. Let's remove `default` along with other cases where there is no action

File: processor/groupbyattrsprocessor/factory.go [hunk 6]
```diff
@@ -64,6 +66,8 @@ func createGroupByAttrsProcessor(logger *zap.Logger, attributes []string) *group
 	var nonEmptyAttributes []string
 	presentAttributes := make(map[string]struct{})
 
+	var sampledLogger = createSampledLogger(logger)
```
[the remark this answers is not in the document]
Comment (dmitryax) [reply processor/groupbyattrsprocessor/factory.go:69]: Based on what I found in a comment below, looks like it's not needed at all

File: processor/groupbyattrsprocessor/processor.go (hunk 2 above)
Comment (crobertson-conga) [reply processor/groupbyattrsprocessor/processor.go:241]: Originally I had only the cases affected.  @pmm-sumo said it would be a good idea to capture this per: https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/9088/files/d2f93c94193f04a51d9245022a678c0b02192484#r842907003
This code should never be called unless the spec changes.  I'm ambivalent as to have this code or not, so will defer to you guys.

Comment (pmm-sumo) [reply processor/groupbyattrsprocessor/processor.go:242]: Yeah, it's unreachable now but if other metric data type would be added in the future and this part would not be updated, we want to have a mechanism to notify about it

Comment (dmitryax) [reply processor/groupbyattrsprocessor/processor.go:242]: Not only spec. Call of this function is leads to these switch cases: https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/processor/groupbyattrsprocessor/processor.go#L130-L164. So in order to run into this code another case statement is needed there. If we want to catch invalid metrics, I don't believe this is the right place. If we really want to do that, I think it's better to add it higher the call stack, e.g. in the switch case that I mentioned

**Comment by crobertson-conga** [comment]
Fixed the changelog conflict, can we get this merged?

File: processor/groupbyattrsprocessor/factory.go (hunk 6 above)
[the remark this answers is not in the document]
Comment (pmm-sumo) [reply processor/groupbyattrsprocessor/factory.go:69]: We had a related discussion and the outcome was that we don't want to introduce sampled logger in that way. There's a more generic solution that as I understand @dmitryax wants to work on and we'll address it then. Right now, lets remove it

File: processor/groupbyattrsprocessor/processor.go (hunk 2 above)
Comment (pmm-sumo) [reply processor/groupbyattrsprocessor/processor.go:242]: As discussed on the sampled logger, we don't want to handle that today. So from that perspective, we can move it to "debug" level and maybe leave a TODO item.

Having said that, I now see that if we really want do it right, then it should be in a different place, as @dmitryax pointed out.

Taking it all together, I'm leaning towards removing this section and maybe opening an issue on handling the unexpected values better (and addressing it in a separate PR)

Comment (dmitryax) [reply processor/groupbyattrsprocessor/processor.go:242]: Sounds like we have an agreement here. @crobertson-conga can you please remove the `default` case along with other cases with no action

**Comment by crobertson-conga** [comment]
Any chance of getting this in soon?

**Comment by dmitryax** [comment]
@crobertson-conga can you please address the latest comments in https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/9088#discussion_r867012376

File: processor/groupbyattrsprocessor/factory.go (hunk 6 above)
[the remark this answers is not in the document]
Comment (dmitryax) [reply processor/groupbyattrsprocessor/factory.go:69]: @crobertson-conga, this is also not needed anymore

File: processor/groupbyattrsprocessor/processor.go (hunk 2 above)
Comment (crobertson-conga) [reply processor/groupbyattrsprocessor/processor.go]: Cool, for some reason I didn't see this comment a few days ago.  Removed the sampling code, this should be good to go.

**Review by dmitryax — APPROVED** [review]

**Comment by crobertson-conga** [comment]
Just resolved the changelog conflicts again, can we get this merged?

**Comment by pmm-sumo** [comment]
This is now labeled as such, which means that one of the maintainers will probably handle that very soon @crobertson-conga

**Comment by dmitryax** [comment]
@codeboten pleases help to merge this
