### PR TITLE
Fix data race in remoteConfig from opampsupervisor

### LINKED ISSUE #44173: Data race in Supervisor's remoteConfig field with concurrent access
### Component(s)

cmd/opampsupervisor

### What happened?

The `Supervisor` struct's `remoteConfig` field is accessed concurrently without synchronization, causing a data race.

**What happens:**

1. The `remoteConfig` field (`*protobufs.AgentRemoteConfig`) is read and written from multiple goroutines:
   - Written in `processRemoteConfigMessage()` when receiving config from the OpAMP server
   - Written in `loadRemoteConfig()` during initialization
   - Read in `composeMergedConfig()` calls from multiple places (`loadAndWriteInitialMergedConfig()`, `setupOwnTelemetry()`, `processRemoteConfigMessage()`, `processAgentIdentificationMessage()`)
   - Read in `saveAndReportConfigStatus()` to get the config hash

2. Concurrent access can occur when:
   - A new remote config arrives while the supervisor is composing a merged config
   - The supervisor is reading `remoteConfig` while another goroutine updates it
   - Multiple goroutines access `remoteConfig` simultaneously

3. This leads to:
   - Data races detected by the race detector
   - Potential nil pointer dereferences if a read happens during a write
   - Undefined behavior from reading partially written values

**Additional context:**

The `saveAndReportConfigStatus()` method accesses `s.remoteConfig.GetConfigHash()` without checking if `remoteConfig` is nil, which can cause a panic if accessed before any remote config is received.

### Collector version

380f40a40406e160c4bfbd8c8561d0658fa52e15

### Environment information

_No response_

### OpenTelemetry Collector configuration

```yaml

```

### Log output

```shell

```

### Additional context

_No response_

### Tip

<sub>[React](https://github.blog/news-insights/product-news/add-reactions-to-pull-requests-issues-and-comments/) with 👍 to help prioritize this issue. Please use comments to provide useful context, avoiding `+1` or `me too`, to help us triage it. Learn more [here](https://opentelemetry.io/community/end-user/issue-participation/).</sub>

### PR DESCRIPTION
**Pull request by iblancasa**
#### Link to tracking issue
Fixes #44173

#### Testing
1. I implemented the test
2. The race condition appears
3. Applied the fix and rerun the test
4. No issues

### CODE REVIEW

File: cmd/opampsupervisor/supervisor/supervisor.go [hunk 1]
```diff
@@ -1594,8 +1594,24 @@ func (s *Supervisor) runAgentProcess() {
 				s.telemetrySettings.Logger.Error("Could not report health to OpAMP server", zap.Error(err))
 			}
 
-			// TODO: decide why the agent stopped. If it was due to bad config, report it to server.
-			// https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/21079
+			// If agent crashed while we were waiting for config to be applied (timeout timer is running),
+			// report the config as FAILED immediately rather than waiting for the timeout.
```
Comment (crobert-1) [inline cmd/opampsupervisor/supervisor/supervisor.go:1598]: Is there any reason the agent could crash at this point other than the config being bad?

**Review by crobert-1 — APPROVED** [review]

File: cmd/opampsupervisor/supervisor/supervisor.go (hunk 1 above)
Comment (iblancasa) [reply cmd/opampsupervisor/supervisor/supervisor.go:1598]: I guess it can happen if there are bugs in the agent too.

Comment (crobert-1) [reply cmd/opampsupervisor/supervisor/supervisor.go:1598]: I guess wording my question another way, is there any kind of failure that could be hit here that we'd actually want to retry? Or is the best UX to stop trying every time no matter what if we get to this point?

Comment (iblancasa) [reply cmd/opampsupervisor/supervisor/supervisor.go:1598]: I think the supervisor should keep retrying. This can be because a bad config or a transient crash like resource pressure, manual kill, dependency failure...

Comment (crobert-1) [reply cmd/opampsupervisor/supervisor/supervisor.go:1598]: Okay, my ignorance is showing here. From the comment, it sounded like it used to retry but no longer does, but I must have missed the context here. So it's still retrying as it should, is that right?

Comment (iblancasa) [reply cmd/opampsupervisor/supervisor/supervisor.go:1598]: Yes. What this PR changes is that we no longer wait to the timeout. If we received an error we directly report it without waiting.
