### PR TITLE
pkg/resourcetotelemetry: add resource attributes to remaining metric points

### LINKED ISSUE #7525: [pkg/resourcetotelemetry] Support for ExponentialHistogram
**Describe the bug**

Similar to #7523, we need to add support for ExponentialHistogram.

**Steps to reproduce**

Send an ExponentialHistogram to a pipeline that uses the `pkg/resourcetotelemetry`. 

**What did you expect to see?**

Datapoints should have resource-level attributes as datapoint-level attributes.

**What did you see instead?**

Datapoints are kept as is.

**What version did you use?**

Should happen as of 36623bcdc41f9663c99e247e63b43d6735c0ba27

**What config did you use?**

n/a

**Environment**

n/a

**Additional context**

Should we also log something if a point has an unrecognized datatype?

### PR DESCRIPTION
**Pull request by Aneurysm9**
Signed-off-by: Anthony J Mirabella <a9@aneurysm9.com>

### CODE REVIEW

**Review by mx-psi — APPROVED** [review]

**Comment by mx-psi** [comment]
Also happens with ExponentialHistogram, filed #7525 for this

**Comment by Aneurysm9** [comment]
> Also happens with ExponentialHistogram, filed #7525 for this

Good catch.  I've added a fix for that here since it's the same thing.  This is a case where generics would likely be helpful.

**Review by mx-psi — APPROVED** [review]

File: pkg/resourcetotelemetry/resource_to_telemetry.go [hunk 1]
```diff
@@ -83,6 +83,10 @@ func addAttributesToMetric(metric *pdata.Metric, labelMap pdata.AttributeMap) {
 		addAttributesToNumberDataPoints(metric.Sum().DataPoints(), labelMap)
 	case pdata.MetricDataTypeHistogram:
 		addAttributesToHistogramDataPoints(metric.Histogram().DataPoints(), labelMap)
+	case pdata.MetricDataTypeSummary:
+		addAttributesToSummaryDataPoints(metric.Summary().DataPoints(), labelMap)
+	case pdata.MetricDataTypeExponentialHistogram:
+		addAttributesToExponentialHistogramDataPoints(metric.ExponentialHistogram().DataPoints(), labelMap)
 	}
```
Comment (bogdandrutu) [inline pkg/resourcetotelemetry/resource_to_telemetry.go:90]: Is there any linter that we can enable to check this? I know is hard since there is no enum type, but maybe some structure tags can help. This needs to be investigated because I bet there are more places like this.

**Review by codeboten — APPROVED** [review]

File: pkg/resourcetotelemetry/resource_to_telemetry.go (hunk 1 above)
Comment (Aneurysm9) [reply pkg/resourcetotelemetry/resource_to_telemetry.go:90]: https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/7532
