### PR TITLE
[processor/tailsampling] Simplify tsp locking

### LINKED ISSUE #41656: [processor/tailsampling] Possible data loss due to improper concurrency
### Component(s)

processor/tailsampling

### What happened?

# Background

I've spent the last week investigating spikes in "dropped too early" errors in
the tailsampling processor. Specifically, I've been looking at scenarios where
traces are dropped prematurely despite being nowhere near the num_traces limit.

There are two possible scenarios in the tailsampling processor that can lead to
data loss. One is a race condition between the goroutine evaluating policies
and the goroutines consuming traces into the processor. The other is a
configuration edge case where traces can be dropped incorrectly if the decision
cache is too small when compared to the num_traces limit.

I'm creating this issue to document the findings and also to discuss potential
solutions.

## Race condition

```mermaid
sequenceDiagram
	participant G1 as Goroutine 1
	participant G2 as Goroutine 2
	participant G3 as Goroutine 3
	participant Cache
	participant idToTrace
	participant Batcher

	G1->>Cache: Get (miss)
	G2->>G2: OnTick
	G2->>G2: makeDecision
	G2->>Cache: Put
	G2->>idToTrace: Delete
	G1->>idToTrace: LoadOrStore
	G1->>Batcher: AppendToCurrentBatch
	Note right of G1: At this point, trace ID is in Batcher, idToTrace, and Cache
	G3->>Cache: Get (hit)
	G3->>idToTrace: Delete
	Note right of G3: G3 has dropped data added by G1, orphaning trace ID in Batcher
	G2->>Batcher: CloseCurrentAndTakeFirstBatch
	G2->>idToTrace: Load (miss)
	Note right of G2: This is the droppedTooEarly signal
```

This race condition arises due to concurrent access and modification of the processor's internal state by multiple goroutines. Specifically, one goroutine (G1) is consuming new traces and attempting to store them, while another (G2) is evaluating sampling policies and updating the decision cache and trace map. Meanwhile, a third goroutine (G3) may also be consuming traces and acting on cache hits.

The sequence is as follows:
- G1 processes a new trace and misses the decision cache, so it proceeds to store the trace in the `idToTrace` map and appends the trace ID to the batcher for later policy evaluation.
- G2, running the periodic policy evaluation, makes a sampling decision for the same trace, updates the decision cache, and deletes the trace from `idToTrace`.
- G1, unaware that G2 has just deleted the trace, completes its `LoadOrStore` operation, potentially re-inserting the trace into `idToTrace` and appending the trace ID to the batcher.
- G3, processing another span for the same trace, finds a hit in the decision cache and deletes the trace from `idToTrace` again.
- Later, G2 closes the current batch in the batcher and attempts to retrieve the trace from `idToTrace`, but finds it missing ("dropped too early").

## Configuration Edge Case

A second root cause for the "dropped too early" issue is the interaction between the `num_traces` map size and the effective retention period of the decision cache, which is determined by its size and the trace ingestion rate.

The decision cache is an LFU (Least Frequently Used) cache with a fixed number of entries. As new traces arrive, old entries are evicted based on usage frequency, not age. This means the "duration" a decision remains in the cache is effectively determined by how quickly the cache fills up, which is a function of the cache size and the trace ingestion rate.

"Dropped too early" events can occur after the processor has been running long enough to fill the `num_traces` map at the current ingestion rate. For example, with a map size of 500,000 and an ingestion rate of 200-300 traces per second, the map fills in about 2,200 seconds (~36 minutes). If the decision cache is smaller than the map, and the ingestion rate is low, a trace's decision may be evicted from the cache before the trace ID is evicted from the map.

The sequence for data loss is:
- New spans arrive for a trace (e.g., trace 123).
- There is no cached decision for the trace.
- There is no entry for the trace in `idToTrace`.
- The trace is added to `idToTrace`.
- If the map (`deleteChan`) is full, an old trace ID is removed to make space.
- The removed trace ID might belong to a trace that is still active, but its decision has already been evicted from the cache due to the cache's limited size and the ingestion rate.

This problem is most pronounced in environments with lower trace ingestion rates, where it takes longer to fill the map than it does to evict a decision from the cache. In high-ingestion environments, the map fills quickly, so trace IDs are evicted before their decisions are evicted from the cache, and the issue does not occur.

If the effective retention period of the decision cache (cache size divided by ingestion rate) is shorter than the time required to fill the `num_traces` map, traces can be dropped prematurely. To avoid this, configure the decision cache size so that its effective retention period matches or exceeds the map fill time.

## Proposal

In the short term, I have two PRs inprogress:

- [x] [Fix the race condition by avoiding state manipulation during ConsumeTraces.](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/41617)
- [x] [Add BlockOnOverflow option](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/41546)

With these two changes together, it's possible to run a decision cache with a small size while avoiding dropped too early errors. It still leaves two open issues:

1. In the case where the race condition previously would have triggered, now it will make an incomplete sampling decision on partial data. Better, but only in cases where the decision is the same.
2. The BlockOnOverflow option introduces backpressure on the trace ingestion path. This is a good thing in some contexts, but not in others.

In order to address these issues, it feels right to refactor the TSP to avoid having so many sources of truth for trace data. Currently there are 3:

1. The `idToTrace` map stores a map from trace ID to trace data and the decisions when decision cache is disabled.
2. The `deleteChan` queue stores trace IDs in FIFO order in order to be able to drop old trace IDs when the `num_traces` limit is reached.
3. The `decisionCache` stores the sampling decision for each trace ID, up to some limit.

It would be better to have a single source of truth for trace data which is
easier to reason about concurrently.

### Collector version

c1c9314c6d538ec3059c6f3f7b59357dc4b1d1bc

### Environment information

_No response_

### OpenTelemetry Collector configuration

```yaml

```

### Log output

```shell

```

### Additional context

_No response_

### Tip

<sub>[React](https://github.blog/news-insights/product-news/add-reactions-to-pull-requests-issues-and-comments/) with 👍 to help prioritize this issue. Please use comments to provide useful context, avoiding `+1` or `me too`, to help us triage it. Learn more [here](https://opentelemetry.io/community/end-user/issue-participation/).</sub>

### PR DESCRIPTION
**Pull request by csmarchbanks**
#### Description
This PR changes the tailsampling processor to do all work (append traces to a batch, decide on which traces from a batch are sampled, forward to the next processor) in a single goroutine. At Grafana Labs we have found that there is significant contention between the various mutexes such that little performance is gained by allowing traces to be updated while a policy evaluation is occurring. In addition, the locking adds a lot of complexity which makes future improvements more challenging, and introduces subtle concurrency issues such as seen in the tracking issue linked below.

We (mostly @Logiraptor) also experimented with using multiple workers, each with their own goroutine to process traces but we found little improvement as yet again various contention issues showed up. See https://github.com/Logiraptor/opentelemetry-collector-contrib/pull/1 (or the first commit in this PR) for more details.

If additional performance is necessary for slow decision tick latencies I would suggest adding parallelism just to the call to `makeDecision`, which would allow additional CPUs to be used without adding contention on `idToTrace` or other locations.

#### Link to tracking issue
Fixes #41656 
Working towards https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/43876

#### Testing
Tests were updated to make sure the tick behavior remains correct and consistent. In addition, the syncBatcher needed to be updated to properly implement `Stop`.

### CODE REVIEW

File: processor/tailsamplingprocessor/processor_benchmarks_test.go
Comment (csmarchbanks) [inline processor/tailsamplingprocessor/processor_benchmarks_test.go:1]: This benchmark is broken and has been for awhile it looks like.

File: processor/tailsamplingprocessor/processor_test.go [hunk 1]
```diff
@@ -66,49 +65,55 @@ func (t *TestPolicyEvaluator) Evaluate(ctx context.Context, traceID pcommon.Trac
 // testTSPController is a set of mechanisms to make the TSP do predictable
 // things in tests.
 type testTSPController struct {
-	// tickBarrier is a barrier to block ticks until the test is ready
-	tickBarrier chan struct{}
+	tickChans []chan chan struct{}
```
Comment (Logiraptor) [inline processor/tailsamplingprocessor/processor_test.go]: I think this can just be a `chan chan struct` now. The slice was for having multiple workers

File: processor/tailsamplingprocessor/processor.go [hunk 2]
```diff
@@ -23,13 +23,11 @@ import (
 	"go.opentelemetry.io/otel/metric"
 	"go.uber.org/zap"
 
-	"github.com/open-telemetry/opentelemetry-collector-contrib/internal/coreinternal/timeutils"
 	"github.com/open-telemetry/opentelemetry-collector-contrib/processor/tailsamplingprocessor/cache"
 	"github.com/open-telemetry/opentelemetry-collector-contrib/processor/tailsamplingprocessor/internal/idbatcher"
 	"github.com/open-telemetry/opentelemetry-collector-contrib/processor/tailsamplingprocessor/internal/metadata"
 	"github.com/open-telemetry/opentelemetry-collector-contrib/processor/tailsamplingprocessor/internal/sampling"
 	"github.com/open-telemetry/opentelemetry-collector-contrib/processor/tailsamplingprocessor/internal/telemetry"
-	"github.com/open-telemetry/opentelemetry-collector-contrib/processor/tailsamplingprocessor/internal/tracelimiter"
```
Comment (Logiraptor) [inline processor/tailsamplingprocessor/processor.go:32]: Should be able to delete this package now

File: processor/tailsamplingprocessor/pkg/samplingpolicy/samplingpolicy.go
Comment (Logiraptor) [inline processor/tailsamplingprocessor/pkg/samplingpolicy/samplingpolicy.go]: This should be convertible to a plain int64 now, right?

**Review by Logiraptor — COMMENTED** [review]
Looks great! Just some minor points of cleanup

File: processor/tailsamplingprocessor/processor_benchmarks_test.go
Comment (Logiraptor) [reply processor/tailsamplingprocessor/processor_benchmarks_test.go:1]: Yeah I noticed that too. I'm fine with deleting it

**Comment by csmarchbanks** [comment]
Thanks! Updated and expanded the changelog to mention that `SpanCount` changed as well.

**Review by Logiraptor — APPROVED** [review]

**Comment by atoulme** [comment]
any performance benchmark we can use to track the impact of this work?

File: processor/tailsamplingprocessor/processor_benchmarks_test.go
Comment (atoulme) [reply processor/tailsamplingprocessor/processor_benchmarks_test.go:1]: can you please do this in a separate PR and open an issue to fix it?

File: processor/tailsamplingprocessor/config.go [hunk 3]
```diff
@@ -291,4 +291,10 @@ type Config struct {
 	Options []Option `mapstructure:"-"`
 	// Make decision as soon as a policy matches
 	SampleOnFirstMatch bool `mapstructure:"sample_on_first_match"`
+	// WorkChanCapacity sets the capacity of the work channel. This is the number of batches of traces to store in the
+	// channel, not individual traces.
+	WorkChanCapacity int `mapstructure:"work_chan_capacity"`
```
Comment (atoulme) [inline processor/tailsamplingprocessor/config.go]: please add both new options to the README. `work_chan_capacity` seems a bit mysterious. Is there any way to track number of spans across all traces stored instead of number of batches? It looks like large batches could have surprising effects.

File: processor/tailsamplingprocessor/processor_telemetry_test.go [hunk 4]
```diff
@@ -214,8 +214,10 @@ func TestMetricsAfterOneEvaluation(t *testing.T) {
 			},
 		},
 	} {
-		got := s.getMetric(tt.m.Name, md)
-		metricdatatest.AssertEqual(t, tt.m, got, tt.opts...)
+		t.Run(tt.m.Name, func(t *testing.T) {
+			got := s.getMetric(tt.m.Name, md)
+			metricdatatest.AssertEqual(t, tt.m, got, tt.opts...)
+		})
```
Comment (atoulme) [inline processor/tailsamplingprocessor/processor_telemetry_test.go]: this seems like a change destined to another PR

File: processor/tailsamplingprocessor/internal/sampling/span_count_sampler.go [hunk 5]
```diff
@@ -34,11 +34,11 @@ func NewSpanCount(settings component.TelemetrySettings, minSpans, maxSpans int32
 func (c *spanCount) Evaluate(_ context.Context, _ pcommon.TraceID, traceData *samplingpolicy.TraceData) (samplingpolicy.Decision, error) {
 	c.logger.Debug("Evaluating spans counts in filter")
 
-	spanCount := int(traceData.SpanCount.Load())
+	spanCount := int32(traceData.SpanCount)
```
Comment (atoulme) [inline processor/tailsamplingprocessor/internal/sampling/span_count_sampler.go]: this can overflow on 64 bit systems.

File: processor/tailsamplingprocessor/config.go (hunk 3 above)
Comment (csmarchbanks) [reply processor/tailsamplingprocessor/config.go]: I'll definitely add DropPendingTracesOnShutdown to the README.

Thinking about it some more I wonder if we should just have a reasonable default to help with throughput and no config unless someone reports they need it. What do you think?

**Comment by csmarchbanks** [comment]
Thanks for the review! I'll work on adding a benchmark, so far I have deployed this to an internal environment and saw no change in performance, but it would be good to validate that in more environments.

**Comment by csmarchbanks** [comment]
I have added a benchmark (and did a small change to improve the benchmark by ~10%). Currently the results look like:
```
                       │ main-with-benchmark.txt │      simplify-tsp-locking.txt       │
                       │         sec/op          │   sec/op     vs base                │
ProcessorThroughput-32               1.463m ± 1%   1.777m ± 1%  +21.45% (p=0.000 n=20)

                       │ main-with-benchmark.txt │       simplify-tsp-locking.txt       │
                       │           B/s           │     B/s       vs base                │
ProcessorThroughput-32              183.0Mi ± 1%   150.7Mi ± 1%  -17.66% (p=0.000 n=20)

                       │ main-with-benchmark.txt │      simplify-tsp-locking.txt       │
                       │          B/op           │     B/op      vs base               │
ProcessorThroughput-32              5.578Mi ± 0%   5.587Mi ± 0%  +0.17% (p=0.000 n=20)

                       │ main-with-benchmark.txt │      simplify-tsp-locking.txt      │
                       │        allocs/op        │  allocs/op   vs base               │
ProcessorThroughput-32               53.57k ± 0%   53.47k ± 0%  -0.19% (p=0.000 n=20)
```

showing a 20% reduction in throughput. I believe much of that is due to GC, specifically the GC penalty applied to goroutines which allocate more than their share. So I am unsure how realistic that would be in a process that is allocating significant amounts of memory in other goroutines as well. Setting GOGC=off shows a 10% reduction in throughput.
```
                       │ main-with-benchmark.txt │      simplify-tsp-locking.txt       │
                       │         sec/op          │   sec/op     vs base                │
ProcessorThroughput-32               1.267m ± 1%   1.411m ± 1%  +11.43% (p=0.000 n=20)

                       │ main-with-benchmark.txt │       simplify-tsp-locking.txt       │
                       │           B/s           │     B/s       vs base                │
ProcessorThroughput-32              211.4Mi ± 1%   189.7Mi ± 1%  -10.26% (p=0.000 n=20)

                       │ main-with-benchmark.txt │      simplify-tsp-locking.txt       │
                       │          B/op           │     B/op      vs base               │
ProcessorThroughput-32              5.582Mi ± 0%   5.589Mi ± 0%  +0.12% (p=0.000 n=20)

                       │ main-with-benchmark.txt │      simplify-tsp-locking.txt      │
                       │        allocs/op        │  allocs/op   vs base               │
ProcessorThroughput-32               53.64k ± 0%   53.48k ± 0%  -0.30% (p=0.000 n=20)

```

So I would say as is users could expect a 10-20% reduction in throughput in the case that they are fully limited by this processor. I am sure there are more optimizations that can be done, but what are your thoughts on those numbers?

**Comment by csmarchbanks** [comment]
In addition, as I mentioned in the description, we could parallelize the decision part of the code if desired. A very rough implementation of that reports 1.3ms/op or 215MB/s, so faster than the implementation from main.

File: processor/tailsamplingprocessor/config.go (hunk 3 above)
Comment (csmarchbanks) [reply processor/tailsamplingprocessor/config.go]: Updates complete

File: processor/tailsamplingprocessor/internal/sampling/span_count_sampler.go (hunk 5 above)
Comment (csmarchbanks) [reply processor/tailsamplingprocessor/internal/sampling/span_count_sampler.go]: Fixed

File: processor/tailsamplingprocessor/processor_benchmarks_test.go
Comment (csmarchbanks) [reply processor/tailsamplingprocessor/processor_benchmarks_test.go:1]: I opened https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/43947 to fix the benchmark (and a few others).

**Comment by csmarchbanks** [comment]
I spent a bit more time looking at profiles and realized we could move the fairly expensive copying of data to before the TSP loop. Doing so both helps with the GC penalty as the work is done on a different go routine, and adds some extra parallelism. This implementation is now faster than what is on main according to the new benchmark:
```
                      │ main-with-benchmark.txt │      simplify-tsp-locking.txt       │
                      │         sec/op          │   sec/op     vs base                │
ProcessorThroughput-8               2.213m ± 2%   1.942m ± 2%  -12.22% (p=0.000 n=10)

                      │ main-with-benchmark.txt │       simplify-tsp-locking.txt       │
                      │           B/s           │     B/s       vs base                │
ProcessorThroughput-8              121.0Mi ± 2%   137.8Mi ± 2%  +13.92% (p=0.000 n=10)

                      │ main-with-benchmark.txt │      simplify-tsp-locking.txt       │
                      │          B/op           │     B/op      vs base               │
ProcessorThroughput-8              5.582Mi ± 0%   5.604Mi ± 0%  +0.41% (p=0.000 n=10)

                      │ main-with-benchmark.txt │      simplify-tsp-locking.txt      │
                      │        allocs/op        │  allocs/op   vs base               │
ProcessorThroughput-8               53.62k ± 0%   53.73k ± 0%  +0.19% (p=0.000 n=10)
```
(I am traveling with a different computer, so ignore the raw performance values).

**Review by Logiraptor — APPROVED** [review]

**Comment by csmarchbanks** [comment]
I have fixed conflicts with a couple PRs and this should be ready to go again.

@atoulme would you have a chance to take another look soon to avoid more merge conflicts?

File: processor/tailsamplingprocessor/internal/sampling/span_count_sampler.go (hunk 5 above)
Comment (atoulme) [reply processor/tailsamplingprocessor/internal/sampling/span_count_sampler.go]: This can still overflow. Using int32 can truncate the number. Here is an example: https://go.dev/play/p/qL-jkVoRjGq

Comment (csmarchbanks) [reply processor/tailsamplingprocessor/internal/sampling/span_count_sampler.go]: Where are you seeing int/int32 still being used? I think this is an outdated diff, the code now transfers the int32s used in the config to int64s in the constructor and compares int64s in all places.

Comment (csmarchbanks) [reply processor/tailsamplingprocessor/internal/sampling/span_count_sampler.go]: I noticed a couple places in processor.go so fixed those as well.

**Review by atoulme — APPROVED** [review]
