### PR TITLE
[zipkin receiver] Fix checking status codes from tags

### LINKED ISSUE #14965: Zipkin exporter and collector do not agree on wire representation of status codes
### Description
The Zipkin exporter and collector do not agree on wire representation of status codes. And neither of which are in line with the spec. (See https://github.com/open-telemetry/opentelemetry-go/issues/3287)

The Zipkin exporter serializes status codes as `Unset`, `Error`, and `Ok`:

https://github.com/open-telemetry/opentelemetry-go/blob/5568a3072367bb8ac4d2d9e759e7deb5a975b9f5/exporters/zipkin/model.go#L211-L213

https://github.com/open-telemetry/opentelemetry-go/blob/d616df61f5d163589228c5ff3be4aa5415f5a884/codes/codes.go#L38-L42

However, the collector expects `STATUS_CODE_UNSET`, `STATUS_CODE_OK`, or `STATUS_CODE_ERROR`, see [here](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/54c0a2e13f6d2e168804212d288cb808f179683e/pkg/translator/zipkin/zipkinv2/to_translator.go#L160).

### Environment
opentelemetry-go v1.11.0
opentelemetry-collector-contrib v0.62.0

### Steps To Reproduce
Using Grafana Tempo's [local example](https://github.com/grafana/tempo/tree/main/example/docker-compose/local):

```go
package main

import (
	"context"
	"log"

	"go.opentelemetry.io/otel"
	"go.opentelemetry.io/otel/codes"
	"go.opentelemetry.io/otel/exporters/zipkin"
	sdktrace "go.opentelemetry.io/otel/sdk/trace"
)

func main() {
	ctx := context.Background()

	exporter, err := zipkin.New("")
	if err != nil {
		log.Fatalf("creating exporter: %s", err)
	}

	tp := sdktrace.NewTracerProvider(
		sdktrace.WithSampler(sdktrace.AlwaysSample()),
		sdktrace.WithBatcher(exporter),
	)
	defer tp.Shutdown(ctx)
	otel.SetTracerProvider(tp)

	_, span := otel.Tracer("foo").Start(ctx, "foo")
	log.Printf("trace ID: %s", span.SpanContext().TraceID())
	span.SetStatus(codes.Error, "something went wrong")
	span.End()
}
```

image

### Expected behavior
Status is correctly passed between exporter and collector.

### Collector version

v0.62.0

### Environment information

_No response_

### OpenTelemetry Collector configuration

_No response_

### Log output

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by MovieStoreGuy**
**Description:** 

It looks like there was a difference in expectations when it came to parsing span status in tags, this looks to resolve this and provide backwards support for existing implementations

**Link to tracking Issue:** 
Fixes https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/14965

**Testing:**

Added new unit test to validate span status is correctly set.

**Documentation:** 
NA

### CODE REVIEW

**Review by crobert-1 — APPROVED** [review]

File: pkg/translator/zipkin/zipkinv2/to_translator_test.go [hunk 1]
```diff
@@ -45,6 +45,37 @@ func TestZipkinSpansToInternalTraces(t *testing.T) {
...
+			zs: []*zipkinmodel.SpanModel{
+				{
+					SpanContext: zipkinmodel.SpanContext{
+						TraceID: convertTraceID(
+							[16]byte{0xF1, 0xF2, 0xF3, 0xF4, 0xF5, 0xF6, 0xF7, 0xF8, 0xF9, 0xFA, 0xFB, 0xFC, 0xFD, 0xFE, 0xFF, 0x80}),
+						ID: convertSpanID([8]byte{0xAF, 0xAE, 0xAD, 0xAC, 0xAB, 0xAA, 0xA9, 0xA8}),
+					},
+					Name: "min.data",
+					Tags: map[string]string{
+						"otel.status_code": "Ok",
```
Comment (atoulme) [inline pkg/translator/zipkin/zipkinv2/to_translator_test.go:59]: are you going to test Unset and Error as well?

Comment (MovieStoreGuy) [reply pkg/translator/zipkin/zipkinv2/to_translator_test.go:59]: Sounds reasonable.

Comment (atoulme) [reply pkg/translator/zipkin/zipkinv2/to_translator_test.go:59]: Yay!

**Review by atoulme — APPROVED** [review]
