### PR TITLE
[chore] fix: using replace_all_patterns on logs makes attributes values empty

### LINKED ISSUE #21109: [transform processor]: using replace_all_patterns on logs makes attributes values empty
### Component(s)

processor/logstransform

## Description

Using the transform processor with this config is making the output empty for few attributes.

## Steps to Reproduce
processors:
```
  transform:
    error_mode: ignore
    log_statements:
      - context: log
        statements: 
         - replace_all_patterns(attributes, "key", "account_id", "my_account_id")
```

## Expected Result

```
Attributes:
     -> device_name: Str(10.213.25.77)
     -> provider: Str(kentik-flow-device)
     -> Type: Str(IPFIX)
     -> dst_endpoint: Str(10.213.31.255:137)
     -> src_as_name: Str(Private IP)
     -> src_addr: Str(10.213.1.4)
     -> dst_addr: Str(10.213.31.255)
     -> dst_as_name: Str(Private IP)
     -> entity.name: Str(10.213.25.77)
     -> instrumentation.name: Str(netflow-events)
     -> input_port: Double(618)
     -> src_endpoint: Str(10.213.1.4:137)
     -> application: Str(netbios-ns)
     -> dst_geo: Str(Private IP)
     -> src_geo: Str(Private IP)
     -> timestamp: Double(1682329199367)
     -> in_pkts: Double(1)
     -> l4_src_port: Double(137)
     -> FlowDirection: Str(ingress)
     -> SamplerAddress: Str(10.213.25.77)
     -> collector.name: Str(ktranslate)
     -> entity.guid: Str(Mzc0NjA2OXxFWFR8RkxPV19ERVZJQ0V8MzE2NDEwNDIwODU0MjM3Mjc5OQ)
     -> instrumentation.provider: Str(kentik)
     -> protocol: Str(UDP)
     -> l4_dst_port: Double(137)
     -> sample_rate: Double(100)
     -> entity.type: Str(FLOW_DEVICE)
     -> in_bytes: Double(78)
     -> my_account_id: Int(3746069) ==> This should change to my_account_id from account_id 
     -> otel-processor: Str(transform-processor)
     -> Foo: Str(Bar)
     -> entity-test: Str(10.213.25.77:FLOW_DEVICE)
```

## Actual Result
```
Attributes:
     -> Type: Str(IPFIX)
     -> src_addr: Str(10.213.4.48)
     -> src_geo: Str(Private IP)
     -> instrumentation.name: Str(netflow-events)
     -> src_endpoint: Str(10.213.4.48:138)
     -> FlowDirection: Str(ingress)
     -> application: Str(netbios-dgm)
     -> dst_geo: Str(Private IP)
     -> entity.name: Str(10.213.25.77)
     -> sample_rate: Str() ==> It got empty
     -> timestamp: Str()  ==> It got empty
     -> device_name: Str(10.213.25.77)
     -> in_pkts: Str() ==> It got empty
     -> l4_src_port: Str() ==> It got empty
     -> provider: Str(kentik-flow-device)
     -> collector.name: Str(ktranslate)
     -> dst_addr: Str(10.213.31.255)
     -> src_as_name: Str(Private IP)
     -> SamplerAddress: Str(10.213.25.77)
     -> dst_as_name: Str(Private IP)
     -> input_port: Str() ==> It got empty
     -> instrumentation.provider: Str(kentik)
     -> l4_dst_port: Str() ==> It got empty
     -> protocol: Str(UDP)
     -> dst_endpoint: Str(10.213.31.255:138)
     -> entity.guid: Str(Mzc0NjA2OXxFWFR8RkxPV19ERVZJQ0V8MzE2NDEwNDIwODU0MjM3Mjc5OQ)
     -> entity.type: Str(FLOW_DEVICE)
     -> in_bytes: Str()  ==> It got empty
     -> my_account_id: Str() ==> Value changed
```

### Collector version

v0.75.0

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

### OpenTelemetry Collector configuration

_No response_

### Log output

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Ishmeet**
**Description:** <Describe what has changed.>
https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/21109
replace_all_patterns on logs were getting empty values when attributes values was other than string. This fixes that.

@TylerHelmuth 

Ex. Adding a feature - Explain what this achieves.-->

**Link to tracking Issue:** <Issue number if applicable>

**Testing:** <Describe what testing was performed and which tests were added.>

**Documentation:** <Describe the documentation added.>

### CODE REVIEW

**Comment by atoulme** [comment]
Please add a CHANGELOG entry. Please add a test to cover this fix.

File: pkg/ottl/ottlfuncs/func_replace_all_patterns.go [hunk 1]
```diff
@@ -57,9 +57,47 @@ func ReplaceAllPatterns[K any](target ottl.PMapGetter[K], mode string, regexPatt
 			case modeKey:
 				if compiledPattern.MatchString(key) {
 					updatedKey := compiledPattern.ReplaceAllLiteralString(key, replacement)
-					updated.PutStr(updatedKey, originalValue.Str())
+					switch originalValue.Type() {
```
Comment (TylerHelmuth) [inline pkg/ottl/ottlfuncs/func_replace_all_patterns.go:60]: I can't look at this in depth till Wednesday but there should be a way to use pcommon.Value and .CopyTo/generic Put to avoid a switch statement.

Comment (TylerHelmuth) [reply pkg/ottl/ottlfuncs/func_replace_all_patterns.go:60]: @Ishmeet I believe this will work:

```go
if compiledPattern.MatchString(key) {
	updatedKey := compiledPattern.ReplaceAllLiteralString(key, replacement)
	originalValue.CopyTo(updated.PutEmpty(updatedKey))
} else {
	originalValue.CopyTo(updated.PutEmpty(key))
}
```

Comment (Ishmeet) [reply pkg/ottl/ottlfuncs/func_replace_all_patterns.go]: yeah

File: .chloggen/fix-func-replace-all-patterns.yaml [hunk 2]
```diff
@@ -0,0 +1,16 @@
+# One of 'breaking', 'deprecation', 'new_component', 'enhancement', 'bug_fix'
+change_type: bug_fix
+
+# The name of the component, or a single word describing the area of concern, (e.g. filelogreceiver)
+component: transformprocessor
+
+# A brief description of the change.  Surround your text with quotes ("") if it needs to start with a backtick (`).
+note: Fixed a scenario where replace_all_patterns on logs was making attribute values empty.
```
Comment (TylerHelmuth) [inline .chloggen/fix-func-replace-all-patterns.yaml:8]:
```suggestion
note: Fixed a scenario where replace_all_patterns would wipe out non-string values on key name change.
```

**Review by TylerHelmuth — APPROVED** [review]
@Ishmeet please sign the CLA and ensure that the email used to sign is the email associated with each commit in the PR.
