### PR TITLE
[receiver/mysql] fix oob overflow for Innodb_buffer_pool_pages_misc

### LINKED ISSUE #35495: [receiver/mysqlreceiver] Mysql receiver - Uint64 to Int64 overflow
### Component(s)

receiver/mysql

## Description
User is hitting this error:
<code>2024-09-12T10:05:08.788Z error scraperhelper/scrapercontroller.go:197 Error scraping metrics {"kind": "receiver", "name": "mysql/replica", "data_type": "metrics", "error": "sql: Scan error on column index 7, name \"SUM_TIMER_FETCH\": converting driver.Value type uint64 (\"10607806269779284266\") to a int64: value out of range; sql: Scan error on column index 7, name \"SUM_TIMER_FETCH\": converting driver.Value type uint64 (\"10607806392347803736\") to a int64: value out of range; failed to parse int64 for MysqlBufferPoolPages, value was 18446744073709551264: strconv.ParseInt: parsing \"18446744073709551264\": value out of range", "scraper": "mysql"}</code>

## Analysis
- For `SUM_TIMER_FETCH` we can safely avoid the overflow, by setting `timeFetch` to uint64 and convert it back to int64 after the division https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/1d12566c29f8192bfaaabb72c3f2eca8df613a87/receiver/mysqlreceiver/scraper.go#L456-L458 

- For  `MysqlBufferPoolPages` not sure if we even support uint64 and what options we have to send this value

### Collector version

 v0.110.0

### PR DESCRIPTION
**Pull request by atoulme**
#### Description
Ignore the value returned by the stat Innodb_buffer_pool_pages_misc if out-of-bounds.

#### Link to tracking issue
Fixes #35495

#### Testing
Add an integration test.

### CODE REVIEW

**Comment by mx-psi** [comment]
```
Error: mysqlreceiver/scraper_test.go:128:62: unnecessary leading newline (whitespace)

```

File: receiver/mysqlreceiver/scraper_test.go [hunk 1]
```diff
@@ -125,6 +125,37 @@ func TestScrape(t *testing.T) {
 	})
 }
 
+func TestScrapeBufferPoolPagesMiscOutOfBounds(t *testing.T) {
+
```
Comment (atoulme) [inline receiver/mysqlreceiver/scraper_test.go:129]:
```suggestion
```

**Review by djaglowski — APPROVED** [review]
