### PR TITLE
[exporter/datadog] Run API key validation in separate goroutine

### LINKED ISSUE #18238: [exporter/datadog] Error while validaing API key: i/o timeout in serverless
### Component(s)

exporter/datadog

## Description
Error while validaing API key: i/o timeout in serverless

## Steps to Reproduce
Collector initialization in lambda/cloudrun frequently have timeouts on initialization trying to validate the api key, this may take a lot of time and times out the function initialization.

## Expected Result
Have an option for not doing this check on serverless environments. We can't depend on a external service responding on each function startup.

### Collector version

0.64.0

## Environment
OS: Docker Distroless
Compiler(if manually compiled): go 1.17

### OpenTelemetry Collector configuration

_No response_

### Log output

```shell
023-02-01T01:27:36.162Z	warn	Error while validating API key	{"kind": "exporter", "data_type": "metrics", "name": "datadog", "error": "Get \"https://api.datadoghq.com/api/v1/validate\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by songy23**
**Description:**
Run API key validation on Datadog exporter in separate goroutine

More context: see https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/13732 and https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/18238

**Link to tracking Issue:** 
Fixes https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/18238

### CODE REVIEW

File: exporter/datadogexporter/logs_exporter.go [hunk 1]
```diff
@@ -45,21 +45,24 @@ type logsExporter struct {
...
 		client := clientutil.CreateZorkianClient(string(cfg.API.Key), cfg.Metrics.TCPAddr.Endpoint)
-		err = clientutil.ValidateAPIKeyZorkian(params.Logger, client)
+		go func() { errchan <- clientutil.ValidateAPIKeyZorkian(params.Logger, client) }()
 	}
 	// validate the apiKey
-	if err != nil && cfg.API.FailOnInvalidKey {
-		return nil, err
+	if cfg.API.FailOnInvalidKey {
+		err := <-errchan
+		if err != nil {
```
Comment (mx-psi) [inline exporter/datadogexporter/logs_exporter.go:63]: nit
```suggestion
		if err := <-errchan; err != nil {
```

File: exporter/datadogexporter/traces_exporter.go [hunk 2]
```diff
@@ -63,22 +63,25 @@ func newTracesExporter(ctx context.Context, params exporter.CreateSettings, cfg
...
 		exp.metricsAPI = datadogV2.NewMetricsApi(apiClient)
 	} else {
 		client := clientutil.CreateZorkianClient(string(cfg.API.Key), cfg.Metrics.TCPAddr.Endpoint)
-		if err := clientutil.ValidateAPIKeyZorkian(params.Logger, client); err != nil && cfg.API.FailOnInvalidKey {
+		go func() { errchan <- clientutil.ValidateAPIKeyZorkian(params.Logger, client) }()
+		exp.client = client
+	}
+	if cfg.API.FailOnInvalidKey {
+		err := <-errchan
+		if err != nil {
```
Comment (mx-psi) [inline exporter/datadogexporter/traces_exporter.go:82]:
```suggestion
		if err := <-errchan; err != nil {
```

**Review by mx-psi — APPROVED** [review]

**Comment by songy23** [comment]
This issue originates from this PR: https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/13732#issuecomment-1258312989. Running the API validation synchronously significantly contributes to the exporter start time (serverless environments are especially sensitive to it), and the response is not used unless config.fail_on_invalid_key is specified.

**Comment by songy23** [comment]
This is now ready to merge :)
