### PR TITLE
[pkg/translator/prometheus] do not normalize metric name with multiple underscore

### LINKED ISSUE #13322: [pkg/translator/prometheus] __ in metric name becomes _
**Describe the bug**
metric `envoy__rule_engine_zlib_buf_error` becomes `envoy_rule_engine_zlib_buf_error` after prometheus translator

**Steps to reproduce**
in this [test](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/pkg/translator/prometheus/normalize_name_test.go#L154-L161), add following and execute
```golang
	require.Equal(t, "envoy__rule_engine_zlib_buf_error", CleanUpString("envoy__rule_engine_zlib_buf_error"))
```

```
        	Error:      	Not equal: 
        	            	expected: "envoy__rule_engine_zlib_buf_error"
        	            	actual  : "envoy_rule_engine_zlib_buf_error"
```

**What did you expect to see?**
`envoy__rule_engine_zlib_buf_error`

**What did you see instead?**
`envoy_rule_engine_zlib_buf_error`

**What version did you use?**
Version: latest commit

**What config did you use?**
Config: (e.g. the yaml config file)

**Environment**
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

**Additional context**

### PR DESCRIPTION
**Pull request by newly12**
**Description:** <Describe what has changed.>
do not normalize metric name with multiple underscore

**Link to tracking Issue:** <Issue number if applicable>
Fixes #13322

**Testing:** <Describe what testing was performed and which tests were added.>
UT

**Documentation:** <Describe the documentation added.>
n/a

### CODE REVIEW

**Comment by dashpole** [comment]
cc @bertysentry

**Comment by bertysentry** [comment]
Prometheus are supposed to use snake case. Allowing double underscore is not be desirable. I mean: I'm not a big fan of altering the code and logic of the Prometheus exporter to support a broken metric name as in #13322. We want to make sure the normalization of metric names ends up with a *proper* Prometheus metric names.

I understand the use case, though: you're receiving Prometheus metrics, maybe doing some processing, and then re-exporting them, so you expect to have exactly the same metric name, even if broken.

Problem is that this use case will break again in the future, once we update the **prometheusreceiver** to convert Prometheus metrics to Otel conventions. Example: `envoy__rule_engine_zlib_buf_errors_total` (received from Prometheus) will be converted to `envoy.rule_engine_zlib_buf_errors` (Otel), which will then be re-exported to Prometheus as  `envoy_rule_engine_zlib_buf_errors_total`, with a single underscore... again!

To cover your particular use case, it would be better to have a configurable option to disable the metric and labels normalization altogether. As long as you're staying in the Prometheus realm, you don't need all this normalization stuff, so it's better to simply disable it.

The normalization can already be disabled with the feature gate, but I think it's preferable to make sure this option remains configurable, even in final 1.0 of the collector.

Would you like to update your PR to add such `disableNormalization` option flag to the configuration of the Prometheus exporters? (must be added to both **prometheusexporter** and **prometheusremotewriteexporter**)

File: exporter/prometheusexporter/collector.go [hunk 1]
```diff
@@ -36,6 +37,12 @@ var (
 	separatorString = string([]byte{model.SeparatorByte})
 )
 
+var disableNormalizationGate = featuregate.Gate{
```
Comment (dashpole) [inline exporter/prometheusexporter/collector.go:40]: this should be part of the exporter configuration, rather than a feature-gate.  Feature-gates are meant to be temporary.

Comment (bertysentry) [reply exporter/prometheusexporter/collector.go:40]: +1

**Comment by bertysentry** [comment]
@newly12 Thank you for the update! However, there is already a feature gate controlling the normalization: `pkg.translator.prometheus.NormalizeName` as described in the [Prometheus Translator package](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/pkg/translator/prometheus). (btw, iirc, this feature gate is still disabled by default, so this part of the code is not even supposed to be executed by default! -- there must be some missing information somewhere, or misunderstanding)

**Comment by newly12** [comment]
@bertysentry yes the feature gate in prometheus translator is disabled by default, the thing is the function `CleanUpString` removes additional non digital or non alphabet character and concrete them with `_`, could you have a look at the original fix? see the [first commit](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/13431/commits/e416d1c482bff44307893229e2af4eaf00002226)

File: exporter/prometheusexporter/collector.go (hunk 1 above)
Comment (newly12) [reply exporter/prometheusexporter/collector.go:40]: yeah misunderstood. will change accordingly if needed.

File: pkg/translator/prometheus/normalize_name.go [hunk 2]
```diff
@@ -131,7 +131,7 @@ func normalizeName(metric pmetric.Metric, namespace string) string {
 	// Split metric name in "tokens" (remove all non-alphanumeric)
 	nameTokens := strings.FieldsFunc(
 		metric.Name(),
-		func(r rune) bool { return !unicode.IsLetter(r) && !unicode.IsDigit(r) },
+		func(r rune) bool { return !unicode.IsLetter(r) && !unicode.IsDigit(r) && string(r) != "_" },
```
Comment (bertysentry) [inline pkg/translator/prometheus/normalize_name.go]: Please do not update *normalizeName()*. This function is called only when feature gate for normalization is ON. In this case, metric names that are produced must conform to Prometheus convention (i.e. no double underscores).

File: pkg/translator/prometheus/normalize_name.go [hunk 3]
```diff
@@ -218,7 +222,9 @@ func perUnitMapGetOrDefault(perUnit string) string {
 // Returns whether the slice contains the specified value
 func contains(slice []string, value string) bool {
 	for _, sliceEntry := range slice {
-		if sliceEntry == value {
+		if strings.Contains(sliceEntry, "_") {
```
Comment (bertysentry) [inline pkg/translator/prometheus/normalize_name.go]: This processing is done only when normalization feature gate is ON, so there is no need to modify this part.

File: pkg/translator/prometheus/normalize_name.go [hunk 4]
```diff
@@ -164,7 +164,7 @@ func normalizeName(metric pmetric.Metric, namespace string) string {
 
 	// Append _total for Counters
 	if metric.DataType() == pmetric.MetricDataTypeSum && metric.Sum().IsMonotonic() {
-		nameTokens = append(removeItem(nameTokens, "total"), "total")
+		nameTokens = appendSuffixIfMissing(nameTokens, "total")
```
Comment (bertysentry) [inline pkg/translator/prometheus/normalize_name.go]: We need to make sure the word "total" doesn't appear twice, so we remove it and then append it.

Otel cumulative sum `network.io.total` with units `By` will be transformed following this workflow:

1. slice ==> `["network", "io", "total"]`
2. append the unit ==> `["network", "io", "total", "bytes"]`
3. remove "total", and then append it again ==> `["network", "io", "bytes", "total"]`
4. join ==> `network_io_bytes_total`

Using *appendSuffixIfMissing()* we would get `network_io_total_bytes_total` which is not desirable.

Please revert (or detail the case you're trying to cover), thank you!

File: pkg/translator/prometheus/normalize_name.go [hunk 5]
```diff
@@ -197,6 +197,10 @@ func CleanUpString(s string) string {
 	return strings.Join(strings.FieldsFunc(s, func(r rune) bool { return !unicode.IsLetter(r) && !unicode.IsDigit(r) }), "_")
 }
 
+func CleanUpStringForMetricName(s string) string {
+	return strings.Join(strings.FieldsFunc(s, func(r rune) bool { return !unicode.IsLetter(r) && !unicode.IsDigit(r) && string(r) != "_" }), "_")
```
Comment (bertysentry) [inline pkg/translator/prometheus/normalize_name.go]: Replace `string(r) != "_"` with `r != '_'`

File: pkg/translator/prometheus/normalize_name.go [hunk 6]
```diff
@@ -235,3 +241,23 @@ func removeItem(slice []string, value string) []string {
 	}
 	return newSlice
 }
+
+func appendSuffixIfMissing(slice []string, value string) []string {
```
Comment (bertysentry) [inline pkg/translator/prometheus/normalize_name.go]: Following my previous comment, this function shouldn't be needed

File: pkg/translator/prometheus/normalize_name_test.go [hunk 7]
```diff
@@ -194,6 +194,7 @@ func TestBuildPromCompliantNameWithNormalize(t *testing.T) {
 	require.Equal(t, "system_io_bytes_total", BuildPromCompliantName(createCounter("system.io", "By"), ""))
 	require.Equal(t, "system_network_io_bytes_total", BuildPromCompliantName(createCounter("network.io", "By"), "system"))
 	require.Equal(t, "_3_14_digits", BuildPromCompliantName(createGauge("3.14 digits", ""), ""))
+	require.Equal(t, "envoy__rule_engine_zlib_buf_error", BuildPromCompliantName(createGauge("envoy__rule_engine_zlib_buf_error", ""), ""))
```
Comment (bertysentry) [inline pkg/translator/prometheus/normalize_name_test.go]: These unit tests are performed with normalization feature gate ON, in which case we don't want to allow double underscores. Please change to: `require.Equal(t, "envoy_rule_engine_zlib_buf_error", ...`

File: pkg/translator/prometheus/normalize_name.go [hunk 8]
```diff
@@ -197,6 +197,10 @@ func CleanUpString(s string) string {
 	return strings.Join(strings.FieldsFunc(s, func(r rune) bool { return !unicode.IsLetter(r) && !unicode.IsDigit(r) }), "_")
 }
 
+func CleanUpStringForMetricName(s string) string {
```
Comment (bertysentry) [inline pkg/translator/prometheus/normalize_name.go]: Please rename to `RemovePromForbiddenRunes()` and add a comment to describe the difference with *CleanUpString()*

**Review by bertysentry — CHANGES_REQUESTED** [review]
A changes still needed. 

**Important**: when normalization feature gate it ON, we don't want to allow double underscores (it's not valid snake case), so you shouldn't need to update any of this code path.

**Comment by bertysentry** [comment]
@newly12 Thank you for the clarification, I reviewed the first commit. Please see my comments.

**Comment by newly12** [comment]
@bertysentry Thanks for your review, please check the latest changes, review comments should all have been addressed.

**Review by bertysentry — APPROVED** [review]
Looks good to me, thank you @newly12

**Review by dashpole — APPROVED** [review]
