### PR TITLE
[BREAKING CHANGE] datadogexporter: Remove default prefix from user metrics

### LINKED ISSUE #2016: [Datadog] All metrics exported with "otel." prefix
**Describe the bug**
We are using the collector to proxy metrics from carbon to DataDog
All of the metrics are prefixed with "otel."

**Steps to reproduce**
Run the collector with any receiver and DataDog exporter

**What did you expect to see?**
The metrics as they were send to the collector

**What did you see instead?**
"otel." prefixed metrics

**What version did you use?**
Version: v0.17.0

### PR DESCRIPTION
**Pull request by mx-psi**
**Description:** 

The `otel.` prefix was introduced in #1483 to prevent clashes between metrics generated by OpenTelemetry host metrics receiver and the Datadog Agent system check.

Following user request and internal discussion, this PR changes the behavior so that only metrics from the `system.` and `process.` namespaces (the ones generated by the host metrics receiver) get the `otel.` prefix.
Running metrics also keep the prefix since they are not generated by an user.

If one wants to keep the previous behavior, the recommended setup is to use the metrics transform processor, adding a rule similar to the following one:
```
include: ^(.*)$
match_type: regexp
action: update
new_name: otel.$1
```

**Link to tracking Issue:** Fixes #2016

**Testing:** Added unit tests for new behavior. Tested on an end-to-end environment

### CODE REVIEW

**Review by jpkrohling — APPROVED** [review]

File: exporter/datadogexporter/metrics/utils.go [hunk 1]
```diff
@@ -88,10 +89,27 @@ func addHostname(metrics []datadog.Metric, logger *zap.Logger, cfg *config.Confi
 	}
 }
 
-// addNamespace prepends all metric names with a given namespace
+// shouldPrepend decides if a given metric name should be prepended by `otel.`.
+// By default, this happens for
+// - hostmetrics receiver metrics (since they clash with Datadog Agent system check) and
+// - running metrics
+func shouldPrepend(name string) bool {
+	namespaces := [...]string{"datadog_exporter.", "system.", "process."}
```
Comment (albertvaka) [inline exporter/datadogexporter/metrics/utils.go:97]: Nit: I think `datadog_exporter.*` metrics don't ever go through `addNamespace`.

**Review by albertvaka — APPROVED** [review]

File: exporter/datadogexporter/metrics/utils.go (hunk 1 above)
Comment (mx-psi) [reply exporter/datadogexporter/metrics/utils.go:97]: They do: they are added in `mapMetrics` and `addNamespace` happens inside `ProcessMetrics`:
 https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/d04011af4f5b0d8e12410684629de674ac298d18/exporter/datadogexporter/metrics_exporter.go#L72-L74
