### PR TITLE
[receiver/tcpcheck] Record tcpcheck.error Cumulative

### LINKED ISSUE #39234: `tcpcheck.error` does not match the value set
### Component(s)

receiver/tcpcheck

## Steps to Reproduce
Simply start with `tcpcheck`‘s default configuration.

## Expected Result
When TCP errors occur continuously, the value of tcpcheck.error should increase incrementally.

## Actual Result
The value is always 1.

### Collector version

v0123.0

## Environment
OS:  Darwin & Linux

### OpenTelemetry Collector configuration

```yaml
exporters:
  otlphttp/metric:
    metrics_endpoint: localhost:8080/metric
  file:
    path: ./otel.log
processors:
  batch:
    send_batch_size: 100
    send_batch_max_size: 100
    timeout: 5s
  cumulativetodelta:
receivers:
  tcpcheck:
    targets:
      - endpoint: xxx.example.com:443
        dialer:
          timeout: 15s
service:
  pipelines:
    metrics/self:
      receivers:
       - tcpcheck
      processors:
        - cumulativetodelta
        - batch
      exporters:
        - otlphttp/metric
        - file
```

### Log output

```shell

```

### Additional context

The detailed description of the `tcpcheck.error` metric is [metadata.yaml](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/33b352ad893cb5240623562409cfad8b997237be/receiver/tcpcheckreceiver/metadata.yaml#L36C3-L36C17). 

After reviewing the [OTel code](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/33b352ad893cb5240623562409cfad8b997237be/receiver/tcpcheckreceiver/scraper.go#L62), I think there are the following solutions:
1. Set the `tcpcheck.error` metric to the `gauge` type.
2. Save the `cumulative` value of the timeseries and then assign it, rather than the [pointValue](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/33b352ad893cb5240623562409cfad8b997237be/receiver/tcpcheckreceiver/scraper.go#L49).
3. Set the metric type to Delta when [initializing](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/33b352ad893cb5240623562409cfad8b997237be/receiver/tcpcheckreceiver/internal/metadata/generated_metrics.go#L100) `tcpcheck.error`

### PR DESCRIPTION
**Pull request by chengchuanpeng**
#### Description
Fix tcpcheck.error from 1 to Cumulative

#### Link to tracking issue
Fixes https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/39234

#### Testing
Add unit test and value increases

### CODE REVIEW

**Comment by atoulme** [comment]
It's already set as cumulative: https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/receiver/tcpcheckreceiver/metadata.yaml#L41 I suspect this would be taken care of?

**Comment by chengchuanpeng** [comment]
> It's already set as cumulative: https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/receiver/tcpcheckreceiver/metadata.yaml#L41 I suspect this would be taken care of?

@atoulme 
Currently, I only record 1 when error happens, and  don't not increase it. 

https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/receiver/tcpcheckreceiver/scraper.go#L49
https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/receiver/tcpcheckreceiver/scraper.go#L62

File: receiver/tcpcheckreceiver/scraper.go [hunk 1]
```diff
@@ -58,9 +79,18 @@ func (s *scraper) scrapeEndpoint(tcpConfig *confignet.TCPAddrConfig, wg *sync.Wa
 	defer mux.Unlock()
 
 	if err != nil {
-		// Record error data point and log the error
-		s.mb.RecordTcpcheckErrorDataPoint(now, pointValue, tcpConfig.Endpoint, err.Error())
+		// Increment error count
+		s.errorCounts[tcpConfig.Endpoint]++
+		s.mb.RecordTcpcheckErrorDataPoint(now, s.errorCounts[tcpConfig.Endpoint], tcpConfig.Endpoint, err.Error())
```
Comment (michael-burt) [inline receiver/tcpcheckreceiver/scraper.go:84]: `metadata.yaml` specifies the following:

```
attributes:
  error.code:
    description: Error code recorded during check
    type: string
  tcpcheck.endpoint:
    description: TCP endpoint
    type: string

metrics:
  tcpcheck.error:
    description: Records errors occurring during TCP check.
    enabled: true
    sum:
      value_type: int
      aggregation_temporality: cumulative
      monotonic: true
    unit: "{error}"
    attributes: [tcpcheck.endpoint, error.code]
    ```
    
Here you are using a raw error message which could introduce cardinality explosion. Is there a way to convert err.Error() to an enum?

File: receiver/tcpcheckreceiver/scraper_test.go [hunk 2]
```diff
@@ -243,3 +276,138 @@ func updateErrorCodeInMetrics(metrics pmetric.Metrics, newErrorCode string) pmet
 		Attributes().PutStr("error.code", newErrorCode)
 	return metrics
 }
+
+func TestScraper_ErrorMetric_Increments(t *testing.T) {
```
Comment (michael-burt) [inline receiver/tcpcheckreceiver/scraper_test.go:280]: Can you update this test to look at multiple endpoints?

File: receiver/tcpcheckreceiver/scraper.go (hunk 1 above)
Comment (chengchuanpeng) [reply receiver/tcpcheckreceiver/scraper.go]: I use the attribute as way to recording enum.
If the error contains 'connection refused' or 'connection timeout', it will be counted; otherwise, it will be considered an unknown error.

**Review by atoulme — APPROVED** [review]
