### PR TITLE
[receiver/filelog] Suppress repeated permission denied errors

### LINKED ISSUE #39491: Repeated and frequent "Failed to open file" on a file it can't read.
### Component(s)

receiver/filelog, pkg/stanza/fileconsumer

## Description

Tried setting up OpenObserve, so tried installing an opentelemetry collector to collect logs and system info and etc.

The default otel-config.yaml from openobserve tries has a `filelog` receiver with a `include: [ /var/log/**log ]` wildcard to match all log files in `/var/log/`.

If there exists a log file that can't be opened the collector will retry every second or so, spamming logs in the process, never stopping or skipping the file.

For every fail it writes a big block of text into the system log.

This is how permissions look on the log file:
`-rw-r----- 1 root adm 145009 Apr 15 21:58 /var/log/cloud-init-output.log`

## Steps to Reproduce
1. Create a file it can't read
2. Configure filelog to read said file
3. Start the collector
4. Watch the never-ending log spam

## Expected Result
One log line informing me a file can't be open.

## Actual Result
Log spam, see attached logs.

### Collector version

v0.124.1

## Environment
OS: Debian GNU/Linux 12 (bookworm) cloud image
Compiler(if manually compiled): N/A

### OpenTelemetry Collector configuration

```yaml
receivers:
  journald:
    directory: /var/log/journal
  filelog/std:
    include: [ /var/log/**log ]
    # start_at: beginning
  hostmetrics:
    root_path: /
    collection_interval: 30s
    scrapers:
      cpu:
      disk:
      filesystem:
      load:
      memory:
      network:
      paging:          
      processes:
      # process: # a bug in the process scraper causes the collector to throw errors so disabling it for now
processors:
  resourcedetection/system:
    detectors: ["system"]
    system:
      hostname_sources: ["os"]
  memory_limiter:
    check_interval: 1s
    limit_percentage: 75
    spike_limit_percentage: 15
  batch:
    send_batch_size: 10000
    timeout: 10s

extensions:
  zpages: {}

exporters:
  otlphttp/openobserve:
    endpoint: http://monitoring.denys.home:5080/api/default/
    headers:
      Authorization: "XXX"
  otlphttp/openobserve_journald:
    endpoint: http://monitoring.denys.home:5080/api/default/
    headers:
      Authorization: "XXX"
      stream-name: journald

service:
  extensions: [zpages]
  pipelines:
    metrics:
      receivers: [hostmetrics]
      processors: [resourcedetection/system, memory_limiter, batch]
      exporters: [otlphttp/openobserve]
    logs:
      receivers: [filelog/std]
      processors: [resourcedetection/system, memory_limiter, batch]
      exporters: [otlphttp/openobserve]
    logs/journald:
      receivers: [journald]
      processors: [resourcedetection/system, memory_limiter, batch]
      exporters: [otlphttp/openobserve_journald]
```

### Log output

```shell
Apr 18 16:00:50 monitoring otelcol-contrib[136903]: 2025-04-18T16:00:50.717+0800        error        fileconsumer/file.go:181        Failed to open file        {"component": "fileconsumer", "error": "open /var/log/cloud-init-output.log: permission denied"}
Apr 18 16:00:50 monitoring otelcol-contrib[136903]: github.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza/fileconsumer.(*Manager).makeFingerprint
Apr 18 16:00:50 monitoring otelcol-contrib[136903]:         github.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza@v0.124.1/fileconsumer/file.go:181
Apr 18 16:00:50 monitoring otelcol-contrib[136903]: github.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza/fileconsumer.(*Manager).makeReaders
Apr 18 16:00:50 monitoring otelcol-contrib[136903]:         github.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza@v0.124.1/fileconsumer/file.go:208
Apr 18 16:00:50 monitoring otelcol-contrib[136903]: github.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza/fileconsumer.(*Manager).consume
Apr 18 16:00:50 monitoring otelcol-contrib[136903]:         github.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza@v0.124.1/fileconsumer/file.go:158
Apr 18 16:00:50 monitoring otelcol-contrib[136903]: github.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza/fileconsumer.(*Manager).poll
Apr 18 16:00:50 monitoring otelcol-contrib[136903]:         github.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza@v0.124.1/fileconsumer/file.go:140
Apr 18 16:00:50 monitoring otelcol-contrib[136903]: github.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza/fileconsumer.(*Manager).startPoller.func1
Apr 18 16:00:50 monitoring otelcol-contrib[136903]:         github.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza@v0.124.1/fileconsumer/file.go:110
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by khpeet**
#### Description
Added logic to suppress repeated error logs due to file permission errors within the `filelog` receiver.

- Updated `makeFingerprint` to check for permission errors via [os.isPermission](https://pkg.go.dev/os#IsPermission)
- Log an error only on the first occurrence for a given file path and add it to an in-memory map, guarded by a mutex to avoid race conditions for concurrent read/writes.
- Debug log only for subsequent read attempt (to avoid spam)
- When the file becomes readable, info log a message and remove the path from the stored set

#### Link to tracking issue
Fixes https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/39491

#### Testing
New unit test verifying:
- First unreadable-open produces exactly one Error-level log.
- Second attempt does not produce another Error-level log.
- When permissions are restored, an Info-level `Previously unreadable...` message appears.

NOTE: Test skips Windows due to unreliable os.Chmod behavior

#### Documentation
Added changelog yaml entry summarizing the issue and fix.

### CODE REVIEW

File: pkg/stanza/fileconsumer/file.go [hunk 1]
```diff
@@ -175,13 +181,42 @@ func (m *Manager) consume(ctx context.Context, paths []string) {
...
 func (m *Manager) makeFingerprint(path string) (*fingerprint.Fingerprint, *os.File) {
 	file, err := os.Open(path) // #nosec - operator must read in files defined by user
 	if err != nil {
-		m.set.Logger.Error("Failed to open file", zap.Error(err))
+
+		// If a file is unreadable due to permissions error, store path in map and log error once (unless in debug mode)
+		if os.IsPermission(err) {
+			m.unreadableMu.Lock()
+			if m.unreadable == nil {
+				m.unreadable = make(map[string]struct{})
```
Comment (atoulme) [inline pkg/stanza/fileconsumer/file.go]: this is not thread safe, is that a problem?

Comment (atoulme) [reply pkg/stanza/fileconsumer/file.go]: ok locks help. But when is `unreadable` nil in this state? It is initialized above.

Comment (khpeet) [reply pkg/stanza/fileconsumer/file.go]: Thanks for taking a look @atoulme! 

- The locks make it thread safe since all accesses to `unreadable` are protected by the mutex.
- The `nil` check for `unreadable` is present mainly for protection against cases where `Manager.Start()` is not called (i.e - in unit tests/edge cases -- the test I added fails without that check)

Comment (khpeet) [reply pkg/stanza/fileconsumer/file.go]: I've removed the nil check/ re-init of `unreadable` and modified the new unit test to function without that requirement.

File: pkg/stanza/fileconsumer/file.go [hunk 2]
```diff
@@ -175,13 +181,38 @@ func (m *Manager) consume(ctx context.Context, paths []string) {
...
 }
 
+// makeFingerprint opens `path` and computes a fingerprint for the file
+// and contains logic to only log file permission errors once per file per startup
 func (m *Manager) makeFingerprint(path string) (*fingerprint.Fingerprint, *os.File) {
 	file, err := os.Open(path) // #nosec - operator must read in files defined by user
 	if err != nil {
-		m.set.Logger.Error("Failed to open file", zap.Error(err))
+		// If a file is unreadable due to permissions error, store path in map and log error once (unless in debug mode)
+		if os.IsPermission(err) {
```
Comment (andrzej-stencel) [inline pkg/stanza/fileconsumer/file.go]: The [os.IsPermission](https://pkg.go.dev/os#IsPermission) function is not deprecated, but its docs say "New code should use errors.Is(err, fs.ErrPermission)." Perhaps use that?

**Comment by khpeet** [comment]
@andrzej-stencel @atoulme - gentle bump on this PR

**Review by VihasMakwana — COMMENTED** [review]
Do we need a mutex? AFAIK, calls to `makeFingerprint` are serialised. Could you confirm this?

Also, @andrzej-stencel is on sick leave until starting of December. It might take some time to get this merged.

**Comment by khpeet** [comment]
> Do we need a mutex? AFAIK, calls to `makeFingerprint` are serialised. Could you confirm this?
> 
> Also, @andrzej-stencel is on sick leave until starting of December. It might take some time to get this merged.

Hey @VihasMakwana - You are correct! Taking a second deeper look, I saw that only a single goroutine calls `poll()` and everything looks sequential. I've removed the mutex.

**Comment by khpeet** [comment]
@andrzej-stencel - Happy New Year! Can we get this one approved/merged?

File: pkg/stanza/fileconsumer/file.go [hunk 3]
```diff
@@ -39,12 +39,17 @@ type Manager struct {
 	pollsToArchive int
 
 	telemetryBuilder *metadata.TelemetryBuilder
+
+	unreadable map[string]struct{}
```
Comment (iblancasa) [inline pkg/stanza/fileconsumer/file.go:51]: I guess this is accessed and modified from different goroutines. I think we need to protect it with a mutex or something.

File: pkg/stanza/fileconsumer/file.go [hunk 4]
```diff
@@ -183,10 +190,30 @@ func (m *Manager) makeFingerprint(path string) (*fingerprint.Fingerprint, *os.Fi
...
+			if !seen {
+				m.set.Logger.Error("Failed to open file", zap.Error(err))
+				m.unreadable[path] = struct{}{}
+			} else {
+				m.set.Logger.Debug("Failed to open file (already reported)", zap.Error(err))
+			}
+		} else {
+			m.set.Logger.Error("Failed to open file", zap.Error(err))
+		}
 		m.set.Logger.Error("Failed to open file", zap.Error(err), zap.String("original_path", path), zap.String("normalized_path", normalizedPath))
```
Comment (iblancasa) [inline pkg/stanza/fileconsumer/file.go]: Should this be included in the previous log message? Both looks too similar and same info will be logged twice, right?

File: pkg/stanza/fileconsumer/file.go [hunk 5]
```diff
@@ -183,10 +190,30 @@ func (m *Manager) makeFingerprint(path string) (*fingerprint.Fingerprint, *os.Fi
 	}
 	file, err := os.Open(normalizedPath) // #nosec - operator must read in files defined by user
 	if err != nil {
+		// If a file is unreadable due to permissions error, store path in map and log error once (unless in debug mode)
+		if os.IsPermission(err) {
+			_, seen := m.unreadable[path]
+			if !seen {
+				m.set.Logger.Error("Failed to open file", zap.Error(err))
+				m.unreadable[path] = struct{}{}
```
Comment (iblancasa) [inline pkg/stanza/fileconsumer/file.go]: Let's imagine you have something creating files with permission issues in a folder. The list here can grown up without limit. This can be a problem. I think we need to limit the number of items that can be added here.

How about implementing an LRU cache?

File: pkg/stanza/fileconsumer/file.go [hunk 6]
```diff
@@ -183,10 +190,30 @@ func (m *Manager) makeFingerprint(path string) (*fingerprint.Fingerprint, *os.Fi
...
+			}
+		} else {
+			m.set.Logger.Error("Failed to open file", zap.Error(err))
+		}
 		m.set.Logger.Error("Failed to open file", zap.Error(err), zap.String("original_path", path), zap.String("normalized_path", normalizedPath))
 		return nil, nil
 	}
 
+	// Notify if previously unreadable file is now able to be read
+	if m.unreadable != nil {
```
Comment (iblancasa) [inline pkg/stanza/fileconsumer/file.go]: I don't think you need to do this check

File: pkg/stanza/fileconsumer/unreadable_test.go [hunk 7]
```diff
@@ -0,0 +1,116 @@
...
+	operator.set.Logger = set.Logger
+	require.NoError(t, operator.Start(testutil.NewUnscopedMockPersister()))
+	defer func() {
+		require.NoError(t, operator.Stop())
+	}()
+
+	// First poll should attempt to open and log an error once
+	operator.poll(t.Context())
+	// small delay to ensure logs are recorded
+	time.Sleep(10 * time.Millisecond)
```
Comment (iblancasa) [inline pkg/stanza/fileconsumer/unreadable_test.go]: Please, use `Eventually` here

**Review by iblancasa — COMMENTED** [review]
I think we need to add tests to:
- Check the log messages not related to permissions -file not found, for instance- are still logged
- (maybe) Test concurrent poll cycles accessing `unreadable` map

File: pkg/stanza/fileconsumer/file.go (hunk 3 above)
Comment (khpeet) [reply pkg/stanza/fileconsumer/file.go:51]: @iblancasa - see previous comment/commit: https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/44350#issuecomment-3576249147

File: pkg/stanza/fileconsumer/file.go (hunk 4 above)
Comment (khpeet) [reply pkg/stanza/fileconsumer/file.go]: This looks to be from a separate commit outside this PR - I can remove the else logging

File: pkg/stanza/fileconsumer/file.go (hunk 3 above)
Comment (iblancasa) [reply pkg/stanza/fileconsumer/file.go:51]: Thank you! Didn't see that comment before.

File: pkg/stanza/fileconsumer/unreadable_test.go (hunk 7 above)
Comment (khpeet) [reply pkg/stanza/fileconsumer/unreadable_test.go]: Changed to `Eventually`

File: pkg/stanza/fileconsumer/file.go (hunk 6 above)
Comment (khpeet) [reply pkg/stanza/fileconsumer/file.go]: Remove this check in latest commit

File: pkg/stanza/fileconsumer/file.go (hunk 5 above)
Comment (khpeet) [reply pkg/stanza/fileconsumer/file.go]: added `maxUnreadableEntries` in latest commit with a default of 10k. This should prevent unbounded memory growth by having the map check its size before adding new entries.

File: pkg/stanza/fileconsumer/file.go (hunk 4 above)
Comment (khpeet) [reply pkg/stanza/fileconsumer/file.go]: Fixed in latest commit

**Comment by khpeet** [comment]
@iblancasa - Fixed most of the feedback (appreciate the review btw!). I also added another test to verify non-permission errors (i.e - file not found) are still logged + it confirms that those kind of errors are not tracked in the unreadable map.

For the concurrent access test, I don't think its needed since `makeFingerprint` calls are serialized and only a single goroutine calls `poll()` (everything looks to be sequential).

**Review by iblancasa — APPROVED** [review]

File: .chloggen/issue-39491.yaml [hunk 8]
```diff
@@ -0,0 +1,30 @@
...
+change_type: enhancement
+
+# The name of the component, or a single word describing the area of concern, (e.g. receiver/filelog)
+component: receiver/filelog
+
+# A brief description of the change.  Surround your text with quotes ("") if it needs to start with a backtick (`).
+note: |
+  Suppress repeated permission-denied error logs for unreadable files in filelog receiver.
+  Now, only one error is logged per file per process run, and an informational message is emitted when the file becomes readable again.
+  This reduces log spam and improves clarity for operators.
```
Comment (andrzej-stencel) [inline .chloggen/issue-39491.yaml]: Can we move the extended description to `subtext`?

```suggestion
note: Suppress repeated permission-denied errors
```

File: pkg/stanza/fileconsumer/file.go (hunk 4 above)
Comment (andrzej-stencel) [reply pkg/stanza/fileconsumer/file.go]: I'm still (again?) seeing duplicate error logging: 

- line 207: `m.set.Logger.Error("Failed to open file", zap.Error(err))`
- this line (212): `m.set.Logger.Error("Failed to open file", ...`

Did it come back in a merge or are we talking about different things?

**Review by andrzej-stencel — COMMENTED** [review]
The test introduced in this PR seems to be failing: https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/21181607334/job/61157176417?pr=44350

Can you take a look at this? And a couple other rather minor comments.

File: pkg/stanza/fileconsumer/file.go (hunk 4 above)
Comment (khpeet) [reply pkg/stanza/fileconsumer/file.go]: This keeps coming back after merging upstream with my fork - fixed again.

File: pkg/stanza/fileconsumer/file.go (hunk 2 above)
Comment (khpeet) [reply pkg/stanza/fileconsumer/file.go]: fixed in latest commit

File: .chloggen/issue-39491.yaml (hunk 8 above)
Comment (khpeet) [reply .chloggen/issue-39491.yaml]: fixed in latest commit

**Comment by khpeet** [comment]
> The test introduced in this PR seems to be failing: https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/21181607334/job/61157176417?pr=44350
> 
> Can you take a look at this? And a couple other rather minor comments.

This was due to the upstream logging line being back from merging that to my fork. Updated and tests should work now

**Review by andrzej-stencel — APPROVED** [review]
