### PR TITLE
[receiver/k8s_cluster] Add back all other vendor-specific node conditions

### LINKED ISSUE #23839: [receiver/k8s_cluster] Missing node metrics for `k8s.node.condition_out_of_disk`, `k8s.node.allocatable_pods` and `k8s.node.allocatable_hugepages-*`
### Component(s)

_No response_

## Description
When [performing the transition to pdata](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/23438), I unwittingly didn't account for some newer allocatable resource metrics associated with nodes. The receiver accepts resource names as strings and doesn't perform a validation on them, and therefore they are not caught by the receiver at collection time.

## Steps to Reproduce
Try to run the receiver with the following configuration:

```
clusterReceiver:
  enabled: true
  config:
    receivers:
      k8s_cluster:
        node_conditions_to_report:
          - Ready
          - DiskPressure
          - MemoryPressure
          - PIDPressure
          - NetworkUnavailable
          - OutOfDisk
        allocatable_types_to_report:
          - cpu
          - memory
          - ephemeral-storage
          - storage
          - pods
          - hugepages-1Gi
          - hugepages-2Mi
```

## Expected Result

The collector should emit the following metrics:
* `k8s.node.condition_out_of_disk`
* `k8s.node.allocatable_pods`
* `k8s.node.allocatable_hugepages_1_gi`
* `k8s.node.allocatable_hugepages_2_mi`

## Actual Result
The collector doesn't emit those metrics.

### Collector version

0.80.0

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

### OpenTelemetry Collector configuration

_No response_

### Log output

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by atoulme**
**Description:**
Add back all other vendor-specific node conditions, and report them even if missing, as well as all allocatable node metrics if present,  to the list of Kubernetes node metrics available, which went missing during the pdata translation

**Link to tracking Issue:**
Fixes #23839

**Testing:**
Unit tests.

**Documentation:**
Not quite. Maybe a doc entry is required here. I haven't looked yet where to place it.

### CODE REVIEW

File: receiver/k8sclusterreceiver/internal/node/nodes.go [hunk 1]
```diff
@@ -46,23 +46,30 @@ func Transform(node *corev1.Node) *corev1.Node {
 func GetMetrics(set receiver.CreateSettings, node *corev1.Node, nodeConditionTypesToReport, allocatableTypesToReport []string) pmetric.Metrics {
 	mb := imetadata.NewMetricsBuilder(imetadata.DefaultMetricsBuilderConfig(), set)
 	ts := pcommon.NewTimestampFromTime(time.Now())
+	customScopeMetrics := pmetric.NewMetrics().ResourceMetrics().AppendEmpty().ScopeMetrics().AppendEmpty()
```
Comment (dmitryax) [inline receiver/k8sclusterreceiver/internal/node/nodes.go:49]: nit:
```suggestion
	customMetrics := pmetric.NewMetricSlice()
```
Then you can use `customMetrics` instead of `customScopeMetrics.Metrics()`

Comment (atoulme) [reply receiver/k8sclusterreceiver/internal/node/nodes.go]: Thanks, fixed!

**Review by TylerHelmuth — APPROVED** [review]
