### PR TITLE
fix(prometheusreceiver): invalid metric name validation error in scrape start from target allocator

### LINKED ISSUE #40788: [receiver/prometheus] Invalid metric name validation scheme error in 0.128.0
### Component(s)

_No response_

## Description

After upgrading from OpenTelemetry Collector 0.127.0 to 0.128.0, the Prometheus receiver fails to create scrape pools for various ServiceMonitors and PodMonitors with the error "invalid metric name validation scheme". This appears to be a breaking change in metric name validation that affects commonly used Prometheus exporters including Kyverno, Loki, kube-state-metrics, and others.

## Steps to Reproduce

1. Deploy OpenTelemetry Collector 0.128.0 with Prometheus receiver and Target Allocator enabled
2. Configure Target Allocator to discover ServiceMonitors and PodMonitors from various namespaces
3. Deploy common Kubernetes monitoring components (Kyverno, Loki, kube-state-metrics, etc.)
4. Observe collector logs

## Expected Result

Prometheus receiver should successfully create scrape pools and collect metrics from all discovered targets, as it did in version 0.127.0.

## Actual Result

Prometheus receiver fails to create scrape pools with error:

```
    error creating new scrape pool {"err": "invalid metric name validation scheme: invalid metric name validation scheme, ", "scrape_pool": "serviceMonitor/kdp-core-kyverno/kyverno-background-controller/0"}
```

This affects multiple scrape targets including:
- serviceMonitor/kdp-core-kyverno/*
- podMonitor/loki/*
- serviceMonitor/kube-state-metrics/*
- podMonitor/opentelemetry-collectors/*

The same configuration works without issues in version 0.127.0.

### Collector version

0.128.09

## Environment
OS: Kubernetes (Linux containers)
OpenTelemetry Collector: 0.128.0 (official container image)
Target Allocator: 0.127.0
OpenTelemetry Operator: 0.127.0
Deployment: Kubernetes StatefulSet via OpenTelemetry Operator

### OpenTelemetry Collector configuration

```yaml
---
# Source: opentelemetry-collectors/templates/otel-metrics-collector/otel-metrics-collector.yaml
apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: otel-metrics
  labels:
    eb/envtype: dev
    eb/owner: MyTeam
    eb/service: opentelemetry
spec:
  mode: statefulset
  replicas: 3
  ports:
    - appProtocol: grpc
      name: otlp-grpc
      port: 4317
      targetPort: 4317
      protocol: TCP
    - appProtocol: http
      name: otlp-http
      port: 4318
      protocol: TCP
      targetPort: 4318
  targetAllocator:
    enabled: true
    replicas: 1
    resources:
      limits:
        memory: 2Gi
      requests:
        cpu: 500m
        memory: 1Gi
    prometheusCR:
      enabled: true
      podMonitorSelector: {}
      serviceMonitorSelector: {}
  resources:
    limits:
      memory: 3Gi
    requests:
      cpu: 750m
      memory: 2Gi
  config:
    receivers:
      prometheus:
        config:
          global: {}
          scrape_configs: []

    exporters:
      otlphttp/metrics:
        endpoint: http://otel-metrics-gateway.example.com:4318        

    processors:
      batch/metrics:
        send_batch_max_size: 1024
        send_batch_size: 512
        timeout: 2s
      memory_limiter:
        check_interval: 1s
        limit_percentage: 80
        spike_limit_percentage: 15

    service:
      pipelines:
        metrics:
          receivers: 
            - prometheus
          processors:
            - batch/metrics
            - memory_limiter
          exporters: 
            - otlphttp/metrics
      telemetry:
        metrics:
          level: detailed
```

### Log output

```shell
2025-06-18T00:26:32.298Z    info    service@v0.128.0/service.go:199    Setting up own telemetry...    {"resource": {"service.instance.id": "65910152-bdde-4a41-ad96-99a45d4f8aaf", "service.name": "otelcol-contrib", "service.version": "0.128.0"}}
2025-06-18T00:26:32.298Z    info    memorylimiter@v0.128.0/memorylimiter.go:149    Using percentage memory limiter    {"resource": {"service.instance.id": "65910152-bdde-4a41-ad96-99a45d4f8aaf", "service.name": "otelcol-contrib", "service.version": "0.128.0"}, "otelcol.component.kind": "processor", "total_memory_mib": 3072, "limit_percentage": 80, "spike_limit_percentage": 15}
2025-06-18T00:26:32.298Z    info    prometheusreceiver@v0.128.0/metrics_receiver.go:157    Starting discovery manager    {"resource": {"service.instance.id": "65910152-bdde-4a41-ad96-99a45d4f8aaf", "service.name": "otelcol-contrib", "service.version": "0.128.0"}, "otelcol.component.id": "prometheus", "otelcol.component.kind": "receiver", "otelcol.signal": "metrics"}
2025-06-18T00:26:32.299Z    info    targetallocator/manager.go:69    Starting target allocator discovery    {"resource": {"service.instance.id": "65910152-bdde-4a41-ad96-99a45d4f8aaf", "service.name": "otelcol-contrib", "service.version": "0.128.0"}, "otelcol.component.id": "prometheus", "otelcol.component.kind": "receiver", "otelcol.signal": "metrics"}
2025-06-18T00:26:37.299Z    error    error creating new scrape pool    {"resource": {"service.instance.id": "65910152-bdde-4a41-ad96-99a45d4f8aaf", "service.name": "otelcol-contrib", "service.version": "0.128.0"}, "otelcol.component.id": "prometheus", "otelcol.component.kind": "receiver", "otelcol.signal": "metrics", "err": "invalid metric name validation scheme: invalid metric name validation scheme, ", "scrape_pool": "serviceMonitor/example-namespace/example-service/0"}
github.com/prometheus/prometheus/scrape.(*Manager).reload
    github.com/prometheus/prometheus@v0.304.1/scrape/manager.go:188
github.com/prometheus/prometheus/scrape.(*Manager).reloader
    github.com/prometheus/prometheus@v0.304.1/scrape/manager.go:161
2025-06-18T00:26:37.299Z    error    error creating new scrape pool    {"resource": {"service.instance.id": "65910152-bdde-4a41-ad96-99a45d4f8aaf", "service.name": "otelcol-contrib", "service.version": "0.128.0"}, "otelcol.component.id": "prometheus", "otelcol.component.kind": "receiver", "otelcol.signal": "metrics", "err": "invalid metric name validation scheme: invalid metric name validation scheme, ", "scrape_pool": "podMonitor/monitoring-namespace/metrics-exporter/0"}
github.com/prometheus/prometheus/scrape.(*Manager).reload
    github.com/prometheus/prometheus@v0.304.1/scrape/manager.go:188
github.com/prometheus/prometheus/scrape.(*Manager).reloader
    github.com/prometheus/prometheus@v0.304.1/scrape/manager.go:161
```

## Version Matrix
- OpenTelemetry Collector: 0.128.0 (fails)
- OpenTelemetry Collector: 0.127.0 (works)
- Target Allocator: 0.127.0
- OpenTelemetry Operator: 0.127.0

## Affected Exporters/Components
This issue affects multiple common Kubernetes monitoring components:
- Kyverno (policy engine)
- Loki (log aggregation)
- kube-state-metrics
- CloudWatch exporter
- Custom application metrics

## Prometheus Version Context
Prometheus version used by collector: v0.304.1 (from stack trace)

## Workaround Status
No known configuration workaround found. Attempted configurations:
- Adding `metric_name_validation_scheme: "utf8"` to global config (failed)
- Various Prometheus receiver flags (failed)
- Transform processors (ineffective - validation occurs before processing)

## Impact Assessment
This is a blocking issue for upgrading to 0.128.0 in environments with:
- ServiceMonitor/PodMonitor auto-discovery enabled
- Common Kubernetes monitoring stack components
- Prevents adoption of 0.128.0 security fixes and features

## Regression Confirmation
Confirmed regression: exact same configuration works in 0.127.0 and fails in 0.128.0

### PR DESCRIPTION
**Pull request by krajorama**
#### Description

Fix invalid metric name validation error in scrape start from target allocator.

Prometheus made setting metric_name_validation_scheme, metric_name_escaping_scheme mandatory mandatory, use sane defaults ("legacy", "undescores").

#### Link to tracking issue

Fixes #40788

#### Testing

Added unit test for target allocator + scrape e2e.
The test fails if:
- Prometheus logged something above the WARN level
- Prometheus reports failed scrape pools in metrics
- No metrics are in the result

#### Documentation

N/A

### CODE REVIEW

**Review by dashpole — DISMISSED** [review]

File: receiver/prometheusreceiver/targetallocator/manager.go [hunk 1]
```diff
@@ -154,6 +154,14 @@ func (m *Manager) sync(compareHash uint64, httpClient *http.Client) (uint64, err
...
 		}
 
+		if scrapeConfig.MetricNameValidationScheme == "" {
+			scrapeConfig.MetricNameValidationScheme = promconfig.LegacyValidationConfig
+		}
+
+		if scrapeConfig.MetricNameEscapingScheme == "" {
+			scrapeConfig.MetricNameEscapingScheme = model.EscapeUnderscores
+		}
+
```
Comment (ywwg) [inline receiver/prometheusreceiver/targetallocator/manager.go]: Sorry, the default behavior is a little more complex: default validation scheme is actually UTF8. And then the escaping scheme is "allow-utf-8" if the validation scheme is UTF8, and is "underscores" if the validation scheme is "legacy"

https://github.com/prometheus/prometheus/blob/main/config/config.go#L874-L920

**Review by ywwg — CHANGES_REQUESTED** [review]

**Comment by krajorama** [comment]
We've discussed this in the OTEL Prometheus WG meeting. The real problem is that Prometheus doesn't set the correct defaults itself. It's ok to make this workaround for now, linked to a new issue in Prometheus, however I need to update the test so that it's creating the base scrape configuration from Prometheus defaults and not manually as in my test code.

File: receiver/prometheusreceiver/targetallocator/manager.go (hunk 1 above)
Comment (krajorama) [reply receiver/prometheusreceiver/targetallocator/manager.go]: I've reused the Validation code from Prometheus to set these instead, so that the code is not duplicated here.

**Comment by krajorama** [comment]
I think I found a nice solution to not duplicate logic from Prometheus , however I don't have a testbed for the [target allocator operator](https://github.com/open-telemetry/opentelemetry-operator/tree/main/cmd/otel-allocator), so it's very hard for me to tell if I'm causing some other problem. 

I imagine it's fair to validate the scrape config that the target allocator provides, but I'm not 100% sure. @dashpole @ywwg

**Review by dashpole — APPROVED** [review]
Thanks!

File: receiver/prometheusreceiver/targetallocator/manager.go [hunk 2]
```diff
@@ -154,6 +154,21 @@ func (m *Manager) sync(compareHash uint64, httpClient *http.Client) (uint64, err
...
+		// TODO(krajorama): remove once
+		// https://github.com/prometheus/prometheus/issues/16750 is solved
+		// https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/35459
+		//   is implemented and is default.
+		if m.promCfg.GlobalConfig.MetricNameValidationScheme == "" {
+			m.promCfg.GlobalConfig.MetricNameValidationScheme = promconfig.LegacyValidationConfig
+		}
+
+		// Validate the scrape config and also fill in the defaults from the global config as needed.
+		err = scrapeConfig.Validate(m.promCfg.GlobalConfig)
```
Comment (ywwg) [inline receiver/prometheusreceiver/targetallocator/manager.go:166]: yes this is the correct approach

File: receiver/prometheusreceiver/targetallocator/manager.go [hunk 3]
```diff
@@ -154,6 +154,21 @@ func (m *Manager) sync(compareHash uint64, httpClient *http.Client) (uint64, err
 			scrapeConfig.ScrapeFallbackProtocol = promconfig.PrometheusText0_0_4
 		}
 
+		// TODO(krajorama): remove once
+		// https://github.com/prometheus/prometheus/issues/16750 is solved
+		// https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/35459
+		//   is implemented and is default.
+		if m.promCfg.GlobalConfig.MetricNameValidationScheme == "" {
+			m.promCfg.GlobalConfig.MetricNameValidationScheme = promconfig.LegacyValidationConfig
```
Comment (ywwg) [inline receiver/prometheusreceiver/targetallocator/manager.go:162]: note that upstream, the default will be UTF-8.  If otel collector wants a different default they will have to override it somewhere.

**Review by ywwg — APPROVED** [review]

**Comment by ArthurSens** [comment]
I couldn't find time to review but I'm trusting david and owen on this one :) 

I'm adding the ready to merge label
