### PR TITLE
[processor/routing] Expand error handling on failure to build exporters

### LINKED ISSUE #6920: Issue with routing processor
**Describe the bug**
Processor says exporter is not found for `default_exporters`.

**Steps to reproduce**
Create an OpenTelemetryCollector resource with the following config:
```
receivers:
  otlp:
    protocols:
      grpc:
processors:
  routing:
    from_attribute: X-OTLP-Tenant
    default_exporters: [otlp/prod]
    table:
    - value: dev
      exporters: [otlp/dev]
exporters:
  otlp/prod:
    endpoint: internal.tracing.svc.cluster.local
  otlp/dev:
    endpoint: internal-dev.tracing.svc.cluster.local
service:
  pipelines:
    traces/otlp:
      receivers: [otlp]
      processors: [routing]
      exporters: [otlp/prod, otlp/dev]
```

**What did you expect to see?**
Successfully created container

**What did you see instead?**
Crashlooping container

```
Error: cannot start processors: error registering default exporter "otlp/prod": exporter not found
2021/12/20 19:28:34 collector server run finished with error: cannot start processors: error registering default exporter "otlp/prod": exporter not found
```

**What version did you use?**
0.40.0

**Environment**
EKS bottlerocket k8s 1.20

Also, I _believe_ the documented example for this processor is wrong. It shows `default_exporters` as a string, but I think it is supposed to be a list of strings. Based off [this](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/processor/routingprocessor/config.go#L29).

### PR DESCRIPTION
**Pull request by jdgeisler**
**Description:** <Describe what has changed.>
This pr is expanding the error handling introduced in PR https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/7423, since the error is also occurring for all exporters defined in the routing processor, not just the default ones.

If multiple pipelines are defined and the routing processor is only added to one of them, a false error is thrown saying the exporter can not be found. The PR above fixed it for the default exporters, so the goal of this PR is to also fix it for the non-default exporters defined in the routing processor.

Fixes https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/6920

**Testing:** <Describe what testing was performed and which tests were added.>
I tested this change in my own local distribution and the error was no longer occurring with a configuration like this [example](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/6920#issuecomment-1042899023)

### CODE REVIEW

**Comment by pmm-sumo** [comment]
@jdgeisler could you also add the testcase for that scenario? (I think `factory_test` would be a good fit for this)

**Comment by jdgeisler** [comment]
@pmm-sumo The test case has been added. To better show how the failure occurs when multiple pipelines and exporters are defined without using the routing processor I added the `config_multipipelines.yaml` file to `testdata`. The unit test uses that config with both metrics and tracing exporter and pipeline types. The routing processor is configured to only use tracing, so the logger throws the warning without an error.

File: processor/routingprocessor/factory_test.go [hunk 1]
```diff
@@ -16,6 +16,13 @@ package routingprocessor
 
 import (
 	"context"
+	"go.opentelemetry.io/collector/component"
```
Comment (pmm-sumo) [inline processor/routingprocessor/factory_test.go:19]: Imports order needs fixing. Just run `make gofmt` and it should be good then

File: processor/routingprocessor/factory_test.go [hunk 2]
```diff
@@ -136,6 +143,55 @@ func TestShouldNotFailWhenNextIsProcessor(t *testing.T) {
...
+	}
+
+	cfg, err := servicetest.LoadConfigAndValidate(filepath.Join("testdata", "config_multipipelines.yaml"), factories)
+	assert.NoError(t, err)
+
+	for _, cfg := range cfg.Processors {
+		exp := newProcessor(zap.NewNop(), cfg)
+		err = exp.Start(context.Background(), host)
+		// assert that no error is thrown due to multiple pipelines and exporters not using the routing processor
+		assert.NoError(t, err)
```
Comment (pmm-sumo) [inline processor/routingprocessor/factory_test.go:191]: I think it practically doesn't change much but for convenience perhaps it would be good to also do the shutdown, e.g. something along
```suggestion
		assert.NoError(t, err)
		assert.NoError(t, exp.Shutdown(context.Background())
```

File: processor/routingprocessor/factory_test.go (hunk 1 above)
Comment (jdgeisler) [reply processor/routingprocessor/factory_test.go:20]: `make gofmt` has been ran and changes pushed

File: processor/routingprocessor/factory_test.go (hunk 2 above)
Comment (jdgeisler) [reply processor/routingprocessor/factory_test.go:193]: Makes sense, just added the shutdown

File: processor/routingprocessor/factory_test.go [hunk 3]
```diff
@@ -16,8 +16,17 @@ package routingprocessor
...
 import (
 	"context"
+
+	"go.opentelemetry.io/collector/component"
+	"go.opentelemetry.io/collector/config/configgrpc"
+	"go.opentelemetry.io/collector/exporter/otlpexporter"
+	"go.uber.org/zap"
+
+	"path/filepath"
 	"testing"
```
Comment (pmm-sumo) [inline processor/routingprocessor/factory_test.go:26]: Hmm, I think it still left too many groups. We want just three of them:

```
// internal

// 3rd party

// project
```

Comment (jdgeisler) [reply processor/routingprocessor/factory_test.go:20]: ah okay I think I got it fixed this time

**Review by pmm-sumo — APPROVED** [review]

**Review by jpkrohling — APPROVED** [review]
