### PR TITLE
[cmd/opampsupervisor] Don't accept remote config if not capable

### LINKED ISSUE #41166: [cmd/opampsupervisor] Failing subtest in Test_composeEffectiveConfig
### Component(s)

cmd/opampsupervisor

## Description

The `Test_composeEffectiveConfig/can_accept_remote_config,_receives_none` is consistently failing for me on main

Spotted on #41135
Possibly related to #40295

### Collector version

d33bea5

### Environment information

n/a

### OpenTelemetry Collector configuration

```yaml
n/a
```

### Log output

```shell
=== Failed
=== FAIL: supervisor Test_composeEffectiveConfig/can_accept_remote_config,_receives_none (0.01s)
    supervisor_test.go:295: 
        	Error Trace:	D:/a/opentelemetry-collector-contrib/opentelemetry-collector-contrib/cmd/opampsupervisor/supervisor/supervisor_test.go:295
        	Error:      	Not equal: 
        	            	expected: true
        	            	actual  : false
        	Test:       	Test_composeEffectiveConfig/can_accept_remote_config,_receives_none
=== FAIL: supervisor Test_composeEffectiveConfig (0.06s)
```

### Additional context

_No response_

### Tip

<sub>[React](https://github.blog/news-insights/product-news/add-reactions-to-pull-requests-issues-and-comments/) with 👍 to help prioritize this issue. Please use comments to provide useful context, avoiding `+1` or `me too`, to help us triage it. Learn more [here](https://opentelemetry.io/community/end-user/issue-participation/).</sub>

### PR DESCRIPTION
**Pull request by douglascamata**
#### Description

This PR does a few important things:

1. Changes the `cmd/opampsupervisor`'s `.gitignore` to specifically ignore state files at the root of the Go module.
2. It fixes the Supervisor's test named `Test_composeEffectiveConfig`. This test was persisting state in its folder, which was hidden by the `.gitignore` mentioned above. This was hiding potential bugs and/or changes of behavior (related to #41166). Now the test uses a `t.TempDir()` as storage folder for the Supervisor.
3. The fix above unearthed a bug: the Supervisor was happy accepting remote configuration even if it didn't have the respective capability. This has been fixed at two levels: configuration merging **and** message processing.
4. Fixed the tests covering `Supervisor.onMessage`, now ensuring the remote config messages are ignored completely at the highest level. Also made them use a `t.TempDir()` as storage folder for the Supervisor to avoid issues similar to the ones mentioned above.

#### Link to tracking issue
Fixes #41166. 

#### Testing

Unit tests updated and fixed.

### CODE REVIEW

File: cmd/opampsupervisor/supervisor/supervisor.go [hunk 1]
```diff
@@ -1790,6 +1794,11 @@ func (s *Supervisor) onMessage(ctx context.Context, msg *types.MessageData) {
 
 // processRemoteConfigMessage processes an AgentRemoteConfig message, returning true if the agent config has changed.
 func (s *Supervisor) processRemoteConfigMessage(msg *protobufs.AgentRemoteConfig) bool {
+	if !s.config.Capabilities.AcceptsRemoteConfig {
+		s.telemetrySettings.Logger.Error("Got remote config message, but the agent does not accept remote config. Ignoring remote config.")
```
Comment (evan-bradley) [inline cmd/opampsupervisor/supervisor/supervisor.go]:
```suggestion
		s.telemetrySettings.Logger.Warn("Got remote config message, but the agent does not accept remote config. Ignoring remote config.")
```
I don't think this is necessarily an error, `warn` probably makes more sense here.

**Review by evan-bradley — APPROVED** [review]
Thanks for the quick and comprehensive fix! Also really appreciate the detailed PR description.
