### PR TITLE
[testbed] Fix loadgenerator race condition

### LINKED ISSUE #32326: Race condition in testbed load generator when parallel is used
### Component(s)

testbed

## Description

If the `ProviderSender#Start` is called to run with more than one goroutine then a race condition occurs due to the shared variable `ProviderSender#prevError`.

## Steps to Reproduce

1. Write a test or edit an existing one to call `ProviderSender#Start` with load options having `LoadOptions#Parallel` value greater than `1`. Example:
```diff
diff --git a/testbed/testbed/mock_backend_test.go b/testbed/testbed/mock_backend_test.go
index 98882d87cb..4763a1f1ba 100644
--- a/testbed/testbed/mock_backend_test.go
+++ b/testbed/testbed/mock_backend_test.go
@@ -48,7 +48,7 @@ func TestGeneratorAndBackend(t *testing.T) {
 			assert.EqualValues(t, 0, lg.DataItemsSent())
 
 			// Generate at 1000 SPS
-			lg.Start(LoadOptions{DataItemsPerSecond: 1000})
+			lg.Start(LoadOptions{DataItemsPerSecond: 1000, Parallel: 2})
 			// ensure teardown in failure scenario
 			t.Cleanup(lg.Stop)
```
2. Run the test using `make test` or `go test -v -race ./...`
3. Observe the output for the race condition.

## Expected Result

No race condition and the tests pass.

## Actual Result

Race conditions found by the race-detector.

### Collector version

v0.98.0

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

### OpenTelemetry Collector configuration

_No response_

### Log output

```shell
==================
WARNING: DATA RACE
Write at 0x00c000466160 by goroutine 59:
  github.com/open-telemetry/opentelemetry-collector-contrib/testbed/testbed.(*ProviderSender).generateTrace()
      /Users/lahsivjar/Projects/elastic/opentelemetry-collector-contrib/testbed/testbed/load_generator.go:250 +0x2d0
  github.com/open-telemetry/opentelemetry-collector-contrib/testbed/testbed.(*ProviderSender).generate.func1()
      /Users/lahsivjar/Projects/elastic/opentelemetry-collector-contrib/testbed/testbed/load_generator.go:218 +0x1f0

Previous write at 0x00c000466160 by goroutine 60:
  github.com/open-telemetry/opentelemetry-collector-contrib/testbed/testbed.(*ProviderSender).generateTrace()
      /Users/lahsivjar/Projects/elastic/opentelemetry-collector-contrib/testbed/testbed/load_generator.go:250 +0x2d0
  github.com/open-telemetry/opentelemetry-collector-contrib/testbed/testbed.(*ProviderSender).generate.func1()
      /Users/lahsivjar/Projects/elastic/opentelemetry-collector-contrib/testbed/testbed/load_generator.go:218 +0x1f0

Goroutine 59 (running) created at:
  github.com/open-telemetry/opentelemetry-collector-contrib/testbed/testbed.(*ProviderSender).generate()
      /Users/lahsivjar/Projects/elastic/opentelemetry-collector-contrib/testbed/testbed/load_generator.go:209 +0x23c
  github.com/open-telemetry/opentelemetry-collector-contrib/testbed/testbed.(*ProviderSender).Start.func2()
      /Users/lahsivjar/Projects/elastic/opentelemetry-collector-contrib/testbed/testbed/load_generator.go:119 +0x34

Goroutine 60 (running) created at:
  github.com/open-telemetry/opentelemetry-collector-contrib/testbed/testbed.(*ProviderSender).generate()
      /Users/lahsivjar/Projects/elastic/opentelemetry-collector-contrib/testbed/testbed/load_generator.go:209 +0x23c
  github.com/open-telemetry/opentelemetry-collector-contrib/testbed/testbed.(*ProviderSender).Start.func2()
      /Users/lahsivjar/Projects/elastic/opentelemetry-collector-contrib/testbed/testbed/load_generator.go:119 +0x34
==================
```

### Additional context

Possible solution: Make `prevError` local to the `generate{Log,Metrics,Trace}` and remove it from `ProviderSender` -- not sure if I am missing something here but that should be enough. If we require the `prevError` to be a field in the `ProviderSender` then we can use `atomic.Value`.

### PR DESCRIPTION
**Pull request by lahsivjar**
**Description:** <Describe what has changed.>
Fixes a race condition in testbed's default load generator (`ProviderSender`). The fix changes the behavior of how logging works for the `ProviderSender`. Before this PR, the code will try to log errors if the previous error is not the same and it would try to do this across goroutines. Now, each error will be logged if the previous error is not the same for each goroutine.

Alternatively, we can also build a logger using bloom filter to try to log each error once though I am not sure if that would be required. This PR offers a quick fix while keeping the behavior reasonably close to the current behavior.

Closes https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/32326

**Link to tracking Issue:** https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/32326

**Testing:** Follow the steps in the tracking issue.

**Documentation:** Not required.

### CODE REVIEW

**Review by songy23 — COMMENTED** [review]
https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/8663186275/job/23756993964?pr=32351#step:8:189

Please fix linter

**Comment by lahsivjar** [comment]
@songy23 Thanks for the review. The previous fix was not totally correct so I have updated the fix to propagate the errors from `generate{Traces,Metrics,Logs}` to the `generate` func and handle previous error logging there. Also, the lint should be fixed too.

File: testbed/testbed/load_generator.go [hunk 1]
```diff
@@ -210,22 +208,41 @@ func (ps *ProviderSender) generate() {
...
+						b, err = ps.generateTrace()
 					case MetricDataSender:
-						ps.generateMetrics()
+						b, err = ps.generateMetrics()
 					case LogDataSender:
-						ps.generateLog()
+						b, err = ps.generateLog()
 					default:
-						log.Printf("Invalid type of ProviderSender sender")
+						log.Printf("Invalid type of ProviderSender sender, quiting load generation")
```
Comment (crobert-1) [inline testbed/testbed/load_generator.go:228]:
```suggestion
						log.Printf("Invalid type of ProviderSender sender, quitting load generation")
```

File: testbed/testbed/load_generator.go [hunk 2]
```diff
@@ -210,22 +208,41 @@ func (ps *ProviderSender) generate() {
 			defer workers.Done()
 			t := time.NewTicker(time.Second / time.Duration(ps.options.DataItemsPerSecond/ps.options.ItemsPerBatch/numWorkers))
 			defer t.Stop()
+
+			var (
+				prevErr error
+				err     error
+				b       bool
```
Comment (crobert-1) [inline testbed/testbed/load_generator.go:215]: Can we use a more descriptive name for the bool here? This coincides with another question, I'm not understanding exactly what the `bool` is supposed to represent that's being returned by the `generate...` methods. Can you explain what that refers to? I thought it was success at first, but that didn't seem quite right from usages.

File: testbed/testbed/load_generator.go [hunk 3]
```diff
@@ -210,22 +208,41 @@ func (ps *ProviderSender) generate() {
...
 					case MetricDataSender:
-						ps.generateMetrics()
+						b, err = ps.generateMetrics()
 					case LogDataSender:
-						ps.generateLog()
+						b, err = ps.generateLog()
 					default:
-						log.Printf("Invalid type of ProviderSender sender")
+						log.Printf("Invalid type of ProviderSender sender, quiting load generation")
+						continue
```
Comment (crobert-1) [inline testbed/testbed/load_generator.go:229]: Why `continue` here instead of `return`? It seems to contradict the log message, and results in just coming back to the same case in the `select` from what I can tell, resulting in log spam without reason.

I'm not sure how returning here would impact test runs, but hopefully the failure reason would be obvious enough with the log message.

File: testbed/testbed/load_generator.go (hunk 2 above)
Comment (lahsivjar) [reply testbed/testbed/load_generator.go:215]: Good point! Honestly, I am also unsure what the `bool` refers to. I wanted to move the decision of logging one level up and that meant moving all the parameters involved in the decision up one level. The `bool` comes from `DataProvider` ([ref](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/2daff18c2e3d9a1b63df72fd5c26f8c83a2d0683/testbed/testbed/data_providers.go#L28-L33)), however, the documentation is unclear on what it means.

Looking into the implementation ([ref](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/2daff18c2e3d9a1b63df72fd5c26f8c83a2d0683/testbed/testbed/data_providers.go#L219)) it seems that a `true` value refers to an empty(?) signal (Metric, Trace, or, Log). Based on the code in the load generator, empty signals are not processed further and thus don't impact `prevErr`. An option to simplify this would be to just clear the previous error even when the `bool` is `true`. It would mean that we would be logging with a bit more frequency in some cases, WDYT?

File: testbed/testbed/load_generator.go (hunk 3 above)
Comment (lahsivjar) [reply testbed/testbed/load_generator.go:229]: > and results in just coming back to the same case in the select from what I can tell, resulting in log spam without reason

I agree. The only reason I went with the `continue` was to keep the same behavior as before. I think we should just error if the signal type is unsupported in the [constructor itself](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/2daff18c2e3d9a1b63df72fd5c26f8c83a2d0683/testbed/testbed/load_generator.go#L98), WDYT?

File: testbed/testbed/load_generator.go (hunk 2 above)
Comment (crobert-1) [reply testbed/testbed/load_generator.go:215]: Thanks for sharing more information here. I came away with a similar understanding after looking a bit more into it, it looks like the bool _might_ be for error. So if an error occurs it'll be true, and false otherwise. (The only time it's true is as you shared, in the `goldenDataProvider`, and it looks like they're error cases, such as for `GenerateLogs` where it's not implemented.) It's almost like it's using a bool instead of just returning an error.

File: testbed/testbed/load_generator.go [hunk 4]
```diff
@@ -210,22 +208,41 @@ func (ps *ProviderSender) generate() {
 			defer workers.Done()
 			t := time.NewTicker(time.Second / time.Duration(ps.options.DataItemsPerSecond/ps.options.ItemsPerBatch/numWorkers))
 			defer t.Stop()
+
+			var (
+				prevErr error
```
Comment (crobert-1) [inline testbed/testbed/load_generator.go:213]: Is `prevErr` supposed to hold all previous errors, just the last error, or something else? I'm trying to better understand the point here before making more suggestions.

Comment (lahsivjar) [reply testbed/testbed/load_generator.go:213]: As per my understanding of the code,

1. Before this PR, the `prevErr` was supposed to hold the last error that occurred during load generation in any of the goroutines -- not sure if this behavior was intended. Also, this is what introduced the race condition that the PR is trying to solve.
2. After this PR, the `prevErr` holds the last error for each goroutine generating the load.

Alternatively, we can get rid of the `prevErr` completely and build a `onceLogger` that can use some probabilistic data structure (like bloom filter) to track what has happened before and only log new errors.

File: testbed/testbed/load_generator.go (hunk 3 above)
Comment (crobert-1) [reply testbed/testbed/load_generator.go:229]: I'd prefer to error sooner rather than later since this is for testing. No reason to waste time if it's going to fail. 👍

File: testbed/testbed/load_generator.go (hunk 2 above)
Comment (crobert-1) [reply testbed/testbed/load_generator.go:215]: From our current understanding then, can we just remove `b`, and all references? Then update all of the `generate...()` methods to only return an error (instead of a bool and error)?

File: testbed/testbed/load_generator.go (hunk 3 above)
Comment (lahsivjar) [reply testbed/testbed/load_generator.go]: Updated the logic to error in the constructor if the sender type is not supported.

File: testbed/testbed/load_generator.go (hunk 2 above)
Comment (lahsivjar) [reply testbed/testbed/load_generator.go]: Updated to remove `b`. Also, a couple of points to highlight the changes that this will lead to:

1. Previously the `prevErr` would not reset when the `b` would be `true` (which as per our current understanding refers to an error in the provider). This means that now we would log a bit more if the error in provider resets the `prevErr` and then again a same error is observed. Practically, I am not sure if this would be a concern based on the current codebase.
2. I am not returning an error if `b` is true from the `generate{Log, Metrics, Trace}`. The main reason for this is that the current codebase doesn't seem to treat this case as an error. I don't have a strong opinion on this and would be happy to address this if you see this as incorrect.

**Review by crobert-1 — APPROVED** [review]
Looks good to me, just one minor suggestion. Thanks for all of your work here, and helping me understand what's going on better! Really appreciate it!

File: testbed/testbed/load_generator.go [hunk 5]
```diff
@@ -210,22 +212,26 @@ func (ps *ProviderSender) generate() {
...
+
+				if err == nil {
+					prevErr = nil
+					continue
+				}
+				// update prevErr to err if it's different than last observed error
+				if prevErr == nil || err.Error() != prevErr.Error() {
+					prevErr = err
+					log.Printf("%v", err)
+				}
```
[the remark this answers is not in the document]
Comment (lahsivjar) [reply testbed/testbed/load_generator.go]: Good point, thanks for raising it. I got tunnel-visioned with the previous approach to not see it 🤦 . I have updated the code now, let me know if it looks good to you.

[the remark this answers is not in the document]
Comment (crobert-1) [reply testbed/testbed/load_generator.go]: Yep, looks good!

**Comment by lahsivjar** [comment]
@songy23 @crobert-1 Is there anything blocking here to get this merged?

**Review by songy23 — APPROVED** [review]

**Comment by lahsivjar** [comment]
@atoulme Friendly ping, will you be able to review this whenever you have time and merge the PR if things look okay?

**Review by codeboten — APPROVED** [review]
