### PR TITLE
[pkg/stanza] Fix issue where add operator did not correctly compile expressions

### LINKED ISSUE #26373: [receiver/filelog] Add operator no longer able to pull env vars with the `env` function
### Component(s)

receiver/filelog

### What happened?

See https://github.com/signalfx/splunk-otel-collector-chart/issues/904 for original report.

The commit https://github.com/open-telemetry/opentelemetry-collector-contrib/commit/44e1f6727ec81bbf434c05d9c52d09396947a70d#diff-1d453bc7c5b0dd32eec0c83b9b06e6aeb291890d5cf7585d437cee1c209e40b4L123 changed the default value of the `env` function to be `os_env_func` with the ability to patch back the calls to `env` to match `os_env_func`.

The backwards compatibility work is done when parsing the expression with a patcher struct that performs the string change:
```
type patcher struct{}

func (p *patcher) Visit(node *ast.Node) {
	n, ok := (*node).(*ast.CallNode)
	if !ok {
		return
	}
	c, ok := (n.Callee).(*ast.IdentifierNode)
	if !ok {
		return
	}
	if c.Value == "env" {
		c.Value = "os_env_func"
	}
}
```

However, this patcher struct is not used consistently across all usages of the expr compilation work. The `add` operator specifically doesn't use it, and therefore fails to find the environment variable lookup function.

### Collector version

0.83.0

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

### OpenTelemetry Collector configuration

_No response_

### Log output

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by djaglowski**
Alternate to #26374

Resolves #26373

### CODE REVIEW

File: pkg/stanza/operator/transformer/add/add_test.go [hunk 1]
```diff
@@ -297,6 +297,24 @@ func TestProcessAndBuild(t *testing.T) {
 			},
 			false,
 		},
+		{
+			"add_expr",
+			func() *Config {
+				cfg := NewConfig()
+				cfg.Field = entry.NewAttributeField("fookey")
+				cfg.Value = "EXPR('foo_' + body.key)"
```
Comment (atoulme) [inline pkg/stanza/operator/transformer/add/add_test.go:305]: Works for me, but would be best if you use the env function there to prove the patcher is doing its job, wdyt?

**Review by atoulme — APPROVED** [review]
