### PR TITLE
[cmd/opampsupervisor] Use `bufio.Reader` instead of `bufio.Scanner` to avoid buffer limits

### LINKED ISSUE #44127: Error when using passthrough_logs=true option #2
### Component(s)

cmd/opampsupervisor

## Description
I am running the Supervisor with passthrough_logs=true config option and get an error in the Supervisor log.

There has been an issue reported for this, but it was closed due to inactivity:
https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/37888

```
{
  "level": "error",
  "ts": 1762770313.9968863,
  "logger": "supervisor",
  "caller": "commander/commander.go:153",
  "msg": "Error reading agent stdout: %w",
  "error": "bufio.Scanner: token too long",
  "stacktrace": "github.com/open-telemetry/opentelemetry-collector-contrib/cmd/opampsupervisor/supervisor/commander.(*Commander).startWithPassthroughLogging.func1\n\t/builds/.../micotelcollector/opentelemetry-collector-contrib/cmd/opampsupervisor/supervisor/commander/commander.go:153"
}
```

## Details and mapping to the code (Copilot):

- The goroutine started with go func() { ... } in startWithPassthroughLogging reads the agent stdout (and another goroutine reads stderr). The stacktrace points at that goroutine in commander.go.
- Inside the goroutine the code uses a bufio.Scanner in a loop to read lines. When the scanner fails (Scan() returns false) the code checks scanner.Err() and logs an error. That log call produced the shown entry.
- The concrete error "bufio.Scanner: token too long" is produced by bufio.Scanner when a token (a line, by default) exceeds the scanner’s internal maximum token size (~64KB).
- The log’s "caller" and stacktrace fields show the file and line where the logging call was made (commander.go in the anonymous func), matching the code path that reads stdout.

## How to fix or mitigate

- If long single-line outputs are expected, stop using bufio.Scanner or increase its buffer:
  - Use scanner.Buffer(buf, max) to raise the max token size, or
  - Replace Scanner with bufio.Reader.ReadBytes('\n') / ReadString('\n') or use io.Copy to stream stdout to the logger (safer for arbitrary-length lines).
- Fix the logging call so the message doesn’t rely on printf formatting. Example: logger.Error("Error reading agent stdout", zap.Error(err)).

## Suggested fix (needs to be checked by a Golang expert)

```
*** a/cmd/opampsupervisor/supervisor/commander/commander.go
--- b/cmd/opampsupervisor/supervisor/commander/commander.go
@@
-import (
-	"bufio"
+import (
+	"bufio"
 	"context"
 	"errors"
 	"fmt"
 	"os"
 	"os/exec"
 	"path/filepath"
 	"slices"
 	"sync/atomic"
 	"syscall"
 	"time"
+	"io"
+	"strings"
 
 	"go.uber.org/zap"
@@
-	// capture agent output
-	go func() {
-		scanner := bufio.NewScanner(stdoutPipe)
-		for scanner.Scan() {
-			line := scanner.Text()
-			colLogger.Info(line)
-		}
-		if err := scanner.Err(); err != nil {
-			c.logger.Error("Error reading agent stdout: %w", zap.Error(err))
-		}
-	}()
-	go func() {
-		scanner := bufio.NewScanner(stderrPipe)
-		for scanner.Scan() {
-			line := scanner.Text()
-			colLogger.Error(line)
-		}
-		if err := scanner.Err(); err != nil {
-			c.logger.Error("Error reading agent stderr: %w", zap.Error(err))
-		}
-	}()
+	// capture agent output (use Reader to avoid Scanner token-size limit)
+	go func() {
+		reader := bufio.NewReader(stdoutPipe)
+		for {
+			line, err := reader.ReadString('\n')
+			if len(line) > 0 {
+				colLogger.Info(strings.TrimRight(line, "\r\n"))
+			}
+			if err != nil {
+				if err != io.EOF {
+					c.logger.Error("Error reading agent stdout", zap.Error(err))
+				}
+				break
+			}
+		}
+	}()
+	go func() {
+		reader := bufio.NewReader(stderrPipe)
+		for {
+			line, err := reader.ReadString('\n')
+			if len(line) > 0 {
+				colLogger.Error(strings.TrimRight(line, "\r\n"))
+			}
+			if err != nil {
+				if err != io.EOF {
+					c.logger.Error("Error reading agent stderr", zap.Error(err))
+				}
+				break
+			}
+		}
+	}()
@@
-	go func() {
-		scanner := bufio.NewScanner(stdoutPipe)
-		for scanner.Scan() {
-			stdout = append(stdout, scanner.Bytes()...)
-			stdout = append(stdout, byte('\n'))
-		}
-		if err := scanner.Err(); err != nil {
-			c.logger.Error("Error reading agent stdout: %w", zap.Error(err))
-		}
-	}()
-	go func() {
-		scanner := bufio.NewScanner(stderrPipe)
-		for scanner.Scan() {
-			stderr = append(stderr, scanner.Bytes()...)
-			stderr = append(stderr, byte('\n'))
-		}
-		if err := scanner.Err(); err != nil {
-			c.logger.Error("Error reading agent stderr: %w", zap.Error(err))
-		}
-	}()
+	go func() {
+		b, err := io.ReadAll(stdoutPipe)
+		if err != nil {
+			c.logger.Error("Error reading agent stdout", zap.Error(err))
+			return
+		}
+		stdout = append(stdout, b...)
+	}()
+	go func() {
+		b, err := io.ReadAll(stderrPipe)
+		if err != nil {
+			c.logger.Error("Error reading agent stderr", zap.Error(err))
+			return
+		}
+		stderr = append(stderr, b...)
+	}()
```

### Collector version

0.128.0

## Environment
OS: Linux
GO_VERSION: "1.24.3"

### OpenTelemetry Collector configuration

```yaml
extensions:
  zpages:
    endpoint: "127.0.0.1:55679"
 
  health_check:
    endpoint: "127.0.0.1:4320"
 
receivers:
  hostmetrics:
    collection_interval: 30s
    scrapers:
      cpu:
        metrics:
          system.cpu.utilization:
             enabled: true
      disk:
      load:
      memory:
        metrics:
          system.memory.utilization:
            enabled: true
      process:
        metrics:
          process.threads:
            enabled: true
          process.signals_pending:
            enabled: true
          process.paging.faults:
            enabled: true
          process.memory.utilization:
            enabled: true
          process.memory.usage:
            enabled: true
          process.open_file_descriptors:
            enabled: true
          process.memory.virtual:
            enabled: true
          process.handles:
            enabled: true
          process.disk.operations:
            enabled: true
          process.context_switches:
            enabled: true
          process.disk.io:
            enabled: true
          process.cpu.utilization:
            enabled: true
          process.cpu.time:
            enabled: true
        mute_process_name_error: true
        mute_process_exe_error: true
        mute_process_io_error: true
        mute_process_user_error: true
        mute_process_cgroup_error: true      
  otlp/richos:    
    protocols:
      http:
        endpoint: "127.0.0.1:4318"
      grpc:
        endpoint: "127.0.0.1:4317"
  otlp/tgvm:
    protocols:
      http:
        endpoint: "10.203.220.1:4318"
      grpc:
        endpoint: "10.203.220.1:4317"
 
processors:
  resourcedetection/env:
    detectors: [env, system]
    timeout: 15s
    override: true
    system:
      resource_attributes:
        host.name:
          enabled: true
        host.id:
          enabled: true
  batch:
    # Datadog APM Intake limit is 3.2MB. Let's make sure the batches do not go over that.
    send_batch_max_size: 8192 # (default = 8192): Maximum batch size of spans to be sent to the backend. The default value is 8192 spans.
    send_batch_size: 1024 # (default = 512): Maximum number of spans to process in a batch. The default value is 512 spans.
    timeout: 10s # (default = 5s): Maximum time to wait until the batch is sent. The default value is 5s.
  memory_limiter:
    check_interval: 5s
    limit_mib: 150
  resource:
    attributes:
      - key: env
        value: DEV
        action: upsert
      - key: build_number
        value: ${env:BUILD_NUMBER}
        action: upsert
 
exporters:
  otlphttp:
    endpoint: http://127.0.0.1:9081/0A/otlp-http
service:
  telemetry:
    # metrics:
    #  address: 'localhost:4319'
    logs:
      level: 'debug'
  extensions: [zpages, health_check]
  pipelines:
    metrics:
      receivers: [otlp/richos, otlp/tgvm, hostmetrics]
      processors: [memory_limiter, batch, resource, resourcedetection/env]
      exporters: [otlphttp]
    traces:
      receivers: [otlp/richos, otlp/tgvm]
      processors: [memory_limiter, batch, resource]
      exporters: [otlphttp]
    logs:
      receivers: [otlp/richos, otlp/tgvm]
      processors: [memory_limiter, batch, resource]
      exporters: [otlphttp]
```

### Log output

```shell
{
  "level": "error",
  "ts": 1762770313.9968863,
  "logger": "supervisor",
  "caller": "commander/commander.go:153",
  "msg": "Error reading agent stdout: %w",
  "error": "bufio.Scanner: token too long",
  "stacktrace": "github.com/open-telemetry/opentelemetry-collector-contrib/cmd/opampsupervisor/supervisor/commander.(*Commander).startWithPassthroughLogging.func1\n\t/builds/.../micotelcollector/opentelemetry-collector-contrib/cmd/opampsupervisor/supervisor/commander/commander.go:153"
}
```

### Additional context

The question is, why is the otelcol writing log lines with more than 64kB per line.

### Tip

<sub>[React](https://github.blog/news-insights/product-news/add-reactions-to-pull-requests-issues-and-comments/) with 👍 to help prioritize this issue. Please use comments to provide useful context, avoiding `+1` or `me too`, to help us triage it. Learn more [here](https://opentelemetry.io/community/end-user/issue-participation/).</sub>

### PR DESCRIPTION
**Pull request by dpaasman00**
#### Description

When passthrough logging is enabled, the supervisor reads in collector output and then writes it to its own logger instead of a dedicated log file. An error can occur when a single collector log is too big (>64kb) and cause the scanner to fail. Instead we'll use a reader splitting logs based on newlines to avoid issues with logs being too large.

#### Link to tracking issue
Fixes #44127

#### Testing
Hard to trigger with a unit test. Can verify using the hostmetrics receiver. I was able to trigger the bug when the hostmetrics receiver tried reading process metrics on my machine. This single log was greater than 64kb. On the previous version I saw the error `bufio.Scanner: token too long` but on this branch it prints the log no issue.

### CODE REVIEW

File: cmd/opampsupervisor/supervisor/commander/commander.go [hunk 1]
```diff
@@ -157,24 +159,42 @@ func (c *Commander) startWithPassthroughLogging() error {
...
-		for scanner.Scan() {
-			line := scanner.Text()
+		reader := bufio.NewReader(stderrPipe)
+		for {
+			line, err := reader.ReadString('\n')
+			if err != nil {
+				if err != io.EOF {
+					c.logger.Error("Error reading agent stderr", zap.Error(err))
+				}
+				// Log the last line if it exists and doesn't end with newline
```
Comment (atoulme) [inline cmd/opampsupervisor/supervisor/commander/commander.go]: that comment doesn't match the code below. You check the line length, then trim it, then log it. Did you mean to trim first?

File: cmd/opampsupervisor/supervisor/commander/commander.go [hunk 2]
```diff
@@ -226,24 +246,48 @@ func (c *Commander) StartOneShot() ([]byte, []byte, error) {
...
+				}
+				// Append the last line if it exists and doesn't end with newline
+				if line != "" {
+					line = strings.TrimRight(line, "\r\n")
+					stderr = append(stderr, []byte(line)...)
+					stderr = append(stderr, byte('\n'))
+				}
+				break
+			}
+			// Normalize line endings to \n
```
Comment (atoulme) [inline cmd/opampsupervisor/supervisor/commander/commander.go:288]: why are we normalizing line endings?

File: cmd/opampsupervisor/supervisor/commander/commander.go [hunk 3]
```diff
@@ -157,24 +159,42 @@ func (c *Commander) startWithPassthroughLogging() error {
...
+					c.logger.Error("Error reading agent stdout", zap.Error(err))
+				}
+				// Log the last line if it exists and doesn't end with newline
+				if line != "" {
+					line = strings.TrimRight(line, "\r\n")
+					colLogger.Info(line)
+				}
+				break
+			}
+			line = strings.TrimRight(line, "\r\n")
```
Comment (atoulme) [inline cmd/opampsupervisor/supervisor/commander/commander.go:176]:
```suggestion
```
this is a deviation of behavior, at least worth a separate PR.

**Comment by atoulme** [comment]
Please add a test.

File: cmd/opampsupervisor/supervisor/commander/commander.go (hunk 1 above)
Comment (dpaasman00) [reply cmd/opampsupervisor/supervisor/commander/commander.go]: Yep, will reword these comments

File: cmd/opampsupervisor/supervisor/commander/commander.go (hunk 3 above)
Comment (dpaasman00) [reply cmd/opampsupervisor/supervisor/commander/commander.go:176]: The previous `scanner.Scan` method used a default splitter [function](https://pkg.go.dev/bufio@go1.24.0#ScanLines) which accounted for a carriage return. The new code is intended to preserve that functionality. I could be mistaken but I think this change preserves that behavior.

File: cmd/opampsupervisor/supervisor/commander/commander.go (hunk 2 above)
Comment (dpaasman00) [reply cmd/opampsupervisor/supervisor/commander/commander.go:288]: We return the arrays as the output of this function. They are then fed into a `bufio.Scanner` which relies on the newlines to properly split and parse the output. I tested without the newlines and the parsing failed.

**Comment by dpaasman00** [comment]
> Please add a test.

I don't think adding a unit test for this will work well. There is an existing e2e test verifying the behavior of passthrough_logs that I updated. I added a new config for the collector using the hostmetrics receiver to try and trigger the same behavior I was experiencing.

File: cmd/opampsupervisor/supervisor/commander/commander.go (hunk 3 above)
Comment (atoulme) [reply cmd/opampsupervisor/supervisor/commander/commander.go:176]: Do you mean https://pkg.go.dev/bufio#ScanLines ? It applies a regex: `\r?\n`

File: cmd/opampsupervisor/supervisor/commander/commander.go (hunk 2 above)
Comment (atoulme) [reply cmd/opampsupervisor/supervisor/commander/commander.go:288]: yes, I think there's something off here.

File: cmd/opampsupervisor/supervisor/commander/commander.go (hunk 3 above)
Comment (dpaasman00) [reply cmd/opampsupervisor/supervisor/commander/commander.go:176]: Yea exactly, it applies that regex and then strips it from the line. Calling `strings.TrimRight(line, "\r\n")` should achieve the same thing.

Comment (atoulme) [reply cmd/opampsupervisor/supervisor/commander/commander.go:176]: Thanks, reading up on `TrimRight` and testing it shows this is indeed the same behavior.

File: cmd/opampsupervisor/supervisor/commander/commander.go (hunk 2 above)
Comment (atoulme) [reply cmd/opampsupervisor/supervisor/commander/commander.go:288]: ok I will let that one go - testing should catch any issues there

File: cmd/opampsupervisor/supervisor/commander/commander.go [hunk 4]
```diff
@@ -157,24 +159,42 @@ func (c *Commander) startWithPassthroughLogging() error {
...
 	// capture agent output
 	go func() {
-		scanner := bufio.NewScanner(stdoutPipe)
-		for scanner.Scan() {
-			line := scanner.Text()
+		reader := bufio.NewReader(stdoutPipe)
+		for {
+			line, err := reader.ReadString('\n')
+			if err != nil {
+				if err != io.EOF {
```
Comment (atoulme) [inline cmd/opampsupervisor/supervisor/commander/commander.go:166]: there's no data in the line variable if the error is EOF?

Comment (dpaasman00) [reply cmd/opampsupervisor/supervisor/commander/commander.go:166]: If the error is EOF there can be data present in `line`. When there's an error reading from the reader, we only want to log non EOF errors so we make sure it's not an EOF error. However, regardless of the error returned, if there's data in `line` we will still use it.

reader.ReadString doc: https://pkg.go.dev/bufio#Reader.ReadString

**Review by atoulme — APPROVED** [review]
