### PR TITLE
[exporter/loadbalancing] Use Linear probing to deal with hash collisions, and increase uniformity of endpoint distribution

### LINKED ISSUE #41200: [loadbalancingexporter] Distribution across target endpoints is not approximately uniform
### Component(s)

exporter/loadbalancing

## Description

In our production workload, the load balancing exporter is sending spans in a fashion that was more widely distributed than I expected, per pod. The highest pod received 3.5x the number of spans that the pod that received the lowest.

This creates a large distribution of CPU usage across endpoints that the LB exporter is sending to, not ideal for managing infrastructure, and right-sizing the allocations for the downstream workload.

## Steps to Reproduce

I've written a test that confirms that the distribution is not uniform, over 100k random trace IDs, I tracked the number of resolutions per endpoint:

Image

As you can see the trend is steeply down. I generated this writing this test in `consistent_hashing_test.go`. Then generated this chart from the CSV.

```golang
func TestUniformityOfDistribution(t *testing.T) {
	endpoints := make([]string, 300)
	for i := range endpoints {
		endpoints[i] = fmt.Sprintf("endpoint-%d", i)
	}
	ring := newHashRing(endpoints)

	n := 100_000
	resolutions := make(map[string][]pcommon.TraceID, len(endpoints))

	for i := 0; i < n; i++ {
		id := generateRandomTraceID(t)
		resolved := ring.endpointFor(id[:])
		resolutions[resolved] = append(resolutions[resolved], id)
	}

	timesResolved := make([]int, len(endpoints))
	for i := range timesResolved {
		res, ok := resolutions[endpoints[i]]
		numRes := 0
		if ok {
			numRes = len(res)
		}
		timesResolved[i] = numRes
	}

	f, err := os.Create("resolutions.csv")
	require.NoError(t, err)
	defer f.Close()

	_, err = f.WriteString("endpoint,n\n")
	require.NoError(t, err)

	for i := range endpoints {
		s := fmt.Sprintf("%s,%d\n", endpoints[i], timesResolved[i])
		_, err = f.WriteString(s)
		require.NoError(t, err)
	}
}
```

## Expected Result

Traces are evenly distributed across endpoints.

## Actual Result

They are not even close to uniformly distributed. We observe a trend as shown in the screenshot.

### Collector version

v0.128.0

### OpenTelemetry Collector configuration

```yaml

```

### Log output

```shell

```

### Additional context

_No response_

### Tip

<sub>[React](https://github.blog/news-insights/product-news/add-reactions-to-pull-requests-issues-and-comments/) with 👍 to help prioritize this issue. Please use comments to provide useful context, avoiding `+1` or `me too`, to help us triage it. Learn more [here](https://opentelemetry.io/community/end-user/issue-participation/).</sub>

### PR DESCRIPTION
**Pull request by jamesmoessis**
#### Description

Updates the ring hash algorithm to use linear probing to decrease the variance of endpoints chosen due to hash collisions.
 
Also updates it to use 4 bytes instead of one - this would cause collision when using more than 256 endpoints, since the byte would overflow.

These changes are discussed and benchmarked in: https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/41200. The benchmarks showed clear benefits for negligible resource consumption.

The only actual changes to main code in the PR is that in `consistent_hashing.go`. The rest is just changing the expectations of the test to match the altered hashing algorithm.

#### Link to tracking issue

Partially fixes https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/41200 

#### Testing

The tests needed to be re-arranged. This was really quite tedious, since they all depend on the specific randomness of the existing hashing algorithm. So I had to re arrange some of the test's expectations with that, too. At some point, they should be redesigned to be more deterministic so more work can easily be done on the hash ring in the future.

### CODE REVIEW

File: exporter/loadbalancingexporter/consistent_hashing.go [hunk 1]
```diff
@@ -103,10 +105,12 @@ func bsearch(pos position, left []ringItem, right []ringItem) ringItem {
 // The slice length of the result matches the numPoints.
 func positionsFor(endpoint string, numPoints int) []position {
 	res := make([]position, 0, numPoints)
+	buf := make([]byte, 4)
 	for i := 0; i < numPoints; i++ {
 		h := crc32.NewIEEE()
+		binary.LittleEndian.PutUint32(buf, uint32(i))
```
Comment (MovieStoreGuy) [inline exporter/loadbalancingexporter/consistent_hashing.go:111]: Does this strictly need to be LittleEndian, or can it be the architecture default?

**Review by MovieStoreGuy — APPROVED** [review]

File: exporter/loadbalancingexporter/consistent_hashing.go [hunk 2]
```diff
@@ -4,13 +4,15 @@
...
 	"hash/crc32"
 	"sort"
 )
 
 const (
-	maxPositions  uint32 = 36000 // 360 degrees with two decimal places
-	defaultWeight int    = 100   // the number of points in the ring for each entry. For better results, it should be greater than 100.
+	maxPositions     uint32 = 36000 // 360 degrees with two decimal places
+	defaultWeight    int    = 100   // the number of points in the ring for each entry. For better results, it should be greater than 100.
+	linearProbeLimit int    = 10    // The number of times to probe ahead in the hash ring if there is a collision while constructing the hash ring
```
Comment (MovieStoreGuy) [inline exporter/loadbalancingexporter/consistent_hashing.go:15]: Would you every want this configurable?

**Comment by MovieStoreGuy** [comment]
I've merged this so it can make it into the next release, and the questions can be followed up later.

File: exporter/loadbalancingexporter/consistent_hashing.go (hunk 2 above)
Comment (jamesmoessis) [reply exporter/loadbalancingexporter/consistent_hashing.go:15]: Probably unnecessary at this point. We discussed in #41200 about making these constants somewhat configurable, or calculating a value for them for the user. But we will figure that out with time

File: exporter/loadbalancingexporter/consistent_hashing.go (hunk 1 above)
Comment (jamesmoessis) [reply exporter/loadbalancingexporter/consistent_hashing.go:111]: It can be anything. Big endian or little endian doesn't make any difference - just need to append the number to the hash. I suppose it could be the architecture default but then you'd get different results on different architectures and it might be a bit annoying test-wise. Happy to hear your thoughts on it

**Comment by jamesmoessis** [comment]
Thankyou @MovieStoreGuy :)
