### PR TITLE
[pkg/stanza]: allow max_batch_size to be 0 for unlimited batching in recombine

### LINKED ISSUE #43982: Container Parser Log Truncation at 1.6 MB when using multiline log recombination
### Component(s)

pkg/stanza

/pkg/stanza/operator/parser/container

## Description
Container logs processed by the OpenTelemetry Collector's container parser are being truncated at exactly **1,638,466 bytes (~1.56 MiB)** when using multiline log recombination.

## Steps to Reproduce
I use this config for log recombine logs multilines but I still found the split log
```yaml
    receivers:
      filelog:
        include:
          - /var/log/pods/*/*/*.log
        operators:
          - id: container-parser
            type: container
          - id: recombine-multiline
            type: recombine
            combine_field: body
            combine_with: ""
            is_last_entry: body matches "\\n$"
            source_identifier: attributes["log.file.path"]
            max_batch_size: 10000
          - id: trim-trailing-newline
            type: regex_replace
            field: body
            regex: "[\n]+$"
            replace_with: ""
        start_at: end
        max_log_size: 10MiB
        storage: file_storage
```
## Expected Result
It should recombine logs that larger than 1.56 MiB

## Actual Result
it just split the logs because of hard limit on this `defaultMaxBatchSize` of container parser

### Collector version

v0.138.0

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

### OpenTelemetry Collector configuration

```yaml
receivers:
      filelog:
        include:
          - /var/log/pods/*/*/*.log
        operators:
          - id: container-parser
            type: container
          - id: recombine-multiline
            type: recombine
            combine_field: body
            combine_with: ""
            is_last_entry: body matches "\\n$"
            source_identifier: attributes["log.file.path"]
            max_batch_size: 10000
          - id: trim-trailing-newline
            type: regex_replace
            field: body
            regex: "[\n]+$"
            replace_with: ""
        start_at: end
        max_log_size: 10MiB
        storage: file_storage
```

### Log output

```shell

```

### Additional context

_No response_

### Tip

<sub>[React](https://github.blog/news-insights/product-news/add-reactions-to-pull-requests-issues-and-comments/) with 👍 to help prioritize this issue. Please use comments to provide useful context, avoiding `+1` or `me too`, to help us triage it. Learn more [here](https://opentelemetry.io/community/end-user/issue-participation/).</sub>

### PR DESCRIPTION
**Pull request by MoosaTae**
#### Description
Allow setting `max_batch_size: 0` in the recombine operator to disable the batch size limit, enabling unlimited batching.

- Modified condition in `transformer.go` to check `maxBatchSize > 0` before applying the limit
- Added test case `TestMaxBatchSizeUnlimited` to verify the new behavior

#### Link to tracking issue
Fixes #43982 (partial - enables the feature)

#### Testing
- Added `TestMaxBatchSizeUnlimited` test

## Configuration Example

```yaml
receivers:
  filelog:
    operators:
      - type: container
```

### CODE REVIEW

**Review by bogdandrutu — COMMENTED** [review]
Title does not match the logic in the PR

**Review by andrzej-stencel — CHANGES_REQUESTED** [review]
I 💯 agree with the issue stated in https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/43982. The output from the `container` operator should not be arbitrarily limited, it should be configurable by the user. How exactly this should be done needs to be discussed.

Let me block this pull request until we reach a conclusion in the discussion on the [issue](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/43982).

File: pkg/stanza/operator/parser/container/parser_test.go [hunk 1]
```diff
@@ -77,13 +77,17 @@ func TestFormatDetectionFailure(t *testing.T) {
...
+	cfg := createRecombineConfig(Config{
+		MaxLogSize: 102400,
+	})
 	expected := recombine.NewConfigWithID(recombineInternalID)
 	expected.IsLastEntry = "attributes.logtag == 'F'"
 	expected.CombineField = entry.NewBodyField()
 	expected.CombineWith = ""
 	expected.SourceIdentifier = entry.NewAttributeField(attrs.LogFilePath)
 	expected.MaxLogSize = 102400
+	expected.MaxBatchSize = 0          // unlimited
```
Comment (ChrsMark) [inline pkg/stanza/operator/parser/container/parser_test.go]: This changes the container parser too, however the [suggestion](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/43982#issuecomment-3521276289) was to do it in a different PR, right?

Comment (MoosaTae) [reply pkg/stanza/operator/parser/container/parser_test.go]: ah, sorry my mistake, I understand it now

**Review by ChrsMark — COMMENTED** [review]
The patch looks good to me but since I'm not super familiar with the whole stanza package let's wait for @andrzej-stencel to review this too as code-owner.

File: .chloggen/fix_container-parser-configurable-batch-size.yaml [hunk 2]
```diff
@@ -0,0 +1,29 @@
+# Use this changelog template to create an entry for release notes.
+
+# One of 'breaking', 'deprecation', 'new_component', 'enhancement', 'bug_fix'
+change_type: enhancement
+
+# The name of the component, or a single word describing the area of concern, (e.g. receiver/filelog)
+component: operator/recombine
```
Comment (andrzej-stencel) [inline .chloggen/fix_container-parser-configurable-batch-size.yaml]:
```suggestion
component: pkg/stanza
```

File: .chloggen/fix_container-parser-configurable-batch-size.yaml [hunk 3]
```diff
@@ -0,0 +1,29 @@
...
+
+# A brief description of the change.  Surround your text with quotes ("") if it needs to start with a backtick (`).
+note: Allow `max_batch_size` of 0 for unlimited batching in recombine operator
```
Comment (andrzej-stencel) [inline .chloggen/fix_container-parser-configurable-batch-size.yaml]:
```suggestion
note: Allow `max_batch_size` of 0 for unlimited batching in `recombine` operator
```

File: .chloggen/fix_container-parser-configurable-batch-size.yaml [hunk 4]
```diff
@@ -0,0 +1,29 @@
+# Use this changelog template to create an entry for release notes.
+
+# One of 'breaking', 'deprecation', 'new_component', 'enhancement', 'bug_fix'
+change_type: enhancement
```
Comment (andrzej-stencel) [inline .chloggen/fix_container-parser-configurable-batch-size.yaml]:
```suggestion
change_type: breaking
```

I think we should mark it as a breaking change.

The previous behavior with `max_batch_size: 0` was the same as with `max_batch_size: 1`. This behavior changes now. As unlikely as it is for a user to have used `max_batch_size: 0` in their configuration, I'd rather be on the safe side and mention this change in the "breaking changes" section.

**Review by andrzej-stencel — COMMENTED** [review]
Thanks @MoosaTae! See the changelog entry comments. I also have two more asks:
 
- Add a warning when both `max_batch_size` and `max_log_size` are set to `0`.
- Update the docs at /pkg/stanza/docs/operators/recombine.md

File: .chloggen/fix_container-parser-configurable-batch-size.yaml (hunk 2 above)
Comment (MoosaTae) [reply .chloggen/fix_container-parser-configurable-batch-size.yaml]: done

File: .chloggen/fix_container-parser-configurable-batch-size.yaml (hunk 3 above)
Comment (MoosaTae) [reply .chloggen/fix_container-parser-configurable-batch-size.yaml]: done

File: .chloggen/fix_container-parser-configurable-batch-size.yaml (hunk 4 above)
Comment (MoosaTae) [reply .chloggen/fix_container-parser-configurable-batch-size.yaml]: done

File: .chloggen/fix_container-parser-configurable-batch-size.yaml [hunk 5]
```diff
@@ -0,0 +1,29 @@
...
+
+# Mandatory: One or more tracking issues related to the change. You can use the PR number here if no issue exists.
+issues: [43982]
+
+# (Optional) One or more lines of additional information to render under the primary note.
+# These lines will be padded with 2 spaces and then inserted directly into the document.
+# Use pipe (|) for multiline entries.
+subtext: |
+  The recombine operator now supports setting `max_batch_size: 0` to disable batch size limits.
+  This allows unlimited batching, letting entries be combined based only on `max_log_size` and matching conditions.
```
Comment (andrzej-stencel) [inline .chloggen/fix_container-parser-configurable-batch-size.yaml:20]:
```suggestion
  This allows unlimited batching, letting entries be combined based only on `max_log_size` and matching conditions.
  If you have `max_batch_size: 0` in your config and want to keep the behavior unchanged, change the configuration to `max_batch_size: 1`.
```

**Review by andrzej-stencel — APPROVED** [review]
Thanks @MoosaTae!

**Review by ChrsMark — APPROVED** [review]
