### PR TITLE
[chore] Fix flaky TestComponentStatus test

### LINKED ISSUE #44415: [internal/healthcheck]: Report for failed tests on main
Auto-generated report for `__run_3` job build.

Link to failed build: https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/19525781433
Commit: 478e34b
PR: #44323

### Component(s)
internal/healthcheck

#### Test Failures
-  `TestComponentStatus`
```
=== RUN   TestComponentStatus
    extension_test.go:41: 
        	Error Trace:	/home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/internal/healthcheck/extension_test.go:41
        	Error:      	Received unexpected error:
        	            	failed to bind to address 127.0.0.1:43093: listen tcp 127.0.0.1:43093: bind: address already in use
        	Test:       	TestComponentStatus
--- FAIL: TestComponentStatus (0.00s)

```

**Note**: Information about any subsequent build failures that happen while
this issue is open, will be added as comments with more information to this issue.

### PR DESCRIPTION
**Pull request by iblancasa**
#### Link to tracking issue
Fixes #44415

#### Testing
Run with `-count=200`.

### CODE REVIEW

**Review by codeboten — COMMENTED** [review]
Looks like this is causing some failures:

```
 Goroutine 2582 in state select, with net/http.(*persistConn).readLoop on top of the stack:
net/http.(*persistConn).readLoop(0xc0003246c0)
	/opt/hostedtoolcache/go/1.24.10/x64/src/net/http/transport.go:2398 +0x14f3
created by net/http.(*Transport).dialConn in goroutine 2580
	/opt/hostedtoolcache/go/1.24.10/x64/src/net/http/transport.go:1947 +0x2d52
]
FAIL	github.com/open-telemetry/opentelemetry-collector-contrib/internal/healthcheck/internal/http	1.044s

DONE 111 tests, 1 failure in 2.255s
```

**Comment by iblancasa** [comment]
@codeboten thanks! Will take a look

File: internal/healthcheck/extension_test.go [hunk 1]
```diff
@@ -32,6 +32,7 @@ func TestComponentStatus(t *testing.T) {
 	cfg.GRPCConfig.NetAddr.Endpoint = testutil.GetAvailableLocalAddress(t)
 	cfg.UseV2 = true
 	ext := NewHealthCheckExtension(t.Context(), *cfg, extensiontest.NewNopSettings(extensiontest.NopType))
+	t.Cleanup(func() { require.NoError(t, ext.Shutdown(t.Context())) })
```
Comment (atoulme) [inline internal/healthcheck/extension_test.go]: can't use t.Context() in Cleanup because it's already canceled by then. You can use defer.

**Comment by atoulme** [comment]
Please address the conflict.

**Review by atoulme — APPROVED** [review]

**Review by evan-bradley — APPROVED** [review]
Overall makes sense to me, appreciate your patience with reviews. Thanks @iblancasa!
