### PR TITLE
[connector/countconnector] Handle non-string attributes

### LINKED ISSUE #30314: Count connector improperly handles non-string attributes
### Component(s)

connector/count

## Description
When specifying attributes the connector will lose the client provided value if it is not a string, such as for `http.status_code`. [The connector](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/connector/countconnector/counter.go#L44) calls [`.Str()`](https://github.com/open-telemetry/opentelemetry-collector/blob/main/pdata/pcommon/value.go#L203) without checking the type, which results in setting the value to an empty string if the original value is not a string.

## Steps to Reproduce
Count an attribute sent by clients as a non-string value:
```yaml
connectors:
  count:
    spans:
      http.status.codes:
        attributes:
          - key: http.status_code
```

## Expected Result
The connector emits metrics with the counts split by `http.status_code`

## Actual Result
The connector emits metrics with `http.status_code` set to an empty string.

### Collector version

v0.91.0

### Environment information

_No response_

### OpenTelemetry Collector configuration

_No response_

### Log output

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by lkwronski**
**Description:** 

Adding support for non string attributes in the count connector. I started working based on https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/30314#issuecomment-1889535313, but it doesn't work. When I try to add the type constaint:

```
type Number interface {
	int64 | float64
}

type AttributeConfig struct {
	Key               string  `mapstructure:"key"`
	DefaultValue      Number  `mapstructure:"default_value"`
}
```
This causes the following error:
```
 cannot use type Number outside a type constraint: interface contains type constraints
```

My idea was to introduce new fields `DefaultIntValue` and `DefaultFloatValue` to handle number types, let me know if this makes sense, if so, I will add documentation and finalize this PR.

**Link to tracking Issue:** Fixes https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/30314.

**Testing:** Added unit test

**Documentation:** TODO

### CODE REVIEW

File: connector/countconnector/config.go [hunk 1]
```diff
@@ -47,8 +47,10 @@ type MetricInfo struct {
 }
 
 type AttributeConfig struct {
-	Key          string `mapstructure:"key"`
-	DefaultValue string `mapstructure:"default_value"`
+	Key               string  `mapstructure:"key"`
+	DefaultValue      string  `mapstructure:"default_value"`
+	DefaultIntValue   int64   `mapstructure:"default_int_value"`
+	DefaultFloatValue float64 `mapstructure:"default_float_value"`
```
Comment (djaglowski) [inline connector/countconnector/config.go:53]: I think this design introduces unnecessary relationships between fields in the config. If we cannot use a type constraint, can we just make `DefaultValue` an `any`?

File: connector/countconnector/counter.go [hunk 2]
```diff
@@ -41,9 +41,23 @@ func (c *counter[K]) update(ctx context.Context, attrs pcommon.Map, tCtx K) erro
...
+				switch typeAttr := attrVal.Type(); typeAttr {
+				case pcommon.ValueTypeInt:
+					countAttrs.PutInt(attr.Key, attrVal.Int())
+				case pcommon.ValueTypeDouble:
+					countAttrs.PutDouble(attr.Key, attrVal.Double())
+				default:
+					countAttrs.PutStr(attr.Key, attrVal.Str())
+				}
+			} else {
+				switch v := attr.DefaultValue.(type) {
```
Comment (lkwronski) [inline connector/countconnector/counter.go:53]: @djaglowski Thanks for review.  I agree that your idea simplifies usage. I just have a problem with this part of the code, I'm not sure if I need to match for each type int -> `int, int8, int16, int32, int64` and the same doubt for float.

File: connector/countconnector/counter.go [hunk 3]
```diff
@@ -41,9 +41,23 @@ func (c *counter[K]) update(ctx context.Context, attrs pcommon.Map, tCtx K) erro
 		countAttrs := pcommon.NewMap()
 		for _, attr := range md.attrs {
 			if attrVal, ok := attrs.Get(attr.Key); ok {
-				countAttrs.PutStr(attr.Key, attrVal.Str())
-			} else if attr.DefaultValue != "" {
```
Comment (djaglowski) [inline connector/countconnector/counter.go:45]: We need to keep this check, or something equivalent.

File: connector/countconnector/counter.go (hunk 2 above)
Comment (djaglowski) [reply connector/countconnector/counter.go:53]: Sure, it's verbose but doable. [Here's a decently comprehensive list](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/11d29882ebd3c97c839a590fcba089e27de6b355/pkg/stanza/adapter/converter.go#L285) which is used elsewhere.

Comment (djaglowski) [reply connector/countconnector/counter.go:53]: Hmm, good point. I suppose since we know these values can only come from configuration, we may not need to handle all types of ints, etc. I'm not sure how we establish guarantees around this but I'm also comfortable just getting a reasonable first implementation in place and adjusting it later if needed.

Comment (lkwronski) [reply connector/countconnector/counter.go:53]: Thanks, that leaves it as it is. PR is ready for review.

File: connector/countconnector/counter.go (hunk 3 above)
Comment (djaglowski) [reply connector/countconnector/counter.go:45]: We need to check if there is a default value set. If not, won't the type switch below panic?

File: connector/countconnector/testdata/config.yaml [hunk 4]
```diff
@@ -165,3 +165,17 @@
...
+      limited.logrecord.count:
+        description: Limited log record count.
+        attributes:
+          - key: env
+            default_value: "local"
+          - key: http_code
+            default_value: 200
+          - key: request_success
+            default_value: 0.85
+
```
Comment (djaglowski) [inline connector/countconnector/testdata/config.yaml:181]:
```suggestion

```

File: connector/countconnector/counter.go (hunk 3 above)
Comment (lkwronski) [reply connector/countconnector/counter.go:45]: Sure, I added panic.

Comment (djaglowski) [reply connector/countconnector/counter.go:45]: We do not rely on panics in the collector. There is no requirement to set a default value, so this is not even a problem. We should just skip the block, like we were doing previously.

**Review by jpkrohling — COMMENTED** [review]
Agree with @djaglowski that the panic is out of place. Other than that, I like the solution given to the default value.

File: connector/countconnector/counter.go (hunk 3 above)
Comment (lkwronski) [reply connector/countconnector/counter.go:45]: I hope I understand now. I added a condition to skip if the default value is `nil`.

**Review by djaglowski — APPROVED** [review]

**Comment by djaglowski** [comment]
Thanks @lkwronski
