### PR TITLE
[receiver/splunkhecreceiver] timestamp accepts nano, micro, milli, and seconds

### LINKED ISSUE #36571: [receiver/splunkhecreceiver] timestamp overflows when not in seconds
### Component(s)

https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/8e0ea012fe93a272b78e27a94e690084538b0963/receiver/splunkhecreceiver

## Description

Splunk HEC allows `time` to be nanosecond, microsecond, millisecond and in second. splunk to log/metric converters assumes all time is in seconds:
- https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/8e0ea012fe93a272b78e27a94e690084538b0963/receiver/splunkhecreceiver/splunk_to_logdata.go#L57
- https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/8e0ea012fe93a272b78e27a94e690084538b0963/receiver/splunkhecreceiver/splunkhec_to_metricdata.go#L122

The receiver should not assume all incoming time is in second and cause overflow by trying to convert `time` to nanosecond before confirming the time unit.

## Steps to Reproduce

1. run otel with splunkhecreceiver
2. curl -X POST http://localhost:8088/services/collector -d '{"time":1732604863241,"event":"data","source":"test","sourcetype":"test","host":"test","index":"main"}'
3. timestamp for the event is now 9223372036854774

## Expected Result

1732604863241000000
Tuesday, November 26, 2024 7:07:43.241 UTC

## Actual Result

9223372036854774
Friday, April 11, 2262 11:47:16.854 UTC

### Collector version

1.0.9

## Environment
Debian Bookworm
go 1.22

### OpenTelemetry Collector configuration

```yaml
receivers:
 splunk_hec:
   endpoint: 8088
   splitting: false
```

### Log output

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by timannguyen**
…d seconds

#### Description

Splunk HEC accepts nano, micro, milli, and sec. It will now guess the time before converting it to nanoseconds. to prevent overflow.

#### Link to tracking issue
Fixes [36571](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/36571)

#### Testing

unit test

#### Documentation

https://docs.splunk.com/Documentation/SplunkCloud/latest/Data/FormateventsforHTTPEventCollector#Event_metadata

### CODE REVIEW

**Review by VihasMakwana — COMMENTED** [review]
LGTM but can you update PR description?

**Comment by splunkericl** [comment]
also need to change here: https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/receiver/splunkhecreceiver/splunkhec_to_metricdata.go#L32

File: receiver/splunkhecreceiver/splunkhec_to_metricdata.go [hunk 1]
```diff
@@ -118,8 +118,37 @@ func addDoubleGauge(metrics pmetric.MetricSlice, metricName string, value float6
 	attributes.CopyTo(doublePt.Attributes())
 }
 
-func convertTimestamp(sec float64) pcommon.Timestamp {
-	return pcommon.Timestamp(sec * 1e9)
+/*
+	Splunk HEC timestamps can be in nanoseconds, microseconds, milliseconds, and seconds epoch.
```
Comment (dehaansa) [inline receiver/splunkhecreceiver/splunkhec_to_metricdata.go:122]: Do you happen to have a documentation link for this statement?

**Review by dehaansa — COMMENTED** [review]
This should have a bugfix changelog entry.

As the other commenter noted, this should also be fixed in the `splunkhec_to_metricdata.go` file, otherwise this appears to be a valuable fix, thanks for the contribution.

**Comment by timannguyen** [comment]
> also need to change here: https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/receiver/splunkhecreceiver/splunkhec_to_metricdata.go#L32

it uses the `convertTimestamp` already.

**Comment by splunkericl** [comment]
> > also need to change here: https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/receiver/splunkhecreceiver/splunkhec_to_metricdata.go#L32
> 
> it uses the `convertTimestamp` already.

This is the function:
```
func convertTimestamp(sec float64) pcommon.Timestamp {
	return pcommon.Timestamp(sec * 1e9)
}
```

**Comment by atoulme** [comment]
Please add a changelog entry, start by executing `make chlog-new` from root of the checkout and fill in the yaml file. Please move this PR as ready to review afterwards.

**Comment by timannguyen** [comment]
> Please add a changelog entry, start by executing `make chlog-new` from root of the checkout and fill in the yaml file. Please move this PR as ready to review afterwards.

My bad. done

**Review by atoulme — APPROVED** [review]
