### PR TITLE
[exporter/prometheusremotewrite] Add support for disable_scope_info and fix scope attribute label translation

### LINKED ISSUE #45266: Prometheus Remote Write exporter should export InstrumentationScope attributes
### Component(s)

exporter/prometheusremotewrite

## Description

The [Prometheus and OpenMetrics compatibility specifiation](https://opentelemetry.io/docs/specs/otel/compatibility/prometheus_and_openmetrics/#instrumentation-scope-1) states that 

> Prometheus exporters MUST by default add [...] the scope attributes as labels with `otel_scope_` prefix

This is not done in the current version of the PRW exporter, which leads to surprising behavior on applications that leverage scope attributes to differentiate metrics. I believe the scope name, version and schema URL are ignored as well.

https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/7b9d37f11b229a93a758cc06a25a95a819952312/pkg/translator/prometheusremotewrite/metrics_to_prw.go#L76

## Steps to Reproduce

Emit metrics with scope attributes.

## Expected Result

The attributes are reflected in the ingested Prometheus metrics.

## Actual Result

The attributes disappear.

### Collector version

v0.142.0

### Additional context

Previous discussions:
- https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/21091
- https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/24248
- https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/43122

### Tip

<sub>[React](https://github.blog/news-insights/product-news/add-reactions-to-pull-requests-issues-and-comments/) with 👍 to help prioritize this issue. Please use comments to provide useful context, avoiding `+1` or `me too`, to help us triage it. Learn more [here](https://opentelemetry.io/community/end-user/issue-participation/).</sub>

### PR DESCRIPTION
**Pull request by SoumyaRaikwar**
#### Description

This PR adds support for the `disable_scope_info` configuration option in the `prometheusremotewrite` exporter. While InstrumentationScope attributes were already being exported as labels, this change adds the ability to disable this behavior and ensures that the `translation_strategy` (including label sanitization) is properly applied to all scope-related label keys (`otel_scope_name`, `otel_scope_version`, and custom scope attributes).

#### Link to tracking issue
Fixes #45266

#### Testing
- Added unit tests in [helper_test.go](cci:7://file:///media/soumya/DATA/open-source/opentelemetry-collector-contrib/pkg/translator/prometheusremotewrite/helper_test.go:0:0-0:0) to verify `disable_scope_info` functionality.
- Verified that `translation_strategy` (sanitization) is correctly applied to `otel_scope_name`, `otel_scope_version`, and custom scope attribute labels.
- All existing unit tests pass.

#### Documentation
- Updated [README.md](cci:7://file:///media/soumya/DATA/open-source/opentelemetry-collector-contrib/exporter/prometheusremotewriteexporter/README.md:0:0-0:0) and [config.schema.yaml](cci:7://file:///media/soumya/DATA/open-source/opentelemetry-collector-contrib/exporter/prometheusremotewriteexporter/config.schema.yaml:0:0-0:0) with the `disable_scope_info` configuration option description.
- Added a focused changelog entry in `.chloggen/issue-45266.yaml`.

### CODE REVIEW

File: pkg/translator/prometheusremotewrite/helper.go [hunk 1]
```diff
@@ -152,6 +153,13 @@ func createAttributes(resource pcommon.Resource, attributes pcommon.Map, scope p
 			}
 		} else {
 			l[finalKey] = label.Value
+			if logOnOverwrite {
```
Comment (dashpole) [inline pkg/translator/prometheusremotewrite/helper.go]: Is this change related to the PR?

File: pkg/translator/prometheusremotewrite/helper.go
Comment (dashpole) [inline pkg/translator/prometheusremotewrite/helper.go:215]: is moving this function necessary to do in this PR?  It makes the diff hard to review.

File: exporter/prometheusremotewriteexporter/README.md [hunk 2]
```diff
@@ -65,6 +65,7 @@ The following settings can be optionally configured:
   - `lag_record_frequency` (default = `15s`): Frequency for how often the exporter will record the lag of the WAL. 
 - `target_info`: customize `target_info` metric
   - `enabled` (default = true): If `enabled` is `true`, a `target_info` metric will be generated for each resource metric (see https://github.com/open-telemetry/opentelemetry-specification/pull/2381).
+- `disable_scope_info` (default = false): If `true`, the scope info metrics (`otel_scope_name`, `otel_scope_version` and `otel_scope_...` attributes) will not be exported.
```
Comment (ArthurSens) [inline exporter/prometheusremotewriteexporter/README.md]: These aren't metrics in OTLP, and won't be metrics in the remote write request. Honestly, I don't know what to call them, but the closest would be "labels" 😅

File: exporter/prometheusremotewriteexporter/config.schema.yaml [hunk 3]
```diff
@@ -37,6 +37,9 @@ properties:
   add_metric_suffixes:
     description: AddMetricSuffixes controls whether unit and type suffixes are added to metrics on export
     type: boolean
+  disable_scope_info:
+    description: DisableScopeInfo allows disabling the export of the scope info metrics
```
Comment (ArthurSens) [inline exporter/prometheusremotewriteexporter/config.schema.yaml]: Let's fix this here as well

**Review by ArthurSens — COMMENTED** [review]
Could we work on only one change per PR?

Let's choose between implementing the scope bits or the histogram bits and create a separate PR for the one we aren't focusing here

File: pkg/translator/prometheusremotewrite/helper.go (hunk 1 above)
Comment (SoumyaRaikwar) [reply pkg/translator/prometheusremotewrite/helper.go]: it was unrelated. I have reverted this change to keep the PR focused.

File: pkg/translator/prometheusremotewrite/helper.go
Comment (SoumyaRaikwar) [reply pkg/translator/prometheusremotewrite/helper.go:215]: reverted it back to original location

**Comment by SoumyaRaikwar** [comment]
> Could we work on only one change per PR?
> 
> Let's choose between implementing the scope bits or the histogram bits and create a separate PR for the one we aren't focusing here

@ArthurSens 
I have reverted the addHistogramDataPoints and the logging logic, will do the refactoring  in a seperate pr

File: exporter/prometheusremotewriteexporter/README.md (hunk 2 above)
Comment (SoumyaRaikwar) [reply exporter/prometheusremotewriteexporter/README.md]: updated

File: exporter/prometheusremotewriteexporter/config.schema.yaml (hunk 3 above)
Comment (SoumyaRaikwar) [reply exporter/prometheusremotewriteexporter/config.schema.yaml]: done!

**Comment by SoumyaRaikwar** [comment]
@rapphil  @dashpole  @ArthurSens @ywwg all the ci are passing now .

File: pkg/translator/prometheusremotewrite/helper.go [hunk 4]
```diff
@@ -176,16 +177,22 @@ func createAttributes(resource pcommon.Resource, attributes pcommon.Map, scope p
...
+		}
+		if scope.Version() != "" {
+			l["otel_scope_version"] = scope.Version()
+		}
+		scope.Attributes().Range(func(k string, v pcommon.Value) bool {
+			key, err := labelNamer.Build("otel_scope_" + k)
+			if err != nil {
+				return true
+			}
+			l[key] = v.AsString()
```
Comment (dashpole) [inline pkg/translator/prometheusremotewrite/helper.go]:
```suggestion
			if err == nil {
				l[key] = v.AsString()
			}
```

File: pkg/translator/prometheusremotewrite/helper.go [hunk 5]
```diff
@@ -176,16 +177,22 @@ func createAttributes(resource pcommon.Resource, attributes pcommon.Map, scope p
...
+			return true
+		})
 	}
-	scope.Attributes().Range(func(k string, v pcommon.Value) bool {
```
Comment (dashpole) [inline pkg/translator/prometheusremotewrite/helper.go:185]: Looks like we are already adding scope attributes as labels.  Can you update the PR title/description/changelog to make clear that this:

* Adds support for disable_scope_info
* Ensures translation_strategy is properly applied to scope attribute label keys.

Comment (SoumyaRaikwar) [reply pkg/translator/prometheusremotewrite/helper.go:185]: @dashpole Done in the latest commit I have updated the PR title, description, and also updated the changelog to reflect that the scope is now focused on:

- Adding support for disable_scope_info.
- Ensuring the translation_strategy is properly applied to all scope-related label keys (otel_scope_name, otel_scope_version,etc).

**Review by ArthurSens — APPROVED** [review]
LGTM, CI failures seem unrelated... I've retriggered them. 

If they fail again, could you rebase your PR on top of main? Hopefully things are looking better on the main branch

**Review by dashpole — APPROVED** [review]

**Review by codeboten — APPROVED** [review]
