### PR TITLE
[extension/httpforwarder] Shutdown should wait server exit

### LINKED ISSUE #37716: [flaky test][exporter/httpforwarder] TestComponentLifecycle is flaky
### Component(s)

extension/httpforwarder

### Describe the issue you're reporting

Based on similar component lifecycle flaky tests a reasonable guess is that the port used in the test is being used by multiple tests and it is not being properly released due to some race during shutdown.

https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/13123874574/job/36615999506#step:8:185

```terminal
=== FAIL: . TestComponentLifecycle/lifecycle (0.00s)
    generated_component_test.go:46: 
        	Error Trace:	D:/a/opentelemetry-collector-contrib/opentelemetry-collector-contrib/extension/httpforwarderextension/generated_component_test.go:46
        	Error:      	Received unexpected error:
        	            	failed to bind to address localhost:7070: listen tcp 127.0.0.1:7070: bind: Only one usage of each socket address (protocol/network address/port) is normally permitted.
        	Test:       	TestComponentLifecycle/lifecycle

=== FAIL: . TestComponentLifecycle (0.00s)

=== FAIL: . TestComponentLifecycle/lifecycle (re-run 1) (0.01s)
    generated_component_test.go:46: 
        	Error Trace:	D:/a/opentelemetry-collector-contrib/opentelemetry-collector-contrib/extension/httpforwarderextension/generated_component_test.go:46
        	Error:      	Received unexpected error:
        	            	failed to bind to address localhost:7070: listen tcp 127.0.0.1:7070: bind: Only one usage of each socket address (protocol/network address/port) is normally permitted.
        	Test:       	TestComponentLifecycle/lifecycle

=== FAIL: . TestComponentLifecycle (re-run 1) (0.01s)
```

### PR DESCRIPTION
**Pull request by pjanotti**
#### Description
Ensures that the `Shutdown` waits for the server to release the listen port and finish the corresponding go routine.

Although a bug on the component it doesn't seem to deserve a changelog since it was detected via tests and there is no issue around the shutdown of the component.

#### Link to tracking issue
Fixes #37716

#### Testing
Repro the issue locally and validated no repro with the changes.
#### Documentation
N/A

### CODE REVIEW

**Review by atoulme — APPROVED** [review]

**Review by dashpole — APPROVED** [review]

File: extension/httpforwarderextension/extension.go [hunk 1]
```diff
@@ -60,7 +64,9 @@ func (h *httpForwarder) Shutdown(_ context.Context) error {
 	if h.server == nil {
 		return nil
 	}
-	return h.server.Close()
+	err := h.server.Close()
+	h.shutdownWG.Wait()
+	return err
```
Comment (bogdandrutu) [inline extension/httpforwarderextension/extension.go:69]: Why not using [Shutdown](https://cs.opensource.google/go/go/+/go1.23.6:src/net/http/server.go;l=3049) [¶](https://pkg.go.dev/net/http#Server.Shutdown)?

Comment (pjanotti) [reply extension/httpforwarderextension/extension.go:69]: The use of `Shutdown` vs `Close` is orthogonal to the issue being fixed in this PR: deterministic release of the port used by the component. In both cases there is still the need to wait the call to `Serve(listener)` to return.

I tend to prefer `Close` since, in certain cases `Shutdown` can take much longer since it needs to wait existing connections to finish gracefully. That said the component owners will have more context if they want to change the current behavior in that regard.

Comment (bogdandrutu) [reply extension/httpforwarderextension/extension.go:69]: I may miss something:

> // Shutdown gracefully shuts down the server without interrupting any
// active connections. Shutdown works by first closing all open
// listeners, then closing all idle connections, and then waiting
// indefinitely for connections to return to idle and then shut down.

File: extension/httpforwarderextension/extension.go [hunk 2]
```diff
@@ -47,7 +49,9 @@ func (h *httpForwarder) Start(ctx context.Context, host component.Host) error {
 		return fmt.Errorf("failed to create HTTP Client: %w", err)
 	}
 
+	h.shutdownWG.Add(1)
 	go func() {
+		defer h.shutdownWG.Done()
```
Comment (dmitryax) [inline extension/httpforwarderextension/extension.go:54]: Nit: I don't think we need a WG here, it can be a channel instead if we need this synronization

File: extension/httpforwarderextension/extension.go (hunk 1 above)
Comment (pjanotti) [reply extension/httpforwarderextension/extension.go:69]: Take into account the possible interleaves of the calls to `Serve` and `Shutdown`/`Close`. The ownership of `listener` is transferred to the `http.Server` when the call to `Serve(listener)` happens. However, since that happens in a goroutine it is possible that `Shutdown` is called before the `http.Server` took the ownership of listener. In this case the listener is not closed until the call to `Serve` happens. `Serve` adds a deferred call to `listener.Close`, even if `Shutdown` was already called, which ensures that the port is released by the time the method returns. 

While this may be rather improbable in practice, it is better for the component to behave deterministically with the shutdown ensuring no left over goroutine and/or port.

File: extension/httpforwarderextension/extension.go [hunk 3]
```diff
@@ -23,6 +24,7 @@ type httpForwarder struct {
 	server     *http.Server
 	settings   component.TelemetrySettings
 	config     *Config
+	shutdownWG sync.WaitGroup
```
[the remark this answers is not in the document]
Comment (pjanotti) [reply extension/httpforwarderextension/extension.go:27]: It needs to be available on the `Shutdown` method.

File: extension/httpforwarderextension/extension.go (hunk 2 above)
Comment (pjanotti) [reply extension/httpforwarderextension/extension.go:54]: Sure, I'm just curious if there is a specific reason for that: is it cheaper or faster? I tend to use WG if there is no need to flow data between concurrent code. That said, I've seen plenty of code using channels for this kind of sync. At first the disadvantage that I see for a channel is that it requires a call to `make(chan struct{})` but I don't know if the compiler optimizes that or not.

File: extension/httpforwarderextension/extension.go (hunk 3 above)
[the remark this answers is not in the document]
Comment (dmitryax) [reply extension/httpforwarderextension/extension.go:27]: Oh, right. I misread it.

File: extension/httpforwarderextension/extension.go (hunk 2 above)
Comment (dmitryax) [reply extension/httpforwarderextension/extension.go:54]: Sure, let's keep it. Doesn't matter that much. I wrote after misreading where the Wait is called.

**Review by dmitryax — APPROVED** [review]
LGTM as a solution tofor the flaky test. The Close vs Shutdown discussion can be solved in a separate PR if needed
