### PR TITLE
[processor/deltatorate] Add int counter support

### LINKED ISSUE #6981: `deltatorateprocessor` ignore int64 counter.
**Describe the bug**
The `detatorateprocessor` does not support int value type. always produce 0.
https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/processor/deltatorateprocessor/processor.go#L77

**Steps to reproduce**
Client report a int64 counter. 

**What did you expect to see?**

**What did you see instead?**

**What version did you use?**
Version: 
0.41.0
**What config did you use?**
Config:

**Environment**
OS: centos
Compiler: go 1.17
**Additional context**

### PR DESCRIPTION
**Pull request by hanjm**
Signed-off-by: Jimmie Han <hanjinming@outlook.com>

**Description:** <Describe what has changed.>

**Link to tracking Issue:** <Issue number if applicable>
Resolves #6981
**Testing:** <Describe what testing was performed and which tests were added.>
Unit test.
**Documentation:** <Describe the documentation added.>

### CODE REVIEW

**Comment by hanjm** [comment]
Count it skip changelog checker?

**Comment by jpkrohling** [comment]
@hanjm I believe this does deserve a changelog entry.

**Comment by jpkrohling** [comment]
@hossain-rayhan, would you like to review this as the original author of this component?

File: processor/deltatorateprocessor/processor.go [hunk 1]
```diff
@@ -74,8 +74,14 @@ func (dtrp *deltaToRateProcessor) processMetrics(_ context.Context, md pdata.Met
...
 					durationNanos := time.Duration(fromDataPoint.Timestamp() - fromDataPoint.StartTimestamp())
-					rate := calculateRate(fromDataPoint.DoubleVal(), durationNanos)
-					newDp.SetDoubleVal(rate)
+					switch fromDataPoint.Type() {
+					case pdata.MetricValueTypeDouble:
+						rate := calculateRate(fromDataPoint.DoubleVal(), durationNanos)
+						newDp.SetDoubleVal(rate)
+					case pdata.MetricValueTypeInt:
+						rate := calculateRate(float64(fromDataPoint.IntVal()), durationNanos)
+						newDp.SetDoubleVal(rate)
```
Comment (jpkrohling) [inline processor/deltatorateprocessor/processor.go:83]: Are those the only possible data point types? Would it make sense to have a default case, in case this constraint changes in the future? If you declare the rate outside of the switch, you can simplify this by having the `newDp.SetDoubleVal` being specified only once, after the switch.

**Comment by jpkrohling** [comment]
This is missing an entry in the changelog, but other than that, this looks good to me despite the minor comment I made. I'll wait a day or so for @hossain-rayhan to review this as well.

**Comment by hossain-rayhan** [comment]
Thanks @jpkrohling, I will take a look.

**Review by anuraaga — APPROVED** [review]

**Review by hossain-rayhan — APPROVED** [review]
LGTM. Thanks.

File: processor/deltatorateprocessor/processor.go (hunk 1 above)
Comment (hanjm) [reply processor/deltatorateprocessor/processor.go]: Simplify code done by latest commit. Thank you.

File: processor/deltatorateprocessor/processor.go [hunk 2]
```diff
@@ -74,7 +74,14 @@ func (dtrp *deltaToRateProcessor) processMetrics(_ context.Context, md pdata.Met
...
 
 					durationNanos := time.Duration(fromDataPoint.Timestamp() - fromDataPoint.StartTimestamp())
-					rate := calculateRate(fromDataPoint.DoubleVal(), durationNanos)
+					var rate float64
+					switch fromDataPoint.Type() {
+					case pdata.MetricValueTypeDouble:
+						rate = calculateRate(fromDataPoint.DoubleVal(), durationNanos)
+					case pdata.MetricValueTypeInt:
+						rate = calculateRate(float64(fromDataPoint.IntVal()), durationNanos)
+					default:
```
Comment (jpkrohling) [inline processor/deltatorateprocessor/processor.go:83]: The default case should return an error (unrecoverable, so that the retry mechanism won't kick in).

https://github.com/open-telemetry/opentelemetry-collector/blob/51fcb65f02055638f223c6abd3d6d2d644c696db/consumer/consumererror/permanent.go#L25-L29

Comment (hanjm) [reply processor/deltatorateprocessor/processor.go:84]: Got it

**Review by jpkrohling — APPROVED** [review]
