### PR TITLE
[pkg/ottl] Add support for inferring the OTTL context from conditions

### LINKED ISSUE #38755: [pkg/ottl] Context Inferer does not support conditions
### Component(s)

pkg/ottl

## Description

All of the logic for parsing conditions is correct, however, the inference is using parseStatements not parseConditions which is causing it to throw a bug

## Steps to Reproduce

try to call ParseConditions(conditions)
```
inferredContext, err := pc.contextInferrer.infer(conditionsValues)
```

is called which uses parse statements to grab the parsed statements.

### Collector version

v0.122.0

### Environment information

in code.

### OpenTelemetry Collector configuration

```yaml

```

### Log output

```shell

```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by jaronoff97**
#### Description
Modifies the recently introduced ParseConditions logic to support inference of conditions

#### Link to tracking issue
Fixes #38755 

#### Testing
Unit tests

#### Documentation
n/a

### CODE REVIEW

File: pkg/ottl/parser_collection_test.go [hunk 1]
```diff
@@ -311,18 +303,17 @@ func Test_ParseStatements_ContextInferenceError(t *testing.T) {
...
 	)
 	require.NoError(t, err)
-	pc.contextInferrer = &mockStaticContextInferrer{"foo"}
 
 	statements := mockGetter{values: []string{`set(foo.attributes["bar"], "foo")`}}
 	_, err = pc.ParseStatements(statements)
 
-	assert.ErrorContains(t, err, `context "foo" inferred from the statements`)
-	assert.ErrorContains(t, err, "is not a supported context")
+	assert.ErrorContains(t, err, `path's first segment must be a valid context name: ["bar" "te"]`)
```
Comment (edmocosta) [inline pkg/ottl/parser_collection_test.go:315]: These changes doesn't seems correct, the previous errors were related to an unknown context being inferred, these ones are raised when no context is inferred.

We can probably keep the mock here, given this test is verifying a parser collection behavior.

File: pkg/ottl/parser_collection_test.go [hunk 2]
```diff
@@ -491,18 +476,17 @@ func Test_ParseConditions_MultipleContexts_Success(t *testing.T) {
...
-	pc, err := NewParserCollection[any](component.TelemetrySettings{})
+	pc, err := NewParserCollection[any](componenttest.NewNopTelemetrySettings())
 	require.NoError(t, err)
-	pc.contextInferrer = &mockStaticContextInferrer{""}
 
 	conditions := mockGetter{values: []string{`bar.attributes["bar"] == "foo"`}}
 	_, err = pc.ParseConditions(conditions)
 
-	assert.ErrorContains(t, err, "unable to infer context from conditions")
+	assert.ErrorContains(t, err, "is not a supported context")
```
Comment (edmocosta) [inline pkg/ottl/parser_collection_test.go:485]: Same as the above comment to keep the mock, they're different errors coming from different places.

File: .chloggen/jaronoff-38755-fix-inference-bug.yaml [hunk 3]
```diff
@@ -0,0 +1,27 @@
+# Use this changelog template to create an entry for release notes.
+
+# One of 'breaking', 'deprecation', 'new_component', 'enhancement', 'bug_fix'
+change_type: bug_fix
+
+# The name of the component, or a single word describing the area of concern, (e.g. filelogreceiver)
+component: pkg/ottl
+
+# A brief description of the change.  Surround your text with quotes ("") if it needs to start with a backtick (`).
+note: Fixes a bug that was preventing ParseConditions from working because it was trying to infer context from statements.
```
Comment (edmocosta) [inline .chloggen/jaronoff-38755-fix-inference-bug.yaml:10]:
```suggestion
note: Fix the `ottl.ParserCollection` to properly infer the OTTL context when using the `ParseConditions` function.
```

File: .chloggen/jaronoff-38755-fix-inference-bug.yaml [hunk 4]
```diff
@@ -0,0 +1,27 @@
...
+subtext:
+
+# If your change doesn't affect end users or the exported elements of any package,
+# you should instead start your pull request title with [chore] or use the "Skip Changelog" label.
+# Optional: The change log or logs in which this entry should be included.
+# e.g. '[user]' or '[user, api]'
+# Include 'user' if the change is relevant to end users.
+# Include 'api' if there is a change to a library API.
+# Default: '[user]'
+change_logs: []
```
Comment (edmocosta) [inline .chloggen/jaronoff-38755-fix-inference-bug.yaml:27]:
```suggestion
change_logs: [api]
```

**Review by edmocosta — COMMENTED** [review]
Thanks for fixing it. I've left a few suggestions for your consideration.

File: pkg/ottl/context_inferrer.go [hunk 5]
```diff
@@ -81,7 +82,63 @@ func withContextInferrerPriorities(priorities []string) priorityContextInferrerO
...
+	requiredEnums := map[enumSymbol]struct{}{}
+
+	var inferredContextPriority int
+	for _, condition := range conditions {
+		parsed, err := parseCondition(condition)
+		if err != nil {
+			return "", err
+		}
+
+		conditionPaths, conditionFunctions, conditionEnums := s.getParsedConditionHints(parsed)
```
[the remark this answers is not in the document]
Comment (jaronoff97) [reply pkg/ottl/context_inferrer.go:110]: yeah i was going back and forth too. I originally implemented it like that, but the types are wonky... I'll go for it and lmk what you think!

File: pkg/ottl/context_inferrer.go [hunk 6]
```diff
@@ -81,11 +83,38 @@ func withContextInferrerPriorities(priorities []string) priorityContextInferrerO
 	}
 }
 
-func (s *priorityContextInferrer) infer(statements []string) (inferredContext string, err error) {
-	s.telemetrySettings.Logger.Debug("Inferring context from statements",
+func (s *priorityContextInferrer) inferFromConditions(conditions []string) (inferredContext string, err error) {
+	return s.innerInfer(conditions, func(condition string) ([]path, map[string]struct{}, map[enumSymbol]struct{}, error) {
```
Comment (edmocosta) [inline pkg/ottl/context_inferrer.go:87]: I think we could clean this up a bit more by moving the parsing logic into the `getParsedConditionHints` (renaming it to `getConditionHints`), so it would match the function signature, and could be used here as `return s.innerInfer(statements, s.getStatementHints)`.

File: pkg/ottl/context_inferrer.go [hunk 7]
```diff
@@ -81,11 +83,38 @@ func withContextInferrerPriorities(priorities []string) priorityContextInferrerO
...
+
+		statementPaths, statementFunctions, statementEnums := s.getParsedStatementHints(parsed)
+		return statementPaths, statementFunctions, statementEnums, nil
+	})
+}
+
+// hinterFunc is used by the innerInfer function to generate the hints (paths, functions, enums, etc.) for the given OTTL.
+type hinterFunc func(string) ([]path, map[string]struct{}, map[enumSymbol]struct{}, error)
+
+func (s *priorityContextInferrer) innerInfer(ottls []string, hinter hinterFunc) (inferredContext string, err error) {
```
Comment (edmocosta) [inline pkg/ottl/context_inferrer.go:113]: nit: given it's not an exported function, I would keep the original name `infer`.

**Review by TylerHelmuth — APPROVED** [review]
