### PR TITLE
[exporter/elasticsearch] Use 64 bit hash to reduce metric grouping hash and _metric_names_hash collision

### LINKED ISSUE #41208: [exporter/elasticsearchexporter/integrationtest]: Report for failed tests on main
Auto-generated report for `__run_3` job build.

Link to failed build: https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/16170619540

#### Test Failures
-  `TestExporter/metrics/batcher_enabled_es_intermittent_http_error`
-  `TestExporter`

**Note**: Information about any subsequent build failures that happen while
this issue is open, will be added as comments with more information to this issue.

### PR DESCRIPTION
**Pull request by carsonip**
#### Description

Replace 32 bit hash with 64 bit xxhash to reduce metric grouping hash collisions and `_metric_names_hash` collisions. The former has a higher risk of data loss.

#### Link to tracking issue
Fixes #41208

### CODE REVIEW

File: exporter/elasticsearchexporter/internal/metricgroup/hasher.go [hunk 1]
```diff
@@ -73,40 +73,40 @@ func (h *ECSDataPointHasher) HashKey() HashKey {
...
-	h.scopeHash = hasher.Sum32()
+	h.scopeHash = hasher.Sum64()
 }
 
 func (h *OTelDataPointHasher) UpdateDataPoint(dp datapoints.DataPoint) {
-	hasher := fnv.New32a()
+	hasher := xxhash.New()
 
 	timestampBuf := make([]byte, 8)
 	binary.LittleEndian.PutUint64(timestampBuf, uint64(dp.Timestamp()))
```
Comment (carsonip) [inline exporter/elasticsearchexporter/internal/metricgroup/hasher.go:112]: [to reviewer] it is actually possible to make timestamp and starttimestamp a field in the HashKey struct to reduce a dimension of possible hash collision.

**Review by carsonip — COMMENTED** [review]
[to reviewer] This leaves us with _metric_names_hash using fnv.New32a. Do we feel comfortable changing it to xxhash as well?

**Review by axw — APPROVED** [review]
metric per doc cannot come soon enough :face_holding_back_tears:

**Review by songy23 — APPROVED** [review]
