### PR TITLE
[receiver/docker_stats] Fix context cancelled bug

### LINKED ISSUE #34194: [docker_stats] - Could not parse docker containerStats for container id
### Component(s)

receiver/dockerstats

## Description

When running the OTel Demo we started getting the following errors (also reported here https://github.com/open-telemetry/opentelemetry-demo/issues/1677):

```
2024-07-22T12:11:15.647Z	error	docker@v0.104.0/docker.go:194	Could not parse docker containerStats for container id	{"kind": "receiver", "name": "docker_stats", "data_type": "metrics", "id": "fcd69fe4a34e8b15153005bc42fda1e7e41c6f743cec83b8171a06a432561452", "error": "context canceled"}
github.com/open-telemetry/opentelemetry-collector-contrib/internal/docker.(*Client).toStatsJSON
	github.com/open-telemetry/opentelemetry-collector-contrib/internal/docker@v0.104.0/docker.go:194
github.com/open-telemetry/opentelemetry-collector-contrib/internal/docker.(*Client).FetchContainerStatsAsJSON
	github.com/open-telemetry/opentelemetry-collector-contrib/internal/docker@v0.104.0/docker.go:144
github.com/open-telemetry/opentelemetry-collector-contrib/receiver/dockerstatsreceiver.(*metricsReceiver).scrapeV2.func1
	github.com/open-telemetry/opentelemetry-collector-contrib/receiver/dockerstatsreceiver@v0.104.0/receiver.go:92
2024-07-22T12:11:15.663Z	error	scraperhelper/scrapercontroller.go:197	Error scraping metrics	{"kind": "receiver", "name": "docker_stats", "data_type": "metrics", "error": "context canceled", "scraper": "docker_stats"}
go.opentelemetry.io/collector/receiver/scraperhelper.(*controller).scrapeMetricsAndReport
	go.opentelemetry.io/collector/receiver@v0.104.0/scraperhelper/scrapercontroller.go:197
go.opentelemetry.io/collector/receiver/scraperhelper.(*controller).startScraping.func1
	go.opentelemetry.io/collector/receiver@v0.104.0/scraperhelper/scrapercontroller.go:169
```

## Steps to Reproduce

```
git clone git@github.com:open-telemetry/opentelemetry-demo.git

cd opentelemetry-demo/

docker compose up -d
```

## Expected Result

No errors on the OTel collector logs.

## Actual Result

Errors mentioned above in the Collector logs.

### Collector version

Tested with `0.102.1`, `0.104.0` and `0.105.0`

## Environment
System Version: macOS 14.5 (23F79)
Kernel Version: Darwin 23.5.0

```
❯ docker info
Client:
 Version:    24.0.7
 Context:    desktop-linux
Server:
 Runtimes: runc io.containerd.runc.v2
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: d8f198a4ed8892c764191ef7b3b06d8a2eeb5c7f
 runc version: v1.1.10-0-g18a0cb0
 init version: de40ad0
 Security Options:
  seccomp
   Profile: unconfined
  cgroupns
 Kernel Version: 6.5.11-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: aarch64
```

### OpenTelemetry Collector configuration

_No response_

### Log output

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by henrikno**
#### Description
Sometimes collecting docker stats would fail with `"error": "context canceled"`

It's because it was cancelling the context concurrently with reading the response. If reading the response takes a little bit of time it would cancel instead of reading the response.

Move context and cancellation outside to the calling function so that it can do parsing before cancelling the timeout.

#### Link to tracking issue
Fixes #34194
https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/34320
https://github.com/open-telemetry/opentelemetry-demo/issues/1677

#### Testing
Added a reproduction integration test that simulates a slightly slow response.

### CODE REVIEW

File: internal/docker/docker_test.go [hunk 1]
```diff
@@ -173,6 +173,27 @@ func TestToStatsJSONErrorHandling(t *testing.T) {
 	require.Error(t, err)
 }
 
+func TestFetchContainerStatsAsJSONWithSlowResponse(t *testing.T) {
+	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
+		if strings.Contains(r.URL.Path, "/stats") {
+			w.Header().Set("Content-Type", "application/json")
+			w.(http.Flusher).Flush()
```
Comment (MovieStoreGuy) [inline internal/docker/docker_test.go:181]: It shouldn't be required to cast the response writer type, or assume that it will be of Flusher.

**Review by MovieStoreGuy — COMMENTED** [review]
Thank you for submitting the change,  

I am not sure that this change will actually fix the issue you're seeing. If the Docker daemon is under significant pressure, it will be delayed in responding, and will block the scrape request meaning that data from the host will be late. 

In this scenario, I believe the best case is to fail fast and fail the request so we can move to the next time window.

**Comment by henrikno** [comment]
Current behaviour that I'm seeing is that I downloaded otelcol, enabled `docker_stats` and get this error very frequently:

```
2026-01-27T21:09:30.489Z	error	docker@v0.141.0/docker.go:196	Could not parse docker containerStats for container id	{"resource": {"service.instance.id": "bedf9234-92c5-4dac-8988-66660892bf7e", "service.name": "./elastic-agent", "service.version": "9.2.4"}, "otelcol.component.id": "docker_stats", "otelcol.component.kind": "receiver", "otelcol.signal": "metrics", "id": "e6af820f51811ab3cd81ca6f71935f0c7faac82d045b06ccddbe6f19c83be4e3", "error": "context canceled"}
github.com/open-telemetry/opentelemetry-collector-contrib/internal/docker.(*Client).toStatsJSON
	github.com/open-telemetry/opentelemetry-collector-contrib/internal/docker@v0.141.0/docker.go:196
github.com/open-telemetry/opentelemetry-collector-contrib/internal/docker.(*Client).FetchContainerStatsAsJSON
	github.com/open-telemetry/opentelemetry-collector-contrib/internal/docker@v0.141.0/docker.go:146
github.com/open-telemetry/opentelemetry-collector-contrib/receiver/dockerstatsreceiver.(*metricsReceiver).scrapeV2.func1
	github.com/open-telemetry/opentelemetry-collector-contrib/receiver/dockerstatsreceiver@v0.141.0/receiver.go:97
```

The host isn't that busy, around 50% CPU, spikes up a little bit, but it runs ~40 containers. So it's missing metrics for a lot of containers.
I tried curling the stats endpoint and the response times seems bimodal. Sometimes it returns in 12 milliseconds, sometimes 900ms. I was briefly looking at the docker code and it seem like there's actually a background process that collects the stats, and it's refreshing every [1 second](https://github.com/moby/moby/blob/master/daemon/daemon.go#L1069), so I think the time taken depends on how long it needs to wait for that to be published. I've never seen it above 1s though.

I'm testing running it with my patch now and the errors went away.
Docker API being slower than the collection interval is a valid concern, but should be handled by the timeout (did a quick test for it, I can add it if we want)

**Comment by ChrsMark** [comment]
@jamesmoessis please take a look too as code-owner.

File: internal/docker/docker.go [hunk 2]
```diff
@@ -138,7 +138,10 @@ func (dc *Client) FetchContainerStatsAsJSON(
 	ctx context.Context,
 	container Container,
 ) (*ctypes.StatsResponse, error) {
-	containerStats, err := dc.FetchContainerStats(ctx, container)
+	statsCtx, cancel := context.WithTimeout(ctx, dc.config.Timeout)
+	defer cancel()
+
+	containerStats, err := dc.FetchContainerStats(statsCtx, container)
```
Comment (jamesmoessis) [inline internal/docker/docker.go:149]: Instead of changing the behaviour, did you consider increasing timeout in the config? Since you are the first person to raise this, it might be something specific about your environment, potentially. Maybe raising the timeout in config would be the best solution.

File: internal/docker/docker_test.go [hunk 3]
```diff
@@ -173,6 +173,27 @@ func TestToStatsJSONErrorHandling(t *testing.T) {
 	require.Error(t, err)
 }
 
+func TestFetchContainerStatsAsJSONWithSlowResponse(t *testing.T) {
+	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
+		if strings.Contains(r.URL.Path, "/stats") {
```
Comment (jamesmoessis) [inline internal/docker/docker_test.go:179]: So the server writes a header, sleeps for 10 seconds (much longer than the client's 5s timeout) and then writes. 

I'm unsure this is desired behaviour for a client timeout. The timeout is for the whole request, not just for getting a connection. Perhaps we need connection timeout (short) and request timeout (longer)

**Review by jamesmoessis — COMMENTED** [review]
Thank you for the contribution - couple of questions here around how the behaviour of a timeout should work

File: internal/docker/docker.go (hunk 2 above)
Comment (henrikno) [reply internal/docker/docker.go:149]: Increasing timeout won't have any effect, it never reaches it. It's cancelling while simultaneously parsing the response, so whoever's faster wins. It's a race condition. I guess it depends on context switching and how much of the response gets buffered in memory. 

Many people have reported it:
https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/34194
https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/34320
https://github.com/open-telemetry/opentelemetry-demo/issues/1677

File: internal/docker/docker_test.go (hunk 3 above)
Comment (henrikno) [reply internal/docker/docker_test.go:179]: The test just sleeps for 10 milliseconds. If I remove the sleep without the fix it fails 50% of the time. I haven't gotten it to succeed with any amount of sleep, even 1ms, I think because it forces a context switch so it triggers the cancellation.

File: internal/docker/docker_test.go (hunk 1 above)
Comment (henrikno) [reply internal/docker/docker_test.go:181]: Looks like the cast was necessary.
`./docker_test.go:180:6: w.Flush undefined (type http.ResponseWriter has no field or method Flush)`

**Comment by henrikno** [comment]
Please review. This is blocking our adoption on hosts running docker.

**Comment by henrikno** [comment]
Reproduces on 0.146.1 macOS (and Ubuntu).


```
docker version
Client:
 Version:           29.2.1
 API version:       1.53
 Go version:        go1.25.6
 Git commit:        a5c7197
 Built:             Mon Feb  2 17:16:37 2026
 OS/Arch:           darwin/arm64
 Context:           desktop-linux

Server: Docker Desktop 4.62.0 (219486)
 Engine:
  Version:          29.2.1
  API version:      1.53 (minimum version 1.44)
  Go version:       go1.25.6
  Git commit:       6bc6209
  Built:            Mon Feb  2 17:16:47 2026
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          v2.2.1
  GitCommit:        dea7da592f5d1d2b7755e3a161be07f43fad8f75
 runc:
  Version:          1.3.4
  GitCommit:        v1.3.4-0-gd6d73eb8
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

cat otel.yml
```yaml
receivers:
  docker_stats:
    api_version: "1.53"
    metrics:
      container.cpu.usage.percpu:
        enabled: true

exporters:
  debug:

service:
  pipelines:
    metrics:
      receivers: [docker_stats]
      exporters:
        - debug
```


`./otelcol-contrib --config otel.yml`

I get errors around 5-17 docker containers (test with different numbers):
`for i in $(seq 1 50); do docker run -d --name "dummy-$i" alpine sleep infinity; done`

Logs:
```
2026-02-26T00:02:09.892-0800	info	service@v0.146.1/service.go:241	Starting otelcol-contrib...	{"resource": {"service.instance.id": "46240e7a-61dc-45e8-af71-22da3052213d", "service.name": "otelcol-contrib", "service.version": "0.146.1"}, "Version": "0.146.1", "NumCPU": 12}
2026-02-26T00:02:09.892-0800	info	extensions/extensions.go:40	Starting extensions...	{"resource": {"service.instance.id": "46240e7a-61dc-45e8-af71-22da3052213d", "service.name": "otelcol-contrib", "service.version": "0.146.1"}}
2026-02-26T00:02:10.026-0800	info	service@v0.146.1/service.go:264	Everything is ready. Begin running and processing data.	{"resource": {"service.instance.id": "46240e7a-61dc-45e8-af71-22da3052213d", "service.name": "otelcol-contrib", "service.version": "0.146.1"}}
2026-02-26T00:02:12.737-0800	error	docker@v0.146.0/docker.go:196	Could not parse docker containerStats for container id	{"resource": {"service.instance.id": "46240e7a-61dc-45e8-af71-22da3052213d", "service.name": "otelcol-contrib", "service.version": "0.146.1"}, "otelcol.component.id": "docker_stats", "otelcol.component.kind": "receiver", "otelcol.signal": "metrics", "id": "00f0a27673d93463225889292035c26ad8070eb5913b5094ae6d0cd6a5153b9a", "error": "context canceled"}
github.com/open-telemetry/opentelemetry-collector-contrib/internal/docker.(*Client).toStatsJSON
	github.com/open-telemetry/opentelemetry-collector-contrib/internal/docker@v0.146.0/docker.go:196
github.com/open-telemetry/opentelemetry-collector-contrib/internal/docker.(*Client).FetchContainerStatsAsJSON
	github.com/open-telemetry/opentelemetry-collector-contrib/internal/docker@v0.146.0/docker.go:146
github.com/open-telemetry/opentelemetry-collector-contrib/receiver/dockerstatsreceiver.(*metricsReceiver).scrapeV2.func1
	github.com/open-telemetry/opentelemetry-collector-contrib/receiver/dockerstatsreceiver@v0.146.0/receiver.go:97
2026-02-26T00:02:12.747-0800	error	docker@v0.146.0/docker.go:196	Could not parse docker containerStats for container id	{"resource": {"service.instance.id": "46240e7a-61dc-45e8-af71-22da3052213d", "service.name": "otelcol-contrib", "service.version": "0.146.1"}, "otelcol.component.id": "docker_stats", "otelcol.component.kind": "receiver", "otelcol.signal": "metrics", "id": "0b03061e44e84aca2e014a029d4dfbed2ac5bf2e465ebcb9b01e8f3f3b94e931", "error": "context canceled"}
github.com/open-telemetry/opentelemetry-collector-contrib/internal/docker.(*Client).toStatsJSON
	github.com/open-telemetry/opentelemetry-collector-contrib/internal/docker@v0.146.0/docker.go:196
github.com/open-telemetry/opentelemetry-collector-contrib/internal/docker.(*Client).FetchContainerStatsAsJSON
	github.com/open-telemetry/opentelemetry-collector-contrib/internal/docker@v0.146.0/docker.go:146
github.com/open-telemetry/opentelemetry-collector-contrib/receiver/dockerstatsreceiver.(*metricsReceiver).scrapeV2.func1
	github.com/open-telemetry/opentelemetry-collector-contrib/receiver/dockerstatsreceiver@v0.146.0/receiver.go:97
2026-02-26T00:02:12.788-0800	error	docker@v0.146.0/docker.go:196	Could not parse docker containerStats for container id	{"resource": {"service.instance.id": "46240e7a-61dc-45e8-af71-22da3052213d", "service.name": "otelcol-contrib", "service.version": "0.146.1"}, "otelcol.component.id": "docker_stats", "otelcol.component.kind": "receiver", "otelcol.signal": "metrics", "id": "f7ab0e20e6a68e6d4c7616c3fe43b2d71228f9f10b1075a2dfb1c64f3c9c1d64", "error": "context canceled"}
github.com/open-telemetry/opentelemetry-collector-contrib/internal/docker.(*Client).toStatsJSON
	github.com/open-telemetry/opentelemetry-collector-contrib/internal/docker@v0.146.0/docker.go:196
github.com/open-telemetry/opentelemetry-collector-contrib/internal/docker.(*Client).FetchContainerStatsAsJSON
	github.com/open-telemetry/opentelemetry-collector-contrib/internal/docker@v0.146.0/docker.go:146
github.com/open-telemetry/opentelemetry-collector-contrib/receiver/dockerstatsreceiver.(*metricsReceiver).scrapeV2.func1
	github.com/open-telemetry/opentelemetry-collector-contrib/receiver/dockerstatsreceiver@v0.146.0/receiver.go:97
2026-02-26T00:02:12.792-0800	error	scraperhelper@v0.146.1/obs_metrics.go:61	Error scraping metrics	{"resource": {"service.instance.id": "46240e7a-61dc-45e8-af71-22da3052213d", "service.name": "otelcol-contrib", "service.version": "0.146.1"}, "otelcol.component.id": "docker_stats", "otelcol.component.kind": "receiver", "otelcol.signal": "metrics", "scraper": "docker_stats", "error": "context canceled; context canceled; context canceled", "errorCauses": [{"error": "context canceled"}, {"error": "context canceled"}, {"error": "context canceled"}]}
go.opentelemetry.io/collector/scraper/scraperhelper.wrapObsMetrics.func1
	go.opentelemetry.io/collector/scraper/scraperhelper@v0.146.1/obs_metrics.go:61
go.opentelemetry.io/collector/scraper.ScrapeMetricsFunc.ScrapeMetrics
	go.opentelemetry.io/collector/scraper@v0.146.1/metrics.go:24
go.opentelemetry.io/collector/scraper/scraperhelper.scrapeMetrics
	go.opentelemetry.io/collector/scraper/scraperhelper@v0.146.1/controller.go:167
go.opentelemetry.io/collector/scraper/scraperhelper.NewMetricsController.func1
	go.opentelemetry.io/collector/scraper/scraperhelper@v0.146.1/controller.go:139
go.opentelemetry.io/collector/scraper/scraperhelper/internal/controller.(*Controller[...]).startScraping.func1
	go.opentelemetry.io/collector/scraper/scraperhelper@v0.146.1/internal/controller/controller.go:113
sync.(*WaitGroup).Go.func1
	sync/waitgroup.go:258
```

**Review by jamesmoessis — APPROVED** [review]
Apologies for the delay on my review. LGTM

**Review by ChrsMark — APPROVED** [review]
LGTM
