### PR TITLE
Fix flaky tests on TestReceiveResourceSpansV2 in datadogconnector

### LINKED ISSUE #37515: [flaky test][connector/datadog] TestReceiveResourceSpansV2/ReceiveResourceSpansV1
### Component(s)

connector/datadog

### Describe the issue you're reporting

https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/12996844617/job/36246540969#step:8:403

```terminal
=== FAIL: . TestReceiveResourceSpansV2/ReceiveResourceSpansV1 (2.12s)
    connector_test.go:252: 
        	Error Trace:	D:/a/opentelemetry-collector-contrib/opentelemetry-collector-contrib/connector/datadogconnector/connector_test.go:252
        	            				D:/a/opentelemetry-collector-contrib/opentelemetry-collector-contrib/connector/datadogconnector/connector_test.go:197
        	Error:      	Not equal: 
        	            	expected: "do-not-use"
        	            	actual  : "none"
        	            	
        	            	Diff:
        	            	--- Expected
        	            	+++ Actual
        	            	@@ -1 +1 @@
        	            	-do-not-use
        	            	+none
        	Test:       	TestReceiveResourceSpansV2/ReceiveResourceSpansV1

=== FAIL: . TestReceiveResourceSpansV2 (4.19s)

DONE 2 runs, 39 tests, 2 failures in 330.701s
```

### PR DESCRIPTION
**Pull request by IbraheemA**
#### Description

Address flaky test `TestReceiveResourceSpansV2/ReceiveResourceSpansV1` in datadogconnector. Previously, test results would depend on test execution order, since the feature flag setting would persist between tests.

#### Link to tracking issue
Fixes #37515

### CODE REVIEW

File: connector/datadogconnector/connector_test.go [hunk 1]
```diff
@@ -202,10 +202,8 @@ func TestReceiveResourceSpansV2(t *testing.T) {
 }
 
 func testReceiveResourceSpansV2(t *testing.T, enableReceiveResourceSpansV2 bool) {
-	if enableReceiveResourceSpansV2 {
-		if err := featuregate.GlobalRegistry().Set("datadog.EnableReceiveResourceSpansV2", true); err != nil {
-			t.Fatal(err)
-		}
+	if err := featuregate.GlobalRegistry().Set("datadog.EnableReceiveResourceSpansV2", enableReceiveResourceSpansV2); err != nil {
```
Comment (songy23) [inline connector/datadogconnector/connector_test.go:205]: You may want to store the current value of the FF and e.g. 
```
prevVal := featuregate.GlobalRegistry().Set("datadog.EnableReceiveResourceSpansV2")
require.NoError(t, featuregate.GlobalRegistry().Set("datadog.EnableReceiveResourceSpansV2", enableReceiveResourceSpansV2))
defer func() {
  featuregate.GlobalRegistry().Set("datadog.EnableReceiveResourceSpansV2", prevVal)
}()
```

same for others

Comment (jackgopack4) [reply connector/datadogconnector/connector_test.go:205]: I like this approach

**Review by songy23 — APPROVED** [review]
LGTM

**Comment by songy23** [comment]
> Generated code is out of date, please run "make generate" and commit the changes in this PR.

also need to fix linter
