### PR TITLE
Fix panic caused by race condition when accessing span attributes

### LINKED ISSUE #12644: [spanmetricsprocessor] panic when using spanmetric with v0.56
**Describe the bug**
using v0.56 and spanmetricsprocessor causes panic and otel collector contrib crash with using spanmetric processor and of course becames totally unusable and unresponsive

**Steps to reproduce**
dunno, probably just using spanmetric ?
for me it usually happens in a bunch of minutes after starting the server

**What did you expect to see?**
no crash, no panic, no errors

**What did you see instead?**
```
panic: runtime error: index out of range [0] with length 0

goroutine 5236 [running]:
go.opentelemetry.io/collector/pdata/internal.Map.Get(...)
        go.opentelemetry.io/collector/pdata@v0.56.0/internal/common.go:636
github.com/open-telemetry/opentelemetry-collector-contrib/processor/spanmetricsprocessor.getDimensionValue({{0x40001570e4?, 0x40022e562c?}, 0x0?}, {0x1?}, {0x4002af2d98?})
        github.com/open-telemetry/opentelemetry-collector-contrib/processor/spanmetricsprocessor@v0.56.0/processor.go:493 +0x1c4
github.com/open-telemetry/opentelemetry-collector-contrib/processor/spanmetricsprocessor.buildKey({0x40016f29f0?, 0x4001697500?}, {0x40024e0ae0?}, {0x4000a882c0, 0x7, 0x52?}, {0x3f?})
        github.com/open-telemetry/opentelemetry-collector-contrib/processor/spanmetricsprocessor@v0.56.0/processor.go:475 +0x130
github.com/open-telemetry/opentelemetry-collector-contrib/processor/spanmetricsprocessor.(*processorImp).aggregateMetricsForSpan(0x40005712c0, {0x40016f29f0, 0x11}, {0x4?}, {0x4000be6ed8?})
        github.com/open-telemetry/opentelemetry-collector-contrib/processor/spanmetricsprocessor@v0.56.0/processor.go:386 +0xa4
github.com/open-telemetry/opentelemetry-collector-contrib/processor/spanmetricsprocessor.(*processorImp).aggregateMetricsForServiceSpans(0x45e4a40?, {0x468bc60?}, {0x40016f29f0, 0x11})
        github.com/open-telemetry/opentelemetry-collector-contrib/processor/spanmetricsprocessor@v0.56.0/processor.go:375 +0x94
github.com/open-telemetry/opentelemetry-collector-contrib/processor/spanmetricsprocessor.(*processorImp).aggregateMetrics(0x40017d0f60?, {0x5b170e8?})
        github.com/open-telemetry/opentelemetry-collector-contrib/processor/spanmetricsprocessor@v0.56.0/processor.go:364 +0xdc
github.com/open-telemetry/opentelemetry-collector-contrib/processor/spanmetricsprocessor.(*processorImp).ConsumeTraces.func1()
        github.com/open-telemetry/opentelemetry-collector-contrib/processor/spanmetricsprocessor@v0.56.0/processor.go:239 +0xd0
created by github.com/open-telemetry/opentelemetry-collector-contrib/processor/spanmetricsprocessor.(*processorImp).ConsumeTraces
        github.com/open-telemetry/opentelemetry-collector-contrib/processor/spanmetricsprocessor@v0.56.0/processor.go:231 +0xc0
```

**What version did you use?**
otel collector contrib docker image v0.56

**What config did you use?**
Config: (e.g. the yaml config file)

```
receivers:
    otlp:
        protocols:
            http:
                include_metadata: true
                cors:
                    allowed_origins: [
                        #OMITTED#
                    ]                    
    # Dummy receiver that's never used, because a pipeline is required to have one.
    otlp/spanmetrics:
        protocols:
            grpc:
                endpoint: "localhost:12345"

    prometheus:
      config:
        scrape_configs:
          - job_name: 'ratelimiter'
            scrape_interval: ${RECEIVERS_PROMETHEUS_CONFIG_SCRAPE_INTERVAL}
            static_configs:
              - targets: ['${HOSTNAME}:8889']

processors:
    attributes/traces:
        actions:
          - key: http.client_latitude
            from_context: CloudFront-Viewer-Latitude
            action: upsert
          - key: http.client_longitude
            from_context: CloudFront-Viewer-Longitude
            action: upsert
    memory_limiter:
        check_interval: 5s
        limit_mib: 448
        spike_limit_mib: 64
    batch:
        send_batch_size: 48
        send_batch_max_size: 48
        timeout: 15s
    transform:
        logs:
            queries:
                - set(attributes["severity_text"], severity_text)
    filter:
        logs:
            exclude:
                match_type: regexp
                record_attributes:
                    - key: severity_text
                      value: "(TRACE|DEBUG)"
    spanmetrics:
        metrics_exporter: prometheus
        dimensions:
            - name: enduser.id
            - name: deployment.environment
            - name: http.status_code
            - name: http.client_ip
            - name: http.client_latitude
            - name: http.client_longitude
            - name: http.method

exporters:
    logging:
        loglevel: ${EXPORTERS_LOGGING_LOGLEVEL}
    otlp:
        endpoint: tempo-eu-west-0.grafana.net:443
        headers:
            authorization: ${EXPORTERS_OTLP_HEADERS_AUTHORIZATION}
            
    prometheusremotewrite:
        endpoint: https://prometheus-prod-01-eu-west-0.grafana.net/api/prom/push
        headers:
            authorization: ${EXPORTERS_PROMETHEUSREMOTEWRITE_HEADERS_AUTHORIZATION}
            
    loki:
        endpoint: https://logs-prod-eu-west-0.grafana.net/loki/api/v1/push
        headers:
            authorization: ${EXPORTERS_LOKI_HEADERS_AUTHORIZATION}
        format: json
        labels:
            attributes:
                container_name: ""
                source: ""
            resource:
                host.name: "hostname"
                
    prometheus:
        endpoint: "${HOSTNAME}:8889"
        metric_expiration: ${EXPORTERS_PROMETHEUS_METRIC_EXPIRATION}

extensions:
    health_check:
service:
    telemetry:
        logs:
            level: ${SERVICE_TELEMETRY_LOGS_LEVEL}
    extensions: [health_check]
    pipelines:
        traces:
            receivers: [otlp]
            processors: [attributes/traces, spanmetrics, memory_limiter, batch]
            exporters: [otlp, logging]
        metrics/spanmetrics:
            # This receiver is just a dummy and never used.
            # Added to pass validation requiring at least one receiver in a pipeline.
            receivers: [otlp/spanmetrics]
            # The metrics_exporter must be present in this list.
            exporters: [prometheus, logging]
        metrics:
            receivers: [otlp]
            processors: [memory_limiter, batch]
            exporters: [prometheus, logging]
        metrics/prometheus:
            receivers: [prometheus]
            processors: [memory_limiter, batch]
            exporters: [prometheusremotewrite, logging]
        logs:
            receivers: [otlp]
            processors: [transform, filter, memory_limiter, batch]
            exporters: [loki, logging]
```

**Environment**
AWS Elastic Beanstalk Linux v2

**Additional context**
This makes otel collector completely unusable

### PR DESCRIPTION
**Pull request by albertteoh**
Signed-off-by: albertteoh <see.kwang.teoh@gmail.com>

**Description:** 
There is a race condition in `Map.Get` exposed by `spanmetricsprocessor`:
```
	for i := range *m.orig {
		akv := &(*m.orig)[i]
```

that can trigger an `index out of range [0] with length 0` error when there was 1 element detected in the slice, the loop is entered and, while attempting to access the first element, the slice is found to be empty.

This is because the metrics are computed in a separate goroutine from the trace "stream":

```
func (p *processorImp) ConsumeTraces(ctx context.Context, traces ptrace.Traces) error {
	go func() {
...
		p.lock.Lock()
		defer p.lock.Unlock()

		p.aggregateMetrics(traces)
...
}()
	// Forward trace data unmodified.
	return p.nextConsumer.ConsumeTraces(ctx, traces) // <-- this could modify the span attributes downstream while 
                                                                                                 // the goroutine above is trying to read it.
}
```

The fix is to `Clone()` the traces and use this clone within the traces->metrics aggregation goroutine.

**Link to tracking Issue:** Fixes https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/12644

**Testing:**

The race condition was reproduced via unit tests, with some hacks:

1. Simulate mutation of the span's attributes in downstream trace consumers by modifying `spanmetricsprocessor.ConsumeTraces` to sleep for a short period of time (1 ms) after the goroutine, then clearing every span's attributes. Why the short sleep? Because we want the spanmetrics processor to think that nothing has change right up until it enters the loop in `Map.Get` (see next step):
  ```
  func (p *processorImp) ConsumeTraces(ctx context.Context, traces ptrace.Traces) error {
	go func() {
	...
	}()
	time.Sleep(time.Millisecond)
	for i := 0; i < traces.ResourceSpans().Len(); i++ {
		attr := traces.ResourceSpans().At(i).Resource().Attributes()
		attr.Clear()
	}
	return p.nextConsumer.ConsumeTraces(ctx, traces)
  }
  ```
2. Modify `Map.Get` to sleep slightly longer than step 1. (2 ms) _within the for loop_ to allow step 1. to finish emptying all the attributes so that by the time we invoke `akv := &(*m.orig)[i]`, `m.orig` will be empty:
  ```
  func (m Map) Get(key string) (Value, bool) {
	for i := range *m.orig {
		time.Sleep(2*time.Millisecond)
		akv := &(*m.orig)[i]
		if akv.Key == key {
			return Value{&akv.Value}, true
		}
	}
	return Value{nil}, false
  }
  ```

3. This successfully triggers the `panic`:

```
=== RUN   TestProcessorConsumeTraces/Test_single_consumption,_three_spans_(Cumulative).
panic: runtime error: index out of range [0] with length 0

goroutine 35 [running]:
go.opentelemetry.io/collector/pdata/internal.Map.Get({0xb4c57012b70?}, {0x1bca27f, 0xc})
	/Users/albertteoh/go/src/github.com/albertteoh/opentelemetry-collector-contrib/processor/spanmetricsprocessor/vendor/go.opentelemetry.io/collector/pdata/internal/common.go:639 +0xfc
github.com/open-telemetry/opentelemetry-collector-contrib/processor/spanmetricsprocessor.(*processorImp).aggregateMetrics(0xc0001b87b0?, {0x1118102?})
	/Users/albertteoh/go/src/github.com/albertteoh/opentelemetry-collector-contrib/processor/spanmetricsprocessor/processor.go:365 +0x69
github.com/open-telemetry/opentelemetry-collector-contrib/processor/spanmetricsprocessor.(*processorImp).ConsumeTraces.func1()
	/Users/albertteoh/go/src/github.com/albertteoh/opentelemetry-collector-contrib/processor/spanmetricsprocessor/processor.go:240 +0xa5
created by github.com/open-telemetry/opentelemetry-collector-contrib/processor/spanmetricsprocessor.(*processorImp).ConsumeTraces
	/Users/albertteoh/go/src/github.com/albertteoh/opentelemetry-collector-contrib/processor/spanmetricsprocessor/processor.go:232 +0xb5
```

Applying the following fix passes the unit test:
  ```
	tracesClone := traces.Clone()
	go func() {
		...
		p.aggregateMetrics(tracesClone)
		...
	}()
	...
	return p.nextConsumer.ConsumeTraces(ctx, traces)
  ```

Unfortunately, there does not appear to be a feasible means to add a unit test to guard against this race condition because the problem is triggered within an external library. 

At the very least, it should be possible to assert that the metrics are aggregated on a copy `traces` and the next `ConsumerTraces` invocation uses the original. 

As such, I propose to do this in another PR because it would involve a fairly large code refactor and would not want this to: 1. block the fix from being released 2. create too much noise in this PR.

Open to suggestions!

### CODE REVIEW

File: processor/spanmetricsprocessor/processor_test.go [hunk 1]
```diff
@@ -293,6 +299,8 @@ func TestProcessorConsumeTraces(t *testing.T) {
 				err := p.ConsumeTraces(ctx, traces)
 
 				// Verify
+				<-done // Wait till ConsumeMetrics verification is done.
```
Comment (albertteoh) [inline processor/spanmetricsprocessor/processor_test.go:302]: This fixes a "test bug" I discovered while trying to reproduce the panic. As we now compute metrics in a separate goroutine, the execution of `p.ConsumeTraces(ctx, traces)` completes immediately, not allowing the metrics aggregation goroutine to complete and terminating it prematurely, that _could_ lead to false positives.

This change ensures that the verification will only be executed once metrics aggregation is complete (i.e. when the "next.ConsumeMetrics" is invoked).

File: processor/spanmetricsprocessor/processor.go [hunk 2]
```diff
@@ -228,6 +228,7 @@ func (p *processorImp) ConsumeTraces(ctx context.Context, traces ptrace.Traces)
 	// that should not interfere with the flow of trace data because
 	// it is an orthogonal concern to the trace flow (it should not impact
 	// upstream or downstream pipeline trace components).
+	tracesClone := traces.Clone()
```
Comment (bogdandrutu) [inline processor/spanmetricsprocessor/processor.go:231]: This to me sounds right the correct fix in this design, but this smells to me as a bad design somehow that we have to do this. The "pipelines" are correctly constructed and passed the right clone of the data by the collector (using capabilities, etc.), and somehow this breaks that assumption and considerably adds more CPU than simply executing the code on the critical path.

**Review by bogdandrutu — DISMISSED** [review]

File: processor/spanmetricsprocessor/processor_test.go (hunk 1 above)
Comment (jpkrohling) [reply processor/spanmetricsprocessor/processor_test.go:302]: Would the test in its current form cause the panic when the main code does not have the fix?

**Comment by amoscatelli** [comment]
Can this be merged please ?
Or are you thinking about a refactor ?

The issue is blocking my environment.

Thank you in advance

File: processor/spanmetricsprocessor/processor_test.go (hunk 1 above)
Comment (albertteoh) [reply processor/spanmetricsprocessor/processor_test.go:302]: No, the test in its current form won't cause the panic.

File: processor/spanmetricsprocessor/processor.go (hunk 2 above)
Comment (albertteoh) [reply processor/spanmetricsprocessor/processor.go:231]: Thanks for the feedback @bogdandrutu. I'm definitely open to ideas to improve the design. 😄 

The original intent with the design change was that we're effectively creating a new stream of metrics data coming out of traces and, in my mind, the propagation of trace data is an orthogonal concern to metrics. That is, the trace pipeline should not depend on, or be impacted by, other components of a downstream metrics pipeline as well as any errors and latency introduced by them. That is, I feel that spanmetricsprocessor should just be a passthrough operation for traces.

Are there existing components that translate from one telemetry type to another, whose design pattern we could follow for this processor?

> The "pipelines" are correctly constructed and passed the right clone of the data by the collector (using capabilities, etc.), and somehow this breaks that assumption and considerably adds more CPU than simply executing the code on the critical path.

I'm not very familiar with some concepts around the collector. For my learning, could you please elaborate more around what is meant by the "right clone" and "capabilities" and how this design adds considerably more CPU?

This also raises an existential question of whether this component should exist at all if it breaks some fundamental assumptions of the collector.

Comment (TylerHelmuth) [reply processor/spanmetricsprocessor/processor.go:231]: I _think_ this is the only processor housed in contrib that generates telemetry of a different signal type than the signal of the pipeline the processor runs in, but it is not the only processor that "short-circuits" data immediately to an exporter (the routingprocessor also does that).  [The need to branch between signal types has been brought up before.](https://github.com/open-telemetry/opentelemetry-collector/issues/2336)

Comment (TylerHelmuth) [reply processor/spanmetricsprocessor/processor.go:231]: Since this processor has already been accepted and is widely used, I don't think now is the time to discuss whether or not it should've been rejected due to the way it interacts with multiple signals.  Feels like a good discussion for the SIG meeting.

For this issue, I think cloning the traces payload is a reasonable solution to allow downstream trace processing to continue while this processor generates and forwards new metrics from its trace payload.  

If cloning the traces payload has substantial performance impact then it could be noted in this processor's README as a Warning, similar to the warning sections of the [cumulativetodelta processor](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/cumulativetodeltaprocessor#warnings) or [transform processor](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/transformprocessor#warnings).  Would probably be appropriate to add a "Performance Impact" to the [Collector's standard warnings](https://github.com/open-telemetry/opentelemetry-collector/blob/main/docs/standard-warnings.md).

Comment (bogdandrutu) [reply processor/spanmetricsprocessor/processor.go:231]: I think I am proposing actually executing the logic on the critical path, instead of cloning to execute async the metrics logic. Not suggesting to remove the processor.

Comment (albertteoh) [reply processor/spanmetricsprocessor/processor.go:231]: Okay, I can do this. 

As for error handling, I'm proposing to return errors caused from any logic in this processor, but only logging errors from the metrics pipeline (i.e. `ConsumeMetrics`).

That is:
```
func (p *processorImp) ConsumeTraces(ctx context.Context, traces ptrace.Traces) error {
	if err := p.tracesToMetrics(ctx, traces); err != nil {
		return err
	}

	// Forward trace data unmodified.
	return p.nextConsumer.ConsumeTraces(ctx, traces)
}

func (p *processorImp) tracesToMetrics(ctx context.Context, traces ptrace.Traces) error {
	p.lock.Lock()
	defer p.lock.Unlock()

	p.aggregateMetrics(traces)
	m, err := p.buildMetrics()
	if err != nil {
		return err
	}

	if err = p.metricsExporter.ConsumeMetrics(ctx, *m); err != nil {
		// Avoid penalising trace processing caused by metrics processing.
		p.logger.Error(err.Error())
	}

	p.resetExemplarData()
	return nil
}
```

Thoughts?

Comment (bogdandrutu) [reply processor/spanmetricsprocessor/processor.go:231]: I would do `multierr.Combine(p.tracesToMetrics(ctx, traces), p.nextConsumer.ConsumeTraces(ctx, traces))` since this processor fanout to 2 components, would call both independent.

Comment (albertteoh) [reply processor/spanmetricsprocessor/processor.go]: Good suggestion. Updated in: [9858d30](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/12661/commits/9858d30b7d386d0814dd4aec7e0dfc489a0bd3a8)

**Comment by francescopotenziani** [comment]
Hi, 
i'm waiting for this merge. Can you accept this pull request? ty

**Comment by jpkrohling** [comment]
This will get merged once it gets all the approvals. From what I can see, it's currently pending on @bogdandrutu's review.

File: processor/spanmetricsprocessor/processor.go [hunk 3]
```diff
@@ -228,28 +229,33 @@ func (p *processorImp) ConsumeTraces(ctx context.Context, traces ptrace.Traces)
 	// that should not interfere with the flow of trace data because
 	// it is an orthogonal concern to the trace flow (it should not impact
 	// upstream or downstream pipeline trace components).
```
Comment (TylerHelmuth) [inline processor/spanmetricsprocessor/processor.go:231]: Parts of this comment are no longer accurate. Can you update it to reflect the new process?

**Review by TylerHelmuth — APPROVED** [review]
Left one nit, otherwise LGTM.

File: processor/spanmetricsprocessor/processor.go (hunk 3 above)
Comment (albertteoh) [reply processor/spanmetricsprocessor/processor.go]: Thanks, updated comment in: [af3dc8f](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/12661/commits/af3dc8fb56a23be29095185302ea487a4e792de8). 

It's mostly deleting since I don't think that line of code is too controversial.

**Review by bogdandrutu — APPROVED** [review]
