### PR TITLE
[exporter/prometheusremotewrite] allocate smaller buffers for prometheus remote write batch time series

### LINKED ISSUE #34269: [exporter/prometheusremotewrite] Excessive buffer allocations in prometheus remote write exporter with large batch sizes
### Component(s)

exporter/prometheusremotewrite

## Description

We have observed high memory usage in our open telemetry collectors which are set up to pull data from a kafka cluster and push to a prometheus remote write endpoint. In order to handle the volume of data we have been increasing the batch size of the batch processor beyond the default (8192) to (50,000) or more. This is due to the fact that prometheus remote write exporter only parallelizes sends within a batch and never parallelizes batches themselves.

While 50k batch size works most of the time we have seen cases where this config runs behind so we have also tried increasing it beyond 50k to 100k/200k or more. When we did this we noticed a dramatic increase in the amount of memory utilized by our collectors.

With a pprof profile we discovered that a huge portion of memory allocations was occuring in this single function "prometheusremotewriteexporter.batchTimeSeries"
e472a152-3503-488e-940a-7feba47810be

Reviewing this function it allocates many large buffers with max capacity set to the full size of the batch even though we expect the individual requests being batched to be smaller. We patched this locally to allocate smaller buffers and observed a huge reduction in memory usage and in our test environment going from ~80gb to ~30-40gb across 11 pods.

image

I will prepare a PR with the proposed patch for further discussion.

## Steps to Reproduce

Configure a metrics pipeline with prometheus remote write exporter and a large batch size (e.g. 100k data points or more). Send large volumes of data through the pipeline, observe the memory allocations in pprof.

### Collector version

v0.101.0

## Environment
OS: Ubuntu 20.04
Compiler(if manually compiled): go 1.21.12

### OpenTelemetry Collector configuration

```
      prometheusremotewrite:
        auth:
          authenticator: bearertokenauth
        endpoint: [SCRUBBED]
        max_batch_size_bytes: 10000000
        remote_write_queue:
          enabled: true
          num_consumers: 25
        resource_to_telemetry_conversion:
          enabled: true
        timeout: 30s
```

```
 batch:
        send_batch_size: 200000
        timeout: 5s
```

### Log output

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by ben-childs-docusign**
**Description:** 
Adjusting buffer allocations in prometheusremotewriteexporter.batchTimeSeries

Rather than allocating the maximum possible size buffer each time we memoize the last buffer size that we actually used and allocate a 2x sized buffer for the next request. This ensures that we tend to allocate buffers sized appropriately for the requests and still avoid array resizing in most cases (unless the data point size changes by more than 2x from one request to the next).

This reduces memory allocations and memory usage significantly in our testing when you have large batches.

In the case that the request sizes never meet the max request size configured for the exporter the existing behavior will remain and we will continue to allocate a single buffer with a size equal to the number of time series / metric metadata objects passed in. There will still be a benefit of not allocating a huge requests buffer in this case since instead of allocating a buffer with a size equal to the number of total objects passed in we default to a buffer of size 10 or 2x the last number of requests whichever is larger.

**Link to tracking Issue:** 
Fixes https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/34269
**Testing:** <Describe what testing was performed and which tests were added.>
We have validated this fix in our test environment and existing unit tests cover this code. The observable behavior is unchanged as this just tweaks the pre-allocated size of the buffers. I can add some unit tests to validate the memoized buffer sizes once we agree on the proper place to store that memoization.

**Documentation:** <Describe the documentation added.>
No documentation added as this is a perf optimization that doesn't have any user facing impact beyond reducing memory usage.

### CODE REVIEW

File: exporter/prometheusremotewriteexporter/helper.go [hunk 1]
```diff
@@ -5,30 +5,41 @@ package prometheusremotewriteexporter // import "github.com/open-telemetry/opent
 
 import (
 	"errors"
+	"math"
 	"sort"
 
 	"github.com/prometheus/prometheus/prompb"
 )
 
+// Track batch sizes sent to avoid over allocating huge buffers.
```
Comment (ben-childs-docusign) [inline exporter/prometheusremotewriteexporter/helper.go:14]: I added this memoization here to quickly test the theory that this would help with our memory allocations. Let me know if there is a better place to store this state.

File: exporter/prometheusremotewriteexporter/helper.go [hunk 2]
```diff
@@ -5,30 +5,41 @@ package prometheusremotewriteexporter // import "github.com/open-telemetry/opent
...
+
 // batchTimeSeries splits series into multiple batch write requests.
 func batchTimeSeries(tsMap map[string]*prompb.TimeSeries, maxBatchByteSize int, m []*prompb.MetricMetadata) ([]*prompb.WriteRequest, error) {
 	if len(tsMap) == 0 {
 		return nil, errors.New("invalid tsMap: cannot be empty map")
 	}
 
-	requests := make([]*prompb.WriteRequest, 0, len(tsMap)+len(m))
-	tsArray := make([]prompb.TimeSeries, 0, len(tsMap))
+	// Allocate a buffer size of at least 10, or twice the last # of requests we sent
```
Comment (ben-childs-docusign) [inline exporter/prometheusremotewriteexporter/helper.go:26]: IMO these optimizations should be safe but we could put them behind a feature flag or config switch if there is any concern. please let me know what you prefer.

File: exporter/prometheusremotewriteexporter/helper.go (hunk 1 above)
Comment (ben-childs-docusign) [reply exporter/prometheusremotewriteexporter/helper.go:14]: We want to memoize the sizes between requests so that we can avoid allocating huge buffers beyond the very first export where we will do so since we have no information to decide on the best buffer sizes.

This memoization just stores the estimated best next buffer size and can handle parallel assignments since it is just a single integer assignment. If there is a race we will just use which ever value wins for the next buffer size.

**Review by dashpole — COMMENTED** [review]
can you add a benchmark that demonstrates the improvement?

**Comment by ben-childs-docusign** [comment]
> can you add a benchmark that demonstrates the improvement?

I'd be happy to, I did share some data in the original issue report: 
https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/34269

Were you looking for anything specific?

**Comment by dashpole** [comment]
Just a standard go benchmark, and then paste the benchstat output before/after.  You should be able to adapt one of the existing tests.

**Comment by ben-childs-docusign** [comment]
Benchmark: 
```
// Benchmark_batchTimeSeries checks batchTimeSeries
func Benchmark_batchTimeSeries(b *testing.B) {

	// First we will instantiate a dummy TimeSeries instance to pass into both the export call and compare the http request
	labels := getPromLabels(label11, value11, label12, value12, label21, value21, label22, value22)
	sample1 := getSample(floatVal1, msTime1)
	sample2 := getSample(floatVal2, msTime2)
	sample3 := getSample(floatVal3, msTime3)

	// Benchmark for large data sizes
	// First allocate 100k data points
	tsArray := make([]*prompb.TimeSeries, 0, 100000)
	for i := 0; i < 100000; i++ {
		ts := getTimeSeries(labels, sample1, sample2, sample3)
		tsArray = append(tsArray, ts)
	}

	tsMap1 := getTimeseriesMap(tsArray)

	for i := 0; i < 100; i++ {
		requests, err := batchTimeSeries(tsMap1, 1000000, nil)
		assert.NoError(b, err)
		assert.Equal(b, 18, len(requests))
	}
}
```
On main:
```
➜  prometheusremotewriteexporter git:(main) go test -bench ^Benchmark_batchTimeSeries$ -benchmem -count=1 -run=^$ -count=2 -memprofile memprofile-main.out
goos: linux
goarch: amd64
pkg: github.com/open-telemetry/opentelemetry-collector-contrib/exporter/prometheusremotewriteexporter
cpu: 13th Gen Intel(R) Core(TM) i9-13900H
Benchmark_batchTimeSeries-20                   1        4558349555 ns/op        13176014344 B/op        30407485 allocs/op
Benchmark_batchTimeSeries-20                   1        4501385843 ns/op        13175981704 B/op        30407360 allocs/op
PASS
ok      github.com/open-telemetry/opentelemetry-collector-contrib/exporter/prometheusremotewriteexporter        9.072s
```
Memory allocs:

profile004

on my branch:
```
➜  prometheusremotewriteexporter git:(bc--patchbufferallocations) go test -bench ^Benchmark_batchTimeSeries$ -benchmem -count=1 -run=^$ -count=2 -memprofile memprofile.out
goos: linux
goarch: amd64
pkg: github.com/open-telemetry/opentelemetry-collector-contrib/exporter/prometheusremotewriteexporter
cpu: 13th Gen Intel(R) Core(TM) i9-13900H
Benchmark_batchTimeSeries-20                   1        3306033633 ns/op        3743644288 B/op 30407478 allocs/op
Benchmark_batchTimeSeries-20                   1        3398682118 ns/op        3732267608 B/op 30407333 allocs/op
PASS
ok      github.com/open-telemetry/opentelemetry-collector-contrib/exporter/prometheusremotewriteexporter        6.716s
```
Memory allocs after

profile003

File: exporter/prometheusremotewriteexporter/helper_test.go [hunk 3]
```diff
@@ -68,6 +68,34 @@ func Test_batchTimeSeries(t *testing.T) {
...
+	tsArray := make([]*prompb.TimeSeries, 0, 100000)
+	for i := 0; i < 100000; i++ {
+		ts := getTimeSeries(labels, sample1, sample2, sample3)
+		tsArray = append(tsArray, ts)
+	}
+
+	tsMap1 := getTimeseriesMap(tsArray)
+
+	// Run batchTimeSeries 100 times with a 1mb max request size
+	for i := 0; i < 100; i++ {
```
Comment (dashpole) [inline exporter/prometheusremotewriteexporter/helper_test.go:92]:
```suggestion
	for i := 0; i < b.N; i++ {
```
The benchmark suite chooses the number of times to call your fn.

File: exporter/prometheusremotewriteexporter/helper_test.go [hunk 4]
```diff
@@ -68,6 +68,34 @@ func Test_batchTimeSeries(t *testing.T) {
...
+	// Benchmark for large data sizes
+	// First allocate 100k time series
+	tsArray := make([]*prompb.TimeSeries, 0, 100000)
+	for i := 0; i < 100000; i++ {
+		ts := getTimeSeries(labels, sample1, sample2, sample3)
+		tsArray = append(tsArray, ts)
+	}
+
+	tsMap1 := getTimeseriesMap(tsArray)
+
```
Comment (dashpole) [inline exporter/prometheusremotewriteexporter/helper_test.go:90]:
```suggestion

	b.ReportAllocs()
	b.ResetTimer()
```
Show memory allocations, and ignore work done thus far for perf analysis

**Comment by dashpole** [comment]
See https://pkg.go.dev/golang.org/x/perf/cmd/benchstat#hdr-Example for how to get the diff using benchstat.

File: exporter/prometheusremotewriteexporter/helper.go [hunk 5]
```diff
@@ -5,30 +5,41 @@ package prometheusremotewriteexporter // import "github.com/open-telemetry/opent
...
 	"errors"
+	"math"
 	"sort"
 
 	"github.com/prometheus/prometheus/prompb"
 )
 
+// Track batch sizes sent to avoid over allocating huge buffers.
+// This helps in the case where large batches are sent to avoid allocating too much unused memory
+var nextTimeSeriesBufferSize = math.MaxInt
```
Comment (dashpole) [inline exporter/prometheusremotewriteexporter/helper.go:16]: there can be multiple prw exporter instances, so you should add this to the `prwExporter` struct, and make the functions that use these variables functions on `prwExporter`

**Comment by ben-childs-docusign** [comment]
benchstat results:
- old :  go test -bench ^Benchmark_batchTimeSeries$ -benchmem -benchtime=100x -run=^$ -count=10 > output-main.txt
- new : go test -bench ^Benchmark_batchTimeSeries$ -benchmem -benchtime=100x -run=^$ -count=10 > output-new.txt

```
/home/ben/go/bin/benchstat output-main.txt output-new.txt
goos: linux
goarch: amd64
pkg: github.com/open-telemetry/opentelemetry-collector-contrib/exporter/prometheusremotewriteexporter
cpu: 13th Gen Intel(R) Core(TM) i9-13900H
                    │ output-main.txt │           output-new.txt            │
                    │     sec/op      │   sec/op     vs base                │
_batchTimeSeries-20       45.28m ± 5%   33.35m ± 4%  -26.35% (p=0.000 n=10)

                    │ output-main.txt │            output-new.txt            │
                    │      B/op       │     B/op      vs base                │
_batchTimeSeries-20     125.28Mi ± 0%   35.22Mi ± 0%  -71.89% (p=0.000 n=10)

                    │ output-main.txt │         output-new.txt          │
                    │    allocs/op    │  allocs/op   vs base            │
_batchTimeSeries-20       300.0k ± 0%   300.0k ± 0%  ~ (p=1.000 n=10) ¹
¹ all samples are equal
```

**Comment by ben-childs-docusign** [comment]
Updated bench stat output on latest code.
```
➜  prometheusremotewriteexporter git:(bc--patchbufferallocations) go test -bench ^Benchmark_batchTimeSeries$ -benchmem -benchtime=100x -run=^$ -count=10 > output-new-revised.txt
➜  prometheusremotewriteexporter git:(bc--patchbufferallocations) /home/ben/go/bin/benchstat output-main.txt output-new.txt output-new-revised.txt
goos: linux
goarch: amd64
pkg: github.com/open-telemetry/opentelemetry-collector-contrib/exporter/prometheusremotewriteexporter
cpu: 13th Gen Intel(R) Core(TM) i9-13900H
                    │ output-main.txt │           output-new.txt            │       output-new-revised.txt        │
                    │     sec/op      │   sec/op     vs base                │   sec/op     vs base                │
_batchTimeSeries-20       45.28m ± 5%   33.35m ± 4%  -26.35% (p=0.000 n=10)   32.15m ± 5%  -29.00% (p=0.000 n=10)

                    │ output-main.txt │            output-new.txt            │        output-new-revised.txt        │
                    │      B/op       │     B/op      vs base                │     B/op      vs base                │
_batchTimeSeries-20     125.28Mi ± 0%   35.22Mi ± 0%  -71.89% (p=0.000 n=10)   35.33Mi ± 0%  -71.80% (p=0.000 n=10)

                    │ output-main.txt │         output-new.txt          │     output-new-revised.txt      │
                    │    allocs/op    │  allocs/op   vs base            │  allocs/op   vs base            │
_batchTimeSeries-20       300.0k ± 0%   300.0k ± 0%  ~ (p=1.000 n=10) ¹   300.0k ± 0%  ~ (p=1.000 n=10) ¹
```

File: .chloggen/bc--patchbufferallocations.yaml [hunk 6]
```diff
@@ -0,0 +1,27 @@
+# Use this changelog template to create an entry for release notes.
+
+# One of 'breaking', 'deprecation', 'new_component', 'enhancement', 'bug_fix'
+change_type: bug_fix
```
Comment (ben-childs-docusign) [inline .chloggen/bc--patchbufferallocations.yaml:4]: should we call this an "enhancement"?

Comment (dashpole) [reply .chloggen/bc--patchbufferallocations.yaml:4]: yes

**Comment by ben-childs-docusign** [comment]
@dashpole thanks for the review - I believe I addressed all your comments, please let me know if I missed anything.

**Review by dashpole — APPROVED** [review]
I think this should be OK without a feature flag.

**Comment by dashpole** [comment]
@rapphil @Aneurysm9 take a look when you have the chance

**Comment by rapphil** [comment]
Taking a look later today. Thanks for the PR.

File: exporter/prometheusremotewriteexporter/helper.go (hunk 2 above)
Comment (rapphil) [reply exporter/prometheusremotewriteexporter/helper.go:36]: I think it is fine to not use a feature flag here.

**Review by rapphil — APPROVED** [review]

**Comment by rapphil** [comment]
thanks for reviewing in detail @dashpole! 

Thank you for this optimization @ben-childs-docusign !
