### PR TITLE
[pkg/stanza] Fix issue where partial fingerprint could be matched to additional files

### LINKED ISSUE #20745: [pkg/stanza] Data loss before increasing fingerprint to config size in specified state
### Component(s)

pkg/stanza, receiver/filelog

## Description

If two files have the same fingerprint and the fingerprint size is smaller than config, even if they have different bytes in the future, data of one file will be lost. 

## Steps to Reproduce
```
func TestFingerprintIncreaseUntilLargerThanConfig(t *testing.T) {
	t.Parallel()
	tempDir := t.TempDir()
	cfg := NewConfig().includeDir(tempDir)
	cfg.FingerprintSize = 18
	cfg.StartAt = "beginning"
	operator, emitCalls := buildTestManager(t, cfg)
	operator.persister = testutil.NewMockPersister("test")

	// Both of they will be include
	file1 := openTempWithPattern(t,tempDir,"*.log1")
	file2 := openTempWithPattern(t,tempDir,"*.log2")

	// Two same fingerprint file , and smaller than  config size
	content := "aaaaaaaaaaa"
	writeString(t,file1, content+"\n")
	writeString(t,file2, content+"\n")
	operator.poll(context.Background())
	// one file will be exclude, ingest only one content
	waitForToken(t, emitCalls,[]byte(content))
	expectNoTokens(t,emitCalls)
	operator.wg.Wait()

	// keep append data to file1 and file2
	newContent := "bbbbbbbbbbbb"
	newContent1 := "ddd"
	writeString(t,file1,newContent1+"\n")
	writeString(t,file2,newContent+"\n")
	operator.poll(context.Background())
	// todo data lost happen , it should be fixed , lost content from file2
	waitForTokens(t,emitCalls,[][]byte{[]byte(content),[]byte(newContent1),[]byte(newContent)})
	operator.wg.Wait()

}

```
## Expected Result
no error
## Actual Result
```
Error:      	elements differ
        	            	
        	            	extra elements in list A:
        	            	([]interface {}) (len=1) {
        	            	 ([]uint8) (len=11) {
        	            	  00000000  61 61 61 61 61 61 61 61  61 61 61                 |aaaaaaaaaaa|
        	            	 }
        	            	}
        	            	
        	            	
        	            	listA:
        	            	([][]uint8) (len=3) {
        	            	 ([]uint8) (len=11) {
        	            	  00000000  61 61 61 61 61 61 61 61  61 61 61                 |aaaaaaaaaaa|
        	            	 },
        	            	 ([]uint8) (len=3) {
        	            	  00000000  64 64 64                                          |ddd|
        	            	 },
        	            	 ([]uint8) (len=12) {
        	            	  00000000  62 62 62 62 62 62 62 62  62 62 62 62              |bbbbbbbbbbbb|
        	            	 }
        	            	}
        	            	
        	            	
        	            	listB:
        	            	([][]uint8) (len=2) {
        	            	 ([]uint8) (len=3) {
        	            	  00000000  64 64 64                                          |ddd|
        	            	 },
        	            	 ([]uint8) (len=12) {
        	            	  00000000  62 62 62 62 62 62 62 62  62 62 62 62              |bbbbbbbbbbbb|
        	            	 }
        	            	}
        	Test:       	TestFingerprintIncreaseUntilLargerThanConfig
```

### Collector version

v.0.73.0

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

### OpenTelemetry Collector configuration

_No response_

### Log output

_No response_

### Additional context

Some idea: 
If the fingerprint size is less than the config size, and the old and new fingerprints are from different files, the new file should be read from the beginning.

### PR DESCRIPTION
**Pull request by djaglowski**
**Description:**

When a file is read before its length reaches the fingerprint size, we capture the contents of the file as a partial fingerprint. When additional data is written to the file, we begin reading from the previously known length, and ultimately create a new fingerprint and offset. However, we were not discarding the first known offset. The effect of this was that, for a brief period of time (about 3 poll cycles), if a new file was found that also started with the same partial fingerprint, we would begin reading the file from the end of the partial fingerprint.

**Link to tracking Issue:**

Fixes https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/20745

**Testing:**

Used test written by @maokitty in #20745

### CODE REVIEW

File: pkg/stanza/fileconsumer/file.go [hunk 1]
```diff
@@ -294,6 +294,11 @@ func (m *Manager) findFingerprintMatch(fp *Fingerprint) (*Reader, bool) {
 	for i := len(m.knownFiles) - 1; i >= 0; i-- {
 		oldReader := m.knownFiles[i]
 		if fp.StartsWith(oldReader.Fingerprint) {
+			// Remove the old reader from the list of known files. We will
+			// add it back in saveCurrent if it is still alive.
+			defer func() {
```
Comment (dmitryax) [inline pkg/stanza/fileconsumer/file.go:299]: Why is deferring needed here, given that the next step is return?

Comment (djaglowski) [reply pkg/stanza/fileconsumer/file.go]: You're right it's not. I was concerned about mutating a slice as we iterate over it, but it is not a problem here.

**Review by dmitryax — APPROVED** [review]
