### PR TITLE
[receiver/mongodbatlas] Refactored to use New metric builder

### LINKED ISSUE #7145: Migrate mongodbatlasreceiver to the new Metrics Builder

### LINKED ISSUE #8831: [receiver/mongodbatlas] Duplicate Metrics
**Describe the bug**
For metrics that have several datapoints identified by attributes, like [mongodbatlas.process.asserts](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/receiver/mongodbatlasreceiver/metadata.yaml#L140-L147), the datapoints are spread across duplicate metrics rather than all bundled under a single metric. This is causing an issue specifically in the googlecloudexporter as Stackdriver is detecting these as duplicate metrics, since they all have the same timestamp, and rejecting them.

**Steps to reproduce**
Configure `mongodbatlas` receiver with `googlecloudexporter` and wait a few collections.

**What did you expect to see?**
No errors during the process with a valid config.

**What did you see instead?**
Getting export errors like this:

```
Exporting failed. Try enabling retry_on_failure config option.	{"kind": "exporter", "name": "googlecloud", "error": "[rpc error: code = InvalidArgument desc = One or more TimeSeries could not be written: Field timeSeries[100] had an invalid value: Duplicate TimeSeries encountered.
```

**What version did you use?**
Version: v0.45.1

**What config did you use?**
Config: 
```yaml
receivers:
  mongodbatlas:
    public_key: REDACTED
    private_key: REDACTED

processors:
  batch:

exporters:
  logging:
  googlecloud:
    retry_on_failure:
      enabled: false

service:
  pipelines:
    metrics:
      receivers: [mongodbatlas]
      processors: [batch]
      exporters: [logging, googlecloud]

```

**Environment**
OS: MacOS 12.2.1
Compiler(if manually compiled): go 1.17.8

**Additional context**
This should be an implementation fix only. I also saw this receiver was not using the `--experimental-gen` flag for mdatagen which would likely make solving this issues easier. 

I am happy to volunteer to make these changes if the owner does not want too.

### PR DESCRIPTION
**Pull request by cpheps**
**Description:** Used latest version of mdatagen on `mongodbatlas` receiver and updated scraper code to utilize generated structures while trying to leave the majority of code intact where possible. 

Not all metric and resource attributes where captures in the `metadata.yaml` so I updated that. I also renamed some resource attributes so they are all prefixed with `mongodb_atlas` where before only some where.

**Link to tracking Issue:** 
Resolves #7145
Resolves #8831

**Testing:** Current tests still pass. Manually compared results against previous results before change and matches according (minus some resource property name changes)

**Documentation:**  Generated metric docs have changed.

### CODE REVIEW

**Comment by cpheps** [comment]
@zenmoto Would you mind giving a review since you are codeowner?

File: receiver/mongodbatlasreceiver/internal/metadata/metric_name_mapping.go [hunk 1]
```diff
@@ -15,707 +15,676 @@
...
+	},
+	"DATABASE_STORAGE_SIZE": func(mb *MetricsBuilder, dp *mongodbatlas.DataPoints, ts pdata.Timestamp) {
+		mb.RecordMongodbatlasDbSizeDataPoint(ts, float64(*dp.Value), AttributeObjectType.Storage)
+	},
+	"DATABASE_INDEX_SIZE": func(mb *MetricsBuilder, dp *mongodbatlas.DataPoints, ts pdata.Timestamp) {
+		mb.RecordMongodbatlasDbSizeDataPoint(ts, float64(*dp.Value), AttributeObjectType.Index)
+	},
+	"DATABASE_DATA_SIZE": func(mb *MetricsBuilder, dp *mongodbatlas.DataPoints, ts pdata.Timestamp) {
+		mb.RecordMongodbatlasDbSizeDataPoint(ts, float64(*dp.Value), AttributeObjectType.Data)
+	},
```
Comment (dmitryax) [inline receiver/mongodbatlasreceiver/internal/metadata/metric_name_mapping.go:668]: I'm good with this approach, but a switch case construction would probably be cleaner than using a map. WDYT?

Comment (cpheps) [reply receiver/mongodbatlasreceiver/internal/metadata/metric_name_mapping.go:668]: Yeah I agree. I was trying to keep the code as close to the original as possible but I don't think a switch case is a huge change and it is cleaner. I'll make the change.

**Comment by zenmoto** [comment]
That is a dramatic improvement.

File: receiver/mongodbatlasreceiver/internal/metadata/metric_name_mapping.go (hunk 1 above)
Comment (cpheps) [reply receiver/mongodbatlasreceiver/internal/metadata/metric_name_mapping.go]: @dmitryax updated!

**Review by zenmoto — APPROVED** [review]

**Comment by cpheps** [comment]
@dmitryax Can I get a re-review on this please?

File: receiver/mongodbatlasreceiver/internal/metadata/metric_name_mapping.go [hunk 2]
```diff
@@ -15,707 +15,856 @@
...
+
 	default:
-		return nil, fmt.Errorf("unrecognized data type for metric '%s'", meas.Name)
+		return nil
 	}
+}
 
-	return &m, nil
+func MeasurementsToMetric(mb *MetricsBuilder, meas *mongodbatlas.Measurements, buildUnrecognized bool) error {
+	recordFunc := getRecordFunc(meas.Name)
```
Comment (dmitryax) [inline receiver/mongodbatlasreceiver/internal/metadata/metric_name_mapping.go:852]: My idea for the switch case was to avoid passing functions. Something like this:

```golang
for _, point := range meas.DataPoints {
    if point.Value != nil {
        curTime, err := time.Parse(time.RFC3339, point.Timestamp)
        if err != nil {
            return err
        }
        record(mb, meas, point, curTime)
    }
}
```

And inside `record` we use switch case to make particular call.

Not needed for this PR tho. Can be done separately.

**Review by dmitryax — APPROVED** [review]
Sorry for the late response

**Review by djaglowski — APPROVED** [review]
