### PR TITLE
fix(exporter/sentry): fix sentry tracing not working

### LINKED ISSUE #4141: Sentry Exporter not exporting traces to sentry
**Describe the bug**
I have my services sending tracing using opentellimetry api to the collector (config below), 
Collector works well with zipkin and sends traces there.
But these tracing are not being sent to sentry, we need to use sentry in our organisation.

For my sentry project, we also have sentry environments like dev, staging and prod, but seems exporter has no config to specify the env in collector config file?

**What did you expect to see?**
Expect to see traces appear in sentry, like they are doing in case of zipkin

**What did you see instead?**
Sentry has no traces at all

**What version did you use?**
otel/opentelemetry-collector-contrib-dev:latest

**What config did you use?**

```
receivers:
  otlp:
    protocols:
      grpc:
      http:

exporters:
  zipkin:
    endpoint: "http://host.docker.internal:9411/api/v2/spans"
  logging:
      loglevel: info
  sentry:
    dsn: mydsn
    insecure_skip_verify: true

processors:
  batch:

extensions:
  health_check: {}

service:
  extensions:
       - health_check
  pipelines:
    traces:
      receivers: [otlp]
      processors:
        - batch
      exporters: 
        - sentry
        - logging
```

**Environment**
Apple Mac laptop

### PR DESCRIPTION
**Pull request by fourbytes**
**Description:** <Describe what has changed.>
 - Set Sentry event ID to a randomly generated UUID. This should fix #4141.
 - Correctly propagate ParentSpanID and Description to exception TraceContext.

**Link to tracking Issue:** #4141

**Testing:**
 - Tested that traces were sent correctly to a live sentry instance.

**Documentation:** <Describe the documentation added.>

### CODE REVIEW

**Comment by tigrannajaryan** [comment]
@AbhiPrasad please review.

File: exporter/sentryexporter/sentry_exporter.go [hunk 1]
```diff
@@ -391,6 +398,14 @@ func transactionFromSpan(span *sentry.Span) *sentry.Event {
...
 }
 
+func generateEventID() sentry.EventID {
+	id, _ := uuid.New().MarshalBinary()
+	out := make([]byte, 32, 32)
+	hex.Encode(out, id)
+
+	return sentry.EventID(out)
+}
+
```
Comment (AbhiPrasad) [inline exporter/sentryexporter/sentry_exporter.go:408]: Prefer approach to https://github.com/getsentry/sentry-go/blob/8a528f85d1952e6690c627caec2efe7f010a6964/util.go#L15 so we don't have to bring in the uuid dep.

**Review by AbhiPrasad — CHANGES_REQUESTED** [review]
Thanks for taking this on!

**Comment by fourbytes** [comment]
Sorry for the delay. I've rebased and updated the uuid generation to the recommended method.

**Comment by fourbytes** [comment]
As per my comment in issue #4141, I found a broader issue with the root span check logic. I *think* I've found a reasonable way to solve this by treating [spans that accept remote incoming parent spans](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/api.md#spankind) as root spans. With this change I finally have traces from opentelemetry showing up perfectly in Sentry:

image

@AbhiPrasad this is ready for another review.

File: exporter/sentryexporter/sentry_exporter.go [hunk 2]
```diff
@@ -361,21 +369,25 @@ func statusFromSpanStatus(spanStatus pdata.SpanStatus) (status sentry.SpanStatus
...
 
-// isRootSpan determines if a span is a root span.
-// If parent span id is empty, then the span is a root span.
-func isRootSpan(s *sentry.Span) bool {
-	return s.ParentSpanID == sentry.SpanID{}
+// spanIsTransaction determines if a span should be sent to Sentry as a transaction.
+// If parent span id is empty or the span kind allows remote parent spans, then the span is a root span.
+func spanIsTransaction(s pdata.Span) bool {
+	kind := s.Kind()
+	return s.ParentSpanID() == pdata.SpanID{} || kind == pdata.SpanKindServer || kind == pdata.SpanKindConsumer
```
Comment (AbhiPrasad) [inline exporter/sentryexporter/sentry_exporter.go:376]: Can we make sure to update https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/exporter/sentryexporter/docs/transformation.md this new context?

Also, can we link to the opentelemetry spec about span kind in the code comments? Like what we do here: https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/21b423bfff56ca1e5d50e6b8f1f9f4929603695b/exporter/sentryexporter/sentry_exporter.go#L273

**Review by AbhiPrasad — APPROVED** [review]
Sorry for the delay, this looks good on the Sentry side. Thanks for your contribution!

**Comment by AbhiPrasad** [comment]
@bogdandrutu this is ready for general otel review btw - the doc changes aren’t a blocker and it’s important to get this merged in so that things work as expected.

**Comment by AbhiPrasad** [comment]
@bogdandrutu ping?

**Comment by AbhiPrasad** [comment]
@tigrannajaryan could you review?

**Review by tigrannajaryan — APPROVED** [review]

**Comment by tigrannajaryan** [comment]
https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/4320/checks?check_run_id=3676312902:
```
sentry_exporter.go:252: File is not `gofmt`-ed with `-s` (gofmt)
		TraceID:      span.TraceID().Bytes(),
		SpanID:       span.SpanID().Bytes(),
		Description:  description,
		Op:           op,
		Tags:         tags,
		StartTime:    unixNanoToTime(span.StartTimestamp()),
		EndTime:      unixNanoToTime(span.EndTimestamp()),
		Status:       status,
```

**Comment by AbhiPrasad** [comment]
@fourbytes could you take a look?

**Comment by bogdandrutu** [comment]
Please rebase and fix lint issues.

**Comment by fourbytes** [comment]
Rebased and gofmt'd!
