### PR TITLE
fix: close geoip providers database readers

### LINKED ISSUE #38961: [flaky test] TestProviderLocation
### Component(s)

processor/geoip

### Describe the issue you're reporting

Looks like the non-deterministic file closing surfaced on Windows. https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/14060865218/job/39371047483?pr=38886

```
=== Failed
=== FAIL: internal/provider/maxmindprovider TestProviderLocation (1.31s)
    testing.go:1232: TempDir RemoveAll cleanup: remove C:\Users\RUNNER~1\AppData\Local\Temp\TestProviderLocation4254277002\001\GeoIP2-City-Test.mmdb: Access is denied.
--- PASS: TestProviderLocation/nil_IP_address (0.00s)
--- PASS: TestProviderLocation/unsupported_database_type (0.00s)
--- PASS: TestProviderLocation/no_IP_metadata_in_database (0.00s)
--- PASS: TestProviderLocation/all_attributes_should_be_present_for_IPv4_using_GeoLite2-City_database (0.00s)
--- PASS: TestProviderLocation/subset_attributes_for_IPv6_IP_using_GeoIP2-City_database (0.00s)

=== FAIL: internal/provider/maxmindprovider TestProviderLocation (re-run 1) (1.97s)
    testing.go:[123](https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/14060865218/job/39371047483?pr=38886#step:8:124)2: TempDir RemoveAll cleanup: remove C:\Users\RUNNER~1\AppData\Local\Temp\TestProviderLocation3963163216\001\GeoIP2-City-Test.mmdb: Access is denied.
--- PASS: TestProviderLocation/nil_IP_address (0.00s)
--- PASS: TestProviderLocation/unsupported_database_type (0.00s)
--- PASS: TestProviderLocation/no_IP_metadata_in_database (0.00s)
--- PASS: TestProviderLocation/all_attributes_should_be_present_for_IPv4_using_GeoLite2-City_database (0.00s)
--- PASS: TestProviderLocation/subset_attributes_for_IPv6_IP_using_GeoIP2-City_database (0.00s)

DONE 2 runs, 57 tests, 2 failures in 17.914s
```

### PR DESCRIPTION
**Pull request by rogercoll**
#### Description

Adds a new `Close` method to the geoIP providers interface, so resources can be freed during processor's shutdown.

#### Link to tracking issue
Fixes https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/38961

#### Testing

Flaky windows tests uncommented.

### CODE REVIEW

**Comment by rogercoll** [comment]
Looks like CI failure is not related ([prometheus-compliance-tests](https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/14448942202/job/40516492643?pr=39379#logs))

File: processor/geoipprocessor/geoip_processor.go [hunk 1]
```diff
@@ -115,3 +115,14 @@ func (g *geoIPProcessor) processAttributes(ctx context.Context, metadata pcommon
 
 	return nil
 }
+
+func (g *geoIPProcessor) shutdown(ctx context.Context) error {
+	for _, geoProvider := range g.providers {
+		err := geoProvider.Close(ctx)
+		if err != nil {
+			return err
```
Comment (andrzej-stencel) [inline processor/geoipprocessor/geoip_processor.go:123]: We should probably continue to close all providers instead of returning after finding the first provider that returns an error on close?

I know this processor currently only has one provider :upside_down_face: but if another provider is added, this code will be incorrect.

File: processor/geoipprocessor/internal/provider/maxmindprovider/provider.go [hunk 2]
```diff
@@ -58,6 +58,12 @@ func (g *maxMindProvider) Location(_ context.Context, ipAddress net.IP) (attribu
 	}
 }
 
+// Close unmaps the geo database file from virtual memory and returns the
+// resources to the system.
+func (g *maxMindProvider) Close(context.Context) error {
+	return g.geoReader.Close()
```
Comment (andrzej-stencel) [inline processor/geoipprocessor/internal/provider/maxmindprovider/provider.go:64]: Should we check if `g.geoReader` is `nil`? :thinking:

File: processor/geoipprocessor/geoip_processor.go (hunk 1 above)
Comment (rogercoll) [reply processor/geoipprocessor/geoip_processor.go]: Good point, wrapping error instead https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/39379/commits/b97f2f6090a31a5ffd35f3c0f6d6e0137d5105cb

let me know if that works for you

File: processor/geoipprocessor/internal/provider/maxmindprovider/provider.go (hunk 2 above)
Comment (rogercoll) [reply processor/geoipprocessor/internal/provider/maxmindprovider/provider.go]: Upss right, let's avoid nil pointer exceptions https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/39379/commits/b97f2f6090a31a5ffd35f3c0f6d6e0137d5105cb

**Review by andrzej-stencel — APPROVED** [review]
Awesome, thank you!

File: processor/geoipprocessor/geoip_processor.go (hunk 1 above)
Comment (andrzej-stencel) [reply processor/geoipprocessor/geoip_processor.go]: Perfect! :ok_hand:
