### PR TITLE
[cmd/opampsupervisor] Fix supervisor ignoring RemoteConfig messages

### LINKED ISSUE #42474: [cmd/opampsupervisor] Supervisor ignoring RemoteConfig message
### Component(s)

cmd/opampsupervisor

## Description
When the supervisor receives a remote config from the OpAMP server, it only sends a response to the server if the supervisor runs into an error evaluating the config or if it decides to apply the configuration to the collector.

## Steps to Reproduce
There's no standard for an OpAMP server, so I'll just describe the situation where this can happen.

Start the supervisor and collector and send a remote configuration to the supervisor. The supervisor should successfully accept the remote config, apply the remote config to the collector, and report an applied status. Now the server should send a new remote config to the server. The new config should have a different hash than the one sent before, but the supervisor should evaluate as functionally equivalent to the previous config. An easy way to do this is change the order in which components are defined. 

## Expected Result
Ideally the supervisor should report some updated status about the remote configuration the server has sent it. The way the supervisor evaluates the configuration may mean there's not functional difference between the last remote config and this new one, but the config hash has changed and the server will likely expect a response.

## Actual Result
The supervisor ignores the remote config message and doesn't respond with a status related to the config it was sent. This can be problematic as the server should expect a response of some kind about the configuration it has sent.

### Supervisor version

main

## Environment
This can be seen across environments.

### Additional context

This topic was discussed in today's OpAMP SIG meeting and we agreed the server may expect a response from the agent after sending a remote configuration.

I'll have a PR up addressing this bug shortly.

### Tip

<sub>[React](https://github.blog/news-insights/product-news/add-reactions-to-pull-requests-issues-and-comments/) with 👍 to help prioritize this issue. Please use comments to provide useful context, avoiding `+1` or `me too`, to help us triage it. Learn more [here](https://opentelemetry.io/community/end-user/issue-participation/).</sub>

### PR DESCRIPTION
**Pull request by dpaasman00**
#### Description
The supervisor will sometimes ignore certain Remote Config messages from the server. Specifically if the supervisor does not think the config is different. Instead it should still respond. In the event the supervisor does not think the config is different, it will send an applied status (functionally the config that was sent is being ran, so applied is appropriate here).

#### Link to tracking issue
Fixes #42474 

#### Testing
Unit tests updated

### CODE REVIEW

File: cmd/opampsupervisor/supervisor/supervisor_test.go [hunk 1]
```diff
@@ -830,28 +840,48 @@ service:
...
-			ConfigHash: []byte("hash"),
+			ConfigHash: remoteConfigHash[:],
 		}
 
 		remoteConfigStatusUpdated := false
 		mc := &mockOpAMPClient{
-			setRemoteConfigStatusFunc: func(*protobufs.RemoteConfigStatus) error {
+			setRemoteConfigStatusFunc: func(rcs *protobufs.RemoteConfigStatus) error {
 				remoteConfigStatusUpdated = true
+				// assert the
```
Comment (evan-bradley) [inline cmd/opampsupervisor/supervisor/supervisor_test.go]:
```suggestion
				// assert the Supervisor reports the new hash as applied
```

File: .chloggen/fix_dakotapaasman-config-unchanged-report-rcs.yaml [hunk 2]
```diff
@@ -0,0 +1,27 @@
+# Use this changelog template to create an entry for release notes.
+
+# One of 'breaking', 'deprecation', 'new_component', 'enhancement', 'bug_fix'
+change_type: "bug_fix"
+
+# The name of the component, or a single word describing the area of concern, (e.g. filelogreceiver)
+component: "opampsupervisor"
+
+# A brief description of the change.  Surround your text with quotes ("") if it needs to start with a backtick (`).
+note: "Fix supervisor ignoring RemoteConfig messages from server"
```
Comment (evan-bradley) [inline .chloggen/fix_dakotapaasman-config-unchanged-report-rcs.yaml]:
```suggestion
note: Always respond to `RemoteConfig` messages with a `RemoteConfigStatus` message
```

File: .chloggen/fix_dakotapaasman-config-unchanged-report-rcs.yaml [hunk 3]
```diff
@@ -0,0 +1,27 @@
...
+
+# Mandatory: One or more tracking issues related to the change. You can use the PR number here if no issue exists.
+issues: [42474]
+
+# (Optional) One or more lines of additional information to render under the primary note.
+# These lines will be padded with 2 spaces and then inserted directly into the document.
+# Use pipe (|) for multiline entries.
+subtext:
```
Comment (evan-bradley) [inline .chloggen/fix_dakotapaasman-config-unchanged-report-rcs.yaml]:
```suggestion
subtext: |
  Previously the Supervisor would not respond if the effective config did not change.
  This caused issues where the same config with a different hash (e.g. reordered keys in the config)
  would not be reported and would appear unapplied by the Supervisor.
```

**Review by evan-bradley — APPROVED** [review]
Looks good to me.

**Review by atoulme — APPROVED** [review]
