### PR TITLE
[processor/k8sattributes] rename k8sattributes processor internal metrics

### LINKED ISSUE #2322: Metrics in k8s processor needs refactor
**Describe the bug**
Metrics exposed by k8s processor lacks meaningful description, and have invalid format.

**Additional context**
As mentioned in comment https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/2199#discussion_r573754727 there is need to provide some additional information about meaning of those metrics. Also need to change their format to fit standard.

### PR DESCRIPTION
**Pull request by fatsheep9146**
**Description:** 
Fix #2322

### CODE REVIEW

File: processor/k8sattributesprocessor/internal/observability/observability.go [hunk 1]
```diff
@@ -27,17 +27,17 @@ func init() {
...
+	mPodsAdded          = stats.Int64("otelcol.k8s.pod.added", "Number of pod add events received", "1")
+	mPodsDeleted        = stats.Int64("otelcol.k8s.pod.deleted", "Number of pod delete events received", "1")
+	mPodTableSize       = stats.Int64("otelcol.k8s.pod.table.size", "Size of table containing pod info", "1")
+	mIPLookupMiss       = stats.Int64("otelcol.k8s.ip.lookup.miss", "Number of times pod by IP lookup failed.", "1")
+	mNamespacesUpdated  = stats.Int64("otelcol.k8s.namespace.updated", "Number of namespace update events received", "1")
+	mNamespacesAdded    = stats.Int64("otelcol.k8s.namespace.added", "Number of namespace add events received", "1")
+	mNamespacesDeleted  = stats.Int64("otelcol.k8s.namespace.deleted", "Number of namespace delete events received", "1")
+	mReplicaSetsUpdated = stats.Int64("otelcol.k8s.replicaset.updated", "Number of ReplicaSet update events received", "1")
+	mReplicaSetsAdded   = stats.Int64("otelcol.k8s.replicaset.added", "Number of ReplicaSet add events received", "1")
+	mReplicaSetsDeleted = stats.Int64("otelcol.k8s.replicaset.deleted", "Number of ReplicaSet delete events received", "1")
```
Comment (dmitryax) [inline processor/k8sattributesprocessor/internal/observability/observability.go:40]: The `otelcol` prefix is already added to all the metrics. So we don't want to duplicate it. PTAL at metric names that other components are exposing, e.g. `otelcol_processor_batch_batch_send_size`

I believe we should have `processor.k8sattributes.replicasets.updated` etc

**Comment by fatsheep9146** [comment]
nicely ping @dmitryax

**Review by dmitryax — APPROVED** [review]

**Comment by fatsheep9146** [comment]
> @fatsheep9146 After giving it a second thought, this change seems too aggressive. We need to run it by a feature gate. Can you please submit another PR to apply an alpha feature gate `processor.k8sattributes.RenameInternalMetrics` on this change? We also need to show a warning in the logs if it's disabled with something like: "The internal metrics of the processor will be renamed 0.82.0. Make sure to enable feature gate `processor.k8sattributes.RenameInternalMetrics` to test it in advance."

Ok, I will submit this pr tomorrow @dmitryax
