### PR TITLE
[pkg/stanza/fileconsumer] Fix issue where offsets could be ignored when start_at=end

### LINKED ISSUE #12769: [receiver/filelog] "start_at: end" should be disregarded when loading offsets from storage
**Describe the bug**
When using a storage extension, the receiver should be able to seamlessly resume log file consumption after a restart. However, current behavior will skip lines that were added to a file while the collector was not running. In order to correct the behavior, the receiver should use ignore the `start_at` setting for files who's offsets are retrieved from a storage extension.

**Steps to reproduce**
Sample configuration:
```yaml
receivers:
  filelog:
    include: [foo/*.log]

exporters:
  logging:
    loglevel: debug

extensions:
  file_storage:
    directory: foo/storage

service:
  extensions: [file_storage]
  pipelines:
    logs:
      receivers: [filelog]
      exporters: [logging]
```

- Start the collector and add some lines to the log file. They should be consumed immediately. Offsets should be written to the storage extension in nearly real time.
- Stop the collector.
- Add some lines to the log file. These are the lines that are skipped due to this bug.
- Start the collector. The new lines should be consumed immediately, but they are not.
- Add more lines to the log file. These lines are correctly consumed.

### PR DESCRIPTION
**Pull request by djaglowski**
The 'start_at' setting is meant to be applicable only during a the first poll 
cycle of the collector. Once the collector has had a chance to start watching 
for files, it should consume any new files from scratch. When restarted, the 
collector should check for the existence of offsets that were previously saved. 
If found, the collector should act the same as it would _after_ the first poll 
cycle. (ie. For known files, start from offsets. For newly found files, start 
from the beginning.) 
 
This PR also standardizes and hardens the related unit tests, which should now 
comprehensively cover all cases w/r/t starting and restarting with offsets. 

The PR also cleans up the mechanism by which we detect whether or not to 
initialize an offset to the end during "restartup". (see [comment here](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/12767/files#r932277408))

Depends on #12771 

Resolves #12769

### CODE REVIEW

File: pkg/stanza/fileconsumer/file.go [hunk 1]
```diff
@@ -320,6 +320,11 @@ func (f *Input) loadLastPollFiles(ctx context.Context) error {
 		return fmt.Errorf("decoding file count: %w", err)
 	}
 
+	if knownFileCount > 0 {
+		f.Infow("Resuming from previously known offset(s). 'start_at' setting is not applicable.")
```
Comment (TylerHelmuth) [inline pkg/stanza/fileconsumer/file.go:324]: Is there any way to override this feature?  Feels like there may be situations where a user would want to re-ingest a file, like if their collector didn't have the proper processors.  Probably not a production feature, but seems like a good option.

Comment (djaglowski) [reply pkg/stanza/fileconsumer/file.go:324]: Sort of. In the simplest case, the user just needs to remove or alter the storage extension. In the case of the `file_storage` extension, they can clear out the storage directory that they've configured, or just choose a new directory to stash offsets.

**Review by TylerHelmuth — APPROVED** [review]
