### PR TITLE
[exporter/awss3] AWS S3 partition timezone config

### LINKED ISSUE #42319: AWS S3 exporter s3_partition_format uses local timezone instead of UTC
### Component(s)

exporter/awss3

## Description

AWS S3 exporter `s3_partition_format` uses local timezone instead of UTC and there is no way to change timezone used for partitioning which might be unexpected since there might be multiple collectors writing into same bucket with different timezones

### Collector version

v0.133.0

## Environment

Any

### OpenTelemetry Collector configuration

```yaml
exporters:
  awss3:
    s3uploader:
      region: "us-east-1"
      s3_bucket: "tmp"
      s3_prefix: "logs"
      s3_partition_format: "%Y/%m/%d/%H/%M" # <- this time will be local instead of UTC
```

### Log output

```shell

```

### Additional context

_No response_

### Tip

<sub>[React](https://github.blog/news-insights/product-news/add-reactions-to-pull-requests-issues-and-comments/) with 👍 to help prioritize this issue. Please use comments to provide useful context, avoiding `+1` or `me too`, to help us triage it. Learn more [here](https://opentelemetry.io/community/end-user/issue-participation/).</sub>

### PR DESCRIPTION
**Pull request by mymmrac**
#### Description

Add `S3PartitionTimezone` config value to be able to change the timezone used for time-based partitioning.

#### Link to tracking issue

Resolves #42319.

#### Testing

Updated existing tests to include time location.

#### Documentation

Added new config value to README.

### CODE REVIEW

**Comment by paulojmdias** [comment]
@mymmrac thanks for your contribution. Can you please update the changelog? You can generate a new entry using `make chlog-new` and then fill in the required details.

File: exporter/awss3exporter/config.go [hunk 1]
```diff
@@ -63,6 +66,9 @@ type S3UploaderConfig struct {
 	// If unspecified, a default function will be used that generates a random string.
 	// Valid values are: "uuidv7"
 	UniqueKeyFuncName string `mapstructure:"unique_key_func_name"`
+
+	// Not in config file, will be set in [Config.Validate].
```
Comment (atoulme) [inline exporter/awss3exporter/config.go]: typically Validate is idempotent. Do you need this field on the Config struct? Can it be derived when used?

Comment (mymmrac) [reply exporter/awss3exporter/config.go]: I can change that, good point

Comment (mymmrac) [reply exporter/awss3exporter/config.go]: Moved the logic to check timezone into `newUploadManager`

File: exporter/awss3exporter/config.go [hunk 2]
```diff
@@ -155,5 +157,6 @@ func (c *Config) Validate() error {
 	if c.S3Uploader.UniqueKeyFuncName != "" && !validUniqueKeyFuncs[c.S3Uploader.UniqueKeyFuncName] {
 		errs = multierr.Append(errs, errors.New("invalid UniqueKeyFuncName"))
 	}
+
```
Comment (atoulme) [inline exporter/awss3exporter/config.go]:
```suggestion
```

**Review by atoulme — APPROVED** [review]
