### PR TITLE
[receiver/prometheusreceiver] Convert NHCB to explicit histogram metric

### LINKED ISSUE #41131: [receiver/prometheusreceiver] does not handle native histograms with custom bucket correctly
### Component(s)

receiver/prometheus

## Description

Native histograms with custom buckets should be converted to explicit Otel histograms, not exponential Otel histograms with fake schema -53.

See https://prometheus.io/docs/specs/native_histograms/#custom-values

## Steps to Reproduce

Add unit test to enable Prometheus parsing to produce NHCB.
Enable the native histograms feature gate.
No need for protobuf input, normal testcase will work.

## Expected Result

Explicit histogram metric on Otel side.

## Actual Result

I expect invalid exponential histogram.

### Collector version

v0.128.0

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

### OpenTelemetry Collector configuration

```yaml

```

### Log output

```shell

```

### Additional context

_No response_

### Tip

<sub>[React](https://github.blog/news-insights/product-news/add-reactions-to-pull-requests-issues-and-comments/) with 👍 to help prioritize this issue. Please use comments to provide useful context, avoiding `+1` or `me too`, to help us triage it. Learn more [here](https://opentelemetry.io/community/end-user/issue-participation/).</sub>

### PR DESCRIPTION
**Pull request by jelly-afk**
#### Description
added prometheus NHCB (native histogram with custom buckets) to otel explicit histogram conversion.

#### Link to tracking issue
Fixes #41131 

#### Testing
Added `TestMetricGroupData_toNHCBDistributionUnitTest` test function to test the conversion.

### CODE REVIEW

File: receiver/prometheusreceiver/internal/transaction.go [hunk 1]
```diff
@@ -223,7 +223,7 @@ func (t *transaction) detectAndStoreNativeHistogramStaleness(atMs int64, key *re
 
 // getOrCreateMetricFamily returns the metric family for the given metric name and scope,
 // and true if an existing family was found.
-func (t *transaction) getOrCreateMetricFamily(key resourceKey, scope scopeID, mn string) *metricFamily {
+func (t *transaction) getOrCreateMetricFamily(key resourceKey, scope scopeID, mn string, schema int32) *metricFamily {
```
Comment (dashpole) [inline receiver/prometheusreceiver/internal/transaction.go]: I would consider not passing schema as an argument here... There are too many places where we use this function and it doesn't make sense.  Instead, just change the call site where we pass the schema below:

```diff
-curMF := t.getOrCreateMetricFamily(*rKey, getScopeID(ls), metricName, schema)
+curMF := t.getOrCreateMetricFamily(*rKey, getScopeID(ls), metricName)
+if curMF. mtype == pmetric.MetricTypeExponentialHistogram && schema == -53 {
+    curMF.mtype = pmetric.MetricTypeHistogram
+}
```
```

**Comment by jelly-afk** [comment]
I would like do some changes here, will open when done.

**Comment by jelly-afk** [comment]
In remotewrite receiver if spans are empty, bucket counts are not filled
https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/9076436634c697ccee0275720985b6bee2f10f84/receiver/prometheusremotewritereceiver/receiver.go#L753-L758
 we should follow it here too, right?

**Comment by dashpole** [comment]
I believe it is filled with all zeroes by the `make()` line

**Comment by jelly-afk** [comment]
ready for review

File: receiver/prometheusreceiver/internal/transaction.go (hunk 1 above)
Comment (ArthurSens) [inline receiver/prometheusreceiver/internal/transaction.go]: Something feels off with this strategy of adding a schema as an argument 🤔 

What if we took a similar approach to the one we use when detecting a NativeHistogram? When we call AppendHistogram, we toggle a flag in the `transaction` object called `addingNativeHistogram`. Couldn't we add the flag there, too?

File: receiver/prometheusreceiver/internal/transaction.go [hunk 2]
```diff
@@ -295,6 +298,12 @@ func (t *transaction) AppendHistogram(_ storage.SeriesRef, ls labels.Labels, atM
 	default:
 	}
 
+	var schema int32
+	if h != nil {
+		schema = h.Schema
+	} else if fh != nil {
+		schema = fh.Schema
+	}
 	t.addingNativeHistogram = true
```
Comment (ArthurSens) [inline receiver/prometheusreceiver/internal/transaction.go:308]: This is the place I had in mind in the comment above. Couldn't we add a second flag here, e.g.

```go
	var schema int32
	if h != nil {
		schema = h.Schema
	} else if fh != nil {
		schema = fh.Schema
	}
	t.addingNativeHistogram = true
	if schema == -53 {
		t.addingNHCB = true
	}
```

If we use that flag when calling getOrCreateMetricFamily, then the schema argument isn't needed and we don't need to add -1 in weird places 😅

File: receiver/prometheusreceiver/internal/transaction.go [hunk 3]
```diff
@@ -245,7 +245,10 @@ func (t *transaction) getOrCreateMetricFamily(key resourceKey, scope scopeID, mn
 		if !ok || !mf.includesMetric(mn) {
 			curMf = newMetricFamily(mn, t.mc, t.logger)
 			if curMf.mtype == pmetric.MetricTypeHistogram && mfKey.isExponentialHistogram {
-				curMf.mtype = pmetric.MetricTypeExponentialHistogram
+				// Don't convert NHCB to ExponentialHistogram.
+				if schema != -53 {
+					curMf.mtype = pmetric.MetricTypeExponentialHistogram
+				}
 			}
```
Comment (ArthurSens) [inline receiver/prometheusreceiver/internal/transaction.go]: I believe this could become a single if...?

**Review by ArthurSens — COMMENTED** [review]
Thanks for working on this one! It looks almost ready, to be honest. I think we can improve a little bit on the readability of the `getOrCreatedMetricFamily` method, adding -1 in almost all calls of that function is looking weird 🤔

File: receiver/prometheusreceiver/internal/transaction.go (hunk 1 above)
Comment (jelly-afk) [reply receiver/prometheusreceiver/internal/transaction.go]: yes that sounds good too

File: receiver/prometheusreceiver/internal/transaction.go (hunk 3 above)
Comment (jelly-afk) [reply receiver/prometheusreceiver/internal/transaction.go]: yes, missed that

**Comment by jelly-afk** [comment]
oh changelog got new validations, will fix

**Comment by jelly-afk** [comment]
ah chlog files from prev release

**Review by ArthurSens — APPROVED** [review]
LGTM, but I'd love it if we could wait for @dashpole or @krajorama's review as well

**Review by dashpole — APPROVED** [review]

**Comment by dashpole** [comment]
huh, something strange happened with my comments.  Maybe I didn't actually leave them? ~~Ignore them for now~~

Edit: Re-posted it below

File: receiver/prometheusreceiver/internal/metricfamily.go [hunk 4]
```diff
@@ -269,6 +292,52 @@ func convertAbsoluteBuckets(spans []histogram.Span, counts []float64, buckets pc
...
+	if len(histogram.PositiveSpans) == 0 {
+		return bucketCounts
+	}
+	bucketIdx := 0
+	for _, span := range histogram.PositiveSpans {
+		bucketIdx += int(span.Offset)
+
+		for i := uint32(0); i < span.Length && bucketIdx < len(bucketCounts) && i < uint32(len(histogram.PositiveBuckets)); i++ {
+			if bucketIdx >= 0 && bucketIdx < len(bucketCounts) {
+				bucketCounts[bucketIdx] = uint64(histogram.PositiveBuckets[i])
```
Comment (dashpole) [inline receiver/prometheusreceiver/internal/metricfamily.go:334]:
```suggestion
                 // This intentionally truncates the float value to an integer (e.g. 5.7 becomes 5).
				bucketCounts[bucketIdx] = uint64(histogram.PositiveBuckets[i])
```
