### PR TITLE
make flaky test TestStartTimeMetricRegex more reliable

### LINKED ISSUE #5752: Flaky test: prometheusreceiver: TestStartTimeMetricRegex failing
**Describe the bug**
`TestStartTimeMetricRegex` is failing, (it was rerun since, will add a link to a failed workflow run when it happens again)

```
make[2]: Entering directory '/home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/receiver/prometheusreceiver'
go test -race -timeout 300s --tags="" ./...
--- FAIL: TestStartTimeMetricRegex (12.72s)
    metrics_receiver_test.go:1379: 
        	Error Trace:	metrics_receiver_test.go:1379
        	            				metrics_receiver_test.go:1564
        	            				metrics_receiver_test.go:1520
        	Error:      	Not equal: 
        	            	expected: time.Date(1970, time.January, 1, 0, 6, 40, 800000000, time.UTC)
        	            	actual  : time.Date(1970, time.January, 1, 0, 0, 0, 0, time.UTC)
        	            	
        	            	Diff:
        	            	--- Expected
        	            	+++ Actual
        	            	@@ -1,4 +1,4 @@
        	            	 (time.Time) {
        	            	- wall: (uint64) 800000000,
        	            	- ext: (int64) 62135597200,
        	            	+ wall: (uint64) 0,
        	            	+ ext: (int64) 62135596800,
        	            	  loc: (*time.Location)(<nil>)
        	Test:       	TestStartTimeMetricRegex
        	Messages:   	label_values:{value:"400" has_value:true} label_values:{value:"post" has_value:true} points:{timestamp:{seconds:1634220661 nanos:999000000} double_value:nan}
    metrics_receiver_test.go:1379: 
        	Error Trace:	metrics_receiver_test.go:1379
        	            				metrics_receiver_test.go:1564
        	            				metrics_receiver_test.go:1520
        	Error:      	Not equal: 
        	            	expected: time.Date(1970, time.January, 1, 0, 6, 40, 800000000, time.UTC)
        	            	actual  : time.Date(1970, time.January, 1, 0, 0, 0, 0, time.UTC)
        	            	
        	            	Diff:
        	            	--- Expected
        	            	+++ Actual
        	            	@@ -1,4 +1,4 @@
        	            	 (time.Time) {
        	            	- wall: (uint64) 800000000,
        	            	- ext: (int64) 62135597200,
        	            	+ wall: (uint64) 0,
        	            	+ ext: (int64) 62135596800,
        	            	  loc: (*time.Location)(<nil>)
        	Test:       	TestStartTimeMetricRegex
        	Messages:   	label_values:{value:"200" has_value:true} label_values:{value:"post" has_value:true} points:{timestamp:{seconds:1634220661 nanos:999000000} double_value:nan}
    metrics_receiver_test.go:1379: 
        	Error Trace:	metrics_receiver_test.go:1379
        	            				metrics_receiver_test.go:1564
        	            				metrics_receiver_test.go:1520
        	Error:      	Not equal: 
        	            	expected: time.Date(1970, time.January, 1, 0, 6, 40, 800000000, time.UTC)
        	            	actual  : time.Date(1970, time.January, 1, 0, 0, 0, 0, time.UTC)
        	            	
        	            	Diff:
        	            	--- Expected
        	            	+++ Actual
        	            	@@ -1,4 +1,4 @@
        	            	 (time.Time) {
        	            	- wall: (uint64) 800000000,
        	            	- ext: (int64) 62135597200,
        	            	+ wall: (uint64) 0,
        	            	+ ext: (int64) 62135596800,
        	            	  loc: (*time.Location)(<nil>)
        	Test:       	TestStartTimeMetricRegex
        	Messages:   	points:{timestamp:{seconds:1634220661 nanos:999000000} distribution_value:{count:-9223372036854775808 buckets:{count:-9223372036854775808}}}
    metrics_receiver_test.go:1379: 
        	Error Trace:	metrics_receiver_test.go:1379
        	            				metrics_receiver_test.go:1564
        	            				metrics_receiver_test.go:1520
        	Error:      	Not equal: 
        	            	expected: time.Date(1970, time.January, 1, 0, 6, 40, 800000000, time.UTC)
        	            	actual  : time.Date(1970, time.January, 1, 0, 0, 0, 0, time.UTC)
        	            	
        	            	Diff:
        	            	--- Expected
        	            	+++ Actual
        	            	@@ -1,4 +1,4 @@
        	            	 (time.Time) {
        	            	- wall: (uint64) 800000000,
        	            	- ext: (int64) 62135597200,
        	            	+ wall: (uint64) 0,
        	            	+ ext: (int64) 62135596800,
        	            	  loc: (*time.Location)(<nil>)
        	Test:       	TestStartTimeMetricRegex
        	Messages:   	points:{timestamp:{seconds:1634220661 nanos:999000000} summary_value:{count:{value:-9223372036854775808} sum:{} snapshot:{percentile_values:{percentile:1 value:nan}}}}
    metrics_receiver_test.go:1384: 
        	Error Trace:	metrics_receiver_test.go:1384
        	            				metrics_receiver_test.go:1564
        	            				metrics_receiver_test.go:1520
        	Error:      	Not equal: 
        	            	expected: 11
        	            	actual  : 22
        	Test:       	TestStartTimeMetricRegex
FAIL
FAIL	github.com/open-telemetry/opentelemetry-collector-contrib/receiver/prometheusreceiver	38.324s
```

**Steps to reproduce**
N/A

**What did you expect to see?**
No test failure

**What did you see instead?**
Test failure

**What version did you use?**
Version: https://github.com/open-telemetry/opentelemetry-collector-contrib/commit/52f5f2b111dfd4d0d892c52fcc93c50382fac2c5 (from this PR https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/5694)

**What config did you use?**
N/A

**Environment**
N/A -> CI run

### PR DESCRIPTION
**Pull request by mustafain117**
**Description:** <Describe what has changed.>
`TestStartTimeMetricRegex` is flaky as it failed in a unit test workflow run according to issue open-telemetry#5752
Unable to reproduce this failure locally by running this test multiple times.
However, based on the error trace in the issue description, the test is flaky as it intermittently generates an additional scrape result with staleness markers.
In order to make this test more reliable, we should only validate the first scrape result and ignore any subsequent scrapes.

**Link to tracking Issue:** <Issue number if applicable>
Resolves #5752

### CODE REVIEW

File: receiver/prometheusreceiver/metrics_receiver_test.go [hunk 1]
```diff
@@ -1364,18 +1364,17 @@ var startTimeMetricPageStartTimestamp = &timestamppb.Timestamp{Seconds: 400, Nan
...
-			}
-			for _, ts := range metric.GetTimeseries() {
-				assert.Equal(t, timestamp.AsTime(), ts.GetStartTimestamp().AsTime(), ts.String())
-				numTimeseries++
-			}
+	for _, metric := range mds[0].Metrics {
+		timestamp := startTimeMetricPageStartTimestamp
+		switch metric.GetMetricDescriptor().GetType() {
+		case metricspb.MetricDescriptor_GAUGE_DOUBLE, metricspb.MetricDescriptor_GAUGE_DISTRIBUTION:
+			timestamp = nil
```
Comment (MovieStoreGuy) [inline receiver/prometheusreceiver/metrics_receiver_test.go:1373]: Not sure I grasp why it is needed to se this to `nil`?

Comment (MovieStoreGuy) [reply receiver/prometheusreceiver/metrics_receiver_test.go:1373]: Setting this to nil would cause issues within test cases below.

Comment (mustafain117) [reply receiver/prometheusreceiver/metrics_receiver_test.go:1373]: Only metrics of cumulative type are required to have a `StartTimestamp`. Since Gauge is not a cumulative metric type, we set the the start timestamp to `nil`.

**Review by dashpole — APPROVED** [review]
LGTM.  Thanks for fixing this

**Review by Aneurysm9 — APPROVED** [review]

**Comment by alolita** [comment]
Thanks @bogdandrutu
