### PR TITLE
[connector/spanmetrics] Fix memory leak

### LINKED ISSUE #27654: spanmetrics connector has memory leak
### Component(s)

connector/spanmetrics

## Description

The `spanmetrics` connector has a memory leak that occurs when the cumulative temporality is used. The `connectorImp#resourceMetrics` map is only ever cleaned up in delta temporality.

https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/628a6cb5f3ef1c2c615c3f9a066ae4a29e718fda/connector/spanmetricsconnector/connector.go#L253-L271

## Steps to Reproduce

 1. Enable cumulative temporality
 2. Observe many changing resources

## Expected Result

`connectorImp#resourceMetrics` is eventually cleaned up.

## Actual Result

`connectorImp#resourceMetrics` keeps growing over time.

### Collector version

628a6cb5f3ef1c2c615c3f9a066ae4a29e718fda

### Environment information

Not relevant

### OpenTelemetry Collector configuration

_No response_

### Log output

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by bripkens**
# Why

The `spanmetrics` connector has a memory leak that occurs when the cumulative temporality is used. The `connectorImp#resourceMetrics` map is only ever cleaned up in delta temporality.

# What

Turn `connectorImp#resourceMetrics` into a LRU cache with a maximum size. To correctly handle metric resets we also introduce a start timestamp per `resourceMetric` instance.

# References

Fixes https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/27654

### CODE REVIEW

File: connector/spanmetricsconnector/config.go [hunk 1]
```diff
@@ -46,6 +46,11 @@ type Config struct {
 	// Optional. See defaultDimensionsCacheSize in connector.go for the default value.
 	DimensionsCacheSize int `mapstructure:"dimensions_cache_size"`
 
+	// ResourceMetricsCacheSize defines the size of the cache holding metrics for a service. This is mostly relevant for
+	// cumulative temporality to avoid memory leaks and correct metric timestamp resets.
+	// Optional. See defaultResourceMetricsCacheSize in connector.go for the default value.
+	ResourceMetricsCacheSize int `mapstructure:"resource_metrics_cache_size"`
```
Comment (crobert-1) [inline connector/spanmetricsconnector/config.go:52]: I believe we want to add an entry in the README for this config option, so users are aware of it, and know how to use it.

Comment (bripkens) [reply connector/spanmetricsconnector/config.go:52]: done @crobert-1

File: connector/spanmetricsconnector/connector.go [hunk 2]
```diff
@@ -79,6 +77,8 @@ type resourceMetrics struct {
 	sums       metrics.SumMetrics
 	events     metrics.SumMetrics
 	attributes pcommon.Map
+	// startTimestamp captures when the first data points for this resource are recorded.
+	startTimestamp pcommon.Timestamp
```
Comment (atoulme) [inline connector/spanmetricsconnector/connector.go:81]: Is this related to the fix?

Comment (bripkens) [reply connector/spanmetricsconnector/connector.go:81]: Yes, it is related @atoulme. As the sums can now go back to `0` for the same attribute combination under cumulative temporality, the start timestamp needs to be reset according to the spec:

https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/data-model.md#temporality

File: connector/spanmetricsconnector/internal/cache/cache.go [hunk 3]
```diff
@@ -74,3 +74,17 @@ func (c *Cache[K, V]) Purge() {
 	c.lru.Purge()
 	c.RemoveEvictedItems()
 }
+
+// ForEach iterates over all the items within the cache, as well as the evicted items (if any).
+func (c *Cache[K, V]) ForEach(fn func(k K, v V)) {
```
Comment (albertteoh) [inline connector/spanmetricsconnector/internal/cache/cache.go:79]: Nice

**Review by albertteoh — APPROVED** [review]
LGTM, thanks very much!

File: connector/spanmetricsconnector/connector_test.go [hunk 4]
```diff
@@ -32,18 +32,19 @@ import (
...
+	boolAttrName             = "boolAttrName"
+	nullAttrName             = "nullAttrName"
+	mapAttrName              = "mapAttrName"
+	arrayAttrName            = "arrayAttrName"
+	notInSpanAttrName0       = "shouldBeInMetric"
+	notInSpanAttrName1       = "shouldNotBeInMetric"
+	regionResourceAttrName   = "region"
+	exceptionTypeAttrName    = "exception.type"
+	DimensionsCacheSize      = 2
+	ResourceMetricsCacheSize = 5
```
Comment (albertteoh) [inline connector/spanmetricsconnector/connector_test.go:47]: nit: does this need to be exported? Looks like `DimensionsCacheSize` might be in the same boat as well.

Comment (bripkens) [reply connector/spanmetricsconnector/connector_test.go]: done @albertteoh

**Review by albertteoh — APPROVED** [review]

**Review by mfilipe — APPROVED** [review]
I don't have knowledge to read the code, but this PR seems promises to solve a problem that I have.

**Review by atoulme — APPROVED** [review]

File: .chloggen/bripkens-spanmetrics-memory-leak.yaml [hunk 5]
```diff
@@ -0,0 +1,11 @@
+# One of 'breaking', 'deprecation', 'new_component', 'enhancement', 'bug_fix'
+change_type: bug_fix
+
+# The name of the component, or a single word describing the area of concern, (e.g. filelogreceiver)
+component: connector/spanmetrics
+
+# A brief description of the change.  Surround your text with quotes ("") if it needs to start with a backtick (`).
+note: Fix memory leak.
```
Comment (JaredTan95) [inline .chloggen/bripkens-spanmetrics-memory-leak.yaml:8]:
```suggestion
note: Fix memory leak when the cumulative temporality is used.
```

**Comment by bripkens** [comment]
done @JaredTan95

**Review by atoulme — APPROVED** [review]

**Review by TylerHelmuth — APPROVED** [review]
