### PR TITLE
[pkg/ottl] Add support for lists as Getter values

### LINKED ISSUE #16320: [pkg/ottl] Unable to use ottl lists in a Getter
### Component(s)

pkg/ottl

## Description
While trying to set an attribute to a list of strings I ran into an issue trying to use `set` with OTTL lists.  The exact statement was 

```yaml
- context: span
  statements:
    - 'set(attributes["list-attr"], ["this", "is", "a", "list"])'
```

which resulted in a parsing error during collector startup.  Digging into the issue it looks like `newGetter` doesn't know how to handle `val.List`.

I see two solutions:
1. Update `newGetter` to return a `literal[K]` with the value being the list, like `return &literal[K]{value: val.List}, nil`.  This is probably undesireable because it ends up exposing the grammar structure to functions and contexts.  The `set` function, for example, will end up passing the `list` struct to the context which doesn't know how to handle it.
2. Update `newGetter` to return a `literal[K]` with the value being a go slice representation of the list.  This means looping through the list and building out a slice based on the grammar values.

I think option 2 is the better solution.

## Steps to Reproduce

Pass a list as the Getter parameter to a function.

## Expected Result

The function knows how to use the list.

## Actual Result

The collector errors during config validation.

### PR DESCRIPTION
**Pull request by evan-bradley**
**Description:**

Allow using lists as a Getter value. This implementation implements a `listGetter` struct that allows recursively evaluating list elements, which allows putting paths and invocations in lists.

**Link to tracking Issue:**

Fixes https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/16320

**Testing:**

Added unit tests to check for this functionality at multiple levels.

**Documentation:**

The existing docs should cover this functionality.

### CODE REVIEW

**Comment by evan-bradley** [comment]
@TylerHelmuth This implementation is different than what we discussed, but will allow for using paths and invocations in lists. The downside is that the lists can be probably unnecessarily complicated, and we can't easily enforce that they are homogeneous, which is required by the specification for Attribute values. There are other places in the OTTL where users can cut themselves, so this seemed like an acceptable tradeoff.

**Comment by TylerHelmuth** [comment]
> we can't easily enforce that they are homogeneous, which is required by the specification for Attribute values

@evan-bradley I wasn't aware that array values for an attribute had to be homogenous.  I was checking the spec earlier for something I was working on and [this section](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/common/attribute-type-mapping.md#array-values) reads to me like arrays can be a mix of values.

**Comment by TylerHelmuth** [comment]
> will allow for using paths and invocations in lists

This is definitely needed, good catch.

File: pkg/ottl/contexts/internal/ottlcommon/value.go [hunk 1]
```diff
@@ -85,6 +85,15 @@ func SetValue(value pcommon.Value, val interface{}) {
 		for _, b := range v {
 			value.Slice().AppendEmpty().SetEmptyBytes().FromRaw(b)
 		}
+	case []any:
+		value.Slice().RemoveIf(func(_ pcommon.Value) bool {
+			return true
+		})
```
Comment (TylerHelmuth) [inline pkg/ottl/contexts/internal/ottlcommon/value.go:91]: `value.SetEmptySlice()` can be used now instead of `RemoveIf` and `value.Slice()`.  I'd be ok updating the rest of the switch statement in this PR.

**Comment by evan-bradley** [comment]
> I wasn't aware that array values for an attribute had to be homogenous. I was checking the spec earlier for something I was working on and [this section](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/common/attribute-type-mapping.md#array-values) reads to me like arrays can be a mix of values.

When working on this, I found two places where the proto `AnyValue` was used:
- Attribute values that are arrays [are required to be homogeneous arrays](https://opentelemetry.io/docs/reference/specification/common/#attribute) by the specification. While OTLP does support heterogeneous arrays for attribute values, the API implementations will only accept and emit attribute values that are homogeneous arrays.
- Logs support [heterogeneous arrays in the body field](https://opentelemetry.io/docs/reference/specification/logs/data-model/#field-body) to support existing log models, but advises a string type for new implementations.

I would prefer that the Collector didn't intentionally emit any data in a format that would be disallowed for an OpenTelemetry language API, since it is likely for data that isn't spec-compliant to be handled inconsistently or simply dropped by backends. I don't think the Collector is technically bound to abide by the specification to that degree, so I don't think we are required to do anything in this case.

I think if we do decide to validate that attributes are only set to homogeneous arrays, we should probably do it in the contexts.

File: pkg/ottl/contexts/internal/ottlcommon/value.go (hunk 1 above)
Comment (evan-bradley) [reply pkg/ottl/contexts/internal/ottlcommon/value.go]: I like that much better. Done.

**Comment by TylerHelmuth** [comment]
Good info, thanks for pointing out those API requirements. I agree, we should follow the spec so we don't produce any invalid data. 

I agree that the contexts should be the enforcers. Within the contexts there are no Getters, just values, so it should be easy to check and enforce.

Can you open an issue to track this enforcement?

**Review by TylerHelmuth — APPROVED** [review]
LGTM

**Comment by evan-bradley** [comment]
> Can you open an issue to track this enforcement?

See https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/16355.

File: pkg/ottl/contexts/internal/ottlcommon/value.go [hunk 2]
```diff
@@ -51,40 +51,37 @@ func SetValue(value pcommon.Value, val interface{}) {
 	case []byte:
 		value.SetEmptyBytes().FromRaw(v)
 	case []string:
-		value.Slice().RemoveIf(func(_ pcommon.Value) bool {
-			return true
-		})
+		value.SetEmptySlice()
 		for _, str := range v {
 			value.Slice().AppendEmpty().SetStr(str)
 		}
```
Comment (bogdandrutu) [inline pkg/ottl/contexts/internal/ottlcommon/value.go:57]: Add a `value.Slice().EnsureCapacity(len(v))` same to all cases to reduce number of allocations.

Comment (evan-bradley) [reply pkg/ottl/contexts/internal/ottlcommon/value.go]: Good catch. Done.

**Review by bogdandrutu — APPROVED** [review]

**Comment by bogdandrutu** [comment]
Needs a rebase

**Review by TylerHelmuth — APPROVED** [review]
