### PR TITLE
[pkg/stanza] handle errors from Operator.Process

### LINKED ISSUE #33783: swallowed exception in Operator.Process
### Component(s)

pkg/stanza, pkg/stanza/fileconsumer

## Description

Some of the usages of https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/d78d7bb37d0c84da04ac8a83356eb669ecd75a95/pkg/stanza/operator/operator.go#L40 don't check for the error, which can lead to silent errors

### Real config

```yaml
      filelog/fraud-detection-raw:
        include:
          - /var/log/pods/*/*/*.log      
        operators:
        - id: container-parser
          type: container
```

Why?
- `include_file_path: true` is missing - but is required unless you set `add_metadata_from_filepath: false`
- exception: https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/6395ff8916f355d9a2c6d8e837e2e07dd6a4f14f/pkg/stanza/operator/parser/container/parser.go#L294

### Test

remove this line: https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/6395ff8916f355d9a2c6d8e837e2e07dd6a4f14f/pkg/stanza/operator/parser/container/parser_test.go#L246

## Expected Result

error is reported to user

## Actual Result

error is silent - you just don't get log messages

### Collector version

0.103.0

### Environment information

_No response_

### OpenTelemetry Collector configuration

_No response_

### Log output

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by zeitlinger**
**Link to tracking Issue:** Fixes https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/33783

**Testing:** 

nothing added

**Documentation:**

not applicable

### CODE REVIEW

**Comment by zeitlinger** [comment]
seems some tests expect some errors to be ignored

Test: https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/d78d7bb37d0c84da04ac8a83356eb669ecd75a95/pkg/stanza/fileconsumer/internal/header/reader_test.go#L75
Error that now shows: https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/5c7e342f93df62087a2f97b342f2f8f8ebda2b3b/pkg/stanza/operator/parser/keyvalue/parser.go#L31

File: pkg/stanza/adapter/benchmark_test.go [hunk 1]
```diff
@@ -6,6 +6,7 @@ package adapter
 import (
 	"context"
 	"fmt"
+	"go.uber.org/zap"
```
Comment (djaglowski) [inline pkg/stanza/adapter/benchmark_test.go:9]: This will have to be moved to the second group of imports in order to pass the linter

**Review by djaglowski — COMMENTED** [review]
Generally looks good to me

File: receiver/otlpjsonfilereceiver/README.md [hunk 2]
```diff
@@ -38,4 +38,4 @@ receivers:
       - "/var/log/*.log"
     exclude:
       - "/var/log/example.log"
-```
\ No newline at end of file
+```
```
Comment (ChrsMark) [inline receiver/otlpjsonfilereceiver/README.md:41]: Is this intentional?

File: pkg/stanza/operator/helper/writer.go [hunk 3]
```diff
@@ -47,14 +47,17 @@ type WriterOperator struct {
 }
 
 // Write will write an entry to the outputs of the operator.
-func (w *WriterOperator) Write(ctx context.Context, e *entry.Entry) {
-	for i, operator := range w.OutputOperators {
+func (w *WriterOperator) Write(ctx context.Context, e *entry.Entry) error {
```
Comment (ChrsMark) [inline pkg/stanza/operator/helper/writer.go:50]: I guess this'd require a changelog entry, most probably mentioned as a breaking (?) change, since that's a package exposed change: https://pkg.go.dev/github.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza@v0.104.0/operator/helper#WriterOperator.Write

**Comment by zeitlinger** [comment]
> seems some tests expect some errors to be ignored
> 
> Test:
> 
> https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/d78d7bb37d0c84da04ac8a83356eb669ecd75a95/pkg/stanza/fileconsumer/internal/header/reader_test.go#L75
> 
> 
> Error that now shows:
> https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/5c7e342f93df62087a2f97b342f2f8f8ebda2b3b/pkg/stanza/operator/parser/keyvalue/parser.go#L31

here's what I tried - but I'm not sure this is the right path - and it's not working

```
Subject: [PATCH] add example for using recombine in container operator
---
Index: pkg/stanza/operator/helper/parser.go
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/pkg/stanza/operator/helper/parser.go b/pkg/stanza/operator/helper/parser.go
--- a/pkg/stanza/operator/helper/parser.go	(revision d5550419676f27a422bb0d2f44e1667aec318a01)
+++ b/pkg/stanza/operator/helper/parser.go	(date 1720096829632)
@@ -91,6 +91,7 @@
 	SeverityParser  *SeverityParser
 	TraceParser     *TraceParser
 	ScopeNameParser *ScopeNameParser
+	IgnoreErrors    bool
 }
 
 // ProcessWith will run ParseWith on the entry, then forward the entry on to the next operators.
@@ -105,7 +106,7 @@
 		return p.HandleEntryError(ctx, entry, err)
 	}
 	if skip {
-		return p.Write(ctx, entry)
+		return p.write(ctx, entry)
 	}
 
 	if err = p.ParseWith(ctx, entry, parse); err != nil {
@@ -118,7 +119,15 @@
 		}
 	}
 
-	return p.Write(ctx, entry)
+	return p.write(ctx, entry)
+}
+
+func (p *ParserOperator) write(ctx context.Context, entry *entry.Entry) error {
+	err := p.Write(ctx, entry)
+	if p.IgnoreErrors {
+		return nil
+	}
+	return err
 }
 
 // ParseWith will process an entry's field with a parser function.
Index: pkg/stanza/fileconsumer/internal/header/config.go
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/pkg/stanza/fileconsumer/internal/header/config.go b/pkg/stanza/fileconsumer/internal/header/config.go
--- a/pkg/stanza/fileconsumer/internal/header/config.go	(revision d5550419676f27a422bb0d2f44e1667aec318a01)
+++ b/pkg/stanza/fileconsumer/internal/header/config.go	(date 1720096829384)
@@ -8,6 +8,7 @@
 	"bytes"
 	"errors"
 	"fmt"
+	"github.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza/operator/parser/keyvalue"
 	"regexp"
 
 	"go.opentelemetry.io/collector/component"
@@ -62,6 +63,11 @@
 		if op.Type() == "filter" {
 			return nil, fmt.Errorf("operator of type filter is not allowed in `metadata_operators`")
 		}
+
+		if op.Type() == "key_value_parser" {
+			parser, _ := op.(*keyvalue.Parser)
+			parser.IgnoreErrors = true
+		}
 	}
 
 	regex, err := regexp.Compile(matchRegex)
```

if we can't figure this out, then maybe the approach is wrong

File: receiver/otlpjsonfilereceiver/README.md (hunk 2 above)
Comment (zeitlinger) [reply receiver/otlpjsonfilereceiver/README.md:41]: no

**Review by djaglowski — APPROVED** [review]

**Review by ChrsMark — APPROVED** [review]
