### PR TITLE
`testbed`: increase limit for TestBallastMemory

### LINKED ISSUE #6535: TestBallastMemory randomly fails still, even with the old fix
**Describe the bug**
TestMemoryBallast fails.  The output of the test failure is meaningless as well.  It does not always fail, but I just saw one fail in a pull request because the functionality we wrote to "give it some leeway" said "I expected nothing higher than 88, the value was 89" and it failed the whole PR.

**Steps to reproduce**
If possible, provide a recipe for reproducing the error.
Just make a PR, run the testbed, it will eventually fail.
**What did you expect to see?**
A clear and concise description of what you expected to see.
I expect to see information on what we are really testing here, and what do the values mean.  Yes 89 is higher than 88, I sincerely doubt that thats a problem of memory usage.

We should probably look and test and see if Memory values are a deviation off after multiple runs of a piece of a code, right now it just seems like it give its it an extra 10% leeway.  That might hide real issues as well.  I'd like to discuss the test here a little bit, what it does, why its there and find a real solution to this issue.

If any test fails, it should be able to convey to me a path to resolution.  If a contributor saw the memory ballast was impacted by their changes and this test failed there is no detail on what one might do to go about remediating this. 
**What did you see instead?**
A clear and concise description of what you saw instead.
That some extra memory was being used for some reason, very little, but more than we expected
**What version did you use?**
Version: (e.g., `v0.4.0`, `1eb551b`, etc)
Any build
**What config did you use?**
Config: (e.g. the yaml config file)
Any
**Environment**
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")
Any
**Additional context**
Old issue here 
https://github.com/open-telemetry/opentelemetry-collector/issues/3233

### PR DESCRIPTION
**Pull request by jpkrohling**
This also improves the error message, making it clear that the usage is 10% higher than the max.

Fixes #6535

Signed-off-by: Juraci Paixão Kröhling <juraci@kroehling.de>

### CODE REVIEW

**Comment by jpkrohling** [comment]
@boostchicken, would you like to review this one?

File: testbed/tests/e2e_test.go [hunk 1]
```diff
@@ -84,43 +84,45 @@ func TestBallastMemory(t *testing.T) {
...
-		}, time.Second*2, fmt.Sprintf("VMS must be greater than %d", test.ballastSize))
-
-		// https://github.com/open-telemetry/opentelemetry-collector/issues/3233
-		// given that the maxRSS isn't an absolute maximum and that the actual maximum might be a bit off,
-		// we give some room here instead of failing when the memory usage isn't that much higher than the max
-		lenientMax := 1.1 * float32(test.maxRSS)
-		assert.LessOrEqual(t, float32(rss), lenientMax)
-		cleanup()
-		tc.Stop()
+		t.Run(fmt.Sprintf("ballast-size-%d", test.ballastSize), func(t *testing.T) {
```
Comment (jpkrohling) [inline testbed/tests/e2e_test.go:87]: Wrapping this in a `t.Run` should give the test a better name, stating which test in the matrix this is about.

File: testbed/tests/e2e_test.go [hunk 2]
```diff
@@ -84,43 +84,45 @@ func TestBallastMemory(t *testing.T) {
...
+			tc.WaitForN(func() bool {
+				rss, vms, _ = tc.AgentMemoryInfo()
+				return vms > test.ballastSize
+			}, time.Second*2, fmt.Sprintf("VMS must be greater than %d", test.ballastSize))
+
+			// https://github.com/open-telemetry/opentelemetry-collector/issues/3233
+			// given that the maxRSS isn't an absolute maximum and that the actual maximum might be a bit off,
+			// we give some room here instead of failing when the memory usage isn't that much higher than the max
+			lenientMax := 1.1 * float32(test.maxRSS)
+			assert.LessOrEqual(t, float32(rss), lenientMax, fmt.Sprintf("The RSS memory usage (%d) is >10%% higher than the limit (%d).", rss, test.maxRSS))
```
Comment (jpkrohling) [inline testbed/tests/e2e_test.go:123]: In theory, the parameters starting from the fourth position would be used in Sprintf, but it wasn't working:


```
    assertion_compare.go:342: 
        	Error Trace:	e2e_test.go:123
        	Error:      	"100" is not less than or equal to "99"
        	Test:       	TestBallastMemory/ballast-size-500
        	Messages:   	[The RSS memory usage (%d) is >10%% higher than the limit (%d). 83 90]
```

So, I'm doing the Sprintf manually here, which results in this:

```
=== RUN   TestBallastMemory/ballast-size-500
2021/12/10 11:21:28 Starting Agent (/home/jpkroehling/Projects/src/github.com/open-telemetry/opentelemetry-collector-contrib/bin/otelcontribcol_linux_amd64)
2021/12/10 11:21:28 Writing Agent log to /home/jpkroehling/Projects/src/github.com/open-telemetry/opentelemetry-collector-contrib/testbed/tests/results/TestBallastMemory/ballast-size-500/agent.log
2021/12/10 11:21:28 Agent running, pid=1049488
    assertion_compare.go:342: 
        	Error Trace:	e2e_test.go:123
        	Error:      	"100" is not less than or equal to "99"
        	Test:       	TestBallastMemory/ballast-size-500
        	Messages:   	[The RSS memory usage (100) is >10% higher than the limit (90).]
```

Comment (bogdandrutu) [reply testbed/tests/e2e_test.go:123]: Use `assert.LessOrEqual[F]`

Comment (jpkrohling) [reply testbed/tests/e2e_test.go:123]: I'm sure I'm doing something stupid, as I'm still not getting it right:

```golang
assert.LessOrEqualf(t, float32(100), lenientMax, "The RSS memory usage (%d) is >10%% higher than the limit (%d).", rss, test.maxRSS)
```

Yields this:

```
2021/12/10 20:17:17 Agent running, pid=1315703
    assertion_compare.go:342: 
                Error Trace:    e2e_test.go:123
                Error:          "100" is not less than or equal to "99"
                Test:           TestBallastMemory/ballast-size-500
                Messages:       [The RSS memory usage (%d) is >10%% higher than the limit (%d). 83 90]
```

Comment (jpkrohling) [reply testbed/tests/e2e_test.go:123]: I've just tried the example from their documentation, and it also doesn't work here:

```
assert.LessOrEqualf(t, 2, 1, "error message %s", "formatted")
```

Yields:
```
                Messages:       [error message %s formatted]
```

**Review by bogdandrutu — APPROVED** [review]
