### PR TITLE
[chore] Fix datadog receiver flakey test.

### LINKED ISSUE #23334: [receiver/datadog]Flaky test TestDefaultReceivers/datadog/lifecycle
Seen in https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/5249506268/jobs/9483727674?pr=23332

```
%v(0xc9a65a0,0x10ddf780)%v(0xc9a65a0,0x10ddf780)--- FAIL: TestDefaultReceivers (60.93s)
    --- FAIL: TestDefaultReceivers/datadog (0.00s)
        --- FAIL: TestDefaultReceivers/datadog/lifecycle (0.00s)
            receivers_test.go:[52](https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/5249506268/jobs/9483727674?pr=23332#step:9:53)3: 
                	Error Trace:	/home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/cmd/otelcontribcol/receivers_test.go:523
                	            				/home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/cmd/otelcontribcol/receivers_test.go:481
                	Error:      	Received unexpected error:
                	            	failed to create datadog listener: listen tcp 127.0.0.1:8126: bind: address already in use
                	Test:       	TestDefaultReceivers/datadog/lifecycle
FAIL
	github.com/open-telemetry/opentelemetry-collector-contrib/cmd/otelcontribcol	coverage: 44.8% of statements
FAIL	github.com/open-telemetry/opentelemetry-collector-contrib/cmd/otelcontribcol	229.4[59](https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/5249506268/jobs/9483727674?pr=23332#step:9:60)s
FAIL
make[2]: *** [../../Makefile.Common:103: test-with-cover] Error 1
make[1]: *** [Makefile:172: cmd/otelcontribcol] Error 2
make[2]: Leaving directory '/home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/cmd/otelcontribcol'
make: *** [Makefile:100: gotest-with-cover] Error 2
make[1]: Leaving directory '/home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib'
Error: Process completed with exit code 2.
```

### PR DESCRIPTION
**Pull request by MovieStoreGuy**
**Description:** 

It tries to bind to an already established port, this uses `:0` to use a randomly assigned port to keep the lifecycle checks

**Link to tracking Issue:** 

closes https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/23334

### CODE REVIEW

**Review by crobert-1 — APPROVED** [review]

File: cmd/otelcontribcol/receivers_test.go [hunk 1]
```diff
@@ -157,6 +158,11 @@ func TestDefaultReceivers(t *testing.T) {
 		},
 		{
 			receiver: "datadog",
+			getConfigFn: func() component.Config {
+				cfg := rcvrFactories["datadog"].CreateDefaultConfig().(*datadogreceiver.Config)
+				cfg.Endpoint = ":0" // Using a randomly assigned address
```
Comment (codeboten) [inline cmd/otelcontribcol/receivers_test.go:163]: nit: could this be `localhost:0` instead?

**Review by TylerHelmuth — APPROVED** [review]
