### PR TITLE
[receiver/kafkareceiver] try to fix flaky tests for franz-go consumer

### LINKED ISSUE #43022: [receiver/kafkareceiver]: Report for failed tests on main
Auto-generated report for `__run` job build.

Link to failed build: https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/18052028888
Commit: b355c1b

### Component(s)
receiver/kafkareceiver

#### Test Failures
-  `TestConsumerShutdownConsuming/BackOff_default_marking`
```
=== RUN   TestConsumerShutdownConsuming/BackOff_default_marking
    consumer_franz_test.go:220: 
        	Error Trace:	/home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/receiver/kafkareceiver/consumer_franz_test.go:220
        	            				/home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/receiver/kafkareceiver/consumer_franz_test.go:224
        	            				/home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/receiver/kafkareceiver/consumer_franz_test.go:235
        	Error:      	Not equal: 
        	            	expected: 4
        	            	actual  : 3
        	Test:       	TestConsumerShutdownConsuming/BackOff_default_marking
        	Messages:   	consume function processed calls mismatch
    consumer_franz_test.go:230: 
        	Error Trace:	/home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/receiver/kafkareceiver/consumer_franz_test.go:230
        	            				/home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/receiver/kafkareceiver/consumer_franz_test.go:235
        	Error:      	Not equal: 
        	            	expected: 4
        	            	actual  : 3
        	Test:       	TestConsumerShutdownConsuming/BackOff_default_marking
--- FAIL: TestConsumerShutdownConsuming/BackOff_default_marking (0.04s)

```
-  `TestConsumerShutdownConsuming`
```
=== RUN   TestConsumerShutdownConsuming
--- FAIL: TestConsumerShutdownConsuming (0.32s)

```

**Note**: Information about any subsequent build failures that happen while
this issue is open, will be added as comments with more information to this issue.

### PR DESCRIPTION
**Pull request by paulojmdias**
#### Description

Tentative fix for the flaky CI tests on TestConsumerShutdownConsuming.
The failures were showing up as `expected=4, actual=3`, which seems tied to timing in slower CI runners. This PR adds a small wait to ensure the expected number of messages is processed before shutting down the consumer.

#### Link to tracking issue
Fixes #43022

### CODE REVIEW

File: receiver/kafkareceiver/consumer_franz_test.go [hunk 1]
```diff
@@ -208,6 +208,11 @@ func TestConsumerShutdownConsuming(t *testing.T) {
 			}, 10*time.Second, 10*time.Millisecond)
 			require.NoError(tb, kafkaClient.ProduceSync(ctx, rs...).FirstErr())
 
+			// Give the consumer a brief moment to poll both records into the same batch.
+			// Without this, on slower CI, one record can land in a later poll,
+			// which gets cut off by Shutdown → called==3 instead of 4.
+			time.Sleep(100 * time.Millisecond)
```
Comment (VihasMakwana) [inline receiver/kafkareceiver/consumer_franz_test.go]: This looks good, but alternatively, we use `require.EventuallyWithT(..)`. wdyt?

Comment (paulojmdias) [reply receiver/kafkareceiver/consumer_franz_test.go]: It should be more accurate than a `time.Sleep` for sure. PTAL in my last [commit](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/43083/commits/ddf83aabed30afc4531349b1e860e79bac2b0580) and let me know WDYT.

**Review by VihasMakwana — APPROVED** [review]

**Review by atoulme — APPROVED** [review]
