### PR TITLE
[extension/text_encoding] Avoid spurious marshalling separators at end of lines

### LINKED ISSUE #42797: [extension/encoding/textencoding] Marshaling and Unmarshaling Separator configurations are ignored by the extension
### Component(s)

extension/encoding/textencoding

## Description

The `text_encoding` extension exposes configuration options for `marshaling_separator` and `unmarshaling_separator`. However, these settings do not appear to affect the exported output when used in combination with the `fileexporter`.

On reviewing the implementation in `extension/encoding/textencodingextension/extension.go`, it seems that the configured values for `marshaling_separator` and `unmarshaling_separator` are never applied when creating the `textLogCodec` instance. As a result, the `marshaling_separator` always defaults to an empty string, regardless of the user-provided configuration.

In addition, the current logic in `MarshalLogs()` (`extension/encoding/textencodingextension/text.go`) appends the separator after every log record. This behavior introduces trailing separators (e.g., empty lines when `marshaling_separator="\n"`) instead of joining records in the same way as a standard delimiter would (e.g., `"\n".join(records)`).

## Steps to Reproduce

1. Configure a `filelog` receiver to read logs from a file.
2. Configure a `fileexporter` with `text_encoding` and set `marshaling_separator` to `"\n"`.
3. Observe the exported log file.

## Expected Result

The following should be the expected log output written by `fileexporter`.

```console
<ip_address> - - [19/Sep/2025:10:04:06 +0000] "POST /api/v1/service/log HTTP/1.1" 200 13 "-" "LuaSocket 3.0.0"
<ip_address> - - [19/Sep/2025:10:04:06 +0000] "POST /api/v1/service/log HTTP/1.1" 200 13 "-" "LuaSocket 3.0.0"
<ip_address> - - [19/Sep/2025:10:04:06 +0000] "POST /api/v1/service/log HTTP/1.1" 200 13 "-" "LuaSocket 3.0.0"
<ip_address> - - [19/Sep/2025:10:04:06 +0000] "POST /api/v1/service/log HTTP/1.1" 200 13 "-" "LuaSocket 3.0.0"
<ip_address> - - [19/Sep/2025:10:04:06 +0000] "POST /api/v1/service/log HTTP/1.1" 200 13 "-" "LuaSocket 3.0.0"
<ip_address> - - [19/Sep/2025:10:04:07 +0000] "POST /api/v1/service/log HTTP/1.1" 200 13 "-" "LuaSocket 3.0.0"
<ip_address> - - [19/Sep/2025:10:04:07 +0000] "POST /api/v1/service/log HTTP/1.1" 200 13 "-" "LuaSocket 3.0.0"
<ip_address> - - [19/Sep/2025:10:04:07 +0000] "POST /api/v1/service/log HTTP/1.1" 200 13 "-" "LuaSocket 3.0.0"
<ip_address> - - [19/Sep/2025:10:04:07 +0000] "POST /api/v1/service/log HTTP/1.1" 200 13 "-" "LuaSocket 3.0.0"
<ip_address> - - [19/Sep/2025:10:04:07 +0000] "POST /api/v1/service/log HTTP/1.1" 200 13 "-" "LuaSocket 3.0.0"
<ip_address> - - [19/Sep/2025:10:04:07 +0000] "POST /api/v1/service/log HTTP/1.1" 200 13 "-" "LuaSocket 3.0.0"
<ip_address> - - [19/Sep/2025:10:04:07 +0000] "POST /api/v1/service/log HTTP/1.1" 200 13 "-" "LuaSocket 3.0.0"
```

## Actual Result

1. Configured `marshaling_separator` value is ignored resulting in log lines within a `ResourceLog` getting concatenated together.

  ```console
  <ip_address> - - [19/Sep/2025:10:04:06 +0000] "POST /api/v1/service/log HTTP/1.1" 200 13 "-" "LuaSocket 3.0.0"<ip_address> - - [19/Sep/2025:10:04:06 +0000] "POST /api/v1/service/log HTTP/1.1" 200 13 "-" "LuaSocket 3.0.0"
  <ip_address> - - [19/Sep/2025:10:04:06 +0000] "POST /api/v1/service/log HTTP/1.1" 200 13 "-" "LuaSocket 3.0.0"
  <ip_address> - - [19/Sep/2025:10:04:06 +0000] "POST /api/v1/service/log HTTP/1.1" 200 13 "-" "LuaSocket 3.0.0"<ip_address> - - [19/Sep/2025:10:04:06 +0000] "POST /api/v1/service/log HTTP/1.1" 200 13 "-" "LuaSocket 3.0.0"
  <ip_address> - - [19/Sep/2025:10:04:07 +0000] "POST /api/v1/service/log HTTP/1.1" 200 13 "-" "LuaSocket 3.0.0"
  <ip_address> - - [19/Sep/2025:10:04:07 +0000] "POST /api/v1/service/log HTTP/1.1" 200 13 "-" "LuaSocket 3.0.0"
  <ip_address> - - [19/Sep/2025:10:04:07 +0000] "POST /api/v1/service/log HTTP/1.1" 200 13 "-" "LuaSocket 3.0.0"<ip_address> - - [19/Sep/2025:10:04:07 +0000] "POST /api/v1/service/log HTTP/1.1" 200 13 "-" "LuaSocket 3.0.0"
  <ip_address> - - [19/Sep/2025:10:04:07 +0000] "POST /api/v1/service/log HTTP/1.1" 200 13 "-" "LuaSocket 3.0.0"<ip_address> - - [19/Sep/2025:10:04:07 +0000] "POST /api/v1/service/log HTTP/1.1" 200 13 "-" "LuaSocket 3.0.0"
  <ip_address> - - [19/Sep/2025:10:04:07 +0000] "POST /api/v1/service/log HTTP/1.1" 200 13 "-" "LuaSocket 3.0.0"
  ```

2. When configured properly, the separator is appended after each record, resulting in extra blank lines in the output when using newline separator for marshaling.

```console
<ip_address> - - [19/Sep/2025:10:04:07 +0000] "POST /api/v1/service/log HTTP/1.1" 200 13 "-" "LuaSocket 3.0.0"
<ip_address> - - [19/Sep/2025:10:04:07 +0000] "POST /api/v1/service/log HTTP/1.1" 200 13 "-" "LuaSocket 3.0.0"

<ip_address> - - [19/Sep/2025:10:04:07 +0000] "POST /api/v1/service/log HTTP/1.1" 200 13 "-" "LuaSocket 3.0.0"

<ip_address> - - [19/Sep/2025:10:04:07 +0000] "POST /api/v1/service/log HTTP/1.1" 200 13 "-" "LuaSocket 3.0.0"
<ip_address> - - [19/Sep/2025:10:04:07 +0000] "POST /api/v1/service/log HTTP/1.1" 200 13 "-" "LuaSocket 3.0.0"
<ip_address> - - [19/Sep/2025:10:04:07 +0000] "POST /api/v1/service/log HTTP/1.1" 200 13 "-" "LuaSocket 3.0.0"

<ip_address> - - [19/Sep/2025:10:04:07 +0000] "POST /api/v1/service/log HTTP/1.1" 200 13 "-" "LuaSocket 3.0.0"
...
```

### Collector version

0.135.0

## Environment

OS: Debian 11

### OpenTelemetry Collector configuration

```yaml
# Sample Otelcol configs

receivers:
  filelog:
    include:
      - /var/log/nginx/access.log
    start_at: end
    include_file_path: true
    include_file_name: false

    resource:
      environment: development
      component: nginx

    operators:
      - type: move
        from: attributes["log.file.path"]
        to: resource["path"]
      - type: add
        field: resource.log_path
        value: EXPR(join([resource.environment,resource.component], "-") + resource.path)

processors:
  batch:
    send_batch_size: 8192
    timeout: 200ms
    send_batch_max_size: 0

  memory_limiter:
    check_interval: 5s
    limit_percentage: 75
    spike_limit_percentage: 10

exporters:
  file:
    path: /var/log/otelcol/*.log
    rotation:
      max_megabytes: 5000
      max_days: 7
      max_backups: 4
      localtime: false
    encoding: text_encoding/utf8
    group_by:
      enabled: true
      resource_attribute: log_path

extensions:
  text_encoding/utf8:
    encoding: utf8
    marshaling_separator: "\n"

service:
  extensions: [text_encoding/utf8]
  pipelines:
    logs:
      receivers: [filelog]
      processors: [memory_limiter,batch]
      exporters: [file]
```

### Log output

```shell

```

### Additional context

Only checked the `MarshalLogs()` logic. The logic used in `UnmarshalLogs()` was not checked for correctness. 

### Tip

<sub>[React](https://github.blog/news-insights/product-news/add-reactions-to-pull-requests-issues-and-comments/) with 👍 to help prioritize this issue. Please use comments to provide useful context, avoiding `+1` or `me too`, to help us triage it. Learn more [here](https://opentelemetry.io/community/end-user/issue-participation/).</sub>

### PR DESCRIPTION
**Pull request by jon-signal**
As a companion to #45272, this partially fixes #42797 by avoiding spurious newlines between blocks of log records. This change modifies existing unit tests to demonstrate the new behavior.

Since tests already existed for this behavior, I recognize that the existing behavior may already be working as intended. Even so, I offer this in the spirit of fully addressing the concerns raise in #42797.

### CODE REVIEW

**Comment by jon-signal** [comment]
Friends, I signed the CLA for #45272; do I need to sign it for each individual pull request I open, or is this just a case of the automated check not noticing that I've signed?

**Comment by atoulme** [comment]
> Friends, I signed the CLA for #45272; do I need to sign it for each individual pull request I open, or is this just a case of the automated check not noticing that I've signed?

you need to check the email you used on both commits. The tool checks your email against its database.

File: extension/encoding/textencodingextension/text.go [hunk 1]
```diff
@@ -69,8 +69,10 @@ func (r *textLogCodec) MarshalLogs(ld plog.Logs) ([]byte, error) {
 			sl := rl.ScopeLogs().At(j)
 			for k := 0; k < sl.LogRecords().Len(); k++ {
 				lr := sl.LogRecords().At(k)
+				if i+j+k > 0 {
+					b = append(b, []byte(r.marshalingSeparator)...)
+				}
```
Comment (atoulme) [inline extension/encoding/textencodingextension/text.go:76]: what does that logic do?

**Comment by jon-signal** [comment]
> you need to check the email you used on both commits. The tool checks your email against its database.

Understood. Both commits have the same email, though. Is there a way to ask the CLA tool to… just check again? I'll try to close and re-open this to see if that helps (with apologies for the noise!).

**Comment by jon-signal** [comment]
> I'll try to close and re-open this to see if that helps (with apologies for the noise!).

…and that did the trick!

File: extension/encoding/textencodingextension/text.go (hunk 1 above)
Comment (jon-signal) [reply extension/encoding/textencodingextension/text.go:76]: So before, we were unconditionally appending the separator after each log entry. Now we _prepend_ the separator if we're on any log entry other than the very first one.

Comment (jon-signal) [reply extension/encoding/textencodingextension/text.go:76]: Elaborating on `i+j+k` specifically: `ld` may contain multiple `ResourceLogs` (`i`), each of which may contain multiple `ScopeLogs` (`j`), each of which may contain multiple `LogRecords` (`k`). In the of `TestTextRoundtrip`, for example, we have two `ResourceLogs`, each of which has a single `ScopeLogs` value, and each of _those_ has a single value in `LogRecords`.

Though now that I've written this out, I can see an edge case. I guess it's _technically_ possible that for `i = j = 0`, we won't have any `LogRecords` at all. On the next loop, we'll have `i+j+k` greater than zero even though we haven't actually written anything. I think the more correct (and honestly clearer) thing to do is to just have a "have we appended any log entries?" variable to track state. I'll do that now.

Comment (jon-signal) [reply extension/encoding/textencodingextension/text.go:76]: …and done.

Comment (atoulme) [reply extension/encoding/textencodingextension/text.go:76]: ok thanks for clarifying.

**Review by atoulme — APPROVED** [review]
