### PR TITLE
fix(telemetrygen): startTimestamp when temporality is cumulative

### LINKED ISSUE #38232: [cmd/telemetrygen] Use same StartTimestamp for cumulative temporality in metrics pipeline
### Component(s)

_No response_

### What happened?

**Describe the bug**

While implementing the `delta` temporality for metrics pipeline in `telemeterygen`, based on the request from issue  #38073, we identified that the current cumulative temporality implementation is not following the official [documentation](https://opentelemetry.io/docs/specs/otel/metrics/data-model/#temporality) of cumulative temporality. More specifically the  `StartTimestamp` is different for each datapoint that is generated.

[Relevant discussion.](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/38073#issuecomment-2679654299)

**Steps to reproduce**
- Collector setup with `otlp` receiver and `debug`  exporter
- Generate `Sum` metric by running: `telemetrygen metrics --duration 2s  --otlp-insecure --metric-type Sum`

**What did you expect to see?**

From the documentation:

> Cumulative temporality means that successive data points repeat the starting timestamp. For example, from start time T0, cumulative data points cover time ranges (T0, T1], (T0, T2], (T0, T3], and so on.

**What did you see instead?**

Each Datapoint has a different `StartTimetamp`. Example below.

```
StartTimestamp: 2025-02-25 21:09:28.313305 +0000 UTC
Timestamp: 2025-02-25 21:09:29.313305 +0000 UTC
Value: 6184
ResourceMetrics open-telemetry/opentelemetry-collector#333
Resource SchemaURL: https://opentelemetry.io/schemas/1.13.0
Resource attributes:
     -> service.name: Str(telemetrygen)
ScopeMetrics #0
ScopeMetrics SchemaURL: 
InstrumentationScope  
Metric #0
Descriptor:
     -> Name: gen
     -> Description: 
     -> Unit: 
     -> DataType: Sum
     -> IsMonotonic: true
     -> AggregationTemporality: Cumulative
NumberDataPoints #0
StartTimestamp: 2025-02-25 21:09:28.313655 +0000 UTC
Timestamp: 2025-02-25 21:09:29.313655 +0000 UTC
Value: 6185
ResourceMetrics open-telemetry/opentelemetry-collector#334
Resource SchemaURL: https://opentelemetry.io/schemas/1.13.0
Resource attributes:
     -> service.name: Str(telemetrygen)
ScopeMetrics #0
ScopeMetrics SchemaURL: 
InstrumentationScope  
Metric #0
Descriptor:
     -> Name: gen
     -> Description: 
     -> Unit: 
     -> DataType: Sum
     -> IsMonotonic: true
     -> AggregationTemporality: Cumulative
NumberDataPoints #0
StartTimestamp: 2025-02-25 21:09:28.313941 +0000 UTC
Timestamp: 2025-02-25 21:09:29.313941 +0000 UTC
```

### Collector version

0.120.0

## Environment
OS: (e.g., "MacOs 24.3.0 Darwin Kernel Version 24.3.0 )

### OpenTelemetry Collector configuration

```yaml
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:

exporters:
  debug:
    verbosity: detailed
  prometheus:
    endpoint: 0.0.0.0:8889

extensions:
  health_check:
  pprof:
  zpages:

service:
  extensions: [health_check, pprof, zpages]
  telemetry:
    metrics:
      level: detailed # Enables the most verbose metrics
      readers:
        - pull:
            exporter:
              prometheus:
                host: "0.0.0.0"
                port: 8888
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug, prometheus]
```

### Log output

```shell

```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by NickAnge**
#### Link to tracking issue
Fixes #38232

#### Testing

Locally Testing with a collector + logs

## Cumulative - default

Screenshot 2025-03-27 at 19 50 54

## Delta 

Screenshot 2025-03-27 at 19 58 52

### CODE REVIEW

File: cmd/telemetrygen/pkg/metrics/worker_test.go [hunk 1]
```diff
@@ -5,15 +5,20 @@ package metrics
 
 import (
 	"context"
+	"sync"
 	"testing"
 	"time"
```
Comment (atoulme) [inline cmd/telemetrygen/pkg/metrics/worker_test.go:11]:
```suggestion
```

File: cmd/telemetrygen/pkg/metrics/worker_test.go [hunk 2]
```diff
@@ -5,15 +5,19 @@ package metrics
...
+	"sync/atomic"
```
Comment (atoulme) [inline cmd/telemetrygen/pkg/metrics/worker_test.go:11]:
```suggestion
	"sync/atomic"
	"testing"
	"time"
```

**Comment by atoulme** [comment]
This looks like a good fix. I have fixed up the imports. Would you please add a changelog entry using `make chlog-new` in the root of your checkout?

**Review by codeboten — COMMENTED** [review]
Thanks @NickAnge! Please add changelog as mentioned by @atoulme, here's the details https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/CONTRIBUTING.md#adding-a-changelog-entry

**Comment by NickAnge** [comment]
hmm, I am not sure why the tests are failing to be honest 🤔 I run the action locally and also tests and they succeed. Could be transient ? Can we re-trigger the action ?
Screenshot 2025-03-29 at 17 10 00

**Comment by NickAnge** [comment]
Thanks @codeboten for the rebase. Can we merge it ?
Let me know if anything else is needed

**Review by atoulme — APPROVED** [review]
