### PR TITLE
[receiver/kafka]: deprecate built-in azure_resource_logs unmarshaler, redirect users to azure encoding extension

### LINKED ISSUE #46267: e kafkareceiver: encoding=azure_resource_logs drops Azure Functions logs when timestamp is in US format (MM/DD/YYYY HH:MM:SS[.mmm])
### Component(s)

pkg/translator/azure

## Description
hen consuming Azure Diagnostic Settings → Event Hubs (Kafka endpoint) with the Kafka receiver using encoding: azure_resource_logs, Azure Functions logs that carry a US‑format timestamp (e.g., 02/20/2026 14:54:26) are dropped before processors run. The decoder appears to accept only ISO/RFC3339 and has no configuration to accept alternate time formats on the Kafka path. This behavior is also reported by others for Functions logs.

- Kafka receiver encodings include azure_resource_logs (logs‑only) and json, but there’s no time_formats knob for azure_resource_logs on the Kafka receiver.
- Azure translator code path is in pkg/translator/azurelogs/resourcelogs_to_logs.go. It parses time and maps fields like event.name, operation.name, result.type etc. (and currently fails for US‑format Functions timestamps).

## Steps to Reproduce
  kafka/${ g }:
    brokers: ["${cfg.broker_name}"]
    topic:    "${cfg.topic}"
    group_id: "${cfg.consumer_group}"
    protocol_version: "2.1.0"
    encoding: "${cfg.encoding}"
    auth:
      tls:
        insecure_skip_verify: false
      sasl:
        mechanism: PLAIN
        username: "$ConnectionString"
        password: "${cfg.conn_string}"

## Expected Result
All Azure Functions diagnostic logs are decoded and passed to processors/exporters.
Timestamp parser should accept the US format that Functions emits in some plans, or at least expose a configuration to specify accepted time formats on this path. Prior reports indicate Functions timestamps vary by SKU/plan and can legitimately be US format.

## Actual Result
- The decoder drops the record (before processors) when the timestamp is like 02/20/2026 14:54:26[.mmm].
- Collector logs show (representative) messages similar to “Unable to convert timestamp from log” and the accepted counter in otelcol_receiver_accepted_log_records{receiver="kafka/diag"} stays at 0 for those records.

### Collector version

0.135.0

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

### OpenTelemetry Collector configuration

```yaml
service:
  telemetry:
    resource:
      service.instance.id: "$${env:CONTAINER_APP_REPLICA_NAME}"
      collector.id: "$${env:CONTAINER_APP_NAME}.${config_version}"
      collector.role: "infra"
      cloud.resource.name: "${workload_name}"
      cloud.platform: "azure.container_apps"
    metrics:
      level: ${ verbosity }
      readers:
        - periodic:
              exporter:
                otlp:
                  protocol: http/protobuf
                  endpoint: http://localhost:4318
    logs:
      level: "${ log_level }"
      encoding: "json"
  extensions: [health_check]
  pipelines:
    metrics:
      receivers: [otlp, prometheus]
      processors: [batch]
      exporters: [%{if log_level == "DEBUG"}debug, %{endif}forward]
    #%{ if traces_enabled }
    traces:
      receivers: [otlp%{ for g,_ in traces_kafka_configs }, kafka/${g}%{ endfor }]
      processors: [batch]
      exporters: [%{ if log_level == "DEBUG"}debug, %{ endif}forward]
    #%{ endif }

    logs:
      receivers: [otlp%{ for g,_ in eh_configs }, kafka/${g}%{ endfor }]
      processors: [batch, transform]
      exporters: [%{if log_level == "DEBUG"}debug, %{endif}forward ]

    # Dynatrace Pipelines
    #%{ if traces_enabled }
    traces/default:
      receivers: [forward]
      processors: [batch, attributes/insert]
      exporters: [${ central_otlp_exporter_id }]
    #%{ endif }
    metrics/default:
      receivers: [forward]
      processors: [batch, attributes/insert, cumulativetodelta]
      exporters: [${ central_otlp_exporter_id }]
    logs/default:
      receivers: [forward]
      processors: [batch, attributes/insert]
      exporters: [${ central_otlp_exporter_id }]

extensions:
  health_check:
    endpoint: "0.0.0.0:13133"
    path: "/health"

receivers:
  prometheus:
    config:
      scrape_configs:
        - job_name: "otel"
          scrape_interval: 60s
          static_configs:
            - targets: ["127.0.0.1:8888"]
          relabel_configs:
            # ADD FILTERING!
            # Processing post-scraping
            - target_label: prom_scrape_jobname
              replacement: otel-aca
        # NOTE: FURTHER SCRAPE CONFIGS ARE INCLUDED
        # AUTOMATICALLY BY MERGING SUPPLEMENTARY YAML CONFIG FILES
  otlp:
    protocols:
      http:
        endpoint: 127.0.0.1:4318
      grpc:
        endpoint: 127.0.0.1:4317

  #%{ for g, cfg in eh_configs} for g in eh_consumer_group, loop evh=${g}
  kafka/${ g }:
    brokers: ["${cfg.broker_name}"]
    topic:    "${cfg.topic}"
    group_id: "${cfg.consumer_group}"
    protocol_version: "2.1.0"
    encoding: "${cfg.encoding}"
    auth:
      tls:
        insecure_skip_verify: false
      sasl:
        mechanism: PLAIN
        username: "$ConnectionString"
        password: "${cfg.conn_string}"
  # %{ endfor }end_for
  # Only when infra traces enabled & kafka-mode
  # %{ if traces_enabled }
  # %{ for g, cfg in traces_kafka_configs} for g in eh_consumer_group, loop evh=${g}
  kafka/${ g }:
    brokers: ["${cfg.broker_name}"]
    topic:    "${cfg.topic}"
    group_id: "${cfg.consumer_group}"
    protocol_version: "2.1.0"
    encoding: "${cfg.encoding}"
    auth:
      tls:
        insecure_skip_verify: false
      sasl:
        mechanism: PLAIN
        username: "$ConnectionString"
        password: "${cfg.conn_string}"
  # %{ endfor }end_for
  # %{ endif }

connectors:
  forward:

processors:
  # Dynatrace requirement, to enable the currently supported compatibility modes
  cumulativetodelta:

  batch:
    send_batch_size: 100
    send_batch_max_size: 1000
    timeout: 40s

  transform:
    error_mode: ignore
    log_statements:
      - context: log
        # Also, the attributes are limited to 100 with 4096 characters
        statements:
          - truncate_all(attributes, 4096)
          - limit(attributes, 100, [])

  # Insert attributes
  attributes/insert:
    ## Add default dimensions to all the signals
    actions:
      # loop for k, v in labels:
      # %{ for k, v in labels }k=${k}, v=${v}
      - action: insert
        key: ${ k }
        value: ${ v }
      # %{endfor }end_for
      - key: collector.id
        value: "$${env:CONTAINER_APP_NAME}.${config_version}"
        action: insert
  # TODO: Keep this one for a later implementation on traces?
  #probabilistic_sampler:
  #  hash_seed: 22
  #  # 100 keeps all logs, 0 rejects all logs.
  #  sampling_percentage: 25 # we keep 25% of the signals / we drop 75% of them
  #  from_attribute: loglevel
  #  attribute_source: record
  #  sampling priority: DEBUG


exporters:
  # %{if log_level == "DEBUG" }if DEBUG is enabled, add debug exporter.
  debug:
    # 'debug' replaces deprecated 'logging'
    # full doc: https://github.com/open-telemetry/opentelemetry-collector/tree/main/exporter/debugexporter
    verbosity: ${verbosity}
    sampling_initial: 5
    sampling_thereafter: 200
  # endif%{endif}
  # TODO: make sure to use the right protocol depending on the var.gateway_collector.ingress.protocol
  ${ central_otlp_exporter_id }:
    endpoint: ${ aca_grpc_gateway }
```

### Log output

```shell

```

### Additional context

_No response_

### Tip

<sub>[React](https://github.blog/news-insights/product-news/add-reactions-to-pull-requests-issues-and-comments/) with 👍 to help prioritize this issue. Please use comments to provide useful context, avoiding `+1` or `me too`, to help us triage it. Learn more [here](https://opentelemetry.io/community/end-user/issue-participation/).</sub>

### PR DESCRIPTION
**Pull request by 57Ajay**
Fixes #46267

## Description

Following discussion with @axw, the preferred path for this issue is to deprecate the built-in `azure_resource_logs` encoding in the Kafka receiver (tracked for removal in #39113) and direct users to the [`azureencodingextension`](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/extension/encoding/azureencodingextension), which provides full control over time formats and is actively maintained.

This PR makes two changes:

1. **Deprecation notice in README** — marks `azure_resource_logs` as deprecated since v0.147.0 with a link to `azureencodingextension`.
2. **Runtime warning** — logs a `Warn`-level message at startup when `azure_resource_logs` is configured, so users are notified even if they haven't read the docs.

## Tests

Added `TestAzureResourceLogsDeprecationWarning` which uses an observed logger to assert that exactly one warning is emitted containing `"azure_resource_logs"` when the encoding is constructed.

### CODE REVIEW

File: receiver/kafkareceiver/encoding.go [hunk 1]
```diff
@@ -74,8 +74,9 @@ func newLogsUnmarshaler(encoding string, set receiver.Settings, host component.H
 		return unmarshaler.JSONLogsUnmarshaler{}, nil
 	case "azure_resource_logs":
 		return &azure.ResourceLogsUnmarshaler{
-			Version: set.BuildInfo.Version,
-			Logger:  set.Logger,
+			Version:     set.BuildInfo.Version,
+			Logger:      set.Logger,
+			TimeFormats: azure.DefaultTimeFormats(),
```
Comment (MovieStoreGuy) [inline receiver/kafkareceiver/encoding.go]: This should call a `New` method instead of directly setting the fields on the struct to avoid potentially missing this in future.

Comment (57Ajay) [reply receiver/kafkareceiver/encoding.go]: already reverting changes so all this will be removed, will add deprecation notice for azure_resource_logs in the README pointing users to azureencodingextension.

**Review by axw — COMMENTED** [review]
Thanks @57Ajay! I think we should also log a warning message when the receiver starts if `azure_resource_logs` is used. Can you please add that?

**Review by cparkins — APPROVED** [review]

**Comment by axw** [comment]
@57Ajay sorry, we'll need to hold off until the azure encoding is alpha: https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/46267#issuecomment-4037168742

I'll try to make that happen for the next release.

File: receiver/kafkareceiver/README.md [hunk 2]
```diff
@@ -170,7 +170,7 @@ Available only for logs:
 - `raw`: the payload's bytes are inserted as the body of a log record.
 - `text`: the payload are decoded as text and inserted as the body of a log record. By default, it uses UTF-8 to decode. You can use `text_<ENCODING>`, like `text_utf-8`, `text_shift_jis`, etc., to customize this behavior.
 - `json`: the payload is decoded as JSON and inserted as the body of a log record.
-- `azure_resource_logs`: the payload is converted from Azure Resource Logs format to OTel format.
+- `azure_resource_logs` (Deprecated [v0.147.0]: use [`azureencodingextension`](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/extension/encoding/azureencodingextension)): the payload is converted from Azure Resource Logs format to OTel format.
```
Comment (axw) [inline receiver/kafkareceiver/README.md]:
```suggestion
- `azure_resource_logs` (Deprecated [v0.149.0]: use [`azureencodingextension`](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/extension/encoding/azureencodingextension)): the payload is converted from Azure Resource Logs format to OTel format.
```

The extension will be included in v0.148.0 as alpha. The v0.148.0 release is in progress, so the deprecation change will need to go into the following release.

**Review by axw — COMMENTED** [review]
LGTM, just need a change on the deprecation notice

**Review by axw — APPROVED** [review]
Thanks @57Ajay!

**Review by paulojmdias — APPROVED** [review]
