### PR TITLE
[mdatagen] add `unsupported_platforms` support and enable several components

### LINKED ISSUE #30561: [receiver/podman] lifecycle test failure on windows
### Component(s)

receiver/podman

### Describe the issue you're reporting

This is currently breaking tests in main:

```
--- FAIL: TestComponentLifecycle (0.00s)
    --- FAIL: TestComponentLifecycle/metrics-shutdown (0.00s)
        generated_component_test.go:67: 
            	Error Trace:	D:/a/opentelemetry-collector-contrib/opentelemetry-collector-contrib/receiver/podmanreceiver/generated_component_test.go:67
            	Error:      	Received unexpected error:
            	            	podman receiver is not supported on windows
            	Test:       	TestComponentLifecycle/metrics-shutdown
FAIL
FAIL	github.com/open-telemetry/opentelemetry-collector-contrib/receiver/podmanreceiver	0.061s
FAIL
```

See https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/7532146479/job/20502194154 for full logs

### PR DESCRIPTION
**Pull request by fatsheep9146**
**Description:** <Describe what has changed.>
Add `supported_platforms` to enable components to describe which platforms are supported, meanwhile this configuration can also be used to generate the liftcycle test to skip windows when the component does not support windows.

**Link to tracking Issue:** <Issue number if applicable>
fix #30561

**Testing:** <Describe what testing was performed and which tests were added.>

**Documentation:** <Describe the documentation added.>

### CODE REVIEW

File: testbed/testbed/child_process_collector.go [hunk 1]
```diff
@@ -227,6 +220,13 @@ func (cp *childProcessCollector) Start(params StartParams) error {
 		cp.cmd.Env = append(cp.cmd.Env, fmt.Sprintf("%s=%s", k, cp.additionalEnv[k]))
 	}
 
+	// Prepare log file
+	logFile, err := os.Create(params.LogFilePath)
+	if err != nil {
+		return fmt.Errorf("cannot create %s: %w", params.LogFilePath, err)
+	}
+	log.Printf("Writing %s log to %s", cp.name, params.LogFilePath)
+
```
Comment (dmitryax) [inline testbed/testbed/child_process_collector.go:229]: Why is this changed?

File: cmd/mdatagen/main.go [hunk 2]
```diff
@@ -320,6 +320,17 @@ func templatize(tmplFile string, md metadata) *template.Template {
...
+					if len(md.Status.SupportedPlatforms) == 0 {
+						return true
+					}
+					for _, platform := range md.Status.SupportedPlatforms {
+						if platform == "windows" {
+							return true
+						}
+					}
+					return false
+				},
```
Comment (dmitryax) [inline cmd/mdatagen/main.go:333]: This is a too specific a solution for our use case. Let's start with `unsupported_platforms` option in metadata.yaml and just list them in `go:build` pragma

**Comment by dmitryax** [comment]
Also I don't think we need to render `+build`. I started removal of this directive in https://github.com/open-telemetry/opentelemetry-collector/pull/9304

File: testbed/testbed/child_process_collector.go (hunk 1 above)
Comment (fatsheep9146) [reply testbed/testbed/child_process_collector.go:229]: This is because the  test `TestAgentEnvVarOption` panics in windows environment, which you can see in
https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/7553756890/job/20566742790

The error is 
```
--- FAIL: TestAgentEnvVarOption (0.00s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x1b917d0]

goroutine 51 [running]:
testing.tRunner.func1.2({0x1ccfa20, 0x2ce3300})
	C:/hostedtoolcache/windows/go/1.20.12/x64/src/testing/testing.go:1526 +0x372
testing.tRunner.func1()
	C:/hostedtoolcache/windows/go/1.20.12/x64/src/testing/testing.go:1529 +0x650
panic({0x1ccfa20, 0x2ce3300})
	C:/hostedtoolcache/windows/go/1.20.12/x64/src/runtime/panic.go:890 +0x263
github.com/open-telemetry/opentelemetry-collector-contrib/testbed/testbed.TestAgentEnvVarOption(0x0?)
	D:/a/opentelemetry-collector-contrib/opentelemetry-collector-contrib/testbed/testbed/child_process_collector_test.go:48 +0x6f0
testing.tRunner(0xc00008d1e0, 0x1f307d0)
	C:/hostedtoolcache/windows/go/1.20.12/x64/src/testing/testing.go:1576 +0x217
created by testing.(*T).Run
	C:/hostedtoolcache/windows/go/1.20.12/x64/src/testing/testing.go:1629 +0x806
```

So I think this panic is due to following lines 

https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/0f92b2195cfe7708c08f10096553270a3a533b9f/testbed/testbed/child_process_collector.go#L195-L200

These lines maybe failed on windows which results the `cp.cmd` is not set correctly, so the 

https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/0f92b2195cfe7708c08f10096553270a3a533b9f/testbed/testbed/child_process_collector_test.go#L48

throws a panic.

I do not have a windows environment to dig this problem, so I try to reorder the code to escape the panic

@dmitryax

Comment (dmitryax) [reply testbed/testbed/child_process_collector.go:229]: But this is unrelated to this PR. Can you please submit a separate one?

File: cmd/mdatagen/templates/component_test.go.tmpl [hunk 3]
```diff
@@ -1,5 +1,10 @@
 // Code generated by mdatagen. DO NOT EDIT.
 
+{{ if not supportsWindows }}
+//go:build !windows
+// +build !windows
```
Comment (dmitryax) [inline cmd/mdatagen/templates/component_test.go.tmpl:5]: All the `+build` directives are removed from the project. No need to render this anymore

File: testbed/testbed/child_process_collector.go (hunk 1 above)
Comment (fatsheep9146) [reply testbed/testbed/child_process_collector.go:229]: @dmitryax  I created one #30670

Comment (dmitryax) [reply testbed/testbed/child_process_collector.go:229]: Thanks. Merged

File: cmd/opampsupervisor/supervisor/supervisor_test.go [hunk 4]
```diff
@@ -52,6 +53,7 @@ func Test_composeEffectiveConfig(t *testing.T) {
 
 	expectedConfig, err := os.ReadFile("../testdata/collector/effective_config.yaml")
 	require.NoError(t, err)
+	expectedConfig = bytes.ReplaceAll(expectedConfig, []byte("\r\n"), []byte("\n"))
```
Comment (codeboten) [inline cmd/opampsupervisor/supervisor/supervisor_test.go:56]: can this change be made in a separate PR? it seems unrelated to the change here

**Review by codeboten — COMMENTED** [review]
Thanks @fatsheep9146! This looks great, just one comment

File: cmd/mdatagen/templates/component_test.go.tmpl [hunk 5]
```diff
@@ -1,5 +1,9 @@
 // Code generated by mdatagen. DO NOT EDIT.
 
+{{- if len .Status.UnsupportedPlatforms }}
+//go:build !({{range $i, $v := .Status.UnsupportedPlatforms}}{{if $i}} || {{end}}{{.}}{{end}})
```
Comment (dmitryax) [inline cmd/mdatagen/templates/component_test.go.tmpl:4]: This seems incorrect. It should be logical AND not OR for the unsupported platforms list.
```suggestion
//go:build {{ range $i, $v := .Status.UnsupportedPlatforms }}{{ if $i }} && {{ end }}!{{ . }}{{ end }}
```

File: cmd/mdatagen/templates/component_test.go.tmpl [hunk 6]
```diff
@@ -1,5 +1,9 @@
 // Code generated by mdatagen. DO NOT EDIT.
 
+{{- if len .Status.UnsupportedPlatforms }}
```
Comment (dmitryax) [inline cmd/mdatagen/templates/component_test.go.tmpl:3]: No too to glue it to the upper comment
```suggestion
{{ if len .Status.UnsupportedPlatforms -}}
```

File: cmd/mdatagen/templates/component_test.go.tmpl (hunk 5 above)
Comment (dmitryax) [reply cmd/mdatagen/templates/component_test.go.tmpl:4]: Oh actually, your solution is good as well since you apply `!(...)` over it, but for some reason `()` are not rendered... Maybe removed by `go fmt`... I still think `!a && !b` is cleaner than `!(a || b)` though

**Comment by pjanotti** [comment]
> this configuration can also be used to generate the liftcycle test to skip windows when the component does not support windows

My understanding is that we should be testing all components on all OSes giving that we expect proper error messages and the that the collector configuration can be parsed on different platforms. Not testing the lifecycle on such platforms as of recently risks crashes without proper error message and regressions in this regard, see:

- https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/29505
- https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/29553
- https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/28679

**Review by pjanotti — CHANGES_REQUESTED** [review]
I understand this as an emergency fix to the broken Windows CI, however, in the end the tests should keep loading the config and expecting a definite error when the platform is not supported.

File: cmd/opampsupervisor/supervisor/supervisor_test.go (hunk 4 above)
Comment (fatsheep9146) [reply cmd/opampsupervisor/supervisor/supervisor_test.go:56]: No problem!

File: cmd/mdatagen/templates/component_test.go.tmpl (hunk 5 above)
Comment (fatsheep9146) [reply cmd/mdatagen/templates/component_test.go.tmpl:4]: Agreed

**Comment by fatsheep9146** [comment]
> I understand this as an emergency fix to the broken Windows CI, however, in the end the tests should keep loading the config and expecting a definite error when the platform is not supported.

Yes, so @dmitryax suggested:
> Let's start with unsupported_platforms option in metadata.yaml and just list them in go:build pragma

I think we can improve this as you suggest in following prs.
@pjanotti

File: cmd/opampsupervisor/supervisor/supervisor_test.go (hunk 4 above)
Comment (fatsheep9146) [reply cmd/opampsupervisor/supervisor/supervisor_test.go:56]: #30690 is created @codeboten

**Comment by fatsheep9146** [comment]
> > I understand this as an emergency fix to the broken Windows CI, however, in the end the tests should keep loading the config and expecting a definite error when the platform is not supported.
> 
> Yes, so @dmitryax suggested:
> 
> > Let's start with unsupported_platforms option in metadata.yaml and just list them in go:build pragma
> 
> I think we can improve this as you suggest in following prs. @pjanotti I will create an issue to track this.

#30691 is created @pjanotti

**Review by dmitryax — APPROVED** [review]

**Comment by dmitryax** [comment]
Thanks @fatsheep9146
