### PR TITLE
fix: update the label selector

### LINKED ISSUE #37892: [processor/k8sattributes] Invalid value: []string{""}: values set must be empty for exists and does not exist
### Component(s)

k8sattributes

## Description

failed to create "k8sattributes/knative" processor when using the exists op in the filter.labels

```yaml
processors:
  batch: {}
  k8sattributes/knative:
    auth_type: serviceAccount
    extract:
      labels:
      - key: serving.knative.dev/configuration
        tag_name: knative.serving.configuration
    filter:
      labels:
      - key: serving.knative.dev/configuration
        op: exists
```

2025/02/13 09:22:47 collector server run finished with error: cannot build pipelines: failed to create "k8sattributes/knative" processor, in pipeline "traces": values: Invalid value: []string{""}: values set must be empty for exists and does not exist

### Collector version

0.60.0, 0.119.0

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

### OpenTelemetry Collector configuration

```yaml
processors:
  batch: {}
  k8sattributes/knative:
    auth_type: serviceAccount
    extract:
      labels:
      - key: serving.knative.dev/configuration
        tag_name: knative.serving.configuration
    filter:
      labels:
      - key: serving.knative.dev/configuration
        op: exists
```

### Log output

```shell
Error: cannot build pipelines: failed to create "k8sattributes/knative" processor, in pipeline "traces": values: Invalid value: []string{""}: values set must be empty for exists and does not exist
2025/02/13 09:25:42 collector server run finished with error: cannot build pipelines: failed to create "k8sattributes/knative" processor, in pipeline "traces": values: Invalid value: []string{""}: values set must be empty for exists and does not exist
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by saltbo**
#### Link to tracking issue
Fixes #37892

### CODE REVIEW

File: processor/k8sattributesprocessor/internal/kube/client.go [hunk 1]
```diff
@@ -948,8 +949,21 @@ func (c *WatchClient) shouldIgnorePod(pod *api_v1.Pod) bool {
...
 func selectorsFromFilters(filters Filters) (labels.Selector, fields.Selector, error) {
 	labelSelector := labels.Everything()
+	singleValueSelections := []selection.Operator{
+		selection.Equals, selection.DoubleEquals, selection.NotEquals,
+		selection.GreaterThan, selection.LessThan,
+	}
 	for _, f := range filters.Labels {
-		r, err := labels.NewRequirement(f.Key, f.Op, []string{f.Value})
+		if f.Op == selection.In || f.Op == selection.NotIn {
+			return nil, nil, fmt.Errorf("field filters don't support operator: '%s'", f.Op)
```
Comment (TylerHelmuth) [inline processor/k8sattributesprocessor/internal/kube/client.go:958]:
```suggestion
			return nil, nil, fmt.Errorf("label filters don't support operator: '%s'", f.Op)
```

File: processor/k8sattributesprocessor/internal/kube/client.go [hunk 2]
```diff
@@ -948,8 +949,21 @@ func (c *WatchClient) shouldIgnorePod(pod *api_v1.Pod) bool {
 
 func selectorsFromFilters(filters Filters) (labels.Selector, fields.Selector, error) {
 	labelSelector := labels.Everything()
+	singleValueSelections := []selection.Operator{
```
Comment (TylerHelmuth) [inline processor/k8sattributesprocessor/internal/kube/client.go:952]: lets make this a map so we can do constant time lookup instead of `slices.Contains`. It can be instantiated as a var outside the function.

**Review by TylerHelmuth — APPROVED** [review]
Thank you!

**Review by TylerHelmuth — COMMENTED** [review]
@saltbo looks like the `TestWithFilterLabels` test is failing with these changes: https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/13333228699/job/37242824462?pr=37894

**Review by dmitryax — APPROVED** [review]
