### PR TITLE
[processor/tailsamplingprocessor] `and` support for string invert match

### LINKED ISSUE #9553: [processor/tailsamplingprocessor] `and` policy appears to ignore `string_attribute` match results
**Describe the bug**

Given a tailsamplingprocessor with an `and` policy that has both `string_attribute` and `probabilistic` sampling, the `and` policy appears to ignore the results of the `string_attribute` match and falls back on only the `probabilistic` results.

I have a service in Kubernetes that is getting scraped with Prometheus. I am trying to configure tail sampling to:

- Keep all "slow" calls (those that take > 5s)
- Keep all error calls (either the trace status is ERROR or the response code >= 500)
- For the remaining calls...
  - Drop all the "noise" - `/metrics`, `/health`, GRPC calls to export traces (where that value is in the `http.url` attribute)
  - Sample 10% of the calls that aren't noise and keep those

The policies to keep slow and error calls work perfectly. However, I still get ~10% of the calls to `/metrics` despite having an `and` policy set up to combine `string_attribute` with `probabilistic` sampling.

**Steps to reproduce**

In Kubernetes:

- Deploy one instance of OpenTelemetry Collector via the OpenTelemetry Operator. Use the `otel/opentelemetry-collector-contrib` container. Relay traces to an endpoint like Jaeger or Dynatrace (I'm using Dynatrace).
- Deploy a test service that will get scraped with Prometheus and also offer endpoints for general consumption.
- Cause an error - note the trace gets forwarded to the endpoint as expected.
- Wait while Prometheus scrapes the metrics, about 10 - 15 minutes. You'll see traces from `/metrics` show up in the trace UI, which indicates the tailsamplingprocessor was not properly dropping the matching traces.

See config section below for configuration.

**What did you expect to see?**

I expect to see _no_ traces from `/metrics` because the `string_attribute` policy should filter them out.

**What did you see instead?**

I see periodic traces from `/metrics` coming through, with approximately the 10% sampling expected from the `probabilistic` policy.

Here is a screenshot of one of the traces that snuck through OpenTelemetry Collector and into Dynatrace. You can see here that:

- The operation completed in 1.58ms, far lower than the 5000ms threshold for the `latency` policy in my config.
- The trace was a success, so it wasn't captured based on the `status_code` policy.
- The `http.url` trace attribute is clearly present and there is only one trace span in the whole thing, so it wasn't a problem with too short of a tail sampling `decision_wait` or with the attribute missing.

Example trace that got through the tailsamplingprocessor

**What version did you use?**

Version: 0.48.0 of the `otel/opentelemetry-collector-contrib` container.

**What config did you use?**

```yaml
extensions:
  memory_ballast:
    size_mib: 683
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
exporters:
  otlphttp/dynatrace:
    endpoint: "${DYNATRACE_ENDPOINT}/api/v2/otlp"
    headers:
      Authorization: "Api-Token ${DYNATRACE_API_TOKEN}"
processors:
  batch/trace:
  memory_limiter/trace:
    limit_mib: 1500
    spike_limit_mib: 512
    check_interval: 5s
  tail_sampling:
    decision_wait: 10s
    policies:
      - name: slow_calls
        type: latency
        latency:
          threshold_ms: 5000
      - name: error_otel_status
        type: status_code
        status_code:
          status_codes:
            - ERROR
      - name: error_http_status
        type: numeric_attribute
        numeric_attribute:
            key: http.status_code
            min_value: 500
      - name: keep_sampled_success
        type: and
        and:
          and_sub_policy:
            - name: drop_noisy_traces_url
              type: string_attribute
              string_attribute:
                key: http.url
                values:
                  - \/metrics
                  - opentelemetry\.proto
                  - favicon\.ico
                  - \/health
                enabled_regex_matching: true
                invert_match: true
            - name: keep_percentage
              type: probabilistic
              probabilistic:
                sampling_percentage: 10
service:
  extensions:
    - memory_ballast
  pipelines:
    traces:
      receivers:
        - otlp
      processors:
        - memory_limiter/trace
        - tail_sampling
        - batch/trace
      exporters:
        - otlphttp/dynatrace
```

**Environment**

OS: Ubuntu 18.04.6 (the Kubernetes node OS)
Docker container: `otel/opentelemetry-collector-contrib` 0.48.0

**Additional context**

There really isn't any good mechanism for debugging the processor. I did turn the logging up to debug level to see what got logged, but all I saw was counts of trace spans that were getting through. I did see the `string_attributes` policy executing, but it didn't seem to make any difference.

Here are the logs from one of the `/metrics` calls that got through. Nothing else at all was running through the system (it's a standalone POC) so I know this is the `/metrics` trace. I can see it passes through `latency.go`, `status_code.go`, `string_tag_filter.go`, and then `probabilistic.go` and finally through the `oltphttpexporter/oltp.go` to get to Dynatrace. I didn't expect to see it make it through the `string_tag_filter.go` to be honest.

```text
2022-04-26T23:17:48.552Z	debug	tailsamplingprocessor@v0.48.0/processor.go:160	Sampling Policy Evaluation ticked	{"kind": "processor", "name": "tail_sampling", "pipeline": "traces"}
2022-04-26T23:17:48.552Z	debug	sampling/latency.go:39	Evaluating spans in latency filter	{"kind": "processor", "name": "tail_sampling", "pipeline": "traces"}
2022-04-26T23:17:48.552Z	debug	sampling/status_code.go:62	Evaluating spans in status code filter	{"kind": "processor", "name": "tail_sampling", "pipeline": "traces"}
2022-04-26T23:17:48.552Z	debug	sampling/string_tag_filter.go:103	Evaluting spans in string-tag filter	{"kind": "processor", "name": "tail_sampling", "pipeline": "traces"}
2022-04-26T23:17:48.552Z	debug	sampling/probabilistic.go:55	Evaluating spans in probabilistic filter	{"kind": "processor", "name": "tail_sampling", "pipeline": "traces"}
2022-04-26T23:17:48.552Z	debug	tailsamplingprocessor@v0.48.0/processor.go:198	Sampling policy evaluation completed	{"kind": "processor", "name": "tail_sampling", "pipeline": "traces", "batch.len": 1, "sampled": 4, "notSampled": 0, "droppedPriorToEvaluation": 0, "policyEvaluationErrors": 0}
2022-04-26T23:17:48.634Z	debug	otlphttpexporter/otlp.go:127	Preparing to make HTTP request	{"kind": "exporter", "name": "otlphttp/dynatrace", "url": "https://bmb58337.live.dynatrace.com/api/v2/otlp/v1/traces"}
2022-04-26T23:17:49.540Z	debug	memorylimiterprocessor/memorylimiter.go:288	Currently used memory.	{"kind": "processor", "name": "memory_limiter/trace", "pipeline": "traces", "cur_mem_mib": 13}
```

I do see [the example configurations in the tailsamplingprocessor](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/processor/tailsamplingprocessor/testdata/tail_sampling_config.yaml) use a sort of combination of YAML and JSON; I tested it both ways in case that mattered and it doesn't.

I tried reducing the number of values to be _only_ `\/metrics` but that didn't stop it from getting through, either. I tried switching to use the `http.target` attribute (since that's also present) but it didn't change anything.

I could be misunderstanding how the `and` policy works, so let me know if I am. Perhaps there's some other way to configure effectively the same thing, like with the `composite` policy, but I'm not entirely sure how.

### PR DESCRIPTION
**Pull request by tillig**
**Description:** Fix #9553: Adds support for tail sampling so the `and` policy can do string invert match.

**Link to tracking Issue:** #9553

**Testing:** Added unit tests to verify string attribute invert could both allow and disallow match.

**Documentation:** No documentation added. Documentation already notes string invert match usage should work, it just hadn't been implemented with `and`.

I didn't refactor the unit tests to be parameterized like those in `string_tag_filter_test.go`; unclear if that's required here.

### CODE REVIEW

**Comment by pmm-sumo** [comment]
@mottibec @fabiovn since it involves the `and` policy and invert matches, could you take a look as well?

File: processor/tailsamplingprocessor/internal/sampling/and.go [hunk 1]
```diff
@@ -45,7 +45,7 @@ func (c *And) Evaluate(traceID pcommon.TraceID, trace *TraceData) (Decision, err
 		if err != nil {
 			return Unspecified, err
 		}
-		if decision == NotSampled {
+		if decision == NotSampled || decision == InvertNotSampled {
```
Comment (pmm-sumo) [inline processor/tailsamplingprocessor/internal/sampling/and.go:48]: Nice find, now I'm wondering if [other places which evaluate decision](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/processor/tailsamplingprocessor/internal/sampling/composite.go#L112) should be updated as well. Quickly looking at the code, this seems to be the case (though to be fair I haven't looked at tailsamplingprocessor code in a while and might be missing something)

Comment (tillig) [reply processor/tailsamplingprocessor/internal/sampling/and.go:48]: I admit I haven't dived deep into the string matching, but it did make me wonder why it matters if it's `Sampled` or `InvertSampled`. It wasn't immediately obvious why a regular decision and an invert decision would need to be treated differently.

**Comment by tillig** [comment]
It appears some sort of ballast load test failed here, but I'm unclear how adding this one "if" check would have caused that. Is there something different I should be doing?

**Comment by TylerHelmuth** [comment]
> It appears some sort of ballast load test failed here, but I'm unclear how adding this one "if" check would have caused that. Is there something different I should be doing?

The load tests have been very flaky recently. The issue is likely not caused by your change. @djaglowski is working on a change to help fix the tests.

File: processor/tailsamplingprocessor/internal/sampling/and.go (hunk 1 above)
Comment (pmm-sumo) [reply processor/tailsamplingprocessor/internal/sampling/and.go:48]: It seems it's the case as well, I tested it and it failed. I am opening second PR right now :)

**Review by pmm-sumo — APPROVED** [review]
LGTM

I have prepared a PR with a similar fix to composite policy: #9793

File: processor/tailsamplingprocessor/internal/sampling/and.go (hunk 1 above)
Comment (mottibec) [reply processor/tailsamplingprocessor/internal/sampling/and.go:48]: @tillig I don't fully understand how the invert works but it looks like there's something related to the `InvertSampled` decision in the [makeDecision](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/fe12a901958f7ed8dfce7f14800776ca5168c37e/processor/tailsamplingprocessor/processor.go#L209) function

Comment (tillig) [reply processor/tailsamplingprocessor/internal/sampling/and.go:48]: Yeah, but even that seems really sort of weird to me.

```golang
	// InvertNotSampled takes precedence over any other decision
	if samplingDecision[sampling.InvertNotSampled] {
		finalDecision = sampling.NotSampled
	} else if samplingDecision[sampling.Sampled] {
		finalDecision = sampling.Sampled
	} else if samplingDecision[sampling.InvertSampled] && !samplingDecision[sampling.NotSampled] {
		finalDecision = sampling.Sampled
	}
```

- All the policies get executed before a decision is made. That's weird, and _sounds_ like it's more of a composite thing than it should be. It _feels_ like the policies should be executed in order and the first one that says "sample this thing" would allow sampling through. That'd perform better, too.
- `InvertNotSampled` has the _highest_ precedence, but `InvertSampled` has the _lowest_ precedence and has to be specifically checked to see if it's also not contradicted by `NotSampled`.

I dunno, I'm coming at it late, I just don't see any doc on it and the special treatment there is kind of confusing. It gets even more confusing when I think about how this affects the way I might get an unexpected result from just a series of policies now. If I put an invert match policy in the mix and it says "no," it'll countermand any other policy I put in there. Even if it's not in an `and` policy. 🤔  Am I reading that wrong?

Comment (pmm-sumo) [reply processor/tailsamplingprocessor/internal/sampling/and.go:48]: Sure thing, I was curious if you would find that useful. As for trying it out, it should be quite easy to [include it via a builder](https://github.com/SumoLogic/sumologic-otel-collector/blob/main/otelcolbuilder/.otelcol-builder.yaml#L36-L37)

Comment (tillig) [reply processor/tailsamplingprocessor/internal/sampling/and.go:48]: Cool, thanks. If/when that time comes, I'll have to actually start learning what "include it via a builder" means. I'm not a go dev and there's a long tail of things to learn. 😄

Comment (mottibec) [reply processor/tailsamplingprocessor/internal/sampling/and.go:48]: Yeah, I agree with that, the behavior of the `tailsamplingprocessor` is not what i would expect. 
the readme should definitely be updated to reflect that.
I know there was talk about deprecating the `tailsamplingprocessor` so I like the idea of upstreaming [cascadingfilterprocessor](https://github.com/SumoLogic/sumologic-otel-collector/tree/main/pkg/processor/cascadingfilterprocessor) I think it can be a great fit to replace it.

**Comment by tillig** [comment]
The PR here is still very much of interest to me. It looks like the unit tests failed with some things unrelated to my change (errors about trying to use a plugin that's not installed?) and the load tests have been noted as flaky and getting a fix.

If there's something I need to do here, please do let me know. I have to admit I'm somewhat new to Go so I'm not sure how to help fix the unrelated issues, but maybe with a little hint to get me going in the right direction?

**Comment by djaglowski** [comment]
@tillig I've removed the Stale label and restarted unit tests. Assuming no persistent issues there, we'll get this merged.

**Comment by tillig** [comment]
Looks like unrelated link checks were failing due to the README in unrelated modules. Brought in additional changes from main in the hopes it'll get me over the hump. (Should I stop bringing in main?)

**Review by djaglowski — APPROVED** [review]
Looks good to me. Seems worth noting in the changelog though.

**Comment by tillig** [comment]
@djaglowski Added. Thanks!
