### PR TITLE
[receiver/prometheusremotewritereceiver] accept unspecified types as gauge

### LINKED ISSUE #41840: [receiver/prometheusremotewrite] Prometheus remote_write to prometheusremotewritereceiver fails with METRIC_TYPE_UNSPECIFIED
### Component(s)

receiver/prometheusremotewrite

## Description

Hi! I'm trying to forward metrics from Prometheus to OpenTelemetry Collector using the prometheusremotewritereceiver. Prometheus is receiving metrics via remote_write from several sources (mainly vmagent and prometheus-agent), then forwarding them to Otel Collector.

```mermaid
flowchart TD
    vma1(vmagent-01)
    vma2(vmagent-02)
    pa1(prometheus-agent-01)
    prometheus(Prometheus)
    otg(Otel Collector Gateway)
    prwr["Prometheus Remote<br>Write Receiver"]
    vma1 -->|Remote Write| prometheus
    vma2 -->|Remote Write| prometheus
    pa1  -->|Remote Write| prometheus
    prometheus -->|Remote Write| prwr
    prwr <--> otg
```
However, when Prometheus sends these metrics to Otel Collector, the collector rejects them with the following error: `METRIC_TYPE_UNSPECIFIED`

This happens for many metrics — the rejected type is always `METRIC_TYPE_UNSPECIFIED`

#### Prometheus config:
```yaml
global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

remote_write:
  - url: "http://192.168.138.91:32411/api/v1/write"
    name: "Remote write to Otelcol gateway"
    protobuf_message: io.prometheus.write.v2.Request
```

#### Collector config (relevant part):
```yaml
receivers:
  prometheusremotewrite:
    endpoint: 192.168.138.91:32411
  otlp:
    protocols:
      grpc:
        endpoint: 192.168.138.91:5555
      http:
        endpoint: 192.168.138.91:32412
``` 

## Expected Result
Metrics should be successfully forwarded from Prometheus to the OpenTelemetry Collector, even if the metrics were originally written to Prometheus via remote_write (e.g., by prometheus-agent or vmagent).

## Actual Result
The `prometheusremotewritereceiver` component rejects incoming metrics from Prometheus with `METRIC_TYPE_UNSPECIFIED` errors.

Example log output from Prometheus:
```
level=ERROR component=remote remote_name="Remote write to Otelcol gateway"
err="server returned HTTP status 400 Bad Request:
unsupported metric type \"METRIC_TYPE_UNSPECIFIED\" for metric \"angie_slabs_pages_slots_used\""
```

Let me know if you’d like me to provide full debug logs or a test environment to reproduce the issue.

### Collector version

0.131.1

## Environment
OS: Ubuntu 24.04
Compiler: go version go1.24.4 linux/amd64

### OpenTelemetry Collector configuration

```yaml

```

### Log output

```shell
Aug 07 13:33:01 test-monit-01 prometheus[186361]: time=2025-08-07T13:33:01.437+03:00 level=ERROR source=queue_manager.go:1668 msg="non-recoverable error" component=remote remote_name="Remote write to Otelcol gateway" url=http://192.168.138.91:32411/api/v1/write failedSampleCount=3995 failedHistogramCount=0 failedExemplarCount=0 err="server returned HTTP status 400 Bad Request: unsupported metric type \"METRIC_TYPE_UNSPECIFIED\" for metric \"node_network_mtu_bytes\"\nunsupported metric type \"METRIC_TYPE_UNSPECIFIED\" for metric \"node_network_mtu_bytes\"\nunsupported metric type \"METRIC_TYPE_UNSPECIFIED\" for metric \"node_network_mtu_bytes\"\nunsupported metric type \"METRIC_TYPE_UNSPECIFIED\" for metric \"node_network_mtu_bytes\"\nunsupported metric type \"METRIC_TYPE_UNSPECIFIED\" for metric \"node_network_mtu_bytes\"\nunsupported metric type \"METRIC_TYPE_UNSPECIFIED\" for metric \"node_network_name_assign_type\"\nunsupported metric type \"METRIC_TYPE_UNSPECIFIED\" for metric \"node_network_name_assign_type\"\nunsupported metric type \"METRIC_TYPE_UNSPECIFIED\" for metric \"node_network_name_assign_type\"\nunsupported metric type \"METRIC_TYPE_UNSPECIFIED\" for metric \"node_network_name_assign_type\"\nunsupported metric type \"METRIC_TYPE_UNSPECIFIED\" for metric \"node_network_name_assign_type\"\nunsupported metric type \"METRIC_TYPE_UNSPECIFIED\" for metric \"node_network_name_assign_type\"\nunsupported metric type \"METRIC_TYPE"

Aug 07 13:35:12 test-monit-01 prometheus[186361]: time=2025-08-07T13:35:12.942+03:00 level=ERROR source=queue_manager.go:1668 msg="non-recoverable error" component=remote remote_name="Remote write to Otelcol gateway" url=http://192.168.138.91:32411/api/v1/write failedSampleCount=3995 failedHistogramCount=0 failedExemplarCount=0 err="server returned HTTP status 400 Bad Request: unsupported metric type \"METRIC_TYPE_UNSPECIFIED\" for metric \"node_disk_filesystem_info\"\nunsupported metric type \"METRIC_TYPE_UNSPECIFIED\" for metric \"node_disk_filesystem_info\"\nunsupported metric type \"METRIC_TYPE_UNSPECIFIED\" for metric \"node_disk_filesystem_info\"\nunsupported metric type \"METRIC_TYPE_UNSPECIFIED\" for metric \"node_disk_filesystem_info\"\nunsupported metric type \"METRIC_TYPE_UNSPECIFIED\" for metric \"node_disk_filesystem_info\"\nunsupported metric type \"METRIC_TYPE_UNSPECIFIED\" for metric \"node_disk_flush_requests_time_seconds_total\"\nunsupported metric type \"METRIC_TYPE_UNSPECIFIED\" for metric \"node_disk_flush_requests_time_seconds_total\"\nunsupported metric type \"METRIC_TYPE_UNSPECIFIED\" for metric \"node_disk_flush_requests_time_seconds_total\"\nunsupported metric type \"METRIC_TYPE_UNSPECIFIED\" for metric \"node_disk_flush_requests_time_seconds_total\"\nunsupported metric type \"METRIC_TYPE_UNSPECIFIED\" for metric \"node_disk_flush_requests_time_seconds_total\"\nunsupported metric type \"METRIC_TYPE_UNSPECI"
```

## Additional context
In Prometheus, when using remote_write, metric types are not explicitly defined — they are inferred based on the metric’s structure and behavior. This might be the reason why the receiver is unable to handle them.

As far as I understand, the OpenTelemetry Collector might expect the metric type to be explicitly set, which Prometheus does not do for remote_write — especially if the metrics were ingested into Prometheus via remote_write themselves (e.g., from prometheus-agent, vmagent, etc.)

### Tip

<sub>[React](https://github.blog/news-insights/product-news/add-reactions-to-pull-requests-issues-and-comments/) with 👍 to help prioritize this issue. Please use comments to provide useful context, avoiding `+1` or `me too`, to help us triage it. Learn more [here](https://opentelemetry.io/community/end-user/issue-participation/).</sub>

### PR DESCRIPTION
**Pull request by jelly-afk**
#### Description
METRIC_TYPE_UNSPECIFIED are now accepted by prometheusremotewritereceiver and given value of "unknown" in metric.metadata["prometheus.type"]

#### Link to tracking issue
Fixes (partially) #41840 

#### Testing
In TestTranslateV2 the "unsupported metric type UNSPECIFIED" was removed and "accept unspecified metric type as gauge" was added to test that unspecified types are accepted as gauge

### CODE REVIEW

**Review by dashpole — COMMENTED** [review]
looking good.  Can you add or update tests to check for metric.metadata?

**Comment by jelly-afk** [comment]
Sure

**Review by ArthurSens — COMMENTED** [review]
LGTM after addressing David's comments.

We could also handle histograms here https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/586b518c73c9a10f74e0faabfcd33e79d7458f8a/receiver/prometheusremotewritereceiver/receiver.go#L300 the same way. Just switch the if to something like `if len(ts.Histograms) > 0 {` and that way we would handle histograms even if their type metadata is missing


Totally fine to do this in a separate PR, since this would also require a new test.

**Comment by jelly-afk** [comment]
The functions we used for testing didnt test for Metadata() so i made a small helper functions to check only the Metadata() map

**Comment by jelly-afk** [comment]
> LGTM after addressing David's comments.
> 
> We could also handle histograms here
> 
> https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/586b518c73c9a10f74e0faabfcd33e79d7458f8a/receiver/prometheusremotewritereceiver/receiver.go#L300
> 
> the same way. Just switch the if to something like `if len(ts.Histograms) > 0 {` and that way we would handle histograms even if their type metadata is missing
> Totally fine to do this in a separate PR, since this would also require a new test.

Hey @ArthurSens now that we accept unspecified types, classic histograms with missing type metadata will be handled as gauge types since they populate the samples instead of histograms

File: receiver/prometheusremotewritereceiver/receiver_test.go [hunk 1]
```diff
@@ -179,6 +181,7 @@ func TestHandlePRWContentTypeNegotiation(t *testing.T) {
 	}
 }
 
+// Uncomment metric.Metadata().PutStr(prometheus.MetricMetadataTypeKey, "histogram") in expected metrics when histogram metrics include the "prometheus.type" metadata.
```
Comment (ArthurSens) [inline receiver/prometheusremotewritereceiver/receiver_test.go]: Could we remove this comment and all the other comments in this test that are about histograms?

We might end up exactly with what you had in mind in the end, but I didn't want to commit to this before discussing it. Could we worry about histograms in the histogram PR?

File: receiver/prometheusremotewritereceiver/receiver_test.go [hunk 2]
```diff
@@ -1755,3 +1798,28 @@ func TestLRUCacheResourceMetrics(t *testing.T) {
 	// As just have 1 slot in the cache, but the cache for metric1 was evicted, this metric1_1 should generate a new resource metric, even having the same job/instance than the metric1.
 	assert.NoError(t, pmetrictest.CompareMetrics(expectedMetrics1_1, mockConsumer.metrics[3]))
 }
+
+func buildMetaDataMapByID(ms pmetric.Metrics) map[string]map[string]any {
```
Comment (ArthurSens) [inline receiver/prometheusremotewritereceiver/receiver_test.go:1798]: Thanks for building this, that looks good as an initial implementation!

In the long run, we want this method to be moved to `pkg/pdatatest/pmetrictest` so this is re-usable by other components that might need to compare metadata. And also because this piece of code makes more sense over there, comparing OTLP metadata isn't really in scope of prometheusremotewritereceiver.

**Review by ArthurSens — COMMENTED** [review]
> Hey @ArthurSens now that we accept unspecified types, classic histograms with missing type metadata will be handled as gauge types since they populate the samples instead of histograms

Not exactly, Native Histograms and Native Histogram Custom Buckets(NHCB) don't follow the codepath you're touching. We'll need a follow up PR for them, but let's worry about that in the right time :)

---

Sorry for the delay here! The PR looks pretty close to ready. Could you rebase to resolve the merge conflict and also address a couple of comments? I'll open an issue for the things we want to solve in a separate PR

File: receiver/prometheusremotewritereceiver/receiver_test.go (hunk 2 above)
Comment (jelly-afk) [reply receiver/prometheusremotewritereceiver/receiver_test.go:1798]: right, will move this once it’s a bit more refined.

**Review by ArthurSens — APPROVED** [review]
Thank you!
