### PR TITLE
[exporter/datadog] Add support to skip TLS verification

### LINKED ISSUE #6235: datadogexporter : TLS and mTLS settings
**Describe the bug**
TLS and mTLS settings are not available for datadogexporter 

is there any option like insecure_skip_verify: false

### PR DESCRIPTION
**Pull request by julien-lebot**
**Description:**
This PR adds an option to disable TLS verification. This was requested in the following issue https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/6235.

**Link to tracking Issue:** [6235
](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/6235)
**Testing:** Added 2 basic unit tests.

**Documentation:** Updated the example configuration.

### CODE REVIEW

File: exporter/datadogexporter/config/config.go [hunk 1]
```diff
@@ -205,13 +205,22 @@ func (t *TagsConfig) GetHostTags() []string {
 	return tags
 }
 
+// LimitedTLSClientSetting is a subset of TLSClientSetting, see LimitedHTTPClientSettings for more details
+type LimitedTLSClientSetting struct {
+	// InsecureSkipVerify controls whether a client verifies the server's
+	// certificate chain and host name.
+	InsecureSkipVerify bool `mapstructure:"insecure_skip_verify"`
+}
```
Comment (mx-psi) [inline exporter/datadogexporter/config/config.go:213]: The config struct is considered part of the public API and therefore we won't be able to make breaking changes to it in the future. To future-proof, we should put this in a `LimitedHTTPClientSettings` like

```go
type LimitedHTTPClientSettings struct {
	TLSSetting LimitedTLSClientSettings `mapstructure:"tls,omitempty"`
}
```

and then embed it on the `Config` struct:

```go
LimitedHTTPClientSettings `mapstructure:",squash"`
```

This results in the same YAML configuration but we future-proof the Go API too.

**Review by mx-psi — COMMENTED** [review]
Just one small comment, otherwise looks good!

**Comment by mx-psi** [comment]
I updated the title to conform to guidelines

**Review by codeboten — COMMENTED** [review]
Any reason not to use the already defined `TLSClientSetting` and only support the flags that are needed from that configuration?

https://github.com/open-telemetry/opentelemetry-collector/blob/18fb01178b794a0b8e2f3b0e48ab6f81056ae2b5/config/configtls/configtls.go#L58

File: CHANGELOG.md [hunk 2]
```diff
@@ -11,6 +11,8 @@
 - `translator/prometheusremotewrite`: add a new module to help translate data from OTLP to Prometheus Remote Write (#7240)
 - `jmxreceiver`: Added `additional_jars` configuration option to launch JMX Metric Gatherer JAR with extended `CLASSPATH` (#7378)
 - `awscontainerinsightreceiver`: add full pod name when configured to AWS Container Insights Receiver (#7415)
+- `datadogexporter`: Add insecure_skip_tls flag to configuration (#7422)
```
Comment (mx-psi) [inline CHANGELOG.md:14]:
```suggestion
- `datadogexporter`: Add insecure_skip_verify flag to configuration (#7422)
```

**Review by mx-psi — APPROVED** [review]
LGTM, just a minor correction on the changelog. I agree with @julien-lebot on why we want to use the `Limited*` pattern (which is already in use in the CloudFoundry receiver). 

An alternative would be to use the `configtls.TLSClientSettings` and fail to unmarshal/validate if any fields we don't support are set, however, I don't see how we would do that, at least not in a way that works over time (each time a new setting is added we would need to 'ban it' manually).

**Comment by jpkrohling** [comment]
Looks like I can't change the code from this PR, thus, I can't fix the changelog conflicts for you. Please rebase this PR.

File: CHANGELOG.md [hunk 3]
```diff
@@ -53,6 +53,7 @@
 - `tailsamplingprocessor`: Add And sampling policy (#6910)
 - `coralogixexporter`: Add Coralogix Exporter (#7383)
 - `prometheusexecreceiver`: Add default value for `scrape_timeout` option (#7587)
+- `datadogexporter`: Add insecure_skip_verify flag to configuration (#7422)
```
Comment (jpkrohling) [inline CHANGELOG.md:56]: This should not be part of the 0.44.0 block, it should be under unreleased.

**Review by jpkrohling — CHANGES_REQUESTED** [review]

File: CHANGELOG.md (hunk 3 above)
Comment (julien-lebot) [reply CHANGELOG.md:56]: Oh good catch, thank you

**Review by jpkrohling — APPROVED** [review]

**Review by codeboten — APPROVED** [review]
