### PR TITLE
[receiver/postgresql] Fix issue where WAL lag stats could cause conversion error

### LINKED ISSUE #14972: Postgresql metrics receiver has runtime error on type conversion
## Description

Postgresql metrics receiver has runtime error on converting null to int64 for `write_lag` 
and `checkpoint_duration_write` float64 to int64

### Collector version

v0.62.1

## Environment
OS: "Ubuntu 20.04"
Compiler(if manually compiled): (e.g., "go 14.2")

### OpenTelemetry Collector configuration

```yaml
extensions:
receivers:
    postgresql:
            endpoint: localhost:5432
            transport: tcp
            username: postgres
            password: password
            databases:
                - test_db
            collection_interval: 10s
            tls:
                insecure: true
exporters:
    kafka:
        brokers: [ localhost:9092 ]
        protocol_version: "3.0.0"
processors:
service:
    pipelines:
        metrics:
            receivers: [ postgresql ]
            processors: []
            exporters: [ kafka ]
```

### Log output

```shell
Oct 17 07:17:31 Test-Host otelcol-contrib[3184939]: 2022-10-17T07:17:31.883Z        error        scraperhelper/scrapercontroller.go:197        Error scraping metrics        {"kind": "receiver", "name": "postgresql", "pipeline": "metrics", "error": "sql: Scan error on column index 2, name \"checkpoint_duration_write\": converting driver.Value type float64 (\"4.0602716e+08\") to a int64: invalid syntax; sql: Scan error on column index 2, name \"write_lag\": converting NULL to int64 is unsupported; sql: Scan error on column index 2, name \"write_lag\": converting NULL to int64 is unsupported; sql: Scan error on column index 2, name \"write_lag\": converting NULL to int64 is unsupported; sql: Scan error on column index 2, name \"write_lag\": converting NULL to int64 is unsupported; sql: Scan error on column index 2, name \"write_lag\": converting NULL to int64 is unsupported; sql: Scan error on column index 2, name \"write_lag\": converting NULL to int64 is unsupported; sql: Scan error on column index 2, name \"write_lag\": converting NULL to int64 is unsupported; sql: Scan error on column index 2, name \"write_lag\": converting NULL to int64 is unsupported; sql: Scan error on column index 2, name \"write_lag\": converting NULL to int64 is unsupported; sql: Scan error on column index 2, name \"write_lag\": converting NULL to int64 is unsupported; sql: Scan error on column index 2, name \"write_lag\": converting NULL to int64 is unsupported; sql: Scan error on column index 2, name \"write_lag\": converting NULL to int64 is unsupported; sql: Scan error on column index 2, name \"write_lag\": converting NULL to int64 is unsupported; sql: Scan error on column index 2, name \"write_lag\": converting NULL to int64 is unsupported; sql: Scan error on column index 2, name \"write_lag\": converting NULL to int64 is unsupported; sql: Scan error on column index 2, name \"write_lag\": converting NULL to int64 is unsupported; sql: Scan error on column index 2, name \"write_lag\": converting NULL to int64 is unsupported; sql: Scan error on column index 2, name \"write_lag\": converting NULL to int64 is unsupported; sql: Scan error on column index 2, name \"write_lag\": converting NULL to int64 is unsupported; sql: Scan error on column index 2, name \"write_lag\": converting NULL to int64 is unsupported; sql: Scan error on column index 2, name \"write_lag\": converting NULL to int64 is unsupported; sql: Scan error on column index 2, name \"write_lag\": converting NULL to int64 is unsupported", "scraper": "postgresql"}
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by djaglowski**
Resolves #14972

An easier implementation would use coalesce to return 0 when the stats are empty, but this would report phantom data points. Instead, this uses coalesce to return -1 and the scraper must use this value to determine whether or not to report a data point.

### CODE REVIEW

File: receiver/postgresqlreceiver/scraper_test.go [hunk 1]
```diff
@@ -263,6 +263,13 @@ func (m *mockClient) initMocks(database string, databases []string, index int) {
 				replayLag:    700,
 				writeLag:     800,
 			},
+			{
```
Comment (jpkrohling) [inline receiver/postgresqlreceiver/scraper_test.go:266]: Would this test here yield the same errors from the reported issue when the fix isn't in place?

Comment (djaglowski) [reply receiver/postgresqlreceiver/scraper_test.go:266]: I don't think so. The error came from within the client library. This is using a mock client so is only testing part of the change. Unfortunately, I think a proper test would require configuring replication within an integration test, which is a bit outside of my wheelhouse.

Comment (jpkrohling) [reply receiver/postgresqlreceiver/scraper_test.go:266]: That's fine, I think it's close enough.

**Review by jpkrohling — APPROVED** [review]
