### PR TITLE
[pkg/ottl] Fix issue with named parameter spacing

### LINKED ISSUE #27638: [pkg/ottl] Parsing of named arguments is whitespace dependent
### Component(s)

pkg/ottl

## Description

While testing out some optional parameter situations I discovered that the named argument parsing is whitespace dependent.  This is in contrast with the rest of OTTL which does not depend on whitespace. I am not yet sure why this is happening as the grammar/tokens seem correct.  The whitespace in `(@(Lowercase(Uppercase | Lowercase)*) Equal)?` is ignored by the parser and the `Equal` token cannot appear in `Lowercase` or `Uppercase`.

## Steps to Reproduce

I added this test to parser_test.go:

```go
{
  name:      "editor with named arg",
  statement: `set(name="foo")`,
  expected: &parsedStatement{
    Editor: editor{
      Function: "set",
      Arguments: []argument{
        {
          Name: "name",
          Value: value{
            String: ottltest.Strp("foo"),
          },
        },
      },
    },
    WhereClause: nil,
  },
},
```

## Expected Result

Test passed

## Actual Result

Got an error parsing the statement. No error occurs if the statement is written as `set(name = "foo")`

### PR DESCRIPTION
**Pull request by TylerHelmuth**
**Description:** 
Fixes an issue with the grammar where named parameters had to have a space after the `=`.

**Link to tracking Issue:**
Closes https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/27638

**Testing:** 
Added a new unit test

### CODE REVIEW

File: pkg/ottl/grammar.go [hunk 1]
```diff
@@ -174,7 +176,7 @@ func (c *compareOp) String() string {
 // comparison represents an optional boolean condition.
 type comparison struct {
 	Left  value     `parser:"@@"`
-	Op    compareOp `parser:"@OpComparison"`
+	Op    compareOp `parser:"@(OpComparison | Equal Equal)"`
```
Comment (evan-bradley) [inline pkg/ottl/grammar.go:179]: Does this allow for `3 = = 4.9`?

Comment (TylerHelmuth) [reply pkg/ottl/grammar.go:179]: I'll test that but probably.

Comment (TylerHelmuth) [reply pkg/ottl/grammar.go:179]: It does.  Not sure what to do about that yet since we use `.Elide` to remove all whitespace tokens.

Comment (TylerHelmuth) [reply pkg/ottl/grammar.go]: Moving the `=` token after `OpComparison` so that `==` will always be matched first seems to work.

**Review by songy23 — APPROVED** [review]

File: pkg/ottl/grammar.go (hunk 1 above)
Comment (evan-bradley) [reply pkg/ottl/grammar.go]: Nice!

**Review by evan-bradley — APPROVED** [review]
Nice work figuring this one out.
