### PR TITLE
[cmd/opampsupervisor] Fix merging lists when using local config

### LINKED ISSUE #39931: [opampsupervisor] Local config with extensions overwriting opamp extension
### Component(s)

cmd/opampsupervisor

## Description

If you supply the opampsupervisor with a local config for the collector that includes extensions, such as 

```yaml
extensions:
  basicauth:
    client_auth:
      username: username
      password: password

service:
  extensions: [basicauth]
```

Then when the commander passes in the config via an additional config flag the default opamp extension will be removed from the extension list.

The problem occurs here:

https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/61f8c78d4833dfca588db0fa530df1fc79da8413/cmd/opampsupervisor/supervisor/commander/commander.go#L75-L102

The commander doesn't do any fancy merging of the config, it just passes the local config(s) as the last parameters, which means those configs' list take precedence over the supervisor's `effective.yaml`.

## Steps to Reproduce

Configure an opampsupervisor to pass the above local config to its agent

## Expected Result

The agent can start with both the basicauth and opampsupervisor extensions

## Actual Result

only the basicauth extension ends up in the extension list.

### Collector version

latest

### Work Around

In your local config make sure that you add the opampextension to the extension list. For the scenario above the work around is:

```yaml
extensions:
  basicauth:
    client_auth:
      username: username
      password: password

service:
  extensions: [opamp, basicauth]
```

### PR DESCRIPTION
**Pull request by evan-bradley**
#### Description

With https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/38671, we supply the local config to the Collector in two places:
1. The effective (merged) config
2. A list of files passed through `--config` flags to the Collector.

While the second approach is preferable in the long term, we have to manually merge the config for now since the Collector doesn't support merging lists in config without a feature gate enabled. This PR therefore opts for the first option until we enable this feature gate.

Fixes #39931

### CODE REVIEW

**Review by TylerHelmuth — APPROVED** [review]

File: cmd/opampsupervisor/supervisor/commander/commander.go [hunk 1]
```diff
@@ -88,19 +86,6 @@ func (c *Commander) Start(ctx context.Context) error {
...
-		fileName := filepath.Base(conf)
-		newPath := filepath.Join(c.logsDir, fileName)
-		if err := common.CopyFile(conf, newPath); err != nil {
-			return fmt.Errorf("cannot copy config file '%s' to storage directory: %s", conf, err.Error())
-		}
-		c.args = append(c.args, "--config")
-		c.args = append(c.args, newPath)
-	}
-	return nil
-}
```
Comment (douglascamata) [inline cmd/opampsupervisor/supervisor/commander/commander.go:102]: The local configuration files should be copied from wherever they are into the Supervisor's storage dir. Why is this being removed?

I am aware of a small bug in this logic that your code might solve: if you use local configuration in the Supervisor, each time the Collector dies and gets restarted by the Supervisor another `--config local_config.yaml` will be added to the Collector. 

See here my reproduction of this particular issue:

```sh
/etc/otel/supervisor-data $ cat ../supervisor.yaml
server:
  endpoint: "http://host.docker.internal:4320/v1/opamp"
  tls:
    insecure_skip_verify: true

capabilities:
  reports_effective_config: true
  reports_own_metrics: true
  reports_own_logs: true
  reports_own_traces: true
  reports_health: true
  accepts_remote_config: true
  reports_remote_config: true

agent:
  executable: /otelcontribcol

  # This passes config files to the Collector.
  config_files:
    - /etc/otel/config.yaml

  # This adds CLI arguments to the Collector.
  args:
    - ''

  # This adds env vars to the Collector process.
  env: {}

# The storage can be used for many things:
# - It stores configuration sent by the OpAMP server so that new collector
#   processes can start with the most known desired config.
storage:
  directory: /etc/otel/supervisor-data/

telemetry:
  logs:
    level: debug
/etc/otel/supervisor-data $ /opampsupervisor --config /etc/otel/supervisor.yaml > /etc/otel/supervisor.log 2>&1 &
/etc/otel/supervisor-data $ ps aux
PID   USER     TIME  COMMAND
    1 10001     0:00 sh
  222 10001     0:00 /opampsupervisor --config /etc/otel/supervisor.yaml
  263 10001     0:00 /otelcontribcol --config /etc/otel/supervisor-data/effective.yaml --config /etc/otel/supervisor-data/config.yaml
  282 10001     0:00 ps aux
/etc/otel/supervisor-data $ kill 263
/etc/otel/supervisor-data $ ps aux
PID   USER     TIME  COMMAND
    1 10001     0:00 sh
  222 10001     0:00 /opampsupervisor --config /etc/otel/supervisor.yaml
  284 10001     0:00 /otelcontribcol --config /etc/otel/supervisor-data/effective.yaml --config /etc/otel/supervisor-data/config.yaml  --config /etc/otel/supervisor-data/config.yaml
  301 10001     0:00 ps aux
/etc/otel/supervisor-data $
```

**Review by douglascamata — CHANGES_REQUESTED** [review]
I think this PR is useful. But it's solving a different problem than what's stated, imho.

File: cmd/opampsupervisor/supervisor/commander/commander.go (hunk 1 above)
Comment (douglascamata) [reply cmd/opampsupervisor/supervisor/commander/commander.go:102]: Also I don't see how this change here fixes the root problem reported by the issue: configuration's still being merged in the exact same way, you are just not copying the local config into the storage dir.

Comment (douglascamata) [reply cmd/opampsupervisor/supervisor/commander/commander.go:102]: Maybe you forgot to commit changes in the `supervisor.go` file, @evan-bradley?

Comment (douglascamata) [reply cmd/opampsupervisor/supervisor/commander/commander.go:102]: Ah, I think I see it now. The local configuration files are already being merged by `Supervisor.composeAgentConfigFiles` 👍

**Review by douglascamata — APPROVED** [review]

**Comment by douglascamata** [comment]
@evan-bradley we might also want to change the priority order for merging configuration:

https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/a0044fba6fb76f034be52fe7bb466f72b2c2314a/cmd/opampsupervisor/supervisor/supervisor.go#L1243-L1262

This doesn't seem right to me. Local configuration (from `composeAgentConfigFiles`) is being merged first, so it can overwrite the built-in/internal configuration (from `composeExtraLocalConfig`, which I think we should rename to avoid confusion) and also from and own metrics configuration (from `ownMetricsCfg`).

I think local configuration should be the very first to be merged, as they shouldn't override any other configuration.

**Comment by evan-bradley** [comment]
@douglascamata Thanks for taking such a close look. I agree that we should probably make local configuration the lowest priority when merging, but the reason this was done like this is described here: https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/38671#discussion_r1999027964. I think that comment also makes some good points, and in my opinion points to the idea that this should be configurable.

For now I'd like to leave the ordering as-is and fix it in its own PR where we can consider it independently of this issue.

**Comment by douglascamata** [comment]
@evan-bradley sounds good to me. My use case for wanting to have local configuration being the lowest priority is because I want to use it as a "base layer" configuration to allow the Supervisor to start Collectors even without being able to talk to the upstream OpAMP backend.

**Comment by douglascamata** [comment]
For the record, I created an issue for the use cas I mentioned of local configuration with the lowest priority (aka base layer config): https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/39963
