### PR TITLE
Fix metadata fetching when metrics differ by trimmable suffixes

### LINKED ISSUE #6931: Prometheus metrics are merged when they differ by trimmable suffixes
**Describe the bug**
The prometheus receiver is renaming metrics if they differ from another metric by a trimmable suffix, and associating them with the wrong metric metadata.

**Steps to reproduce**

With the metrics:

```
# HELP my_metric_total A counter metric
# TYPE my_metric_total counter
my_metric_total 0.5
# HELP my_metric A gauge metric
# TYPE my_metric gauge
my_metric 2
```

The `my_metric_total` metric is renamed to my_metric, and the gauge metadata is used.  This is because with the current logic, we [checked for a trimmed metric name](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/ebea5bc82e5a146db11d4b496a7a62e2151fe89a/receiver/prometheusreceiver/internal/metricfamily.go#L55) before we [check for the untrimmed metric name](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/ebea5bc82e5a146db11d4b496a7a62e2151fe89a/receiver/prometheusreceiver/internal/metricfamily.go#L61).  So if a metric exists with the metadata for `my_metric`, the `my_metric_total` metric will use that if it exists.

This results in a single metric named `my_metric`, which is a gauge, and has values 0.5 and 2.

**What did you expect to see?**

I expect to see both the `my_metric` and `my_metric_total` with correct metadata, and correct values.

**What version did you use?**
Version: HEAD

**Additional context**

In https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/4865, we handled the case in which the metric `python_gc_objects_collected_total` had metadata under `python_gc_objects_collected`, which was supposed to be how the python client wrote counter metrics.

However, after experimenting with the python client, I found that to be incorrect:
```
# HELP python_gc_objects_collected_total Objects collected during gc
# TYPE python_gc_objects_collected_total counter
python_gc_objects_collected_total{generation="0"} 167.0
python_gc_objects_collected_total{generation="1"} 174.0
python_gc_objects_collected_total{generation="2"} 0.0
```

Python _does_ attach _total to the metric, but it _does not_ send metadata without the _total suffix.  There is a [test case](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/receiver/prometheusreceiver/internal/metricsbuilder_test.go#L246) that tests for that, and should be removed or reworked.

### PR DESCRIPTION
**Pull request by dashpole**
**Description:** <Describe what has changed.>
Fix incorrect merging of metric metadata when metrics differ by trimmable suffixes.  Additionally, remove unnecessary interfaces, and simplify the implementation of metadata fetching to make it more readable.

To fix the bug, first always check for metadata using the original metricName _first_.  We need to do this both when looking up the metric family (in metricsbuilder.go), and when looking up metadata when constructing the initial metric family.  Second,  add the `includesMetric()` function to metricFamily, which ensures that we only merge metrics under types that include multiple series.  For example, if there is an existing family `my_metric`, which is a gauge, it does not include metrics `my_metric` + suffix.

To make the newMetricFamily function more readable, split out a `metadataForMetric` function, which is shared between pdata/opencensus implementations.  This allows us to return early once we have found metadata for the metric, and reduces the number of `else` statements (and nesting) needed to handle all cases correctly.  Also, use a map to store internal metric metadata to avoid needing to recreate the same MetricMetadata frequently for internal metrics.

**Link to tracking Issue:** <Issue number if applicable>
Fixes https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/6931

**Testing:** <Describe what testing was performed and which tests were added.>

As described in https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/6931, the comment prior to `python_gc_collections_total` isn't correct, so I added metadata for `counter_test_total` in the metadata table.

I added metadata for `poor_name` to the testing metadata cash.  Prior to the fixes in this PR, this would cause tests to fail by making `poor_name_count` be incorrectly renamed to `poor_name` and come out as a gauge.

@Aneurysm9 @gracewehner

### CODE REVIEW

**Review by Aneurysm9 — APPROVED** [review]

**Review by gracewehner — APPROVED** [review]
Thanks @dashpole for finding and fixing this!

For `python_gc_objects_collected_total`, when adding some debug lines I still see the `mc.Metadata(metricName)` lookup fail unless it's only looking for `python_gc_objects_collected`, even though the `#TYPE` and `#HELP` hints include `_total`: 
https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/32a4474c8031da873b8d48ef793c5bb93cf0a878/receiver/prometheusreceiver/internal/metricfamily.go#L48 I am still not sure why it behaves like that for the default python counters...

However the metric is still sent with these changes since it then follows this code path: https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/32a4474c8031da873b8d48ef793c5bb93cf0a878/receiver/prometheusreceiver/internal/metricfamily.go#L57-L61

I think it'll be considered a gauge though instead of a counter because of: https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/32a4474c8031da873b8d48ef793c5bb93cf0a878/receiver/prometheusreceiver/internal/metricsbuilder.go#L252-L253

**Review by jpkrohling — DISMISSED** [review]
I believe this is an improvement, but it would be good to address @gracewehner's point before merging.

**Comment by dashpole** [comment]
Figured out what the discrepancy was from.  I think the prometheus server (and thus, the otel collector) add openmetrics headers by default: https://github.com/prometheus/prometheus/blob/27343277fa47465e54799e2a0a5356febe697c29/scrape/scrape.go#L761.

If I curl my python client with: `curl -v localhost:8000/metrics/ --header "Accept: application/openmetrics-text"`, I get 
```
...
< Content-Type: application/openmetrics-text; version=0.0.1; charset=utf-8
< Content-Length: 2098
<
# HELP python_gc_objects_collected Objects collected during gc
# TYPE python_gc_objects_collected counter
python_gc_objects_collected_total{generation="0"} 101.0
python_gc_objects_collected_total{generation="1"} 273.0
python_gc_objects_collected_total{generation="2"} 0.0
...
```

I'll make sure we can handle that case properly

File: receiver/prometheusreceiver/internal/metricfamily.go [hunk 1]
```diff
@@ -48,37 +41,32 @@ type metricFamily struct {
...
+	}, metricName
+}
+
+func newMetricFamily(metricName string, mc MetadataCache, logger *zap.Logger, intervalStartTimeMs int64) *metricFamily {
+	metadata, familyName := metadataForMetric(metricName, mc)
 	ocaMetricType := convToOCAMetricType(metadata.Type)
 
-	// If a counter has a _total suffix but metadata is stored without it, keep _total suffix as the name otherwise
-	// the metric sent won't have the suffix
-	if ocaMetricType == metricspb.MetricDescriptor_CUMULATIVE_DOUBLE && strings.HasSuffix(metricName, metricSuffixTotal) {
```
Comment (dashpole) [inline receiver/prometheusreceiver/internal/metricfamily.go:78]: Now i'm trying to figure out what to do with this... If metric metadata is sent without a type suffix, it would seem strange to add it here, but that is what the previous behavior was.

Comment (dashpole) [reply receiver/prometheusreceiver/internal/metricfamily.go:78]: I'm keeping the current behavior for now, even though it seems strange to me.

**Comment by jpkrohling** [comment]
@dashpole, once this is ready for another review, please notify @gracewehner as well.

**Comment by dashpole** [comment]
@gracewehner I think i've resolved your concern above.  It now correctly handles the openmetrics case above
