### PR TITLE
[pkg/stanza] Stop readerFactory from returning an error when creating an unsafeReader

### LINKED ISSUE #12766: [pkg/stanza] Creating `unsafeReader` returns an error when initialised with `fromBeginning` set to `false`
**Describe the bug**
When a new `Reader` is created by using a `readerBuilder` for a file not set to be read from the beginning, `readerBuilder` overwrites tries to determine the offset in the `build()` function. In particular, this happens when `unsafeReader` is called on the `readerFactory`. This bug caused the `filelog` receiver to crash after restarting.

**Additional context**
This bug has been found because the `filelog` reader did not work correctly.
Steps to reproduce, expected and actual result can be seen here: https://github.com/SumoLogic/sumologic-otel-collector/issues/681

### PR DESCRIPTION
**Pull request by aboguszewski-sumo**
**Description:** 
The method `unsafeReader()` of the `readerBuilder` no longer returns errors when the parameter `isBeginning` is set to `false`. This caused the `filelog` receiver to crash when the collector was restarted and the parameter `start_at` was set to `end` (which was also the default value).

**Link to tracking Issue:** 
Fixes #12766 

**Testing:** 
Manual testing against the test data mentioned in the issue.

### CODE REVIEW

File: pkg/stanza/fileconsumer/reader_factory.go [hunk 1]
```diff
@@ -122,7 +128,8 @@ func (b *readerBuilder) build() (r *Reader, err error) {
 		r.Fingerprint = fp
 	}
 
-	if !b.fromBeginning {
+	// unsafeReader has the file set to nil, so don't try emending its offset.
+	if !b.fromBeginning && !b.isUnsafe {
```
Comment (djaglowski) [inline pkg/stanza/fileconsumer/reader_factory.go:132]: Technically, we don't need the additional variable and associated code, and could just move this block into the `if b.file != nil` condition above. I think the comment you've added would be sufficient to explain why it is located there.

**Review by djaglowski — APPROVED** [review]
Thank you for reporting this and submitting the fix as well. 

I would like to rework the implementation, but this issue is urgent. I've manually verified the issue and tested the fix, so I will merge this now and submit a follow up PR with this suggestion and some test cases.
