### PR TITLE
[exporter/elasticsearch] Deprecate retry::max_requests in favor of retry::max_retries

### LINKED ISSUE #32344: [exporter/elasticsearch] Clarify retry.max_requests behavior
### Component(s)

exporter/elasticsearch

## Description

Docs (code comments, README) do not clearly reflect the meaning of `retry.max_requests`, as in practice it counts the initial publishing attempt as well. Therefore, max_requests=1 means retry is disabled, which is a little counter intuitive.

We should either fix the documentation to align with implementation, or fix the implementation to make it more intuitive. The issue with fixing the implementation is that it is a breaking change for existing users.

Either way, docs need to be updated such that it is clear that the same retry value is used for both HTTP retries and per-document retries, and as a result the total attempts can be greater than max_requests.

## Steps to Reproduce

set retry.max_requests=1, get a per-document 429 from ES

## Expected Result

the document is retried once

## Actual Result

the document is not retried

### Collector version

0.97.0

### Environment information

_No response_

### OpenTelemetry Collector configuration

_No response_

### Log output

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by carsonip**
**Description:** <Describe what has changed.>

The new retry::max_retries will be exactly retry::max_requests - 1, but it will be much more intuitive to the end user. Deprecate retry::max_requests.

**Link to tracking Issue:** <Issue number if applicable>
Fixes #32344

**Testing:** <Describe what testing was performed and which tests were added.>

**Documentation:** <Describe the documentation added.>

### CODE REVIEW

File: exporter/elasticsearchexporter/exporter_test.go [hunk 1]
```diff
@@ -349,14 +349,10 @@ func TestExporterLogs(t *testing.T) {
 
 	t.Run("no retry", func(t *testing.T) {
 		configurations := map[string]func(*Config){
-			"max_requests limited": func(cfg *Config) {
```
Comment (carsonip) [inline exporter/elasticsearchexporter/exporter_test.go:352]: [to reviewer] surprisingly, setting retry::enabled to true and retry::max_requests to 1 in the past will cause 0 to be passed to es client and result in a default of 3 retries. This can be seen as a bug but will be out of scope of this PR. Therefore, I've clarified in the README that user should set retry::enabled to false instead of retry::max_retries to 0

File: exporter/elasticsearchexporter/config.go [hunk 2]
```diff
@@ -169,9 +169,13 @@ type RetrySettings struct {
 	// Enabled allows users to disable retry without having to comment out all settings.
 	Enabled bool `mapstructure:"enabled"`
 
-	// MaxRequests configures how often an HTTP request is retried before it is assumed to be failed.
+	// MaxRequests configures how often an HTTP request is attempted before it is assumed to be failed.
+	// Deprecated: use MaxRetries instead.
 	MaxRequests int `mapstructure:"max_requests"`
 
+	// MaxRetries configures how many times an HTTP request is retried.
+	MaxRetries int `mapstructure:"max_retries"`
```
Comment (crobert-1) [inline exporter/elasticsearchexporter/config.go:177]: Is there a reason this is an `int` instead of `uint`?

File: exporter/elasticsearchexporter/README.md [hunk 3]
```diff
@@ -197,7 +197,8 @@ The behaviour of this bulk indexing can be configured with the following setting
   - `interval` (default=30s): Write buffer flush time limit.
 - `retry`: Elasticsearch bulk request retry settings
   - `enabled` (default=true): Enable/Disable request retry on error. Failed requests are retried with exponential backoff.
-  - `max_requests` (default=3): Number of HTTP request retries.
+  - `max_requests` (DEPRECATED, use retry::max_retries instead): Number of HTTP request retries including the initial attempt.
+  - `max_retries` (default=3): Number of HTTP request retries. To disable retries, set `retry::enabled` to `false` instead of setting `max_retries` to `0`.
```
Comment (crobert-1) [inline exporter/elasticsearchexporter/README.md:201]: Does it matter that the default value is now technically one more retry than before? (Just want to call out potential change in behavior of the default configuration for users here)

Comment (carsonip) [reply exporter/elasticsearchexporter/README.md:201]: Oh! nice catch. Yes let me fix that.

File: exporter/elasticsearchexporter/config.go (hunk 2 above)
Comment (carsonip) [reply exporter/elasticsearchexporter/config.go:177]: I think the libraries elasticsearchexporter uses all have their retries config as int, so it'll be straightforward for us to use int here as well.

Comment (crobert-1) [reply exporter/elasticsearchexporter/config.go:177]: In that case I believe we should add validation then in `Validate()` to ensure it's a non-negative value.

Comment (carsonip) [reply exporter/elasticsearchexporter/config.go:177]: out of curiosity, is there a way to for the user to pass in 0 as an int value in the exporter config, other than using a `*int`? I believe it is indistinguishable from unset and it will be overwritten by a default.

Comment (carsonip) [reply exporter/elasticsearchexporter/config.go:177]: or to put it in a different way, what's the best practice if we want to accept 0 as a valid int configuration value?

Comment (crobert-1) [reply exporter/elasticsearchexporter/config.go:177]: No, there's no way to distinguish if it's `int`.

Since you've called out how to properly disable retries in the README, I'd assume it's enough to not have to worry about users setting the `max_retries` to 0. If anyone ever comments about unexpected behavior, we can simply refer them to the `enabled` config option, and have them set it to false.

To me, it's fine if validate succeeds if `max_retries` is `0`, whether it was set by the user or not.

**Review by crobert-1 — APPROVED** [review]

File: exporter/elasticsearchexporter/config.go [hunk 4]
```diff
@@ -351,11 +363,16 @@ func (cfg *Config) MappingMode() MappingMode {
...
 
-func logConfigDeprecationWarnings(cfg *Config, logger *zap.Logger) {
+func handleDeprecatedConfig(cfg *Config, logger *zap.Logger) {
 	if cfg.Mapping.Dedup != nil {
 		logger.Warn("dedup is deprecated, and is always enabled")
 	}
 	if cfg.Mapping.Dedot && cfg.MappingMode() != MappingECS || !cfg.Mapping.Dedot && cfg.MappingMode() == MappingECS {
 		logger.Warn("dedot has been deprecated: in the future, dedotting will always be performed in ECS mode only")
 	}
+	if cfg.Retry.MaxRequests != 0 {
```
Comment (andrzej-stencel) [inline exporter/elasticsearchexporter/config.go:373]: This means that if user sets both `max_requests` and `max_retries`, the value of `max_requests` will be used, and a warning will be displayed that `max_requests` is deprecated.

Wouldn't it be better to disallow setting both options?

File: exporter/elasticsearchexporter/exporter_test.go (hunk 1 above)
Comment (andrzej-stencel) [reply exporter/elasticsearchexporter/exporter_test.go:352]: Oooh thanks for the clarification :+1:

Comment (andrzej-stencel) [reply exporter/elasticsearchexporter/exporter_test.go:352]: In this case, shouldn't we treat `retry::max_retries: 0` as invalid when `retry::enabled` is `true`?

Comment (carsonip) [reply exporter/elasticsearchexporter/exporter_test.go:352]: I don't think it will ever be 0, because if it is unspecified or 0, we will make it the default = 2. So I wonder how we would ever enforce this

Comment (andrzej-stencel) [reply exporter/elasticsearchexporter/exporter_test.go:352]: Oh, right, the `retry::max_retries` is defined as an `int` and not `*int`, so we won't be able to tell in the `Validate()` method whether the user explicitly set it to `0` or they haven't set it at all. I guess we could either change the type of `retry::max_retries` to `*int`, or just leave it as is and not validate this. I'd rather go with the first option, but the second one is acceptable too, as Curtis [commented](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/35571/files#r1786639764).

File: exporter/elasticsearchexporter/bulkindexer.go [hunk 5]
```diff
@@ -50,27 +50,34 @@ type bulkIndexerSession interface {
 	Flush(context.Context) error
 }
 
+const defaultMaxRetries = 2
```
Comment (carsonip) [inline exporter/elasticsearchexporter/bulkindexer.go:53]: [to reviewer] moving default out of default config, otherwise we cannot detect max_requests !=0 and max_retries != 0 due to default config being initialized first.

File: exporter/elasticsearchexporter/config.go [hunk 6]
```diff
@@ -280,6 +280,9 @@ func (cfg *Config) Validate() error {
 	if cfg.Retry.MaxRetries < 0 {
 		return errors.New("retry::max_retries should be non-negative")
 	}
+	if cfg.Retry.MaxRequests > 0 && cfg.Retry.MaxRetries > 0 {
```
Comment (andrzej-stencel) [inline exporter/elasticsearchexporter/config.go]:
```suggestion
	if cfg.Retry.MaxRequests != 0 && cfg.Retry.MaxRetries != 0 {
```

**Review by andrzej-stencel — APPROVED** [review]
Just a small nit that maybe can be fixed in a follow-up PR

File: exporter/elasticsearchexporter/config.go (hunk 6 above)
Comment (carsonip) [reply exporter/elasticsearchexporter/config.go]: :facepalm: I did exactly that but forgot to push
