### PR TITLE
[receiver/azuremonitorreceiver] Scrape storage account sub types

### LINKED ISSUE #37220: [azuremonitor receiver] Don't scrape metrics namespace when not equal to a resource type
### Component(s)

receiver/azuremonitor

## Description
The azuremonitor receiver is not able to retrieve metrics with a namespace being different from resource type. Typically like {resource type}/something e.g Microsoft.Storage/storageAccounts/blobServices. 

Technically, what it does is that for each resource type, and for each resource, it get metrics definition using this [Azure Metric Definitions - List API](https://learn.microsoft.com/en-us/rest/api/monitor/metric-definitions/list?view=rest-monitor-2023-10-01&tabs=HTTP). Which means that it takes a storage account resource and get the shape of the metrics (metric names, dimensions, etc..) from it. By default it seems to get only the metric namespace that is equal to the name of the resource type "Microsoft.Storage/storageAccounts" and not all the rest "Microsoft.Storage/storageAccounts/*"

So to make it simple it does 

- GET resources of type "Microsoft.Storage/storageAccounts" -> find X resources
- for each resource, GET metrics definition of that resource, and only namespace "Microsoft.Storage/storageAccounts"
- GET resources of type "Microsoft.Storage/storageAccounts/blobServices" -> find nothing
- terminate
=> No metrics collecte for blob services namespace

There is a confusion between Resource type and Metric namespace in Azure that partially overlaps. 
For this reason, we basically have no metrics for the "sub resource types namespaces" of this kind

## Steps to Reproduce
Start an otel collector with an azure receiver and give a for example Microsoft.Storage/storageAccounts/blobServices
```yaml
  azuremonitor/storageaccount-blob-tst:
    cache_resources: 3600
    client_id: <redacted>
    client_secret: <redacted>
    cloud: AzureCloud
    collection_interval: 60s
    initial_delay: 1s
    tenant_id: <redacted>
    services: [ "Microsoft.Storage/storageAccounts/blobServices" ]
    subscription_id: <redacted>
```

## Expected Result
We should have the metrics from the blob services namesapce

## Actual Result
No resources found, so no metrics

### Collector version

v0.117.0

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

### OpenTelemetry Collector configuration

```yaml

```

### Log output

```shell

```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by celian-garcia**
#### Description

This PR is another attempt to fix the problem of Storage Account metrics. Less elegant but more pragmatic. 
I didn't find any pattern that would explain what's occurring with that issue. It seems that some implicit storage account sub resources with suffix like ``/blobServices/default`` etc are always created for each storage account. 
- They're not discoverable.
- No other resource type does the same behavior

Hence this hack to add these implicit sub resources every time we want to scrape storage account metrics.

#### Link to tracking issue
Fixes #37220

#### Testing
Unit tested the functions and tested manually with a real Azure API. The blobServices etc metrics are well retrieved with ``type="Microsoft.Storage/storageAccounts/blobServices"``

#### Documentation
No documentation needed here as it is just working as intended.

### CODE REVIEW

File: receiver/azuremonitorreceiver/scraper_batch.go [hunk 1]
```diff
@@ -307,6 +307,45 @@ func (s *azureBatchScraper) getResourcesAndTypes(ctx context.Context, subscripti
...
 }
 
+// hackResources is a workaround specially done for the storageAccount metrics.
+// Every StorageAccount resources have some implicit sub resources (/blobServices/default, fileServices/default, etc...) that are not returned by the API.
+// We need to add them manually to the resources and resourceTypes map.
+// Note that we do that hack only if the user has asked the sub resource types explicitly in the services config.
+// Example:
+// For each resource with id .../Microsoft.Storage/storageAccount/myResource of type Microsoft.Storage/storageAccount,
+// It will create a fake resource with id .../Microsoft.Storage/storageAccount/myResource/blobServices/default of type Microsoft.Storage/storageAccounts/blobServices.
+// TODO: duplicate
```
Comment (celian-garcia) [inline receiver/azuremonitorreceiver/scraper_batch.go:319]: Note that I have a TODO duplicate on several methods of the two scraper. I would like to address it in another PR to not pollute. I promise I will do it right after this PR will be merged.

File: receiver/azuremonitorreceiver/scraper.go [hunk 2]
```diff
@@ -550,6 +588,15 @@ func getMetricAggregations(metricNamespace, metricName string, filters NestedLis
...
 
+func sliceFindInsensitive(slice []string, value string) (int, bool) {
+	for i, v := range slice {
+		if strings.EqualFold(v, value) {
+			return i, true
+		}
+	}
+	return -1, false
+}
+
```
Comment (MovieStoreGuy) [inline receiver/azuremonitorreceiver/scraper.go]: You should be able to use one of the `slices.IndexFunc` (or similar) instead of defining a custom function for this.

**Review by MovieStoreGuy — COMMENTED** [review]
I am concerned about the potential performance overhead this will add and the additional memory requirements.

Do you mind spending some time checking what is the performance changes with some benchmarks?

File: receiver/azuremonitorreceiver/scraper.go (hunk 2 above)
Comment (celian-garcia) [reply receiver/azuremonitorreceiver/scraper.go]: Thank you for the review @MovieStoreGuy I thought about it and doing the EqualFold at scrape time can be avoided creating a copy of the ``Services`` slice config in lower case at start time. I committed an example showing it.

Thinking again I can even go further because of the character exceptional of this hack. I can build booleans on start, to activate or not storageAccount subtypes hack based on services list. I believe it can improve even more readability and performance.

Comment (celian-garcia) [reply receiver/azuremonitorreceiver/scraper.go]: I created two commits
- One with the lowercase slice built on start https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/44200/commits/4f1ff2494ec013d17b2e826151a23401004a2b87
- One with simple hack activations booleans built on start https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/44200/commits/aae70a22a7802dafc5c1b1668ab6b6db920eb78c

I let you tell me your pref. Mine is second. Because hack for hack it doesn't need to be dynamically computed.

File: receiver/azuremonitorreceiver/scraper.go [hunk 3]
```diff
@@ -98,14 +99,31 @@ func (*timeWrapper) Now() time.Time {
 	return time.Now()
 }
 
+type storageAccountHackConfig struct {
```
Comment (MovieStoreGuy) [inline receiver/azuremonitorreceiver/scraper.go]: I feel like we should we add a comment around this considering we are outwardly calling it a hack.

File: receiver/azuremonitorreceiver/scraper.go [hunk 4]
```diff
@@ -319,6 +338,64 @@ func (s *azureScraper) getResources(ctx context.Context, subscriptionID string)
...
 }
 
+// hackResources is a workaround specially done for the storageAccount metrics.
+// Every StorageAccount resources have some implicit sub resources (/blobServices/default, fileServices/default, etc...) that are not returned by the API.
+// We need to add them manually to the resources and resourceTypes map.
+// Note that we do that hack only if the user has asked the sub resource types explicitly in the services config.
+// Example:
+// For each resource with id .../Microsoft.Storage/storageAccount/myResource of type Microsoft.Storage/storageAccount,
+// It will create a fake resource with id .../Microsoft.Storage/storageAccount/myResource/blobServices/default of type Microsoft.Storage/storageAccounts/blobServices.
+// TODO: duplicate
```
Comment (MovieStoreGuy) [inline receiver/azuremonitorreceiver/scraper.go]: If this hack is permanent then it isn't really hack it is more a transformation, or translation. 

The question is, will this method be removed in future, or is this a temporary addition?

File: receiver/azuremonitorreceiver/scraper.go [hunk 5]
```diff
@@ -319,6 +338,64 @@ func (s *azureScraper) getResources(ctx context.Context, subscriptionID string)
...
+func (s *azureScraper) hackResources(resources []*armresources.GenericResourceExpanded) []*armresources.GenericResourceExpanded {
+	var hackedResources []*armresources.GenericResourceExpanded
```
Comment (MovieStoreGuy) [inline receiver/azuremonitorreceiver/scraper.go]: I have a feeling the verb `hacked` may scare some users that are just glancing through the project, could you use a different name here?

File: receiver/azuremonitorreceiver/scraper.go [hunk 6]
```diff
@@ -319,6 +338,64 @@ func (s *azureScraper) getResources(ctx context.Context, subscriptionID string)
...
+}
+
+// hackResource creates a fake new resource with give type and ID.
+// The rest of the attributes (location, tags, etc...) are copied from the original resource.
+// TODO: duplicate
+func (s *azureScraper) hackResource(resource *armresources.GenericResourceExpanded, newResourceType, newResourceID string) *armresources.GenericResourceExpanded {
+	hackedResource, err := copyResource(resource)
+	if err != nil {
+		s.settings.Logger.Error("failed to create a hack resource",
+			zap.String("resource type", *resource.Type),
```
Comment (MovieStoreGuy) [inline receiver/azuremonitorreceiver/scraper.go]: I believe there is a stringp type that does the check to see if the pointer is set or not.

Comment (MovieStoreGuy) [reply receiver/azuremonitorreceiver/scraper.go]: Also, if copy resource fails, is it likely that this will fail due to resource being nil?

File: receiver/azuremonitorreceiver/scraper.go [hunk 7]
```diff
@@ -587,3 +664,16 @@ func filterResourceTags(tagFilterList map[string]struct{}, resourceTags map[stri
...
+	hackedResourceStr, err := original.MarshalJSON()
+	if err != nil {
+		return nil, err
+	}
+	var newResource armresources.GenericResourceExpanded
+	err = newResource.UnmarshalJSON(hackedResourceStr)
+	if err != nil {
+		return nil, err
+	}
+	return &newResource, nil
```
Comment (MovieStoreGuy) [inline receiver/azuremonitorreceiver/scraper.go]: This feels rather heavy handed in order to perform a deep clone, is there a way to do this without constructing a json object?

**Review by MovieStoreGuy — COMMENTED** [review]
Sorry, I had some time to review the code. 

I am mostly concerned about performing a copy via json serde, is there a way around this?

File: receiver/azuremonitorreceiver/scraper.go (hunk 7 above)
Comment (celian-garcia) [reply receiver/azuremonitorreceiver/scraper.go]: argh yeah you're definitely right. There are several lib for deep copy but I see that in this repo:
https://github.com/mohae/deepcopy

There is also this one that we use internally
https://github.com/brunoga/deep

let me bench that since it's definitely something important in my implementation

File: receiver/azuremonitorreceiver/scraper.go (hunk 5 above)
Comment (celian-garcia) [reply receiver/azuremonitorreceiver/scraper.go]: You're completely right hack is not serious. I'm currently replacing "hack" or "fake" wording.

Comment (celian-garcia) [reply receiver/azuremonitorreceiver/scraper.go]: ✅  Renamed ``hackedResources`` to ``subTypeResources``

File: receiver/azuremonitorreceiver/scraper.go (hunk 4 above)
Comment (celian-garcia) [reply receiver/azuremonitorreceiver/scraper.go]: ✅  Renamed ``hackResources()`` to ``processResources()``

File: receiver/azuremonitorreceiver/scraper.go (hunk 6 above)
Comment (celian-garcia) [reply receiver/azuremonitorreceiver/scraper.go]: ✅  No more error to manage and resource nil is managed with an if on top

File: receiver/azuremonitorreceiver/scraper.go (hunk 7 above)
Comment (celian-garcia) [reply receiver/azuremonitorreceiver/scraper.go]: ✅  I made a benchmarck (see new .md file added) and I found a clone library even better and which is already in the deps of otelcollector contrib

File: receiver/azuremonitorreceiver/scraper.go (hunk 3 above)
Comment (celian-garcia) [reply receiver/azuremonitorreceiver/scraper.go]: ✅  Renamed ``storageAccountHackConfig`` to ``storageAccountSpecificConfig``

**Review by MovieStoreGuy — APPROVED** [review]
