### PR TITLE
[exporter/azuremonitor] Support handling log exceptions

### LINKED ISSUE #38432: [azuremonitorexporter] LogRecordToEnvelope does not handle exceptions
### Component(s)

exporter/azuremonitor

## Description
When using azuremonitor as exporter using the Otel Contrib distribution, exceptions which are logged per symantec definition of OpenTelemetry is forward to Azure Monitor as traces, not exceptions.

## Steps to Reproduce

1. Setup otel azuremonitor contrib.
2. Configure span to include required attributes exception.type, exception.message
3. Await data in application insights, and verify that no exceptions has been logged, but an entry in traces exists.

## Expected Result
Log records of span specified as exceptions, end in the exceptions table.

## Actual Result
Log records appear in traces table.

## Suggested code change:

Alter log_to_envelope.go. Change `LogRecordToEnvelope(*)` to use `contracts.NewExceptionData()` when span attributes fulfill the symantec specification of an exception.

### Collector version

v.0.120.0

## Environment
OS: Ubuntu 20.04 and Windows 11.102

### OpenTelemetry Collector configuration

```yaml

```

### Log output

```shell

```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by hgaol**
#### Description

Support handling exceptions to azure application insights `exceptions` table, and the logic aligned with implementation in azure SDK like [js](https://github.com/Azure/azure-sdk-for-js/blob/main/sdk/monitor/monitor-opentelemetry-exporter/src/utils/logUtils.ts#L78C3-L78C67), [python](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/monitor/azure-monitor-opentelemetry-exporter/azure/monitor/opentelemetry/exporter/export/logs/_exporter.py#L143).

#### Link to tracking issue
Fixes #38432 .

#### Testing

1. added unit tests.
2. validated using 2 application insights. some results showed below.

image

#### Documentation

As described in README.md

### CODE REVIEW

File: exporter/azuremonitorexporter/config.go [hunk 1]
```diff
@@ -12,13 +12,14 @@ import (
...
+	QueueSettings         exporterhelper.QueueBatchConfig `mapstructure:"sending_queue"`
+	Endpoint              string                          `mapstructure:"endpoint"`
+	ConnectionString      configopaque.String             `mapstructure:"connection_string"`
+	InstrumentationKey    configopaque.String             `mapstructure:"instrumentation_key"`
+	MaxBatchSize          int                             `mapstructure:"maxbatchsize"`
+	MaxBatchInterval      time.Duration                   `mapstructure:"maxbatchinterval"`
+	SpanEventsEnabled     bool                            `mapstructure:"spaneventsenabled"`
+	ShutdownTimeout       time.Duration                   `mapstructure:"shutdown_timeout"`
+	CustomEventsEnabled   bool                            `mapstructure:"custom_events_enabled"`
+	ExceptionEventEnabled bool                            `mapstructure:"exception_events_enabled"`
```
Comment (atoulme) [inline exporter/azuremonitorexporter/config.go:24]:
```suggestion
	ExceptionEventsEnabled bool                            `mapstructure:"exception_events_enabled"`
```

**Review by atoulme — APPROVED** [review]
just a nit on naming

File: exporter/azuremonitorexporter/config.go (hunk 1 above)
Comment (hgaol) [reply exporter/azuremonitorexporter/config.go]: updated.
