### PR TITLE
[pkg/stanza] Ensure `container` parser respects the `if` condition and `on_error` settings when format detection fails

### LINKED ISSUE #41508: [pkg/stanza] `container` parser does not respect the `if` or `on_error` options when container log format is unrecognized
### Component(s)

pkg/stanza

## Description

The [container](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/v0.130.0/pkg/stanza/docs/operators/container.md) parser fails to process logs that are not formatted according to one of the known container runtime formats (Docker or Containerd or CRI-O).

These non-Kubernetes logs are processed even if they are supposed to be excluded from processing via the `if` option.

Error is logged for each such log and the entry is dropped even if `on_error: send_quiet` is configured.

## Steps to Reproduce

1. Prepare input files `/tmp/k8s.log` and `/tmp/non-k8s.log` as below

`/tmp/k8s.log`

```
2025-05-15T15:50:37.505201169-07:00 stdout F a random container log
```

`/tmp/non-k8s.log`

```
a random non-k8s log
```

2. Run the collector with the below configuration 

## Expected Result

- Both logs should be exported, because `on_error` is set to `send_quiet`
- No error should be logged, because the non-k8s log should not be processed according to the `if` option

## Actual Result

- The log from the `non-k8s.log` file is not exported
- Error "failed to emit token" is logged

### Collector version

v0.130.0

### Environment information

Any

### OpenTelemetry Collector configuration

```yaml
service:
  pipelines:
    logs:
      receivers:
        - filelog
      exporters:
        - debug

  telemetry:
    logs:
      level: warn # Exclude info logs for clarity

receivers:
  filelog:
    include:
      - /tmp/k8s.log
      - /tmp/non-k8s.log
    include_file_path: true
    start_at: beginning
    operators:
      - type: container
        if: attributes["log.file.name"] == "k8s.log"
        add_metadata_from_filepath: false

exporters:
  debug:
    use_internal_logger: false
    verbosity: normal
```

### Log output

```shell
$ otelcol-contrib-0.130.0-linux_amd64 --config 0723-container-if.yaml
2025-07-23T12:41:32.443+0200    error   reader/reader.go:246    failed to emit token    {"resource": {"service.instance.id": "ece82c5e-1b99-423a-9cef-a625f5b6eab3", "service.name": "otelcol-contrib", "service.version": "0.130.0"}, "otelcol.component.id": "filelog", "otelcol.component.kind": "receiver", "otelcol.signal": "logs", "component": "fileconsumer", "path": "non-k8s.log", "error": "consume entries: failed to detect a valid container log format: entry cannot be parsed as container logs: a random non-k8s log"}
github.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza/fileconsumer/internal/reader.(*Reader).readContents
        github.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza@v0.130.0/fileconsumer/internal/reader/reader.go:246
github.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza/fileconsumer/internal/reader.(*Reader).ReadToEnd
        github.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza@v0.130.0/fileconsumer/internal/reader/reader.go:120
github.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza/fileconsumer.(*Manager).consume.func1
        github.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza@v0.130.0/fileconsumer/file.go:169
Logs    {"resource logs": 1, "log records": 1}
ResourceLog #0
ScopeLog #0
a random container log log.file.path=k8s.log log.file.name=k8s.log log.iostream=stdout logtag=F
```

### Additional context

If I understand correctly, this is because the [container format recognition](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/pkg/stanza/operator/parser/container/parser.go#L81-L84) is done before `if` condition is evaluated.

### Tip

<sub>[React](https://github.blog/news-insights/product-news/add-reactions-to-pull-requests-issues-and-comments/) with 👍 to help prioritize this issue. Please use comments to provide useful context, avoiding `+1` or `me too`, to help us triage it. Learn more [here](https://opentelemetry.io/community/end-user/issue-participation/).</sub>

### PR DESCRIPTION
**Pull request by paulojmdias**
#### Description

Ensure `container` parser respects the `if` condition and `on_error` settings when format detection fails.

#### Link to tracking issue
Fixes #41508

#### Testing

Added tests to validate the expected behaviour.

### CODE REVIEW

File: pkg/stanza/operator/parser/container/parser.go [hunk 1]
```diff
@@ -76,11 +76,20 @@ func (p *Parser) ProcessBatch(ctx context.Context, entries []*entry.Entry) error
 
 // Process will parse an entry of Container logs
 func (p *Parser) Process(ctx context.Context, entry *entry.Entry) (err error) {
+	// Short circuit if the "if" condition does not match
+	skip, err := p.Skip(ctx, entry)
+	if err != nil {
+		return p.HandleEntryError(ctx, entry, err)
```
Comment (ChrsMark) [inline pkg/stanza/operator/parser/container/parser.go:82]: I remember that we had found the usage of the `HandleEntryError` a bit tricky "recently": https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/35726#issuecomment-2447241709

In this, I'm not quite sure if this fix will be enough (it might be).

Since I'm not really fresh on this and I don't really have the time to spend on this pkg, @andrzej-stencel @paulojmdias please feel free to refactor as needed here according to stanza's patterns. Let me know if there is anything "container" specific.

**Review by andrzej-stencel — APPROVED** [review]
From my local testing the fix appears to work as intended 👍 I have no knowledge as to why the skip code was originally only invoked after the format detection. The code looks good to me. Thank you @paulojmdias!

File: pkg/stanza/operator/parser/container/parser.go (hunk 1 above)
Comment (andrzej-stencel) [reply pkg/stanza/operator/parser/container/parser.go:82]: Thanks Christos for taking a look. Even if the fix is not enough, it should be an improvement from the current situation.
