### PR TITLE
[exporter/elasticsearch] Fix regression `retry::max_retries` not applying correctly for HTTP request levels retries

### LINKED ISSUE #39670: [exporter/elasticsearch] retry setting not take effect after the es down
### Component(s)

exporter/elasticsearch

## Description
I use exporter's persistent queue to ensure that logs are not lost when es is offline,
My collection solution is ： opentelemetry sdk->collector(use elasticsearch exporter)->elasticsearch
I configured sending_queue, but found that retry_on_failure does not work in elasticsearch exporter, so I configured retry
after es is offline and restarted, the logs are not retried as expected but lost, and use retry_on_failure for otlp jaeger can work.
Please help me see if there is a problem with the configuration or how to ensure that log not lost
## Steps to Reproduce
1. docker stop es
2. send request for generate logs for collector
3. after at least 10 min then docker start es
## Expected Result
es will collect logs of requests during service offline
## Actual Result
no collect and log loss

### Collector version

v0.123.0

## Environment
linux docker

### OpenTelemetry Collector configuration

```yaml
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
        cors:
          allowed_origins:
            - "http://*"
            - "https://*"
  docker_stats:
    endpoint: unix:///var/run/docker.sock

exporters:
  debug:
  #verbosity: detailed
  otlp:
    endpoint: "jaeger:8027"
    tls:
      insecure: true
    retry_on_failure:
      enabled: true
      initial_interval: 5s
      max_interval: 168h
      max_elapsed_time: 168h
    sending_queue:
      enabled: true
      storage: file_storage/otlp
      queue_size: 1073741824
  elasticsearch:
    tls:
      insecure: false
    endpoints: ["xxxx:8011"] 
    logstash_format:
      enabled: true
    timeout: 2m
    discover:
      on_start: true
      interval: 5
    retry:
      enabled: true
      max_retries: 100000
      initial_interval: 5s
      max_interval: 168h
      retry_on_status:
        - 429
        - 500
        - 502
        - 503
        - 504
    flush:
      bytes: 10485760
    sending_queue:
      enabled: true
      storage: file_storage/es
      queue_size: 1073741824

extensions:
  file_storage/es:
    directory: /var/lib/storage/es
    timeout: 10s
  file_storage/otlp:
    directory: /var/lib/storage/otlp
    timeout: 10s

service:
  extensions: [file_storage/es, file_storage/otlp]
  telemetry:
    logs:
      level: debug
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp, debug]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [elasticsearch, debug]
```

### Log output

```shell
2025-04-26T03:23:17.302Z        debug   elasticsearchexporter@v0.123.0/esclient.go:71   Request failed. {"reason": "dial tcp xxxx:8011: connect: connection refused"}
2025-04-26T03:23:18.239Z        debug   elasticsearchexporter@v0.123.0/esclient.go:71   Request failed. {"reason": "dial tcp xxxx:8011: connect: connection refused"}
2025-04-26T03:23:57.171Z        error   elasticsearchexporter@v0.123.0/bulkindexer.go:348       bulk indexer flush error        {"error": "failed to execute the request: context deadline exceeded"}
github.com/open-telemetry/opentelemetry-collector-contrib/exporter/elasticsearchexporter.flushBulkIndexer
        github.com/open-telemetry/opentelemetry-collector-contrib/exporter/elasticsearchexporter@v0.123.0/bulkindexer.go:348
github.com/open-telemetry/opentelemetry-collector-contrib/exporter/elasticsearchexporter.(*asyncBulkIndexerWorker).flush
        github.com/open-telemetry/opentelemetry-collector-contrib/exporter/elasticsearchexporter@v0.123.0/bulkindexer.go:331
github.com/open-telemetry/opentelemetry-collector-contrib/exporter/elasticsearchexporter.(*asyncBulkIndexerWorker).run
        github.com/open-telemetry/opentelemetry-collector-contrib/exporter/elasticsearchexporter@v0.123.0/bulkindexer.go:324
github.com/open-telemetry/opentelemetry-collector-contrib/exporter/elasticsearchexporter.newAsyncBulkIndexer.func1
        github.com/open-telemetry/opentelemetry-collector-contrib/exporter/elasticsearchexporter@v0.123.0/bulkindexer.go:217
2025-04-26T03:23:57.172Z        error   elasticsearchexporter@v0.123.0/bulkindexer.go:348       bulk indexer flush error        {"error": "failed to execute the request: context deadline exceeded"}
github.com/open-telemetry/opentelemetry-collector-contrib/exporter/elasticsearchexporter.flushBulkIndexer
        github.com/open-telemetry/opentelemetry-collector-contrib/exporter/elasticsearchexporter@v0.123.0/bulkindexer.go:348
github.com/open-telemetry/opentelemetry-collector-contrib/exporter/elasticsearchexporter.(*asyncBulkIndexerWorker).flush
        github.com/open-telemetry/opentelemetry-collector-contrib/exporter/elasticsearchexporter@v0.123.0/bulkindexer.go:331
github.com/open-telemetry/opentelemetry-collector-contrib/exporter/elasticsearchexporter.(*asyncBulkIndexerWorker).run
        github.com/open-telemetry/opentelemetry-collector-contrib/exporter/elasticsearchexporter@v0.123.0/bulkindexer.go:324
github.com/open-telemetry/opentelemetry-collector-contrib/exporter/elasticsearchexporter.newAsyncBulkIndexer.func1
        github.com/open-telemetry/opentelemetry-collector-contrib/exporter/elasticsearchexporter@v0.123.0/bulkindexer.go:217
```

### Additional context

_No response_

### LINKED ISSUE #40488: [exporter/elasticsearchexporter/integrationtest]: Report for failed tests on main
Auto-generated report for `__run_3` job build.

Link to failed build: https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/15446943365

#### Test Failures
-  `TestExporter/metrics/batcher_enabled_es_intermittent_failure`
-  `TestExporter`

**Note**: Information about any subsequent build failures that happen while
this issue is open, will be added as comments with more information to this issue.

### PR DESCRIPTION
**Pull request by carsonip**
#### Description

`retry::max_retries` that gets passed to ES client is incorrectly overwritten if `retry::max_retries` > 2. This causes HTTP requests to give up retrying much sooner than expected, which affects scenario where ES is down and data may be lost due to this bug.

This was a regression from #37333, released in v0.120.0

Re-enable integration test.

#### Link to tracking issue
Fixes #39670 
Fixes #40488

### CODE REVIEW

File: exporter/elasticsearchexporter/esclient.go [hunk 1]
```diff
@@ -145,7 +150,7 @@ func newElasticsearchClient(
 		RetryOnError: func(_ *http.Request, err error) bool {
 			return !errors.Is(err, context.Canceled) && !errors.Is(err, context.DeadlineExceeded)
 		},
-		MaxRetries:   min(defaultMaxRetries, config.Retry.MaxRetries),
```
Comment (axw) [inline exporter/elasticsearchexporter/esclient.go:148]: Yikes, I don't know what I was thinking. Can we add a unit test that would have failed, so I don't make the same stupid mistake twice? :sweat_smile:

**Review by andrzej-stencel — APPROVED** [review]

File: exporter/elasticsearchexporter/esclient.go (hunk 1 above)
Comment (carsonip) [reply exporter/elasticsearchexporter/esclient.go:148]: done in 9b7ee9de30a274813ca2507042c79af2a0551056

Comment (carsonip) [reply exporter/elasticsearchexporter/esclient.go:148]: confirmed that the test failed before the fix. 

> Yikes, I don't know what I was thinking. 

oh well, I am equally guilty :face_exhaling:

**Comment by carsonip** [comment]
Blocked by https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/41188

**Review by axw — APPROVED** [review]
