### PR TITLE
Fix: zero_threshold reset in exponential histograms

### LINKED ISSUE #46108: prometheusremotewrite v2 reset delta_thresholds to "zero"
### Component(s)

exporter/prometheusremotewrite

## Description
I am sending exponential histograms from SpringBoot 3.5.8 to opentelemetry collector and forwarding them further to otlp and to prometheus remote write v2.

SpringBoot is sending zero_threshold value 20 by default (20ms or 20ns) , which I can see being rounded to zero_threshold=0.019999999999999997, when I decode the otlp protocol buffer requests.  Also when exporting otlp the value remains correct. otlp debug does not show the zero_threshold value

However I can see that native exponential histogram conversion to prometheus remote write v2 works, except that zero_threshold value is reset to value 1.000000e-128. I can see the value when I decode the remete write requests. 
I can see also value when reading the metrics from prometheus.

Wrong zero_threshold cause issues rendering the histograms.

## Steps to Reproduce
Create service which generate http_server and/or http_clientmetrics, and export native histograms in otlp format.

If you use SpribgBoot then configure spring boot to send exponential metrics. 
You can also use otel libraries to generate metrics.
```
management.otlp.metrics.step=30s
management.otlp.metrics.export.url=http://localhost:24318/v1/metrics
management.otlp.metrics.export.enabled=true
management.otlp.metrics.export.aggregation-temporality=cumulative
management.otlp.metrics.export.base-time-unit=seconds
management.otlp.metrics.export.histogram-flavor=base2_exponential_bucket_histogram

management.metrics.distribution.percentile-histogram.http=true
```

Configute otel contrib collector 0.145
```
receivers:
  otlp:
    protocols:
      http:
        endpoint: "0.0.0.0:24318"

exporters:
  debug:
    verbosity: detailed
  otlphttp:
    endpoint: http://localhost:4318
    compression: none
    tls:
      insecure: true
  prometheusremotewrite:
    endpoint: "http://localhost:19091/api/v1/write"
    protobuf_message: io.prometheus.write.v2.Request
    tls:
      insecure: true

service:
  pipelines:
    metrics:
      receivers: [otlp, spanmetrics, count]
      exporters: [prometheus, prometheus/servicegraph, prometheusremotewrite, debug, otlphttp]
    metrics/servicegraph:
      receivers: [servicegraph]
      exporters: [prometheus/servicegraph]
    traces:
      #receivers: [otlp, zipkin]
      receivers: [otlp]
      processors: [memory_limiter, batch, filter, transform]
      exporters: 
      - otlphttp
      - servicegraph
      - spanmetrics
      - count
      - debug

  telemetry:
    logs:
      level: debug
      initial_fields:
        service: my-instance
    metrics:
      level: detailed


```
## Expected Result

zero_threshold value remain unchanged

## Actual Result
Apparently promotmeusremotewrite v2 exporter is not setting value from otel native histogram and use default value instead.

## Otel logs not shoring zero_threshold

```
Buckets #0, Count: 1061
Metric #31
Descriptor:
     -> Name: http.server.requests
     -> Description:
     -> Unit: seconds
     -> DataType: ExponentialHistogram
     -> AggregationTemporality: Cumulative
ExponentialHistogramDataPoints #0
Data point attributes:
     -> app: Str(xxx)
     -> error: Str(none)
     -> exception: Str(none)
     -> outcome: Str(SUCCESS)
     -> springBoot: Str(3.5.8)
     -> status: Str(200)
     -> uri: Str((info)
StartTimestamp: 2026-02-16 10:08:45.136 +0000 UTC
Timestamp: 2026-02-16 10:27:16.62 +0000 UTC
Count: 147700
Sum: 64692.115425
Bucket (0.042320, 0.044194], Count: 2
Bucket (0.044194, 0.046151], Count: 1
Bucket (0.046151, 0.048194], Count: 13
Bucket (0.048194, 0.050328], Count: 6
Bucket (0.050328, 0.052556], Count: 16
Bucket (0.052556, 0.054883], Count: 16
```

## decoded otel message showing correct zero_threshold
```
    Metric #31: http.server.requests
      Unit: seconds
      Type: ExponentialHistogram
      DataPoints: 1
        [0] labels={app=xxx, error=none, exception=none, method=GET, outcome=SUCCESS, springBoot=3.5.8, status=200, uri=/info } 
        [0] time_unix_nano=1771237636620000000 start_time_unix_nano=1771236525136000000 count=147700 sum=64692.115425 scale=4 zero_count=0 zero_threshold=0.019999999999999997 positive_bucket_counts=104

```
## decoded prometheus reqote write v2 containing wrong zero_threshold
```
    Metadata: type=METRIC_TYPE_HISTOGRAM help= unit=seconds
  TimeSeries #109:
    Labels (16 pairs):
      __name__=http_server_requests_seconds,app=xxx,error=none,exception=none,job="zzz",method=GET,outcome=SUCCESS,springBoot=3.5.8,status=200,uri=/info
    Samples: 0
    Histograms: 1
      [0] timestamp=1771237636620 start_timestamp=0
          count_int=147700 sum=64692.115425
           zero_threshold=1.000000e-128 schema=4
    Metadata: type=METRIC_TYPE_HISTOGRAM help= unit=seconds
```

### Collector version

0.145

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

### OpenTelemetry Collector configuration

```yaml

```

### Log output

```shell

```

### Additional context

_No response_

### Tip

<sub>[React](https://github.blog/news-insights/product-news/add-reactions-to-pull-requests-issues-and-comments/) with 👍 to help prioritize this issue. Please use comments to provide useful context, avoiding `+1` or `me too`, to help us triage it. Learn more [here](https://opentelemetry.io/community/end-user/issue-participation/).</sub>

### PR DESCRIPTION
**Pull request by singhvibhanshu**
#### Description
This PR fixes an issue where the `zero_threshold` in exponential histograms was being reset to the default value (1e-128) even when a specific threshold was provided in the OTLP data.

#### Link to tracking issue
Fixes #46108

#### Testing
- Verified that `make test` passes in `pkg/translator/prometheusremotewrite`.
- Logic ensures `ZeroThreshold` is only used if the value from the data point is non-zero.

### CODE REVIEW

**Comment by atoulme** [comment]
Please add a changelog.

**Comment by singhvibhanshu** [comment]
I've added the changelog entry.

File: pkg/translator/prometheusremotewrite/histograms.go [hunk 1]
```diff
@@ -77,9 +77,12 @@ func exponentialToNativeHistogram(p pmetric.ExponentialHistogramDataPoint) (prom
 		Schema:    scale,
 
 		ZeroCount: &prompb.Histogram_ZeroCountInt{ZeroCountInt: p.ZeroCount()},
-		// TODO use zero_threshold, if set, see
-		// https://github.com/open-telemetry/opentelemetry-proto/pull/441
-		ZeroThreshold: defaultZeroThreshold,
+		ZeroThreshold: func() float64 {
```
Comment (dashpole) [inline pkg/translator/prometheusremotewrite/histograms.go]: Its a bit odd to define a function here.  I would prefer just moving the initialization logic for ZeroThreshold to just below the struct declaration (similar to Sum)

**Comment by dashpole** [comment]
Please add a unit test.

File: pkg/translator/prometheusremotewrite/histograms.go (hunk 1 above)
Comment (singhvibhanshu) [reply pkg/translator/prometheusremotewrite/histograms.go]: Thanks!
Completely agree with you.
I've removed the inline function and moved the `ZeroThreshold` initialization logic just below the struct declaration to match how `Sum` is handled.

**Comment by singhvibhanshu** [comment]
> Please add a unit test.

I added a new test case (`convert exp. to native histogram with specific zero_threshold`) to `TestExponentialToNativeHistogram` to verify the new logic.

Here are the successful test logs for the package:
```
prometheusremotewrite git:(fix/zero_threshold-prometheusremotewrite) ✗ make test
/home/singhvibhanshu/.cache/go-build/da/daec4766e6722172b5532bee30884b4241deb4988f40a60d9077c29c92c5b52a-d/gotestsum --rerun-fails=1 --packages="./..." -- -race -timeout 900s -parallel 4 --tags=""
✓  . (1.037s)

DONE 223 tests in 1.037s
```

**Review by ArthurSens — APPROVED** [review]
Thanks!
