### PR TITLE
kafka receiver exposes some metrics by partition (fixes #30177)

### LINKED ISSUE #30177: Kafka receiver does not render otelcol_kafka_receiver_current_offset correctly
### Component(s)

_No response_

## Description
The Kafka receiver only reports `otelcol_kafka_receiver_current_offset` metrics for a single partition. e.g. If I have a 10-partition topic, and three collectors, each will render the metric once.

The value reported is correct for the single partition that is being reported on; the rest are just missing

## Steps to Reproduce
* Create a multi-partition kafka topic
* Produce otlp spans, ensuring all partitions contain records
* Inspect http://<collector>:8888/metrics

## Expected Result

Each partition has its offset reported, with a `partition` tag (ideally)
```
otelcol_kafka_receiver_current_offset{partition=0} 50,001
otelcol_kafka_receiver_current_offset{partition=3} 50,002
otelcol_kafka_receiver_current_offset{partition=6} 50,003
otelcol_kafka_receiver_current_offset{partition=9} 50,004
```

## Actual Result
Only one partition has its offset reported.  I omitted some uninteresting tag, but note that `name` was an empty string
```
otelcol_kafka_receiver_current_offset{name=""} 50,002
```

### Collector version

0.91.0

## Environment
OS: linux
Compiler(if manually compiled): (e.g., "go 14.2")

### OpenTelemetry Collector configuration

```yaml
receivers:
  kafka:
    brokers:
      - some.kafka1:9092
      - some.kafka2:9092
      - some.kafka3:9092
    topic: otlp_spans
    encoding: otlp_proto
    group_id: otel-collector-backend
  
  processors:
    memory_limiter:
      limit_mib: 400
      spike_limit_mib: 60 # 15% of (pod memory - 100mi)
      check_interval: 5s
  exporters:
    otlp:
      endpoint: some-collector.telemetry.svc:4317
      tls:
        insecure: true
  extensions:
    health_check:
      endpoint: 0.0.0.0:13133
  service:
    extensions:
      - health_check
    pipelines:
      traces:
        receivers:
          - kafka
        processors:
          - memory_limiter
        exporters:
          - otlp
```

### Log output

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by spadger**
**Description:**

Fixes [#30177](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/30177) The Kafka receiver now exposes the following metrics according to partition.  Beforehand, if a collector were consuming from 10 partitions, one of each metric would be rendered, with its value fluctuating according to the state of each partition's consumer.  Now the metrics endpoint will expose 10 sets of metrics, each with a `partition` tag.

* kafka_receiver_messages
* kafka_receiver_current_offset
* kafka_receiver_offset_lag

**Testing:**
* Unit tests were run
* Stats endpoint observed manually for correctness
* Scraped stats charted in Prometheus to ensure stability

Example output:
```
otelcol_kafka_receiver_messages{name="",partition="0",service_instance_id="db3bae97-1856-4b49-85cb-8559db48f345",service_name="otelcontribcol",service_version="0.91.0-dev"} 29
otelcol_kafka_receiver_messages{name="",partition="1",service_instance_id="db3bae97-1856-4b49-85cb-8559db48f345",service_name="otelcontribcol",service_version="0.91.0-dev"} 32
otelcol_kafka_receiver_messages{name="",partition="10",service_instance_id="db3bae97-1856-4b49-85cb-8559db48f345",service_name="otelcontribcol",service_version="0.91.0-dev"} 32
otelcol_kafka_receiver_messages{name="",partition="11",service_instance_id="db3bae97-1856-4b49-85cb-8559db48f345",service_name="otelcontribcol",service_version="0.91.0-dev"} 28
otelcol_kafka_receiver_messages{name="",partition="12",service_instance_id="db3bae97-1856-4b49-85cb-8559db48f345",service_name="otelcontribcol",service_version="0.91.0-dev"} 36
otelcol_kafka_receiver_messages{name="",partition="13",service_instance_id="db3bae97-1856-4b49-85cb-8559db48f345",service_name="otelcontribcol",service_version="0.91.0-dev"} 38
```

**Documentation:**
None added

### CODE REVIEW

**Review by mx-psi — COMMENTED** [review]
Pinging codeowners @pavolloffay @MovieStoreGuy

File: receiver/kafkareceiver/kafka_receiver.go [hunk 1]
```diff
@@ -446,7 +447,10 @@ func (c *tracesConsumerGroupHandler) ConsumeClaim(session sarama.ConsumerGroupSe
 			}
 
 			ctx := c.obsrecv.StartTracesOp(session.Context())
-			statsTags := []tag.Mutator{tag.Upsert(tagInstanceName, c.id.String())}
+			statsTags := []tag.Mutator{
+				tag.Upsert(tagInstanceName, c.id.String()),
+				tag.Upsert(tagPartition, strconv.Itoa(int(claim.Partition()))),
```
Comment (MovieStoreGuy) [inline receiver/kafkareceiver/kafka_receiver.go:452]: I would prefer to have this an opt in tag due to potential cardinality increase in can bring

Comment (spadger) [reply receiver/kafkareceiver/kafka_receiver.go:452]: It's true that you'd get increased cardinality (instead of 3 metrics per receiver, you'd have 3*topic-partition-count), but right now, the metrics are just wrong. If you take a look at the chart in the [issue](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/30177) you'll see the counter fluctuating according to the latest partition to be read.  This plays havoc with prometheus `rate` calculations, because it ignores counter values decreasing (they aren't allowed to decrease) but it counts all increases.

Imagine this scenario:
* topic has 2 partitions
* partition 1 offset: 0
* partition 2 offset: 1000
* both partitions have 1 span per 2 prometheus scrapes (each alternating)

In this case, prometheus will see the counter values: [1, 1000, 2, 1001, 3, 1003]

So in this case, we have 0.5 spans per scrape, but the rate function will return ~3000 spans per scrape.

I pulled these graphs just now, and they're from the same collector, one being sarama offsets and the other being processed messages. Queries were
```
sum(rate(otelcol_kafka_receiver_current_offset{... some stuff ...}[3m]))
sum(rate(otelcol_receiver_accepted_spans{... same stuff ...}[3m]))
```
image
image

Comment (spadger) [reply receiver/kafkareceiver/kafka_receiver.go:452]: I was thinking about how we could remove the cardinality and just roll everything into one single metric (e.g. by just returning the sum of all our offset deltas since we start up) but I think in at least some cases it would violate Kafka's semantic modek.  e.g. In my head, I could justify the `receiver_offset_lag` metric being aggregated e.g. `warning, there is a general rising backlog of unprocessed spans`, but `current_offset` is 100% tied to a partition and not a topic.

Comment (MovieStoreGuy) [reply receiver/kafkareceiver/kafka_receiver.go:452]: That makes sense to me, if it doesn't make sense to provide a less detailed metric, then an alternative metric makes the most sense to me.

**Comment by MovieStoreGuy** [comment]
Could I ask you to rebase with the latest changes in main?

**Comment by spadger** [comment]
@MovieStoreGuy sorry, I have been ill, but I'll keep it rebased daily

File: receiver/kafkareceiver/kafka_receiver.go (hunk 1 above)
Comment (spadger) [reply receiver/kafkareceiver/kafka_receiver.go:452]: There is a partition-agnostic metric by the way - `otelcol_kafka_receiver_messages`

**Review by MovieStoreGuy — APPROVED** [review]

**Comment by spadger** [comment]
Thanks @MovieStoreGuy  :)
