### PR TITLE
[datadogexporter] Add support for summary datatype

### LINKED ISSUE #3154: DataDog exporter doesn't export `ValueRecorder` metrics
It seems that the DataDog exporter doesn't export `ValueRecorder` metrics

Topology:
service: (OTEL-SDK) --> host: (OTEL Agent) --> storage:(Datadog)

We are using the opentelelmtry-sdk to send the metrics from our services to the host `otelcontrib` agent, then the otel-agent using `Datadog` exporter to send the metrics to the DataDog, when we are using some of the types of `ValueRecorder` the metrics are not showing in the DataDog web, when we do see the metrics via the `logging` exporter.  
The other meter types (`IntCounter`, `ValueObserve`, etc..) work as expecting.

Reproduce:

 Service:
 Configure OTLP exporter:
```golang
ctx := context.Background()
	exporter, err := otlp.NewExporter(ctx) // Configure as needed.
	if err != nil {
		log.Fatalf("failed to create exporter: %v", err)
	}
	defer func() {
		err := exporter.Shutdown(ctx)
		if err != nil {
			log.Fatalf("failed to stop exporter: %v", err)
		}
	}()
```

Create the ValueRecorder
```golang
ioReadBytes := metric.Must(meterInfra).NewInt64ValueRecorder("io.read.bytes", metric.WithDescription("IO read bytes"))

ioReadBytes.Record(ctx.Background, 1024)
``` 

I see this metric in the `logging` exporter but is missing in the DataDog web

I am so tried to produce the metric via batch-mesurment, but it still doesn't work
```golang
db.metricGraphMeter.RecordBatch(
  db.ctx,
  []attribute.KeyValue{attribute.String("units", "bytes")},
  db.dbMetrics.ioWriteBytes.Measurement(int64(len(nodeBytes))),
 )
```

The only way I succeed to produce `ValueRecorder` like metric is via counter using measurement, but this solution looks broken to me.
```golang
db.metricGraphMeter.RecordBatch(
	db.ctx,
	[]attribute.KeyValue{attribute.String("units", "bytes")},
	db.dbMetrics.ioWriteBytesTest.Measurement(nodeBytesLen),
)
```

This issue is very critical to us, as we don't have a way to send the value metrics for now

### PR DESCRIPTION
**Pull request by mx-psi**
**Description:** 

Add support for summary datatype to the Datadog exporter.

Since this is a datatype that is used mostly for compatibility with OpenMetrics, the implementation largely follows the features on our existing OpenMetrics base check on the Datadog Agent.

**Link to tracking Issue:** Fixes #3154

**Testing:** Added unit tests.

**Documentation:** Documented `report_quantiles` flag

### CODE REVIEW

File: exporter/datadogexporter/metrics_translator.go [hunk 1]
```diff
@@ -251,6 +252,52 @@ func mapHistogramMetrics(name string, slice pdata.HistogramDataPointSlice, bucke
...
+	} else if quantile == 1.0 {
+		// it needs to have a '.0' added at the end according to the spec
+		return "quantile:1.0"
+	}
+	return fmt.Sprintf("quantile:%s", strconv.FormatFloat(quantile, 'g', -1, 64))
+}
+
+// mapSummaryMetrics maps summary datapoints into Datadog metrics
+func mapSummaryMetrics(name string, slice pdata.SummaryDataPointSlice, quantiles bool, attrTags []string) []datadog.Metric {
+	// Allocate assuming none are nil and no percentiles
```
Comment (KSerrania) [inline exporter/datadogexporter/metrics_translator.go:273]: Nit for consistent naming (quantiles are not necessarily percentiles):
```suggestion
	// Allocate assuming none are nil and no quantiles
```

**Review by KSerrania — APPROVED** [review]
LGTM

**Review by ericmustin — APPROVED** [review]
:shipit:

**Review by bogdandrutu — APPROVED** [review]
