### PR TITLE
[receiver/k8scluster] Check resource support before setting up watchers

### LINKED ISSUE #9414: [receiver/k8scluster] Dropped support of k8s cluster version earlier than 1.21
After https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/7406 k8scluster receiver works only with 1.21+ versions k8s server API.

If k8s server version is 1.20 or lower, the following error messages are thrown and no metrics are collected:

```
W0422 20:00:11.629441       1 reflector.go:324] k8s.io/client-go@v0.23.3/tools/cache/reflector.go:167: failed to list *v1.CronJob: the server could not find the requested resource
E0422 20:00:11.629501       1 reflector.go:138] k8s.io/client-go@v0.23.3/tools/cache/reflector.go:167: Failed to watch *v1.CronJob: failed to list *v1.CronJob: the server could not find the requested resource
W0422 20:00:13.085439       1 reflector.go:324] k8s.io/client-go@v0.23.3/tools/cache/reflector.go:167: failed to list *v1.CronJob: the server could not find the requested resource
E0422 20:00:13.085471       1 reflector.go:138] k8s.io/client-go@v0.23.3/tools/cache/reflector.go:167: Failed to watch *v1.CronJob: failed to list *v1.CronJob: the server could not find the requested resource
W0422 20:00:16.247928       1 reflector.go:324] k8s.io/client-go@v0.23.3/tools/cache/reflector.go:167: failed to list *v1.CronJob: the server could not find the requested resource
E0422 20:00:16.247961       1 reflector.go:138] k8s.io/client-go@v0.23.3/tools/cache/reflector.go:167: Failed to watch *v1.CronJob: failed to list *v1.CronJob: the server could not find the requested resource
```

Even if 1.20 is EOL'd already, all the cloud providers like EKS, AKS and GKE still support it.

### PR DESCRIPTION
**Pull request by dmitryax**
This change adds additional validation using discovery API before setting up watchers on particular k8s resources. Otherwise, if k8s API doesn't support a k8s resource, setting up watchers breaks the receiver.

This change also adds support of batch/v1beta1 CronJob resources.

This makes the receiver able to work with k8s server versions 1.19 and 1.20 which are still available on some cloud providers.

Fixes: https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/9414

### CODE REVIEW

**Comment by mx-psi** [comment]
@open-telemetry/collector-contrib-approvers is there anyone with more knowledge of Kubernetes internals than me that can review this? I don't feel confident enough to be able to give a thorough review here

File: receiver/k8sclusterreceiver/watcher.go [hunk 1]
```diff
@@ -83,33 +78,108 @@ func newResourceWatcher(
...
-		factory.Autoscaling().V2beta2().HorizontalPodAutoscalers().Informer(),
-	)
+	// Map of supported group version kinds by name of a kind.
+	// If none of the group versions are supported by k8s server for a specific kind,
+	// informer for that kind won't be set and a warning message is thrown.
+	// This map should be kept in sync with what can be provided by the supported k8s server versions.
+	// List of group version kinds must be ordered starting from the most recent versions.
+	// Informer will be configured to use the latest version supported by k8s API.
+	supportedKinds := map[string][]schema.GroupVersionKind{
+		"Pod":                   {{Group: "", Version: "v1", Kind: "Pod"}},
```
Comment (TylerHelmuth) [inline receiver/k8sclusterreceiver/watcher.go:88]: Is there a way to put all the different group versions in "constants" so the are easier to reuse?  Would be great to use the same representation in both this list and the case statement in `setupInformerForKind`.  Will making adding new group versions less prone to error.

File: receiver/k8sclusterreceiver/watcher.go [hunk 2]
```diff
@@ -83,33 +78,108 @@ func newResourceWatcher(
...
-	rw.setupInformers(&autoscalingv2beta2.HorizontalPodAutoscaler{},
-		factory.Autoscaling().V2beta2().HorizontalPodAutoscalers().Informer(),
-	)
+	// Map of supported group version kinds by name of a kind.
+	// If none of the group versions are supported by k8s server for a specific kind,
+	// informer for that kind won't be set and a warning message is thrown.
+	// This map should be kept in sync with what can be provided by the supported k8s server versions.
+	// List of group version kinds must be ordered starting from the most recent versions.
+	// Informer will be configured to use the latest version supported by k8s API.
+	supportedKinds := map[string][]schema.GroupVersionKind{
```
Comment (TylerHelmuth) [inline receiver/k8sclusterreceiver/watcher.go:87]: Would this map ever need to be used somewhere else?  Is there benefit to defining it in such a way that something else can reference it?

File: receiver/k8sclusterreceiver/internal/collection/metadatastore.go [hunk 3]
```diff
@@ -32,13 +29,13 @@ type metadataStore struct {
 }
 
 // setupStore tracks metadata of services, jobs and replicasets.
-func (ms *metadataStore) setupStore(o runtime.Object, store cache.Store) {
-	switch o.(type) {
-	case *corev1.Service:
+func (ms *metadataStore) setupStore(gvk schema.GroupVersionKind, store cache.Store) {
+	switch gvk {
+	case schema.GroupVersionKind{Group: "", Version: "v1", Kind: "Service"}:
```
Comment (TylerHelmuth) [inline receiver/k8sclusterreceiver/internal/collection/metadatastore.go:34]: Would be great to reuse the group version "constants" here as well

File: receiver/k8sclusterreceiver/internal/collection/cronjobs.go [hunk 4]
```diff
@@ -67,9 +88,28 @@ func getResourceForCronJob(cj *batchv1.CronJob) *resourcepb.Resource {
 	}
 }
 
+func getResourceForCronJobBeta(cj *batchv1beta1.CronJob) *resourcepb.Resource {
```
Comment (TylerHelmuth) [inline receiver/k8sclusterreceiver/internal/collection/cronjobs.go:91]: Might not be worth it bc of generics, but could we prevent the duplicated logic between `getResourceForCronJob` and `getResourceForCronJobBeta` if instead of taking the version as the parameter we passed in the UID, Name, Namespace, and ClusterName?

File: receiver/k8sclusterreceiver/watcher.go (hunk 2 above)
Comment (dmitryax) [reply receiver/k8sclusterreceiver/watcher.go:87]: No, this map is only needed in this function

File: receiver/k8sclusterreceiver/watcher.go (hunk 1 above)
Comment (dmitryax) [reply receiver/k8sclusterreceiver/watcher.go:88]: I agree. I was hoping to find these constants in k8s library, but there are only internal ones, usually they use them like this. I'll add constants in our code

**Review by TylerHelmuth — APPROVED** [review]

**Comment by bogdandrutu** [comment]
cc @dashpole

**Review by jpkrohling — APPROVED** [review]
This looks good to me, but it would be good to decide when to remove the deprecated batch API from this code.

**Review by dashpole — COMMENTED** [review]
Here is a different idea: Can we feature-gate the use of these new k8s APIs?  Right now, since most users are on versions without support for the new APIs, they need to stay on the old ones, and we should use the old ones by default.  In ~6 months, most users should be on the new ones (but many lag behind), and we should change the default to use the new ones.

Edit: alternatively, we can just stick with the older APIs.

I'm not sure using discovery APIs is a good idea.  It isn't a common pattern in k8s to check something only once.  APIs can also be updated without restarting the collector.

**Comment by jpkrohling** [comment]
> Can we feature-gate the use of these new k8s APIs?

The batch v1 API has been released a couple of versions ago, hasn't it?

**Comment by dashpole** [comment]
> The batch v1 API has been released a couple of versions ago, hasn't it?

It was, but the k8s community has a fairly wide support window for older versions, since most managed k8s offerings lag ~3 versions behind what is just released.

**Comment by dmitryax** [comment]
@dashpole thanks for your feedback. We can use feature gates instead of discovery API. Ideally I wanted to make sure that if the informer API is not available for some resource, the receiver would keep working providing metrics for other resources. Do you have any idea how that can be achieved without using discovery API?

**Comment by dashpole** [comment]
> Do you have any idea how that can be achieved without using discovery API?

The discovery API is definitely the right way of doing it.  It would probably be acceptable to use the discovery API if the receiver fails if the discovery API isn't available (i.e. don't just log the error--return it)

**Comment by dmitryax** [comment]
> The discovery API is definitely the right way of doing it. It would probably be acceptable to use the discovery API if the receiver fails if the discovery API isn't available (i.e. don't just log the error--return it)

I like this approach. I'll change it accordingly

**Review by dashpole — APPROVED** [review]
this looks reasonable to me.

File: receiver/k8sclusterreceiver/watcher.go [hunk 5]
```diff
@@ -75,39 +74,119 @@ func newResourceWatcher(
...
+
+		// Setup informer for the latest supported group version
+		for _, gvk := range gvks {
+			supported, err := rw.isKindSupported(gvk)
+			if err != nil {
+				return err
+			}
+			if supported {
+				rw.setupInformerForKind(gvk, factory)
+				continue kinds
```
Comment (dashpole) [inline receiver/k8sclusterreceiver/watcher.go:121]: If i'm reading this correctly, if it finds the CronJob v1 GVK, it won't set up an informer on CronJob v1beta1.  Does this mean that in clusters which support both versions (e.g. 1.21) if a user creates a v1beta1 CronJob they won't get any metrics (since we are only watching for v1 CronJobs)?

Comment (dmitryax) [reply receiver/k8sclusterreceiver/watcher.go:121]: Yes, this is the behavior. v1beta1 CronJob is deprecated in 1.21, so setting up watchers for it throws warnings. I believe It may be confusing to show warnings for users even if they migrated all the cronjob manifests.

I'm open to other opinions here

Comment (dashpole) [reply receiver/k8sclusterreceiver/watcher.go:121]: I would prefer watching both versions if both are available.  Warning logs are OK IMO, but for a user that upgrades from v1.20 to v1.21 (only v1beta1 support to v1 and v1beta1 support), they would lose their metrics until they update their manifests.  Even if they knew about this detail, it wouldn't be possible to keep metrics flowing during the version upgrade

Comment (dmitryax) [reply receiver/k8sclusterreceiver/watcher.go]: Sounds reasonable. I update the code
