### PR TITLE
[connector/spanmetricsconnector] fix cardinality limit not work

### LINKED ISSUE #39645: cardinality limit not work
### Component(s)

connector/spanmetrics

## Description
After https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/39084 merged, I test it in my env, I found some bugs

## Steps to Reproduce
use the `TestConnectorWithCardinalityLimit` func and change the `i` to 5, you can find that cardinality limit not work.

https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/154ba2bb62b69490d765e560d5e2534497275d21/connector/spanmetricsconnector/connector_test.go#L2018

I will fix it.

### Collector version

main

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

### OpenTelemetry Collector configuration

```yaml

```

### Log output

```shell

```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Frapschen**
#### Description
fix #39645

In this PR, changes are below:
1. Fix the bug and use unit tests to ensure that the cardinality limit works as expected.
2. Add missing check logic when adding exemplars to duration metrics.
3. Considering issue #36805, I moved all cardinality limit logic to the internal/metrics package and implemented the check in each GetOrCreate method of the metrics type. 
4. Modify overflow metrics to include only one attribute: `otel.metric.overflow: true`.

### CODE REVIEW

**Comment by Frapschen** [comment]
wait https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/39648 to get merged.

**Comment by Frapschen** [comment]
Sorry, @iblancasa. I’ve assigned this issue to myself because I have a PR (https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/39134) that depends on the fix from this current bug-fix PR.

Please review this PR and feel free to incorporate any code from your side to enhance it further.

File: connector/spanmetricsconnector/internal/metrics/metrics.go [hunk 1]
```diff
@@ -137,16 +170,32 @@ func (m *exponentialHistogramMetrics) GetOrCreate(key Key, attributesFun BuildAt
 		)
 		histogram.Init(cfg)
 
+		attributes := pcommon.NewMap()
+		if m.IsCardinalityLimitReached() {
+			limitReached = true
+			key = overflowKey
+
+			// check if overflowKey already exit
```
Comment (iblancasa) [inline connector/spanmetricsconnector/internal/metrics/metrics.go:178]:
```suggestion
			// check if overflowKey already exists
```

File: connector/spanmetricsconnector/internal/metrics/metrics.go [hunk 2]
```diff
@@ -64,27 +69,50 @@ type exponentialHistogram struct {
...
+func (m *explicitHistogramMetrics) GetOrCreate(key Key, attributesFun BuildAttributesFun, startTimestamp pcommon.Timestamp) (Histogram, bool) {
+	limitReached := false
 	h, ok := m.metrics[key]
 	if !ok {
+		attributes := pcommon.NewMap()
+		if m.IsCardinalityLimitReached() {
+			limitReached = true
+			key = overflowKey
+
+			// check if overflowKey already exit
```
Comment (iblancasa) [inline connector/spanmetricsconnector/internal/metrics/metrics.go:103]:
```suggestion
			// check if overflowKey already exists
```

File: connector/spanmetricsconnector/internal/metrics/metrics.go [hunk 3]
```diff
@@ -279,19 +328,38 @@ func (m *SumMetrics) IsCardinalityLimitReached() bool {
...
+	limitReached := false
 	s, ok := m.metrics[key]
 	if !ok {
+		attributes := pcommon.NewMap()
+		// check when new key coming
+		if m.IsCardinalityLimitReached() {
+			limitReached = true
+			key = overflowKey
+
+			// check if overflowKey already exit
```
Comment (iblancasa) [inline connector/spanmetricsconnector/internal/metrics/metrics.go:341]:
```suggestion
			// check if overflowKey already exists
```

File: connector/spanmetricsconnector/internal/metrics/metrics.go [hunk 4]
```diff
@@ -64,27 +69,50 @@ type exponentialHistogram struct {
...
-func (m *explicitHistogramMetrics) GetOrCreate(key Key, attributesFun BuildAttributesFun, startTimestamp pcommon.Timestamp) Histogram {
+func (m *explicitHistogramMetrics) IsCardinalityLimitReached() bool {
+	return m.cardinalityLimit > 0 && len(m.metrics) >= m.cardinalityLimit
+}
+
+func (m *explicitHistogramMetrics) GetOrCreate(key Key, attributesFun BuildAttributesFun, startTimestamp pcommon.Timestamp) (Histogram, bool) {
+	limitReached := false
 	h, ok := m.metrics[key]
 	if !ok {
+		attributes := pcommon.NewMap()
```
Comment (iblancasa) [inline connector/spanmetricsconnector/internal/metrics/metrics.go:98]: Would it make sense to just declare the variable here and create a new map only in the case where the cardinality limit is reached and the overflow attribute is not there?

File: connector/spanmetricsconnector/connector.go [hunk 5]
```diff
@@ -391,48 +391,26 @@ func (p *connectorImp) aggregateMetrics(traces ptrace.Traces) {
...
-				s := sums.GetOrCreate(key, attributesFun, startTimestamp)
-				if p.config.Exemplars.Enabled && !span.TraceID().IsEmpty() {
+				s, limitReached := sums.GetOrCreate(key, attributesFun, startTimestamp)
+				if !limitReached && p.config.Exemplars.Enabled && !span.TraceID().IsEmpty() {
 					s.AddExemplar(span.TraceID(), span.SpanID(), duration)
 				}
 				s.Add(1)
 
+				// aggregate histogram metrics
+				if !p.config.Histogram.Disable {
```
Comment (iblancasa) [inline connector/spanmetricsconnector/connector.go:406]: Should we also add tests for the histograms? I didn't add them before because I though they were not needed but I'm not sure now.

File: connector/spanmetricsconnector/internal/metrics/metrics.go [hunk 6]
```diff
@@ -64,27 +69,50 @@ type exponentialHistogram struct {
...
+			limitReached = true
+			key = overflowKey
+
+			// check if overflowKey already exit
+			h, ok = m.metrics[key]
+			if ok {
+				return h, limitReached
+			}
+
+			attributes.PutBool(overflowKey, true)
```
Comment (iblancasa) [inline connector/spanmetricsconnector/internal/metrics/metrics.go:109]: Question: when we are not reaching the cardinality limit, we copy the resource attributes to the datapoints -they are added by the method `buildAttributes`-. Shouldn't we do the same here?

File: connector/spanmetricsconnector/connector_test.go [hunk 7]
```diff
@@ -2098,15 +2130,17 @@ func TestConnectorWithCardinalityLimitForEvents(t *testing.T) {
 	// Second consume to trigger overflow
```
Comment (iblancasa) [inline connector/spanmetricsconnector/connector_test.go:2130]: The comment in line 2127 is not valid anymore, thought

File: connector/spanmetricsconnector/connector_test.go [hunk 8]
```diff
@@ -1984,11 +1985,11 @@ func TestConnectorWithCardinalityLimit(t *testing.T) {
 	ils2 := rspan2.ScopeSpans().AppendEmpty()
 
 	// Add spans with different names to trigger overflow
-	for i := 0; i < 3; i++ {
-		span := ils.Spans().AppendEmpty()
-		span.SetName(fmt.Sprintf("operation%d", i))
-		span.SetKind(ptrace.SpanKindServer)
-		span.Attributes().PutStr("http.method", "GET")
+	for i := 0; i < 5; i++ {
+		span1 := ils.Spans().AppendEmpty()
```
Comment (iblancasa) [inline connector/spanmetricsconnector/connector_test.go:1989]:
```suggestion
		span1 := ils1.Spans().AppendEmpty()
```

File: connector/spanmetricsconnector/connector_test.go [hunk 9]
```diff
@@ -1998,13 +1999,18 @@ func TestConnectorWithCardinalityLimit(t *testing.T) {
 
 	assert.NoError(t, connector.ConsumeTraces(context.Background(), traces))
 
-	metrics := connector.buildMetrics()
+	// first buildMetrics emit zero datapoint value
+	_ = connector.buildMetrics()
```
Comment (iblancasa) [inline connector/spanmetricsconnector/connector_test.go:2003]: I think it would be a good idea to check here that we are getting the metrics we expect with value 0

File: connector/spanmetricsconnector/connector_test.go [hunk 10]
```diff
@@ -1998,13 +1999,18 @@ func TestConnectorWithCardinalityLimit(t *testing.T) {
...
+
+	// mock send two batch of spans to this connector
```
Comment (iblancasa) [inline connector/spanmetricsconnector/connector_test.go:2005]: Why two batch of spans?

In my PR I just called `connector.buildMetrics()` twice (one to initialize to 0 and another one to get the values of the spans the connector consumed).

I don't have a strong opinion about this but it took me a while to get why the values for the datapoints where those... until I noticed about this line.

**Review by iblancasa — COMMENTED** [review]
Thanks for your work! Great.

File: .chloggen/fix-issue-39645.yaml [hunk 11]
```diff
@@ -0,0 +1,27 @@
...
+subtext:
+
+# If your change doesn't affect end users or the exported elements of any package,
+# you should instead start your pull request title with [chore] or use the "Skip Changelog" label.
+# Optional: The change log or logs in which this entry should be included.
+# e.g. '[user]' or '[user, api]'
+# Include 'user' if the change is relevant to end users.
+# Include 'api' if there is a change to a library API.
+# Default: '[user]'
+change_logs: [user]
```
[the remark this answers is not in the document]
Comment (Frapschen) [reply .chloggen/fix-issue-39645.yaml:27]: Your are right, this feature has not been released, so we don't need a change log

File: connector/spanmetricsconnector/connector.go (hunk 5 above)
Comment (Frapschen) [reply connector/spanmetricsconnector/connector.go:406]: yes, I have also add a test case for Histogram in `TestConnectorWithCardinalityLimit`

File: connector/spanmetricsconnector/connector_test.go (hunk 9 above)
Comment (Frapschen) [reply connector/spanmetricsconnector/connector_test.go:2003]: This PR (https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/39052) introduces a feature where call metrics are initialized with a value of 0. However, I haven't added a unit test to verify this behavior. I plan to add a separate test function to handle it.

In the current test case, I am just skip the first 0 value.

File: connector/spanmetricsconnector/connector_test.go (hunk 10 above)
Comment (Frapschen) [reply connector/spanmetricsconnector/connector_test.go:2005]: I think using a single batch of spans would also work. The reason I used two batches of spans was to avoid falling into potential edge-case traps in the code.

I can provide more comments on that to make it more noticeable.

File: connector/spanmetricsconnector/internal/metrics/metrics.go (hunk 6 above)
Comment (Frapschen) [reply connector/spanmetricsconnector/internal/metrics/metrics.go:109]: If this line (`attributes.PutBool(overflowKey, true)`) is executed, I believe that `IsCardinalityLimitReached()` has already been checked and returned true. This means we have reached the cardinality limit.

If I am mistaken, please correct me.

Comment (iblancasa) [reply connector/spanmetricsconnector/internal/metrics/metrics.go:110]: That’s true. But what I mean is that we are not copying the resource atrributes when cardinality limit is reached. But we do for the other cases.
I think we need to be consistent and copy them in both situations (for consistency).

File: connector/spanmetricsconnector/connector_test.go (hunk 10 above)
Comment (iblancasa) [reply connector/spanmetricsconnector/connector_test.go]: Great! Thanks

File: connector/spanmetricsconnector/internal/metrics/metrics.go (hunk 6 above)
Comment (Frapschen) [reply connector/spanmetricsconnector/internal/metrics/metrics.go:110]: After careful consideration, I believe there is currently no need to add resource attributes to the overflow metric for the following reasons:

- **Different use cases**: The overflow metric is primarily used to record the number of metrics exceeding the cardinality limit, which is fundamentally different from the purpose of regular metrics. Its design goal does not involve consistency of label sets, so adding resource attributes would have limited value.
- **Implementation complexity**: The current buildAttributes method returns an attributes variable that cannot distinguish between resource attributes and regular attributes. Forcibly adding resource attributes would increase code complexity.
- **Potential high cardinality issues**: If the resource attributes in user spans already suffer from high cardinality, including them in the overflow metric could also lead to high cardinality for this metric, which goes against its original design intent.

That said, resource attributes could indeed help users analyze which applications generate spanmetrics encountering high cardinality issues. However, during testing, it was found that the `prometheus` exporter already provides similar functionality through the job label (with the service name as its value), fulfilling this need. Other exporters, however, may not meet this requirement.

In summary, I recommend not adding resource attributes to the overflow metric for now. We can optimize further based on user feedback in the future.

Comment (iblancasa) [reply connector/spanmetricsconnector/internal/metrics/metrics.go:110]: Resource attributes are copied as part of execution of `func (p *connectorImp) buildMetrics()` to the resulting resource metrics.

In the method `attributesFun` are copying the resource attributes to the dp too. This is not important for the Prometheus exporter but can be for those users using other exporter like OTLP.

If we don't copy the resource attributes to the overflow metric, I'm not sure if we can "break" users (I know this has not been released yet) because will cause a different behavior.

Currently it is fine because we have those attributes in the resource attributes, marking the overflow for just that resource and metric.

I'm fine not copying it now but what I wanted to highlight is that we are not consistent here and, maybe, we want to revisit this later. I would say it makes sense to not add the resource attributes to the DPs to any of the exposed metrics because they will be added to the RM anyway. This would save some resources.

> Different use cases: The overflow metric is primarily used to record the number of metrics exceeding the cardinality limit, which is fundamentally different from the purpose of regular metrics. Its design goal does not involve consistency of label sets, so adding resource attributes would have limited value.

This is partially true. Because we need to identify for what resource there was an overflow. Currently, since the resource attributes are copied to the resource metrics, we are covered and we are consistent when exporting using Prometheus but we are not copying for DPs.

> Implementation complexity: The current buildAttributes method returns an attributes variable that cannot distinguish between resource attributes and regular attributes. Forcibly adding resource attributes would increase code complexity.

There is a method called `addResourceAttributes` that currently is doing this for us... but if this method cannot be used I don't think complexity in this case is a thing.

> Potential high cardinality issues: If the resource attributes in user spans already suffer from high cardinality, including them in the overflow metric could also lead to high cardinality for this metric, which goes against its original design intent.

I disagree. I thing this will not happen because we will only have one overflow per metric and resource as maximum.

**Review by iblancasa — APPROVED** [review]

**Comment by iblancasa** [comment]
@open-telemetry/collector-contrib-approvers can somebody take a look to this and merge? I approved as code owner.

**Review by atoulme — APPROVED** [review]
