### PR TITLE
[exporter/datadog] Add `api.fail_on_invalid_key` to fail fast if API Key is invalid

### LINKED ISSUE #7402: [exporter/datadog] datadog exporter should fail fast if api key validation fail
**Describe the bug**
Currently, if datadog exporter failed to validate api key, it would only give some warning logs as below:
```
{"level":"info","ts":1642812421.1986244,"caller":"utils/api.go:32","msg":"Validating API key.","kind":"exporter","name":"datadog"}
{"level":"info","ts":1642812421.5067706,"caller":"utils/api.go:39","msg":"API key validation successful.","kind":"exporter","name":"datadog"}
```
Opentelemetry collector can still get started even if datadog exported was failed to get started. And metrics `send_failed_metric_points`, `send_failed_spans`  will not count the metrics failed to be sent to datadog if datadog exporter was not started properly. Basically, datadog exporter would just fail silently. This made people hard to monitor this proactively. People can only found something goes wrong when they see metrics/traces missing in datadog. 

I understand it's hard to let `send_failed_metric_points`, `send_failed_spans` count the metrics/traces failed to sent caused by datadog exporter start up failure -- we only record these metrics when one export operation is done, while there is no export operation in this case. So that I think it would be better just let opentelemetry collector fail fast during startup if the api key failed to be validated successfully.

### PR DESCRIPTION
**Pull request by keisku**
**Description:** <Describe what has changed.>

Add `api.fail_on_invalid_key` to fail fast if API Key is invalid.

**Link to tracking Issue:** <Issue number if applicable>

https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/7402

**Testing:** <Describe what testing was performed and which tests were added.>

`fail_on_invalid_key: false`

1 ) Set the invalid API key and `fail_on_invalid_key: false`.
2 ) `make run`
3 ) Confirming error message
This behavior is same as before.

```
GO111MODULE=on go run --race ./cmd/otelcontribcol/... --config local/config.yaml
2022/04/28 06:42:12 proto: duplicate proto type registered: jaeger.api_v2.PostSpansRequest
2022/04/28 06:42:12 proto: duplicate proto type registered: jaeger.api_v2.PostSpansResponse
2022-04-28T06:42:12.532+0900    info    datadogexporter/factory.go:195  sanitizing Datadog traces exporter configuration        {"kind": "exporter", "name": "datadog"}
2022-04-28T06:42:12.532+0900    info    utils/api.go:37 Validating API key.     {"kind": "exporter", "name": "datadog"}
2022-04-28T06:42:13.262+0900    warn    utils/api.go:47 API Key validation failed       {"kind": "exporter", "name": "datadog"}
2022-04-28T06:42:13.263+0900    info    datadogexporter/factory.go:135  sanitizing Datadog metrics exporter configuration       {"kind": "exporter", "name": "datadog"}
2022-04-28T06:42:13.263+0900    info    utils/api.go:37 Validating API key.     {"kind": "exporter", "name": "datadog"}
2022-04-28T06:42:13.966+0900    warn    utils/api.go:47 API Key validation failed       {"kind": "exporter", "name": "datadog"}
2022-04-28T06:42:13.967+0900    info    builder/exporters_builder.go:255        Exporter was built.     {"kind": "exporter", "name": "datadog"}
```

`fail_on_invalid_key: true`

1 ) Set the invalid API key and `fail_on_invalid_key: true`.
2 ) `make run`
3 ) Confirming error message
```
GO111MODULE=on go run --race ./cmd/otelcontribcol/... --config local/config.yaml
2022/04/28 06:40:36 proto: duplicate proto type registered: jaeger.api_v2.PostSpansRequest
2022/04/28 06:40:36 proto: duplicate proto type registered: jaeger.api_v2.PostSpansResponse
2022-04-28T06:40:36.322+0900    info    datadogexporter/factory.go:195  sanitizing Datadog traces exporter configuration        {"kind": "exporter", "name": "datadog"}
2022-04-28T06:40:36.322+0900    info    utils/api.go:37 Validating API key.     {"kind": "exporter", "name": "datadog"}
2022-04-28T06:40:37.111+0900    warn    utils/api.go:47 API Key validation failed       {"kind": "exporter", "name": "datadog"}
Error: cannot build exporters: error creating datadog exporter: API Key validation failed
2022/04/28 06:40:37 collector server run finished with error: cannot build exporters: error creating datadog exporter: API Key validation failed
exit status 1
make: *** [run] Error 1
```

**Documentation:** <Describe the documentation added.>

### CODE REVIEW

**Review by dashpole — COMMENTED** [review]
I don't know if a config option is appropriate here. If configuration is invalid, the component should always fail IMO.  If an exporter cannot be started as configured, it should return the error in its `newMetricsExporter` function, for example.

**Comment by mx-psi** [comment]
> I don't know if a config option is appropriate here. If configuration is invalid, the component should always fail IMO. If an exporter cannot be started as configured, it should return the error in its `newMetricsExporter` function, for example.

I agree in principle, but there is some internal hesitancy to failing to start by default because of a feature that may be added to Datadog in the future related to API keys, so I think we want it behind a flag, even if I agree this looks odd from the outside

**Review by mx-psi — CHANGES_REQUESTED** [review]

**Review by mx-psi — CHANGES_REQUESTED** [review]
Thanks for doing this! My main comment is that instead of panicking with `logger.Fatal`, we should return an error. I left some other comments inline

File: exporter/datadogexporter/internal/utils/api.go [hunk 1]
```diff
@@ -27,17 +30,21 @@ func CreateClient(APIKey string, endpoint string) *datadog.Client {
...
+	if err == nil && valid {
 		logger.Info("API key validation successful.")
-	} else {
-		logger.Warn("API key validation failed.")
+		return nil
+	}
+	if err != nil {
+		msg := "Error while validating API key"
+		logger.Warn(msg, zap.Error(err))
+		return fmt.Errorf("%s: %w", msg, err)
```
Comment (mx-psi) [inline exporter/datadogexporter/internal/utils/api.go:46]: We should not return an error here: imagine there is an ongoing incident and the Datadog API returns a "500 Internal Server Error" error code; it could be that the API key is valid in this case and we just were not able to confirm that.

```suggestion
		return nil

Comment (keisku) [reply exporter/datadogexporter/internal/utils/api.go]: https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/9426/commits/006a462c613159e15b075ac7268936a471a40e01

File: exporter/datadogexporter/factory_test.go [hunk 2]
```diff
@@ -447,6 +495,49 @@ func TestCreateAPITracesExporter(t *testing.T) {
...
+
+	require.NoError(t, err)
+	require.NotNil(t, cfg)
+
+	// Use the mock server for API key validation
+	c := (cfg.Exporters[config.NewComponentIDWithName(typeStr, "api")]).(*ddconfig.Config)
+	c.Metrics.TCPAddr.Endpoint = server.URL
+	c.HostMetadata.Enabled = false
+
+	t.Run("failed_on_invalid_key is true", func(t *testing.T) {
```
Comment (mx-psi) [inline exporter/datadogexporter/factory_test.go:517]:
```suggestion
	t.Run("fail_on_invalid_key is true", func(t *testing.T) {
```

File: exporter/datadogexporter/factory_test.go [hunk 3]
```diff
@@ -447,6 +495,49 @@ func TestCreateAPITracesExporter(t *testing.T) {
...
+		ctx := context.Background()
+		exp, err := factory.CreateTracesExporter(
+			ctx,
+			componenttest.NewNopExporterCreateSettings(),
+			cfg.Exporters[config.NewComponentIDWithName(typeStr, "api")],
+		)
+		assert.EqualError(t, err, "API Key validation failed")
+		assert.Nil(t, exp)
+	})
+	t.Run("failed_on_invalid_key is false", func(t *testing.T) {
```
Comment (mx-psi) [inline exporter/datadogexporter/factory_test.go:528]:
```suggestion
	t.Run("fail_on_invalid_key is false", func(t *testing.T) {
```

**Review by mx-psi — DISMISSED** [review]
Looks great, thanks for addressing the comments! 🙇 Just two tiny nits, after those are addressed I will wait for David to ACK my comment and then mark as ready to merge

**Comment by mx-psi** [comment]
It looks like you also need to address some lint errors: https://github.com/open-telemetry/opentelemetry-collector-contrib/runs/6209762394?check_suite_focus=true

**Review by mx-psi — APPROVED** [review]

File: exporter/datadogexporter/factory.go [hunk 4]
```diff
@@ -198,6 +198,7 @@ func (f *factory) createTracesExporter(
 	}
 
 	ctx, cancel := context.WithCancel(ctx)
+	defer cancel()
```
[the remark this answers is not in the document]
Comment (mx-psi) [reply exporter/datadogexporter/factory.go:201]: Thanks for the comment, it would have been difficult to figure out where this was coming from otherwise!

**Comment by codeboten** [comment]
Closing and re-opening PR to trigger the `gotidy` CI check

**Review by codeboten — APPROVED** [review]

**Comment by mx-psi** [comment]
Looks like it passed now

File: exporter/datadogexporter/factory.go (hunk 4 above)
Comment (gbbr) [inline exporter/datadogexporter/factory.go:201]: Actually this cancels the exporter prematurely after the function exits. The cancel is only meant to be called on shutdown (it is part of shutdown, so technically it _does_ get called on all paths).

Comment (mx-psi) [reply exporter/datadogexporter/factory.go:201]: > (it is part of shutdown, so technically it does get called on all paths).

the lint was failing because it was not called when the traces exporter fails to get created. I opened #9797 to fix this, thanks for spotting that!
