### PR TITLE
[receiver/awsfirehosereceiver] Fix unmarshal error when request is larger than the buffer limit of bufio.Scanner (Issue 38736)

### LINKED ISSUE #38736: [receiver/awsfirehose] Unmarshal error when request is larger than the buffer limit of bufio.Scanner
### Component(s)

_No response_

## Description
We are seeing error `Error scanning for newline-delimited JSON` with root cause `bufio.Scanner: token too long` in `awsfirehosereceiver`.

The unmarshaller uses 
```
scanner := bufio.NewScanner(r)
```
to read and deserialize json payload of Firehose stream HTTP request. The scanner has an internal buffer which has the [max size](https://github.com/golang/go/blob/master/src/bufio/scan.go#L82) of 64KB. 

However, Firehose buffers incoming data (CloudWatch logs & metrics) before sending them. Default buffer size is 5MB but configurable up to 64MB. 

Image

Each log event can take up to 256KB. [doc](https://docs.aws.amazon.com/AmazonCloudWatchLogs/latest/APIReference/API_PutLogEvents.html#:~:text=Each%20log%20event%20can%20be,in%20a%20batch%20is%2010%2C000.)

So we can hit the 64KB buffer quickly even with the default Firehose buffer size of 5MB.

## Steps to Reproduce
Can be reproduced with a unit test which creates a message that is larger than 64KB
```
func TestUnmarshalLargePayload(t *testing.T) {
	unmarshaler := NewUnmarshaler(zap.NewNop(), component.NewDefaultBuildInfo())

	var largePayload bytes.Buffer
	largePayload.WriteString(`{"messageType":"DATA_MESSAGE","owner":"123","logGroup":"test","logStream":"test","logEvents":[`)
	largePayload.WriteString(`{"timestamp":1742239784,"message":"`)
	for largePayload.Len() < 64*1024-4 {
		largePayload.WriteString("a")
	}
	largePayload.WriteString(`"}]}`)

	compressedRecord, err := gzipData(largePayload.Bytes())
	require.NoError(t, err)

	_, err = unmarshaler.UnmarshalLogs(compressedRecord)
	require.Error(t, err)
	require.Equal(t, errInvalidRecords, err)
}
```

## Expected Result
`awsfirehose` receiver should be able to handle large incoming requests without error.

### Option1: raise buffer limit of bufio.Scanner
We can call https://pkg.go.dev/bufio#Scanner.Buffer method to pass a byte buffer with higher capacity to the scanner. 
```
scanner := bufio.NewScanner(r)
buf := make([]byte, 0, initialBufferCapacity)
scanner.Buffer(buf, 64*1024*1024) // set the buffer limit to 64MB
```

We would need to determine the initial buffer capacity which ideally work for most of the requests. But this really depends on the data that is streamed by firehose. We might need to make this configurable.

### Option2: use bufio.Reader
`bufio.Reader` seems to provide better error handling and can read large tokens. https://chriswilcox.dev/blog/2024/04/09/Scan-vs-Read-in-bufio.html

### Collector version

v0.121.0

## Environment
OS: (e.g., "Macos 15.3.1")

### OpenTelemetry Collector configuration

```yaml

```

### Log output

```shell

```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by yiquanzhou**
#### Description
Fixes https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/38736
CW log unmarshaller only needs to read and unmarshal one single `cwLog` json object. Remove the scanning using `bufio.Scanner` which has limited buffer size.

#### Link to tracking issue
Fixes https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/38736

#### Testing
Remove unit tests for reading multiple json objects and update existing one.

Add a test to verify that a large cw log request payload can be correctly unmarshalled.

### CODE REVIEW

File: receiver/awsfirehosereceiver/internal/unmarshaler/cwlog/unmarshaler.go [hunk 1]
```diff
@@ -67,95 +67,59 @@ func (u *Unmarshaler) UnmarshalLogs(compressedRecord []byte) (plog.Logs, error)
 	}
 	defer u.gzipPool.Put(r)
 
-	type resourceKey struct {
-		owner     string
-		logGroup  string
-		logStream string
+	data, err := io.ReadAll(r)
```
Comment (axw) [inline receiver/awsfirehosereceiver/internal/unmarshaler/cwlog/unmarshaler.go:70]: Ideally we would decode directly from the reader, but I suppose this won't be worse than the existing code.

FYI we're working on extracting the unmarshaler to a separate component, and we'll optimise it there: https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/38821

**Review by axw — APPROVED** [review]
Thank you! Makes everything so much simpler, too.

File: receiver/awsfirehosereceiver/internal/unmarshaler/cwlog/unmarshaler.go (hunk 1 above)
Comment (yiquanzhou) [reply receiver/awsfirehosereceiver/internal/unmarshaler/cwlog/unmarshaler.go:70]: I suppose you are referring to this part 
https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/38821/files#diff-c98f13982ab112641b8e7b47af57922b415065212d6f5939a2998aee80fba34bR88-R92

Yeah that's definitely better. I'll leave the optimization to that PR then.

**Comment by yiquanzhou** [comment]
@songy23 @Aneurysm9 could one of you review the PR please?

**Review by songy23 — APPROVED** [review]

**Comment by songy23** [comment]
will wait a few days before merging in case @Aneurysm9 wants to take a look
