### PR TITLE
elasticexporter: translate exception span events

### LINKED ISSUE #1803: Elastic exporter discards exception data
**Describe the bug**

I have instrumented a JaxRS Java app with opentelemetry-java-instrumentation. opentelemetry-collector-contrib is configured to receive `otlp` and to export `elastic` + `loggin`. Elastic-APM is configured to output to console and Kibana.

I can see in the logs that the the collector is receiving trace data containing expection data in the span, but the `elastic` exporter drops the exception data. The exception data is not visible in ElasticAPM’s stdout nor is it persisted to Elasticsearch.

**Steps to reproduce**

1. Instrument a Java app with `opentelemetry-java-instrumentation`
2. Configure an opentelemetry-collector to receive `otlp` and export `logging`  and `elastic` trace data.
3. Configure ElasticAPM to output to console
4. Provoke an exception.

**What did you expect to see?**
I expect to see the stacktrace and exception details visible in ElasticAPM’s stdout and persisted to Elasticsearch (if ElasticAPM has been configured to do so).

**What did you see instead?**
JSON objects in ElasticAPM’s console output containing span details but missing the exception details.

**What version did you use?**

`opentelemetry-java-instrumentation:0.12.0`
`elastic-apm:7.10.1`
`opentelemetry-collector-contrib:0.16.0`

**What config did you use?**

otel.yaml
```
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:55680
exporters:
  elastic:
    apm_server_url: "http://elastic:8200/"
  logging:
    loglevel: debug
service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [elastic, logging]
```

apm-server.docker.yml (Elastic APM config)
```
apm-server:
  host: "0.0.0.0:8200"
output.console:
  enabled: true
  codec.json:
    pretty: true
    escape_html: false
```

docker-compose.yaml
```
version: '3'
services:
  otel:
    image: otel/opentelemetry-collector-contrib:0.16.0
    volumes:
      - ./docker/otel.yml:/etc/otel/config.yaml
    ports:
      - "55680:55680"
  elastic:
    image: docker.elastic.co/apm/apm-server:7.10.1
    volumes:
      - "./docker/apm-server.docker.yml:/usr/share/apm-server/apm-server.yml:ro"
  web:
    build: .
```

**Environment**

I’m using macOS 11.0.1 (20B29) 

Below is the output from 

OS: Linux 4.19.121-linuxkit

**Additional context**

Console output showing combined output from otel and elastic:

https://gist.github.com/paulgrav/96f1f1a21e92bf96cfd54db95d7b2559

### PR DESCRIPTION
**Pull request by axw**
**Description:**

Translate exception span events to Elastic APM's error model.

Arbitrary span events are not currently supported, so we only handle exceptions for now.
Support for parsing Java stacktraces has been added; this may be expanded to other languages later.

Once https://github.com/elastic/apm-agent-go/pull/862 lands I'll update this PR to split class.method.

**Link to tracking Issue:**

Closes https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/1803

**Testing:**

Unit tests added. Also tested with the span events provided in the linked issue.

### CODE REVIEW

**Comment by axw** [comment]
@simitt @jalvz please take a look when you can.

File: exporter/elasticexporter/internal/translator/elastic/exceptions.go [hunk 1]
```diff
@@ -0,0 +1,204 @@
...
+		//  - "module/class.method"
+		module, function = function[:slash], function[slash+1:]
+		if slash := strings.IndexRune(function, '/'); slash >= 0 {
+			module, function = function[:slash], function[slash+1:]
+		}
+	}
+	var classname string
+	if dot := strings.LastIndexByte(function, '.'); dot > 0 {
+		// Split into classname and method.
+		classname, function = function[:dot], function[dot+1:]
```
Comment (anuraaga) [inline exporter/elasticexporter/internal/translator/elastic/exceptions.go:183]: Does the regex make sure there's no `dot` at the end of the function? Either way, probably safe to have a bounds check since we definitely don't want to panic.

File: exporter/elasticexporter/internal/translator/elastic/exceptions.go [hunk 2]
```diff
@@ -0,0 +1,204 @@
...
+		return fmt.Errorf("failed to parse stacktrace line %q", s)
+	}
+	var module string
+	function := submatch[1]
+	if slash := strings.IndexRune(function, '/'); slash >= 0 {
+		// We could have either:
+		//  - "class_loader/module/class.method"
+		//  - "module/class.method"
+		module, function = function[:slash], function[slash+1:]
+		if slash := strings.IndexRune(function, '/'); slash >= 0 {
```
Comment (anuraaga) [inline exporter/elasticexporter/internal/translator/elastic/exceptions.go:176]: Does the regex make sure there's no slash at the end of the function? Either way, probably safe to have a bounds check since we definitely don't want to panic.

**Review by anuraaga — COMMENTED** [review]
In case it's any reference, here's our similar code in xray https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/master/exporter/awsxrayexporter/translator/cause.go#L159

It seems like we're getting to where we need a structure for a stacktrace in the collector framework itself to share parsing code to reduce chance of bugs. Though not volunteering for it :P /cc @jmacd

File: exporter/elasticexporter/internal/translator/elastic/exceptions.go (hunk 1 above)
Comment (anuraaga) [reply exporter/elasticexporter/internal/translator/elastic/exceptions.go:183]: Admittedly I can't remember if go returns an empty slice though if it was at the boundary, if so than no worries

Comment (axw) [reply exporter/elasticexporter/internal/translator/elastic/exceptions.go:183]: Indeed, `x[len(x):]` will return an empty slice.

**Review by anuraaga — APPROVED** [review]
Thanks for confirming

**Review by jalvz — APPROVED** [review]
