### PR TITLE
[processor/k8sattributes] Wait for ReplicaSet informer before starting pod informer

### LINKED ISSUE #37056: Prometheus metrics missing k8s_deployment_name attribute for short period after agent restart
### Component(s)

processor/k8sattributes

## Description
We have otel deployed as a daemon set in our cluster and have noticed that after a restart of the otel agent pods, prometheus metrics are missing the k8s_deployment_name attribute even though it is being extracted as part of the k8sattributes processor. After about 5 minutes, the problem resolves and the label is present on metrics. Notably, we have not observed this issue with the k8s_daemonset_name attribute. By looking at the logs, we found the k8s.deployment.name attribute is missing from the resource, while the other extracted metadata is present (see attached logs).

Our config sets the `wait_for_metadata` flag to true. The k8sattribute processor config we are currently using:
```
  k8sattributes:
    wait_for_metadata: true
    auth_type: "serviceAccount"
    passthrough: false
    filter:
      node_from_env_var: KUBE_NODE_NAME
    extract:
      metadata:
        - k8s.pod.name
        - k8s.pod.uid
        - k8s.deployment.name
        - k8s.deployment.uid
        - k8s.namespace.name
      labels:
        # Extracts the value of a pod label and inserts it as a resource attribute
        - tag_name: service_name
          key: tags.datadoghq.com/service
          from: pod
        - tag_name: version
          key: tags.datadoghq.com/version
          from: pod
        - tag_name: label_k8s_bluecore_com_team
          key: k8s.bluecore.com/team
          from: pod
    pod_association:
      # below association takes a look at the datapoint's k8s.pod.uid resource attribute and tries to match it with
      # the pod having the same attribute.
      - sources:
          - from: resource_attribute
            name: k8s.pod.uid
```

## Steps to Reproduce
Deploy otel with a prometheus receiver and a pipeline that uses the k8sattributes processor with the config above. Use the debug exporter to output to stdout. Note that for ~5 min after a restart of the otel pod, k8s_deployment_name is missing from the metrics. After about 5 min, the resource attribute appears.

## Expected Result
After the otel pods restart, the k8s_deployment_name label should be on all exported metrics.

## Actual Result
For about 5 minutes after otel pods restart, exported prometheus metrics are missing the k8s_deployment_name label despite it being extracted as part of the k8sattribute processor.

### Collector version

v0.116.1

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

### OpenTelemetry Collector configuration

```yaml
receivers:
  prometheus/bc:
    config:
      scrape_configs:
      - job_name: bc-prom
        scrape_interval: 60s
        kubernetes_sd_configs:
        - role: pod
          selectors:
          - role: pod
            # only scrape data from pods running on the same node as collector
            field: "spec.nodeName=${env:KUBE_NODE_NAME}"
        relabel_configs:
        # scrape pods annotated with "prometheus.io/scrape: true"
        - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
          regex: "true"
          action: keep
        # read the port from "prometheus.io/port: <port>" annotation and update scraping address accordingly
        - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
          action: replace
          target_label: __address__
          regex: ([^:]+)(?::\d+)?;(\d+)
          # escaped $1:$2
          replacement: $$1:$$2
        # do not scrape init containers; the above does not catch this case because most init containers do not have ports defined
        - source_labels: [ __meta_kubernetes_pod_container_init ]
          regex: "false"
          action: keep
        metric_relabel_configs:
        - source_labels: [__name__]
          regex: "(bc_.*|controller_runtime_.*|rest_client_requests_total|velero_.*|node_.*|certmanager_.*|kubelet_.*)"
          action: keep
processors:
  resourcedetection:
    detectors: [env, gcp]
    timeout: 5s
    gcp:
      resource_attributes:
        cloud.provider:
          enabled: true
        cloud.platform:
          enabled: true
        cloud.account.id:
          enabled: true
        cloud.region:
          enabled: true
        cloud.availability_zone:
          enabled: true
        k8s.cluster.name:
          enabled: true
        host.id:
          enabled: false
        host.name:
          enabled: false
  k8sattributes:
    wait_for_metadata: true
    auth_type: "serviceAccount"
    passthrough: false
    filter:
      node_from_env_var: KUBE_NODE_NAME
    extract:
      metadata:
        - k8s.pod.name
        - k8s.pod.uid
        - k8s.deployment.name
        - k8s.deployment.uid
        - k8s.namespace.name
      labels:
        # Extracts the value of a pod label and inserts it as a resource attribute
        - tag_name: service_name
          key: tags.datadoghq.com/service
          from: pod
        - tag_name: version
          key: tags.datadoghq.com/version
          from: pod
        - tag_name: label_k8s_bluecore_com_team
          key: k8s.bluecore.com/team
          from: pod
    pod_association:
      # below association takes a look at the datapoint's k8s.pod.uid resource attribute and tries to match it with
      # the pod having the same attribute.
      - sources:
          - from: resource_attribute
            name: k8s.pod.uid
  batch:
    send_batch_max_size: 1000
    send_batch_size: 100
    timeout: 10s
exporters:
  debug:
    verbosity: detailed
    sampling_initial: 5
    sampling_thereafter: 200
service:
  pipelines:
    metrics/bc:
      receivers: [prometheus/bc]
      processors:
        - batch
        - resourcedetection
        - k8sattributes
      exporters:
        - debug
```

### Log output

```shell
Immediately after otel pods restart, note that k8s.deployment.name is missing as a resource attribute but the other extracted metadata is present:

Resource attributes:
     -> service.name: Str(bc-prom)
     -> net.host.name: Str(<ip>)
     -> server.address: Str(<ip>)
     -> service.instance.id: Str(<ip>:9102)
     -> net.host.port: Str(9102)
     -> http.scheme: Str(http)
     -> server.port: Str(9102)
     -> url.scheme: Str(http)
     -> cluster_name: Str(<cluster_name>)
     -> k8s.pod.name: Str(txnl-api-5fc5f496c5-r4grd)
     -> k8s.pod.uid: Str(03a84821-8629-4345-b265-c5018856468d)
     -> k8s.container.name: Str(txnl-api)
     -> k8s.namespace.name: Str(txnl-api)
     -> pod: Str(txnl-api-5fc5f496c5-r4grd)
     -> cloud.provider: Str(gcp)
     -> cloud.account.id: Str(<cluster_name>)
     -> cloud.platform: Str(gcp_kubernetes_engine)
     -> cloud.region: Str(<region>)
     -> label_k8s_bluecore_com_team: Str(<team>)
     -> service_name: Str(txnl-api)
     -> version: Str(7c79a41)
```

Also notice that the k8s.daemonset.name attribute IS present immediately after otel pods restart:
```
Resource attributes:
     -> service.name: Str(bc-prom)
     -> net.host.name: Str(<ip>)
     -> server.address: Str(<ip>)
     -> service.instance.id: Str(<ip>:9100)
     -> net.host.port: Str(9100)
     -> http.scheme: Str(http)
     -> server.port: Str(9100)
     -> url.scheme: Str(http)
     -> k8s.namespace.name: Str(otel-system)
     -> pod: Str(prometheus-node-exporter-c9xsw)
     -> k8s.pod.name: Str(prometheus-node-exporter-c9xsw)
     -> k8s.pod.uid: Str(37b69e3e-6589-4aae-806e-a0009822bf25)
     -> k8s.container.name: Str(node-exporter)
     -> k8s.daemonset.name: Str(prometheus-node-exporter)
     -> cloud.provider: Str(gcp)
     -> cloud.account.id: Str(<cluster_name>)
     -> cloud.platform: Str(gcp_kubernetes_engine)
     -> cloud.region: Str(<region>)
     -> cluster_name: Str(<cluster_name>)
```

After about 5 minutes, with no further changes, the resource DOES contain the k8s.deployment.name attribute:
```
Resource attributes:
     -> service.name: Str(bc-prom)
     -> net.host.name: Str(<ip>)
     -> server.address: Str(<ip>)
     -> service.instance.id: Str(<ip>:9102)
     -> net.host.port: Str(9102)
     -> http.scheme: Str(http)
     -> server.port: Str(9102)
     -> url.scheme: Str(http)
     -> k8s.pod.name: Str(txnl-api-5fc5f496c5-8khhd)
     -> k8s.pod.uid: Str(90eda72b-4dc7-40e9-bf4a-f9827b298315)
     -> k8s.container.name: Str(txnl-api)
     -> k8s.namespace.name: Str(txnl-api)
     -> cluster_name: Str(<cluster_name>)
     -> pod: Str(txnl-api-5fc5f496c5-8khhd)
     -> cloud.provider: Str(gcp)
     -> cloud.account.id: Str(<cluster_name>)
     -> cloud.platform: Str(gcp_kubernetes_engine)
     -> cloud.region: Str(<region>)
     -> k8s.deployment.name: Str(txnl-api)
     -> k8s.deployment.uid: Str(f5d96967-5e4a-4728-8f12-ae7ad969b42e)
     -> service_name: Str(txnl-api)
     -> version: Str(7c79a41)
     -> label_k8s_bluecore_com_team: Str(<team>)
```
```


### Additional context

_No response_

### PR DESCRIPTION
**Pull request by bacherfl**
#### Description

This PR is an alternative approach to the previous fix made for #37056, which did not fully solve the issue of the deployment name not being added to a pod after the initial informer sync

#### Link to tracking issue
Fixes #37056

#### Testing
Re-enabled the flaky E2E test

### CODE REVIEW

File: processor/k8sattributesprocessor/internal/kube/client.go [hunk 1]
```diff
@@ -210,9 +210,11 @@ func New(
 func (c *WatchClient) Start() error {
 	synced := make([]cache.InformerSynced, 0)
 
+	waitForReplicaSets := false
 	// start the replicaSet informer first, as the replica sets need to be
 	// present at the time the pods are handled, to correctly establish the connection between pods and deployments
 	if c.Rules.DeploymentName || c.Rules.DeploymentUID {
+		waitForReplicaSets = true
```
Comment (ChrsMark) [inline processor/k8sattributesprocessor/internal/kube/client.go:217]: Waiting for the ReplicaSet informer to sync before allowing Pod informer to sync make sense.

Should we consider waiting for other resources too before unblocking the Pod's sync?

I wonder if it is just cleaner to start all the informers in parallel except of the Pod informer, wait for them to sync and then start the Pod informer eventually ensuring that all the dependencies are in sync.

Comment (bacherfl) [reply processor/k8sattributesprocessor/internal/kube/client.go]: good suggestion - I modified the initialisation to wait for all other informers before starting the pod informer, and this makes it a bit cleaner. This will also make it safer for the future in case there might be other instances of where a pod requires information of another resource to already be in the cache.

File: processor/k8sattributesprocessor/internal/kube/client.go [hunk 2]
```diff
@@ -210,6 +210,7 @@ func New(
 func (c *WatchClient) Start() error {
 	synced := make([]cache.InformerSynced, 0)
 
+	waitForInformers := []cache.SharedInformer{}
```
Comment (ChrsMark) [inline processor/k8sattributesprocessor/internal/kube/client.go:213]: Do we need a second array for the informers? I would try to just use the `synced` directly excluding the Pod's sync status.

File: processor/k8sattributesprocessor/internal/kube/client.go [hunk 3]
```diff
@@ -222,21 +223,11 @@ func (c *WatchClient) Start() error {
 			return err
 		}
 		synced = append(synced, reg.HasSynced)
-		go c.replicasetInformer.Run(c.stopCh)
+		waitForInformers = append(waitForInformers, c.replicasetInformer)
+		go c.runInformer(c.replicasetInformer)
```
Comment (ChrsMark) [inline processor/k8sattributesprocessor/internal/kube/client.go:227]: Do we need the extra function call here? Maybe we can just call directly the `go c.replicasetInformer.Run(c.stopCh)`?

File: processor/k8sattributesprocessor/internal/kube/client.go [hunk 4]
```diff
@@ -257,9 +249,23 @@ func (c *WatchClient) Start() error {
...
 
+	reg, err = c.informer.AddEventHandler(cache.ResourceEventHandlerFuncs{
+		AddFunc:    c.handlePodAdd,
+		UpdateFunc: c.handlePodUpdate,
+		DeleteFunc: c.handlePodDelete,
+	})
+	if err != nil {
+		return err
+	}
+	synced = append(synced, reg.HasSynced)
```
Comment (ChrsMark) [inline processor/k8sattributesprocessor/internal/kube/client.go:264]: I think that eventually we should only block on the pod's `synced` result. The rest syncs are blocking pod's informer to start anyways, right?

File: processor/k8sattributesprocessor/internal/kube/client.go [hunk 5]
```diff
@@ -257,9 +249,23 @@ func (c *WatchClient) Start() error {
...
+
+	// start the podInformer with the prerequisite of the other informers to be finished first
+	go c.runInformer(c.informer, waitForInformers...)
```
Comment (ChrsMark) [inline processor/k8sattributesprocessor/internal/kube/client.go:267]: If we pass the `synced` array of the dependency informers here we are saved from passing the complete Informers' objects to the function.

File: processor/k8sattributesprocessor/internal/kube/client.go [hunk 6]
```diff
@@ -1123,6 +1129,24 @@ func (c *WatchClient) getReplicaSet(uid string) (*ReplicaSet, bool) {
 	return nil, false
 }
 
+// runInformer starts the given informer. This method optionally takes a list of other informers that should complete
+// before the informer is started. This is necessary e.g. for the pod informer which requires the replica set informer
+// to be finished to correctly establish the connection to the replicaset/deployment it belongs to.
+func (c *WatchClient) runInformer(informer cache.SharedInformer, dependencies ...cache.SharedInformer) {
```
Comment (ChrsMark) [inline processor/k8sattributesprocessor/internal/kube/client.go:1135]: How about calling this one `runInformerWithDependencies` and having it receiving a `cache.InformerSynced` array directly?

**Comment by bacherfl** [comment]
after running the tests a number of times, it looks like the e2e tests are passing consistently now, so this should be ready for review

**Review by ChrsMark — COMMENTED** [review]
I left some suggestions based on the following logic:

Step 1: wait for all Informers to get synced before unblocking the Pod's informer start
Step 2. Based on the `waitForMetadata` setting block on Pod's informer sync which is already dependent to the sync of the rest of the informers.

In this, the Pod's informer sync comes as a [task chord](https://ask.github.io/celery/userguide/tasksets.html#chords) which is the only one we need to block on from the main flow since it's already blocked on the rest "internally".

**Comment by bacherfl** [comment]
> I left some suggestions based on the following logic:
> 
> Step 1: wait for all Informers to get synced before unblocking the Pod's informer start Step 2. Based on the `waitForMetadata` setting block on Pod's informer sync which is already dependent to the sync of the rest of the informers.
> 
> In this, the Pod's informer sync comes as a [task chord](https://ask.github.io/celery/userguide/tasksets.html#chords) which is the only one we need to block on from the main flow since it's already blocked on the rest "internally".

Thanks for the review! Those suggestions make sense, I will look into updating the PR accordingly now

File: processor/k8sattributesprocessor/internal/kube/client.go [hunk 7]
```diff
@@ -1123,6 +1126,24 @@ func (c *WatchClient) getReplicaSet(uid string) (*ReplicaSet, bool) {
...
+func (c *WatchClient) runInformerWithDependencies(informer cache.SharedInformer, dependencies []cache.InformerSynced) {
+	if len(dependencies) > 0 {
+		timeoutCh := make(chan struct{})
+		// TODO hard coding the timeout for now, check if we should make this configurable
+		t := time.AfterFunc(5*time.Second, func() {
+			close(timeoutCh)
+		})
+		defer t.Stop()
+		for _, dependency := range dependencies {
+			cache.WaitForCacheSync(timeoutCh, dependency)
```
Comment (ChrsMark) [inline processor/k8sattributesprocessor/internal/kube/client.go:1141]: nit: Maybe just
```suggestion
			cache.WaitForCacheSync(timeoutCh, dependencies...)
```?

**Review by ChrsMark — APPROVED** [review]
Thank's!

**Comment by ChrsMark** [comment]
@fatsheep9146 @TylerHelmuth @dmitryax could you take a look as well?

File: processor/k8sattributesprocessor/internal/kube/client.go [hunk 8]
```diff
@@ -260,13 +248,28 @@ func (c *WatchClient) Start() error {
...
 
+	reg, err = c.informer.AddEventHandler(cache.ResourceEventHandlerFuncs{
+		AddFunc:    c.handlePodAdd,
+		UpdateFunc: c.handlePodUpdate,
+		DeleteFunc: c.handlePodDelete,
+	})
+	if err != nil {
+		return err
+	}
+
```
Comment (fatsheep9146) [inline processor/k8sattributesprocessor/internal/kube/client.go:259]: Why not add podInformer's HasSynced into the slice `synced`

Comment (bacherfl) [reply processor/k8sattributesprocessor/internal/kube/client.go:259]: the `synced` slice contains the informers that need to be completed before the pod informer can start. Adding the pod informer's HasSynced to this slice would therefore cause the informer to stall indefinitely. Once the pod informer has started, we wait for it to be finished further down below - i.e. [here](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/37138/files#diff-da945276e27b1e0a3eed6a7e4a97c5b1bb9d90da43bd8ef9fce8b533584d4292R272)

**Review by fatsheep9146 — APPROVED** [review]

File: processor/k8sattributesprocessor/internal/kube/client.go (hunk 8 above)
Comment (fatsheep9146) [reply processor/k8sattributesprocessor/internal/kube/client.go:259]: Got it, thanks for explaining.
