### PR TITLE
[receiver/kafka] Fix bug that was blocking shutdown

### LINKED ISSUE #30789: Kafka receiver stuck while shutting down at v0.93.0
### Component(s)

receiver/kafka

## Description
Shutting down kafka receiver got stuck forever while transitioning from `StatusStopping` to `StatusStopped`.

I've debugged this for a while and apparently this is because of `consumeLoop` returns `context canceled` error and do `ReportStatus FatalErrorEvent` at `receiver/kafkareceiver/kafka_receiver.go` between line 163-165. But the `sync.Mutex.Lock()` in `ReportStatus FatalErrorEvent` never gets unlocked (I don't know why), so that the `ReportStatus` for `StatusStopped` stuck forever while trying to acquire the mutex lock.

Also, I've tried to rollback to v0.92.0 and it works well. And traced to issue down to `receiver/kafkareceiver/kafka_receiver.go` at line 164 `c.settings.ReportStatus(component.NewFatalErrorEvent(err))` changed at PR https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/30593 was the cause.

## Steps to Reproduce
Create a collector with `kafkareceiver` factory in it. And have a `receivers.kafka` in the config.

## Expected Result
Should be able to shutdown properly.

## Actual Result
Stuck indefinitely while shutting down with the logs below.

### Collector version

v0.93.0

### Environment information

_No response_

### OpenTelemetry Collector configuration

```yaml
service:
  pipelines:
    traces:
      receivers: [kafka]

receivers:
  kafka:
    brokers:
      - localhost:9092
    encoding: otlp_proto # available encodings are otlp_proto, jaeger_proto, jaeger_json, zipkin_proto, zipkin_json, zipkin_thrift
    initial_offset: earliest # consume messages from the beginning
```

### Log output

```shell
2024-01-26T08:32:45.266+0700	info	kafkareceiver@v0.93.0/kafka_receiver.go:431	Starting consumer group	{"kind": "receiver", "name": "kafka", "data_type": "traces", "partition": 0}
^C2024-01-26T08:32:53.626+0700	info	otelcol@v0.93.0/collector.go:258	Received signal from OS	{"signal": "interrupt"}
2024-01-26T08:32:53.626+0700	info	service@v0.93.0/service.go:179	Starting shutdown...
2024-01-26T08:32:54.010+0700	info	kafkareceiver@v0.93.0/kafka_receiver.go:181	Consumer stopped	{"kind": "receiver", "name": "kafka", "data_type": "traces", "error": "context canceled"}
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by crobert-1**
**Description:** <Describe what has changed.>

The kafka receiver's shutdown method is to cancel the context of a running sub goroutine. However, a small bug was causing a fatal error to be reported during shutdown when this expected condition was hit. The fatal error being reported during shutdown was causing another bug to be hit, https://github.com/open-telemetry/opentelemetry-collector/issues/9824.

This fix means that shutdown won't be blocked in expected shutdown conditions, but the `core` bug referenced above means shutdown will still be block in unexpected error situations. 

This fix is being taken from a comment made by @Dennis8274 on the issue.

**Link to tracking Issue:** <Issue number if applicable>
Fixes #30789

**Testing:** <Describe what testing was performed and which tests were added.>
Stepped through `TestTracesReceiverStart` in a debugger before the change to see the fatal status being reported. It was no longer reported after applying the fix. Manually tested running the collector with a kafka receiver and saw that before the fix it was indeed being blocked on a normal shutdown, but after the fix it shutdown as expected.

### CODE REVIEW

File: receiver/kafkareceiver/kafka_receiver.go [hunk 1]
```diff
@@ -126,8 +127,8 @@ func createKafkaClient(config Config) (sarama.ConsumerGroup, error) {
 	return sarama.NewConsumerGroup(config.Brokers, config.GroupID, saramaConfig)
 }
 
-func (c *kafkaTracesConsumer) Start(_ context.Context, _ component.Host) error {
-	ctx, cancel := context.WithCancel(context.Background())
+func (c *kafkaTracesConsumer) Start(ctx context.Context, _ component.Host) error {
```
Comment (crobert-1) [inline receiver/kafkareceiver/kafka_receiver.go:130]: I can remove this change if necessary since it's unrelated to the bug fix, but the receiver should be creating the child context from the passed in context, not `context.Background`. Let me know if this should be removed.

**Review by yurishkuro — APPROVED** [review]

**Review by mwear — APPROVED** [review]

**Review by atoulme — APPROVED** [review]

File: receiver/kafkareceiver/kafka_receiver.go (hunk 1 above)
Comment (MovieStoreGuy) [reply receiver/kafkareceiver/kafka_receiver.go:130]: From the [component.Start](https://github.com/open-telemetry/opentelemetry-collector/blob/main/component/component.go#L28:L40) method:

> 	// If the component needs to perform a long-running starting operation then it is recommended
	// that Start() returns quickly and the long-running operation is performed in background.
	// In that case make sure that the long-running operation does not use the context passed
	// to Start() function since that context will be cancelled soon and can abort the long-running
	// operation. Create a new context from the context.Background() for long-running operations.

I worry this works by exiting quickly and doesn't run for the complete time. Can I ask you to confirm that this approach works and the advice provided by the type is out of date?

Comment (crobert-1) [reply receiver/kafkareceiver/kafka_receiver.go:130]: I'll test when I get a chance, but definitely not worth going against the spec for this change. Thanks for bringing this up @MovieStoreGuy, I hadn't seen that in the spec!

File: receiver/kafkareceiver/kafka_receiver.go [hunk 2]
```diff
@@ -126,8 +127,8 @@ func createKafkaClient(config Config) (sarama.ConsumerGroup, error) {
...
+	ctx, cancel := context.WithCancel(ctx)
```
Comment (crobert-1) [inline receiver/kafkareceiver/kafka_receiver.go:131]:
```suggestion
	ctx, cancel := context.WithCancel(context.Background())
```

File: receiver/kafkareceiver/kafka_receiver.go (hunk 1 above)
Comment (crobert-1) [inline receiver/kafkareceiver/kafka_receiver.go:130]:
```suggestion
func (c *kafkaTracesConsumer) Start(_ context.Context, _ component.Host) error {
```

Comment (crobert-1) [reply receiver/kafkareceiver/kafka_receiver.go]: I was able to test, it looks like using the passed in context works today when running the collector from the CLI, since the collector is starting components synchronously in the same goroutine. The context being passed in isn't cancelled within the lifespan of this component, as the child context created by `WithCancel` is cancelled during `Shutdown` before the passed in context is closed.

Still worth removing to conform to the spec though, I could imagine relying on `context.Background` being useful in different system architectures down the road.

**Review by fatsheep9146 — APPROVED** [review]

**Review by MovieStoreGuy — APPROVED** [review]
