### PR TITLE
[processor/k8sattribute] k8sattribute deployment logic enhancement

### LINKED ISSUE #12936: [processor/k8sattributes] k8s.deployment.name attribute can be set to a wrong value
`k8s.deployment.name` attribute value is taken from the pod name using regexp. This is not a robust approach. In some scenarios it can set the attribute to a wrong value. For example a Stateful Set called `sts-test` will create a pod called `sts-test-1`, telemetry from that pod will get the attribute `k8s.deployment.name: sts` which is incorrect, `k8s.deployment.name` should not be set for such pod.

There are two ways to solve the problem:

1. Make the [regexp](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/processor/k8sattributesprocessor/internal/kube/client.go#L64) more strict. This will lower chances for getting a wrong attribute, but it's impossible to completely eliminate the chances with the regexp approach

2. Use the k8s API to fetch an owner of the pod, check if it's replicaset controlled by a deployment, then set the correct value for `k8s.deplyment.name` attribute. This is a robust approach, but we need to make sure it doesn't introduce a significant computational overhead and load on k8s API.

### PR DESCRIPTION
**Pull request by fatsheep9146**
**Description:** <Describe what has changed.>
fix #12936

### CODE REVIEW

File: processor/k8sattributesprocessor/internal/kube/client.go [hunk 1]
```diff
@@ -313,6 +306,12 @@ func (c *WatchClient) extractPodAttributes(pod *api_v1.Pod) map[string]string {
 				if c.Rules.ReplicaSetName {
 					tags[conventions.AttributeK8SReplicaSetName] = ref.Name
 				}
+				if c.Rules.Deployment {
+					parts := c.deploymentRegex.FindStringSubmatch(pod.Name)
```
Comment (dmitryax) [inline processor/k8sattributesprocessor/internal/kube/client.go:310]: I thought we agreed to apply regex on the replicaset name to reduce chance of deducting a wrong name

**Review by dmitryax — COMMENTED** [review]
Why so many changes in tests?

File: processor/k8sattributesprocessor/internal/kube/client.go [hunk 2]
```diff
@@ -292,18 +292,11 @@ func (c *WatchClient) extractPodAttributes(pod *api_v1.Pod) map[string]string {
...
-			tags[conventions.AttributeK8SDeploymentName] = parts[1]
-		}
-	}
-
 	if c.Rules.ReplicaSetID || c.Rules.ReplicaSetName ||
 		c.Rules.DaemonSetUID || c.Rules.DaemonSetName ||
 		c.Rules.JobUID || c.Rules.JobName ||
-		c.Rules.StatefulSetUID || c.Rules.StatefulSetName {
+		c.Rules.StatefulSetUID || c.Rules.StatefulSetName ||
+		c.Rules.Deployment {
```
[the remark this answers is not in the document]
Comment (dmitryax) [reply processor/k8sattributesprocessor/internal/kube/client.go:299]: Actually ignore this comment. We can keep it here to avoid code duplication. The overhead is negligible

**Comment by fatsheep9146** [comment]
> Why so many changes in tests?

I first refracted the test, but then found @povilasv already enhance the test with better way. So I already reverted the changes I made to test.

File: processor/k8sattributesprocessor/internal/kube/client.go (hunk 1 above)
Comment (fatsheep9146) [reply processor/k8sattributesprocessor/internal/kube/client.go]: Done

File: processor/k8sattributesprocessor/internal/kube/client.go [hunk 3]
```diff
@@ -59,9 +59,9 @@ type WatchClient struct {
 	Namespaces map[string]*Namespace
 }
 
-// Extract deployment name from the pod name. Pod name is created using
-// format: [deployment-name]-[Random-String-For-ReplicaSet]-[Random-String-For-Pod]
-var dRegex = regexp.MustCompile(`^(.*)-[0-9a-zA-Z]*-[0-9a-zA-Z]*$`)
+// Extract replicaset name from the pod name. Pod name is created using
+// format: [deployment-name]-[Random-String-For-ReplicaSet]
+var rRegex = regexp.MustCompile(`^(.*)-[0-9a-zA-Z]*$`)
```
Comment (dmitryax) [inline processor/k8sattributesprocessor/internal/kube/client.go:64]:
```suggestion
var rRegex = regexp.MustCompile(`^(.*)-[0-9a-zA-Z]+$`)
```

I don't believe all these symbols are really being used, but at least let's make sure we require the suffix for the match

**Review by dmitryax — COMMENTED** [review]
Just one nit. Otherwise LGMT

**Review by dmitryax — APPROVED** [review]
