### PR TITLE
[spanmetrics] Fix initialization of the default histogram buckets when the `seconds` unit is provided.

### LINKED ISSUE #21797: connector/spanmetrics: unreasonable default histogram buckets if unit=seconds
### Component(s)

connector/spanmetrics

## Description

If using spanemtrics connector with "explicit" bucket config and seconds as unit, but not setting bucket boundaries, it seems buckets default to millisecond ones and don't make sense for seconds. Everything falls into `2` bucket :) 

## Steps to Reproduce
Use this spanmetrics connector config:
```
connectors:
  spanmetrics:
    namespace: "traces.spanmetrics"
    histogram:
      unit: "s"
      explicit:
```

### Collector version

0.75.0

### Environment information

_No response_

### OpenTelemetry Collector configuration

```yaml
# extra settings to be merged into OpenTelemetry Collector configuration
# do not delete this file
receivers:
  fluentforward:
    endpoint: otelcol:24224

exporters:
  logging:
    verbosity: detailed
  otlp/tempo:
    endpoint: tempo:4317
    tls:
      insecure: true
  # TODO spanmetrics does not work correctly with prometheus exporter, until it is fixed we will
  # use prometheusremotewrite instead
  prometheusremotewrite:
    endpoint: http://prometheus:9090/api/v1/write
    target_info:
      enabled: true
  loki:
    endpoint: http://loki:3100/loki/api/v1/push

processors:
  attributes:
    actions:
      - action: insert
        key: service.name
        from_attribute: container_name
      - action: insert
        key: service.namespace
        value: opentelemetry-demo
      - action: insert
        key: service.instance.id
        from_attribute: container_id
      - action: insert
        key: service_name
        from_attribute: container_name
      - action: insert
        key: loki.attribute.labels
        value: service_name

  groupbyattrs:
    keys:
      - service.name
      - service.namespace
      - service.instance.id

  transform/grafanacloudapm:
    trace_statements:
      - context: span
        statements:
          - replace_match(attributes["http.target"], "/api/products/*", "/api/products/{productId}")
          - set(name, Concat([attributes["http.method"], attributes["http.target"]], " ")) where name == "HTTP GET" and attributes["http.target"] != nil
          - set(name, Concat([attributes["http.method"], attributes["http.target"]], " ")) where name == "HTTP POST" and attributes["http.target"] != nil
  transform/fluentd:
    log_statements:
      - context: log
        statements:
          - replace_pattern(attributes["container_name"], "^/", "")
          - replace_pattern(attributes["container_name"], "\\-", "")
  batch:
  filter:
    error_mode: ignore
    traces:
      span:
        # filter out internal spans
        - "kind == 1"
  # TODO remove once Tempo span to metrics generator is aligned with OTel spanmetrics,
  # see https://docs.google.com/document/d/1iSvlc0Sg0HY86kf_0ApTTQmVze8PHnRSMYadSmU5qpQ/edit#
  metricstransform:
    transforms:
      - include: traces.spanmetrics.duration
        action: update
        new_name: traces.spanmetrics.latency
      - include: traces.spanmetrics.calls
        action: update
        new_name: traces.spanmetrics.calls.total

connectors:
  spanmetrics:
    namespace: "traces.spanmetrics"
    histogram:
      unit: "s"
      explicit:

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [filter, transform/grafanacloudapm, batch]
      exporters: [spanmetrics]
    metrics:
      receivers: [spanmetrics]
      processors: [metricstransform, batch]
      exporters: [prometheusremotewrite]
    metrics/otlp:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheusremotewrite]
    traces/tempo:
      receivers: [otlp]
      processors: [transform/grafanacloudapm, batch]
      exporters: [otlp/tempo]
    logs:
      receivers: [otlp, fluentforward]
      processors: [transform/fluentd, attributes, groupbyattrs]
      exporters: [loki]
```

### Log output

_No response_

### Additional context

Would make sense to use bucket boundaries that are prescribed for `http.server.duration` in the spec: https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/semantic_conventions/http-metrics.md#http-server

### PR DESCRIPTION
**Pull request by kovrus**
**Description:** <Describe what has changed.>

Fix initialization of the default histogram buckets when the `seconds` unit is provided.

**Link to tracking Issue:** <Issue number if applicable>
Resolves https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/21797

**Testing:** <Describe what testing was performed and which tests were added.>
Unit tests

### CODE REVIEW

**Comment by kovrus** [comment]
cc: @domasx2

**Review by andrzej-stencel — APPROVED** [review]

**Review by atoulme — APPROVED** [review]

File: connector/spanmetricsconnector/connector.go [hunk 1]
```diff
@@ -127,19 +127,30 @@ func newConnector(logger *zap.Logger, config component.Config, ticker *clock.Tic
 	}, nil
 }
 
-func (p *connectorImp) initHistogramMetrics() metrics.HistogramMetrics {
-	cfg := p.config
+func initHistogramMetrics(cfg *Config) metrics.HistogramMetrics {
```
Comment (albertteoh) [inline connector/spanmetricsconnector/connector.go:130]: Why pass Config as a pointer; it looks like it's read-only?

File: connector/spanmetricsconnector/connector.go [hunk 2]
```diff
@@ -127,19 +127,30 @@ func newConnector(logger *zap.Logger, config component.Config, ticker *clock.Tic
...
 	if cfg.Histogram.Explicit != nil && cfg.Histogram.Explicit.Buckets != nil {
 		bounds = durationsToUnits(cfg.Histogram.Explicit.Buckets, unitDivider(cfg.Histogram.Unit))
+	} else {
+		switch cfg.Histogram.Unit {
+		case metrics.Milliseconds:
+			bounds = defaultHistogramBucketsMs
+		case metrics.Seconds:
+			bounds = make([]float64, len(defaultHistogramBucketsMs))
+			for i, v := range defaultHistogramBucketsMs {
+				bounds[i] = v / float64(time.Second.Milliseconds())
```
Comment (albertteoh) [inline connector/spanmetricsconnector/connector.go:149]: Did you consider the suggestion from: https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/21797 of using the bucket boundaries prescribed for `http.server.duration` suggested in: https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/semantic_conventions/http-metrics.md#http-server?

Comment (albertteoh) [reply connector/spanmetricsconnector/connector.go:138]: Sure thing, makes sense 👍🏼

**Review by albertteoh — APPROVED** [review]
