### PR TITLE
[receiver/sqlquery] Fix memory leak and failing tests

### LINKED ISSUE #31782: [receiver/sqlquery] Broken Test TestPostgresIntegrationLogsTrackingWithStorage
### Component(s)

receiver/sqlquery

### What happened?

Since https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/31667 was merged the `TestPostgresIntegrationLogsTrackingWithStorage` integration test has started failing silently for some reason.

You can see the failures inside the `Run Integration Test` step in jobs like:
- https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/8254951071/job/22580335315
- https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/8268349528/job/22621241890
any another other job since.

image

For some reason my `update-otel` PR is actually showing the failure: https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/8300689476/job/22720973013

### Collector version

Latest

### Environment information

_No response_

### OpenTelemetry Collector configuration

_No response_

### Log output

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by crobert-1**
**Description:** <Describe what has changed.>

This PR includes two changes that are dependent on each other.

1. Fix test failing in https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/31778. Explanation given [here.](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/31778#issuecomment-2000561498) All changes in `integration_test.go` are related to this.
2. When the test was fixed, `goleak` started failing. The logs receiver opens a DB connection when it's started, but shutdown does not close the DB. This DB needs to be closed during shutdown to avoid a leaked goroutine. All changes outside of `integration_test.go` are for this.
3. Since the memory leak changes were modifying errors, I moved from using `multierr.append` to `errors.Join` as well.

**Link to tracking Issue:** <Issue number if applicable>
Resolves #31782
Related to https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/31778

**Testing:** <Describe what testing was performed and which tests were added.>
Tests are passing

### CODE REVIEW

File: receiver/sqlqueryreceiver/logs_receiver.go [hunk 1]
```diff
@@ -174,13 +174,13 @@ func (receiver *logsReceiver) Shutdown(ctx context.Context) error {
 		return nil
 	}
 
+	var errors error
 	receiver.settings.Logger.Debug("stopping...")
 	receiver.stopCollecting()
 	for _, queryReceiver := range receiver.queryReceivers {
-		queryReceiver.shutdown(ctx)
+		errors = multierr.Append(errors, queryReceiver.shutdown(ctx))
```
Comment (TylerHelmuth) [inline receiver/sqlqueryreceiver/logs_receiver.go:181]: Lets not use `multierror`, we recently had a PR to remove its use: https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/31768

Comment (TylerHelmuth) [reply receiver/sqlqueryreceiver/logs_receiver.go:181]: NVM, that was the internal package.

**Review by TylerHelmuth — APPROVED** [review]

File: receiver/sqlqueryreceiver/logs_receiver.go (hunk 1 above)
Comment (crobert-1) [reply receiver/sqlqueryreceiver/logs_receiver.go:181]: Good call, I've updated.

File: receiver/sqlqueryreceiver/logs_receiver.go [hunk 2]
```diff
@@ -286,19 +286,19 @@ func (queryReceiver *logsQueryReceiver) collect(ctx context.Context) (plog.Logs,
...
 			rowToLog(row, logsConfig, logRecord)
 			logRecord.SetObservedTimestamp(observedAt)
 			if logsConfigIndex == 0 {
-				errs = multierr.Append(errs, queryReceiver.storeTrackingValue(ctx, row))
+				errs = append(errs, queryReceiver.storeTrackingValue(ctx, row))
 			}
 		}
 	}
-	return logs, nil
+	return logs, errors.Join(errs...)
```
Comment (crobert-1) [inline receiver/sqlqueryreceiver/logs_receiver.go:301]: `errs` was originally being put together in the above loop, but not returned. I assume this was a bug and `errs` should be returned.

File: receiver/sqlqueryreceiver/logs_receiver.go (hunk 1 above)
Comment (crobert-1) [reply receiver/sqlqueryreceiver/logs_receiver.go]: I've updated to use `errors.Join`, I'm fine with leaving it in (even though the scope of this PR is pretty wide now), or removing it. Just let me know.
