### PR TITLE
[exporter/datadog] Fail when API validation key failed with a 403

### LINKED ISSUE #33935: [exporter/datadog] Error returned from authAPI.Validate is not propagated
### Component(s)

exporter/datadog

## Description

The error returned from `Validate` is not returned. I'm not sure if this is intentional or not. From debugging this and entering an invalid API key I see an error of `403 forbidden` is returned but only logged.
https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/6ff2a8a5ec508d8b0833836089721a4a1a0b8651/exporter/datadogexporter/internal/clientutil/api.go#L39-L53

### Collector version

v0.104.0

### Environment information

_No response_

### OpenTelemetry Collector configuration

_No response_

### Log output

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by mx-psi**
**Description:** <Describe what has changed.>

The API key validation endpoint returns a 403 in some situations when validating an API key. This makes the exporter fail on that case.

**Link to tracking Issue:** Fixes #33935

### CODE REVIEW

**Review by songy23 — APPROVED** [review]

File: exporter/datadogexporter/internal/clientutil/api.go [hunk 1]
```diff
@@ -46,6 +46,9 @@ func ValidateAPIKey(ctx context.Context, apiKey string, logger *zap.Logger, apiC
 	}
 	if err != nil {
 		logger.Warn("Error while validating API key", zap.Error(err))
+		if httpresp.StatusCode == 403 {
```
Comment (songy23) [inline exporter/datadogexporter/internal/clientutil/api.go:49]: Needs to fix test: https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/9838873873/job/27159740034?pr=33944#step:8:302
