### PR TITLE
Fix incorrect pod metadata assignment when  contains a non-IP hostname

### LINKED ISSUE #43938: Stop treating host.name associations as pod IPs
### Component(s)

processor/k8sattributes

### What happened?

The k8sattributes processor currently assumes that the host.name resource attribute always contains a pod IP.

When an upstream component reports a textual hostname instead—say, metrics-indexer—the processor still tries to look up a pod using that string and ends up returning metadata for whichever pod last registered with that hostname. The effect is that spans or metrics from one workload can suddenly carry labels from an unrelated workload, such as k8s_statefulset_name="metrics-indexer" appearing on traffic originating from another service, which both confuses debugging and inflates label cardinality.

### Collector version

76b4c60780c1f83a039ef7e6381bd2a2e1345ff0

### Environment information

_No response_

### OpenTelemetry Collector configuration

```yaml

```

### Log output

```shell

```

### Additional context

_No response_

### Tip

<sub>[React](https://github.blog/news-insights/product-news/add-reactions-to-pull-requests-issues-and-comments/) with 👍 to help prioritize this issue. Please use comments to provide useful context, avoiding `+1` or `me too`, to help us triage it. Learn more [here](https://opentelemetry.io/community/end-user/issue-participation/).</sub>

### PR DESCRIPTION
**Pull request by iblancasa**
#### Link to tracking issue
Fixes #43938

### CODE REVIEW

**Comment by iblancasa** [comment]
@dmitryax @fatsheep9146 @tylerbenson @ChrsMark can you take a look? :) Thanks!

File: processor/k8sattributesprocessor/pod_association.go [hunk 1]
```diff
@@ -47,7 +47,7 @@ func extractPodID(ctx context.Context, attrs pcommon.Map, associations []kube.As
 				// If association configured by resource_attribute
 				// In k8s environment, host.name label set to a pod IP address.
 				// If the value doesn't represent an IP address, we skip it.
-				if asso.Name == string(conventions.HostNameKey) && net.ParseIP(attributeValue) == nil {
+				if source.Name == string(conventions.HostNameKey) && net.ParseIP(attributeValue) == nil {
```
Comment (ChrsMark) [inline processor/k8sattributesprocessor/pod_association.go:50]: It seems that [`Association.Name`](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/f562ab5d2aa8bdb3c11a205d072d99858116339f/processor/k8sattributesprocessor/internal/kube/kube.go#L402) is not used in any other place apart from here. I guess we could remove it entirely?
I haven't seen this being used in configurations actually. @dmitryax @TylerHelmuth any thoughts on this?

**Review by ChrsMark — APPROVED** [review]

File: processor/k8sattributesprocessor/pod_association.go (hunk 1 above)
Comment (iblancasa) [reply processor/k8sattributesprocessor/pod_association.go:50]: Ping  @dmitryax

Comment (dmitryax) [reply processor/k8sattributesprocessor/pod_association.go:50]: Yes, seems like Association.Name is a leftover from https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/8465 and can be removed in a separate PR

**Review by dmitryax — APPROVED** [review]
