### PR TITLE
[resourcedetection] Add api provider to eks detector

### LINKED ISSUE #39503: [processor/resourcedetection] Support EKS Auto Mode cluster
### Component(s)

[processor/resourcedetection] 

## Description
`EKS Auto Mode` cluster does not provide `IMDS` access unless the pod is running in `hostNetwork` .

https://docs.aws.amazon.com/eks/latest/userguide/automode-learn-instances.html#_instance_metadata_service
```
If a pod absolutely requires IMDS access when running in Auto Mode:
The pod must be configured to run with hostNetwork: true
This allows the pod to access the instance metadata service directly
```

This is problematic if the pod is not running with `hostNetwork` as the following detectors and functionalities that pull data from the ec2 metadata server will fail:

1- `ec2` detector uses the metadata server to set the following attributes https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/processor/resourcedetectionprocessor/internal/aws/ec2/ec2.go#L110-L115 and we need to find an alternative way using the instance. 
Suggestion:
- use the k8s api to get the node description and check the `ProviderID` to parse the instanceID and region.
- use the AWS api to describe the instanceID and pull the remaining info needed to set the `ec2` detector attribute
- this solution is only for `ec2` instances running as nodes in k8s cluster, so we need to either have a separate `ec2-eks` detector or add an option to the existing `ec2` detector, example: `eks`, to signal the logic to use this alternate approach

2- `eks` detector. In addition to this fix https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/39486 , the following functionality that depends on `IMDS` will fail.
- `k8s.cluster.name` 
- `cloud.account.id`
This can also be fixed with similar approach as above, ie: use the `ProviderID` to get the `region` and `instanceID` ....

## Steps to Reproduce
Install the collector in k8s `EKS Auto Mode` cluster and make sure the pods are not in hostnetwork.
Also make sure you have a resource detection processor with `eks` (`k8s.cluster.name` and `cloud.account.id` set to true) and `ec2` detector enabled

## Expected Result
All resource attributes are discovered correctly.

## Actual Result
Errors:
```
2025-04-18T16:20:26.893Z	warn	eks/detector.go:155	Unable to get EKS cluster name	{"error": "operation error ec2imds: GetRegion, exceeded maximum number of attempts, 3, http response error StatusCode: 401, request to EC2 IMDS failed"}
```

### Collector version

main

## Important Note

While developing the above suggestion, I have noticed that AWS API client gets its auth credentials through the metadata server endpoint. In other words, we can no longer "transparently" use AWS API calls in EKS AUTO MODE (non hostnetwork pod) as this endpoint is not reachable.
This means that the user needs to explicitly define the AWS credentials. This can be done through different means, example, env variables or using POD Identity.
Pod Identity is the best choice as the agent identity is pre-installed in EKS Auto Mode and the user will only need to create the appropriate role and associate it with the pod SA.

### PR DESCRIPTION
**Pull request by dloucasfx**
#### Description
This is a replacement for this PR https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/39981

- Expanded the resource attributes to be on par with the EC2 detector (the new attributes are set to false by default) https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/40061
- The EKS detector now uses the newly introduced EKS metadata provider when the IMDS service is not available
- If IMDS Service is available, we use the EC2 metadata provider

This is needed for EKS clusters that don't have access to IMDS server and causing the EC2 detector and the accountID/ClusterName attributes in the EKS detector to fail.

#### Link to tracking issue
Fixes https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/39503

#### Testing
Unit tests coverage
Manual deployment on EKS automode cluster

#### Documentation
In addition to the auto generated doc, I added new content to the reamdme

### CODE REVIEW

File: processor/resourcedetectionprocessor/internal/aws/eks/detector.go [hunk 1]
```diff
@@ -64,160 +61,149 @@ var _ detectorUtils = (*eksDetectorUtils)(nil)
...
+		return aws.Config{}, err
 	}
 
-	imdsClient := imds.NewFromConfig(cfg)
-	instanceIdentityDocument, err := imdsClient.GetInstanceIdentityDocument(ctx, &imds.GetInstanceIdentityDocumentInput{})
-	if err != nil {
-		logger.Warn(defaultErrorMessage, zap.Error(err))
-		return ""
+	maxAttempts := e.cfg.MaxAttempts
+	if checkAccess {
```
Comment (atoulme) [inline processor/resourcedetectionprocessor/internal/aws/eks/detector.go:198]: Is this only for the first check?

Comment (dloucasfx) [reply processor/resourcedetectionprocessor/internal/aws/eks/detector.go:198]: yes.
This is mainly used by `isIMDSAccessible` and to make sure we only attempt once
I documented this here https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/40205/files#diff-2fd609a720e95f7ad6fe8c31180f20671dbf62301fba3c9914fcb81a8cc930aaR388

Comment (dloucasfx) [reply processor/resourcedetectionprocessor/internal/aws/eks/detector.go:198]: And if you mean whether to run it "once" , I thought of that and I don't think we should as the state of the network/IMDS might change between detect retries (in case of an error)

File: processor/resourcedetectionprocessor/internal/aws/eks/config.go [hunk 2]
```diff
@@ -4,15 +4,28 @@
...
 )
 
+const imdsCheckMaxRetryDefault = 1
+
 type Config struct {
 	ResourceAttributes metadata.ResourceAttributesConfig `mapstructure:"resource_attributes"`
+	NodeFromEnvVar     string                            `mapstructure:"node_from_env_var"`
+	IMDSCheckMaxRetry  int                               `mapstructure:"imds_check_max_retry"`
+	MaxAttempts        int                               `mapstructure:"max_attempts"`
+	MaxBackoff         time.Duration                     `mapstructure:"max_backoff"`
```
Comment (dmitryax) [inline processor/resourcedetectionprocessor/internal/aws/eks/config.go:21]: Do we really need the additional retries inside the eks detector given that we already have an exponential backoff retry mechanism calling the detector https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/5f2aa3a8dbc2eb6fd3e2f59b37a79b1c54fa805c/processor/resourcedetectionprocessor/internal/resourcedetection.go#L143. Can't we just rely on that instead?

Comment (dloucasfx) [reply processor/resourcedetectionprocessor/internal/aws/eks/config.go:21]: But even them, I still think they each have a different purpose; let's say you have code that uses the client multiple times and it's querying a flaky endpoint, the first query succeeds but the second one didn't on the first try, now that we have partial data, you want the client in this case to try again and not count on the detector retry which will start all over.

The `IMDSCheckMaxRetry` is introduced to set the retry to 1 for test access https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/40205/files#diff-2fd609a720e95f7ad6fe8c31180f20671dbf62301fba3c9914fcb81a8cc930aaR388

Finally, this makes it consistent with the ec2 detector that also exposes the same settings.

Comment (dloucasfx) [reply processor/resourcedetectionprocessor/internal/aws/eks/config.go:21]: I have seen reports on windows EC2 where the network stack might be slow enough for the imds call to fail.
In this case and if user is confident that they have access to imds endpoint, then they can increase it and adjust the health check settings

Comment (dloucasfx) [reply processor/resourcedetectionprocessor/internal/aws/eks/config.go:21]: ... my comment about the windows EC2 reports is actually for a standalone EC2 instance, not a k8s windows node, so I guess with k8s windows node, the network stack should be already established .
But yes, if you don't think we might run into an scenario where the we need to increase the retry, then I am fine removing `imds_check_max_retry`

Comment (dmitryax) [reply processor/resourcedetectionprocessor/internal/aws/eks/config.go:21]: Yes, we should prefer not to expose extra options unless they are needed to solve a problem. Excessive configuration interfaces add complexity for users and make maintenance more challenging.

Comment (dloucasfx) [reply processor/resourcedetectionprocessor/internal/aws/eks/config.go]: @dmitryax 
I removed `imds_check_max_retry` option

File: processor/resourcedetectionprocessor/README.md [hunk 3]
```diff
@@ -319,6 +319,12 @@ processors:
 
 ### Amazon EKS
 
+This detector reads resource information from the [EC2 instance metadata service](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-instance-metadata.html) to retrieve related resource attributes.
+If IMDS is not available, (example: EKS-AutoMode and POD not on the hostnetwork), it falls back to a combination of [Kubernetes API](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.25/#-strong-kubernetes-api-v1-25-strong-) 
+and [EC2 API](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_DescribeInstances.html) to retrieve related resource attributes.
+
+EC2 API requires the `EC2:DescribeInstances` permission to be granted to the IAM role. If IMDS is not accessible, ex: EKS-AutoMode, you can use [POD Identity](https://docs.aws.amazon.com/eks/latest/userguide/pod-identities.html).
```
Comment (dmitryax) [inline processor/resourcedetectionprocessor/README.md:326]: Should we expand a bit how to set up the pod identity to make it work in EKS-AutoMode?

**Review by dmitryax — APPROVED** [review]

File: processor/resourcedetectionprocessor/README.md (hunk 3 above)
Comment (dmitryax) [reply processor/resourcedetectionprocessor/README.md:326]: You're right that's too much

**Comment by dmitryax** [comment]
We discussed this change offline with @dloucasfx and decided that the new retry configuration options are unlikely to be useful in this detector, so we should remove them in a separate PR to keep the configuration interface clean.
