### PR TITLE
[fix] [extensions/storage/filestorage] refactor benchmarks

### LINKED ISSUE #45914: [extension/storage/filestorage]: benchmarks fail locally with Go 1.23+ and measure mostly cache-miss paths
### Component(s)

extension/storage/filestorage

## Description
When running the filestorage benchmarks locally with Go 1.23+ using testing.B.Loop, some benchmarks fail and others measure slightly misleading code paths.
Additionally, several benchmarks primarily measure cache-miss / not-found paths rather than successful operations. (call Get/Batch on keys that were never set )

## Steps to Reproduce
command (from extension/storage/filestorage):
`go test ./... -bench . -run ^$
`
## Expected Result
test PASS
## Actual Result
BenchmarkClientCompactLargeDBFile
    benchmark.go:412: B.Loop called with timer stopped
--- FAIL: BenchmarkClientCompactLargeDBFile
BenchmarkClientCompactDb
    benchmark.go:412: B.Loop called with timer stopped
--- FAIL: BenchmarkClientCompactDb
FAIL

### Collector version

main

## Environment
darwin arm64 apple M2 Max

### Additional context

BenchmarkClientCompactLargeDBFile and BenchmarkClientCompactDb call b.Loop() while the benchmark timer is stopped and then call b.StartTimer() inside the loop body.
With the new testing.B.Loop API (Go 1.23+), the timer must be running when b.Loop() is invoked, so this pattern triggers B.Loop called with timer stopped.

I will open a fix PR soon

### Tip

<sub>[React](https://github.blog/news-insights/product-news/add-reactions-to-pull-requests-issues-and-comments/) with 👍 to help prioritize this issue. Please use comments to provide useful context, avoiding `+1` or `me too`, to help us triage it. Learn more [here](https://opentelemetry.io/community/end-user/issue-participation/).</sub>

### PR DESCRIPTION
**Pull request by RealAnna**
#### Description

This PR fixes and refactors the filestorage benchmarks

### Filestorage benchmarks — main vs this PR (darwin / arm64, Apple M2 Max)

| Benchmark                         | Main ms/op | Main semantics                                           | This PR ms/op | This PR semantics                                                   |
|-----------------------------------|-----------:|----------------------------------------------------------|--------------:|---------------------------------------------------------------------|
| `BenchmarkClientGet`              | 4.26       | `Get` on key that was **never set** (mostly miss).       | 6.92          | `Get` on an **existing** key (read hit).                           |
| `BenchmarkClientGet100`           | 4.27       | Batch `Get` of 100 **missing** keys (100 misses).        | 6.93          | Batch `Get` of 100 **existing** keys.                              |
| `BenchmarkClientSet`              | 8.41       | Single `Set` (overwriting same key).                     | 8.42          | Same: single `Set` (overwrite).                                    |
| `BenchmarkClientSet100`           | 8.27       | Batch `Set` of 100 keys.                                 | 8.16          | Same: batch `Set` of 100 keys.                                     |
| `BenchmarkClientDelete`           | 4.81       | `Delete` on key that quickly stopped existing (miss).    | 6.92          | Delete of existing keys (keys prefilled before measurement).       |
| `BenchmarkClientSetLargeDB`       | 8.24       | `Set` after DB grew large and was mostly cleared.        | 8.61          | Same scenario; slightly higher measured cost.                      |
| `BenchmarkClientInitLargeDB`      | 24.85      | `newClient` on large DB (many entries).                  | 28.56         | Same: `newClient` on large DB.                                     |
| `BenchmarkClientCompactLargeDBFile` | —        | Fails: `B.Loop called with timer stopped`.               | 41,144.60     | Compaction of large DB file (mostly deleted data, one key left).   |
| `BenchmarkClientCompactDb`        | —          | Fails: `B.Loop called with timer stopped`.               | 2,735.23      | Heavier DB compaction scenario (many live + dead pages).           |

> **Note:** The compaction benchmarks previously failed locally due to `B.Loop` being called with the timer stopped. This PR corrects the timer usage and adds proper per‑iteration cleanup so they now complete successfully and measure only the `Compact` call.

#### Link to tracking issue

Fixes #45914

### CODE REVIEW

File: extension/storage/filestorage/client_test.go [hunk 1]
```diff
@@ -411,10 +411,18 @@ func BenchmarkClientGet(b *testing.B) {
...
+	require.NoError(b, client.Set(ctx, testKey, testValue))
 
+	b.ResetTimer()
 	for b.Loop() {
-		_, err = client.Get(ctx, testKey)
+		v, err := client.Get(ctx, testKey)
 		require.NoError(b, err)
+		if len(v) == 0 {
+			b.Fatalf("unexpected empty value")
+		}
```
Comment (swiatekm) [inline extension/storage/filestorage/client_test.go]: We can replace this with a more terse
```suggestion
		require.Equal(t, testValue, v)
```

File: extension/storage/filestorage/client_test.go [hunk 2]
```diff
@@ -430,11 +438,18 @@ func BenchmarkClientGet100(b *testing.B) {
...
 
+	// Pre-populate keys so we measure "hit" batch performance.
+	for i := 0; i < 100; i++ {
+		key := fmt.Sprintf("testKey-%d", i)
+		require.NoError(b, client.Set(ctx, key, []byte("testValue")))
+	}
+
 	testEntries := make([]*storage.Operation, 100)
-	for i := range 100 {
+	for i := 0; i < 100; i++ {
```
Comment (swiatekm) [inline extension/storage/filestorage/client_test.go]: Why are you changing this syntax to the less idiomatic one?

File: extension/storage/filestorage/client_test.go [hunk 3]
```diff
@@ -411,10 +411,18 @@ func BenchmarkClientGet(b *testing.B) {
 
 	ctx := b.Context()
 	testKey := "testKey"
+	testValue := []byte("testValue")
+
+	// Pre-populate so we measure "Get hit" performance.
+	require.NoError(b, client.Set(ctx, testKey, testValue))
 
+	b.ResetTimer()
```
Comment (swiatekm) [inline extension/storage/filestorage/client_test.go]: According to the [documentation](https://pkg.go.dev/testing@go1.24.13#hdr-Benchmarks), we don't need this reset, as only the operations inside the b.Loop() range are timed.

This applies to the other changes as well.

File: extension/storage/filestorage/client_test.go [hunk 4]
```diff
@@ -583,36 +610,42 @@ func BenchmarkClientCompactLargeDBFile(b *testing.B) {
...
 	for n := 0; b.Loop(); n++ {
 		testDbFile := filepath.Join(tempDir, fmt.Sprintf("my_db%d", n))
 		err = os.Link(dbFile, testDbFile)
 		require.NoError(b, err)
+
 		client, err = newClient(zap.NewNop(), testDbFile, time.Second, &CompactionConfig{}, false)
 		require.NoError(b, err)
-		b.StartTimer()
+
+		// Measure Compact (and any work done before it) with the timer running.
```
Comment (swiatekm) [inline extension/storage/filestorage/client_test.go]: Ideally, we should only measure `Compact`. I think I'd prefer switching to an old-style `for range b.N` loop here.

File: extension/storage/filestorage/client_test.go [hunk 5]
```diff
@@ -625,35 +658,41 @@ func BenchmarkClientCompactDb(b *testing.B) {
...
 	for n := 0; b.Loop(); n++ {
 		testDbFile := filepath.Join(tempDir, fmt.Sprintf("my_db%d", n))
 		err = os.Link(dbFile, testDbFile)
 		require.NoError(b, err)
+
 		client, err = newClient(zap.NewNop(), testDbFile, time.Second, &CompactionConfig{}, false)
 		require.NoError(b, err)
-		b.StartTimer()
+
+		// Measure compact with the timer running.
```
Comment (swiatekm) [inline extension/storage/filestorage/client_test.go]: See above, I think it's better to run the loop as `for range b.N` here.

**Review by swiatekm — COMMENTED** [review]
Thank you for trying to improve these! Conceptually, your changes are good. I'm not sure I fully understand why you want to switch from the range loop syntax to the C style one.

**Comment by atoulme** [comment]
Moving to draft while you address feedback, please mark ready for review once done.

File: extension/storage/filestorage/client_test.go [hunk 6]
```diff
@@ -596,23 +612,27 @@ func BenchmarkClientCompactLargeDBFile(b *testing.B) {
 		require.NoError(b, client.Set(ctx, testKey, entry))
 	}
 
-	// Leave one key in the db
+	// Leave one key in the DB.
```
Comment (RealAnna) [inline extension/storage/filestorage/client_test.go]:
```suggestion
	// Leave one key in the db.
```

File: extension/storage/filestorage/client_test.go [hunk 7]
```diff
@@ -596,23 +612,27 @@ func BenchmarkClientCompactLargeDBFile(b *testing.B) {
 		require.NoError(b, client.Set(ctx, testKey, entry))
 	}
 
-	// Leave one key in the db
+	// Leave one key in the db.
```
Comment (RealAnna) [inline extension/storage/filestorage/client_test.go]:
```suggestion
	// Leave one key in the db
```

**Comment by RealAnna** [comment]
@swiatekm thanks! Tried to make the stile coherent switching to range everywhere 😄  let me know if anything else feels amiss!

File: extension/storage/filestorage/client_test.go [hunk 8]
```diff
@@ -492,9 +503,18 @@ func BenchmarkClientDelete(b *testing.B) {
...
+	// We create b.N distinct keys so each Delete is a delete-hit
+	for i := range b.N {
+		key := fmt.Sprintf("%s-%d", testKey, i)
+		require.NoError(b, client.Set(ctx, key, testValue))
+	}
+
+	for i := range b.N {
+		key := fmt.Sprintf("%s-%d", testKey, i)
+		require.NoError(b, client.Delete(ctx, key))
 	}
```
Comment (swiatekm) [inline extension/storage/filestorage/client_test.go]: This is the part we want to measure, so it should be in a b.Loop().

**Review by swiatekm — COMMENTED** [review]
One comment, otherwise looks good to me. Can you re-run the benchmarks and see how they're affected after these final changes?

File: extension/storage/filestorage/client_test.go [hunk 9]
```diff
@@ -492,9 +503,18 @@ func BenchmarkClientDelete(b *testing.B) {
...
-	for b.Loop() {
-		require.NoError(b, client.Delete(ctx, testKey))
+	// Setup: insert unique keys so they exist before being deleted
+	// We create b.N distinct keys so each Delete is a delete-hit
+	for i := range b.N {
+		key := fmt.Sprintf("%s-%d", testKey, i)
+		require.NoError(b, client.Set(ctx, key, testValue))
+	}
+
+	for i := range b.N {
```
Comment (RealAnna) [inline extension/storage/filestorage/client_test.go]:
```suggestion
	for b.Loop() {
```

**Review by swiatekm — APPROVED** [review]
Thank you for fixing these!

**Review by VihasMakwana — APPROVED** [review]
