### PR TITLE
kafkareceiver:franz-go: Fix race on lost partition

### LINKED ISSUE #41239: Data race in franz-go consumer mode for the kafkareceiver
### Component(s)

receiver/kafka

## Description

Data race condition is detected in assignment handling for fetch and lost/rebalance paths.

## Steps to Reproduce
It is an edge case and seems to happen because it is possible for the wait group in `pc` to call `Wait` and potentially be at zero count when the fetch loop triggers `WaitGroup#Add`.

## Expected Result
N/A

## Actual Result
N/A

### Collector version

v0.129.0

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

### OpenTelemetry Collector configuration

```yaml

```

### Log output

```shell
logger.go:146: 2025-07-10T03:03:27.038Z	ERROR	elasticsearchexporter@v0.129.0/bulkindexer.go:368	bulk indexer flush error	{"resource": {"service.instance.id": "5ed07791-6b82-4233-a291-e9a4d2ef3d39", "service.name": "", "service.version": ""}, "otelcol.component.id": "elasticsearch", "otelcol.component.kind": "exporter", "otelcol.signal": "metrics", "error": "flush failed (410): "}
        github.com/open-telemetry/opentelemetry-collector-contrib/exporter/elasticsearchexporter.flushBulkIndexer
        	/go/pkg/mod/github.com/open-telemetry/opentelemetry-collector-contrib/exporter/elasticsearchexporter@v0.129.0/bulkindexer.go:368
        github.com/open-telemetry/opentelemetry-collector-contrib/exporter/elasticsearchexporter.(*syncBulkIndexerSession).Flush
        	/go/pkg/mod/github.com/open-telemetry/opentelemetry-collector-contrib/exporter/elasticsearchexporter@v0.129.0/bulkindexer.go:178
        github.com/open-telemetry/opentelemetry-collector-contrib/exporter/elasticsearchexporter.(*sessionList).Flush.func1
        	/go/pkg/mod/github.com/open-telemetry/opentelemetry-collector-contrib/exporter/elasticsearchexporter@v0.129.0/exporter.go:616
        golang.org/x/sync/errgroup.(*Group).add.func1
        	/go/pkg/mod/golang.org/x/sync@v0.15.0/errgroup/errgroup.go:128
    logger.go:146: 2025-07-10T03:03:27.038Z	ERROR	elasticsearchexporter@v0.129.0/bulkindexer.go:368	bulk indexer flush error	{"resource": {"service.instance.id": "5ed07791-6b82-4233-a291-e9a4d2ef3d39", "service.name": "", "service.version": ""}, "otelcol.component.id": "elasticsearch", "otelcol.component.kind": "exporter", "otelcol.signal": "metrics", "error": "flush failed (410): "}
        github.com/open-telemetry/opentelemetry-collector-contrib/exporter/elasticsearchexporter.flushBulkIndexer
        	/go/pkg/mod/github.com/open-telemetry/opentelemetry-collector-contrib/exporter/elasticsearchexporter@v0.129.0/bulkindexer.go:368
        github.com/open-telemetry/opentelemetry-collector-contrib/exporter/elasticsearchexporter.(*syncBulkIndexerSession).Flush
        	/go/pkg/mod/github.com/open-telemetry/opentelemetry-collector-contrib/exporter/elasticsearchexporter@v0.129.0/bulkindexer.go:178
        github.com/open-telemetry/opentelemetry-collector-contrib/exporter/elasticsearchexporter.(*sessionList).Flush.func1
        	/go/pkg/mod/github.com/open-telemetry/opentelemetry-collector-contrib/exporter/elasticsearchexporter@v0.129.0/exporter.go:616
        golang.org/x/sync/errgroup.(*Group).add.func1
        	/go/pkg/mod/golang.org/x/sync@v0.15.0/errgroup/errgroup.go:128
    logger.go:146: 2025-07-10T03:03:27.038Z	ERROR	internal/base_exporter.go:117	Exporting failed. Rejecting data. Try enabling sending_queue to survive temporary failures.	{"resource": {"service.instance.id": "5ed07791-6b82-4233-a291-e9a4d2ef3d39", "service.name": "", "service.version": ""}, "otelcol.component.id": "elasticsearch", "otelcol.component.kind": "exporter", "otelcol.signal": "metrics", "error": "flush failed (410): ", "rejected_items": 1}
        go.opentelemetry.io/collector/exporter/exporterhelper/internal.(*BaseExporter).Send
        	/go/pkg/mod/go.opentelemetry.io/collector/exporter@v0.129.0/exporterhelper/internal/base_exporter.go:117
        go.opentelemetry.io/collector/exporter/exporterhelper.NewMetricsRequest.newConsumeMetrics.func1
        	/go/pkg/mod/go.opentelemetry.io/collector/exporter@v0.129.0/exporterhelper/metrics.go:193
        go.opentelemetry.io/collector/consumer.ConsumeMetricsFunc.ConsumeMetrics
        	/go/pkg/mod/go.opentelemetry.io/collector/consumer@v1.35.0/metrics.go:27
        go.opentelemetry.io/collector/consumer.ConsumeMetricsFunc.ConsumeMetrics
        	/go/pkg/mod/go.opentelemetry.io/collector/consumer@v1.35.0/metrics.go:27
        github.com/open-telemetry/opentelemetry-collector-contrib/receiver/kafkareceiver.(*metricsHandler).consumeData
        	/go/pkg/mod/github.com/open-telemetry/opentelemetry-collector-contrib/receiver/kafkareceiver@v0.129.0/kafka_receiver.go:209
        github.com/open-telemetry/opentelemetry-collector-contrib/receiver/kafkareceiver.processMessage[...]
        	/go/pkg/mod/github.com/open-telemetry/opentelemetry-collector-contrib/receiver/kafkareceiver@v0.129.0/kafka_receiver.go:315
        github.com/open-telemetry/opentelemetry-collector-contrib/receiver/kafkareceiver.newMetricsReceiver.func1.1
        	/go/pkg/mod/github.com/open-telemetry/opentelemetry-collector-contrib/receiver/kafkareceiver@v0.129.0/kafka_receiver.go:99
        github.com/open-telemetry/opentelemetry-collector-contrib/receiver/kafkareceiver.(*franzConsumer).handleMessage
        	/go/pkg/mod/github.com/open-telemetry/opentelemetry-collector-contrib/receiver/kafkareceiver@v0.129.0/consumer_franz.go:421
        github.com/open-telemetry/opentelemetry-collector-contrib/receiver/kafkareceiver.(*franzConsumer).consume.func2.1
        	/go/pkg/mod/github.com/open-telemetry/opentelemetry-collector-contrib/receiver/kafkareceiver@v0.129.0/consumer_franz.go:244
```

### Additional context

_No response_

### Tip

<sub>[React](https://github.blog/news-insights/product-news/add-reactions-to-pull-requests-issues-and-comments/) with 👍 to help prioritize this issue. Please use comments to provide useful context, avoiding `+1` or `me too`, to help us triage it. Learn more [here](https://opentelemetry.io/community/end-user/issue-participation/).</sub>

### PR DESCRIPTION
**Pull request by marclop**
#### Description
Fixes an edge case where a consumer could lose a partition while it is consuming messages. This leads to unexpected behavior due to the race and likely cause the consumer to malfunction.

#### Link to tracking issue
Fixes #41239

#### Testing
Unit tested

#### Documentation

Added chlog.

### CODE REVIEW

File: receiver/kafkareceiver/consumer_franz.go [hunk 1]
```diff
@@ -387,13 +426,16 @@ func (c *franzConsumer) lost(ctx context.Context, _ *kgo.Client,
 			// balancer on topic lost/deleted.
 			if pc, ok := c.assignments[tp]; ok {
 				delete(c.assignments, tp)
-				pc.cancel(errors.New(
+				// Cancel also locks the partition consumer. This ensures that
+				// the partition consumer is not processing messages when the
```
Comment (axw) [inline receiver/kafkareceiver/consumer_franz.go]:
```suggestion
				// the partition consumer stops processing messages when the
```

I think?

**Review by axw — APPROVED** [review]

**Review by MovieStoreGuy — APPROVED** [review]
