### PR TITLE
metricstarttimeprocessor: add reset detection for histograms

### LINKED ISSUE #38582: Adjuster doesn't detect resets when individual bucket count decreases
### Component(s)

processor/metricstarttime

## Description
When an individual bucket counter decreases but the total count  and sum goes up, the adjuster doesn't recognize the reset: https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/7445a71a944e5623144e86bb7654e80086fab698/processor/metricstarttimeprocessor/internal/truereset/adjuster.go#L112

## Steps to Reproduce
Consider a histogram with 2 buckets:  the buckets with boundaries  0 < x < 1 and 1 < y < 2

And at time `t` I get a histogram point with the following bucket counts {10, 20}
and then at time `t + x` I get another point with the bucket counts {100, 19}

This should trigger a reset as the individual bucket counter should never be decreasing.

### Collector version

latest

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

### OpenTelemetry Collector configuration

```yaml

```

### Log output

```shell

```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by ridwanmsharif**
#### Description
When an individual bucket counter decreases but the total count and sum goes up, the adjuster now recognizes it as a reset.

#### Link to tracking issue
Fixes https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/38582

#### Testing
Added unit tests.

#### Documentation
N/A

### CODE REVIEW

**Comment by ridwanmsharif** [comment]
This is rebased on top of some of the decoupling/refactor work here: https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/38579

**Comment by ridwanmsharif** [comment]
cc @psx95 @aabmass from context of the normalization done in the GCP exporters

File: processor/metricstarttimeprocessor/internal/datapointstorage/timeseries_map.go [hunk 1]
```diff
@@ -102,6 +102,82 @@ func (tsm *TimeseriesMap) GC() {
 	tsm.Mark = false
 }
 
+func (tsi *TimeseriesInfo) IsResetHistogram(h pmetric.HistogramDataPoint) bool {
+	if h.Count() != 0 && tsi.Histogram.Count() != 0 && h.Count() < tsi.Histogram.Count() {
```
Comment (dehaansa) [inline processor/metricstarttimeprocessor/internal/datapointstorage/timeseries_map.go:106]: Should it still be a reset if `h.Count() == 0 && h.Count() < tsi.Histogram.Count()`
```suggestion
	if tsi.Histogram.Count() != 0 && h.Count() < tsi.Histogram.Count() {
```

File: processor/metricstarttimeprocessor/internal/datapointstorage/timeseries_map.go [hunk 2]
```diff
@@ -102,6 +102,82 @@ func (tsm *TimeseriesMap) GC() {
...
+		return true
+	}
+	if h.Sum() != 0 && tsi.Histogram.Sum() != 0 && h.Sum() < tsi.Histogram.Sum() {
```
Comment (dehaansa) [inline processor/metricstarttimeprocessor/internal/datapointstorage/timeseries_map.go:109]:
```suggestion
	if tsi.Histogram.Sum() != 0 && h.Sum() < tsi.Histogram.Sum() {
```

File: processor/metricstarttimeprocessor/internal/datapointstorage/timeseries_map.go [hunk 3]
```diff
@@ -102,6 +102,82 @@ func (tsm *TimeseriesMap) GC() {
...
+		if h.BucketCounts().At(i) < tsi.Histogram.BucketCounts().At(i) {
+			return true
+		}
+	}
+	return false
+}
+
+func (tsi *TimeseriesInfo) IsResetExponentialHistogram(eh pmetric.ExponentialHistogramDataPoint) bool {
+	// Same as the histogram implementation
+	if eh.Count() != 0 && tsi.ExponentialHistogram.Count() != 0 && eh.Count() < tsi.ExponentialHistogram.Count() {
```
Comment (dehaansa) [inline processor/metricstarttimeprocessor/internal/datapointstorage/timeseries_map.go:139]: Same question as non-exponential histograms, wouldn't a new 0 count data point count as a reset?

File: processor/metricstarttimeprocessor/internal/datapointstorage/timeseries_map.go [hunk 4]
```diff
@@ -102,6 +102,82 @@ func (tsm *TimeseriesMap) GC() {
 	tsm.Mark = false
 }
 
+func (tsi *TimeseriesInfo) IsResetHistogram(h pmetric.HistogramDataPoint) bool {
```
Comment (psx95) [inline processor/metricstarttimeprocessor/internal/datapointstorage/timeseries_map.go:105]: Probably add a small comment stating the purpose of this function. I'm assuming it checks whether the HistogramDataPoint being added will cause the timeseries to "reset".
It would also be a great place to put a one-liner about what a reset implies.

File: processor/metricstarttimeprocessor/internal/datapointstorage/timeseries_map.go (hunk 1 above)
Comment (psx95) [reply processor/metricstarttimeprocessor/internal/datapointstorage/timeseries_map.go:106]: IIUC, I think the intention here is to not return false if it is the first point in the timeseries. 

The condition could be `if (h.Count() != 0 && tsi.Histogram.Count() != 0) && h.Count() < tsi.Histogram.Count()`. 
For better readability:

```go
isFirstPoint := h.Count() == 0 && tsi.Histogram.Count() == 0

if isFirstPoint {
  return false;
}

if h.Count() < tsi.Histogram.Count() {
  return true;
}
// rest of the logic ...
```

File: processor/metricstarttimeprocessor/internal/datapointstorage/timeseries_map.go (hunk 3 above)
Comment (ridwanmsharif) [reply processor/metricstarttimeprocessor/internal/datapointstorage/timeseries_map.go]: Thats a good point, the zero comparison isn't needed. As long as the value decrements, it should count as a reset.

**Review by psx95 — APPROVED** [review]

**Review by dehaansa — APPROVED** [review]
LGTM
