### PR TITLE
[processor/deltatocumulative]: bugfix - process all samples

### LINKED ISSUE #31350: deltatocumulative aborts after first sample
### Component(s)

processor/deltatocumulative

## Description

`deltatocumulativeprocessor` only updates the first sample of each stream

## Steps to Reproduce

send a stream with more than two samples

## Expected Result

all samples are converted to cumulative

## Actual Result

only first sample is converted

### Collector version

d4dda619ba45df1df52086797ca8036a01bd5351

### PR DESCRIPTION
**Pull request by tombrk**
**Description:** <Describe what has changed.>

Due to an oversight, the processor stopped after the first sample. It should process all available samples per stream.

**Testing:**
Tests have been added to verify:
- `Samples()` visits all samples
- `Aggregate()` edits all samples

**Issues**
Fixes https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/31350

### CODE REVIEW

File: processor/deltatocumulativeprocessor/internal/streams/data.go [hunk 1]
```diff
@@ -43,7 +43,7 @@ func Aggregate[D data.Point[D]](m metrics.Data[D], aggr Aggregator[D]) error {
 			return true
 		}
 		next.CopyTo(dp)
-		return false
+		return true
```
Comment (ethercrow) [inline processor/deltatocumulativeprocessor/internal/streams/data.go:46]: Since this line was the cause of the bug, I'd be interested in reducing the confusion about whether `true` means `yes, continue iterating` or `yes, stop iterating`.

One approach would be to define constants CONTINUE=true and BREAK=false and using those in the loop bodies. I think readers would have much easier time following the loop logic.

Comment (djaglowski) [reply processor/deltatocumulativeprocessor/internal/streams/data.go:46]: I think a comment should suffice.

Do we also need to flip the other boolean returned?

Comment (RichieSams) [reply processor/deltatocumulativeprocessor/internal/streams/data.go:46]: If / when the golang RangeFunc proposal is merged, then we can use a native `range`, which will remove the confusion. But until then, I agree that a comment should be ok.

**Review by RichieSams — APPROVED** [review]

**Review by RichieSams — APPROVED** [review]

**Comment by RichieSams** [comment]
@djaglowski or @open-telemetry/collector-contrib-approvers  Can someone additionally approve this PR? Github doesn't seem to count my approval, since I was made owner after this PR was created

**Review by djaglowski — APPROVED** [review]
