### PR TITLE
[receiver/filelog] Support preserving whitespace for log entries

### LINKED ISSUE #18242: whitespaces are always trimmed
### Component(s)

receiver/filelog

## Description
whitespaces are always trimmed and potential issue while working with other operators

## Steps to Reproduce

given CRI logs below, the 2nd line ends with a whitespace

```bash
cat -evt /tmp/container.log
2023-02-01T19:59:48.437970951-07:00 stderr F foo$
2023-02-01T19:59:48.437953934-07:00 stderr F $
$
```

## Expected Result

whitespaces are not trimmed, so the regexp for CRI logs would work properly

## Actual Result

got error because the 2nd line(last whitespace) got trimmed

### Collector version

v0.70.0

### Environment information

n/a

### OpenTelemetry Collector configuration

```yaml
receivers:
  filelog:
    include: [ /tmp/container.log ]
    include_file_path: true
    include_file_name: true
    start_at: beginning
    operators:
      - type: regex_parser
        id: parser-crio
        regex: ^(?P<go_timestamp_field>[^ Z]+) (?P<filename>stdout|stderr) (?P<logtag>[^ ]*) (?P<log>.*)$
        timestamp:
          parse_from: attributes.go_timestamp_field
          layout_type: gotime
          layout: 2006-01-02T15:04:05.999999999Z07:00
      - type: move
        id: move_body
        from: attributes.log
        to: body
```

### Log output

```shell
2023-02-02T15:28:04.832+0800    error   helper/transformer.go:110       Failed to process entry {"kind": "receiver", "name": "filelog/1.log", "pipeline": "logs", "operator_id": "parser-crio", "operator_type": "regex_parser", "error": "regex pattern does not match", "action": "send", "entry": {"observed_timestamp":"2023-02-02T15:28:04.832791+08:00","timestamp":"0001-01-01T00:00:00Z","body":"2023-02-01T19:59:48.437953934-07:00 stderr F","attributes":{"log.file.name":"container.log","log.file.path":"/tmp/container.log"},"severity":0,"scope_name":""}}
github.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza/operator/helper.(*TransformerOperator).HandleEntryError
        /Users/yundeng/go/pkg/mod/github.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza@v0.70.0/operator/helper/transformer.go:110
github.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza/operator/helper.(*ParserOperator).ParseWith
        /Users/yundeng/go/pkg/mod/github.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza@v0.70.0/operator/helper/parser.go:151
github.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza/operator/helper.(*ParserOperator).ProcessWithCallback
        /Users/yundeng/go/pkg/mod/github.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza@v0.70.0/operator/helper/parser.go:123
github.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza/operator/helper.(*ParserOperator).ProcessWith
        /Users/yundeng/go/pkg/mod/github.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza@v0.70.0/operator/helper/parser.go:109
github.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza/operator/parser/regex.(*Parser).Process
        /Users/yundeng/go/pkg/mod/github.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza@v0.70.0/operator/parser/regex/regex.go:110
github.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza/operator/helper.(*WriterOperator).Write
        /Users/yundeng/go/pkg/mod/github.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza@v0.70.0/operator/helper/writer.go:64
github.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza/operator/input/file.(*Input).emit
        /Users/yundeng/go/pkg/mod/github.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza@v0.70.0/operator/input/file/file.go:65
github.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza/fileconsumer.(*Reader).ReadToEnd
        /Users/yundeng/go/pkg/mod/github.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza@v0.70.0/fileconsumer/reader.go:87
github.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza/fileconsumer.(*Manager).consume.func1
        /Users/yundeng/go/pkg/mod/github.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza@v0.70.0/fileconsumer/file.go:138
```

### Additional context

https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/pkg/stanza/operator/helper/multiline.go#L201-L206

### PR DESCRIPTION
**Pull request by newly12**
**Description:** <Describe what has changed.>

Fixes #18242

**Link to tracking Issue:** <Issue number if applicable>
#18242

**Testing:** <Describe what testing was performed and which tests were added.>
Added.

**Documentation:** <Describe the documentation added.>
Added

### CODE REVIEW

File: pkg/stanza/fileconsumer/config.go [hunk 1]
```diff
@@ -83,7 +83,7 @@ func (c Config) Build(logger *zap.SugaredLogger, emit EmitFunc) (*Manager, error
 	}
 
 	// Ensure that splitter is buildable
-	factory := newMultilineSplitterFactory(c.Splitter.EncodingConfig, c.Splitter.Flusher, c.Splitter.Multiline)
```
Comment (djaglowski) [inline pkg/stanza/fileconsumer/config.go:86]: This looks like a good change. Would you please open a separate PR for it though?

File: receiver/filelogreceiver/README.md [hunk 2]
```diff
@@ -18,6 +18,7 @@ Tails and parses logs from files.
 | `multiline`                  |                  | A `multiline` configuration block. See below for more details                                                      |
 | `force_flush_period`         | `500ms`          | Time since last read of data from file, after which currently buffered log should be send to pipeline. Takes `time.Duration` (e.g. `10s`, `1m`, or `500ms`) as value. Zero means waiting for new data forever |
 | `encoding`                   | `utf-8`          | The encoding of the file being read. See the list of supported encodings below for available options               |
+| `preserve_whitespace`        | `false`          | Whether to preserve leading and trailing whitespace. |
```
Comment (djaglowski) [inline receiver/filelogreceiver/README.md:21]: Would you please also update the udp and tcp receiver readme's?

File: pkg/stanza/operator/helper/multiline.go [hunk 3]
```diff
@@ -44,12 +44,12 @@ type MultilineConfig struct {
 }
 
 // Build will build a Multiline operator.
-func (c MultilineConfig) Build(enc encoding.Encoding, flushAtEOF bool, force *Flusher, maxLogSize int) (bufio.SplitFunc, error) {
-	return c.getSplitFunc(enc, flushAtEOF, force, maxLogSize)
+func (c MultilineConfig) Build(enc encoding.Encoding, flushAtEOF bool, force *Flusher, maxLogSize int, preserveWhitespace bool) (bufio.SplitFunc, error) {
```
Comment (djaglowski) [inline pkg/stanza/operator/helper/multiline.go:47]: nit: These flags are used in similar ways. Let's keep them together.
```suggestion
func (c MultilineConfig) Build(enc encoding.Encoding, flushAtEOF, preserveWhitespace bool, force *Flusher, maxLogSize int) (bufio.SplitFunc, error) {
```

File: pkg/stanza/operator/helper/multiline.go [hunk 4]
```diff
@@ -96,13 +96,17 @@ func (c MultilineConfig) getSplitFunc(enc encoding.Encoding, flushAtEOF bool, fo
 
 // NewLineStartSplitFunc creates a bufio.SplitFunc that splits an incoming stream into
 // tokens that start with a match to the regex pattern provided
-func NewLineStartSplitFunc(re *regexp.Regexp, flushAtEOF bool) bufio.SplitFunc {
+func NewLineStartSplitFunc(re *regexp.Regexp, flushAtEOF bool, preserveWhitespace bool) bufio.SplitFunc {
```
Comment (djaglowski) [inline pkg/stanza/operator/helper/multiline.go:99]: nit: Might as well condense here too.
```suggestion
func NewLineStartSplitFunc(re *regexp.Regexp, flushAtEOF, preserveWhitespace bool) bufio.SplitFunc {
```

File: pkg/stanza/operator/helper/multiline.go [hunk 5]
```diff
@@ -96,13 +96,17 @@ func (c MultilineConfig) getSplitFunc(enc encoding.Encoding, flushAtEOF bool, fo
...
 		firstLoc := re.FindIndex(data)
 		if firstLoc == nil {
 			// Flush if no more data is expected
 			if len(data) != 0 && atEOF && flushAtEOF {
-				token = trimWhitespaces(data)
+				if preserveWhitespace {
+					token = data
+				} else {
+					token = trimWhitespaces(data)
+				}
```
Comment (djaglowski) [inline pkg/stanza/operator/helper/multiline.go:109]: Since we reuse this pattern a lot, maybe we should set the appropriate func:
```go
type trimFunc func([]byte) []byte

func noTrim(token []byte) []byte {
    return token
}

func NewWhateverSplitFunc(..., preserveWhitespace bool) bufio.SplitFunc {
    trim := trimWhitespaces
    if preserveWhiteSpace {
        trim = noTrim
    }

    ...

    token = trim(token)

    ...
}

```

It's not clear to me that this is better, but what do you think?

**Comment by djaglowski** [comment]
This generally looks good to me, though I think the noted part should be a separate PR. Otherwise, just a few nits and would appreciate a few more tests as you mentioned.

File: pkg/stanza/operator/helper/multiline.go (hunk 5 above)
Comment (newly12) [reply pkg/stanza/operator/helper/multiline.go]: Thanks for the suggestion, I think it's better than if else block, I've update it like this way.

File: receiver/filelogreceiver/README.md (hunk 2 above)
Comment (newly12) [reply receiver/filelogreceiver/README.md:21]: updated readme.

File: pkg/stanza/fileconsumer/config.go (hunk 1 above)
Comment (newly12) [reply pkg/stanza/fileconsumer/config.go:86]: Filed https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/18303

File: pkg/stanza/fileconsumer/splitter_factory.go [hunk 6]
```diff
@@ -25,16 +25,21 @@ type splitterFactory interface {
 }
 
 type multilineSplitterFactory struct {
-	helper.SplitterConfig
+	EncodingConfig     helper.EncodingConfig
+	Flusher            helper.FlusherConfig
+	Multiline          helper.MultilineConfig
+	PreserveWhitespace bool
```
Comment (djaglowski) [inline pkg/stanza/fileconsumer/splitter_factory.go:31]: This PR looks good to me and I'm ok with merging it, but I had a thought that we should decide on first.

Do you think we might eventually have a need to support similar options, like `preserve_leading` and `preserve_trailing`?

If so, this boolean would probably need to be deprecated in favor of either separate booleans or an enumeration. 

I think two booleans could easily be evaluated together to choose the correct trimFunc, and otherwise the processing remains the same.

Should we just do this now to protect against a breaking change later? Up to you.

Comment (newly12) [reply pkg/stanza/fileconsumer/splitter_factory.go:31]: I am not sure if there is need to only trim the leading or trailing whitespace in future, I think maybe having this only option to trim or keep them both for now, and in future if necessary moving the trim functionality to an operator makes more sense?

Comment (djaglowski) [reply pkg/stanza/fileconsumer/splitter_factory.go:31]: Either way sounds fine to me. Typically we try to define boolean parameters so that they default to false, but I do think the names you suggested are better, so seems like a reasonable exception.

Comment (newly12) [reply pkg/stanza/fileconsumer/splitter_factory.go]: It looks like having parameters default to true causing issue in `syslog_input` [config](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/pkg/stanza/operator/input/syslog/syslog.go#L51-L52), which supports embedded `tcp_input` and `udp_input`, any suggestion, maybe we need to stick to false as default values and rename parameters as presevingXxxWhitespaces?

from https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/4251161435/jobs/7393183635#logs

```
--- FAIL: TestUnmarshal (0.01s)
    --- PASS: TestUnmarshal/default (0.00s)
    --- FAIL: TestUnmarshal/tcp (0.00s)
    --- FAIL: TestUnmarshal/udp (0.00s)
```

Comment (djaglowski) [reply pkg/stanza/fileconsumer/splitter_factory.go]: Hmm, seems to be one more reminder why defaulting to false is preferred. :)

> maybe we need to stick to false as default values and rename parameters as presevingXxxWhitespaces

👍 Let's go with this.

**Comment by newly12** [comment]
oops, looks like I accidentally merged & pushed some commits that involved other components and a lot of labels & reviewers were added because of this..

**Review by djaglowski — APPROVED** [review]
Thanks @newly12!
