### PR TITLE
[exporter/azuremonitor] Export metric attributes to Azure Monitor

### LINKED ISSUE #19407: Azure Monitor exporter does not export metric attributes
### Component(s)

exporter/azuremonitor

## Description

The Azure Monitor exporter should export metric attributes as `customDimensions`. Currently it does not export metric attributes (dimensions) to Azure Monitor. 

## Steps to Reproduce

Run the following sample (slight variation of the getting started section [from the OTel .NET docs](https://github.com/open-telemetry/opentelemetry-dotnet/tree/main/docs/metrics/getting-started)):

```csharp
public class Program
{
    private static readonly Meter MyMeter = new("OtelTest", "1.0");
    private static readonly Counter<long> MyFruitCounter = MyMeter.CreateCounter<long>("MyFruitCounter");

    public static void Main()
    {
        using var meterProvider = Sdk.CreateMeterProviderBuilder()
            .AddMeter("OtelTest")
            .AddOtlpExporter()
            .AddConsoleExporter()
            .Build();

        MyFruitCounter.Add(1, new("name", "apple"), new("color", "red"));
    }
}
```

## Expected Result

The console exporter shows the information an expected result could contain:

```
Resource associated with Metric:
    service.name: unknown_service:oteltest

Export MyFruitCounter, Meter: OtelTest/1.0
(2023-03-08T17:09:25.3912339Z, 2023-03-08T17:09:25.7726745Z] color: red name: apple LongSum
Value: 1
```

Note the `color: red name: apple` snippet. Application Insights should contain the same information.

## Actual Result

The information about the attributes cannot be found in Application Insights.

### Collector version

0.72

## Environment
OS: WSL on Windows 11

### OpenTelemetry Collector configuration

```yaml
receivers:
  otlp:
    protocols: 
      grpc:
processors:
exporters:
  logging:
  azuremonitor:
    instrumentation_key: <redacted>
service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: []
      exporters: [logging,azuremonitor]
    metrics:
      receivers: [otlp]
      processors: []
      exporters: [logging,azuremonitor]
    logs:
      receivers: [otlp]
      processors: []
      exporters: [logging,azuremonitor]
```

### Log output

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by bastbu**
**Description:**

As of now, no attributes (dimensions) from the metrics timeseries model are exported to Application Insights. This PR ensures that for all metric points, attributes are present as `customDimensions` in Application Insights.

**Link to tracking Issue:**

Fixes #19407

**Testing:**

Automated tests ensure that metric attributes (dimensions) are exported to the properties on the Application Insights contract.

**Documentation:**

No documentation added.

### CODE REVIEW

File: exporter/azuremonitorexporter/metric_to_envelopes.go [hunk 1]
```diff
@@ -140,9 +143,11 @@ func (m scalarMetric) getTimedDataPoints() []*timedMetricDataPoint {
 		}
 		dataPoint.Count = 1
 		dataPoint.Kind = contracts.Measurement
+		numberDataPoint.Attributes()
```
Comment (atoulme) [inline exporter/azuremonitorexporter/metric_to_envelopes.go:146]:
```suggestion
```

**Comment by atoulme** [comment]
LGTM with one suggestion.

File: exporter/azuremonitorexporter/metric_to_envelopes.go (hunk 1 above)
Comment (bastbu) [reply exporter/azuremonitorexporter/metric_to_envelopes.go]: Good catch! Applied with 20b54fd44f341cdc81b512a36a695ae2cc8af2a8.

**Review by dmitryax — APPROVED** [review]
