### PR TITLE
[chore]: fix linux packaging tests

### LINKED ISSUE #16450: [gh-actions] build-package jobs are failing on the ubuntu-22.04 runners
GitHub actions runner `ubuntu-latest` tag was recently upgraded from Ubuntu 20.04.5 to Ubuntu 22.04.1.

The `build-package` job is failing now. We need to investigate and update it to work on the latest Ubuntu version.

Failing job examples:
- https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/3528442298/jobs/5918829725#logs
- https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/3528442298/jobs/5918829832

### PR DESCRIPTION
**Pull request by cwegener**
Fixes open-telemetry/opentelemetry-collector-contrib#16450

The original packaging tests for the Linux packages (deb, rpm) that were
created in open-telemetry/opentelemetry-collector-contrib#405 used a bit of gnarly work around in order to allow very
limited Systemd functionality to be used in Docker/Containerd

At the time when those packaging tests were written, podman was already
able to run Systemd, but podman was not included in Ubuntu 20.04 yet ...

Now that Podman is available in Ubuntu 22.04, running SystemD in Podman
just works.

Signed-off-by: Christoph Wegener <cwegener@users.noreply.github.com>

### CODE REVIEW

File: internal/buildscripts/packaging/fpm/test.sh [hunk 1]
```diff
@@ -30,47 +30,46 @@ if [[ ! "$pkg_type" =~ ^(deb|rpm)$ ]]; then
...
 
-docker build -t $image_name -f "$SCRIPT_DIR/$pkg_type/Dockerfile.test" "$SCRIPT_DIR"
-docker rm -fv $container_name >/dev/null 2>&1 || true
+podman build -t $image_name -f "$SCRIPT_DIR/$pkg_type/Dockerfile.test" "$SCRIPT_DIR"
+podman rm -fv $container_name >/dev/null 2>&1 || true
 
 # test install
 echo
-$docker_run
+podman run --name $container_name -d $image_name
```
Comment (bryan-aguilar) [inline internal/buildscripts/packaging/fpm/test.sh:42]: In your comment [here](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/16450#issuecomment-1867077311), you said there should be a check to ensure that the `run` does not silently fail. Will podman fail here if the container fails to start or should we still add an additional check?

Comment (cwegener) [reply internal/buildscripts/packaging/fpm/test.sh:42]: Yes, `podman-run` will return a non-zero exit code ala `chroot`, 125 - podman command itself failed, 126 - the contained command failed to run, 127 - the contained command could not be found. (These are the same as `docker-run` should return)

However, the original issue in #16450 is actually the result of the initial `docker-run` to succeeding, but then the container immediately shuts off again due to unknown reasons (apart from the reason that Docker and SystemD have been at loggerheads for years and expecting the two to run smoothly together is not an option at this point in time)

So, going back to my original comment in your question. Yes,  there should be a health-check command running inside the `otelcolcontrib-*-test` images that waits until SystemD has finished starting up all services before returning a 'healthy' state. Then the `test.sh` bash script could wait for the container to transition into a healthy state after `podman-run` and before `podman-cp`, which would cover for that period of uncertainty where the container started, but might have not fully initialized as expected.

I think this should be part of a separate patch though. I'll start working on adding that health check function.

Comment (bryan-aguilar) [reply internal/buildscripts/packaging/fpm/test.sh:42]: Thanks for the thorough answer. If this PR gets merged before the health check function PR is submitted please create a new tracking issue for it.

**Review by bryan-aguilar — APPROVED** [review]

File: internal/buildscripts/packaging/fpm/test.sh (hunk 1 above)
Comment (cwegener) [reply internal/buildscripts/packaging/fpm/test.sh:42]: I created a tracking issue for the health check issue. #30239

**Comment by cwegener** [comment]
@codeboten Pinging you since you currently are assigned to the issue that this patch fixes.

**Review by TylerHelmuth — APPROVED** [review]
I'm no ubuntu or podman expert, but the replacements make sense to me and the CI is passing.  I'd like a few more @open-telemetry/collector-contrib-approvers to review before merging.

**Review by djaglowski — APPROVED** [review]
lgtm

**Comment by cwegener** [comment]
> I'm no ubuntu or podman expert, but the replacements make sense to me and the CI is passing. I'd like a few more @open-telemetry/collector-contrib-approvers to review before merging.

This is a good intro to the Docker vs. SystemD feud. https://lwn.net/Articles/676831/

**Review by codeboten — APPROVED** [review]
Thanks for taking this on @cwegener!
