### PR TITLE
[pkg/stanza/fileconsumer] Fix issue where empty files caused errors

### LINKED ISSUE #22815: Filelog: seek C:\\example\\consul-abc.log: file already closed
### Component(s)

receiver/filelog

## Description
In v78.0, does the filelog receiver continuously log errors, as seen below, if you have an empty log file in the log directory. It did not happen in v77.0.

## Steps to Reproduce
* Use a standard configuration
* Create an empty file in the directory getting monitored, such as consul-2.log.
* Start OtelCol service.

## Expected Result

Errors should not happen and be logged.

## Actual Result
Errors are getting logged.

### Collector version

v78.0

## Environment
Windows 2022 Server

### OpenTelemetry Collector configuration

```yaml
receivers:
  filelog:
    include: [ C:/example//consul-*.log ]
    poll_interval: 10ms
exporters:
  logging:
    verbosity: detailed
service:
  pipelines:
    logs:
      receivers: [ filelog ]
      processors: [ ]
      exporters: [ logging ]
```

### Log output

```shell
2023-05-26T08:38:45.351-0700	info	service/telemetry.go:104	Setting up own telemetry...
2023-05-26T08:38:45.351-0700	info	service/telemetry.go:127	Serving Prometheus metrics	{"address": ":8888", "level": "Basic"}
2023-05-26T08:38:45.352-0700	info	exporter@v0.78.2/exporter.go:275	Development component. May change in the future.	{"kind": "exporter", "data_type": "logs", "name": "logging"}
2023-05-26T08:38:45.352-0700	info	service/service.go:131	Starting otelcol.exe...	{"Version": "0.78.0", "NumCPU": 20}
2023-05-26T08:38:45.352-0700	info	extensions/extensions.go:30	Starting extensions...
2023-05-26T08:38:45.352-0700	info	adapter/receiver.go:45	Starting stanza receiver	{"kind": "receiver", "name": "filelog", "data_type": "logs"}
2023-05-26T08:38:45.352-0700	info	service/service.go:148	Everything is ready. Begin running and processing data.
2023-05-26T08:38:45.365-0700	info	fileconsumer/file.go:194	Started watching file from end. To read preexisting logs, configure the argument 'start_at' to 'beginning'	{"kind": "receiver", "name": "filelog", "data_type": "logs", "component": "fileconsumer", "path": "C:\\example\\consul-abc.log"}
2023-05-26T08:38:45.366-0700	error	fileconsumer/file.go:233	Failed to create reader	{"kind": "receiver", "name": "filelog", "data_type": "logs", "component": "fileconsumer", "error": "stat: GetFileType C:\\example\\consul-abc.log: The handle is invalid."}
github.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza/fileconsumer.(*Manager).makeReader
	github.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza@v0.78.0/fileconsumer/file.go:233
github.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza/fileconsumer.(*Manager).consume
	github.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza@v0.78.0/fileconsumer/file.go:132
github.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza/fileconsumer.(*Manager).poll
	github.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza@v0.78.0/fileconsumer/file.go:125
github.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza/fileconsumer.(*Manager).startPoller.func1
	github.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza@v0.78.0/fileconsumer/file.go:94
2023-05-26T08:38:45.381-0700	error	fileconsumer/reader.go:62	Failed to seek	{"kind": "receiver", "name": "filelog", "data_type": "logs", "component": "fileconsumer", "path": "C:\\example\\consul-abc.log", "error": "seek C:\\example\\consul-abc.log: file already closed"}
github.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza/fileconsumer.(*Reader).ReadToEnd
	github.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza@v0.78.0/fileconsumer/reader.go:62
github.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza/fileconsumer.(*Manager).consume.func1
	github.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza@v0.78.0/fileconsumer/file.go:148
2023-05-26T08:38:46.389-0700	error	fileconsumer/reader.go:62	Failed to seek	{"kind": "receiver", "name": "filelog", "data_type": "logs", "component": "fileconsumer", "path": "C:\\example\\consul-abc.log", "error": "seek C:\\example\\consul-abc.log: file already closed"}
github.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza/fileconsumer.(*Reader).ReadToEnd
	github.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza@v0.78.0/fileconsumer/reader.go:62
github.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza/fileconsumer.(*Manager).consume.func1
	github.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza@v0.78.0/fileconsumer/file.go:148
2023-05-26T08:38:47.397-0700	error	fileconsumer/reader.go:62	Failed to seek	{"kind": "receiver", "name": "filelog", "data_type": "logs", "component": "fileconsumer", "path": "C:\\example\\consul-abc.log", "error": "seek C:\\example\\consul-abc.log: file already closed"}
github.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza/fileconsumer.(*Reader).ReadToEnd
	github.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza@v0.78.0/fileconsumer/reader.go:62
github.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza/fileconsumer.(*Manager).consume.func1
	github.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza@v0.78.0/fileconsumer/file.go:148
2023-05-26T08:38:48.406-0700	error	fileconsumer/reader.go:62	Failed to seek	{"kind": "receiver", "name": "filelog", "data_type": "logs", "component": "fileconsumer", "path": "C:\\example\\consul-abc.log", "error": "seek C:\\example\\consul-abc.log: file already closed"}
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by djaglowski**
Resolves #22815

### CODE REVIEW

**Review by crobert-1 — APPROVED** [review]
Looks good, tested locally and the issue has been resolved. Thanks for fixing!

File: pkg/stanza/fileconsumer/file.go [hunk 1]
```diff
@@ -211,8 +211,8 @@ func (m *Manager) makeReader(path string) *Reader {
 		// Empty file, don't read it until we can compare its fingerprint
 		if err = file.Close(); err != nil {
 			m.Errorf("problem closing file %s", file.Name())
-			return nil
 		}
+		return nil
```
Comment (codeboten) [inline pkg/stanza/fileconsumer/file.go:215]: is there a test that would prevent regressions here?

Comment (djaglowski) [reply pkg/stanza/fileconsumer/file.go:215]: I don't know a reasonable way to test this without a refactoring quite a bit, which is something I'd very much like to do as soon as possible.

**Review by dmitryax — APPROVED** [review]

File: pkg/stanza/fileconsumer/file.go (hunk 1 above)
Comment (djaglowski) [reply pkg/stanza/fileconsumer/file.go:215]: @codeboten, are you ok with merging this? Hardening this package is an ongoing priority for me but this is a fairly annoying bug and I think the necessary changes to make the fix testable would cause it to persist into the next release.

Comment (dmitryax) [reply pkg/stanza/fileconsumer/file.go:215]: I'd say we should merge this given that it's an obvious bug

**Review by atoulme — APPROVED** [review]

**Comment by djaglowski** [comment]
I think we should merge.

File: pkg/stanza/fileconsumer/file.go (hunk 1 above)
Comment (atoulme) [reply pkg/stanza/fileconsumer/file.go:215]: @djaglowski happy to file a bug to follow up on refactoring and testing this further if that helps, unless there's a ticket for this already.

Comment (djaglowski) [reply pkg/stanza/fileconsumer/file.go:215]: Good idea @atoulme. I've created https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/23069

**Review by codeboten — APPROVED** [review]
