### PR TITLE
Fix issue with LookbackTime calculation

### LINKED ISSUE #43943: The calculation of LookbackTime default value is flawed
### Component(s)

receiver/receivercreator, receiver/sqlserver

### Describe the issue you're reporting

The default value of `lookbackTime` in TopQueryCollection config is always calculated as `2` * `default value of CollectionInterval`.

This logic is flawed because the default value will always stay at 20 (2*10=20) even if the user provides a collection interval of `60` seconds.

The expected default value for lookbackTime in this case should be `120` (2*60=120)

### Tip

<sub>[React](https://github.blog/news-insights/product-news/add-reactions-to-pull-requests-issues-and-comments/) with 👍 to help prioritize this issue. Please use comments to provide useful context, avoiding `+1` or `me too`, to help us triage it. Learn more [here](https://opentelemetry.io/community/end-user/issue-participation/).</sub>

### PR DESCRIPTION
**Pull request by sv-splunk**
#### Description
The default value of `lookbackTime` in TopQueryCollection config is always calculated as `2` * `default value of CollectionInterval`.

This logic is flawed because the default value will always stay at 20 (2*10=20) even if the user provides a collection interval of `60` seconds.

The expected default value for lookbackTime in this case should be `120` (2*60=120).

The fix is to calculate lookbackTime based on the final value of CollectionInterval.

#### Link to tracking issue
Fixes https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/43943

#### Testing
Unit tests updated.

### CODE REVIEW

File: receiver/sqlserverreceiver/factory_others_test.go [hunk 1]
```diff
@@ -95,6 +95,8 @@ func TestFactoryOtherOS(t *testing.T) {
 				require.NotEmpty(t, scrapers)
 
 				sqlScrapers = setupSQLServerLogsScrapers(params, cfg)
+				require.Equal(t, 2*sqlScrapers[0].config.ControllerConfig.CollectionInterval.Seconds(), sqlScrapers[0].config.LookbackTime.Seconds(),
```
Comment (constanca-m) [inline receiver/sqlserverreceiver/factory_others_test.go]: Add the tests for the config in the `config_test`, it is easier to make sure it works there. [See](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/f60a7a4b411d8252d340edfaa48703abf61b312d/receiver/sqlserverreceiver/config_test.go#L137).

Comment (sv-splunk) [reply receiver/sqlserverreceiver/factory_others_test.go]: @constanca-m Thanks for the review, however it was still a draft-PR, just moved to "ready for review" now.

I have moved logic around a bit, also the tests. Please check.

File: receiver/sqlserverreceiver/config.go [hunk 2]
```diff
@@ -103,3 +103,10 @@ func directDBConnectionEnabled(config *Config) (bool, error) {
 	// It is a valid direct connection configuration
 	return true, nil
 }
+
+func (cfg *Config) EffectiveLookbackTime() time.Duration {
+	if cfg.LookbackTime <= 0 {
```
Comment (dmitryax) [inline receiver/sqlserverreceiver/config.go]: Handling negative values here is confusing. They should be rejected in config Validate

File: receiver/sqlserverreceiver/factory.go [hunk 3]
```diff
@@ -56,7 +56,6 @@ func createDefaultConfig() component.Config {
 			MaxRowsPerQuery: 100,
 		},
 		TopQueryCollection: TopQueryCollection{
-			LookbackTime:        2 * cfg.CollectionInterval / time.Second,
```
Comment (XSAM) [inline receiver/sqlserverreceiver/factory.go:59]: I am not sure why method `EffectiveLookbackTime` is necessary.

Could we simply

- Update this line to `LookbackTime:        2 * cfg.CollectionInterval` for the fix.
- Update `Validate` on `config.go` to avoid negative value.
- Add a test to prevent regression

File: receiver/sqlserverreceiver/config.go (hunk 2 above)
Comment (sv-splunk) [reply receiver/sqlserverreceiver/config.go]: @dmitryax Updated to validate negative values and removed the same from above function.

File: receiver/sqlserverreceiver/factory.go (hunk 3 above)
Comment (sv-splunk) [reply receiver/sqlserverreceiver/factory.go:59]: @XSAM thats the whole point of this PR. When `LookbackTime:        2 * cfg.CollectionInterval` is set, the default value of `LookbackTime` become based on only the default value of `CollectionInterval`.  Default value of `LookbackTime` wont change if user provides a value for `CollectionInterval`.

**Review by dmitryax — APPROVED** [review]
