### PR TITLE
[tailsamplingprocessor] Replace misleading policy latency metric

### LINKED ISSUE #38502: [tailsamplingprocessor] Decision Timer Latency Metric is misleading
### Component(s)

processor/tailsampling

## Description
After https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/37722, I realized there is another issue with the decision timer latency metric. 

Basically, it currently measures a latency from starting policy evaluation until just after each trace is evaluated. This isn't super useful, consider the following scenario:

-  A batch with 10 traces, each taking 1ms to evaluate all policies

## Steps to Reproduce

Run the tsp, observe the `otelcol_processor_tail_sampling_sampling_decision_timer_latency` metric.

## Expected Result

I would expect this metric to report one of two things, either:

1. The total time to evaluate a batch (in this case 10ms)
2. The time to evaluate each trace (in this case 1ms)

IMO (1) is more useful, since it's a direct indication of whether the tsp is at risk of falling behind on processing traces.

## Actual Result
 
- The histogram will record times 1ms, 2ms, 3ms, etc up to 10ms. 
- In the end the p99 will be 9ms, p50 will be ~5ms, and average will be 5ms.

I considered opening a PR to change the implementation to (1) above, but figured I would open this issue first to make sure I'm not missing an important use-case for (2). Happy to submit the PR though if not!

### Collector version

N/A

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

### OpenTelemetry Collector configuration

```yaml

```

### Log output

```shell

```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Logiraptor**
#### Description

This PR removes the metric otelcol_processor_tail_sampling_sampling_decision_latency. It adds a pair of metrics as replacement called
`processor_tail_sampling_sampling_policy_cpu_time` and `processor_tail_sampling_sampling_policy_executions`. It is an implementation of the feedback received in https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/42620

Originally reported in https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/38502, this metric does not measure the latency of a particular policy. Instead, it measures the latency since policy evaluation began which is mostly not a useful signal.

To make matters worse, profiling shows that recording this metric accounts for >20% of cpu time spent evaluating policies. Since the tailsamplingprocessor is bottlenecked on the single threaded decision loop, this 20% is much better spent on making decisions rather than measuring a misleading metric.

As a replacement, I've added a metric to track total time spent on each policy as well as count total executions. This allows slow policies to still be identified by checking their total or average execution time without the heavy CPU / gc pressure / synchronization cost of recording a histogram in the inner loop.

#### Link to tracking issue
Fixes #38502 - closed on accident, and I am not otel enough to reopen it

### CODE REVIEW

**Review by portertech — APPROVED** [review]

**Review by carsonip — APPROVED** [review]
lgtm, thanks. One suggestion on naming: will `otelcol_processor_tail_sampling_sampling_policy_cpu_time_sum` and `otelcol_processor_tail_sampling_sampling_policy_cpu_time_count` be clearer to indicate that these 2 metrics are a pair? Or does it not follow the naming convention?

File: processor/tailsamplingprocessor/processor.go [hunk 1]
```diff
@@ -295,6 +295,8 @@ type policyDecisionMetrics struct {
 type policyMetrics struct {
 	idNotFoundOnMapCount, evaluateErrorCount, decisionSampled, decisionNotSampled, decisionDropped int64
 	tracesSampledByPolicyDecision                                                                  []map[samplingpolicy.Decision]policyDecisionMetrics
+	timeSpentExecutingPolicies                                                                     []time.Duration
+	policyExecutions                                                                               []int64
```
Comment (pjanotti) [inline processor/tailsamplingprocessor/processor.go]: nit: what about one slice with a small struct instead of 2 slices?

File: processor/tailsamplingprocessor/processor.go [hunk 2]
```diff
@@ -304,6 +306,8 @@ func newPolicyMetrics(numPolicies int) *policyMetrics {
 	}
 	return &policyMetrics{
 		tracesSampledByPolicyDecision: tracesSampledByPolicyDecision,
+		timeSpentExecutingPolicies:    make([]time.Duration, numPolicies),
```
Comment (pjanotti) [inline processor/tailsamplingprocessor/processor.go]: nit: the name is a bit misleading, something like `cumulativeExecutionTime` or similar seems better

Comment (carsonip) [reply processor/tailsamplingprocessor/processor.go]: If I'm understanding correctly it is only cumulative within a tick, not across ticks.

Comment (pjanotti) [reply processor/tailsamplingprocessor/processor.go]: That's why naming is hard :) the main thing that sounded a bit misleading to me is more about the `Policies` at the end that seems to indicate something across all policies, the next field is even `policyExecutions`. Anyway, treat it as a "nit" suggestion.

**Review by pjanotti — APPROVED** [review]
