### PR TITLE
[testbed] Allow ballast memory test to remeasure after GC

### LINKED ISSUE #6927: Flaky test - TestBallastMemory/ballast-size-100
TestBallastMemory/ballast-size-100 is failing intermittently, like here: https://github.com/open-telemetry/opentelemetry-collector-contrib/runs/4594999189?check_suite_focus=true

```
        	Error Trace:	e2e_test.go:123
        	Error:      	"78" is not less than or equal to "77"
        	Test:       	TestBallastMemory/ballast-size-100
        	Messages:   	[The RSS memory usage (78) is >10% higher than the limit (70).]
```

### PR DESCRIPTION
**Pull request by djaglowski**
Resolves #6927

### CODE REVIEW

**Comment by djaglowski** [comment]
I've rerun the affected test several times and have not observed a failure. It's not clear that the condition has been hit yet though. Will rerun a few more times, but I think this can be reviewed.

File: testbed/tests/e2e_test.go [hunk 1]
```diff
@@ -119,6 +119,23 @@ func TestBallastMemory(t *testing.T) {
...
+			if rss > test.ballastSize && float32(rss) <= garbageCollectionMax {
+				t.Log("Possible garbage collection under way. Remeasuring RSS.")
+				tc.WaitForN(func() bool {
+					rss, vms, _ = tc.AgentMemoryInfo()
+					return float32(rss) <= lenientMax
+				}, time.Second, fmt.Sprintf("The RSS memory usage (%d) is >10%% higher than the limit (%d).", rss, test.maxRSS))
+
+				// Now wait a moment and take one more measurement, to ensure we didn't just observe a momentary dip
+				time.Sleep(100 * time.Millisecond)
+				rss, vms, _ = tc.AgentMemoryInfo()
```
Comment (TylerHelmuth) [inline testbed/tests/e2e_test.go:136]: Isn't this a slippery slope?  What if garbage collection was happening so our second check was correct when the memory dropped but then during this check there is another momentary spike?

Comment (djaglowski) [reply testbed/tests/e2e_test.go]: I removed the extra sample and pull the final check into an `else`, so that we don't have an `if true then true` check in the case where we wait for gc to finish.

**Review by TylerHelmuth — APPROVED** [review]
