### PR TITLE
[exporter/datadog] Fix host alias field in metadata payload & fix GCP host alias.

### LINKED ISSUE #9122: [exporter/datadog] Possibly incorrect json identifier for host aliases
**Describe the bug**
The json name for host aliases is called `host-aliases` in the datadog exporter but its called `host_aliases` in the datadog agent. Could it be that the name is wrong? I also have issues getting host aliases into datadog via the otel collector.

**Steps to reproduce**
try to export host infos with host aliases

**What did you expect to see?**
host aliases in datadog

**What did you see instead?**
an empty list

**What version did you use?**
0.48.0

**Additional context**
this issue is related to the datadog exporter

### PR DESCRIPTION
**Pull request by KSerrania**
**Description:**

Fixes the metadata payload field name used to send host aliases to the Datadog backend (the correct field is `host_aliases`, not `host-aliases`, see this [datadog-agent code](https://github.com/DataDog/datadog-agent/blob/5a2ce199bc5811ff7b7adefe3b495b934a70fe03/pkg/metadata/host/payload.go#L27) for comparison).

Also fixes the GCP host alias resolution to match what is done in the [datadog-agent](https://github.com/DataDog/datadog-agent/blob/af9d7fe04565107f199c60e01f718e9407fb758f/pkg/util/cloudproviders/gce/gce.go#L96-L115). Since we weren't sending this host alias correctly at all before, we consider this not to be a breaking change.

**Link to tracking Issue:** #9122

**Testing:** Amended the unit test for the GCP host alias. Manually checked that host aliases are now properly seen in the Datadog backend when the `Meta.HostAliases` field is not empty.

**Documentation:** n/a

### CODE REVIEW

File: exporter/datadogexporter/internal/model/attributes/gcp/gcp.go [hunk 1]
```diff
@@ -43,9 +43,10 @@ func HostInfoFromAttributes(attrs pcommon.Map) (hostInfo *HostInfo) {
 	hostInfo = &HostInfo{}
 
 	if hostID, ok := attrs.Get(conventions.AttributeHostID); ok {
-		// Add host id as a host alias to preserve backwards compatibility
-		// The Datadog Agent does not do this
-		hostInfo.HostAliases = append(hostInfo.HostAliases, hostID.StringVal())
+		if cloudAccount, ok := attrs.Get(conventions.AttributeCloudAccountID); ok {
+			alias := fmt.Sprintf("%s.%s", hostID.StringVal(), cloudAccount.StringVal())
+			hostInfo.HostAliases = append(hostInfo.HostAliases, alias)
+		}
```
Comment (mx-psi) [inline exporter/datadogexporter/internal/model/attributes/gcp/gcp.go:49]: Note for future git history spelunkers: this is not a breaking change since we were not sending host aliases at all to the backend.

**Review by mx-psi — APPROVED** [review]

**Comment by mx-psi** [comment]
🤔 Could you do an empty commit? Github Actions is not running for some reason on your last commit

**Comment by mx-psi** [comment]
```
2022-05-05T09:28:13.2773192Z === RUN   TestMetadataFromAttributes
2022-05-05T09:28:13.2773553Z     metadata_test.go:129: 
2022-05-05T09:28:13.2773968Z         	Error Trace:	metadata_test.go:129
2022-05-05T09:28:13.2774343Z         	Error:      	elements differ
2022-05-05T09:28:13.2774669Z         	            	
2022-05-05T09:28:13.2775136Z         	            	extra elements in list A:
2022-05-05T09:28:13.2775792Z         	            	([]interface {}) (len=1) {
2022-05-05T09:28:13.2776519Z         	            	 (string) (len=18) "project:project-id"
2022-05-05T09:28:13.2776890Z         	            	}
2022-05-05T09:28:13.2777202Z         	            	
2022-05-05T09:28:13.2871981Z         	            	
2022-05-05T09:28:13.2872628Z         	            	listA:
2022-05-05T09:28:13.2873129Z         	            	([]string) (len=4) {
2022-05-05T09:28:13.2874196Z         	            	 (string) (len=19) "instance-id:host-id",
2022-05-05T09:28:13.2874941Z         	            	 (string) (len=15) "zone:cloud-zone",
2022-05-05T09:28:13.2875924Z         	            	 (string) (len=23) "instance-type:host-type",
2022-05-05T09:28:13.2876715Z         	            	 (string) (len=18) "project:project-id"
2022-05-05T09:28:13.2877109Z         	            	}
2022-05-05T09:28:13.2877472Z         	            	
2022-05-05T09:28:13.2877812Z         	            	
2022-05-05T09:28:13.2878209Z         	            	listB:
2022-05-05T09:28:13.2878848Z         	            	([]string) (len=3) {
2022-05-05T09:28:13.2879598Z         	            	 (string) (len=19) "instance-id:host-id",
2022-05-05T09:28:13.2880331Z         	            	 (string) (len=15) "zone:cloud-zone",
2022-05-05T09:28:13.2881107Z         	            	 (string) (len=23) "instance-type:host-type"
2022-05-05T09:28:13.2881493Z         	            	}
2022-05-05T09:28:13.2881920Z         	Test:       	TestMetadataFromAttributes
2022-05-05T09:28:13.2882372Z --- FAIL: TestMetadataFromAttributes (0.00s)
```

**Comment by mx-psi** [comment]
ditto as with the other PR: looks mergeable to me if you mark as ready to review

**Review by mx-psi — APPROVED** [review]
