### PR TITLE
[elasticsearchexporter] ignore expected errors

### LINKED ISSUE #38598: [exporter/elasticsearch] Don't log version conflict errors if these are expected
### Component(s)

exporter/elasticsearch

## Description
For profiling, version conflicts when writing documents into k/v indices are expected and should be ignored. Currently, these are logged as errors. To not clutter logs, these errors from Es should not even be logged in debug mode.

## Steps to Reproduce
Build the collector with elasticsearchexporter and go.opentelemetry.io/ebpf-profiler as receiver.
Configure to export to an Elasticsearch instance and run the collector.
## Expected Result
None

## Actual Result
Example output:
```
2025-03-13T11:36:55.699+0100    error   elasticsearchexporter/bulkindexer.go:359        failed to index document        {"otelcol.component.id": "elasticsearch", "otelcol.component.kind": "Exporter", "otelcol.signal": "profiles", "index": ".profiling-stackframes-v001-000001", "error.type": "version_conflict_engine_exception", "error.reason": "[zmx2UHDFWwhtW92j5VhG8gAAAAAAAAAB]: version conflict, document already exists (current version [1])"}
```

### Collector version

v0.121.0

## Environment
Linux

### OpenTelemetry Collector configuration

```yaml
dist:
  name: profiling-collector
  description: Profiling OTel Collector distribution
  output_path: ./collector


processors:
  - gomod:
      github.com/open-telemetry/opentelemetry-collector-contrib/processor/resourcedetectionprocessor v0.121.0

exporters:
  - gomod:
      go.opentelemetry.io/collector/exporter/debugexporter v0.121.0
  - gomod:
      go.opentelemetry.io/collector/exporter/otlpexporter v0.121.0
  - gomod:
      github.com/open-telemetry/opentelemetry-collector-contrib/exporter/elasticsearchexporter v0.121.0
    import: github.com/open-telemetry/opentelemetry-collector-contrib/exporter/elasticsearchexporter
    name: elasticsearchexporter
    path: ../../open-telemetry/opentelemetry-collector-contrib/exporter/elasticsearchexporter


receivers:
  - gomod: go.opentelemetry.io/ebpf-profiler v0.0.1
    import: go.opentelemetry.io/ebpf-profiler/collector
    name: profilesreceiver
    path: ../../open-telemetry/opentelemetry-ebpf-profiler
  - gomod:
      go.opentelemetry.io/collector/receiver/otlpreceiver v0.121.0

replaces:
  - github.com/openshift/api v3.9.0+incompatible => github.com/openshift/api v0.0.0-20180801171038-322a19404e37
```

### Log output

```shell

```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by florianl**
#### Description
When writing profiling data into Elasticsearch, some errors are expected. So we do not want to flood logging with these errors.

#### Link to tracking issue
Fixes https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/38598

### CODE REVIEW

**Review by carsonip — COMMENTED** [review]
I understand that we don't want the error log. What about metrics? Should we treat them as successful, or failure? With your change the documents are neither successful nor failing in terms of metrics

**Comment by florianl** [comment]
> Should we treat them as successful, or failure?

It depends on how you see it. The write to the database failed. But the entry in the database exists and would imply a success. Therefore I did not make changes to telemetry and would also not expect to see them in this scope.

**Review by carsonip — COMMENTED** [review]
> Therefore I did not make changes to telemetry and would also not expect to see them in this scope.

I think your change does have an impact on telemetry. The way `continue` shortcircuits, telemetry is now skipped. If you move the change to a few lines lower, then yes there is no change to telemetry.

**Comment by florianl** [comment]
@carsonip moved the `continue` after `tb.ElasticsearchDocsProcessed.Add(...)`.

**Review by carsonip — APPROVED** [review]

File: exporter/elasticsearchexporter/bulkindexer.go [hunk 1]
```diff
@@ -518,6 +518,15 @@ func flushBulkIndexer(
 			)),
 		)
 
+		if resp.Error.Type == "version_conflict_engine_exception" &&
```
Comment (MovieStoreGuy) [inline exporter/elasticsearchexporter/bulkindexer.go:521]: Please also add a test around this.

**Review by MovieStoreGuy — COMMENTED** [review]
Please make sure that tests are not skipped over, it helps when performing upgrades.

File: exporter/elasticsearchexporter/bulkindexer.go (hunk 1 above)
Comment (florianl) [reply exporter/elasticsearchexporter/bulkindexer.go:521]: Added a test with https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/42071/commits/21a5546e8f785814e9d6202dbc1b08ede4a6ee9e.

**Review by carsonip — APPROVED** [review]

**Review by andrzej-stencel — APPROVED** [review]
