### PR TITLE
fix(azuremonitorreceiver): Azure Monitor receiver should not produce gaps in data points for PT1M time grains

### LINKED ISSUE #37337: Azure Monitor receiver doesn't honor time grain
### Component(s)

receiver/azuremonitor

## Description
Azure monitor receiver has gaps in metrics when collecting PT1M metrics with 1 minute interval. It results in data points lost.

## Steps to Reproduce
Configure Azure Monitor receiver to fetch any Azure metric with PT1M time grain

## Expected Result
Metrics received for every minute without gaps: for 60 minutes receive 60 data points.

## Actual Result
Some metrics are lost, for 60 minutes interval it collects roufly 40..45 data points.

### Collector version

v0.117.0

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

### OpenTelemetry Collector configuration

```yaml
exporters:
  debug:
    verbosity: detailed

processors:
  filter/azuremonitor/eventhub:
    error_mode: ignore
    metrics:
      metric:
        - 'not name == "azure_incomingmessages_total"'

receivers:
  azuremonitor/eventhub:
    subscription_id: "${env:AM_SUBSCRIPTION_ID}"
    tenant_id: "${env:AM_TENANT_ID}"
    client_id: "${env:AM_SP_CLIENT_ID}"
    client_secret: "${env:AM_SP_CLIENT_SECRET}"
    collection_interval: 1m
    initial_delay: 1s
    resource_groups:
      - ${env:AM_RESOURCE_GROUP}
    services:
      - microsoft.eventhub/namespaces

service:
  pipelines:
    metrics:
      exporters:
      - debug
      processors:
      - filter/azuremonitor/eventhub
      receivers:
      - azuremonitor/eventhub
```

### Log output

```shell

```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by an-mmx**
#### Description
The current implementation of tracking for the last metrics fetch is highly sensitive to time, relying on `time.Now()`. This sensitivity causes the loss of data points due to jitter in 1-minute intervals. I recommend a change request to implement a more robust comparison with the last minute of metrics fetch.

#### Link to tracking issue
Fixes https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/37337

#### Testing
A new coverage introduced in unit test

#### Documentation
No documentation added

### CODE REVIEW

**Comment by celian-garcia** [comment]
That's very interesting. Did you observe the same thing with other timegrain? 
I feel like your fix would fix only the PT1M but not others. 

We have a fork (using batch metric API instead of metric API in order to resolve a problem of rate limitation, anyway..) and in that fork we did something different. We remove 4 times the duration of the timegrain. 
So for a PT1M, we take 4 * 60 = 240 seconds in the past. This to ensure that we'll receive some data as if we take only 60sec back, we sometimes have nothing, and nothing, and nothing. Of course it's not the exactly the same API but maybe the problem is the same. 

So in the end, we're very interested in having some figures with before/after. And I think I will try your implementation with our fork.

**Comment by an-mmx** [comment]
> .. Did you observe the same thing with other timegrain? I feel like your fix would fix only the PT1M but not others.

Following the scrapper logic and our changes, it should work well. The root cause of the issue was in a timedrift caused by various factors (like requests duration and processing time) and the way it was compared. This change mitigates impact of the timedrift.
Could you please share your concerns regarding other timegrains?


> We have a fork (using batch metric API instead of metric API in order to resolve a problem of rate limitation, anyway..) and in that fork we did something different. We remove 4 times the duration of the timegrain. So for a PT1M, we take 4 * 60 = 240 seconds in the past. This to ensure that we'll receive some data as if we take only 60sec back, we sometimes have nothing, and nothing, and nothing. Of course it's not the exactly the same API but maybe the problem is the same.

Have you checked for these gaps in Azure App Insights? Azure doesn't store null-value data points, it might be the case: https://learn.microsoft.com/en-us/azure/azure-monitor/essentials/metrics-troubleshoot#chart-shows-dashed-line


> So in the end, we're very interested in having some figures with before/after. And I think I will try your implementation with our fork.

Sure.
We collect Azure EventHub IncomingMessages metric. Here you can see a line, representing a count of data points per 1 hour collected before the fix, filtered by a single unique dimension. We can observe that we collect less than 60 datapoints per hour, and this isn't something we expect.
Screenshot 2025-02-10 at 16 23 04

The next screenshot have taken after the fix. It is build on the same query. We can observe that we have reached 60 datapoints per hour. We can also observe some "spikes". These spikes is a result of otel-collector restarts. However, it isn't a problem for us. 
Screenshot 2025-02-10 at 16 23 17

**Comment by celian-garcia** [comment]
Well ok, I checked twice and our fork using getBatch metrics API is completely different in terms of interface. We make a batchRequest giving start and end time and the classic metrics API doesn't even have this notion actually. 
This is just to take the metrics at a T time. So what you did is perfect and seems indeed to largely mitigates the issue. 

LGTM in the end, I would like to approve, but I'm owner of this code since only a week and I'm not sure how can I approve it :D

**Comment by an-mmx** [comment]
Usch, I've rebased w/ main and lots of test got failed :/

**Review by celian-garcia — APPROVED** [review]
Hoping that it has some weight here, I'm approving these changes. 
🙏 
I've been assign to CODEOWNERS after the PR has been created :)

**Comment by crobert-1** [comment]
> Hoping that it has some weight here, I'm approving these changes.

@celian-garcia: You're a code owner now, so it definitely counts. Really appreciate your input here 🙂

File: receiver/azuremonitorreceiver/scraper.go [hunk 1]
```diff
@@ -57,6 +57,7 @@ const (
 	attributeResourceType  = "type"
 	metadataPrefix         = "metadata_"
 	tagPrefix              = "tags_"
+	truncateTimeGrain      = time.Minute
```
Comment (crobert-1) [inline receiver/azuremonitorreceiver/scraper.go:60]: Asking out of ignorance: Does this logic and bug fix still work if the receiver's `collection_interval` is set to some non-default value? (Something other than 1 minute)

Comment (an-mmx) [reply receiver/azuremonitorreceiver/scraper.go:60]: It works well with a `collection_interval` of less than 1 minute. In our environment, we use `collection_interval: 30s` to mitigate the risk of losing metrics upon re-deployment. Currently, we collect metrics with a PT1M time grain and it works as expected. We have also tested with PT1H metrics and encountered no issues.

Comment (an-mmx) [reply receiver/azuremonitorreceiver/scraper.go:60]: Yeah, btw, also this case is covered in unit test.

File: .chloggen/fix_azure-monitor-receiver-time-grain.yaml [hunk 2]
```diff
@@ -0,0 +1,28 @@
+# Use this changelog template to create an entry for release notes.
+
+# One of 'breaking', 'deprecation', 'new_component', 'enhancement', 'bug_fix'
+change_type: bug_fix
+
+# The name of the component, or a single word describing the area of concern, (e.g. filelogreceiver)
+component: azuremonitorreceiver
+
+# A brief description of the change.  Surround your text with quotes ("") if it needs to start with a backtick (`).
+note: "Azure Monitor receiver doesn't honor time grain"
```
Comment (crobert-1) [inline .chloggen/fix_azure-monitor-receiver-time-grain.yaml:10]:
```suggestion
note: "Fix bug where the time grain wasn't honored"
```
Nit: Just want to make it clear this bug is fixed now.

**Review by crobert-1 — APPROVED** [review]
