### PR TITLE
Use target and metadata from context

### LINKED ISSUE #5757: Prometheus Receiver - honor_labels set to true doesnt work with federation
**Describe the bug**
When using federation, honor_labels set to true doesnt work since the source prometheus server's job name is not found in the list of targets in the destination prometheus config

**Steps to reproduce**
Using federation, try to scrape metrics from another prometheus server with honor_labels set to true. 

**What did you expect to see?**
Metrics collected correctly by the otel collector with the labels from the source prometheus server honored

**What did you see instead?**
An error that says "job or instance cannot be found from labels"

**What version did you use?**
Version: v0.27.0

**What config did you use?**
Config: (e.g. the yaml config file)

    global:
      evaluation_interval: 5s
      scrape_interval: 5s
    scrape_configs:
    - job_name: federate
      honor_labels: true
      metrics_path: '/federate'
      params:
        'match[]': ['job:my_job_name']
      static_configs:
        - targets:
          - 'prometheus-prometheus-oper-prometheus.monitoring:9090'

**Environment**
OS: Ubuntu 20.04
Compiler(if manually compiled): go 1.14

**Additional context**
This seems to be related to the way targets are looked up based on job/instance labels. Related to #5663

### PR DESCRIPTION
**Pull request by gouthamve**
**Description:** This uses the target and metadata info passed in through context instead of looking them up via `instance` and `job` labels.

**Link to tracking Issue:** This fixes #5757 and #5663

**Testing:** I've done a `Prometheus --> OTel Collector --> Another Prometheus` with `honor_labels: true` and Prometheus federation. It used to fail before but now it works!

**TODO**:
- [x] Get https://github.com/prometheus/prometheus/pull/10473 merged
- [x] Fix tests / add new ones

### CODE REVIEW

**Comment by gouthamve** [comment]
I'll resolve the conflicts once upstream PR is merged.

File: receiver/prometheusreceiver/internal/otlp_transaction_test.go [hunk 1]
```diff
@@ -14,125 +14,125 @@
 
 package internal
 
-import (
-	"context"
-	"testing"
-	"time"
+// import (
```
Comment (dashpole) [inline receiver/prometheusreceiver/internal/otlp_transaction_test.go:17]: I assume you are still in the process of fixing these tests?

**Comment by dashpole** [comment]
Looks good once the prerequisites are complete

File: receiver/prometheusreceiver/internal/otlp_transaction_test.go [hunk 2]
```diff
@@ -14,125 +14,125 @@
...
-		},
-	)
-	// processedLabels contain label values after processing (e.g. relabeling)
-	processedLabels := labels.New(
-		labels.Label{
-			Name:  model.InstanceLabel,
-			Value: "localhost:8080",
-		},
-	)
+// func Test_transaction_pdata(t *testing.T) {
```
Comment (pmm-sumo) [inline receiver/prometheusreceiver/internal/otlp_transaction_test.go:31]: Why this (and other) tests are commented?

File: receiver/prometheusreceiver/metrics_receiver.go [hunk 3]
```diff
@@ -90,7 +90,6 @@ func (r *pReceiver) Start(_ context.Context, host component.Host) error {
 		r.cfg.PrometheusConfig.GlobalConfig.ExternalLabels,
 	)
 	r.scrapeManager = scrape.NewManager(&scrape.Options{}, logger, r.ocaStore)
-	r.ocaStore.SetScrapeManager(r.scrapeManager)
```
Comment (pmm-sumo) [inline receiver/prometheusreceiver/metrics_receiver.go:93]: I think ScrapeManager capability has been removed from prometheusreceiver. Basing on the comments in other section, it's needed for "OCAStore". I'm not sure if the latter is still relevant but wanted to make sure we're not removing some part of functionality

**Comment by pmm-sumo** [comment]
I think the rebase resulted in a bunch of `go.mod`/`go.sum` modified in components unrelated to changes

File: receiver/prometheusreceiver/internal/instance_relabel_end_to_end_test.go [hunk 4]
```diff
@@ -0,0 +1,224 @@
...
+	"go.opentelemetry.io/collector/processor/batchprocessor"
+	"go.opentelemetry.io/collector/service"
+	"go.uber.org/zap"
+	"go.uber.org/zap/zapcore"
+
+	"github.com/open-telemetry/opentelemetry-collector-contrib/exporter/prometheusremotewriteexporter"
+	"github.com/open-telemetry/opentelemetry-collector-contrib/receiver/prometheusreceiver"
+)
+
+func TestJobInstanceRelabelEndToEnd(t *testing.T) {
```
Comment (Aneurysm9) [inline receiver/prometheusreceiver/internal/instance_relabel_end_to_end_test.go:43]: This should probably happen in the `prometheusreceiver` package where we already have a framework for e2e tests and shape testing of the resulting pdata metrics.

File: receiver/prometheusreceiver/metrics_receiver.go (hunk 3 above)
Comment (Aneurysm9) [reply receiver/prometheusreceiver/metrics_receiver.go:93]: Strike that, reverse it.  This PR removes the need for the scrape manager in the OCAStore, but the receiver still needs it as it is what handles scraping targets emitted by the discovery manager.

File: receiver/prometheusreceiver/internal/otlp_transaction_test.go (hunk 2 above)
Comment (gouthamve) [reply receiver/prometheusreceiver/internal/otlp_transaction_test.go]: hi, sorry, missed this somehow. Fixed it now!

File: receiver/prometheusreceiver/metrics_receiver.go (hunk 3 above)
Comment (gouthamve) [reply receiver/prometheusreceiver/metrics_receiver.go:93]: I'm not sure I follow but as Anthony said, its not required for `OCAStore` anymore. But it still exists in `r.scrapeManager`. I am resolving this comment as I think it has been addressed, but please let me know if I am missing something.

File: receiver/prometheusreceiver/internal/instance_relabel_end_to_end_test.go (hunk 4 above)
Comment (gouthamve) [reply receiver/prometheusreceiver/internal/instance_relabel_end_to_end_test.go:44]: Hrm, so, I tried moving it there, but the framework there is about verifying the "scrape" output and I cannot figure out how to verify the target and job labels that are added. Could you give me a pointer?

Comment (Aneurysm9) [reply receiver/prometheusreceiver/internal/instance_relabel_end_to_end_test.go:44]: You'd want to build a [test like this one](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/b00283b724e83bb91526108cdc3c43520c167961/receiver/prometheusreceiver/metrics_receiver_labels_test.go#L31), probably in that same file since it's already testing labeling handling.  The [validation function](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/b00283b724e83bb91526108cdc3c43520c167961/receiver/prometheusreceiver/metrics_receiver_labels_test.go#L47) can prepare a [set of expected resource attributes](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/b00283b724e83bb91526108cdc3c43520c167961/receiver/prometheusreceiver/metrics_receiver_labels_test.go#L47), which in this case would include the job and instance ID values mapped to the appropriate resource attribute identifiers.  `doCompare()` will [take care of asserting](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/519ea7ff61cb09d2be2d40b070fad753a1603a9b/receiver/prometheusreceiver/metrics_receiver_helper_test.go#L326-L332) that all of the expected resource attributes are present.

Comment (gouthamve) [reply receiver/prometheusreceiver/internal/instance_relabel_end_to_end_test.go:44]: Ah ack, working on it now. I didn't realise the resource attributes part.

**Comment by gouthamve** [comment]
@dashpole @Aneurysm9 @pmm-sumo Thanks for the initial review, I think I have addressed all the comments now. Could you take another look when you have some time?

File: receiver/prometheusreceiver/metrics_receiver_labels_test.go [hunk 5]
```diff
@@ -619,3 +620,70 @@ func TestHonorLabelsTrueConfig(t *testing.T) {
...
+			scrapeConfig.MetricRelabelConfigs = []*relabel.Config{
+				{
+					// this config should replace the instance label with 'relabeled-instance'
+					Action:      relabel.Replace,
+					Regex:       relabel.MustNewRegexp("(.*)"),
+					TargetLabel: "instance",
+					Replacement: "relabeled-instance",
+				},
+				{
+					// this config should replace the instance label with 'relabeled-instance'
```
Comment (Aneurysm9) [inline receiver/prometheusreceiver/metrics_receiver_labels_test.go:653]:
```suggestion
					// this config should replace the job label with 'not-target1'
```

**Review by Aneurysm9 — APPROVED** [review]

**Comment by jpkrohling** [comment]
PR updated to account for the v0.48.0 changes

**Review by dashpole — APPROVED** [review]

**Review by pmm-sumo — APPROVED** [review]

**Comment by jpkrohling** [comment]
Nice, github now allows us to restart only the failed jobs. Once we have a green build, I'll merge this.

**Comment by shacharSirotkin** [comment]
Hi,
I know it's a pretty old PR but I would be happy if you can upload a working config for Prometheus federation. 
I'm struggling with it for a long time. 
Thanks 🙏

**Comment by mx-psi** [comment]
> Hi, I know it's a pretty old PR but I would be happy if you can upload a working config for Prometheus federation. I'm struggling with it for a long time. Thanks 🙏

Please open a new issue for this, thanks!
