### PR TITLE
[pkg/ottl] Fix OTTL functions by using setters

### LINKED ISSUE #39100: [pkg/ottl] Fix replace functions for profiles
### Component(s)

pkg/ottl

### Describe the issue you're reporting

**Background**
The profiles signal uses indices + lookup table instead of an array or map.

For example, `pprofile.Profile` contains a lookup table of attributes (AttributeTable), which is referenced by an array of indices (AttributeIndices).

During the work on the transformprocessor ([draft PR(https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/39036)), it turned out that a typical accessor/getter for attributes would return a `pcommon.Map`. The OTTL functions then change this map and pass it to the accessor/setter.

**Problem**
Some of the OTTL functions assume that changes to the attributes map returned by the getter automatically change the profiles data without calling the setter.
For example [here](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/b1ea2d22d262bb98eb9eb635bab088300c136612/pkg/ottl/ottlfuncs/func_replace_all_patterns.go#L100)
So the changes are never written to the `pprofile.Profile` in this case.

**Possible solution**
Just from my limited knowledge... better solution possibly exist.
- identify all places were this assumption is wrong
- change the OTTL functions signature to take a GetSetter instead of a Getter and call the setter.

cc @TylerHelmuth

### PR DESCRIPTION
**Pull request by rockdaboot**
#### Description

Some OTTL functions do not call the accessor.setter function, but instead change the variable directly.
This doesn't work with the profiles signal where non-trivial processing is needed.

For example, attributes are split into a lookup table and arrays of indices (the rationale is de-duplication). While the accessor.getter function returns a pcommon.Map for attributes, any changes made to that map require passing the map to the accessor.setter function.

#### Link to tracking issue
Fixes #39100

### CODE REVIEW

File: pkg/ottl/ottlfuncs/func_delete_key.go [hunk 1]
```diff
@@ -29,13 +32,39 @@ func createDeleteKeyFunction[K any](_ ottl.FunctionContext, oArgs ottl.Arguments
...
 		}
 		val.Remove(key)
-		return nil, nil
+		return nil, target.Set(ctx, tCtx, val)
+	}
+}
+
+var emptyMap = pcommon.Map{}
+
+func anyToMap[K any](ctx context.Context, tCtx K, target ottl.GetSetter[K]) (pcommon.Map, error) {
```
Comment (rockdaboot) [inline pkg/ottl/ottlfuncs/func_delete_key.go:48]: Any advice where this should go into?

File: pkg/ottl/ottlfuncs/func_replace_all_matches.go [hunk 2]
```diff
@@ -75,11 +76,14 @@ func replaceAllMatches[K any](target ottl.PMapGetter[K], pattern string, replace
 				return nil, err
 			}
 		}
-		for _, value := range val.All() {
+
+		updated := pcommon.NewMap()
```
Comment (rockdaboot) [inline pkg/ottl/ottlfuncs/func_replace_all_matches.go:80]: The temporary map `updated` has been introduced here to avoid changing the input map `val`.
I have no `urban knowledge` here, so please advise whether
a) it's ok to change `val` here and `updated` should be removed
or
b) whether other functions should also not change `val`

File: pkg/ottl/ottlfuncs/func_delete_key.go [hunk 3]
```diff
@@ -6,12 +6,15 @@ package ottlfuncs // import "github.com/open-telemetry/opentelemetry-collector-c
...
+	"fmt"
+
+	"go.opentelemetry.io/collector/pdata/pcommon"
 
 	"github.com/open-telemetry/opentelemetry-collector-contrib/pkg/ottl"
 )
 
 type DeleteKeyArguments[K any] struct {
-	Target ottl.PMapGetter[K]
+	Target ottl.GetSetter[K]
```
Comment (TylerHelmuth) [inline pkg/ottl/ottlfuncs/func_delete_key.go:17]: I'd much prefer we make a ottl.PMapGetterSetter and make OTTL enforce the type. That was the original intent behind the typed-getters. We wanted to give function authors type guarantees when we could.

Comment (rockdaboot) [reply pkg/ottl/ottlfuncs/func_delete_key.go:17]: I started with a `ottl.PMapGetSetter` type, but could not get beyond this kind of error
```
--- FAIL: Test_e2e_editors (0.00s)
    --- FAIL: Test_e2e_editors/replace_all_patterns(attributes,_"key",_"^http",_"test") (0.00s)
panic: reflect.Set: value of type ottl.StandardGetSetter[github.com/open-telemetry/opentelemetry-collector-contrib/pkg/ottl/contexts/ottllog.TransformContext] is not assignable to type ottl.PMapGetSetter[github.com/open-telemetry/opentelemetry-collector-contrib/pkg/ottl/contexts/ottllog.TransformContext] [recovered]
        panic: reflect.Set: value of type ottl.StandardGetSetter[github.com/open-telemetry/opentelemetry-collector-contrib/pkg/ottl/contexts/ottllog.TransformContext] is not assignable to type ottl.PMapGetSetter[github.com/open-telemetry/opentelemetry-collector-contrib/pkg/ottl/contexts/ottllog.TransformContext]
```

Reverting back to `ottl.PMapGetSetter` requires help from someone with a deeper understanding of the OTTL code. Would you give me a helping hand when done, @TylerHelmuth?

Alternatively, since this PR blocks the [profiles support for the transformprocessor](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/39009), we can merge this and introduce `PMapGetSetter` in a saeparate PR.

File: pkg/ottl/ottlfuncs/func_delete_key.go (hunk 1 above)
Comment (edmocosta) [reply pkg/ottl/ottlfuncs/func_delete_key.go:48]: It depends on https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/39416#discussion_r2056329367, if we create the new `PMapGetSetter` reusing the existing typed getters, this won't be needed anymore, otherwise it will probably be moved into the specific getter impl.

File: pkg/ottl/ottlfuncs/func_replace_all_matches.go (hunk 2 above)
Comment (rockdaboot) [reply pkg/ottl/ottlfuncs/func_replace_all_matches.go:80]: Then we should at least take care that the OTTL functions doesn't change the values to avoid unexpected side-effects. We should create an own issue for this for further discussion.

File: pkg/ottl/ottlfuncs/func_delete_key.go (hunk 3 above)
Comment (rockdaboot) [reply pkg/ottl/ottlfuncs/func_delete_key.go]: Thanks for clarification and help!
The requested changes have been applied.

File: pkg/ottl/expression.go [hunk 4]
```diff
@@ -406,6 +406,24 @@ func (g StandardFunctionGetter[K]) Get(args Arguments) (Expr[K], error) {
 	return Expr[K]{exprFunc: fn}, nil
 }
 
+type PMapGetSetter[K any] interface {
```
Comment (edmocosta) [inline pkg/ottl/expression.go:409]: Could you please move these OTTL changes to a separate PR? It would also be nice to have some unit tests for that as well. Thanks!

Comment (rockdaboot) [reply pkg/ottl/expression.go:409]: @edmocosta The code has been split out into https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/39657. I still leave it here and fix things up when  #39657 has been merged into main.

**Comment by rockdaboot** [comment]
@TylerHelmuth Can you please also review #39657, which became a requirement for this PR?

File: pkg/ottl/ottlfuncs/func_flatten.go [hunk 5]
```diff
@@ -72,7 +72,7 @@ func flatten[K any](target ottl.PMapGetter[K], p ottl.Optional[string], d ottl.O
 		flattenData.flattenMap(m, prefix, 0)
 		flattenData.result.MoveTo(m)
 
-		return nil, nil
+		return nil, target.Set(ctx, tCtx, m)
```
Comment (TylerHelmuth) [inline pkg/ottl/ottlfuncs/func_flatten.go:75]: The call to `MoveTo` above is already updating the map behind the scenes without needing to call `target.set`. Those calls, as well as any `.CopyTo` calls against the target map will need to be removed.

Comment (rockdaboot) [reply pkg/ottl/ottlfuncs/func_flatten.go:75]: @TylerHelmuth Calling `target.Set` is mandatory here, since the attributes in the profiles signal can not be rendered as `pcommon.Map`. The setter has to take the values from the map and update two arrays, the lookup table and the array of indices into the lookup table. So for profiles, `CopyTo` or `MoveTo` without `target.Set` are essential no-ops and those should be removed. That's possibly what you meant, but you wrote it differently. Can you clarify, please?

File: pkg/ottl/ottlfuncs/func_replace_all_matches.go (hunk 2 above)
Comment (rockdaboot) [reply pkg/ottl/ottlfuncs/func_replace_all_matches.go]: I removed this piece of code again, we can discuss this separately when it pops up in reality.

File: pkg/ottl/ottlfuncs/func_flatten.go (hunk 5 above)
Comment (rockdaboot) [reply pkg/ottl/ottlfuncs/func_flatten.go]: Anyway, addressed this in func_flatten as it makes sense to me.

Comment (edmocosta) [reply pkg/ottl/ottlfuncs/func_flatten.go]: I'm wondering if we could extend the `pcommon.Map` to support creating read-only shallow copies of the original Map, setting the internal state to `StateReadOnly`. When this Map's state is set, it ensures that no data modification is performed and panics if that happen, which IMO would be fine, considering trying to modify read-only data should be considered a programming error.
 

Example:

```go
func (m Map) AsReadOnly() Map {
	state := internal.StateReadOnly
	return newMap(m.getOrig(), &state)
}
```

With that functionality, we could either make the `PMapGetSetter` [Get](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/39657/files#diff-073258313a2dc02137ad7eaeaf7323b6bf9639115905c2532c65bb635046229bR420) returns read-only values, or change it on the OTTL context path getters.

```go
func (path StandardPMapGetSetter[K]) Get(ctx context.Context, tCtx K) (pcommon.Map, error) {
	m, err := return path.Getter(ctx, tCtx)
        // ...
        return m.AsReadOnly(), nil
}
```

Thoughts?

Comment (TylerHelmuth) [reply pkg/ottl/ottlfuncs/func_flatten.go]: @edmocosta thats a good idea to enforce what we want.

@rockdaboot what I meant is that if we're trying to enforce that maps be set via the context's setter instead of via pdata functions, we should be consistent. In the case of flatten (and I think a majority of our editors that work on maps) we are calling ether `CopyTo` or `MoveTo` on the target instead of calling a setter. If a function does that and then also calls the `.Set` function, for most contexts it'll end up calling `CopyTo` or `MoveTo` twice. 

Since we're being consistent calling the context's setter, we need to remove the additional `CopyTo` or `MoveTo` in the function.

Comment (rockdaboot) [reply pkg/ottl/ottlfuncs/func_flatten.go]: @TylerHelmuth So I got it right, for `flatten` this already has been addressed.
It seems to be the only function affected. What other function do you have in mind?

Comment (rockdaboot) [reply pkg/ottl/ottlfuncs/func_flatten.go]: @edmocosta Good idea. Are you going to create an issue/PR? Does this PR has to wait for the new functionality or can we add read-only maps later? Just looking for clarity here.

Comment (TylerHelmuth) [reply pkg/ottl/ottlfuncs/func_flatten.go]: Maybe check merge_maps and the replace_all_patterns key scenario.

**Comment by TylerHelmuth** [comment]
The existing e2e tests give me confidence for all the non-profiles context. Would it be worth adding e2e tests for profiles specifically since it behaves different that the other contexts? Right now the e2e tests only use ottllog since they all behaved in the same general way.

File: pkg/ottl/ottlfuncs/func_flatten.go (hunk 5 above)
Comment (rockdaboot) [reply pkg/ottl/ottlfuncs/func_flatten.go]: > Maybe check merge_maps and the replace_all_patterns key scenario.

@TylerHelmuth In both function, the `CopyTo` has not `pcommon.Map` as source/target, instead that is on `pcommon.Value`. Can you give a concrete example of your idea for improvement? In `ctxutil.SetMap()` we could test the destination ans source map for equality and if true, skip the `CopyTo()` or do this check/skip inside `Map.CopyTo()`. But it feels out-of-scope for this PR.

**Comment by rockdaboot** [comment]
> The existing e2e tests give me confidence for all the non-profiles context. Would it be worth adding e2e tests for profiles specifically since it behaves different that the other contexts? Right now the e2e tests only use ottllog since they all behaved in the same general way.

Would you like to create an issue? I think it makes absolutely sense to have those e2e tests for profiles (and others).

File: pkg/ottl/ottlfuncs/func_flatten.go (hunk 5 above)
Comment (edmocosta) [reply pkg/ottl/ottlfuncs/func_flatten.go]: FYI, I've opened a PR adding the read-only functions: https://github.com/open-telemetry/opentelemetry-collector/pull/12995

**Comment by rockdaboot** [comment]
> The existing e2e tests give me confidence for all the non-profiles context. Would it be worth adding e2e tests for profiles specifically since it behaves different that the other contexts? Right now the e2e tests only use ottllog since they all behaved in the same general way.

For useful profiles based e2e tests, we first should merge https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/39681, because the current e2e tests heavily rely on attributes accessors. Without attributes processors, e2e test would look completely different to the logs based e2e tests. That's a) hardly to compare and b) lot of work and c) more code to maintain (no de-duplication of code possible).

**Comment by edmocosta** [comment]
> For useful profiles based e2e tests, we first should merge https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/39681, because the current e2e tests heavily rely on attributes accessors. Without attributes processors, e2e test would look completely different to the logs based e2e tests. That's a) hardly to compare and b) lot of work and c) more code to maintain (no de-duplication of code possible).

I agree it would have more value testing the editors with the paths that makes the profile context different, such as the `attributes`, and I'd be okay handling it in a separate issue(https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/40738). 

Before moving forward with this one, I really think we should add a few more tests cases to ensure that the problem this PR fixes won't happen again. We can do that by verifying that the setter function was actually called, and that the result is correct not just because the editor is directly modifying the object reference, but also because of setter call.

**Comment by rockdaboot** [comment]
> > For useful profiles based e2e tests, we first should merge #39681, because the current e2e tests heavily rely on attributes accessors. Without attributes processors, e2e test would look completely different to the logs based e2e tests. That's a) hardly to compare and b) lot of work and c) more code to maintain (no de-duplication of code possible).
> 
> I agree it would have more value testing the editors with the paths that makes the profile context different, such as the `attributes`, and I'd be okay handling it in a separate issue(#40738).
> 
> Before moving forward with this one, I really think we should add a few more tests cases to ensure that the problem this PR fixes won't happen again. We can do that by verifying that the setter function was actually called, and that the result is correct not just because the editor is directly modifying the object reference, but also because of setter call.

Added a check that the setter got actually called. This still doesn't check whether the editor was directly modifying the object as well. @edmocosta Would is the preferred way of doing that?

**Comment by edmocosta** [comment]
> Added a check that the setter got actually called. This still doesn't check whether the editor was directly modifying the object as well. @edmocosta Would is the preferred way of doing that?

We currently don't have any efficient mechanism to enforce the immutability of those returned maps - and my PData [PR](https://github.com/open-telemetry/opentelemetry-collector/pull/12995) got some pushback - so I think it would be fine to keep it as it's for now, and tackle it later when we decide how to deal with that in the OTTL core. 

@TylerHelmuth please let me know if you agree with [this](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/39416#issuecomment-2988017082), and with moving this PR forward. 

Thanks!

**Comment by rockdaboot** [comment]
@edmocosta @TylerHelmuth We now have OTTL e2e tests based on profiles.
The tests uncovered an issue in `accessAttributesKey()`, which is fixed in this PR.
Please let me know what you think.

**Review by TylerHelmuth — APPROVED** [review]
