### PR TITLE
[extension/awslogsencodingextension] Fix gzip header detection for mi…

### LINKED ISSUE #41884: Awslog encoding failing
### Component(s)

extension/encoding/awslogsencoding

### What happened?

Description
When using the OpenTelemetry Collector Contrib’s AWS S3 receiver with the awslogs_encoding/text_vpc_flow_log extension for ingesting AWS VPC Flow Logs (stored as .log.gz files), the receiver sometimes parses the entire contents of the file as a single log entry rather than splitting by record. This occurs despite the files being properly gzip-compressed and decompressing normally with gunzip locally.
There is no Content-Encoding metadata on these S3 objects.

Steps to Reproduce
Export AWS VPC Flow Logs to an S3 bucket with the default option (resulting in .log.gz files containing space-separated plain text records).

Configure the OpenTelemetry Collector Contrib’s awss3receiver with:

```
awss3receiver:
  encodings:
    - extension: awslogs_encoding/text_vpc_flow_log
      suffix: ".log.gz"
```
Deploy the collector and point it to the S3 bucket containing the log files.

Observe the ingested log records.

Expected Result
Each flow log line in the file should be parsed as a separate record/event.

The receiver should decompress .log.gz files and split them correctly according to the VPC Flow Log text specification.

Actual Result
The OpenTelemetry Collector Contrib's AWS S3 receiver attempts to process .log.gz files and logs the following error:

`2025-08-11T05:10:54.907Z  error  awss3receiver@v0.131.0/s3sqsreader.go:202  Failed to get reader for S3 object ... "error": "failed to get reader for vpc_flow_log '...log.gz': failed to decompress content: gzip: invalid header"`

The collector fails to decompress the .log.gz file and does not ingest the log data.

The same .log.gz file can be successfully decompressed locally using gunzip, confirming the file is valid.

The S3 object's metadata does not include a Content-Encoding header.

As a result, the expected VPC flow log lines do not appear as individual log entries in the collector; ingestion for these files fails with the above error.
Additional Info:

S3 objects have no Content-Encoding metadata.

Local decompression works as expected.

Collector configuration uses the recommended extension for VPC Flow Logs.

The issue persists regardless of whether files have the .log.gz extension and valid gzip compression

### Collector version

v0.131.0

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

### OpenTelemetry Collector configuration

```yaml
receivers:
  awss3:
    s3downloader:
      region: "ap-south-1"                 
      s3_bucket: "vpc-flow-log"     
    encodings:
      - extension: awslogs_encoding/text_vpc_flow_log
        suffix: ".log"
      - extension: awslogs_encoding/text_vpc_flow_log
        suffix: ".log.gz"

exporters:
  logging:
    loglevel: debug

service:
  pipelines:
    logs:
      receivers: [awss3]
      exporters: [logging]
```

### Log output

```shell
2025-08-11T05:10:54.907Z  error  awss3receiver@v0.131.0/s3sqsreader.go:202  Failed to get reader for S3 object ... "error": "failed to get reader for vpc_flow_log '...log.gz': failed to decompress content: gzip: invalid header
```

### Additional context

_No response_

### Tip

<sub>[React](https://github.blog/news-insights/product-news/add-reactions-to-pull-requests-issues-and-comments/) with 👍 to help prioritize this issue. Please use comments to provide useful context, avoiding `+1` or `me too`, to help us triage it. Learn more [here](https://opentelemetry.io/community/end-user/issue-participation/).</sub>

### PR DESCRIPTION
**Pull request by adithya-r-nathan**
[extension/awslogsencodingextension] Fix gzip header detection for mixed compressed/uncompressed files

- Add gzip magic bytes check (0x1f, 0x8b) before decompression
- Handle files with .gz extension that are not actually compressed
- Apply fix to WAF, CloudTrail, CloudWatch, VPC Flow formats

Fixes #41884

#### Description

This PR fixes the "gzip: invalid header" error that occurs when the AWS logs encoding extension processes files with `.gz` extensions that are not actually gzip-compressed. 

**Problem:** The extension was attempting to decompress all input as gzip without checking if the data was actually compressed, causing failures when processing plain text files that happen to have `.gz` extensions.

**Solution:** Added gzip magic bytes detection (`0x1f`, `0x8b`) before attempting decompression. If the magic bytes are not present, the data is processed as plain text instead of failing with a decompression error.

**Affected formats:** WAF logs, CloudTrail logs, CloudWatch subscription filter logs, and VPC Flow logs (plain text format).

#### Link to tracking issue
Fixes #41884

#### Testing

- All existing unit tests pass
- Added test coverage for non-gzip input handling in `TestGetReaderFromFormat`
- Updated `TestNew_VPCFlowLog` to reflect the new resilient behavior
- Verified compression detection works for both compressed and uncompressed files
- Tested concurrent gzip reader usage to ensure thread safety is maintained

#### Documentation

No documentation changes required as this is a bug fix that maintains backward compatibility while extending support for mixed file types.

### CODE REVIEW

File: extension/encoding/awslogsencodingextension/extension.go [hunk 1]
```diff
@@ -108,22 +107,46 @@ func (e *encodingExtension) getGzipReader(buf []byte) (io.Reader, error) {
...
-	case formatWAFLog, formatCloudWatchLogsSubscriptionFilter, formatCloudTrailLog:
-		reader, err := e.getGzipReader(buf)
-		return gzipEncoding, reader, err
+	case formatWAFLog:
+		// Check if the data is compressed
+		if len(buf) > 2 && buf[0] == 0x1f && buf[1] == 0x8b {
+			reader, err := e.getGzipReader(buf)
+			return gzipEncoding, reader, err
+		}
+		return bytesEncoding, bytes.NewReader(buf), nil
```
Comment (constanca-m) [inline extension/encoding/awslogsencodingextension/extension.go]: Thanks for taking the initiative to fix this. Can you put this in a function so it doesn't need to be repeated so many times?

File: extension/encoding/awslogsencodingextension/extension_test.go [hunk 2]
```diff
@@ -4,169 +4,163 @@
...
-	_, err = e.UnmarshalLogs([]byte("invalid"))
-	require.ErrorContains(t, err, `failed to get reader for "vpc_flow_log" logs`)
+    cfg := createDefaultConfig().(*Config)
+    cfg.Format = formatVPCFlowLog
+    e, err := newExtension(cfg, extensiontest.NewNopSettings(extensiontest.NopType))
+    require.NoError(t, err)
+    require.NotNil(t, e)
+
+    // VPC Flow Log unmarshaler is resilient and handles invalid input gracefully
+    _, err = e.UnmarshalLogs([]byte("insufficient fields for vpc flow log"))
```
Comment (constanca-m) [inline extension/encoding/awslogsencodingextension/extension_test.go]: Is it ok with you to refactor this message `insufficient fields for vpc flow log`? It makes it read like an error will be thrown from it

File: extension/encoding/awslogsencodingextension/extension.go (hunk 1 above)
Comment (adithya-r-nathan) [reply extension/encoding/awslogsencodingextension/extension.go]: Makes perfect sense! I've updated the code to use a common function instead of repeating the gzip detection logic everywhere.

File: extension/encoding/awslogsencodingextension/extension_test.go (hunk 2 above)
Comment (adithya-r-nathan) [reply extension/encoding/awslogsencodingextension/extension_test.go]: You're absolutely right! I've updated the test code with a helper function and changed that confusing message.

File: extension/encoding/awslogsencodingextension/extension.go
Comment (axw) [inline extension/encoding/awslogsencodingextension/extension.go:1]: It looks like your editor/IDE has changed tabs to spaces. This will cause CI to fail, please run `make fmt` to fix.

**Review by axw — CHANGES_REQUESTED** [review]

File: extension/encoding/awslogsencodingextension/extension_test.go [hunk 3]
```diff
@@ -18,6 +18,13 @@ import (
     subscriptionfilter "github.com/open-telemetry/opentelemetry-collector-contrib/extension/encoding/awslogsencodingextension/internal/unmarshaler/subscription-filter"
 )
 
+// Helper function to unmarshal logs and expect no error
+func unmarshalLogsExpectNoError(t *testing.T, e *encodingExtension, buf []byte) {
+    logs, err := e.UnmarshalLogs(buf)
+    require.NoError(t, err)
+    require.NotNil(t, logs)
+}
+
```
Comment (axw) [inline extension/encoding/awslogsencodingextension/extension_test.go]: This is used in one place, not sure it's worth making a helper out of it?

**Review by axw — COMMENTED** [review]
Thank you, the code change looks good apart from the whitespace and IMO premature introduction of a helper function.

This is worthy of a changelog, please see https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/CONTRIBUTING.md#adding-a-changelog-entry

File: extension/encoding/awslogsencodingextension/extension_test.go (hunk 3 above)
Comment (adithya-r-nathan) [reply extension/encoding/awslogsencodingextension/extension_test.go]: Thanks for the feedback! I've addressed all the issues:

✅ Fixed formatting with `go fmt`  
✅ Removed helper function - inlined since only used once  
✅ Added changelog entry

**Review by axw — APPROVED** [review]
LGTM, thanks :)

**Review by constanca-m — APPROVED** [review]
Thanks!

**Comment by adithya-r-nathan** [comment]
I have locally built the image and tested it by deploying with the built image. It appears to be functioning correctly.

**Review by atoulme — APPROVED** [review]

**Comment by axw** [comment]
Unit test failure is unrelated, I'll put up a fix
