### PR TITLE
[exporter/signalfx] Fix memory leak on shutdown

### LINKED ISSUE #30864: [exporter/signalfx] Failing goleak test
### Component(s)

exporter/signalfx

## Description

The signalfx exporter is failing goleak tests with 

```
goleak: Errors on successful test run: found unexpected goroutines:
[Goroutine 9 in state chan send, with github.com/open-telemetry/opentelemetry-collector-contrib/exporter/signalfxexporter/internal/apm/requests.(*ReqSender).Send on top of the stack:
github.com/open-telemetry/opentelemetry-collector-contrib/exporter/signalfxexporter/internal/apm/requests.(*ReqSender).Send(0xc00007c660, 0xc0001cca00)
	/home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/exporter/signalfxexporter/internal/apm/requests/sender.go:52 +0x12c
github.com/open-telemetry/opentelemetry-collector-contrib/exporter/signalfxexporter/internal/apm/correlations.(*Client).makeRequest(0xc000411e10, 0xc000036690)
	/home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/exporter/signalfxexporter/internal/apm/correlations/client.go:334 +0x14a8
github.com/open-telemetry/opentelemetry-collector-contrib/exporter/signalfxexporter/internal/apm/correlations.(*Client).processChan(0xc000411e10)
	/home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/exporter/signalfxexporter/internal/apm/correlations/client.go:355 +0x39a
created by github.com/open-telemetry/opentelemetry-collector-contrib/exporter/signalfxexporter/internal/apm/correlations.(*Client).Start in goroutine 7
	/home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/exporter/signalfxexporter/internal/apm/correlations/client.go:387 +0xa6
]
```

[job log](https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/7709155483/job/21009946555)

### Collector version

816671e3a2378b40c1d24114a09efc93b0c2e63d

### Additional context

Started happening after #30457 cc @crobert-1

### PR DESCRIPTION
**Pull request by crobert-1**
**Description:** <Describe what has changed.>

`goleak` was detecting leaking goroutines in tests, this attempts to resolve. I found what appeared to be a couple races but can't reproduce locally so I'll run CI a few times to ensure this works as expected.

Changes in PR:
1. Add correlation client Shutdown function that blocks on the waitgroup. This is the main fix of this PR that should fix the leaking goroutines.
2. Re-organize the shutdown process of the apm client correlation test suite to properly synchronize the shutting down process.
3. Fix typo
4. Add goleak checks to exporter/signalfx/internal/correlation` and `exporter/signalfx/internal/apm/correlations`

**Link to tracking Issue:** <Issue number if applicable>
Resolves #30864
#30438

**Testing:** <Describe what testing was performed and which tests were added.>
All existing and added tests should be passing. Since this has only failed in CI I'm going to try to run it a few times before marking as ready for review.

### CODE REVIEW

**Comment by crobert-1** [comment]
Tests have passed 6 times in a row, I believe this is ready for review.

**Review by atoulme — APPROVED** [review]

File: exporter/signalfxexporter/internal/correlation/correlation_test.go [hunk 1]
```diff
@@ -86,6 +86,10 @@ func TestTrackerStart(t *testing.T) {
 			} else {
 				require.NoError(t, err)
 			}
+
+			if tracker != nil {
+				assert.NoError(t, tracker.Shutdown(context.Background()))
+			}
```
Comment (dmitryax) [inline exporter/signalfxexporter/internal/correlation/correlation_test.go:92]: How tracker can be nil at this point?

**Review by dmitryax — APPROVED** [review]
LGTM, just one clarification

File: exporter/signalfxexporter/internal/correlation/correlation_test.go (hunk 1 above)
Comment (crobert-1) [reply exporter/signalfxexporter/internal/correlation/correlation_test.go:92]: Good catch, I don't think it can. I don't remember my thought process here, but it may have been concern about an error on start. If `tracker.Start` is called and `tracker` is nil, that would panic anyways, so there's no need to check below it in the test.

The test is passing without this check, so I'll remove it.

**Comment by sparam** [comment]
@crobert-1 any idea which version introduced this memory leak?

**Comment by crobert-1** [comment]
> @crobert-1 any idea which version introduced this memory leak?

Not exactly sure, but it's been present since at least `v0.86.0`.
