### PR TITLE
[receiver/k8sobjectsreceiver] Handle missing objects via `error_mode`

### LINKED ISSUE #38803: [k8sobjectsreceiver] Degrade gracefully, when watched CRDs are not found
### Component(s)

receiver/k8sobjects

## Description
Today, if you specify a list of CRDs to be watched, the collector won't start if any of them are missing and stay in  CrashLoopBackOff.

## Steps to Reproduce

Apply the following receiver and use it in a pipeline without having `telemetries.telemetry.istio.io` installed on your cluster. 

```yaml
receivers:
    k8sobjects:
      objects:
        - name: telemetries
          mode: watch
          group: telemetry.istio.io/v1alpha1
```
## Expected Result

The collector should start, and the receiver should be able to watch all CRDs it has found.

## Actual Result

```console
Error: invalid configuration: receivers::k8sobjects: resource XY not found. Valid resources are: [                                                                                                                                                                      helmchartconfigs configmaps rolebindings etc. ... 
```

### Collector version

v0.115.0

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

### OpenTelemetry Collector configuration

```yaml
receivers:
  k8sobjects:
    objects:
      - name: telemetries
        mode: watch
        group: telemetry.istio.io/v1alpha1
```

### Log output

```shell
Error: invalid configuration: receivers::k8sobjects: resource XY not found. Valid resources are: [                                                                                                                                                                      helmchartconfigs configmaps rolebindings etc. ...
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by krisztianfekete**
#### Description
This PR adopts a similar logic to `ottl.ErrorMode` for `k8sobjectsreceiver`, enabling users to choose between ignoring, silencing, and propagating errors for missing objects.

The default is `propagate`, therefore it is backward compatible with the current state.

#### Link to tracking issue
Fixes https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/38803

#### Testing
Added tests, and also tested by building my own image and deployed into a Kubernetes cluster.

#### Documentation
I've updated `receiver/k8sobjectsreceiver/config.yaml` and README with the new config options.

### CODE REVIEW

**Comment by krisztianfekete** [comment]
> Not a big fan of bringing a language feature of ottl into an exporter. I think the k8sobjectsreceiver can create and maintain its own semantics. That said, will defer to codeowners.

Yes, there are other components re-using that, but more closely related to OTTL maybe. I am fine re-implementing it for this receiver too, if that's the consensus.

File: receiver/k8sobjectsreceiver/config.go [hunk 1]
```diff
@@ -50,26 +59,59 @@ type K8sObjectsConfig struct {
...
 	// For mocking purposes only.
 	makeDiscoveryClient func() (discovery.ServerResourcesInterface, error)
 	makeDynamicClient   func() (dynamic.Interface, error)
 }
 
-func (c *Config) Validate() error {
+func (c *Config) Validate(logger *zap.Logger) error {
+	if logger == nil {
+		logger = zap.NewNop()
+	}
```
Comment (atoulme) [inline receiver/k8sobjectsreceiver/config.go:74]: please just return errors.

File: receiver/k8sobjectsreceiver/receiver.go [hunk 2]
```diff
@@ -63,6 +68,7 @@ func newReceiver(params receiver.Settings, config *Config, consumer consumer.Log
 		config:   config,
 		obsrecv:  obsrecv,
 		mu:       sync.Mutex{},
+		logger:   params.Logger,
```
Comment (atoulme) [inline receiver/k8sobjectsreceiver/receiver.go:71]: why do you define this logger separately from the logger under `setting`?

File: receiver/k8sobjectsreceiver/receiver.go [hunk 3]
```diff
@@ -50,6 +51,10 @@ func newReceiver(params receiver.Settings, config *Config, consumer consumer.Log
 		return nil, err
 	}
 
+	if err := config.Validate(); err != nil {
+		return nil, err
+	}
```
Comment (atoulme) [inline receiver/k8sobjectsreceiver/receiver.go:56]: Please remove this, this is incorrect. Validation happens through ConfigValidator casting outside of the creation of the receiver.

File: receiver/k8sobjectsreceiver/config.go [hunk 4]
```diff
@@ -50,26 +59,61 @@ type K8sObjectsConfig struct {
...
 	makeDynamicClient   func() (dynamic.Interface, error)
 }
 
 func (c *Config) Validate() error {
+	zapCfg := zap.NewProductionConfig()
+	logger, err := zapCfg.Build()
+	if err != nil {
+		return fmt.Errorf("failed to create logger: %w", err)
+	}
+	c.logger = logger
```
Comment (atoulme) [inline receiver/k8sobjectsreceiver/config.go:77]: please do not create a logger or change the state of the Config struct in Validate.

File: receiver/k8sobjectsreceiver/config.go [hunk 5]
```diff
@@ -50,26 +59,61 @@ type K8sObjectsConfig struct {
...
+	}
+
 	validObjects, err := c.getValidObjects()
 	if err != nil {
-		return err
+		if c.ErrorMode == PropagateError {
+			return err
+		}
+		if c.ErrorMode == IgnoreError {
+			c.logger.Warn("Error getting valid objects", zap.Error(err))
```
Comment (atoulme) [inline receiver/k8sobjectsreceiver/config.go:95]: ignore means ignore, please remove the warning.

File: receiver/k8sobjectsreceiver/config.go [hunk 6]
```diff
@@ -33,6 +34,14 @@ var modeMap = map[mode]bool{
 	WatchMode: true,
 }
 
+type ErrorMode string
+
+const (
+	PropagateError ErrorMode = "propagate"
+	IgnoreError    ErrorMode = "ignore"
+	SilentError    ErrorMode = "silent"
```
Comment (atoulme) [inline receiver/k8sobjectsreceiver/config.go:42]: I don't see a functional difference.

File: receiver/k8sobjectsreceiver/config.go [hunk 7]
```diff
@@ -33,6 +34,14 @@ var modeMap = map[mode]bool{
 	WatchMode: true,
 }
 
+type ErrorMode string
+
+const (
+	PropagateError ErrorMode = "propagate"
```
Comment (atoulme) [inline receiver/k8sobjectsreceiver/config.go:40]: I also don't understand what Propagate means here - are we propagating errors from somewhere?

File: receiver/k8sobjectsreceiver/config.go (hunk 5 above)
Comment (atoulme) [reply receiver/k8sobjectsreceiver/config.go:95]: I think the problem is that this validation should not take place in Config.Validate then. That should happen in the Start function of the receiver.

Comment (krisztianfekete) [reply receiver/k8sobjectsreceiver/config.go:95]: Yes, most of this validation can be also moved there, but the original purpose of `Validate` was validating available objects. My intention is providing ways to handle various modes of Validation in case of errors by following the original logic. 

Happy to collaborate with you and the code owners on fixing this, but I think at this point, it's better to take a step back and come up with a consensus on what should be in scope for `Validation` and `Start`.

Comment (krisztianfekete) [reply receiver/k8sobjectsreceiver/config.go:95]: Any thoughts, code-owners?
cc. @dmitryax @ChrsMark @TylerHelmuth

Comment (krisztianfekete) [reply receiver/k8sobjectsreceiver/config.go:95]: Let me ping this thread gently.

Comment (ChrsMark) [reply receiver/k8sobjectsreceiver/config.go:95]: TBH it looks weird to me that there is already a `get` (with `getValidObjects()) of Objects in this `Validate` method. I'd think that needs to be refactored.

In any case, is the intention to handle errors when receiving objects? If so, the logic should be applied on the `watch` when the objects are received.

Comment (ChrsMark) [reply receiver/k8sobjectsreceiver/config.go]: Hey @krisztianfekete I just had a more careful look into this. I now see why we want to check for existing objects on startup, which makes sense (what I mentioned in my previous comment about checking every object that `watch` receives is a different thing).

In this, having a way to mute errors from this once-off check/validation makes sense.

However, what @atoulme mentioned at https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/38851#discussion_r2010626635 sounds right but since we already have the validation in place we will need a separate PR to refactor this. The question is if we should require this refactoring before introducing the settings the current PR suggests 🤔. @TylerHelmuth @atoulme wdyt?

File: receiver/k8sobjectsreceiver/config.go [hunk 8]
```diff
@@ -50,53 +58,26 @@ type K8sObjectsConfig struct {
...
+	Objects   []*K8sObjectsConfig `mapstructure:"objects"`
+	ErrorMode ErrorMode           `mapstructure:"error_mode"`
+	logger    *zap.Logger
 
 	// For mocking purposes only.
 	makeDiscoveryClient func() (discovery.ServerResourcesInterface, error)
 	makeDynamicClient   func() (dynamic.Interface, error)
 }
 
-func (c *Config) Validate() error {
```
Comment (ChrsMark) [inline receiver/k8sobjectsreceiver/config.go:60]: I suggest this refactoring to take place in a separate PR.

Comment (krisztianfekete) [reply receiver/k8sobjectsreceiver/config.go:60]: Makes sense. I can revert to [c5d68b5](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/38851/commits/c5d68b55356c601de22bbd6935d9a3fb19bc899e) move the default propagation into default config, and if we are fine with ignore/silent/propagate (can also reduce to true/false or similar) the PR should fix the original validation issue at startup.

File: receiver/k8sobjectsreceiver/config.go (hunk 5 above)
Comment (krisztianfekete) [reply receiver/k8sobjectsreceiver/config.go]: This was done in https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/39469

**Review by ChrsMark — COMMENTED** [review]
Thank's @krisztianfekete, overall looks good to me with few small suggestions.

Probably a `make fmt` will fix the lint errors.

File: receiver/k8sobjectsreceiver/config.go [hunk 9]
```diff
@@ -50,14 +60,26 @@ type K8sObjectsConfig struct {
...
+	Objects   []*K8sObjectsConfig `mapstructure:"objects"`
+	ErrorMode ErrorMode           `mapstructure:"error_mode"`
+	logger    *zap.Logger
 
 	// For mocking purposes only.
 	makeDiscoveryClient func() (discovery.ServerResourcesInterface, error)
 	makeDynamicClient   func() (dynamic.Interface, error)
 }
 
+func (c *Config) SetLogger(logger *zap.Logger) {
```
Comment (ChrsMark) [inline receiver/k8sobjectsreceiver/config.go:72]: Is this required? It looks weird to me that we need to set logger as part of the Config but maybe I miss sth here.

File: receiver/k8sobjectsreceiver/receiver.go [hunk 10]
```diff
@@ -321,3 +361,30 @@ func newTicker(ctx context.Context, repeat time.Duration) *time.Ticker {
...
+
+	switch kr.config.ErrorMode {
+	case PropagateError:
+		if msg != "" {
+			return fmt.Errorf("%s: %w", msg, err)
+		}
+		return err
+	case IgnoreError:
+		if msg != "" {
+			kr.setting.Logger.Warn(msg, zap.Error(err))
```
[the remark this answers is not in the document]
Comment (iblancasa) [reply receiver/k8sobjectsreceiver/receiver.go:373]: I agree. Or maybe introducing a new `ErrorMode` that is like `IgnoreError` but with warning log level.

File: receiver/k8sobjectsreceiver/receiver.go [hunk 11]
```diff
@@ -74,24 +74,36 @@ func newReceiver(params receiver.Settings, config *Config, consumer consumer.Log
...
-			availableResource := make([]string, len(validObjects))
-			for k := range validObjects {
-				availableResource = append(availableResource, k)
+			err := fmt.Errorf("resource not found: %s", object.Name)
+			// First handle the error which will log it if in ignore mode
+			if handlerErr := kr.handleError(err, ""); handlerErr != nil {
+				return handlerErr
+			}
+
+			// Then log additional context if in ignore mode
```
Comment (iblancasa) [inline receiver/k8sobjectsreceiver/receiver.go:97]: I think this should be propagated in case `PropagateError` is used too.

File: receiver/k8sobjectsreceiver/receiver.go [hunk 12]
```diff
@@ -176,7 +201,9 @@ func (kr *k8sobjectsreceiver) startPull(ctx context.Context, config *K8sObjectsC
 		case <-ticker.C:
 			objects, err := resource.List(ctx, listOption)
 			if err != nil {
-				kr.setting.Logger.Error("error in pulling object", zap.String("resource", config.gvr.String()), zap.Error(err))
+				kr.setting.Logger.Error("error in pulling object",
```
Comment (iblancasa) [inline receiver/k8sobjectsreceiver/receiver.go:204]: Shouldn't this be done using the `handleError` method?

File: receiver/k8sobjectsreceiver/receiver.go [hunk 13]
```diff
@@ -74,24 +74,36 @@ func newReceiver(params receiver.Settings, config *Config, consumer consumer.Log
...
-		return err
+		return kr.handleError(err, "failed to create dynamic client")
 	}
 	kr.client = client
 
 	// Validate objects against K8s API
 	validObjects, err := kr.config.getValidObjects()
 	if err != nil {
-		return err
+		return kr.handleError(err, "failed to get valid objects")
```
[the remark this answers is not in the document]
Comment (iblancasa) [reply receiver/k8sobjectsreceiver/receiver.go:84]: I agree. Following the description of the field, it should apply to missing objects but not to all errors. Right?

[the remark this answers is not in the document]
Comment (krisztianfekete) [reply receiver/k8sobjectsreceiver/receiver.go:84]: Right, wondering what's the best way to differentiate between objects not found and network failures. Maybe checking for context deadline exceeded cases in `handleError` which should propagate regardless of `error_mode`?

File: receiver/k8sobjectsreceiver/receiver.go (hunk 10 above)
[the remark this answers is not in the document]
Comment (krisztianfekete) [reply receiver/k8sobjectsreceiver/receiver.go]: Switched to info level.

File: receiver/k8sobjectsreceiver/receiver.go (hunk 13 above)
[the remark this answers is not in the document]
Comment (ChrsMark) [reply receiver/k8sobjectsreceiver/receiver.go:86]: I would just return the error as is and let the Collector handle it as usual.

File: receiver/k8sobjectsreceiver/receiver.go (hunk 12 above)
Comment (ChrsMark) [reply receiver/k8sobjectsreceiver/receiver.go]: I would avoid handling all errors. I think `error_mode` was originally proposed for errors that occur while checking if desired k8s objects are available via the K8s API. These are errors that we can easily ignore or silent but we cannot easily generalise for all errors that might occur during the execution of the receiver. Maybe we can rename the setting or clearly mention this in the docs to avoid confusion. That said, I think we should only use  `handleError` for the respective k8s-api-objects-validation errors and leave everything else as is. Otherwise we introduce extra complexity to the receiver.

File: receiver/k8sobjectsreceiver/receiver.go [hunk 14]
```diff
@@ -131,10 +140,17 @@ func (kr *k8sobjectsreceiver) Shutdown(context.Context) error {
...
-	kr.setting.Logger.Info("Started collecting", zap.Any("gvr", object.gvr), zap.Any("mode", object.Mode), zap.Any("namespaces", object.Namespaces))
+	kr.setting.Logger.Info("Started collecting",
+		zap.Any("gvr", object.gvr),
+		zap.Any("mode", object.Mode),
+		zap.Any("namespaces", object.Namespaces))
 
 	switch object.Mode {
 	case PullMode:
+		// Set default interval if not set
+		if object.Interval == 0 {
```
Comment (ChrsMark) [inline receiver/k8sobjectsreceiver/receiver.go:151]: This does not seem the right place to do this. Could that be done earlier when we originally create/validate the objects?

File: receiver/k8sobjectsreceiver/receiver.go (hunk 12 above)
Comment (iblancasa) [reply receiver/k8sobjectsreceiver/receiver.go]: I agree. When asked that, I was trying to understand on what situations we wanted to silent or not. But I totally agree with you

File: receiver/k8sobjectsreceiver/receiver.go (hunk 14 above)
Comment (krisztianfekete) [reply receiver/k8sobjectsreceiver/receiver.go]: Moved it to `newReceiver`

**Review by iblancasa — APPROVED** [review]

File: receiver/k8sobjectsreceiver/receiver.go [hunk 15]
```diff
@@ -101,15 +113,21 @@ func (kr *k8sobjectsreceiver) Start(ctx context.Context, _ component.Host) error
...
 		}
+
 		object.gvr = gvr
+		validConfigs = append(validConfigs, object)
 	}
 
-	kr.setting.Logger.Info("Object Receiver started")
+	if len(validConfigs) == 0 {
+		err := errors.New("no valid Kubernetes objects found to watch")
+		return kr.handleError(err, "")
```
[the remark this answers is not in the document]
Comment (ChrsMark) [reply receiver/k8sobjectsreceiver/receiver.go:128]: Why not to just return the error? 
```suggestion
		return err
```

File: receiver/k8sobjectsreceiver/receiver.go (hunk 13 above)
[the remark this answers is not in the document]
Comment (ChrsMark) [reply receiver/k8sobjectsreceiver/receiver.go:89]: That's still unresolved. Why not to just return the error?

```suggestion
		return err
```

File: receiver/k8sobjectsreceiver/receiver.go [hunk 16]
```diff
@@ -74,24 +79,36 @@ func newReceiver(params receiver.Settings, config *Config, consumer consumer.Log
...
+				return handlerErr
+			}
+
+			// Then log additional context if in ignore mode
+			if kr.config.ErrorMode == IgnoreError {
+				availableResource := make([]string, 0, len(validObjects))
+				for k := range validObjects {
+					availableResource = append(availableResource, k)
+				}
+				kr.setting.Logger.Warn("Available resources in cluster",
```
Comment (ChrsMark) [inline receiver/k8sobjectsreceiver/receiver.go:108]: Can we just pass the `Available resources in cluster...` message to `handleError` above? Right now we log twice for the same reason, right?

File: receiver/k8sobjectsreceiver/receiver.go [hunk 17]
```diff
@@ -74,7 +78,7 @@ func newReceiver(params receiver.Settings, config *Config, consumer consumer.Log
 func (kr *k8sobjectsreceiver) Start(ctx context.Context, _ component.Host) error {
 	client, err := kr.config.getDynamicClient()
 	if err != nil {
-		return err
+		return kr.handleError(err, "failed to create dynamic client")
```
Comment (ChrsMark) [inline receiver/k8sobjectsreceiver/receiver.go:81]: I guess we missed this one? 
```suggestion
		return err
```

Let's fix it as well.

**Review by ChrsMark — APPROVED** [review]
LGTM

File: receiver/k8sobjectsreceiver/receiver.go (hunk 17 above)
Comment (krisztianfekete) [reply receiver/k8sobjectsreceiver/receiver.go]: Had it staged, just pushed it, thanks!
