### PR TITLE
fix[receiver/sqlquery]: Null value logs collection

### LINKED ISSUE #43984: fix[receiver/sqlquery] Null values result in a hard error instead of a warning.
### Component(s)

receiver/sqlquery

## Description

When utilizing the SQL Query Receiver to collect logs, any null value in a row results in no rows being collected. This is contrary to the documentation [here](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/receiver/sqlqueryreceiver/README.md#null-values), which seems to indicate that while all rows that contain null values should result in a warning log, one row having a null value should not result in all rows being dropped and an error.

## Steps to Reproduce

Use the SQL query receiver to query from a database table with at least one NULL value.

Image

## Expected Result

All rows should be collected, any NULL data should be ignored. A warning log should be emitted to indicate missing data to the user.

## Actual Result

No logs are returned and an error such as `error getting rows: column "TestMe": NULL value` is returned.

### Collector version

v0.138.0

## Environment
OS: Microsoft Windows Server 2019
MSSQL Server

### OpenTelemetry Collector configuration

Here is the relevant receiver configuration.

```yaml
    sqlquery/s-01JV3219M36D7NT5THYRSD12EF__logs:
        additional_params: {}
        collection_interval: 10s
        database: AdventureWorks2022
        driver: sqlserver
        host: bp-qa-ub-wintoo
        password: (sensitive)
        port: 1433
        queries:
            - logs:
                - body_column: GroupName
              sql: USE AdventureWorks2022; select * from HumanResources.Department where ModifiedDate > @p1
              tracking_column: ModifiedDate
              tracking_start_value: 2008-04-30 00:00:00:000
        telemetry:
            logs:
                query: true
        username: test
```

### Log output

```shell

```

### Additional context

This should be a small fix, the error is [handled well in the internal/sqlquery package](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/f52d79b36486f351db0ba2cfd2e724be331eaf12/internal/sqlquery/scraper.go#L79) - it just needs to be similarly handled well in the [receiver/sqlqueryreceiver package](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/f52d79b36486f351db0ba2cfd2e724be331eaf12/receiver/sqlqueryreceiver/logs_receiver.go#L294).

### Tip

<sub>[React](https://github.blog/news-insights/product-news/add-reactions-to-pull-requests-issues-and-comments/) with 👍 to help prioritize this issue. Please use comments to provide useful context, avoiding `+1` or `me too`, to help us triage it. Learn more [here](https://opentelemetry.io/community/end-user/issue-participation/).</sub>

### PR DESCRIPTION
**Pull request by mrsillydog**
#### Description

This change prevents log collection from being fully halted by a single log with a NULL value. Instead, logs should drop NULL values, and other logs will be collected normally.

#### Link to tracking issue
Fixes https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/43984

#### Testing

Unit testing to ensure that the receiver would not error upon receiving `ErrNullValueWarning` from DBClient.QueryRows.
Manual testing with a distribution of the collector built off of this branch.

### CODE REVIEW

File: receiver/sqlqueryreceiver/logs_receiver.go [hunk 1]
```diff
@@ -291,7 +291,10 @@ func (queryReceiver *logsQueryReceiver) collect(ctx context.Context) (plog.Logs,
 		rows, err = queryReceiver.client.QueryRows(ctx)
 	}
 	if err != nil {
-		return logs, fmt.Errorf("error getting rows: %w", err)
+		if !errors.Is(err, sqlquery.ErrNullValueWarning) {
+			return logs, fmt.Errorf("error getting rows: %w", err)
+		}
+		queryReceiver.logger.Warn("problems encountered getting log rows", zap.Error(err))
```
Comment (crobert-1) [inline receiver/sqlqueryreceiver/logs_receiver.go]: I don't know what the actual log message will be here, but since we know it's a null value error, the default statement could specifically mention that a null value has been encountered.

File: receiver/sqlqueryreceiver/logs_receiver.go [hunk 2]
```diff
@@ -291,7 +291,10 @@ func (queryReceiver *logsQueryReceiver) collect(ctx context.Context) (plog.Logs,
 		rows, err = queryReceiver.client.QueryRows(ctx)
 	}
 	if err != nil {
-		return logs, fmt.Errorf("error getting rows: %w", err)
+		if !errors.Is(err, sqlquery.ErrNullValueWarning) {
+			return logs, fmt.Errorf("error getting rows: %w", err)
```
Comment (crobert-1) [inline receiver/sqlqueryreceiver/logs_receiver.go]: For the sake of consistency, maybe just copy what the [metrics log message](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/805c95e8da7c0bdcb6b5e97985caaf7f7d553ecc/internal/sqlquery/scraper.go#L80) is here?

File: receiver/sqlqueryreceiver/logs_receiver_test.go [hunk 3]
```diff
@@ -117,3 +119,41 @@ func TestLogsQueryReceiver_BothDatasourceFields(t *testing.T) {
 	require.NoError(t, err)
 	require.NoError(t, receiver.Shutdown(ctx))
 }
+
+func TestLogsQueryReceiver_NullValue(t *testing.T) {
+	fakeClient := &sqlquery.FakeDBClient{
+		StringMaps: [][]sqlquery.StringMap{
+			{{"col1": "42"}},
```
Comment (crobert-1) [inline receiver/sqlqueryreceiver/logs_receiver_test.go]: Maybe move col1 and 42 to variables since they're being set and checked?

**Review by crobert-1 — APPROVED** [review]

**Comment by crobert-1** [comment]
Thanks for filing the issue and fixing as well, @mrsillydog, really appreciate your help!

File: receiver/sqlqueryreceiver/logs_receiver.go (hunk 2 above)
Comment (mrsillydog) [reply receiver/sqlqueryreceiver/logs_receiver.go]: Error strings in go are idiomatically not capitalized, but I've made them consistent with `scraper: %w`
