### PR TITLE
fix(ottl): enforce valid types for setters in contexts

### LINKED ISSUE #40198: [pkg/ottl] OTTL contexts paths are ignoring failed setters executions
### Component(s)

pkg/ottl

### Describe the issue you're reporting

Currently, many OTTL contexts path setters are ignoring the value type assertion failures, which I'm not sure if it was a design decision, or some bad pattern that was copied from one context to another. 

For example, the following statements would  NOT fail the execution, and IMO, it should, as `severity_number` must be an `int64`, and not an `string`:

```yaml
log_statements:
 - context: log
   statements:
    - set(severity_number, "bar")
```

It happens because those paths setters are ignoring type assertion failures, and are not returning any error, making the set operation silently fail:

```go
func accessSeverityNumber[K Context]() ottl.StandardGetSetter[K] {
	return ottl.StandardGetSetter[K]{
                // ...
		Setter: func(_ context.Context, tCtx K, val any) error {
			if i, ok := val.(int64); ok {
				tCtx.GetLogRecord().SetSeverityNumber(plog.SeverityNumber(i))
			}
			return nil
		},
	}
}
```

I understand that changing this behavior would be a kind of breaking change (noop statements doing that would starting failing). So I'm wondering, Do we have any reason for that work like this? If we don't, I really think we should start fixing them and propagating some error when those set operation fails to execute.

### PR DESCRIPTION
**Pull request by jsvd**
#### Description
Introduce a common utility to check for the expected type and returns a consistent error message.
Also applies the use of this utility to ctxscope, ctxlog and ctxmetric.

#### Link to tracking issue
Fixes #40198

#### Testing
Adds testing for the new utility, will address any tests whose behavior is changed by this propagation of error that didn't exist before.

#### TODO
As it is now, the PR changes some but not all setters, I can either apply them all here or create a followup PR with more refactorings.

#### Alternate designs
Introducing a new helper in ctxerror was considered but it can be done at a later stage, as it requires consensus on the set of metadata that such helper would require or optional (e.g. context name, path segment).

### CODE REVIEW

File: pkg/ottl/contexts/internal/ctxutil/typecheck.go [hunk 1]
```diff
@@ -0,0 +1,16 @@
+// Copyright The OpenTelemetry Authors
+// SPDX-License-Identifier: Apache-2.0
+
+package ctxutil // import "github.com/open-telemetry/opentelemetry-collector-contrib/pkg/ottl/contexts/internal/ctxutil"
+
+import "fmt"
+
+// ExpectType ensures val can be asserted to T, returning a descriptive error when it cannot.
+func ExpectType[T any](val any) (T, error) {
+	var zero T
```
Comment (TylerHelmuth) [inline pkg/ottl/contexts/internal/ctxutil/typecheck.go]: Since it's only used inside the if statement, lets move the initialization there.

**Review by TylerHelmuth — APPROVED** [review]
1 nit, otherwise looks good

**Comment by jsvd** [comment]
@TylerHelmuth nit addressed and rebased, ready to go!
I will open a subsequent PR that applies this to the remaining applicable contexts:

```
       pkg/ottl/contexts/internal/ctxdatapoint/datapoint.go
       pkg/ottl/contexts/internal/ctxprofile/profile.go
       pkg/ottl/contexts/internal/ctxprofilesample/profilesample.go
       pkg/ottl/contexts/internal/ctxresource/resource.go
       pkg/ottl/contexts/internal/ctxspan/span.go
       pkg/ottl/contexts/internal/ctxspanevent/span_events.go
```

**Review by odubajDT — APPROVED** [review]

**Comment by jsvd** [comment]
@TylerHelmuth 👋 could we get this merged? thanks!

**Review by atoulme — APPROVED** [review]

**Comment by atoulme** [comment]
You addressed the nit, merging.
