### PR TITLE
[receiver/prometheusremotewrite] flaky test

### LINKED ISSUE #36654: [receiver/prometheusremotewrite] Flaky test
### Component(s)

receiver/prometheusremotewrite

### Describe the issue you're reporting

I've just noticed we have some flaky tests in main: https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/12146357038/job/33870088465

```
=== FAIL: . TestComponentLifecycle/metrics-lifecycle (0.00s)
    generated_component_test.go:65: 
        	Error Trace:	/home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/receiver/prometheusremotewritereceiver/generated_component_test.go:65
        	Error:      	Received unexpected error:
        	            	failed to create prometheus remote-write listener: listen tcp 127.0.0.1:9090: bind: address already in use
        	Test:       	TestComponentLifecycle/metrics-lifecycle

=== FAIL: . TestComponentLifecycle (0.00s)

=== FAIL: . TestHandlePRWContentTypeNegotiation/no_content_type (0.00s)
    receiver_test.go:90: 
        	Error Trace:	/home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/receiver/prometheusremotewritereceiver/receiver_test.go:90
        	Error:      	Received unexpected error:
        	            	Post "http://localhost:9090/api/v1/write": dial tcp [::1]:9090: connect: connection refused
        	Test:       	TestHandlePRWContentTypeNegotiation/no_content_type

=== FAIL: . TestHandlePRWContentTypeNegotiation (0.00s)
    receiver_test.go:[43](https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/12146357038/job/33870088465#step:7:44): 
        	Error Trace:	/home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/receiver/prometheusremotewritereceiver/receiver_test.go:36
        	            				/home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/receiver/prometheusremotewritereceiver/receiver_test.go:43
        	Error:      	Received unexpected error:
        	            	failed to create prometheus remote-write listener: listen tcp 127.0.0.1:9090: bind: address already in use
        	Test:       	TestHandlePRWContentTypeNegotiation
```

### PR DESCRIPTION
**Pull request by perebaj**
#### Description

Using httptest package instead of starting a real server avoiding port conflicts.

#### Link to tracking issue
Fixes https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/36654

### CODE REVIEW

File: receiver/prometheusremotewritereceiver/receiver_test.go [hunk 1]
```diff
@@ -131,6 +132,85 @@ func TestHandlePRWContentTypeNegotiation(t *testing.T) {
...
+	var compressedBody []byte
+	snappy.Encode(compressedBody, pBuf.Bytes())
+
+	// no content type
+	expectedCode := http.StatusUnsupportedMediaType
+
+	req := httptest.NewRequest(http.MethodPost, "/api/v1/write", bytes.NewBuffer(compressedBody))
+	req.Header.Set("Content-Encoding", "snappy")
+	req.Header.Set("Content-Type", "")
+	w := httptest.NewRecorder()
```
Comment (perebaj) [inline receiver/prometheusremotewritereceiver/receiver_test.go:150]: @ArthurSens It's not done yet. It's just an idea. Did you see any problem to use `httptest` instead of call `setupServer`? Like you did here ⬇️

https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/d74ba549cdedb249a58b26ea39fa1644e3786d1e/receiver/prometheusremotewritereceiver/receiver_test.go#L74-L75

httptest take care of a bunch of things. Including the creation of a valid base url and ports. For that specific case where we are just validating the expected `statusCode` given a header, I think that would be a good approach to avoid the `flaky test thing`. WDYT?

Comment (perebaj) [reply receiver/prometheusremotewritereceiver/receiver_test.go:150]: @pjanotti some constraint about this approach?

File: .chloggen/prw-flaky-test.yaml [hunk 2]
```diff
@@ -0,0 +1,27 @@
+# Use this changelog template to create an entry for release notes.
```
Comment (ArthurSens) [inline .chloggen/prw-flaky-test.yaml:1]: I know I asked you to add this changelog entry, but I think the correct option is to add the `skip changelog` label

File: receiver/prometheusremotewritereceiver/receiver_test.go (hunk 1 above)
Comment (ArthurSens) [reply receiver/prometheusremotewritereceiver/receiver_test.go]: Yes, I like your approach! Let's do it!

**Comment by ArthurSens** [comment]
/label "Skip Changelog"

not sure if this will work, let's see

File: .chloggen/prw-flaky-test.yaml (hunk 2 above)
Comment (perebaj) [reply .chloggen/prw-flaky-test.yaml:1]: Should I remove it, then?

Comment (ArthurSens) [reply .chloggen/prw-flaky-test.yaml:1]: yes please

**Comment by perebaj** [comment]
> /label "Skip Changelog"
> 
> not sure if this will work, let's see

I think that you need to set this label

image

**Review by ArthurSens — APPROVED** [review]

**Review by pjanotti — APPROVED** [review]

**Review by songy23 — APPROVED** [review]
