### PR TITLE
[exporter/loadbalancing] Add top level sending_queue, retry_on_failure and timeout settings

### LINKED ISSUE #16826: [loadbalancing-exporter] enabling exporterhelper persistent queue breaks loadbalancer exporting
### Component(s)

exporter/loadbalancing

## Description

Enabling [persistent queuing](https://github.com/open-telemetry/opentelemetry-collector/tree/main/exporter/exporterhelper#persistent-queue) on an otlp exporter configured in the [loadbalancing-exporter](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/exporter/loadbalancingexporter) results in `Sender Failed` warnings from the batch processor and no logs being exported.  When the `sending_queue.storage` configuration option is removed the loadbalancing-exporter works.

It appears that when persistent queuing is enabled the loadbalancing-exporter is only registering the first endpoint in the `hostname` list.

## Steps to Reproduce

1.) Use the test config provided in [loadbalancing-exporter](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/exporter/loadbalancingexporter/README.md)

2.) Add and configure the `storage` extension and add enable the extension in the service configuration.

3.) Enable persistent queuing via `sending_queue.storage` config options.

## Expected Result

Expected results are logs being exported via the loadbalancing-exporter to the backend receivers.

## Actual Result

This config results in errors (listed below) and a failure to export logs.

### Collector version

v0.64.0

## Environment
OS: Debian 11

Otel was installed via deb pkg from releases.

### OpenTelemetry Collector configuration

```yaml
receivers:
  otlp/loadbalancer:
    protocols:
      grpc:
        endpoint: localhost:4317
  otlp/backend-1:
    protocols:
      grpc:
        endpoint: localhost:55690
  otlp/backend-2:
    protocols:
      grpc:
        endpoint: localhost:55700
  otlp/backend-3:
    protocols:
      grpc:
        endpoint: localhost:55710
  otlp/backend-4:
    protocols:
      grpc:
        endpoint: localhost:55720
  filelog:
    include:
      - /var/log/syslog
    start_at: end
    include_file_path: true
    include_file_name: true
    storage: file_storage

processors:
  batch:
    send_batch_size: 10000
    timeout: 200ms

extensions:
  file_storage:
    directory: /var/lib/otelcol
    timeout: 1s
    compaction:
      on_start: true
      on_rebound: true
      directory: /tmp
      max_transaction_size: 65536

exporters:
  logging:
  loadbalancing:
    protocol:
      otlp:
        timeout: 1s
        tls:
          insecure: true
        retry_on_failure:
          enabled: true
          initial_interval: 5s
          max_interval: 30s
          max_elapsed_time: 5m
        sending_queue:
          enabled: true
          storage: file_storage
          num_consumers: 10
          queue_size: 5000
    resolver:
      static:
        hostnames:
        - localhost:55690
        - localhost:55700
        - localhost:55710
        - localhost:55720

service:
  extensions: [file_storage]
  pipelines:
    logs/loadbalancer:
      receivers:
        - filelog
      processors: [batch]
      exporters:
        - loadbalancing
    logs/backend-1:
      receivers:
        - otlp/backend-1
      processors: []
      exporters:
        - logging
    logs/backend-2:
      receivers:
        - otlp/backend-2
      processors: []
      exporters:
        - logging
    logs/backend-3:
      receivers:
        - otlp/backend-3
      processors: []
      exporters:
        - logging
    logs/backend-4:
      receivers:
        - otlp/backend-4
      processors: []
      exporters:
        - logging
```

### Log output

```shell
Dec 08 21:39:10 otel-agent systemd[1]: Started OpenTelemetry Collector Contrib.

Dec 08 21:39:10 otel-agent otelcol-contrib[2229801]: 2022-12-08T21:39:10.713Z        info        service/telemetry.go:110        Setting up own telemetry...
Dec 08 21:39:10 otel-agent otelcol-contrib[2229801]: 2022-12-08T21:39:10.714Z        info        service/telemetry.go:140        Serving Prometheus metrics        {"address": ":8888", "level": "basic"}
Dec 08 21:39:10 otel-agent otelcol-contrib[2229801]: 2022-12-08T21:39:10.714Z        info        components/components.go:30        In development component. May change in the future.        {"kind": "exporter", "data_type": "logs", "name": "logging", "stability": "in development"}
Dec 08 21:39:10 otel-agent otelcol-contrib[2229801]: 2022-12-08T21:39:10.715Z        info        service/service.go:89        Starting otelcol-contrib...        {"Version": "0.64.0", "NumCPU": 1}
Dec 08 21:39:10 otel-agent otelcol-contrib[2229801]: 2022-12-08T21:39:10.715Z        info        extensions/extensions.go:41        Starting extensions...
Dec 08 21:39:10 otel-agent otelcol-contrib[2229801]: 2022-12-08T21:39:10.715Z        info        extensions/extensions.go:44        Extension is starting...        {"kind": "extension", "name": "file_storage"}
Dec 08 21:39:10 otel-agent otelcol-contrib[2229801]: 2022-12-08T21:39:10.715Z        info        extensions/extensions.go:48        Extension started.        {"kind": "extension", "name": "file_storage"}
Dec 08 21:39:10 otel-agent otelcol-contrib[2229801]: 2022-12-08T21:39:10.715Z        info        pipelines/pipelines.go:74        Starting exporters...
Dec 08 21:39:10 otel-agent otelcol-contrib[2229801]: 2022-12-08T21:39:10.715Z        info        pipelines/pipelines.go:78        Exporter is starting...        {"kind": "exporter", "data_type": "logs", "name": "logging"}
Dec 08 21:39:10 otel-agent otelcol-contrib[2229801]: 2022-12-08T21:39:10.715Z        info        pipelines/pipelines.go:82        Exporter started.        {"kind": "exporter", "data_type": "logs", "name": "logging"}
Dec 08 21:39:10 otel-agent otelcol-contrib[2229801]: 2022-12-08T21:39:10.715Z        info        pipelines/pipelines.go:78        Exporter is starting...        {"kind": "exporter", "data_type": "logs", "name": "loadbalancing"}
Dec 08 21:39:10 otel-agent otelcol-contrib[2229801]: 2022-12-08T21:39:10.717Z        info        filestorage/client.go:244        finished compaction        {"kind": "extension", "name": "file_storage", "directory": "/var/lib/otelcol/exporter_otlp__logs", "elapsed": 0.00013827}
Dec 08 21:39:10 otel-agent otelcol-contrib[2229801]: 2022-12-08T21:39:10.720Z        warn        zapgrpc/zapgrpc.go:191        [core] [Channel #1 SubChannel #2] grpc: addrConn.createTransport failed to connect to {
Dec 08 21:39:13 otel-agent otelcol-contrib[2229801]: 2022-12-08T21:39:13.582Z        info        pipelines/pipelines.go:82        Exporter started.        {"kind": "exporter", "data_type": "logs", "name": "loadbalancing"}
Dec 08 21:39:13 otel-agent otelcol-contrib[2229801]: 2022-12-08T21:39:13.582Z        info        pipelines/pipelines.go:86        Starting processors...
Dec 08 21:39:13 otel-agent otelcol-contrib[2229801]: 2022-12-08T21:39:13.582Z        info        pipelines/pipelines.go:90        Processor is starting...        {"kind": "processor", "name": "batch", "pipeline": "logs/loadbalancer"}
Dec 08 21:39:13 otel-agent otelcol-contrib[2229801]: 2022-12-08T21:39:13.582Z        info        pipelines/pipelines.go:94        Processor started.        {"kind": "processor", "name": "batch", "pipeline": "logs/loadbalancer"}
Dec 08 21:39:13 otel-agent otelcol-contrib[2229801]: 2022-12-08T21:39:13.582Z        info        pipelines/pipelines.go:98        Starting receivers...
Dec 08 21:39:13 otel-agent otelcol-contrib[2229801]: 2022-12-08T21:39:13.582Z        info        pipelines/pipelines.go:102        Receiver is starting...        {"kind": "receiver", "name": "otlp/backend-4", "pipeline": "logs"}
Dec 08 21:39:13 otel-agent otelcol-contrib[2229801]: 2022-12-08T21:39:13.582Z        info        otlpreceiver@v0.64.0/otlp.go:71        Starting GRPC server        {"kind": "receiver", "name": "otlp/backend-4", "pipeline": "logs", "endpoint": "localhost:55720"}
Dec 08 21:39:13 otel-agent otelcol-contrib[2229801]: 2022-12-08T21:39:13.582Z        info        pipelines/pipelines.go:106        Receiver started.        {"kind": "receiver", "name": "otlp/backend-4", "pipeline": "logs"}
Dec 08 21:39:13 otel-agent otelcol-contrib[2229801]: 2022-12-08T21:39:13.582Z        info        pipelines/pipelines.go:102        Receiver is starting...        {"kind": "receiver", "name": "otlp/backend-3", "pipeline": "logs"}
Dec 08 21:39:13 otel-agent otelcol-contrib[2229801]: 2022-12-08T21:39:13.582Z        info        otlpreceiver@v0.64.0/otlp.go:71        Starting GRPC server        {"kind": "receiver", "name": "otlp/backend-3", "pipeline": "logs", "endpoint": "localhost:55710"}
Dec 08 21:39:13 otel-agent otelcol-contrib[2229801]: 2022-12-08T21:39:13.583Z        info        pipelines/pipelines.go:106        Receiver started.        {"kind": "receiver", "name": "otlp/backend-3", "pipeline": "logs"}
Dec 08 21:39:13 otel-agent otelcol-contrib[2229801]: 2022-12-08T21:39:13.583Z        info        pipelines/pipelines.go:102        Receiver is starting...        {"kind": "receiver", "name": "otlp/backend-1", "pipeline": "logs"}
Dec 08 21:39:13 otel-agent otelcol-contrib[2229801]: 2022-12-08T21:39:13.583Z        info        otlpreceiver@v0.64.0/otlp.go:71        Starting GRPC server        {"kind": "receiver", "name": "otlp/backend-1", "pipeline": "logs", "endpoint": "localhost:55690"}
Dec 08 21:39:13 otel-agent otelcol-contrib[2229801]: 2022-12-08T21:39:13.583Z        info        pipelines/pipelines.go:106        Receiver started.        {"kind": "receiver", "name": "otlp/backend-1", "pipeline": "logs"}
Dec 08 21:39:13 otel-agent otelcol-contrib[2229801]: 2022-12-08T21:39:13.583Z        info        pipelines/pipelines.go:102        Receiver is starting...        {"kind": "receiver", "name": "otlp/backend-2", "pipeline": "logs"}
Dec 08 21:39:13 otel-agent otelcol-contrib[2229801]: 2022-12-08T21:39:13.583Z        info        otlpreceiver@v0.64.0/otlp.go:71        Starting GRPC server        {"kind": "receiver", "name": "otlp/backend-2", "pipeline": "logs", "endpoint": "localhost:55700"}
Dec 08 21:39:13 otel-agent otelcol-contrib[2229801]: 2022-12-08T21:39:13.583Z        info        pipelines/pipelines.go:106        Receiver started.        {"kind": "receiver", "name": "otlp/backend-2", "pipeline": "logs"}
Dec 08 21:39:13 otel-agent otelcol-contrib[2229801]: 2022-12-08T21:39:13.583Z        info        pipelines/pipelines.go:102        Receiver is starting...        {"kind": "receiver", "name": "filelog", "pipeline": "logs"}
Dec 08 21:39:13 otel-agent otelcol-contrib[2229801]: 2022-12-08T21:39:13.583Z        info        adapter/receiver.go:55        Starting stanza receiver        {"kind": "receiver", "name": "filelog", "pipeline": "logs"}
Dec 08 21:39:13 otel-agent otelcol-contrib[2229801]: 2022-12-08T21:39:13.586Z        info        filestorage/client.go:244        finished compaction        {"kind": "extension", "name": "file_storage", "directory": "/var/lib/otelcol/receiver_filelog_", "elapsed": 0.0002708}
Dec 08 21:39:13 otel-agent otelcol-contrib[2229801]: 2022-12-08T21:39:13.587Z        info        fileconsumer/file.go:312        Resuming from previously known offset(s). 'start_at' setting is not applicable.        {"kind": "receiver", "name": "filelog", "pipeline": "logs", "component": "fileconsumer"}
Dec 08 21:39:13 otel-agent otelcol-contrib[2229801]: 2022-12-08T21:39:13.587Z        info        pipelines/pipelines.go:106        Receiver started.        {"kind": "receiver", "name": "filelog", "pipeline": "logs"}
Dec 08 21:39:13 otel-agent otelcol-contrib[2229801]: 2022-12-08T21:39:13.587Z        info        service/service.go:106        Everything is ready. Begin running and processing data.
Dec 08 21:39:13 otel-agent otelcol-contrib[2229801]: 2022-12-08T21:39:13.788Z        info        fileconsumer/file.go:159        Started watching file        {"kind": "receiver", "name": "filelog", "pipeline": "logs", "component": "fileconsumer", "path": "/var/log/syslog"}
Dec 08 21:39:13 otel-agent otelcol-contrib[2229801]: 2022-12-08T21:39:13.989Z        warn        batchprocessor@v0.64.0/batch_processor.go:178        Sender failed        {"kind": "processor", "name": "batch", "pipeline": "logs/loadbalancer", "error": "couldn't find the exporter for the endpoint \"localhost:55710\""}
Dec 08 21:39:13 otel-agent otelcol-contrib[2229801]: 2022-12-08T21:39:13.997Z        info        LogsExporter        {"kind": "exporter", "data_type": "logs", "name": "logging", "#logs": 100}
Dec 08 21:39:13 otel-agent otelcol-contrib[2229801]: 2022-12-08T21:39:13.999Z        info        LogsExporter        {"kind": "exporter", "data_type": "logs", "name": "logging", "#logs": 12}
Dec 08 21:39:14 otel-agent otelcol-contrib[2229801]: 2022-12-08T21:39:14.194Z        warn        batchprocessor@v0.64.0/batch_processor.go:178        Sender failed        {"kind": "processor", "name": "batch", "pipeline": "logs/loadbalancer", "error": "couldn't find the exporter for the endpoint \"localhost:55720\"; couldn't find the exporter for the endpoint \"localhost:55710\"", "errorCauses": [{"error": "couldn't find the exporter for the endpoint \"localhost:55720\""}, {"error": "couldn't find the exporter for the endpoint \"localhost:55710\""}]}
Dec 08 21:39:14 otel-agent otelcol-contrib[2229801]: 2022-12-08T21:39:14.394Z        warn        batchprocessor@v0.64.0/batch_processor.go:178        Sender failed        {"kind": "processor", "name": "batch", "pipeline": "logs/loadbalancer", "error": "couldn't find the exporter for the endpoint \"localhost:55710\""}
Dec 08 21:39:14 otel-agent otelcol-contrib[2229801]: 2022-12-08T21:39:14.596Z        warn        batchprocessor@v0.64.0/batch_processor.go:178        Sender failed        {"kind": "processor", "name": "batch", "pipeline": "logs/loadbalancer", "error": "couldn't find the exporter for the endpoint \"localhost:55710\""}
Dec 08 21:39:14 otel-agent otelcol-contrib[2229801]: 2022-12-08T21:39:14.797Z        warn        batchprocessor@v0.64.0/batch_processor.go:178        Sender failed        {"kind": "processor", "name": "batch", "pipeline": "logs/loadbalancer", "error": "couldn't find the exporter for the endpoint \"localhost:55710\""}
Dec 08 21:39:14 otel-agent otelcol-contrib[2229801]: 2022-12-08T21:39:14.999Z        info        LogsExporter        {"kind": "exporter", "data_type": "logs", "name": "logging", "#logs": 1}
Dec 08 21:39:15 otel-agent otelcol-contrib[2229801]: 2022-12-08T21:39:15.199Z        warn        batchprocessor@v0.64.0/batch_processor.go:178        Sender failed        {"kind": "processor", "name": "batch", "pipeline": "logs/loadbalancer", "error": "couldn't find the exporter for the endpoint \"localhost:55720\""}
Dec 08 21:39:15 otel-agent otelcol-contrib[2229801]: 2022-12-08T21:39:15.400Z        warn        batchprocessor@v0.64.0/batch_processor.go:178        Sender failed        {"kind": "processor", "name": "batch", "pipeline": "logs/loadbalancer", "error": "couldn't find the exporter for the endpoint \"localhost:55720\""}
Dec 08 21:39:15 otel-agent otelcol-contrib[2229801]: 2022-12-08T21:39:15.602Z        warn        batchprocessor@v0.64.0/batch_processor.go:178        Sender failed        {"kind": "processor", "name": "batch", "pipeline": "logs/loadbalancer", "error": "couldn't find the exporter for the endpoint \"localhost:55700\""}
Dec 08 21:39:15 otel-agent otelcol-contrib[2229801]: 2022-12-08T21:39:15.802Z        warn        batchprocessor@v0.64.0/batch_processor.go:178        Sender failed        {"kind": "processor", "name": "batch", "pipeline": "logs/loadbalancer", "error": "couldn't find the exporter for the endpoint \"localhost:55700\""}
Dec 08 21:39:16 otel-agent otelcol-contrib[2229801]: 2022-12-08T21:39:16.004Z        info        LogsExporter        {"kind": "exporter", "data_type": "logs", "name": "logging", "#logs": 1}
Dec 08 21:39:16 otel-agent otelcol-contrib[2229801]: 2022-12-08T21:39:16.205Z        info        LogsExporter        {"kind": "exporter", "data_type": "logs", "name": "logging", "#logs": 1}
Dec 08 21:39:39 otel-agent otelcol-contrib[2229801]: 2022-12-08T21:39:39.084Z        warn        batchprocessor@v0.64.0/batch_processor.go:178        Sender failed        {"kind": "processor", "name": "batch", "pipeline": "logs/loadbalancer", "error": "couldn't find the exporter for the endpoint \"localhost:55710\""}
Dec 08 21:39:39 otel-agent otelcol-contrib[2229801]: 2022-12-08T21:39:39.287Z        info        LogsExporter        {"kind": "exporter", "data_type": "logs", "name": "logging", "#logs": 1}
Dec 08 21:39:39 otel-agent otelcol-contrib[2229801]: 2022-12-08T21:39:39.488Z        info        LogsExporter        {"kind": "exporter", "data_type": "logs", "name": "logging", "#logs": 1}
Dec 08 21:40:09 otel-agent otelcol-contrib[2229801]: 2022-12-08T21:40:09.183Z        warn        batchprocessor@v0.64.0/batch_processor.go:178        Sender failed        {"kind": "processor", "name": "batch", "pipeline": "logs/loadbalancer", "error": "couldn't find the exporter for the endpoint \"localhost:55710\""}
Dec 08 21:40:09 otel-agent otelcol-contrib[2229801]: 2022-12-08T21:40:09.386Z        info        LogsExporter        {"kind": "exporter", "data_type": "logs", "name": "logging", "#logs": 1}
Dec 08 21:40:09 otel-agent otelcol-contrib[2229801]: 2022-12-08T21:40:09.587Z        info        LogsExporter        {"kind": "exporter", "data_type": "logs", "name": "logging", "#logs": 1}
Dec 08 21:40:09 otel-agent otelcol-contrib[2229801]: 2022-12-08T21:40:09.788Z        warn        batchprocessor@v0.64.0/batch_processor.go:178        Sender failed        {"kind": "processor", "name": "batch", "pipeline": "logs/loadbalancer", "error": "couldn't find the exporter for the endpoint \"localhost:55720\""}
Dec 08 21:40:09 otel-agent otelcol-contrib[2229801]: 2022-12-08T21:40:09.989Z        warn        batchprocessor@v0.64.0/batch_processor.go:178        Sender failed        {"kind": "processor", "name": "batch", "pipeline": "logs/loadbalancer", "error": "couldn't find the exporter for the endpoint \"localhost:55720\""}
Dec 08 21:40:10 otel-agent otelcol-contrib[2229801]: 2022-12-08T21:40:10.192Z        warn        batchprocessor@v0.64.0/batch_processor.go:178        Sender failed        {"kind": "processor", "name": "batch", "pipeline": "logs/loadbalancer", "error": "couldn't find the exporter for the endpoint \"localhost:55710\""}
Dec 08 21:40:10 otel-agent otelcol-contrib[2229801]: 2022-12-08T21:40:10.392Z        info        LogsExporter        {"kind": "exporter", "data_type": "logs", "name": "logging", "#logs": 1}
Dec 08 21:40:10 otel-agent otelcol-contrib[2229801]: 2022-12-08T21:40:10.592Z        warn        batchprocessor@v0.64.0/batch_processor.go:178        Sender failed        {"kind": "processor", "name": "batch", "pipeline": "logs/loadbalancer", "error": "couldn't find the exporter for the endpoint \"localhost:55710\""}
Dec 08 21:40:10 otel-agent otelcol-contrib[2229801]: 2022-12-08T21:40:10.793Z        warn        batchprocessor@v0.64.0/batch_processor.go:178        Sender failed        {"kind": "processor", "name": "batch", "pipeline": "logs/loadbalancer", "error": "couldn't find the exporter for the endpoint \"localhost:55710\""}
Dec 08 21:40:10 otel-agent otelcol-contrib[2229801]: 2022-12-08T21:40:10.995Z        warn        batchprocessor@v0.64.0/batch_processor.go:178        Sender failed        {"kind": "processor", "name": "batch", "pipeline": "logs/loadbalancer", "error": "couldn't find the exporter for the endpoint \"localhost:55720\""}
Dec 08 21:40:11 otel-agent otelcol-contrib[2229801]: 2022-12-08T21:40:11.197Z        warn        batchprocessor@v0.64.0/batch_processor.go:178        Sender failed        {"kind": "processor", "name": "batch", "pipeline": "logs/loadbalancer", "error": "couldn't find the exporter for the endpoint \"localhost:55720\""}
Dec 08 21:40:11 otel-agent otelcol-contrib[2229801]: 2022-12-08T21:40:11.398Z        warn        batchprocessor@v0.64.0/batch_processor.go:178        Sender failed        {"kind": "processor", "name": "batch", "pipeline": "logs/loadbalancer", "error": "couldn't find the exporter for the endpoint \"localhost:55710\""}
Dec 08 21:40:11 otel-agent otelcol-contrib[2229801]: 2022-12-08T21:40:11.598Z        warn        batchprocessor@v0.64.0/batch_processor.go:178        Sender failed        {"kind": "processor", "name": "batch", "pipeline": "logs/loadbalancer", "error": "couldn't find the exporter for the endpoint \"localhost:55710\""}
Dec 08 21:40:11 otel-agent otelcol-contrib[2229801]: 2022-12-08T21:40:11.800Z        warn        batchprocessor@v0.64.0/batch_processor.go:178        Sender failed        {"kind": "processor", "name": "batch", "pipeline": "logs/loadbalancer", "error": "couldn't find the exporter for the endpoint \"localhost:55710\""}
Dec 08 21:40:12 otel-agent otelcol-contrib[2229801]: 2022-12-08T21:40:12.001Z        info        LogsExporter        {"kind": "exporter", "data_type": "logs", "name": "logging", "#logs": 1}
Dec 08 21:40:12 otel-agent otelcol-contrib[2229801]: 2022-12-08T21:40:12.201Z        warn        batchprocessor@v0.64.0/batch_processor.go:178        Sender failed        {"kind": "processor", "name": "batch", "pipeline": "logs/loadbalancer", "error": "couldn't find the exporter for the endpoint \"localhost:55720\""}
Dec 08 21:40:12 otel-agent otelcol-contrib[2229801]: 2022-12-08T21:40:12.402Z        warn        batchprocessor@v0.64.0/batch_processor.go:178        Sender failed        {"kind": "processor", "name": "batch", "pipeline": "logs/loadbalancer", "error": "couldn't find the exporter for the endpoint \"localhost:55700\""}
Dec 08 21:40:12 otel-agent otelcol-contrib[2229801]: 2022-12-08T21:40:12.603Z        warn        batchprocessor@v0.64.0/batch_processor.go:178        Sender failed        {"kind": "processor", "name": "batch", "pipeline": "logs/loadbalancer", "error": "couldn't find the exporter for the endpoint \"localhost:55700\""}
Dec 08 21:40:12 otel-agent otelcol-contrib[2229801]: 2022-12-08T21:40:12.804Z        warn        batchprocessor@v0.64.0/batch_processor.go:178        Sender failed        {"kind": "processor", "name": "batch", "pipeline": "logs/loadbalancer", "error": "couldn't find the exporter for the endpoint \"localhost:55700\""}
Dec 08 21:40:13 otel-agent otelcol-contrib[2229801]: 2022-12-08T21:40:13.006Z        info        LogsExporter        {"kind": "exporter", "data_type": "logs", "name": "logging", "#logs": 1}
Dec 08 21:40:13 otel-agent otelcol-contrib[2229801]: 2022-12-08T21:40:13.205Z        warn        batchprocessor@v0.64.0/batch_processor.go:178        Sender failed        {"kind": "processor", "name": "batch", "pipeline": "logs/loadbalancer", "error": "couldn't find the exporter for the endpoint \"localhost:55720\""}
Dec 08 21:40:13 otel-agent otelcol-contrib[2229801]: 2022-12-08T21:40:13.407Z        warn        batchprocessor@v0.64.0/batch_processor.go:178        Sender failed        {"kind": "processor", "name": "batch", "pipeline": "logs/loadbalancer", "error": "couldn't find the exporter for the endpoint \"localhost:55700\""}
Dec 08 21:40:13 otel-agent otelcol-contrib[2229801]: 2022-12-08T21:40:13.608Z        warn        batchprocessor@v0.64.0/batch_processor.go:178        Sender failed        {"kind": "processor", "name": "batch", "pipeline": "logs/loadbalancer", "error": "couldn't find the exporter for the endpoint \"localhost:55700\""}
Dec 08 21:40:13 otel-agent otelcol-contrib[2229801]: 2022-12-08T21:40:13.809Z        warn        batchprocessor@v0.64.0/batch_processor.go:178        Sender failed        {"kind": "processor", "name": "batch", "pipeline": "logs/loadbalancer", "error": "couldn't find the exporter for the endpoint \"localhost:55720\""}
Dec 08 21:40:14 otel-agent otelcol-contrib[2229801]: 2022-12-08T21:40:14.009Z        warn        batchprocessor@v0.64.0/batch_processor.go:178        Sender failed        {"kind": "processor", "name": "batch", "pipeline": "logs/loadbalancer", "error": "couldn't find the exporter for the endpoint \"localhost:55700\""}
Dec 08 21:40:14 otel-agent otelcol-contrib[2229801]: 2022-12-08T21:40:14.211Z        warn        batchprocessor@v0.64.0/batch_processor.go:178        Sender failed        {"kind": "processor", "name": "batch", "pipeline": "logs/loadbalancer", "error": "couldn't find the exporter for the endpoint \"localhost:55720\""}
Dec 08 21:40:14 otel-agent otelcol-contrib[2229801]: 2022-12-08T21:40:14.413Z        info        LogsExporter        {"kind": "exporter", "data_type": "logs", "name": "logging", "#logs": 1}
Dec 08 21:40:14 otel-agent otelcol-contrib[2229801]: 2022-12-08T21:40:14.613Z        info        LogsExporter        {"kind": "exporter", "data_type": "logs", "name": "logging", "#logs": 1}
Dec 08 21:40:39 otel-agent otelcol-contrib[2229801]: 2022-12-08T21:40:39.107Z        warn        batchprocessor@v0.64.0/batch_processor.go:178        Sender failed        {"kind": "processor", "name": "batch", "pipeline": "logs/loadbalancer", "error": "couldn't find the exporter for the endpoint \"localhost:55720\""}
Dec 08 21:40:39 otel-agent otelcol-contrib[2229801]: 2022-12-08T21:40:39.308Z        warn        batchprocessor@v0.64.0/batch_processor.go:178        Sender failed        {"kind": "processor", "name": "batch", "pipeline": "logs/loadbalancer", "error": "couldn't find the exporter for the endpoint \"localhost:55700\""}
Dec 08 21:40:39 otel-agent otelcol-contrib[2229801]: 2022-12-08T21:40:39.509Z        info        LogsExporter        {"kind": "exporter", "data_type": "logs", "name": "logging", "#logs": 1}
Dec 08 21:40:39 otel-agent otelcol-contrib[2229801]: 2022-12-08T21:40:39.710Z        warn        batchprocessor@v0.64.0/batch_processor.go:178        Sender failed        {"kind": "processor", "name": "batch", "pipeline": "logs/loadbalancer", "error": "couldn't find the exporter for the endpoint \"localhost:55720\""}
Dec 08 21:40:39 otel-agent otelcol-contrib[2229801]: 2022-12-08T21:40:39.912Z        info        LogsExporter        {"kind": "exporter", "data_type": "logs", "name": "logging", "#logs": 1}
Dec 08 21:40:40 otel-agent otelcol-contrib[2229801]: 2022-12-08T21:40:40.113Z        warn        batchprocessor@v0.64.0/batch_processor.go:178        Sender failed        {"kind": "processor", "name": "batch", "pipeline": "logs/loadbalancer", "error": "couldn't find the exporter for the endpoint \"localhost:55720\""}
Dec 08 21:40:40 otel-agent otelcol-contrib[2229801]: 2022-12-08T21:40:40.314Z        warn        batchprocessor@v0.64.0/batch_processor.go:178        Sender failed        {"kind": "processor", "name": "batch", "pipeline": "logs/loadbalancer", "error": "couldn't find the exporter for the endpoint \"localhost:55710\""}
Dec 08 21:40:40 otel-agent otelcol-contrib[2229801]: 2022-12-08T21:40:40.515Z        warn        batchprocessor@v0.64.0/batch_processor.go:178        Sender failed        {"kind": "processor", "name": "batch", "pipeline": "logs/loadbalancer", "error": "couldn't find the exporter for the endpoint \"localhost:55700\""}
Dec 08 21:40:40 otel-agent otelcol-contrib[2229801]: 2022-12-08T21:40:40.716Z        warn        batchprocessor@v0.64.0/batch_processor.go:178        Sender failed        {"kind": "processor", "name": "batch", "pipeline": "logs/loadbalancer", "error": "couldn't find the exporter for the endpoint \"localhost:55710\""}
Dec 08 21:40:40 otel-agent otelcol-contrib[2229801]: 2022-12-08T21:40:40.917Z        warn        batchprocessor@v0.64.0/batch_processor.go:178        Sender failed        {"kind": "processor", "name": "batch", "pipeline": "logs/loadbalancer", "error": "couldn't find the exporter for the endpoint \"localhost:55700\""}
Dec 08 21:40:41 otel-agent otelcol-contrib[2229801]: 2022-12-08T21:40:41.118Z        warn        batchprocessor@v0.64.0/batch_processor.go:178        Sender failed        {"kind": "processor", "name": "batch", "pipeline": "logs/loadbalancer", "error": "couldn't find the exporter for the endpoint \"localhost:55700\""}
Dec 08 21:40:41 otel-agent otelcol-contrib[2229801]: 2022-12-08T21:40:41.320Z        warn        batchprocessor@v0.64.0/batch_processor.go:178        Sender failed        {"kind": "processor", "name": "batch", "pipeline": "logs/loadbalancer", "error": "couldn't find the exporter for the endpoint \"localhost:55720\""}
Dec 08 21:40:41 otel-agent otelcol-contrib[2229801]: 2022-12-08T21:40:41.521Z        warn        batchprocessor@v0.64.0/batch_processor.go:178        Sender failed        {"kind": "processor", "name": "batch", "pipeline": "logs/loadbalancer", "error": "couldn't find the exporter for the endpoint \"localhost:55700\""}
Dec 08 21:40:41 otel-agent otelcol-contrib[2229801]: 2022-12-08T21:40:41.724Z        info        LogsExporter        {"kind": "exporter", "data_type": "logs", "name": "logging", "#logs": 1}
Dec 08 21:40:41 otel-agent otelcol-contrib[2229801]: 2022-12-08T21:40:41.923Z        warn        batchprocessor@v0.64.0/batch_processor.go:178        Sender failed        {"kind": "processor", "name": "batch", "pipeline": "logs/loadbalancer", "error": "couldn't find the exporter for the endpoint \"localhost:55700\""}
Dec 08 21:40:42 otel-agent otelcol-contrib[2229801]: 2022-12-08T21:40:42.124Z        warn        batchprocessor@v0.64.0/batch_processor.go:178        Sender failed        {"kind": "processor", "name": "batch", "pipeline": "logs/loadbalancer", "error": "couldn't find the exporter for the endpoint \"localhost:55710\""}
Dec 08 21:40:42 otel-agent otelcol-contrib[2229801]: 2022-12-08T21:40:42.325Z        warn        batchprocessor@v0.64.0/batch_processor.go:178        Sender failed        {"kind": "processor", "name": "batch", "pipeline": "logs/loadbalancer", "error": "couldn't find the exporter for the endpoint \"localhost:55710\""}
Dec 08 21:40:42 otel-agent otelcol-contrib[2229801]: 2022-12-08T21:40:42.526Z        warn        batchprocessor@v0.64.0/batch_processor.go:178        Sender failed        {"kind": "processor", "name": "batch", "pipeline": "logs/loadbalancer", "error": "couldn't find the exporter for the endpoint \"localhost:55700\""}
Dec 08 21:40:42 otel-agent otelcol-contrib[2229801]: 2022-12-08T21:40:42.727Z        warn        batchprocessor@v0.64.0/batch_processor.go:178        Sender failed        {"kind": "processor", "name": "batch", "pipeline": "logs/loadbalancer", "error": "couldn't find the exporter for the endpoint \"localhost:55720\""}
Dec 08 21:40:42 otel-agent otelcol-contrib[2229801]: 2022-12-08T21:40:42.929Z        warn        batchprocessor@v0.64.0/batch_processor.go:178        Sender failed        {"kind": "processor", "name": "batch", "pipeline": "logs/loadbalancer", "error": "couldn't find the exporter for the endpoint \"localhost:55720\""}
Dec 08 21:40:43 otel-agent otelcol-contrib[2229801]: 2022-12-08T21:40:43.129Z        warn        batchprocessor@v0.64.0/batch_processor.go:178        Sender failed        {"kind": "processor", "name": "batch", "pipeline": "logs/loadbalancer", "error": "couldn't find the exporter for the endpoint \"localhost:55700\""}
Dec 08 21:40:43 otel-agent otelcol-contrib[2229801]: 2022-12-08T21:40:43.331Z        warn        batchprocessor@v0.64.0/batch_processor.go:178        Sender failed        {"kind": "processor", "name": "batch", "pipeline": "logs/loadbalancer", "error": "couldn't find the exporter for the endpoint \"localhost:55720\""}
Dec 08 21:40:43 otel-agent otelcol-contrib[2229801]: 2022-12-08T21:40:43.532Z        warn        batchprocessor@v0.64.0/batch_processor.go:178        Sender failed        {"kind": "processor", "name": "batch", "pipeline": "logs/loadbalancer", "error": "couldn't find the exporter for the endpoint \"localhost:55700\""}
Dec 08 21:40:43 otel-agent otelcol-contrib[2229801]: 2022-12-08T21:40:43.734Z        warn        batchprocessor@v0.64.0/batch_processor.go:178        Sender failed        {"kind": "processor", "name": "batch", "pipeline": "logs/loadbalancer", "error": "couldn't find the exporter for the endpoint \"localhost:55710\""}
Dec 08 21:40:43 otel-agent otelcol-contrib[2229801]: 2022-12-08T21:40:43.936Z        info        LogsExporter        {"kind": "exporter", "data_type": "logs", "name": "logging", "#logs": 1}
Dec 08 21:40:44 otel-agent otelcol-contrib[2229801]: 2022-12-08T21:40:44.136Z        warn        batchprocessor@v0.64.0/batch_processor.go:178        Sender failed        {"kind": "processor", "name": "batch", "pipeline": "logs/loadbalancer", "error": "couldn't find the exporter for the endpoint \"localhost:55700\""}
Dec 08 21:40:44 otel-agent otelcol-contrib[2229801]: 2022-12-08T21:40:44.337Z        warn        batchprocessor@v0.64.0/batch_processor.go:178        Sender failed        {"kind": "processor", "name": "batch", "pipeline": "logs/loadbalancer", "error": "couldn't find the exporter for the endpoint \"localhost:55700\""}
Dec 08 21:40:44 otel-agent otelcol-contrib[2229801]: 2022-12-08T21:40:44.538Z        warn        batchprocessor@v0.64.0/batch_processor.go:178        Sender failed        {"kind": "processor", "name": "batch", "pipeline": "logs/loadbalancer", "error": "couldn't find the exporter for the endpoint \"localhost:55710\""}
Dec 08 21:40:44 otel-agent otelcol-contrib[2229801]: 2022-12-08T21:40:44.739Z        warn        batchprocessor@v0.64.0/batch_processor.go:178        Sender failed        {"kind": "processor", "name": "batch", "pipeline": "logs/loadbalancer", "error": "couldn't find the exporter for the endpoint \"localhost:55720\""}
Dec 08 21:40:44 otel-agent otelcol-contrib[2229801]: 2022-12-08T21:40:44.940Z        warn        batchprocessor@v0.64.0/batch_processor.go:178        Sender failed        {"kind": "processor", "name": "batch", "pipeline": "logs/loadbalancer", "error": "couldn't find the exporter for the endpoint \"localhost:55720\""}
Dec 08 21:40:45 otel-agent otelcol-contrib[2229801]: 2022-12-08T21:40:45.142Z        warn        batchprocessor@v0.64.0/batch_processor.go:178        Sender failed        {"kind": "processor", "name": "batch", "pipeline": "logs/loadbalancer", "error": "couldn't find the exporter for the endpoint \"localhost:55710\""}
Dec 08 21:40:45 otel-agent otelcol-contrib[2229801]: 2022-12-08T21:40:45.342Z        info        LogsExporter        {"kind": "exporter", "data_type": "logs", "name": "logging", "#logs": 1}
Dec 08 21:40:45 otel-agent otelcol-contrib[2229801]: 2022-12-08T21:40:45.542Z        warn        batchprocessor@v0.64.0/batch_processor.go:178        Sender failed        {"kind": "processor", "name": "batch", "pipeline": "logs/loadbalancer", "error": "couldn't find the exporter for the endpoint \"localhost:55710\""}
Dec 08 21:40:45 otel-agent otelcol-contrib[2229801]: 2022-12-08T21:40:45.744Z        warn        batchprocessor@v0.64.0/batch_processor.go:178        Sender failed        {"kind": "processor", "name": "batch", "pipeline": "logs/loadbalancer", "error": "couldn't find the exporter for the endpoint \"localhost:55700\""}
Dec 08 21:40:45 otel-agent otelcol-contrib[2229801]: 2022-12-08T21:40:45.945Z        warn        batchprocessor@v0.64.0/batch_processor.go:178        Sender failed        {"kind": "processor", "name": "batch", "pipeline": "logs/loadbalancer", "error": "couldn't find the exporter for the endpoint \"localhost:55710\""}
Dec 08 21:40:46 otel-agent otelcol-contrib[2229801]: 2022-12-08T21:40:46.146Z        warn        batchprocessor@v0.64.0/batch_processor.go:178        Sender failed        {"kind": "processor", "name": "batch", "pipeline": "logs/loadbalancer", "error": "couldn't find the exporter for the endpoint \"localhost:55720\""}
Dec 08 21:40:46 otel-agent otelcol-contrib[2229801]: 2022-12-08T21:40:46.347Z        warn        batchprocessor@v0.64.0/batch_processor.go:178        Sender failed        {"kind": "processor", "name": "batch", "pipeline": "logs/loadbalancer", "error": "couldn't find the exporter for the endpoint \"localhost:55710\""}
Dec 08 21:40:46 otel-agent otelcol-contrib[2229801]: 2022-12-08T21:40:46.547Z        warn        batchprocessor@v0.64.0/batch_processor.go:178        Sender failed        {"kind": "processor", "name": "batch", "pipeline": "logs/loadbalancer", "error": "couldn't find the exporter for the endpoint \"localhost:55720\""}
Dec 08 21:40:46 otel-agent otelcol-contrib[2229801]: 2022-12-08T21:40:46.748Z        warn        batchprocessor@v0.64.0/batch_processor.go:178        Sender failed        {"kind": "processor", "name": "batch", "pipeline": "logs/loadbalancer", "error": "couldn't find the exporter for the endpoint \"localhost:55720\""}
Dec 08 21:40:46 otel-agent otelcol-contrib[2229801]: 2022-12-08T21:40:46.951Z        info        LogsExporter        {"kind": "exporter", "data_type": "logs", "name": "logging", "#logs": 1}
Dec 08 21:40:47 otel-agent otelcol-contrib[2229801]: 2022-12-08T21:40:47.150Z        warn        batchprocessor@v0.64.0/batch_processor.go:178        Sender failed        {"kind": "processor", "name": "batch", "pipeline": "logs/loadbalancer", "error": "couldn't find the exporter for the endpoint \"localhost:55710\""}
Dec 08 21:40:47 otel-agent otelcol-contrib[2229801]: 2022-12-08T21:40:47.351Z        warn        batchprocessor@v0.64.0/batch_processor.go:178        Sender failed        {"kind": "processor", "name": "batch", "pipeline": "logs/loadbalancer", "error": "couldn't find the exporter for the endpoint \"localhost:55720\""}
Dec 08 21:40:47 otel-agent otelcol-contrib[2229801]: 2022-12-08T21:40:47.553Z        info        LogsExporter        {"kind": "exporter", "data_type": "logs", "name": "logging", "#logs": 1}
Dec 08 21:40:47 otel-agent otelcol-contrib[2229801]: 2022-12-08T21:40:47.752Z        warn        batchprocessor@v0.64.0/batch_processor.go:178        Sender failed        {"kind": "processor", "name": "batch", "pipeline": "logs/loadbalancer", "error": "couldn't find the exporter for the endpoint \"localhost:55720\""}
Dec 08 21:40:47 otel-agent otelcol-contrib[2229801]: 2022-12-08T21:40:47.953Z        warn        batchprocessor@v0.64.0/batch_processor.go:178        Sender failed        {"kind": "processor", "name": "batch", "pipeline": "logs/loadbalancer", "error": "couldn't find the exporter for the endpoint \"localhost:55720\""}
Dec 08 21:40:48 otel-agent otelcol-contrib[2229801]: 2022-12-08T21:40:48.154Z        info        LogsExporter        {"kind": "exporter", "data_type": "logs", "name": "logging", "#logs": 1}
Dec 08 21:40:48 otel-agent otelcol-contrib[2229801]: 2022-12-08T21:40:48.354Z        warn        batchprocessor@v0.64.0/batch_processor.go:178        Sender failed        {"kind": "processor", "name": "batch", "pipeline": "logs/loadbalancer", "error": "couldn't find the exporter for the endpoint \"localhost:55720\""}
Dec 08 21:40:48 otel-agent otelcol-contrib[2229801]: 2022-12-08T21:40:48.556Z        warn        batchprocessor@v0.64.0/batch_processor.go:178        Sender failed        {"kind": "processor", "name": "batch", "pipeline": "logs/loadbalancer", "error": "couldn't find the exporter for the endpoint \"localhost:55710\""}
Dec 08 21:40:48 otel-agent otelcol-contrib[2229801]: 2022-12-08T21:40:48.756Z        warn        batchprocessor@v0.64.0/batch_processor.go:178        Sender failed        {"kind": "processor", "name": "batch", "pipeline": "logs/loadbalancer", "error": "couldn't find the exporter for the endpoint \"localhost:55700\""}
Dec 08 21:40:48 otel-agent otelcol-contrib[2229801]: 2022-12-08T21:40:48.959Z        info        LogsExporter        {"kind": "exporter", "data_type": "logs", "name": "logging", "#logs": 1}
Dec 08 21:40:49 otel-agent otelcol-contrib[2229801]: 2022-12-08T21:40:49.160Z        info        LogsExporter        {"kind": "exporter", "data_type": "logs", "name": "logging", "#logs": 1}
Dec 08 21:40:49 otel-agent otelcol-contrib[2229801]: 2022-12-08T21:40:49.360Z        warn        batchprocessor@v0.64.0/batch_processor.go:178        Sender failed        {"kind": "processor", "name": "batch", "pipeline": "logs/loadbalancer", "error": "couldn't find the exporter for the endpoint \"localhost:55710\""}
Dec 08 21:40:49 otel-agent otelcol-contrib[2229801]: 2022-12-08T21:40:49.560Z        warn        batchprocessor@v0.64.0/batch_processor.go:178        Sender failed        {"kind": "processor", "name": "batch", "pipeline": "logs/loadbalancer", "error": "couldn't find the exporter for the endpoint \"localhost:55720\""}
Dec 08 21:40:49 otel-agent otelcol-contrib[2229801]: 2022-12-08T21:40:49.762Z        info        LogsExporter        {"kind": "exporter", "data_type": "logs", "name": "logging", "#logs": 1}
Dec 08 21:40:49 otel-agent otelcol-contrib[2229801]: 2022-12-08T21:40:49.962Z        warn        batchprocessor@v0.64.0/batch_processor.go:178        Sender failed        {"kind": "processor", "name": "batch", "pipeline": "logs/loadbalancer", "error": "couldn't find the exporter for the endpoint \"localhost:55710\""}
Dec 08 21:40:50 otel-agent otelcol-contrib[2229801]: 2022-12-08T21:40:50.162Z        warn        batchprocessor@v0.64.0/batch_processor.go:178        Sender failed        {"kind": "processor", "name": "batch", "pipeline": "logs/loadbalancer", "error": "couldn't find the exporter for the endpoint \"localhost:55720\""}
Dec 08 21:40:50 otel-agent otelcol-contrib[2229801]: 2022-12-08T21:40:50.364Z        warn        batchprocessor@v0.64.0/batch_processor.go:178        Sender failed        {"kind": "processor", "name": "batch", "pipeline": "logs/loadbalancer", "error": "couldn't find the exporter for the endpoint \"localhost:55720\""}
Dec 08 21:40:50 otel-agent otelcol-contrib[2229801]: 2022-12-08T21:40:50.565Z        info        LogsExporter        {"kind": "exporter", "data_type": "logs", "name": "logging", "#logs": 1}
Dec 08 21:40:50 otel-agent otelcol-contrib[2229801]: 2022-12-08T21:40:50.765Z        info        LogsExporter        {"kind": "exporter", "data_type": "logs", "name": "logging", "#logs": 1}
Dec 08 21:41:09 otel-agent otelcol-contrib[2229801]: 2022-12-08T21:41:09.050Z        warn        batchprocessor@v0.64.0/batch_processor.go:178        Sender failed        {"kind": "processor", "name": "batch", "pipeline": "logs/loadbalancer", "error": "couldn't find the exporter for the endpoint \"localhost:55720\""}
Dec 08 21:41:09 otel-agent otelcol-contrib[2229801]: 2022-12-08T21:41:09.251Z        warn        batchprocessor@v0.64.0/batch_processor.go:178        Sender failed        {"kind": "processor", "name": "batch", "pipeline": "logs/loadbalancer", "error": "couldn't find the exporter for the endpoint \"localhost:55720\""}
Dec 08 21:41:09 otel-agent otelcol-contrib[2229801]: 2022-12-08T21:41:09.454Z        warn        batchprocessor@v0.64.0/batch_processor.go:178        Sender failed        {"kind": "processor", "name": "batch", "pipeline": "logs/loadbalancer", "error": "couldn't find the exporter for the endpoint \"localhost:55700\""}
Dec 08 21:41:09 otel-agent otelcol-contrib[2229801]: 2022-12-08T21:41:09.656Z        info        LogsExporter        {"kind": "exporter", "data_type": "logs", "name": "logging", "#logs": 1}
Dec 08 21:41:09 otel-agent otelcol-contrib[2229801]: 2022-12-08T21:41:09.856Z        warn        batchprocessor@v0.64.0/batch_processor.go:178        Sender failed        {"kind": "processor", "name": "batch", "pipeline": "logs/loadbalancer", "error": "couldn't find the exporter for the endpoint \"localhost:55710\""}
Dec 08 21:41:10 otel-agent otelcol-contrib[2229801]: 2022-12-08T21:41:10.057Z        warn        batchprocessor@v0.64.0/batch_processor.go:178        Sender failed        {"kind": "processor", "name": "batch", "pipeline": "logs/loadbalancer", "error": "couldn't find the exporter for the endpoint \"localhost:55710\""}
Dec 08 21:41:10 otel-agent otelcol-contrib[2229801]: 2022-12-08T21:41:10.259Z        warn        batchprocessor@v0.64.0/batch_processor.go:178        Sender failed        {"kind": "processor", "name": "batch", "pipeline": "logs/loadbalancer", "error": "couldn't find the exporter for the endpoint \"localhost:55720\""}
Dec 08 21:41:10 otel-agent otelcol-contrib[2229801]: 2022-12-08T21:41:10.459Z        warn        batchprocessor@v0.64.0/batch_processor.go:178        Sender failed        {"kind": "processor", "name": "batch", "pipeline": "logs/loadbalancer", "error": "couldn't find the exporter for the endpoint \"localhost:55710\""}
Dec 08 21:41:10 otel-agent otelcol-contrib[2229801]: 2022-12-08T21:41:10.660Z        warn        batchprocessor@v0.64.0/batch_processor.go:178        Sender failed        {"kind": "processor", "name": "batch", "pipeline": "logs/loadbalancer", "error": "couldn't find the exporter for the endpoint \"localhost:55710\""}
Dec 08 21:41:10 otel-agent otelcol-contrib[2229801]: 2022-12-08T21:41:10.861Z        warn        batchprocessor@v0.64.0/batch_processor.go:178        Sender failed        {"kind": "processor", "name": "batch", "pipeline": "logs/loadbalancer", "error": "couldn't find the exporter for the endpoint \"localhost:55710\""}
Dec 08 21:41:11 otel-agent otelcol-contrib[2229801]: 2022-12-08T21:41:11.061Z        warn        batchprocessor@v0.64.0/batch_processor.go:178        Sender failed        {"kind": "processor", "name": "batch", "pipeline": "logs/loadbalancer", "error": "couldn't find the exporter for the endpoint \"localhost:55710\""}
Dec 08 21:41:11 otel-agent otelcol-contrib[2229801]: 2022-12-08T21:41:11.262Z        warn        batchprocessor@v0.64.0/batch_processor.go:178        Sender failed        {"kind": "processor", "name": "batch", "pipeline": "logs/loadbalancer", "error": "couldn't find the exporter for the endpoint \"localhost:55710\""}
Dec 08 21:41:11 otel-agent otelcol-contrib[2229801]: 2022-12-08T21:41:11.464Z        warn        batchprocessor@v0.64.0/batch_processor.go:178        Sender failed        {"kind": "processor", "name": "batch", "pipeline": "logs/loadbalancer", "error": "couldn't find the exporter for the endpoint \"localhost:55700\""}
Dec 08 21:41:11 otel-agent otelcol-contrib[2229801]: 2022-12-08T21:41:11.664Z        warn        batchprocessor@v0.64.0/batch_processor.go:178        Sender failed        {"kind": "processor", "name": "batch", "pipeline": "logs/loadbalancer", "error": "couldn't find the exporter for the endpoint \"localhost:55700\""}
Dec 08 21:41:11 otel-agent otelcol-contrib[2229801]: 2022-12-08T21:41:11.865Z        warn        batchprocessor@v0.64.0/batch_processor.go:178        Sender failed        {"kind": "processor", "name": "batch", "pipeline": "logs/loadbalancer", "error": "couldn't find the exporter for the endpoint \"localhost:55710\""}
Dec 08 21:41:12 otel-agent otelcol-contrib[2229801]: 2022-12-08T21:41:12.067Z        warn        batchprocessor@v0.64.0/batch_processor.go:178        Sender failed        {"kind": "processor", "name": "batch", "pipeline": "logs/loadbalancer", "error": "couldn't find the exporter for the endpoint \"localhost:55720\""}
Dec 08 21:41:12 otel-agent otelcol-contrib[2229801]: 2022-12-08T21:41:12.269Z        warn        batchprocessor@v0.64.0/batch_processor.go:178        Sender failed        {"kind": "processor", "name": "batch", "pipeline": "logs/loadbalancer", "error": "couldn't find the exporter for the endpoint \"localhost:55720\""}
Dec 08 21:41:12 otel-agent otelcol-contrib[2229801]: 2022-12-08T21:41:12.470Z        warn        batchprocessor@v0.64.0/batch_processor.go:178        Sender failed        {"kind": "processor", "name": "batch", "pipeline": "logs/loadbalancer", "error": "couldn't find the exporter for the endpoint \"localhost:55710\""}
Dec 08 21:41:12 otel-agent otelcol-contrib[2229801]: 2022-12-08T21:41:12.672Z        info        LogsExporter        {"kind": "exporter", "data_type": "logs", "name": "logging", "#logs": 1}
Dec 08 21:41:12 otel-agent otelcol-contrib[2229801]: 2022-12-08T21:41:12.872Z        info        LogsExporter        {"kind": "exporter", "data_type": "logs", "name": "logging", "#logs": 1}
Dec 08 21:41:39 otel-agent otelcol-contrib[2229801]: 2022-12-08T21:41:39.165Z        warn        batchprocessor@v0.64.0/batch_processor.go:178        Sender failed        {"kind": "processor", "name": "batch", "pipeline": "logs/loadbalancer", "error": "couldn't find the exporter for the endpoint \"localhost:55700\""}
Dec 08 21:41:39 otel-agent otelcol-contrib[2229801]: 2022-12-08T21:41:39.365Z        warn        batchprocessor@v0.64.0/batch_processor.go:178        Sender failed        {"kind": "processor", "name": "batch", "pipeline": "logs/loadbalancer", "error": "couldn't find the exporter for the endpoint \"localhost:55710\""}
Dec 08 21:41:39 otel-agent otelcol-contrib[2229801]: 2022-12-08T21:41:39.566Z        warn        batchprocessor@v0.64.0/batch_processor.go:178        Sender failed        {"kind": "processor", "name": "batch", "pipeline": "logs/loadbalancer", "error": "couldn't find the exporter for the endpoint \"localhost:55710\""}
Dec 08 21:41:39 otel-agent otelcol-contrib[2229801]: 2022-12-08T21:41:39.767Z        info        LogsExporter        {"kind": "exporter", "data_type": "logs", "name": "logging", "#logs": 1}
Dec 08 21:41:39 otel-agent otelcol-contrib[2229801]: 2022-12-08T21:41:39.967Z        warn        batchprocessor@v0.64.0/batch_processor.go:178        Sender failed        {"kind": "processor", "name": "batch", "pipeline": "logs/loadbalancer", "error": "couldn't find the exporter for the endpoint \"localhost:55720\""}
Dec 08 21:41:40 otel-agent otelcol-contrib[2229801]: 2022-12-08T21:41:40.168Z        warn        batchprocessor@v0.64.0/batch_processor.go:178        Sender failed        {"kind": "processor", "name": "batch", "pipeline": "logs/loadbalancer", "error": "couldn't find the exporter for the endpoint \"localhost:55710\""}
Dec 08 21:41:40 otel-agent otelcol-contrib[2229801]: 2022-12-08T21:41:40.368Z        warn        batchprocessor@v0.64.0/batch_processor.go:178        Sender failed        {"kind": "processor", "name": "batch", "pipeline": "logs/loadbalancer", "error": "couldn't find the exporter for the endpoint \"localhost:55700\""}
Dec 08 21:41:40 otel-agent otelcol-contrib[2229801]: 2022-12-08T21:41:40.568Z        warn        batchprocessor@v0.64.0/batch_processor.go:178        Sender failed        {"kind": "processor", "name": "batch", "pipeline": "logs/loadbalancer", "error": "couldn't find the exporter for the endpoint \"localhost:55710\""}
Dec 08 21:41:40 otel-agent otelcol-contrib[2229801]: 2022-12-08T21:41:40.770Z        warn        batchprocessor@v0.64.0/batch_processor.go:178        Sender failed        {"kind": "processor", "name": "batch", "pipeline": "logs/loadbalancer", "error": "couldn't find the exporter for the endpoint \"localhost:55720\""}
Dec 08 21:41:40 otel-agent otelcol-contrib[2229801]: 2022-12-08T21:41:40.971Z        warn        batchprocessor@v0.64.0/batch_processor.go:178        Sender failed        {"kind": "processor", "name": "batch", "pipeline": "logs/loadbalancer", "error": "couldn't find the exporter for the endpoint \"localhost:55700\""}
Dec 08 21:41:41 otel-agent otelcol-contrib[2229801]: 2022-12-08T21:41:41.172Z        warn        batchprocessor@v0.64.0/batch_processor.go:178        Sender failed        {"kind": "processor", "name": "batch", "pipeline": "logs/loadbalancer", "error": "couldn't find the exporter for the endpoint \"localhost:55710\""}
Dec 08 21:41:41 otel-agent otelcol-contrib[2229801]: 2022-12-08T21:41:41.374Z        warn        batchprocessor@v0.64.0/batch_processor.go:178        Sender failed        {"kind": "processor", "name": "batch", "pipeline": "logs/loadbalancer", "error": "couldn't find the exporter for the endpoint \"localhost:55700\""}
Dec 08 21:41:41 otel-agent otelcol-contrib[2229801]: 2022-12-08T21:41:41.575Z        warn        batchprocessor@v0.64.0/batch_processor.go:178        Sender failed        {"kind": "processor", "name": "batch", "pipeline": "logs/loadbalancer", "error": "couldn't find the exporter for the endpoint \"localhost:55700\""}
Dec 08 21:41:41 otel-agent otelcol-contrib[2229801]: 2022-12-08T21:41:41.777Z        warn        batchprocessor@v0.64.0/batch_processor.go:178        Sender failed        {"kind": "processor", "name": "batch", "pipeline": "logs/loadbalancer", "error": "couldn't find the exporter for the endpoint \"localhost:55720\""}
Dec 08 21:41:41 otel-agent otelcol-contrib[2229801]: 2022-12-08T21:41:41.977Z        warn        batchprocessor@v0.64.0/batch_processor.go:178        Sender failed        {"kind": "processor", "name": "batch", "pipeline": "logs/loadbalancer", "error": "couldn't find the exporter for the endpoint \"localhost:55710\""}
Dec 08 21:41:42 otel-agent otelcol-contrib[2229801]: 2022-12-08T21:41:42.178Z        warn        batchprocessor@v0.64.0/batch_processor.go:178        Sender failed        {"kind": "processor", "name": "batch", "pipeline": "logs/loadbalancer", "error": "couldn't find the exporter for the endpoint \"localhost:55710\""}
Dec 08 21:41:42 otel-agent otelcol-contrib[2229801]: 2022-12-08T21:41:42.380Z        warn        batchprocessor@v0.64.0/batch_processor.go:178        Sender failed        {"kind": "processor", "name": "batch", "pipeline": "logs/loadbalancer", "error": "couldn't find the exporter for the endpoint \"localhost:55710\""}
Dec 08 21:41:42 otel-agent otelcol-contrib[2229801]: 2022-12-08T21:41:42.581Z        warn        batchprocessor@v0.64.0/batch_processor.go:178        Sender failed        {"kind": "processor", "name": "batch", "pipeline": "logs/loadbalancer", "error": "couldn't find the exporter for the endpoint \"localhost:55720\""}
Dec 08 21:41:42 otel-agent otelcol-contrib[2229801]: 2022-12-08T21:41:42.782Z        warn        batchprocessor@v0.64.0/batch_processor.go:178        Sender failed        {"kind": "processor", "name": "batch", "pipeline": "logs/loadbalancer", "error": "couldn't find the exporter for the endpoint \"localhost:55700\""}
Dec 08 21:41:42 otel-agent otelcol-contrib[2229801]: 2022-12-08T21:41:42.983Z        warn        batchprocessor@v0.64.0/batch_processor.go:178        Sender failed        {"kind": "processor", "name": "batch", "pipeline": "logs/loadbalancer", "error": "couldn't find the exporter for the endpoint \"localhost:55720\""}
Dec 08 21:41:43 otel-agent otelcol-contrib[2229801]: 2022-12-08T21:41:43.185Z        warn        batchprocessor@v0.64.0/batch_processor.go:178        Sender failed        {"kind": "processor", "name": "batch", "pipeline": "logs/loadbalancer", "error": "couldn't find the exporter for the endpoint \"localhost:55700\""}
Dec 08 21:41:43 otel-agent otelcol-contrib[2229801]: 2022-12-08T21:41:43.387Z        info        LogsExporter        {"kind": "exporter", "data_type": "logs", "name": "logging", "#logs": 1}
Dec 08 21:41:43 otel-agent otelcol-contrib[2229801]: 2022-12-08T21:41:43.588Z        warn        batchprocessor@v0.64.0/batch_processor.go:178        Sender failed        {"kind": "processor", "name": "batch", "pipeline": "logs/loadbalancer", "error": "couldn't find the exporter for the endpoint \"localhost:55700\""}
Dec 08 21:41:43 otel-agent otelcol-contrib[2229801]: 2022-12-08T21:41:43.790Z        info        LogsExporter        {"kind": "exporter", "data_type": "logs", "name": "logging", "#logs": 1}
Dec 08 21:41:43 otel-agent otelcol-contrib[2229801]: 2022-12-08T21:41:43.990Z        warn        batchprocessor@v0.64.0/batch_processor.go:178        Sender failed        {"kind": "processor", "name": "batch", "pipeline": "logs/loadbalancer", "error": "couldn't find the exporter for the endpoint \"localhost:55710\""}
Dec 08 21:42:09 otel-agent otelcol-contrib[2229801]: 2022-12-08T21:42:09.099Z        warn        batchprocessor@v0.64.0/batch_processor.go:178        Sender failed        {"kind": "processor", "name": "batch", "pipeline": "logs/loadbalancer", "error": "couldn't find the exporter for the endpoint \"localhost:55720\""}
Dec 08 21:42:09 otel-agent otelcol-contrib[2229801]: 2022-12-08T21:42:09.300Z        info        LogsExporter        {"kind": "exporter", "data_type": "logs", "name": "logging", "#logs": 1}
Dec 08 21:42:09 otel-agent otelcol-contrib[2229801]: 2022-12-08T21:42:09.500Z        warn        batchprocessor@v0.64.0/batch_processor.go:178        Sender failed        {"kind": "processor", "name": "batch", "pipeline": "logs/loadbalancer", "error": "couldn't find the exporter for the endpoint \"localhost:55720\""}
Dec 08 21:42:09 otel-agent otelcol-contrib[2229801]: 2022-12-08T21:42:09.701Z        warn        batchprocessor@v0.64.0/batch_processor.go:178        Sender failed        {"kind": "processor", "name": "batch", "pipeline": "logs/loadbalancer", "error": "couldn't find the exporter for the endpoint \"localhost:55700\""}
Dec 08 21:42:09 otel-agent otelcol-contrib[2229801]: 2022-12-08T21:42:09.902Z        warn        batchprocessor@v0.64.0/batch_processor.go:178        Sender failed        {"kind": "processor", "name": "batch", "pipeline": "logs/loadbalancer", "error": "couldn't find the exporter for the endpoint \"localhost:55700\""}
Dec 08 21:42:10 otel-agent otelcol-contrib[2229801]: 2022-12-08T21:42:10.103Z        info        LogsExporter        {"kind": "exporter", "data_type": "logs", "name": "logging", "#logs": 1}
Dec 08 21:42:10 otel-agent otelcol-contrib[2229801]: 2022-12-08T21:42:10.303Z        warn        batchprocessor@v0.64.0/batch_processor.go:178        Sender failed        {"kind": "processor", "name": "batch", "pipeline": "logs/loadbalancer", "error": "couldn't find the exporter for the endpoint \"localhost:55720\""}
Dec 08 21:42:10 otel-agent otelcol-contrib[2229801]: 2022-12-08T21:42:10.504Z        warn        batchprocessor@v0.64.0/batch_processor.go:178        Sender failed        {"kind": "processor", "name": "batch", "pipeline": "logs/loadbalancer", "error": "couldn't find the exporter for the endpoint \"localhost:55700\""}
Dec 08 21:42:10 otel-agent otelcol-contrib[2229801]: 2022-12-08T21:42:10.705Z        warn        batchprocessor@v0.64.0/batch_processor.go:178        Sender failed        {"kind": "processor", "name": "batch", "pipeline": "logs/loadbalancer", "error": "couldn't find the exporter for the endpoint \"localhost:55720\""}
Dec 08 21:42:10 otel-agent otelcol-contrib[2229801]: 2022-12-08T21:42:10.907Z        warn        batchprocessor@v0.64.0/batch_processor.go:178        Sender failed        {"kind": "processor", "name": "batch", "pipeline": "logs/loadbalancer", "error": "couldn't find the exporter for the endpoint \"localhost:55710\""}
Dec 08 21:42:11 otel-agent otelcol-contrib[2229801]: 2022-12-08T21:42:11.108Z        warn        batchprocessor@v0.64.0/batch_processor.go:178        Sender failed        {"kind": "processor", "name": "batch", "pipeline": "logs/loadbalancer", "error": "couldn't find the exporter for the endpoint \"localhost:55700\""}
Dec 08 21:42:11 otel-agent otelcol-contrib[2229801]: 2022-12-08T21:42:11.310Z        warn        batchprocessor@v0.64.0/batch_processor.go:178        Sender failed        {"kind": "processor", "name": "batch", "pipeline": "logs/loadbalancer", "error": "couldn't find the exporter for the endpoint \"localhost:55700\""}
Dec 08 21:42:11 otel-agent otelcol-contrib[2229801]: 2022-12-08T21:42:11.510Z        warn        batchprocessor@v0.64.0/batch_processor.go:178        Sender failed        {"kind": "processor", "name": "batch", "pipeline": "logs/loadbalancer", "error": "couldn't find the exporter for the endpoint \"localhost:55710\""}
Dec 08 21:42:11 otel-agent otelcol-contrib[2229801]: 2022-12-08T21:42:11.711Z        warn        batchprocessor@v0.64.0/batch_processor.go:178        Sender failed        {"kind": "processor", "name": "batch", "pipeline": "logs/loadbalancer", "error": "couldn't find the exporter for the endpoint \"localhost:55700\""}
Dec 08 21:42:11 otel-agent otelcol-contrib[2229801]: 2022-12-08T21:42:11.913Z        info        LogsExporter        {"kind": "exporter", "data_type": "logs", "name": "logging", "#logs": 1}
Dec 08 21:42:12 otel-agent otelcol-contrib[2229801]: 2022-12-08T21:42:12.113Z        warn        batchprocessor@v0.64.0/batch_processor.go:178        Sender failed        {"kind": "processor", "name": "batch", "pipeline": "logs/loadbalancer", "error": "couldn't find the exporter for the endpoint \"localhost:55700\""}
Dec 08 21:42:12 otel-agent otelcol-contrib[2229801]: 2022-12-08T21:42:12.315Z        warn        batchprocessor@v0.64.0/batch_processor.go:178        Sender failed        {"kind": "processor", "name": "batch", "pipeline": "logs/loadbalancer", "error": "couldn't find the exporter for the endpoint \"localhost:55710\""}
Dec 08 21:42:12 otel-agent otelcol-contrib[2229801]: 2022-12-08T21:42:12.516Z        info        LogsExporter        {"kind": "exporter", "data_type": "logs", "name": "logging", "#logs": 1}
Dec 08 21:42:12 otel-agent otelcol-contrib[2229801]: 2022-12-08T21:42:12.716Z        warn        batchprocessor@v0.64.0/batch_processor.go:178        Sender failed        {"kind": "processor", "name": "batch", "pipeline": "logs/loadbalancer", "error": "couldn't find the exporter for the endpoint \"localhost:55710\""}
Dec 08 21:42:12 otel-agent otelcol-contrib[2229801]: 2022-12-08T21:42:12.917Z        info        LogsExporter        {"kind": "exporter", "data_type": "logs", "name": "logging", "#logs": 1}
Dec 08 21:42:13 otel-agent otelcol-contrib[2229801]: 2022-12-08T21:42:13.118Z        info        LogsExporter        {"kind": "exporter", "data_type": "logs", "name": "logging", "#logs": 1}
Dec 08 21:42:13 otel-agent otelcol-contrib[2229801]: 2022-12-08T21:42:13.318Z        warn        batchprocessor@v0.64.0/batch_processor.go:178        Sender failed        {"kind": "processor", "name": "batch", "pipeline": "logs/loadbalancer", "error": "couldn't find the exporter for the endpoint \"localhost:55710\""}
Dec 08 21:42:13 otel-agent otelcol-contrib[2229801]: 2022-12-08T21:42:13.520Z        warn        batchprocessor@v0.64.0/batch_processor.go:178        Sender failed        {"kind": "processor", "name": "batch", "pipeline": "logs/loadbalancer", "error": "couldn't find the exporter for the endpoint \"localhost:55710\""}
```

### Additional context

_No response_

### LINKED ISSUE #35378: [exporter/loadbalancing] Data loss occurring when change in downstream DNS records or pods
### Component(s)

exporter/loadbalancing

## Description

We have used the DNS resolver and K8S resolver which seem to both cause data loss, because they route based on the IP address.

We are using the load balancing exporter for tail sampling, but this problem is generally applicable to this exporter. 

When our downstream services changes scales/deploys, the IP addresses change. And, since the IP address is tied to exporter, the spans get trapped in that exporter's queue, with no way out. That exporter is deleted along with the data that lives in its queue. 

Everytime we deploy we get a bunch of dropped spans as a result.

## Steps to Reproduce

Set up the loadbalancing exporter with the DNS resolver, then change the IP address that the DNS record resolves to. You will see `otelcol_exporter_send_failed_spans` tick up.

## Expected Result

Data is not dropped but re-balanced / successfully exported. 

## Actual Result

Data is lost along with the exporter that is deleted due to its IP address no longer being active.

### Potential solutions

We are using a stateful set, so the DNS records / pod names are stable, i.e. `pod-0, pod-1, ... , pod-n`. If the exporters were attached to these names instead of the IP addresses, this would solve the issue. This may be possible using the [pod hostname](https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#pod-s-hostname-and-subdomain-fields) or SRV record.

Another potential solution, which may or may not be possible, is to release the data trapped in the exporter queue, when an exporter is deleted. 

### Collector version

v0.109.0

## Environment
Kubernetes, arm64

### OpenTelemetry Collector configuration

```yaml
exporters:
  loadbalancing:
    protocol:
      otlp:
        sending_queue:
          queue_size: 1000
    resolver:
      dns:
        hostname: stateful-sampler.tailsampling
        port: "4317"
```

### Log output

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Fiery-Fenix**
##### Problem statement
`loadbalancing` exporter is actually a wrapper that's creates and manages set of actual `otlp` exporters
Those `otlp` exporters technically shares same configuration parameters that are defined on `loadbalancing` exporter level, including `sending_queue` configuration. The only difference is `endpoint` parameter that are substituted by `loadbalancing` exporter itself
This means, that `sending_queue`, `retry_on_failure` and `timeout` settings can be defined only on `otlp` sub-exporters, while top-level `loadbalancing` exporter is missing all those settings
This configuration approach produces several issue, that are already reported by users:
* Impossibility to use Persistent Queue in `loadbalancing` exporter (see #16826). That's happens because `otlp` sub-exporters are sharing the same configurations, including configuration of the queue, i.e. they all are using the same `storage` instance at the same time which is not possible at the moment
* Data loss even using `sending_queue` configuration (see #35378). That's happens because Queue is defined on level of `otlp` sub-exporters and if this exporter cannot flush data from queue (for example, endpoint is not available anymore) there is no other options that just to discard data from queue, i.e. there is no higher level queue and persistent storage where data can be returned is case of permanent failure

There might be some other potential issue that was already tracked and related to current configuration approach

##### Proposed solution
The easiest way to solve issues above - is to use standard approach for queue, retry and timeout configuration using `exporterhelper`
This will bring queue, retry and timeout functionality to the top-level of `loadbalancing` exporter, instead of `otlp` sub-exporters 
Related to mentioned issues it will bring:
* Single Persistent Queue, that is used by all `otlp` sub-exporters (not directly of course)
* Queue will not be discarded/destroyed if any (or all) of endpoint that are unreachable anymore, top-level queue will keep data until new endpoints will be available
* Scale-up and scale-down event for next layer of OpenTelemetry Collectors in K8s environments will be more predictable, and will not include data loss anymore (potential fix for #33959). There is still a big chance of inconsistency when some data will be send to incorrect endpoint, but it's already better state that we have right now

##### Noticeable changes
* `loadbalancing` exporter on top-level now uses `exporterhelper` with all supported functionality by it
* `sending_queue` will be automatically disabled on `otlp` exporters when it already present on top-level `loadbalancing` exporter. This change is done to prevent data loss on `otlp` exporters because queue there doesn't provide expected result. Also it will prevent potential misconfiguration from user side and as result - irrelevant reported issues 
* `exporter` attribute for metrics generated from `otlp` sub-exporters now includes endpoint for better visibility and to segregate them from top-level `loadbalancing` exporter - was `"exporter": "loadbalancing"`, now `"exporter": "loadbalancing/127.0.0.1:4317"`
* logs, generated by `otlp` sub-exporters now includes additional attribute `endpoint` with endpoint value with the same reasons as for metrics

#### Link to tracking issue
Fixes #35378
Fixes #16826

#### Testing
Proposed changes was heavily tested on large K8s environment with set of different scale-up/scale-down event using persistent queue configuration - no data loss were detected, everything works as expected

#### Documentation
`README.md` was updated to reflect new configuration parameters available. Sample `config.yaml` was updated as well

### CODE REVIEW

**Review by MovieStoreGuy — COMMENTED** [review]
Looks like it will need `make fmt` to be run to fix up a couple lines.

File: exporter/loadbalancingexporter/factory.go [hunk 1]
```diff
@@ -32,20 +40,98 @@ func createDefaultConfig() component.Config {
...
 
-func createTracesExporter(_ context.Context, params exporter.Settings, cfg component.Config) (exporter.Traces, error) {
-	return newTracesExporter(params, cfg)
+func buildExporterConfig(cfg *Config, endpoint string) otlpexporter.Config {
+	oCfg := cfg.Protocol.OTLP
+	oCfg.Endpoint = endpoint
+	// If top level queue is enabled - per-endpoint queue must be disable
+	// This helps us to avoid unexpected issues with mixing 2 level of exporter queues
+	if cfg.QueueSettings.Enabled {
+		oCfg.QueueConfig.Enabled = false
```
Comment (jamesmoessis) [inline exporter/loadbalancingexporter/factory.go:58]: Looking at the `ConsumeTraces()`, and it would be similar for metrics and logs. This is the code for when it exports.  

```golang
for exp, td := range exporterSegregatedTraces {
  start := time.Now()
  err := exp.ConsumeTraces(ctx, td)
  exp.consumeWG.Done()
  errs = multierr.Append(errs, err)
  ...
}
```

Now that the `exp` exporter has no queue, won't `ConsumeTraces()` block until exporting is finished? This would, I assume, make the export times much slower because it has to export the routed data in-series. This would take quite a long time especially if there are hundreds of backends to export to, likely causing a timeout.

What might be necessary is an `errgroup` or similar which can execute these now-blocking-calls to the exporter. I would be interested to hear your thoughts or maybe @jpkrohling's or @MovieStoreGuy's thoughts on this.

File: .chloggen/feat_loadbalancing-exporter-queue.yaml [hunk 2]
```diff
@@ -0,0 +1,27 @@
...
+# A brief description of the change.  Surround your text with quotes ("") if it needs to start with a backtick (`).
+note: Adding sending_queue, retry_on_failure and timeout settings to loadbalancing exporter configuration
+
+# Mandatory: One or more tracking issues related to the change. You can use the PR number here if no issue exists.
+issues: [35378,16826]
+
+# (Optional) One or more lines of additional information to render under the primary note.
+# These lines will be padded with 2 spaces and then inserted directly into the document.
+# Use pipe (|) for multiline entries.
+subtext: OTLP sub-exporter queue will be automatically disabled if loadbalancing exporter queue is enabled to avoid data loss
```
Comment (jamesmoessis) [inline .chloggen/feat_loadbalancing-exporter-queue.yaml:18]: Now that you've consolidated all exporter queues into one, their overall size is smaller. This could lead to dropped data in some deployments, since you are going from `n*queueSize` to `1*queueSize` - I don't think this is necessarily a breaking change but I think it should be mentioned in the changelog, so users can increase the queue size if they run into issues.

File: exporter/loadbalancingexporter/trace_exporter_test.go [hunk 3]
```diff
@@ -349,35 +344,6 @@ func TestConsumeTracesUnexpectedExporterType(t *testing.T) {
 	assert.EqualError(t, res, fmt.Sprintf("unable to export traces, unexpected exporter type: expected exporter.Traces but got %T", newNopMockExporter()))
 }
 
-func TestBuildExporterConfig(t *testing.T) {
```
Comment (jamesmoessis) [inline exporter/loadbalancingexporter/trace_exporter_test.go:352]: How difficult would it be to add a test that verifies data is not lost if an exporter is taken out of the ring? Could be useful since I don't see much verification of this behaviour

**Review by jamesmoessis — COMMENTED** [review]
This looks great, the approach is sound. Just a couple of talking points below. Thankyou for contributing this!

File: exporter/loadbalancingexporter/factory.go (hunk 1 above)
Comment (MovieStoreGuy) [reply exporter/loadbalancingexporter/factory.go:58]: Switching to an export queue also means that includes the queue workers which allow parallel processing, which allows a layer of latency hiding. 

Including a new "queue" worker in this could be hazardous in how it is done, say if you create a routine for each split batch you could end up with high amount of routine scheduling which can cause a significant performance hit. Then if you do more an async send on channels you have the original risk that this solves due to the queue moving from the current queue structure, to now a buffered channel that now needs to be shared again. 

For this iteration, I would suggest leaving it out of this change and keep as an issue in the backlog of "investigate and address if required"

**Comment by Fiery-Fenix** [comment]
> Looks like it will need `make fmt` to be run to fix up a couple lines.

done

File: exporter/loadbalancingexporter/factory.go (hunk 1 above)
Comment (Fiery-Fenix) [reply exporter/loadbalancingexporter/factory.go]: Missed that part (
Than yes, disabling seb-exporter queue in code might be too risky for all users
I have removed those lines

File: .chloggen/feat_loadbalancing-exporter-queue.yaml (hunk 2 above)
Comment (Fiery-Fenix) [reply .chloggen/feat_loadbalancing-exporter-queue.yaml]: I've updated changelog to reflect this part

File: exporter/loadbalancingexporter/README.md [hunk 4]
```diff
@@ -90,6 +90,7 @@ Refer to [config.yaml](./testdata/config.yaml) for detailed examples on using th
   * `traceID`: Routes spans based on their `traceID`. Invalid for metrics.
   * `metric`: Routes metrics based on their metric name. Invalid for spans.
   * `streamID`: Routes metrics based on their datapoint streamID. That's the unique hash of all it's attributes, plus the attributes and identifying information of its resource, scope, and metric data
+* loadbalancing exporter supports set of standard [queuing, batching, retry and timeout settings](https://github.com/open-telemetry/opentelemetry-collector/blob/main/exporter/exporterhelper/README.md)
```
Comment (jpkrohling) [inline exporter/loadbalancingexporter/README.md:93]: This needs more documentation: what happens when a failure occurs and then the ring is changed? Will it be directed to a new backend (yes!)? This expected behavior should be explicitly documented to our users.

File: exporter/loadbalancingexporter/factory.go [hunk 5]
```diff
@@ -32,20 +40,94 @@ func createDefaultConfig() component.Config {
 	otlpDefaultCfg.Endpoint = "placeholder:4317"
 
 	return &Config{
+		TimeoutSettings: exporterhelper.NewDefaultTimeoutConfig(),
```
Comment (jpkrohling) [inline exporter/loadbalancingexporter/factory.go:43]: This behavior should be clearly documented. I think it would even make sense to log a warning in case users tried to use that option.

That said, there ARE users relying on this feature at the moment. What should we do about them? I think we should copy their current values to the load-balancer level, which would give them roughly the same desired behavior they have today.

So, here's how it could work:

1) if the OTLP Exporter options do not include the resiliency options, use our new defaults 
2) if there are, copy the ones from the OTLP section into the top-level config, and set the OTLP one to the default values, writing a log message stating that this is happening
3) if there are options at both levels, the ones at the load-balancing level wins, as that's the newest one and we can assume it's the latest intent from the user (but log a WARN in this case, it's serious enough)

I don't think we need a feature flag or deprecation plan for this.

**Review by jpkrohling — COMMENTED** [review]
I really like this solution! I think it only needs more explicit documentation and better care for current users explicitly setting the resiliency options.

File: exporter/loadbalancingexporter/README.md (hunk 4 above)
Comment (Fiery-Fenix) [reply exporter/loadbalancingexporter/README.md:96]: I added a short description of new resilience mechanism into "Resilience and scaling considerations" section in README, please take a look

File: exporter/loadbalancingexporter/factory.go (hunk 5 above)
Comment (Fiery-Fenix) [reply exporter/loadbalancingexporter/factory.go:43]: Should we do this approach for all 3 resilience options (queue, retry and timeout) or it should be only to timeout settings?

**Review by jamesmoessis — APPROVED** [review]

File: exporter/loadbalancingexporter/factory.go (hunk 5 above)
Comment (jamesmoessis) [reply exporter/loadbalancingexporter/factory.go:43]: @jpkrohling re-ping - I think this is the only open question left on this PR. Trying to get it moving again

Comment (MovieStoreGuy) [reply exporter/loadbalancingexporter/factory.go:43]: > Should we do this approach for all 3 resilience options

Please do all three in this PR since it can go out together for the best optimal experience.

Comment (Fiery-Fenix) [reply exporter/loadbalancingexporter/factory.go:43]: I was thinking a lot about this "magic" and I'm sure now that we shouldn't do such settings copy because it may produce bunch of unpredictable issues.
First of all users not always looking into the logs, especially on containerized environments like K8s, and may easily miss warning record.
Also, to make this change work as expected, user needs to tune resilience options for BOTH `loadbalancing` exporter and `otlp` sub-exportes.
From our own experience, when we were testing this change: we have to lower down all 3 resilience options configured initially for sub-exportes to make data delivery reliable in our quite flexible environment. Simple copy of those settings make everything even worse than it was before
For example, retry and timeout settings were set to non-default, quite large, values. Keeping them as-is has a side effect of large delay in endpoints re-balancing, because failed sub-exporter was trying again and again to send data to already dead endpoint instead of returning data to `loadbalancing` exporter and re-balance it to "fresh" endpoints.
So I believe that users SHOULD review `loadbalancing` exporter settings by themself to achieve proper results instead of relying on unexpected change made by exporter code.
Probably we should add some additional warning to Changelog item that users should review their settings when upgrading to a new version? For me it sounds as much better option than implementing "magic" copy-paste code

Comment (jamesmoessis) [reply exporter/loadbalancingexporter/factory.go:43]: I think that makes sense, and given you've tested in production that gives me more confidence.

Comment (MovieStoreGuy) [reply exporter/loadbalancingexporter/factory.go:43]: Thank you for your response @Fiery-Fenix.

What I would suggest is the log a warning if the options are ignored at the load balancer level. Perhaps some internal metrics to track and some configuration to update based on the data being returned.

To @jpkrohling point, adding the load balancer queue and timeout helpers could cause some issues, mostly the timeout of timeouts for unaware users, so a log would help here. (Providing users more context and warnings, even if they may not get reviewed is important).

I do agree with your point that copying values might be magic and perhaps not the correct path forward. From my perspective, I think the top level load balancer would be at least double the sub exporters settings by default; mostly to allow a reshuffled into the queue and delivered to the next available endpoint.

The definite warning is when the top level exporter has a lower configuration compared to the sub exporter, that is a definite must.

File: exporter/loadbalancingexporter/README.md [hunk 6]
```diff
@@ -117,11 +121,80 @@ exporters:
...
+      queue_size: 1000
+      storage: file_storage/otc
+    routing_key: "service"
+    protocol:
+      otlp:
+        # all options from the OTLP exporter are supported
+        # except the endpoint
+        timeout: 1s
+        # doesn't take any effect because loadbalancing.sending_queue
+        # is enabled
```
Comment (jpkrohling) [inline exporter/loadbalancingexporter/README.md:177]: This is still confusing to me: looking at the code in the factory, the only property it overrides is the endpoint. Why is this not effective?

```go
func buildExporterConfig(cfg *Config, endpoint string) otlpexporter.Config {
	oCfg := cfg.Protocol.OTLP
	oCfg.Endpoint = endpoint

	return oCfg
}
```

File: exporter/loadbalancingexporter/factory.go (hunk 5 above)
Comment (jpkrohling) [reply exporter/loadbalancingexporter/factory.go:43]: I guess I'm just confused, but I'll try to clarify my points:

- If this PR brings change in behavior for people using the load-balancing exporter today, this is potentially a breaking change. Breaking changes have to be phased in: at N+1 (next version), this new feature has to be added behind a feature-flag and disabled by default. with proper notices to end-users about the upcoming change in the default behavior (changelog, warn log entries); at N+3, the flag is enabled by default; at N+5, the flag is removed and only the new behavior is active. 
- My previous understanding was that the resiliency options from the individual exporters would be moved to the top-level config. Copying the config from the individual exporters config to the top-level would make this a non-breaking change, as the behavior for the end-user is the roughly the same.
- My understanding now is that this is not changing the behavior: people can still configure the resiliency options at the individual exporters *and* at the top-level exporter. In this case, the readme still seems to be wrong in one place (the sending queue comment I left in place).

File: exporter/loadbalancingexporter/README.md [hunk 7]
```diff
@@ -48,14 +48,17 @@ This also supports service name based exporting for traces. If you have two or m
...
+The `loadbalancingexporter` will, irrespective of the chosen resolver (`static`, `dns`, `k8s`), create one exporter per endpoint. Each level of exporters, `loadbalancingexporter` itself and all sub-exporters (one per each endpoint), have it's own queue, timeout and retry mechanisms. Importantly, the `loadbalancingexporter` will attempt to re-route data to a healthy endpoint on delivery failure because in-memory queue, retry and timeout setting are enabled by default ([more details on queuing, retry and timeout default settings](https://github.com/open-telemetry/opentelemetry-collector/blob/main/exporter/exporterhelper/README.md)).
```
Comment (jpkrohling) [inline exporter/loadbalancingexporter/README.md:51]: I understand this, but I wonder how easy this is to digest for new users. Perhaps we need a diagram somewhere? Like this: https://excalidraw.com/#json=idSDC7sKrosXFgMflKTMr,4aSVSJCVCJDInmGanZJW9Q

**Review by jpkrohling — COMMENTED** [review]
Apart from a couple of clarifications, this looks OK to me.

File: exporter/loadbalancingexporter/README.md (hunk 6 above)
Comment (Fiery-Fenix) [reply exporter/loadbalancingexporter/README.md]: That was a leftover from previous version, removed

File: exporter/loadbalancingexporter/README.md [hunk 8]
```diff
@@ -48,14 +48,39 @@ This also supports service name based exporting for traces. If you have two or m
...
+The `loadbalancingexporter` will, irrespective of the chosen resolver (`static`, `dns`, `k8s`), create one `otlp` exporter per endpoint. Each level of exporters, `loadbalancingexporter` itself and all sub-exporters (one per each endpoint), have it's own queue, timeout and retry mechanisms. Importantly, the `loadbalancingexporter`, by default, will NOT attempt to re-route data to a healthy endpoint on delivery failure, because in-memory queue, retry and timeout setting are disabled by default ([more details on queuing, retry and timeout default settings](https://github.com/open-telemetry/opentelemetry-collector/blob/main/exporter/exporterhelper/README.md)).
 
-* When using the `static` resolver and a target is unavailable, all the target's load-balanced telemetry will fail to be delivered until either the target is restored or removed from the static list. The same principle applies to the `dns` resolver.
+```
```
Comment (MovieStoreGuy) [inline exporter/loadbalancingexporter/README.md:53]: Thank you for drawing this one out, if you ever wanted to make it easier to visualise in Github you can use:

https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-diagrams

**Review by MovieStoreGuy — APPROVED** [review]

**Comment by MovieStoreGuy** [comment]
Leaving this with @jpkrohling as the code owner for this component :)

**Review by jpkrohling — APPROVED** [review]

**Comment by jpkrohling** [comment]
Thank you for your contribution, I think this change greatly improves the load balancer!

File: exporter/loadbalancingexporter/factory.go (hunk 1 above)
Comment (jamesmoessis) [reply exporter/loadbalancingexporter/factory.go]: @Fiery-Fenix @MovieStoreGuy revisiting this, I think we actually do need to have a way of disabling the sub exporter queue without blocking in series here.

It's not really solving the problem if the sub exporter has a queue remaining, because that's where the data loss occurred. Then, if we disable the sub-exporter queue, it's extremely slow (blocking exporting in series for each endpoint). 

So I think this part of the code needs more work. Perhaps we should re open the issue or start a new issue.
