### PR TITLE
[receiver/libhoney] Fix msgpack response object

### LINKED ISSUE #40413: Libhoney receiver msgpack response is wrong
### Component(s)

_No response_

## Description

The libhoney receiver properly handles batches of events but then responds with an OTLP-style `partialSuccess` sort of response. The libhoney exporters will not necessarily error our but may retry or emit error log messages. 

## Steps to Reproduce

It's difficult to send msgpack from the CLI to get a raw signal back, but if you use the libhoney-go examples, you can see it in action. 

## Expected Result

A msgpacked object like `[]ResponseInBatch{{Status: http.StatusAccepted}}`

## Actual Result

A msgpacked object like `partialSuccess: []`

### Collector version

1.127.0

## Environment
OS: macos 15.5
Compiler(if manually compiled): go1.23.8

### OpenTelemetry Collector configuration

```yaml
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4417
      http:
        endpoint: 0.0.0.0:4418
  libhoney:
    http:
      endpoint: 0.0.0.0:8088
      traces_url_paths:
        - "/1/events"
        - "/1/batch"
    auth_api: https://api.honeycomb.io
    fields:
      resources:
        service_name: service.name
      scopes:
        library_name: library.name
        library_version: library.version
      attributes:
        trace_id: trace.trace_id
        parent_id: trace.parent_id
        span_id: trace.span_id
        name: name
        error: error
        spankind: span.kind
        durationFields:
          - duration_ms
```

### Log output

```shell

```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by mterhar**
#### Description

This change replaces the OTLP response code that was reused from other receivers and makes it respond with the proper libhoney objects.

#### Link to tracking issue
Fixes #40413 40413

#### Testing

Unit tests were updated to detect a regression

### CODE REVIEW

File: receiver/libhoneyreceiver/receiver.go [hunk 1]
```diff
@@ -261,8 +264,28 @@ func (r *libhoneyReceiver) handleEvent(resp http.ResponseWriter, req *http.Reque
...
+	default:
+		// For JSON requests, return JSON response
+		responseBody, err = json.Marshal(noErrors)
+		contentType = encoder.JSONContentType
+	}
+
+	if err != nil {
+		errorutil.HTTPError(resp, err)
+		return
+	}
```
Comment (TylerHelmuth) [inline receiver/libhoneyreceiver/receiver.go:304]: Can we check for this error case before creating `noErrors` and doing the switch logic?

Comment (mterhar) [reply receiver/libhoneyreceiver/receiver.go:304]: `noErrors` being marshalled into JSON or MSGPACK is what's contained in that last `err` check on line 284. There's still another error check on line 262 to ensure batch was handled properly. I don't think we can flip this around but also checking for errors on marshaling a constant is a bit overkill.

**Review by TylerHelmuth — APPROVED** [review]
