### PR TITLE
[receiver/sqlqueryreceiver] Add instrumentation scope to sqlqueryreceiver metrics & logs

### LINKED ISSUE #31028: Instrumentation scope not present in Metric stream
### Component(s)

receiver/sqlquery

## Description

The **Instrumentation Scope** is not being set to the expected value (i.e. `otelcol/sqlqueryreceiver`) in the Metric streams that are generated from the `sqlqueryreceiver`.

## Steps to Reproduce

1. Download otelcol-contrib v0.93.0 or earlier
2. Run collector with the provided sample configuration
3. Observe the Metrics stream produced on stdout

## Expected Result

The `Instrumentation Scope` should show `otelcol/sqlqueryreceiver`

## Actual Result

The `Instrumentation Scope` is empty

### Collector version

v0.93.0

## Environment
OS: Ubuntu 22.04,

### OpenTelemetry Collector configuration

```yaml
receivers:
  sqlquery/test:
    driver: postgres
    collection_interval: 60s
    datasource: "postgres://user:password@/database?sslmode=disable"
    queries:
      - sql: |
          select now() as "timestamp", 1 as "metric"

        metrics:
          - metric_name: testmetric
            value_column: metric
            value_type: int
            data_type: gauge
            unit: "1"

exporters:
  logging:
    verbosity: detailed

service:
  pipelines:
    metrics:
      receivers:
        - sqlquery/test
      processors: []
      exporters:
        - logging
```

### Log output

```shell
2024-02-05T17:55:10.631+1100    info    service@v0.93.0/telemetry.go:76 Setting up own telemetry...
2024-02-05T17:55:10.631+1100    info    service@v0.93.0/telemetry.go:146        Serving metrics {"address": ":8888", "level": "Basic"}
2024-02-05T17:55:10.631+1100    info    exporter@v0.93.0/exporter.go:275        Deprecated component. Will be removed in future releases.       {"kind": "exporter", "data_type": "metrics", "name": "logging"}
2024-02-05T17:55:10.632+1100    info    service@v0.93.0/service.go:139  Starting otelcol-contrib...     {"Version": "0.93.0", "NumCPU": 16}                                                                                                                    2024-02-05T17:55:10.632+1100    info    extensions/extensions.go:34     Starting extensions...                                                                                                                                                                 2024-02-05T17:55:10.632+1100    info    service@v0.93.0/service.go:165  Everything is ready. Begin running and processing data.
2024-02-05T17:55:11.641+1100    info    MetricsExporter {"kind": "exporter", "data_type": "metrics", "name": "logging", "resource metrics": 1, "metrics": 1, "data points": 1}
2024-02-05T17:55:11.641+1100    info    ResourceMetrics #0
Resource SchemaURL:
ScopeMetrics #0
ScopeMetrics SchemaURL:
InstrumentationScope
Metric #0
Descriptor:
     -> Name: testmetric
     -> Description:
     -> Unit: 1
     -> DataType: Gauge
NumberDataPoints #0
StartTimestamp: 1970-01-01 00:00:00 +0000 UTC
Timestamp: 2024-02-05 06:55:11.641453691 +0000 UTC
Value: 1
        {"kind": "exporter", "data_type": "metrics", "name": "logging"}
^C2024-02-05T17:55:13.613+1100  info    otelcol@v0.93.0/collector.go:258        Received signal from OS {"signal": "interrupt"}
2024-02-05T17:55:13.613+1100    info    service@v0.93.0/service.go:179  Starting shutdown...
2024-02-05T17:55:13.614+1100    info    extensions/extensions.go:59     Stopping extensions...
2024-02-05T17:55:13.614+1100    info    service@v0.93.0/service.go:193  Shutdown complete.
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by dehaansa**
#### Description
Add instrumentation scope to the metrics and logs emitted by the sqlqueryreceiver.

#### Link to tracking issue
Fixes https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/31028

#### Testing
Updated integration tests.

### CODE REVIEW

**Review by atoulme — APPROVED** [review]

**Review by dmitryax — APPROVED** [review]

File: receiver/sqlqueryreceiver/integration_test.go [hunk 1]
```diff
@@ -1,8 +1,6 @@
 // Copyright The OpenTelemetry Authors
 // SPDX-License-Identifier: Apache-2.0
 
-//go:build integration
```
Comment (songy23) [inline receiver/sqlqueryreceiver/integration_test.go:4]: This breaks Windows CIs, see https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/36917

Comment (dehaansa) [reply receiver/sqlqueryreceiver/integration_test.go:4]: Oops, I didn't intend to commit that in this PR that was just for local tests. https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/36923
