### PR TITLE
[receiver/faroreceiver] Add Faro receiver logic to wireframe

### LINKED ISSUE #19180: New component: Faro Receiver
### The purpose and use-cases of the new component

The purpose of this component would be to ingest telemetry data sent from [Grafana Faro](https://github.com/grafana/faro-web-sdk). 

### Example configuration for the component

```yaml
receivers:
  faro:
    http:
  faro/withcors:
    http:
      cors:
        allowed_origins:
          - *
```
      

### Telemetry data types supported

- Logs
- Traces

### Is this a vendor-specific component?

- [ ] This is a vendor-specific component
- [ ] If this is a vendor-specific component, I am proposing to contribute this as a representative of the vendor.

### Sponsor (optional)

@dehaansa 

### Additional context

The Grafana Faro Web SDK is a highly configurable open source JavaScript agent that can easily be embedded in web applications to collect real user monitoring (RUM) data: performance metrics, logs, exceptions, events, and traces.

### PR DESCRIPTION
**Pull request by t00mas**
#### Description
Faro receiver package enables Faro-compatible endpoints. This makes it work.

#### Link to tracking issue
Fixes https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/19180

#### Testing
Adding more unit tests.

### CODE REVIEW

**Comment by t00mas** [comment]
Note: I'm basically copying https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/38224 from @dark0dave and making updates

**Comment by atoulme** [comment]
Moving to draft while this PR is being worked on. Please mark ready to review and ping @dehaansa when done.

File: receiver/faroreceiver/utils.go [hunk 1]
```diff
@@ -0,0 +1,49 @@
...
+	case http.StatusBadGateway:
+		return true
+	case http.StatusServiceUnavailable:
+		return true
+	case http.StatusGatewayTimeout:
+		return true
+	default:
+		return false
+	}
+}
```
Comment (mar4uk) [inline receiver/faroreceiver/utils.go:49]: functions from utils.go seem are not used anywhere

**Review by mar4uk — APPROVED** [review]

**Comment by atoulme** [comment]
@dehaansa please review

File: receiver/faroreceiver/receiver.go [hunk 2]
```diff
@@ -0,0 +1,212 @@
...
+			}
+		} else {
+			r.settings.Logger.Debug("Faro logs are nil, skipping")
+		}
+	} else {
+		r.settings.Logger.Debug("Logs consumer not registered, skipping")
+	}
+
+	if len(errors) > 0 {
+		r.settings.Logger.Error("Failed to process Faro payload", zap.Any("payload", payload), zap.Any("errors", errors))
```
Comment (dehaansa) [inline receiver/faroreceiver/receiver.go:198]: Given that clients may re-send, should we fail fast? IE if traces fails, do we _want_ to try to send logs?

File: receiver/faroreceiver/receiver.go [hunk 3]
```diff
@@ -0,0 +1,212 @@
...
+	"go.opentelemetry.io/collector/config/confighttp"
+	"go.opentelemetry.io/collector/consumer"
+	"go.opentelemetry.io/collector/receiver"
+	"go.opentelemetry.io/collector/receiver/receiverhelper"
+	"go.uber.org/zap"
+
+	farotranslator "github.com/open-telemetry/opentelemetry-collector-contrib/pkg/translator/faro"
+)
+
+const faroPath = "/"
```
Comment (dehaansa) [inline receiver/faroreceiver/receiver.go:27]: if I understand the faro [spec](https://github.com/grafana/faro/blob/main/spec/gen/faro.gen.yaml) correctly, should this support receiving data on /collect/{appKey}?

File: receiver/faroreceiver/receiver.go [hunk 4]
```diff
@@ -0,0 +1,212 @@
...
+	if len(errors) > 0 {
+		r.settings.Logger.Error("Failed to process Faro payload", zap.Any("payload", payload), zap.Any("errors", errors))
+		r.errorHandler(resp, req, strings.Join(errors, "\n"), http.StatusInternalServerError)
+		return
+	}
+
+	resp.WriteHeader(http.StatusOK)
+}
+
+func (r *faroReceiver) errorHandler(w http.ResponseWriter, _ *http.Request, errMsg string, statusCode int) {
```
Comment (dehaansa) [inline receiver/faroreceiver/receiver.go:206]: From the [spec](https://github.com/grafana/faro/blob/main/spec/gen/faro.gen.yaml), shouldn't this be json encoded?

**Comment by atoulme** [comment]
Moving to draft, please fix conflicts and address review and mark ready for review again.

File: receiver/faroreceiver/receiver.go (hunk 4 above)
Comment (t00mas) [reply receiver/faroreceiver/receiver.go:217]: Yep! Modifying that
I'm not sure about the schema being right in the spec though - @mar4uk I think the spec mixes Faro payload Exceptions with what the receiver can return

File: receiver/faroreceiver/receiver.go (hunk 2 above)
Comment (t00mas) [reply receiver/faroreceiver/receiver.go]: I think yes - I'm making this fail fast so not to waste time when things go wrong.

File: receiver/faroreceiver/receiver.go [hunk 5]
```diff
@@ -0,0 +1,212 @@
...
+	} else {
+		r.settings.Logger.Debug("Traces consumer not registered, skipping")
+	}
+
+	if r.nextLogs != nil {
+		logs, err := farotranslator.TranslateToLogs(req.Context(), payload)
+		if err == nil {
+			err = r.nextLogs.ConsumeLogs(req.Context(), logs)
+			if err != nil {
+				errors = append(errors, fmt.Sprintf("failed to push logs: %v", err))
```
[the remark this answers is not in the document]
Comment (t00mas) [reply receiver/faroreceiver/receiver.go]: Same

File: receiver/faroreceiver/receiver.go [hunk 6]
```diff
@@ -0,0 +1,212 @@
...
+	}
+
+	var errors []string
+
+	if r.nextTraces != nil {
+		traces, err := farotranslator.TranslateToTraces(req.Context(), payload)
+		if err == nil {
+			err = r.nextTraces.ConsumeTraces(req.Context(), traces)
+			if err != nil {
+				errors = append(errors, fmt.Sprintf("failed to push traces: %v", err))
```
[the remark this answers is not in the document]
Comment (t00mas) [reply receiver/faroreceiver/receiver.go]: Applying suggestion (sorry for not accepting this one straight away, modified this along the other changes from above)

File: receiver/faroreceiver/receiver.go [hunk 7]
```diff
@@ -0,0 +1,212 @@
...
+		if err == nil {
+			err = r.nextLogs.ConsumeLogs(req.Context(), logs)
+			if err != nil {
+				errors = append(errors, fmt.Sprintf("failed to push logs: %v", err))
+			}
+		} else {
+			r.settings.Logger.Debug("Faro logs are nil, skipping")
+		}
+	} else {
+		r.settings.Logger.Debug("Logs consumer not registered, skipping")
```
[the remark this answers is not in the document]
Comment (t00mas) [reply receiver/faroreceiver/receiver.go]: Removing

File: receiver/faroreceiver/receiver.go [hunk 8]
```diff
@@ -0,0 +1,212 @@
...
+		if err == nil {
+			err = r.nextTraces.ConsumeTraces(req.Context(), traces)
+			if err != nil {
+				errors = append(errors, fmt.Sprintf("failed to push traces: %v", err))
+			}
+		} else {
+			r.settings.Logger.Debug("Faro traces are nil, skipping")
+		}
+	} else {
+		r.settings.Logger.Debug("Traces consumer not registered, skipping")
```
[the remark this answers is not in the document]
Comment (t00mas) [reply receiver/faroreceiver/receiver.go]: Removing

File: receiver/faroreceiver/receiver.go [hunk 9]
```diff
@@ -0,0 +1,212 @@
...
+
+	if r.nextTraces != nil {
+		traces, err := farotranslator.TranslateToTraces(req.Context(), payload)
+		if err == nil {
+			err = r.nextTraces.ConsumeTraces(req.Context(), traces)
+			if err != nil {
+				errors = append(errors, fmt.Sprintf("failed to push traces: %v", err))
+			}
+		} else {
+			r.settings.Logger.Debug("Faro traces are nil, skipping")
```
[the remark this answers is not in the document]
Comment (t00mas) [reply receiver/faroreceiver/receiver.go]: I think I messed up with a linter error here and removed the check for traces (and logs) - I'm putting it back now

File: receiver/faroreceiver/receiver.go [hunk 10]
```diff
@@ -0,0 +1,212 @@
...
+			componentstatus.ReportStatus(host, componentstatus.NewFatalErrorEvent(err))
+		}
+	}()
+
+	r.settings.Logger.Info("HTTP server started", zap.String("address", r.serverHTTP.Addr))
+	return nil
+}
+
+func (r *faroReceiver) handleFaroRequest(resp http.ResponseWriter, req *http.Request) {
+	resp.Header().Set("Access-Control-Allow-Methods", "POST, OPTIONS")
```
[the remark this answers is not in the document]
Comment (t00mas) [reply receiver/faroreceiver/receiver.go]: Harmless, but moving these to the preflight path below it 👍🏼

File: receiver/faroreceiver/factory.go [hunk 11]
```diff
@@ -34,22 +36,66 @@ func createDefaultConfig() component.Config {
...
+		fCfg,
+		func() component.Component {
+			var rcv component.Component
+			rcv, err = newFaroReceiver(fCfg, &set)
+			return rcv
+		},
+	)
+	if err != nil {
+		return nil, err
+	}
```
[the remark this answers is not in the document]
Comment (t00mas) [reply receiver/faroreceiver/factory.go]: Refactoring 👍🏼

**Review by dehaansa — COMMENTED** [review]
New concern out of the refactoring.

File: receiver/faroreceiver/receiver.go [hunk 12]
```diff
@@ -0,0 +1,241 @@
...
+	w.WriteHeader(statusCode)
+
+	resp := errorResponse{
+		Error:   http.StatusText(statusCode),
+		Code:    statusCode,
+		Message: errMsg,
+	}
+
+	if err := json.NewEncoder(w).Encode(resp); err != nil {
+		r.settings.Logger.Error("Could not write JSON response",
```
[the remark this answers is not in the document]
Comment (t00mas) [reply receiver/faroreceiver/receiver.go:228]: Isn't it overkill? json.NewEncoder(w).Encode() only fails (I think) if writing to a closed connection, mem corruption, system-level I/O errors...

A fallback like `fallback := fmt.Sprintf(`{"error":%q,"code":%d,"message":%q}`, http.StatusText(statusCode), statusCode, errMsg)` is easy to add now, but I don't see much benefit.

File: receiver/faroreceiver/receiver.go (hunk 4 above)
Comment (mar4uk) [reply receiver/faroreceiver/receiver.go:217]: Oh, right, the schema is not correct. It indeed mixes Faro payload Exceptions with error that actually returned

File: receiver/faroreceiver/receiver.go (hunk 3 above)
Comment (mar4uk) [reply receiver/faroreceiver/receiver.go:27]: agree, let's change the spec. It should be possible to use any URL

**Review by dehaansa — APPROVED** [review]
LGTM.

**Review by atoulme — APPROVED** [review]

File: receiver/faroreceiver/README.md [hunk 13]
```diff
@@ -12,4 +12,30 @@
...
+  faro:
+    endpoint: 'localhost:8081'
+```
+
+### Advanced Configuration
+```yaml
+receivers:
+  faro:
+    endpoint: 'localhost:8081'
+    cors:
```
Comment (ElementalWarrior) [inline receiver/faroreceiver/README.md:37]: I believe this is incorrect. his should be something like:
```yaml
receivers:
  faro:
    protocols:
      http:
        endpoint: 'localhost:8081'
        cors:
          ..
```

Comment (ElementalWarrior) [reply receiver/faroreceiver/README.md:37]: Actually I'm not even sure the cors implementation works at all. Both the config I've posted above and the example in the readme do not change the cors response headers.
