### PR TITLE
[pkg/stanza] Fix Stanza Key Value Parser custom pair delimiter bug

### LINKED ISSUE #31034: [pkg/stanza] Stanza Key Value Parser incorrectly parsing pairs with custom pair delimiter
### Component(s)

pkg/stanza

## Description
The Stanza key value parser does not respect quotes while doing pair parsing with a custom pair delimiter. 

## Steps to Reproduce
Perhaps easiest to reproduce by adding the following unit test to the `TestParser` unit test in this [test file](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/pkg/stanza/operator/parser/keyvalue/keyvalue_test.go):
``` go
{
	"custom pair delimiter in quoted value",
	func(kv *Config) {
		kv.PairDelimiter = "_"
	},
	&entry.Entry{
		Body: `a=b_c="d_e"`,
	},
	&entry.Entry{
		Attributes: map[string]any{
			"a": "b",
			"c": "d_e",
		},
		Body: `a=b_c="d_e"`,
	},
	false,
	false,
},
```
## Expected Result
In the unit test above, we set a custom pair delimiter of `_` and provide an input string that has a quoted value which contains the pair delimiter (`c="d_e"`). I would expect the parser to respect the quotes and split the input string into 2 key value pairs (`a=b`, `c="d_e"`). Then the parser would split the pairs into their keys and values resulting in the `Attributes` map defined in the unit test. 

## Actual Result
The actual result is during pair parsing the parser does not respect quotes and splits on the quoted `_`. This means that pair parsing results in these values: `a=b`, `c="d`, `e"`.  When the parser then tries to split the keys and values in each pair, it fails on `e"` because there is no delimiter to split on. The resulting output of the test case is 

```
Error:      	Received unexpected error: expected 'e"' to split by '=' into two items, got 1
```

### Collector version

main (present in current commit 292f291)

## Environment
Don't believe this is necessary

### OpenTelemetry Collector configuration

_No response_

### Log output

_No response_

### Additional context

I found this bug while adopting the parser over for a new OTTL function discussed in this issue: #30998. This bug occurs when a custom pair delimiter is used because`strings.Split()` gets used to split up the pairs, which does not respect quotes. This bug doesn't occur when using the default pair delimiter (white space) because a custom function passed to `strings.FieldsFunc` is used which does respect quotes.

### PR DESCRIPTION
**Pull request by dpaasman00**
**Description:** <Describe what has changed.>
Fixes a bug that would occur where quotes were not respected while pair parsing with a custom pair delimiter. This occurred because in the case of a custom pair delimiter `strings.Split()` was used which does not respect quotes. This bug was only an issue with custom pair delimiters because the default white space delimiter used `strings.FieldsFunc`with a function that did respect quotes. 

This fix adds the function `splitPairs(input, pairDelimiter string) ([]string, error)` which will split the given input on the given pairDelimiter. 

Alternative solutions like `strings.FieldsFunc` and `csv.NewReader` were considered but not used because they require the delimiter be a rune. This would have worked in many cases except for when the delimiter is more than 1 unique character long. Since the delimiter shouldn't be limited to a single rune, those solutions were rejected. 

A consequence of this new function respecting quotes is it will fail and return an error if any quoted value is ever malformed. For example, given the input `k1=v1 k2='v2"` the function will return an error because the single quote used for `k2`'s value is never closed. It will also fail on the input `k1='v1 k2=v2 k3=v3` for the same reason that the quote is never closed. I believe this is the behavior we want so that we don't return incorrect pairs for further parsing.

**Link to tracking Issue:** <Issue number if applicable>
Closes #31034 

**Testing:** <Describe what testing was performed and which tests were added.>
Added in additional unit tests to verify correct behaviors.

**Documentation:** <Describe the documentation added.>
I don't believe documentation is required as the user shouldn't see any changes to intended behavior.

### CODE REVIEW

File: pkg/stanza/operator/parser/keyvalue/keyvalue.go [hunk 1]
```diff
@@ -122,14 +122,45 @@ func (kv *Parser) parser(input string, delimiter string) (map[string]any, error)
...
+// splitPairs will split the input on the pairDelimiter and return the resulting slice.
+// `strings.Split` is not used because it does not respect quotes and will split if the delimiter appears in a quoted value
+func splitPairs(input, pairDelimiter string) ([]string, error) {
+	var result []string
+	currentPair := ""
+	delimiterLength := len(pairDelimiter)
+	quoteChar := "" // "" means we are not in quotes
+
+	i := 0
+	for i < len(input) {
```
Comment (djaglowski) [inline pkg/stanza/operator/parser/keyvalue/keyvalue.go:134]:
```suggestion
	for i := 0; i < len(input); i++ {
```

File: pkg/stanza/operator/parser/keyvalue/keyvalue.go [hunk 2]
```diff
@@ -122,14 +122,45 @@ func (kv *Parser) parser(input string, delimiter string) (map[string]any, error)
...
+				}
+			} else {
+				quoteChar = string(input[i])
+			}
 		}
-		return !quoted && r == ' '
-	})
-	return raw
+		currentPair += string(input[i])
+		i++
```
Comment (djaglowski) [inline pkg/stanza/operator/parser/keyvalue/keyvalue.go:154]:
```suggestion
```

File: pkg/stanza/operator/parser/keyvalue/keyvalue.go [hunk 3]
```diff
@@ -122,14 +122,45 @@ func (kv *Parser) parser(input string, delimiter string) (map[string]any, error)
...
+	i := 0
+	for i < len(input) {
+		if quoteChar == "" && i+delimiterLength <= len(input) && input[i:i+delimiterLength] == pairDelimiter {
+			if currentPair == "" {
+				i++
+				continue
+			}
+			result = append(result, currentPair)
+			currentPair = ""
+			i += delimiterLength
```
Comment (djaglowski) [inline pkg/stanza/operator/parser/keyvalue/keyvalue.go:142]:
```suggestion
			i += delimiterLength - 1
```

File: pkg/stanza/operator/parser/keyvalue/keyvalue_test.go [hunk 4]
```diff
@@ -572,6 +581,77 @@ key=value`,
...
+			&entry.Entry{
+				Attributes: map[string]any{
+					"a": "b",
+					"c": "this is a \"co ol\" value",
+				},
+				Body: `a=b c='this is a "co ol" value'`,
+			},
+			false,
+			false,
+		},
```
Comment (djaglowski) [inline pkg/stanza/operator/parser/keyvalue/keyvalue_test.go:617]: I was able to break this test by removing ` value` from the both and expectations. It seems the final `"` is dropped.

```go
		{
			"embedded double quotes in single quoted value",
			func(kv *Config) {},
			&entry.Entry{
				Body: `a=b c='this is a "co ol"'`,
			},
			&entry.Entry{
				Attributes: map[string]any{
					"a": "b",
					"c": "this is a \"co ol\"",
				},
				Body: `a=b c='this is a "co ol"'`,
			},
			false,
			false,
		},
```

File: pkg/stanza/operator/parser/keyvalue/keyvalue.go [hunk 5]
```diff
@@ -122,14 +122,45 @@ func (kv *Parser) parser(input string, delimiter string) (map[string]any, error)
...
+// `strings.Split` is not used because it does not respect quotes and will split if the delimiter appears in a quoted value
+func splitPairs(input, pairDelimiter string) ([]string, error) {
+	var result []string
+	currentPair := ""
+	delimiterLength := len(pairDelimiter)
+	quoteChar := "" // "" means we are not in quotes
+
+	i := 0
+	for i < len(input) {
+		if quoteChar == "" && i+delimiterLength <= len(input) && input[i:i+delimiterLength] == pairDelimiter {
```
Comment (djaglowski) [inline pkg/stanza/operator/parser/keyvalue/keyvalue.go:135]: This seems a bit more complicated than necessary. Could you iterate on this some more. My advice would be:
1. As noted in other comments, you only need to increment `i` manually when you find a delimiter. Otherwise, just let the loop handle it.
2. Try to handle "quick conclusions" first, so you can just if `if simple case { continue }`. This flattens the deeply nested structure because afterwards you know any tokens did not match those conditions.

File: pkg/stanza/operator/parser/keyvalue/keyvalue_test.go (hunk 4 above)
Comment (dpaasman00) [reply pkg/stanza/operator/parser/keyvalue/keyvalue_test.go:617]: I think this behavior was present before this change as well due to this bit of code in `parser()`:
```go
key := strings.TrimSpace(strings.Trim(m[0], "\"'"))
value := strings.TrimSpace(strings.Trim(m[1], "\"'"))
```
It was trimming any and all leading or trailing quotes. I fixed this behavior by getting rid of the need to strip the quotes in `parser()` by no longer including them in the strings returned by `splitPairs()`. We'll still call `strings.TrimSpace()` here to strip any leading or trailing white space.

Comment (dpaasman00) [reply pkg/stanza/operator/parser/keyvalue/keyvalue_test.go:617]: Also added in this test as well

File: pkg/stanza/operator/parser/keyvalue/keyvalue.go (hunk 5 above)
Comment (dpaasman00) [reply pkg/stanza/operator/parser/keyvalue/keyvalue.go]: Updated the loop to be an actual for loop now and flattened most of the nested `if` blocks. Let me know if I should be more aggressive in simplifying the loop or if this new version is good!

File: pkg/stanza/operator/parser/keyvalue/keyvalue_test.go (hunk 4 above)
Comment (djaglowski) [reply pkg/stanza/operator/parser/keyvalue/keyvalue_test.go:624]: Nice, thanks

File: .chloggen/pkg-stanza-fix-key-value-pair-delimiter-bug.yaml [hunk 6]
```diff
@@ -0,0 +1,27 @@
+# Use this changelog template to create an entry for release notes.
+
+# One of 'breaking', 'deprecation', 'new_component', 'enhancement', 'bug_fix'
+change_type: bug_fix
+
+# The name of the component, or a single word describing the area of concern, (e.g. filelogreceiver)
+component: pkg/stanza
+
+# A brief description of the change.  Surround your text with quotes ("") if it needs to start with a backtick (`).
+note: Fixed a bug in the Key Value Parser that could arise when using a custom pair delimiter.
```
Comment (djaglowski) [inline .chloggen/pkg-stanza-fix-key-value-pair-delimiter-bug.yaml:10]:
```suggestion
note: Fixed a bug in the keyvalue_parser where quoted values could be split if they contained a delimited.
```

**Review by djaglowski — APPROVED** [review]
