### PR TITLE
[receiver/googlecloudpubsubreceiver] Fix flaky TestReceiver

### LINKED ISSUE #47541: [receiver/googlecloudpubsubreceiver]: Report for failed tests on main
Auto-generated report for `__run` job build.

Link to failed build: https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/24259314595
Commit: 86f97be
PR: #47277

### Component(s)
receiver/googlecloudpubsub

#### Test Failures
-  `TestReceiver`
```
=== RUN   TestReceiver
    receiver_test.go:190: 
        	Error Trace:	/home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/receiver/googlecloudpubsubreceiver/receiver_test.go:190
        	Error:      	Condition never satisfied
        	Test:       	TestReceiver
--- FAIL: TestReceiver (101.03s)

```

**Note**: Information about any subsequent build failures that happen while
this issue is open, will be added as comments with more information to this issue.

### PR DESCRIPTION
**Pull request by vyagh**
Stabilize TestReceiver by replacing an unreliable 1s fixed sleep with proper assert. Eventually polling. 
The test was flaking in CI when async stream startup took longer than 1s, causing published messages to be missed.

The change also:
normalizes all Eventually timeouts in the file to 10s for consistency across signal types.
Fixes #47541

### CODE REVIEW

**Review by dmitryax — APPROVED** [review]

**Review by alexvanboxel — APPROVED** [review]
Approved by codeowner

File: receiver/googlecloudpubsubreceiver/receiver_test.go [hunk 1]
```diff
@@ -171,16 +171,10 @@ func TestReceiver(t *testing.T) {
 		logsConsumer:    logSink,
 	}
 	assert.NoError(t, receiver.Start(ctx, fakeHost{}))
-
-	receiver.tracesConsumer = traceSink
-	receiver.metricsConsumer = metricSink
-	receiver.logsConsumer = logSink
```
Comment (songy23) [inline receiver/googlecloudpubsubreceiver/receiver_test.go:177]: Revert these?

Comment (vyagh) [reply receiver/googlecloudpubsubreceiver/receiver_test.go:177]: reverted :)

**Comment by vyagh** [comment]
increased timeouts to 30s for slower windows ci runners
