### PR TITLE
[receiver/k8sobjects] Fix issue where resourceVersion was not being remembered,

### LINKED ISSUE #24805: [receiver/k8sobjects] resourceVersion is not remembered
### Component(s)

receiver/k8sobjects

## Description
Ran across an issue today where we noticed the same event was being emitted by the k8sobjectsreceiver.  Investigating I found that although we are using `RetryWatcher` to automatically keep track of the resourceVersion during retries, we were not honoring that option in our `watchFunc`. The result is that any time the client has an error that can be retried it recollects all the available objects.

The fix for this issue, I believe, is to perform a list first, get the returned resourceVersion, and continue from there. See https://kubernetes.io/docs/reference/using-api/api-concepts/#efficient-detection-of-changes for details.

## Steps to Reproduce
1. Deploy the k8sobjects receiver
2. Wait for an inevitable connection reset

## Expected Result
The client intelligently handles the reset using the latest resourceVersion that it saw

## Actual Result
The client restarts the watch with a resourceVersion of `""`.

### Collector version

0.82.0

### Environment information

_No response_

### OpenTelemetry Collector configuration

_No response_

### Log output

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by TylerHelmuth**
**Description:** <Describe what has changed.>
Fixes an issue where the latest resourceVersion that `RetryWatcher` is remembering is not honored.

It turns out that `RetryWatcher` also doesn't like being passed `""` or `"0"` during startup, and if you pass it a default value of `"1"` it will most likely return with a `410` complaining that the resource is too old and is long gone.

To fix this, we not perform an initial `List` to get the latest values and a proper resourceVersion. This is recommended by https://kubernetes.io/docs/reference/using-api/api-concepts/#efficient-detection-of-changes.

**Link to tracking Issue:**
Closes https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/24805

**Testing:**
I tested this a lot manually.  I updated the unit tests, but it was a struggle - the fake client framework doesn't honor the resourceVersion concept like k8s actually does.

**Documentation:** 
Updated the readme to call out that Watch mode needs list access if no resource_version is provided.

### CODE REVIEW

File: receiver/k8sobjectsreceiver/receiver.go [hunk 1]
```diff
@@ -146,40 +147,85 @@ func (kr *k8sobjectsreceiver) startWatch(ctx context.Context, config *K8sObjects
...
 				kr.setting.Logger.Warn("Watch channel closed unexpectedly", zap.String("resource", config.gvr.String()))
 				return
 			}
-			logs := watchObjectsToLogData(&data, time.Now(), config)
-
-			obsCtx := kr.obsrecv.StartLogsOp(ctx)
-			err := kr.consumer.ConsumeLogs(obsCtx, logs)
-			kr.obsrecv.EndLogsOp(obsCtx, metadata.Type, 1, err)
+			logs, err := watchObjectsToLogData(&data, time.Now(), config)
+			if err != nil {
```
Comment (TylerHelmuth) [inline receiver/k8sobjectsreceiver/receiver.go:190]: Since we're passing around resourceVersion values properly there is now a chance that the client returns a 410 and an status object complaining that the resource doesn't exist. This is a rare situation that would normally only happen if the user self-supplied a resourceVersion that was too old.

At the moment I am handling that as an error and allowing the processor to keep running, but the group that had the error will stop. The proper way to handle that situation is to do another List to get a proper resourceVersion again.  I think we should do that, but as a followup PR.

File: receiver/k8sobjectsreceiver/receiver.go [hunk 2]
```diff
@@ -146,40 +147,85 @@ func (kr *k8sobjectsreceiver) startWatch(ctx context.Context, config *K8sObjects
...
+
+	if objects == nil {
+		return "", fmt.Errorf("nil objects returned, this is an error in the k8sobjectsreceiver")
+	}
+
+	if len(objects.Items) > 0 {
+		logs := pullObjectsToLogData(objects, time.Now(), config)
+		obsCtx := kr.obsrecv.StartLogsOp(ctx)
+		err = kr.consumer.ConsumeLogs(obsCtx, logs)
+		kr.obsrecv.EndLogsOp(obsCtx, metadata.Type, logs.LogRecordCount(), err)
```
Comment (dmitryax) [inline receiver/k8sobjectsreceiver/receiver.go:222]: Are we sending all the objects on the start based on provided `config.ResourceVersion` config? That seems like an unexpected side effect

Comment (TylerHelmuth) [reply receiver/k8sobjectsreceiver/receiver.go:222]: If the user provides a `resouce_version` via the collector configuration then this initial list won't occur.  Instead, the watcher goes right into Watch and starts receiver the same after the `resource_version`.

This function is necessary if no `reasource_version` or a `resource_version="0"` (I need to update the PR to handle that case) in order to get the initial state and the resourceVersion.  I assumed we would ingest that initial state and the continue on to the watching. We would also only do this ingestion on collector startup - if the connection was reset the RetryWatcher has already remembered the latestResourceVersion to use when starting back up.

Ingesting this initial list has the benefit of guaranteeing the user has the latest state before it starts streaming the updates.  If we just start streaming the updates it is possible users don't have all the information.

Not ingesting the initial state does solve the issue of the receiver re-ingesting data on restart, but could mean some objects that would've ingested by the list would be missed.

Comment (TylerHelmuth) [reply receiver/k8sobjectsreceiver/receiver.go:222]: Ya thats fine with me.  So we're on the same page, you'd prefer we do the List to get the resourceVersion but not ingest the results, correct?

Comment (TylerHelmuth) [reply receiver/k8sobjectsreceiver/receiver.go:222]: Also, if we do provide a `includeInitialState` setting in the future, it would only apply when `watch` is specified an no `resource_version` is supplied.  According to the docs, supplying an explicit `resource_version` in the config implies the state is already understood - if a `resource_version` is ever supplied by the user we should not do a `List`.

Comment (dmitryax) [reply receiver/k8sobjectsreceiver/receiver.go:222]: > Ya thats fine with me. So we're on the same page, you'd prefer we do the List to get the resourceVersion but not ingest the results, correct?

Yes

> Also, if we do provide a includeInitialState setting in the future, it would only apply when watch is specified an no resource_version is supplied. According to the docs, supplying an explicit resource_version implies the state is already understood - if a resource_version is ever supplied by the user we should not do a List.

I'd like to have the behavior consistent not depending on `resource_version`, but if it's not possible we can document the limitation

Comment (TylerHelmuth) [reply receiver/k8sobjectsreceiver/receiver.go:222]: It is certainly possible, but I believe it is counter to K8s API best practices.  We can discuss in another issue tho.

Comment (TylerHelmuth) [reply receiver/k8sobjectsreceiver/receiver.go]: Updated to handle "0" resource versions and to stop ingesting the initial state.

**Review by dmitryax — APPROVED** [review]
