### PR TITLE
Postgresql receiver - Fix explain plan collection

### LINKED ISSUE #46274: Postgresqlreceiver explain plan fails on non-DML statement
### Component(s)

receiver/postgresql

### What happened?

In postresql receiver,  "EXPLAIN" is failing for non-DML statements.
It appears that PostgreSQL's EXPLAIN only works with SELECT, INSERT, UPDATE, DELETE, MERGE
It does NOT work with DDL like:
GRANT, REVOKE, DROP, CREATE (tables/functions/triggers), ALTER, etc.

### Collector version

0.146.0

## Environment
OS: (e.g., "Ubuntu 20.04")

### OpenTelemetry Collector configuration

```yaml
config:
  exporters:
    debug:
      verbosity: detailed
    otlphttp/test:
      headers:
  processors:
    batch:
      send_batch_max_size: 2
      send_batch_size: 1
      timeout: 10s
    memory_limiter:
      check_interval: 2s
      limit_mib: 500
      limit_percentage: 80
      spike_limit_percentage: 30
    resourcedetection:
      detectors:
      - env
      - eks
      - ec2
      - system
      override: true
      timeout: 15s
  receivers:
    postgresql:
      collection_interval: 10s
      databases:
      - postgres
      endpoint: rds.amazonaws.com:5432
      events:
        db.server.query_sample:
          enabled: true
        db.server.top_query:
          enabled: true
      password: Password123
      tls:
        insecure: true
      username: test
  service:
    pipelines:
      logs:
        exporters:
        - otlphttp/test
        - debug
        processors:
        - memory_limiter
        - batch
        - resourcedetection
        receivers:
        - postgresql
      metrics/sqlserver:
        receivers:
        - postgresql
image:
  repository: otel/opentelemetry-collector-contrib
  tag: 0.146.0
mode: deployment
nodeSelector:
  kubernetes.io/hostname: ip-192-168-55-121.us-east-2.compute.internal
resources:
  limits:
    cpu: 500m
    memory: 1000Mi
  requests:
    cpu: 250m
    memory: 128Mi
```

### Log output

```shell
Log snippets showing the error:

> 2026-02-19 17:32:39.620 UTC [69] ERROR:  prepared statement "otel__7750326004825482867" does not exist
> 2026-02-19 17:32:39.620 UTC [69] STATEMENT:  /* otel-collector-ignore */ DEALLOCATE PREPARE otel__7750326004825482867
> 2026-02-19 17:32:39.620 UTC [74] ERROR:  syntax error at or near "GRANT" at character 104
> 2026-02-19 17:32:39.620 UTC [74] STATEMENT:  /* otel-collector-ignore */ SET plan_cache_mode = force_generic_plan;PREPARE otel_93658453767373431 AS GRANT SELECT ON pg_locks TO demo;EXPLAIN(FORMAT JSON) EXECUTE otel_93658453767373431;
> 2026-02-19 17:32:39.620 UTC [74] ERROR:  prepared statement "otel_93658453767373431" does not exist
> 2026-02-19 17:32:39.620 UTC [74] STATEMENT:  /* otel-collector-ignore */ DEALLOCATE PREPARE otel_93658453767373431
> 2026-02-19 17:32:39.620 UTC [69] ERROR:  syntax error at or near "DROP" at character 107
> 2026-02-19 17:32:39.620 UTC [69] STATEMENT:  /* otel-collector-ignore */ SET plan_cache_mode = force_generic_plan;PREPARE otel__2633920873916966092 AS DROP FUNCTION pg_stat_statements_reset(Oid, Oid, bigint);EXPLAIN(FORMAT JSON) EXECUTE otel__2633920873916966092;
> 2026-02-19 17:32:39.621 UTC [69] ERROR:  prepared statement "otel__2633920873916966092" does not exist
> 2026-02-19 17:32:39.621 UTC [69] STATEMENT:  /* otel-collector-ignore */ DEALLOCATE PREPARE otel__2633920873916966092
> 2026-02-19 17:32:39.621 UTC [74] ERROR:  syntax error at or near "GRANT" at character 107
> 2026-02-19 17:32:39.621 UTC [74] STATEMENT:  /* otel-collector-ignore */ SET plan_cache_mode = force_generic_plan;PREPARE otel__7363549952190889315 AS GRANT SELECT ON pg_stat_bgwriter TO demo;EXPLAIN(FORMAT JSON) EXECUTE otel__7363549952190889315;
> 2026-02-19 17:32:39.621 UTC [74] ERROR:  prepared statement "otel__7363549952190889315" does not exist
> 2026-02-19 17:32:39.621 UTC [74] STATEMENT:  /* otel-collector-ignore */ DEALLOCATE PREPARE otel__7363549952190889315
> 2026-02-19 17:32:39.623 UTC [74] ERROR:  syntax error at or near "DROP" at character 107
> 2026-02-19 17:32:39.623 UTC [74] STATEMENT:  /* otel-collector-ignore */ SET plan_cache_mode = force_generic_plan;PREPARE otel__4349052727969988123 AS DROP TRIGGER IF EXISTS update_users_updated_at ON users;EXPLAIN(FORMAT JSON) EXECUTE otel__4349052727969988123;
> 2026-02-19 17:32:39.623 UTC [74] ERROR:  prepared statement "otel__4349052727969988123" does not exist
> 2026-02-19 17:32:39.623 UTC [74] STATEMENT:  /* otel-collector-ignore */ DEALLOCATE PREPARE otel__4349052727969988123
> 2026-02-19 17:32:39.623 UTC [74] ERROR:  syntax error at or near "REVOKE" at character 161
> 2026-02-19 17:32:39.623 UTC [74] STATEMENT:  /* otel-collector-ignore */ SET plan_cache_mode = force_generic_plan;PREPARE otel__8620197643790484943 AS -- Don't want this to be available to non-superusers.
>         REVOKE ALL ON FUNCTION pg_stat_statements_reset() FROM PUBLIC;EXPLAIN(FORMAT JSON) EXECUTE otel__8620197643790484943;
> 2026-02-19 17:32:39.624 UTC [74] ERROR:  prepared statement "otel__8620197643790484943" does not exist
> 2026-02-19 17:32:39.624 UTC [74] STATEMENT:  /* otel-collector-ignore */ DEALLOCATE PREPARE otel__8620197643790484943
> 2026-02-19 17:32:39.624 UTC [69] ERROR:  syntax error at or near "REVOKE" at character 317
> 2026-02-19 17:32:39.624 UTC [69] STATEMENT:  /* otel-collector-ignore */ SET plan_cache_mode = force_generic_plan;PREPARE otel__645730092975661821 AS /* contrib/pg_stat_statements/pg_stat_statements--1.5--1.6.sql */
```

### Additional context

_No response_

### Tip

<sub>[React](https://github.blog/news-insights/product-news/add-reactions-to-pull-requests-issues-and-comments/) with 👍 to help prioritize this issue. Please use comments to provide useful context, avoiding `+1` or `me too`, to help us triage it. Learn more [here](https://opentelemetry.io/community/end-user/issue-participation/).</sub>

### PR DESCRIPTION
**Pull request by akshays-19**
Fixing postgresql explain plan failure for non-DML statements. Added a whitelist of supported statements for EXPLAIN

#### Link to tracking issue
Fixes #46274

Added tests

### CODE REVIEW

File: receiver/postgresqlreceiver/client.go [hunk 1]
```diff
@@ -86,8 +86,65 @@ type postgreSQLClient struct {
...
+	"UPDATE": true,
+	"WITH":   true, // CTEs
+	"MERGE":  true, // PostgreSQL 15+
+	"VALUES": true,
+}
+
+// isExplainableQuery checks if a query can be explained by PostgreSQL.
+// Uses a whitelist approach, only allows known DML statements.
+func isExplainableQuery(query string) bool {
+	normalizedQuery := strings.ToUpper(strings.TrimSpace(query))
```
Comment (ebrdarSplunk) [inline receiver/postgresqlreceiver/client.go]: We should consider only uppering the first word rather than the whole query statement as we are only interested in the first word right?

**Review by ebrdarSplunk — CHANGES_REQUESTED** [review]

File: .chloggen/postgresql-fix-explain-ddl.yaml [hunk 2]
```diff
@@ -0,0 +1,30 @@
+# Use this changelog template to create an entry for release notes.
+
+# One of 'breaking', 'deprecation', 'new_component', 'enhancement', 'bug_fix'
+change_type: bug_fix
+
+# The name of the component, or a single word describing the area of concern, (e.g. receiver/filelog)
+component: receiver/postgresql
+
+# A brief description of the change.  Surround your text with quotes ("") if it needs to start with a backtick (`).
+Fix EXPLAIN plan collection failing on DDL statements (GRANT, DROP, REVOKE, etc.)
```
Comment (ebrdarSplunk) [inline .chloggen/postgresql-fix-explain-ddl.yaml]: we spoke about it but need to have "-note:" otherwise formatting issues

**Review by ebrdarSplunk — CHANGES_REQUESTED** [review]

**Review by ebrdarSplunk — APPROVED** [review]

File: receiver/postgresqlreceiver/client.go [hunk 3]
```diff
@@ -86,8 +86,66 @@ type postgreSQLClient struct {
...
+			continue
+		case strings.HasPrefix(trimmed, "/*"):
+			idx := strings.Index(trimmed, "*/")
+			if idx == -1 {
+				return false
+			}
+			trimmed = strings.TrimSpace(trimmed[idx+2:])
+			continue
+		}
+		break
```
Comment (evan-bradley) [inline receiver/postgresqlreceiver/client.go:124]:
```suggestion
			continue
		default:
			break
		}
```
Bit of a nit, but if this works the same, I think it would be easier to read this as three cases in a switch statement.

File: receiver/postgresqlreceiver/scraper_test.go [hunk 4]
```diff
@@ -631,6 +631,73 @@ func TestScrapeTopQueries(t *testing.T) {
...
+		{name: "UPDATE", query: "UPDATE users SET name = 'test' WHERE id = 1", expected: true},
+		{name: "DELETE", query: "DELETE FROM users WHERE id = 1", expected: true},
+		{name: "SELECT with leading whitespace", query: "   SELECT * FROM users", expected: true},
+		{name: "WITH CTE", query: "WITH cte AS (SELECT * FROM users) SELECT * FROM cte", expected: true},
+		{name: "TABLE shorthand", query: "TABLE users", expected: true},
+		{name: "VALUES", query: "VALUES (1, 'a'), (2, 'b')", expected: true},
+		{name: "MERGE", query: "MERGE INTO target USING source ON target.id = source.id WHEN MATCHED THEN UPDATE SET name = source.name", expected: true},
+		{name: "SELECT after comment", query: "-- comment\nSELECT * FROM users", expected: true},
+		{name: "SELECT after multi-line comment", query: "/* comment */ SELECT * FROM users", expected: true},
+		{name: "SELECT with parenthesis", query: "(SELECT * FROM users)", expected: false}, // Subquery alone - first char is '('
```
Comment (evan-bradley) [inline receiver/postgresqlreceiver/scraper_test.go:653]: Would be good to add tests for cases where non-printable characters mark the end of the first word as well, specifically tabs, and newlines.

**Review by evan-bradley — APPROVED** [review]
Looks good to me at a high level, but I'll leave the final review to the code owners.

**Review by dmitryax — APPROVED** [review]

**Comment by dmitryax** [comment]
Merging given that it's a bugfix
