### PR TITLE
[datadog receiver] Exit function on failed payload decode

### LINKED ISSUE #24562: [receiver/datadog] otlp runtime logs reported error
### Component(s)

receiver/datadog

### Describe the issue you're reporting

I am using receiver/datadog to export data from datadog agent,but open-telemetry keeps reporting errors.
My demo project is very simple, with step-by-step installation and deployment.I don't know why this is a problem.
datadog-agent version:
image

dd-java-agent version(latest):
image

open-telemetry-collector-contrib version:
image

otel-conf.yaml:
image

otel error logs:
image

image

### PR DESCRIPTION
**Pull request by MovieStoreGuy**
**Description:** 

Exit on error to avoid NPE

**Link to tracking Issue:**

Fixes https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/24562

**Testing:**

I would like to fix up how the component does tests in future PR.

**Documentation:**

N/A

### CODE REVIEW

**Review by gouthamve — APPROVED** [review]
LGTM, good catch!

**Review by jpkrohling — APPROVED** [review]

File: receiver/datadogreceiver/receiver.go [hunk 1]
```diff
@@ -91,6 +91,7 @@ func (ddr *datadogReceiver) handleTraces(w http.ResponseWriter, req *http.Reques
 	if err != nil {
 		http.Error(w, "Unable to unmarshal reqs", http.StatusInternalServerError)
 		ddr.params.Logger.Error("Unable to unmarshal reqs")
+		return
```
Comment (jpkrohling) [inline receiver/datadogreceiver/receiver.go:94]: Do you think it's feasible to add a test for this?

**Review by jpkrohling — APPROVED** [review]

**Review by crobert-1 — APPROVED** [review]

File: receiver/datadogreceiver/receiver.go (hunk 1 above)
Comment (MovieStoreGuy) [reply receiver/datadogreceiver/receiver.go:94]: Yeah, sorry it too me a bit to figure out how best to test it.
