### PR TITLE
[receiver/prometheusreceiver] Do not add `host.name` to metrics from localhost/unspecified targets

### LINKED ISSUE #6465: [Prometheus receiver] `host.name` attribute set to `0.0.0.0`
**Describe the bug**

When scraping internal metrics as documented [here](https://github.com/open-telemetry/opentelemetry-collector/blob/7ed3f75ef84d9e9d11b175a0859060f765faca0b/docs/troubleshooting.md#metrics) the metrics have a `0.0.0.0` hostname attribute set. The `host.name` semantic convention [is described in the OpenTelemetry specification](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/resource/semantic_conventions/host.md) as:

> Name of the host. On Unix systems, it may contain what the hostname command returns, or the fully qualified hostname, or another name specified by the user.

As e.g. [Wikipedia says](https://en.wikipedia.org/wiki/0.0.0.0),
>  the address 0.0.0.0 is a non-routable meta-address used to designate an invalid, unknown or non-applicable target

so I would argue that this value does not follow the specification (it is not the name of any valid host).

**Steps to reproduce**

Follow the instructions [here](https://github.com/open-telemetry/opentelemetry-collector/blob/7ed3f75ef84d9e9d11b175a0859060f765faca0b/docs/troubleshooting.md#metrics) and add a logging exporter to the pipeline with `logLevel` debug (see below for full config). Run the Collector and wait a few seconds.

**What did you expect to see?**

The internal metrics had a valid hostname or no hostname at all.

**What did you see instead?**

Metric payloads had the `host.name` attribute set to `0.0.0.0`. For example:

```
Resource labels:
     -> service.name: STRING(otelcol)
     -> host.name: STRING(0.0.0.0)
     -> instance: STRING(0.0.0.0:8888)
     -> port: STRING(8888)
     -> scheme: STRING(http)
     -> job: STRING(otelcol)
InstrumentationLibraryMetrics #0
InstrumentationLibrary
Metric #0
Descriptor:
     -> Name: otelcol_exporter_enqueue_failed_log_records
     -> Description: Number of log records failed to be added to the sending queue.
     -> Unit:
     -> DataType: Sum
     -> IsMonotonic: true
     -> AggregationTemporality: AGGREGATION_TEMPORALITY_CUMULATIVE
NumberDataPoints #0
Data point attributes:
     -> exporter: STRING(logging)
     -> service_instance_id: STRING(5e515c71-b05f-4735-88a8-9ecf5a4db707)
     -> service_version: STRING(latest)
StartTimestamp: 2021-11-30 15:21:30.96 +0000 UTC
Timestamp: 2021-11-30 15:21:30.96 +0000 UTC
Value: 0.000000
```

**What version did you use?**
Version: 61b560090fa1c0538409f578e0d011a89031e05a
**What config did you use?**
Config: 

```yaml
receivers:
  prometheus:
    config:
      scrape_configs:
      - job_name: 'otelcol'
        scrape_interval: 10s
        static_configs:
        - targets: ['0.0.0.0:8888']
        metric_relabel_configs:
          - source_labels: [ __name__ ]
            regex: '.*grpc_io.*'
            action: drop
exporters:
  logging:
    loglevel: debug
service:
  pipelines:
    metrics:
      receivers: [prometheus]
      processors: []
      exporters: [logging]

```

**Environment**

not relevant (happens on any environment).

**Additional context**

This attribute is added by this function: https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/61b560090fa1c0538409f578e0d011a89031e05a/receiver/prometheusreceiver/internal/prom_to_otlp.go#L24-L39

cc @Aneurysm9 @dashpole as CODEOWNERS

### PR DESCRIPTION
**Pull request by mx-psi**
**Description:** 

Do not add `host.name` for Prometheus receiver metrics that come from scraping a localhost or unspecified (`0.0.0.0`) target.

**Link to tracking Issue:** Fixes #6465.

**Testing:** Amended unit test. Ran example on linked issue to manually check this fixed the problem:

<details>

<summary>logging exporter when running example on linked issue</summary>

```
Resource labels:
     -> service.name: STRING(otelcol)
     -> job: STRING(otelcol)
     -> instance: STRING(0.0.0.0:8888)
     -> port: STRING(8888)
     -> scheme: STRING(http)
InstrumentationLibraryMetrics #0
InstrumentationLibrary  
Metric #0
Descriptor:
     -> Name: otelcol_exporter_enqueue_failed_log_records
     -> Description: Number of log records failed to be added to the sending queue.
     -> Unit: 
     -> DataType: Sum
     -> IsMonotonic: true
     -> AggregationTemporality: AGGREGATION_TEMPORALITY_CUMULATIVE
NumberDataPoints #0
Data point attributes:
     -> exporter: STRING(logging)
     -> service_instance_id: STRING(dd14a920-f022-4e27-a638-3f2dd8327716)
     -> service_version: STRING(latest)
StartTimestamp: 2021-12-06 11:46:20.958 +0000 UTC
Timestamp: 2021-12-06 11:46:20.958 +0000 UTC
Value: 0.000000
```

</details>

### CODE REVIEW

**Comment by jpkrohling** [comment]
What's up with the instance value? Shouldn't it be `127.0.0.1` as well?

```
     -> instance: STRING(0.0.0.0:8888)
```

**Comment by mx-psi** [comment]
> What's up with the instance value? Shouldn't it be 127.0.0.1 as well?

I don't have a strong opinion about this. I see a couple arguments in favor of keeping it as `0.0.0.0:8888`: the instance is not a semantic convention, so the `0.0.0.0` is not incorrect in that sense and its useful to have the original value somewhere, but I also realize having `host.name + port == instance` seems like an useful property.

**Review by jpkrohling — APPROVED** [review]
I'm approving, as I also don't see a problem with instance having 0.0.0.0. If you decide to leave it as it is, let me know and I'll merge this.

**Comment by mx-psi** [comment]
I would leave it as it is, but maybe let's wait a bit in case @Aneurysm9 or @dashpole have a different opinion, since they are CODEOWNERS?

File: receiver/prometheusreceiver/internal/prom_to_otlp.go [hunk 1]
```diff
@@ -21,11 +21,24 @@ import (
...
+	}
+	return host
+}
+
 func createNodeAndResourcePdata(job, instance, scheme string) pdata.Resource {
 	host, port, err := net.SplitHostPort(instance)
 	if err != nil {
 		host = instance
 	}
+	host = sanitizeHost(host)
```
Comment (bertysentry) [inline receiver/prometheusreceiver/internal/prom_to_otlp.go:41]: Wouldn't it be better to **remove** the host name *Attribute* when its value is `0.0.0.0`, `localhost`, `127.0.0.1` or `::1` (or any variation of this) and let the [resourcedetection processor](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/resourcedetectionprocessor) do the job or setting this attribute properly (with the actual host name of the system).

Because eventually, the metric is going to be stored somewhere else, where *localhost* will be either meaningless or misleading.

**Comment by dashpole** [comment]
@Aneurysm9 do we need to be able to distinguish between 0.0.0.0 and 127.0.0.1 for prom compliance reasons?  I.e. If we rename 0.0.0.0 to 127.0.0.1, we presumably need to do the reverse in the prom remote write exporter to match the prometheus server.  But if 0.0.0.0 and 127.0.0.1 are both valid, then we wouldn't be able to do that.

File: receiver/prometheusreceiver/internal/prom_to_otlp.go (hunk 1 above)
Comment (mx-psi) [reply receiver/prometheusreceiver/internal/prom_to_otlp.go:41]: I certainly would prefer that (e.g. the way we as a vendor use `host.name` makes it so `localhost` and similar attributes are practically useless), but I was assuming these attributes were necessary for something Prometheus-related.

Maybe @dashpole can comment on this?

Comment (dashpole) [reply receiver/prometheusreceiver/internal/prom_to_otlp.go:41]: If you are using the resource detection processor, it overrides the existing values by default anyways.  I double-checked, and host.name isn't used for anything prometheus-related

Comment (mx-psi) [reply receiver/prometheusreceiver/internal/prom_to_otlp.go:41]: > If you are using the resource detection processor, it overrides the existing values by default anyways. 

There are valid use cases where you don't want the `resourcedetectionprocessor` to override the hostname (e.g. chaining multiple Collectors), or maybe you can't/don't want to use it at all (e.g. your Collector distro doesn't support it or you don't want the performance hit).

>  I double-checked, and host.name isn't used for anything prometheus-related

Personally I would prefer removing it then, if everyone is on board with this. I agree with @bertysentry that having a localhost-like value for `host.name` is, while spec-compliant, not very useful in practice.

Comment (dashpole) [reply receiver/prometheusreceiver/internal/prom_to_otlp.go:41]: Removing it only when its a localhost equivalent? Or removing it entirely?

Comment (bertysentry) [reply receiver/prometheusreceiver/internal/prom_to_otlp.go:41]: **resourcedetectionprocessor** has an `override` option that can be set to `false` to prevent it from overwriting attributes that are already set.

Removing the `host.name` attributes in **prometheusreceiver** when its value is `localhost` (or any variation of localhost, incl. `0.0.0.0`) will then work very well in combination with **resourcedetectionprocessor** (and `override: false`). 

Typical example: the internal *otelcol* Prometheus exporter, whose metrics are currently attached to `0.0.0.0`, which are not usable once these metrics from several collectors are aggregated into a Prometheus server.

Comment (mx-psi) [reply receiver/prometheusreceiver/internal/prom_to_otlp.go:41]: > Removing it only when its a localhost equivalent?

Only when localhost or equivalent, yes

**Comment by jpkrohling** [comment]
From what I understood, there's an agreement then in removing the label when the value is localhost (127.*, 0.0.0.0), right?

**Comment by mx-psi** [comment]
Updated PR diff, name and description after discussion above. PTAL!

File: receiver/prometheusreceiver/internal/prom_to_otlp.go [hunk 2]
```diff
@@ -21,28 +21,36 @@ import (
 	conventions "go.opentelemetry.io/collector/model/semconv/v1.5.0"
 )
 
-const (
-	localHostIPv4 = "127.0.0.1"
-	anyIPIPv4     = "0.0.0.0"
-)
+// isAllowedHost returns if a host can be used as a value for the 'host.name' key.
+// localhost-like hosts and unspecified (0.0.0.0) hosts are not allowed.
+func isAllowedHost(host string) bool {
```
Comment (bertysentry) [inline receiver/prometheusreceiver/internal/prom_to_otlp.go:26]: Nitpicking: `isDiscernibleHost(host)` would sound clearer to me than `isAllowedHost(host)`, which makes me think of ACLs, firewalls, etc. 
(totally optional suggestion)

Comment (mx-psi) [reply receiver/prometheusreceiver/internal/prom_to_otlp.go]: Done!

File: receiver/prometheusreceiver/internal/prom_to_otlp.go [hunk 3]
```diff
@@ -21,6 +21,25 @@ import (
...
 )
 
+// isDiscernibleHost checks if a host can be used as a value for the 'host.name' key.
+// localhost-like hosts and unspecified (0.0.0.0) hosts are not discernible.
+func isDiscernibleHost(host string) bool {
+	ip := net.ParseIP(host)
+	if ip != nil {
+		// An IP is discernible if
+		//  - it's not local (e.g. belongs to 127.0.0.0/8 or ::1/128) and
+		//  - it's not unspecficied (e.g. the 0.0.0.0 address).
```
Comment (jpkrohling) [inline receiver/prometheusreceiver/internal/prom_to_otlp.go:31]:
```suggestion
		//  - it's not unspecified (e.g. the 0.0.0.0 address).
```

File: receiver/prometheusreceiver/internal/prom_to_otlp_test.go [hunk 4]
```diff
@@ -52,13 +52,15 @@ type jobInstanceDefinition struct {
...
 
-func makeResourceWithJobInstanceScheme(def *jobInstanceDefinition) pdata.Resource {
+func makeResourceWithJobInstanceScheme(def *jobInstanceDefinition, noHost bool) pdata.Resource {
 	resource := pdata.NewResource()
 	attrs := resource.Attributes()
 	// Using hardcoded values to assert on outward expectations so that
 	// when variables change, these tests will fail and we'll have reports.
 	attrs.UpsertString("service.name", def.job)
-	attrs.UpsertString("host.name", def.host)
+	if !noHost {
```
Comment (jpkrohling) [inline receiver/prometheusreceiver/internal/prom_to_otlp_test.go:61]: If this flag is used only here, consider making it in the affirmative case, like: `hasHost`. Using a double-negative might be confusing.

File: receiver/prometheusreceiver/internal/prom_to_otlp.go (hunk 3 above)
Comment (mx-psi) [reply receiver/prometheusreceiver/internal/prom_to_otlp.go]: done

File: receiver/prometheusreceiver/internal/prom_to_otlp_test.go (hunk 4 above)
Comment (mx-psi) [reply receiver/prometheusreceiver/internal/prom_to_otlp_test.go]: fixed, it's only used there indeed

**Review by bertysentry — APPROVED** [review]

**Review by dashpole — APPROVED** [review]

**Review by jpkrohling — APPROVED** [review]
