### PR TITLE
[chore][receiver/sqlserverreceiver] Fix flaky sqlserverreceiver integration tests

### LINKED ISSUE #45070: [bug][receiver/sqlserverreceiver] integration test flake: TopQuery returns zero logs and panics on empty ResourceLogs
### Component(s)

receiver/sqlserver

### What happened?

In CI, the TestEventsScraper integration test fails for the TopQuery subtest. The test sometimes observes zero log records and then immediately indexes into ResourceLogs().At(0), which panics with “index out of range [0] with length 0.” There’s also an assertion that actualLog.LogRecordCount() is positive that fails during Eventually polling when the scraper hasn’t yet produced logs in the expected window. This appears to be a timing/data-availability issue combined with unsafe indexing assumptions.

Assertion failure:
“0 is not positive”
“Condition never satisfied”
Panic:
panic: runtime error: index out of range [0] with length 0
at plog.ResourceLogsSlice.At(...), called from integration_test.go lines where the test does .ResourceLogs().At(0).ScopeLogs().At(0).LogRecords()

### Steps to reproduce
Run integration tests for receiver/sqlserverreceiver in CI (GitHub Actions) against mcr.microsoft.com/mssql/server:2022-latest.
The flake is intermittent; re-runs may pass or fail. It’s more likely under CI timing variability.
### Expected behavior
The test should wait until the required TopQuery event exists and then verify attributes without panicking.
Indexing should be guarded (no .At(0) on empty slices).
Clear assertion failures instead of panics when data has not yet arrived.
### Actual behavior
Eventually polling sometimes observes zero logs; an immediate .At(0) access panics.
The positive count assertion fails when the scraper hasn’t produced logs yet.
CI run aborts due to suspected panic; some tests may be skipped afterward.

### Collector version

main

### Environment information

CI: GitHub Actions
Go: 1.24.11 (per CI logs)
SQL Server image: mcr.microsoft.com/mssql/server:2022-latest
Collector pdata: v1.48.0 (per module path in stack trace)

### OpenTelemetry Collector configuration

```yaml

```

### Log output

```shell
Logs/stack traces
=== FAIL: . TestEventsScraper/TopQuery (22.04s)
    integration_test.go:156:
            Error:       "0" is not positive
    integration_test.go:156:
            Error:       Condition never satisfied
            Test:        TestEventsScraper/TopQuery

=== FAIL: . TestEventsScraper (48.99s)
panic: runtime error: index out of range [0] with length 0 [recovered]
    panic: runtime error: index out of range [0] with length 0

go.opentelemetry.io/collector/pdata/plog.ResourceLogsSlice.At(...)
github.com/open-telemetry/opentelemetry-collector-contrib/receiver/sqlserverreceiver.TestEventsScraper.func4(...): integration_test.go:163
github.com.open-telemetry/opentelemetry-collector-contrib/receiver/sqlserverreceiver.TestEventsScraper.func5(...): integration_test.go:232
```

### Additional context

The test config uses TopQueryCollection.CollectionInterval = 1ms, but event production depends on the query workload and SQL Server timing; windows may not align, resulting in empty slices.
The workload goroutine runs queries continuously; slight delays or startup sequencing may cause the scraper to miss the initial window.
Proposed fix
Guard indexing by checking lengths or by iterating ResourceLogs and ScopeLogs rather than using .At(0) directly.
Strengthen the Eventually condition to look for the specific top query record (db.query.text == "SELECT * FROM dbo.test_table") rather than just a positive total count.
Optionally add a brief delay in the workload loop and/or slightly increase Eventually timeouts to reduce flakiness.

### Tip

<sub>[React](https://github.blog/news-insights/product-news/add-reactions-to-pull-requests-issues-and-comments/) with 👍 to help prioritize this issue. Please use comments to provide useful context, avoiding `+1` or `me too`, to help us triage it. Learn more [here](https://opentelemetry.io/community/end-user/issue-participation/).</sub>

### PR DESCRIPTION
**Pull request by osullivandonal**
#### Description

The SQL Server integration tests are flaky when running in CI. 

The reason for this is twofold: first, the LookbackTime is set to 1μs while the collection interval is 1ms. This causes issues where the lookback time window is too small to find any queries that ran. Second, the test was setting a variable inside an EventuallyWithT closure and then using that variable outside the closure, which meant the final assertion could fail even when EventuallyWithT succeeded.

The fix increases LookbackTime to 1 second and moves all validation logic inside the EventuallyWithT closure to ensure atomicity.

#### Link to tracking issue
Fixes #45070 

#### Testing

Test was ran locally multiple times with no failures:

```bash
cd receiver/sqlserverreceiver
go test -tags=integration -run TestEventsScraper/TopQuery -count 5
```

### CODE REVIEW

File: receiver/sqlserverreceiver/integration_test.go [hunk 1]
```diff
@@ -152,24 +152,39 @@ func TestEventsScraper(t *testing.T) {
...
+						if query == "SELECT * FROM dbo.test_table" {
+							found = true
+							break
+						}
+					}
+
+					assert.True(tt, found, "Expected query not found in logs")
+				}, 10*time.Second, 100*time.Millisecond)
+
+				assert.True(t, found, "Expected query not found in final validation")
```
Comment (dehaansa) [inline receiver/sqlserverreceiver/integration_test.go]: This shouldn't be necessary, as the Eventually will fail if the last attempt fails and this won't be reached.

**Review by dehaansa — APPROVED** [review]
One nit, otherwise LGTM.

File: receiver/sqlserverreceiver/integration_test.go [hunk 2]
```diff
@@ -152,24 +152,39 @@ func TestEventsScraper(t *testing.T) {
...
-				for i := 0; i < logRecords.Len(); i++ {
-					attributes := logRecords.At(i).Attributes().AsRaw()
+					assert.NotNil(tt, actualLog)
 
-					query := attributes["db.query.text"].(string)
-					if query == "SELECT * FROM dbo.test_table" {
-						found = true
+					if actualLog.LogRecordCount() == 0 {
+						assert.Fail(tt, "No log records found")
+						return
```
Comment (crobert-1) [inline receiver/sqlserverreceiver/integration_test.go:165]: The return here is unnecessary as the assertion before it will always fail.

File: receiver/sqlserverreceiver/integration_test.go [hunk 3]
```diff
@@ -152,24 +152,39 @@ func TestEventsScraper(t *testing.T) {
...
 					}
-				}
-				assert.True(t, found)
+
+					if actualLog.ResourceLogs().Len() == 0 {
+						assert.Fail(tt, "No resource logs found")
+						return
```
Comment (crobert-1) [inline receiver/sqlserverreceiver/integration_test.go:170]: The return here is unnecessary as the assertion before it will always fail.

File: receiver/sqlserverreceiver/integration_test.go (hunk 2 above)
Comment (atoulme) [reply receiver/sqlserverreceiver/integration_test.go:165]: assert.Fail doesn't exit right away though. `require.Fail` exits right away

File: receiver/sqlserverreceiver/integration_test.go (hunk 1 above)
Comment (osullivandonal) [reply receiver/sqlserverreceiver/integration_test.go]: Good spot, I have removed this assert.

File: receiver/sqlserverreceiver/integration_test.go (hunk 2 above)
Comment (osullivandonal) [reply receiver/sqlserverreceiver/integration_test.go:165]: The return statements here are intentional and necessary.

Inside assert.EventuallyWithT, a failing assert does not stop execution of the closure — it only marks the current attempt as failed. The closure will be retried on the next tick until either all assertions pass or the timeout expires.

These returns act as guards for intermediate states where the logs slice is still empty. They terminate the current polling attempt early and allow EventuallyWithT to retry on the next tick.

If we remove the returns, execution continues after a failed assertion and we will index into empty slices, causing a panic and failing the test immediately instead of retrying.

We also can’t replace assert.Fail with require.Fail here: require calls FailNow, which would abort the closure and cause EventuallyWithT to stop retrying entirely.

So while the assertion will indeed fail on that tick, the return is still required to safely short-circuit the attempt and preserve the retry semantics.

File: receiver/sqlserverreceiver/integration_test.go (hunk 3 above)
Comment (osullivandonal) [reply receiver/sqlserverreceiver/integration_test.go:170]: As explained above, we need this short circuit.

File: receiver/sqlserverreceiver/integration_test.go (hunk 2 above)
Comment (crobert-1) [reply receiver/sqlserverreceiver/integration_test.go:165]: Ah, TIL, thank you both for clarifying!

**Review by crobert-1 — APPROVED** [review]
