### PR TITLE
[chore] Fix flaky tests on lokireceiver

### LINKED ISSUE #42173: [receiver/lokireceiver]: Report for failed tests on main
Auto-generated report for `__run` job build.

Link to failed build: https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/17133666850

#### Test Failures
-  `TestSendingProtobufPushRequestToHTTPEndpoint`
```
=== RUN   TestSendingProtobufPushRequestToHTTPEndpoint
    loki_test.go:135: 
        	Error Trace:	/home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/receiver/lokireceiver/loki_test.go:135
        	            				/opt/hostedtoolcache/go/1.24.6/arm64/src/testing/testing.go:1211
        	            				/opt/hostedtoolcache/go/1.24.6/arm64/src/testing/testing.go:1445
        	            				/opt/hostedtoolcache/go/1.24.6/arm64/src/testing/testing.go:1786
        	Error:      	Received unexpected error:
        	            	context canceled
        	Test:       	TestSendingProtobufPushRequestToHTTPEndpoint
--- FAIL: TestSendingProtobufPushRequestToHTTPEndpoint (0.00s)
=== RUN   TestSendingProtobufPushRequestToHTTPEndpoint/Sending_contentEncoding="snappy"_contentType=application/x-protobuf_to_http_endpoint
--- PASS: TestSendingProtobufPushRequestToHTTPEndpoint/Sending_contentEncoding="snappy"_contentType=application/x-protobuf_to_http_endpoint (0.00s)

```

**Note**: Information about any subsequent build failures that happen while
this issue is open, will be added as comments with more information to this issue.

### LINKED ISSUE #42317: [receiver/lokireceiver]: Report for failed tests on main
Auto-generated report for `__run` job build.

Link to failed build: https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/17297809637

#### Test Failures
-  `TestSendingPushRequestToHTTPEndpoint`
```
=== RUN   TestSendingPushRequestToHTTPEndpoint
    loki_test.go:135: 
        	Error Trace:	/home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/receiver/lokireceiver/loki_test.go:135
        	            				/opt/hostedtoolcache/go/1.24.6/arm64/src/testing/testing.go:1211
        	            				/opt/hostedtoolcache/go/1.24.6/arm64/src/testing/testing.go:1445
        	            				/opt/hostedtoolcache/go/1.24.6/arm64/src/testing/testing.go:1786
        	Error:      	Received unexpected error:
        	            	context canceled
        	Test:       	TestSendingPushRequestToHTTPEndpoint
--- FAIL: TestSendingPushRequestToHTTPEndpoint (0.01s)
=== RUN   TestSendingPushRequestToHTTPEndpoint/Sending_contentEncoding=""_contentType=application/json_to_http_endpoint
--- PASS: TestSendingPushRequestToHTTPEndpoint/Sending_contentEncoding=""_contentType=application/json_to_http_endpoint (0.00s)
=== RUN   TestSendingPushRequestToHTTPEndpoint/Sending_contentEncoding="snappy"_contentType=application/json_to_http_endpoint
--- PASS: TestSendingPushRequestToHTTPEndpoint/Sending_contentEncoding="snappy"_contentType=application/json_to_http_endpoint (0.00s)
=== RUN   TestSendingPushRequestToHTTPEndpoint/Sending_contentEncoding="gzip"_contentType=application/json_to_http_endpoint
--- PASS: TestSendingPushRequestToHTTPEndpoint/Sending_contentEncoding="gzip"_contentType=application/json_to_http_endpoint (0.00s)
=== RUN   TestSendingPushRequestToHTTPEndpoint/Sending_contentEncoding="deflate"_contentType=application/json_to_http_endpoint
--- PASS: TestSendingPushRequestToHTTPEndpoint/Sending_contentEncoding="deflate"_contentType=application/json_to_http_endpoint (0.00s)

```

**Note**: Information about any subsequent build failures that happen while
this issue is open, will be added as comments with more information to this issue.

### PR DESCRIPTION
**Pull request by mar4uk**
#### Description
Ensure the request is closed when the test finishes so t.Cleanup() can shut down without consulting the (already-canceled) test context

#### Link to tracking issue
Fixes https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/42317
Fixes https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/42173

### CODE REVIEW

File: receiver/lokireceiver/loki_test.go [hunk 1]
```diff
@@ -73,6 +73,9 @@ func sendToCollector(endpoint, contentType, contentEncoding string, body []byte)
 	if err != nil {
 		return err
 	}
+	// Ensure the request is closed when the test finishes so t.Cleanup() can shut down
+	// without consulting the (already-canceled) test context. See issue #42173.
+	req.Close = true
```
Comment (pjanotti) [inline receiver/lokireceiver/loki_test.go]: I had 2 cases in which `req.Close` was not enough to fix the flakiness, but it did seem to have reduced the flakiness.

File: receiver/lokireceiver/loki_test.go [hunk 2]
```diff
@@ -107,8 +110,12 @@ func startGRPCServer(t *testing.T) (*grpc.ClientConn, *consumertest.LogsSink) {
 	lr, err := newLokiReceiver(config, sink, set)
 	require.NoError(t, err)
 
-	require.NoError(t, lr.Start(t.Context(), componenttest.NewNopHost()))
-	t.Cleanup(func() { require.NoError(t, lr.Shutdown(t.Context())) })
+	ctx := t.Context()
+
+	require.NoError(t, lr.Start(ctx, componenttest.NewNopHost()))
+	t.Cleanup(func() {
+		require.NoError(t, lr.Shutdown(ctx))
```
Comment (pjanotti) [inline receiver/lokireceiver/loki_test.go]: I suggest here that you wrap `ctx` with `context.WithoutCancel` given that `req.Close = true` may not be enough.

File: receiver/lokireceiver/loki_test.go [hunk 3]
```diff
@@ -131,8 +138,12 @@ func startHTTPServer(t *testing.T) (string, *consumertest.LogsSink) {
...
```
Comment (pjanotti) [inline receiver/lokireceiver/loki_test.go]: Same here.

File: receiver/lokireceiver/loki_test.go [hunk 4]
```diff
@@ -408,8 +419,12 @@ func TestExpectedStatus(t *testing.T) {
 			lr, err := newLokiReceiver(config, consumer, receivertest.NewNopSettings(metadata.Type))
 			require.NoError(t, err)
 
-			require.NoError(t, lr.Start(t.Context(), componenttest.NewNopHost()))
-			t.Cleanup(func() { require.NoError(t, lr.Shutdown(t.Context())) })
+			ctx := t.Context()
+
+			require.NoError(t, lr.Start(ctx, componenttest.NewNopHost()))
+			t.Cleanup(func() {
```
Comment (pjanotti) [inline receiver/lokireceiver/loki_test.go]: Inside a test function I would consider this part of the test and use a `defer` instead, that will be called before the context is canceled.

File: receiver/lokireceiver/loki_test.go (hunk 1 above)
Comment (mar4uk) [reply receiver/lokireceiver/loki_test.go]: Removed `req.Close` completely. Ran tests locally with -count=1000 to make sure the last changes fix flakiness

**Review by axw — APPROVED** [review]

**Review by atoulme — APPROVED** [review]
