### PR TITLE
[exporter/prometheusremotewrite] Fix negative index reference to bucket list

### LINKED ISSUE #7149: [exporter/prometheusremotewrite] Collector crashes after metrics expiry
Relates to https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/6935

**Describe the bug**
When metrics expire, opentelemetry-collector crashes.

**Steps to reproduce**
1. Start otel collector with provided config below.
2. Start HotROD example: `docker run   --rm --network="host" --env JAEGER_AGENT_HOST=localhost  --env JAEGER_AGENT_PORT=6835   -p8080-8083:8080-8083   jaegertracing/example-hotrod:latest   all`
    1. This will emit spans to otel collector on port `6835`.
3. Click on a button on HotROD example to send a trace.
4. Check that the `latency_bucket` metrics are correct for the first minute of data, and make a note of which bucket has `count > 0`. For example, where the metric has label `le = "250"`.
    1. Example query: `latency_bucket{service_name = "driver", le="250"}`

**What did you expect to see?**

After a minute (on metric expiry), the metric with `le = "250"` (example query `latency_bucket{service_name = "driver", le="250"}`) should no longer be query-able (a null value).

**What did you see instead?**

After a minute (on metric expiry), the opentelemetry-collector crashes with the following logs:

```
2022-01-12T12:53:46.460Z	debug	prometheusexporter@v0.42.0/accumulator.go:262	metric expired: latency	{"kind": "exporter", "name": "prometheus"}
2022-01-12T12:53:46.460Z	debug	prometheusexporter@v0.42.0/accumulator.go:262	metric expired: latency	{"kind": "exporter", "name": "prometheus"}
2022-01-12T12:53:46.460Z	debug	prometheusexporter@v0.42.0/accumulator.go:262	metric expired: latency	{"kind": "exporter", "name": "prometheus"}
2022-01-12T12:53:46.466Z	INFO	loggingexporter/logging_exporter.go:54	MetricsExporter	{"#metrics": 7}
2022-01-12T12:53:46.466Z	DEBUG	loggingexporter/logging_exporter.go:64	ResourceMetrics #0

...

panic: runtime error: index out of range [-1]

goroutine 111 [running]:
github.com/open-telemetry/opentelemetry-collector-contrib/exporter/prometheusremotewriteexporter.addSingleHistogramDataPoint({0x8}, {0x0}, {0x0}, {0x0, 0x0}, 0xc00226aaa0, 0x8)
	github.com/open-telemetry/opentelemetry-collector-contrib/exporter/prometheusremotewriteexporter@v0.42.0/helper.go:397 +0x8bd
github.com/open-telemetry/opentelemetry-collector-contrib/exporter/prometheusremotewriteexporter.(*PRWExporter).PushMetrics(0xc00061ba40, {0x4bb0408, 0xc00225d800}, {0x4bb0440})
	github.com/open-telemetry/opentelemetry-collector-contrib/exporter/prometheusremotewriteexporter@v0.42.0/exporter.go:151 +0xa25
go.opentelemetry.io/collector/exporter/exporterhelper.(*metricsRequest).export(0x4bb0440, {0x4bb0408, 0xc00225d800})
	go.opentelemetry.io/collector@v0.42.0/exporter/exporterhelper/metrics.go:67 +0x34
go.opentelemetry.io/collector/exporter/exporterhelper.(*timeoutSender).send(0xc000a06028, {0x4c18830, 0xc002264ae0})
	go.opentelemetry.io/collector@v0.42.0/exporter/exporterhelper/common.go:232 +0x96
go.opentelemetry.io/collector/exporter/exporterhelper.(*retrySender).send(0xc00031d200, {0x4c18830, 0xc002264ae0})
	go.opentelemetry.io/collector@v0.42.0/exporter/exporterhelper/queued_retry.go:176 +0x5eb
go.opentelemetry.io/collector/exporter/exporterhelper.(*metricsSenderWithObservability).send(0xc00012e168, {0x4c18830, 0xc002264ae0})
	go.opentelemetry.io/collector@v0.42.0/exporter/exporterhelper/metrics.go:134 +0x88
go.opentelemetry.io/collector/exporter/exporterhelper.(*queuedRetrySender).start.func1({0x3f9a020, 0xc002264ae0})
	go.opentelemetry.io/collector@v0.42.0/exporter/exporterhelper/queued_retry_inmemory.go:105 +0x5c
go.opentelemetry.io/collector/exporter/exporterhelper/internal.consumerFunc.consume(0xc00064ffa8, {0x3f9a020, 0xc002264ae0})
	go.opentelemetry.io/collector@v0.42.0/exporter/exporterhelper/internal/bounded_memory_queue.go:99 +0x2c
go.opentelemetry.io/collector/exporter/exporterhelper/internal.(*boundedMemoryQueue).StartConsumers.func2()
	go.opentelemetry.io/collector@v0.42.0/exporter/exporterhelper/internal/bounded_memory_queue.go:78 +0xd6
created by go.opentelemetry.io/collector/exporter/exporterhelper/internal.(*boundedMemoryQueue).StartConsumers
	go.opentelemetry.io/collector@v0.42.0/exporter/exporterhelper/internal/bounded_memory_queue.go:68 +0xa5
```

**What version did you use?**
Version: `main` branch

**What config did you use?**
Config: 
```
receivers:
  jaeger:
    protocols:
      thrift_binary:
        endpoint: "localhost:6836"
      thrift_compact:
        endpoint: "localhost:6835"
  otlp/spanmetrics:
    protocols:
      grpc:
        endpoint: :12345
  otlp:
    protocols:
      grpc:
        endpoint: :4317
  prometheus:
    config:
      global:
        external_labels:
          p8s_logzio_name: spm-demo-otel
      scrape_configs: 
      - job_name: 'atm'
        scrape_interval: 15s
        static_configs:
        - targets: [ "0.0.0.0:8889" ]
exporters:
  jaeger:
    endpoint: "localhost:14250"
    tls:
      insecure: true
  prometheus:
    endpoint: "localhost:8889"
    metric_expiration: 1m
  logging:
    loglevel: debug
  prometheusremotewrite:
    endpoint: https://myremotewriteendpoint
    headers:
      Authorization: Bearer mybearertoken
processors:
  batch:
  spanmetrics:
    metrics_exporter: prometheus
    latency_histogram_buckets: [2ms, 6ms, 10ms, 100ms, 250ms, 500ms, 1000ms, 10000ms, 100000ms, 1000000ms]
    dimensions:
      - name: http.method
        default: GET
      - name: http.status_code    
extensions:
  pprof:
    endpoint: :1777
  zpages:
    endpoint: :55679
  health_check:
service:
  extensions: [health_check, pprof, zpages]
  pipelines:
    traces:
      receivers: [jaeger]
      processors: [spanmetrics,batch]
      exporters: [jaeger, logging]
    metrics/spanmetrics:
      # This receiver is just a dummy and never used.
      # Added to pass validation requiring at least one receiver in a pipeline.
      receivers: [otlp/spanmetrics]
      exporters: [prometheus]
    metrics:
      receivers: [otlp,prometheus]
      exporters: [logging,prometheusremotewrite]      
  telemetry:
    logs:
      level: "debug"
```

**Environment**
OS: "Ubuntu 20.04"
Compiler(if manually compiled): "go 1.17.5")

cc @Aneurysm9

### PR DESCRIPTION
**Pull request by albertteoh**
**Description:** 

When an upstream `prometheus` exporter flags metrics as stale, it also zeroes the metrics, leading to an empty bucket list.

When `prometheusremotewrite` receives this metric, it attempts to accumulate the `+Inf` bucket count by referencing the last bucket index with `len(pt.BucketCounts())-1`, resulting in an index of `-1` and causing the collector to `panic` and crash.

The fix involves only accumulating the count `+Inf` count if the datapoint does not have the `MetricDataPointFlagNoRecordedValue` flag present.

**Link to tracking Issue:** Fixes #7149

**Testing:** 

- Update unit test to reproduce the index out of range and fail; and add fix to confirm the tests pass.
- Manually integration tested with a metrics vendor and confirmed the crash no longer occurs.
  - Also confirmed the gaps in metrics are visible in remote vendor's metrics dashboard (Grafana).

### CODE REVIEW

File: exporter/prometheusremotewriteexporter/testutil_test.go [hunk 1]
```diff
@@ -158,21 +158,23 @@ var (
...
-		staleNaNDoubleGauge: getDoubleGaugeMetric(staleNaNDoubleGauge, lbs1, floatVal1, time1),
-		staleNaNIntSum:      getIntSumMetric(staleNaNIntSum, lbs1, intVal1, time1),
-		staleNaNSum:         getSumMetric(staleNaNSum, lbs1, floatVal1, time1),
-		staleNaNHistogram:   getHistogramMetric(staleNaNHistogram, lbs1, time1, floatVal2, uint64(intVal2), bounds, buckets),
-		staleNaNSummary:     getSummaryMetric(staleNaNSummary, lbs2, time2, floatVal2, uint64(intVal2), quantiles),
+		staleNaNIntGauge:       getIntGaugeMetric(staleNaNIntGauge, lbs1, intVal1, time1),
+		staleNaNDoubleGauge:    getDoubleGaugeMetric(staleNaNDoubleGauge, lbs1, floatVal1, time1),
+		staleNaNIntSum:         getIntSumMetric(staleNaNIntSum, lbs1, intVal1, time1),
+		staleNaNSum:            getSumMetric(staleNaNSum, lbs1, floatVal1, time1),
+		staleNaNHistogram:      getHistogramMetric(staleNaNHistogram, lbs1, time1, floatVal2, uint64(intVal2), bounds, buckets),
```
Comment (albertteoh) [inline exporter/prometheusremotewriteexporter/testutil_test.go:175]: I wasn't sure if I should just modify this test input to have empty bounds/buckets, if that's what a stale NaN Histogram should always look like, so I decided to adde a new case to avoid reducing coverage for that particular scenario.

**Comment by jpkrohling** [comment]
@albertteoh, is this fixing the linked issue, or just part of the final solution?

**Comment by albertteoh** [comment]
> @albertteoh, is this fixing the linked issue, or just part of the final solution?

Thanks for pointing that out. It fixes the linked issue; I've updated the description to include the "Fixes" annotation.

File: exporter/prometheusremotewriteexporter/testutil_test.go (hunk 1 above)
Comment (Aneurysm9) [reply exporter/prometheusremotewriteexporter/testutil_test.go:175]: When coming from the `prometheus` receiver there will be empty bounds/buckets (at least, for now, I'm not positive it's correct), but if any other source produces metrics with that flag there may be bounds/buckets, so this is probably safest.

**Review by Aneurysm9 — APPROVED** [review]
