### PR TITLE
[processor/isolationforest] Fix goroutine leak in modelUpdateLoop shutdown

### LINKED ISSUE #42675: [processor/isolationforest] Goroutine leak in modelUpdateLoop causing test suite failures with goleak
### Component(s)

processor/isolationforest

## Description
The isolation forest processor creates background goroutines for model updates but fails to properly clean them up during test execution, causing goleak to detect goroutine leaks. While the processor functionality works correctly, the test suite fails due to improper resource cleanup.

The leaked goroutines are from modelUpdateLoop method which runs in the background for periodic model updates. The processor's Shutdown() method doesn't properly wait for these goroutines to terminate before returning.

## Steps to Reproduce
1. Navigate to the isolation forest processor directory:
bash
cd processor/isolationforestprocessor

2. Run the test suite with goleak enabled:
bash
go test -v ./...

Observe that individual tests pass but the overall suite fails due to goroutine leaks

## Expected Result
- All tests should pass without any goroutine leaks
- The test suite should complete successfully with exit code 0
- goleak should not detect any leaked goroutines after test completion
- Background modelUpdateLoop goroutines should be properly terminated during processor shutdown

## Actual Result
PASS
coverage: 69.6% of statements
goleak: Errors on successful test run: found unexpected goroutines:
[Goroutine 116 in state select, with github.com/open-telemetry/opentelemetry-collector-contrib/processor/isolationforestprocessor.(*isolationForestProcessor).modelUpdateLoop on top of the stack:
github.com/open-telemetry/opentelemetry-collector-contrib/processor/isolationforestprocessor.(*isolationForestProcessor).modelUpdateLoop(...)
        /home/venu/opentelemetry-collector-contrib/processor/isolationforestprocessor/processor.go:137
created by github.com/open-telemetry/opentelemetry-collector-contrib/processor/isolationforestprocessor.newIsolationForestProcessor in goroutine 115
        /home/venu/opentelemetry-collector-contrib/processor/isolationforestprocessor/processor.go:106 +0x787
 Goroutine 118 in state select, with github.com/open-telemetry/opentelemetry-collector-contrib/processor/isolationforestprocessor.(*isolationForestProcessor).modelUpdateLoop on top of the stack:
github.com/open-telemetry/opentelemetry-collector-contrib/processor/isolationforestprocessor.(*isolationForestProcessor).modelUpdateLoop(...)
        /home/venu/opentelemetry-collector-contrib/processor/isolationforestprocessor/processor.go:137
created by github.com/open-telemetry/opentelemetry-collector-contrib/processor/isolationforestprocessor.newIsolationForestProcessor in goroutine 117
        /home/venu/opentelemetry-collector-contrib/processor/isolationforestprocessor/processor.go:106 +0x787
 ... (additional similar goroutines)
]
exit status 1
FAIL    github.com/open-telemetry/opentelemetry-collector-contrib/processor/isolationforestprocessor    0.551s

### Collector version

0.135.0

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

### OpenTelemetry Collector configuration

```yaml

```

### Log output

```shell

```

### Additional context

_No response_

### Tip

<sub>[React](https://github.blog/news-insights/product-news/add-reactions-to-pull-requests-issues-and-comments/) with 👍 to help prioritize this issue. Please use comments to provide useful context, avoiding `+1` or `me too`, to help us triage it. Learn more [here](https://opentelemetry.io/community/end-user/issue-participation/).</sub>

### PR DESCRIPTION
**Pull request by VenuEmmadi**
#### Description
This PR fixes goroutine leaks in the isolation forest processor caused by improper shutdown coordination of background `modelUpdateLoop` goroutines.

The processor was starting background goroutines for periodic model updates but not properly waiting for them to terminate during shutdown, causing `goleak` test failures. The tests would pass functionally but fail due to leaked goroutines remaining active after test completion.

**Root Cause:**
- `newIsolationForestProcessor` starts `go processor.modelUpdateLoop()` 
- `Shutdown()` method signals stop but doesn't wait for goroutine termination
- Tests don't call `Shutdown()` on created processors

**Fix:**
- Added `shutdownWG sync.WaitGroup` for proper goroutine tracking
- Modified `Shutdown()` to wait for all background goroutines to complete
- Updated tests to call `Shutdown()` during cleanup
- No functional changes to processor behavior

#### Link to tracking issue
Fixes #42675 

#### Testing
- All existing tests now pass without goroutine leaks
- `goleak` tests pass successfully  
- Added proper shutdown cleanup to all test functions that create processors
- Verified no regression in processor functionality
- Background goroutines properly terminate in both test and production environments

**Files tested:**
- `processor_test.go` - Fixed 5 test functions to call `Shutdown()`
- `factory_test.go` - Already had proper shutdown calls
- `integration_test.go` - Verified shutdown coordination works

#### Documentation
- Updated inline code comments explaining shutdown coordination
- No user-facing documentation changes needed (internal fix only)
- Proper goroutine lifecycle management maintains existing API

### CODE REVIEW

File: processor/isolationforestprocessor/processor_test.go [hunk 1]
```diff
@@ -96,6 +96,12 @@ func Test_newIsolationForestProcessor_Basic(t *testing.T) {
 	require.NoError(t, err)
 	require.NotNil(t, p)
 
+	// Add shutdown cleanup
+	t.Cleanup(func() {
+		shutdownErr := p.Shutdown(t.Context())
```
Comment (axw) [inline processor/isolationforestprocessor/processor_test.go]:
```suggestion
		shutdownErr := p.Shutdown(context.WithoutCancel(t.Context()))
```

The t.Context method returns a context that is cancelled when the test ends, before cleanups are invoked. This has been the cause of flaky tests in other components recently.

I see that the Shutdown method ignores context (it shouldn't), but even so it would be good to make this change to avoid others copy & pasting the same thing and causing flaky tests in other components.

File: processor/isolationforestprocessor/processor.go [hunk 2]
```diff
@@ -103,6 +104,10 @@ func newIsolationForestProcessor(config *Config, logger *zap.Logger) (*isolation
 	}
 
 	processor.updateTicker = time.NewTicker(updateFreq)
+
+	// Properly track the background goroutine with WaitGroup
+	processor.shutdownWG.Add(1)
+
 	go processor.modelUpdateLoop()
```
Comment (axw) [inline processor/isolationforestprocessor/processor.go]:
```suggestion
	// Properly track the background goroutine with WaitGroup
	processor.shutdownWG.Add(1)
	go func() {
		defer processor.shutdownWG.Done()
		processor.modelUpdateLoop()
	}()
```

Bit of a style preference, but I find that keeping the Add and Done calls close together makes it easier to reason about.

**Review by axw — APPROVED** [review]
Looks good, just a couple of minor suggestions.

**Review by axw — APPROVED** [review]

**Review by andrzej-stencel — APPROVED** [review]
Thanks @VenuEmmadi for this fix.

As a side note, it seems that [starting the model update loop](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/94af87394e863fa9c1b243e70ae3b04ef2e6cc51/processor/isolationforestprocessor/processor.go#L105-L106) should happen in the processor's `Start` function rather than in the `newIsolationForestProcessor` function.

**Review by atoulme — APPROVED** [review]
