### PR TITLE
awsfirehosereceiver: fix named extension loading

### LINKED ISSUE #39808: [receiver/awsfirehose] Encoding configuration fails if the ID contains `/`
### Component(s)

receiver/awsfirehose

## Description

The `encoding` extension fails if it contains an ID with `/`. The error comes from:

https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/3ebd0ddc658b5ad88ff99da730191f21bcc2cb40/receiver/awsfirehosereceiver/receiver.go#L301-L304

The `NewType` [function](https://github.com/open-telemetry/opentelemetry-collector/blob/e4f8b0119a5f04b9d5af0efabafcfda9980fcb83/component/identifiable.go#L51):

```
// NewType creates a type. It returns an error if the type is invalid.
// A type must
// - have at least one character,
// - start with an ASCII alphabetic character and
// - can only contain ASCII alphanumeric characters and '_'.
```

Instead of encoding being a string, it could be a `component.ID` to get rid of this bug.

## Steps to Reproduce

You can reproduce it using:
```yaml
extensions:
  awslogs_encoding/cloudwatch:
    format: cloudwatch_logs_subscription_filter

receivers:
  awsfirehose:
    endpoint: :1234
    encoding: awslogs_encoding/cloudwatch
```

You will see the collector fails with:
```
Error: cannot start pipelines: failed to start "awsfirehose/cwlogs" receiver: failed to start consumer: failed to load encoding extension: invalid component type: invalid character(s) in type "awslogs_encoding/cloudwatch"
```

## Expected Result

I expect it work without issues, and that the receiver can load the encoding extension by its ID.

## Actual Result

The collector does not start:
```
Error: cannot start pipelines: failed to start "awsfirehose/cwlogs" receiver: failed to start consumer: failed to load encoding extension: invalid component type: invalid character(s) in type "awslogs_encoding/cloudwatch"
```

### Collector version

v0.125.0

## Environment
OS: Ubuntu 24.10

### PR DESCRIPTION
**Pull request by axw**
#### Description

Fix the loading of extensions to treat the encoding name as a component ID, i.e. a type and optional name. This allows using an encoding extension with a name, e.g. "awslogs_encoding/cloudwatch".

#### Link to tracking issue

Fixes #39808

#### Testing

Unit tests added.

#### Documentation

None

### CODE REVIEW

File: receiver/awsfirehosereceiver/receiver.go [hunk 1]
```diff
@@ -296,12 +296,11 @@ func loadEncodingExtension[T any](host component.Host, encoding, signalType stri
 	return unmarshaler, nil
 }
 
-// encodingToComponentID converts an encoding string to a component ID using the given encoding as type.
+// encodingToComponentID attempts to parse the encoding string as a component ID.
 func encodingToComponentID(encoding string) (*component.ID, error) {
-	componentType, err := component.NewType(encoding)
-	if err != nil {
+	var id component.ID
```
Comment (constanca-m) [inline receiver/awsfirehosereceiver/receiver.go:301]: What if the `component.ID` is used in the configuration of the receiver instead?

Comment (axw) [reply receiver/awsfirehosereceiver/receiver.go:301]: I think that's a reasonable idea, but I'd like to leave it for a followup - I think it would just be cosmetic, and it's a lot more involved.

**Review by andrzej-stencel — APPROVED** [review]
Does this mean the [Kafka exporter](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/3ab18b424afaa0c8125c058bd66f1d5b087fa3ed/exporter/kafkaexporter/marshaler.go#L101) and [Kafka receiver](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/3ab18b424afaa0c8125c058bd66f1d5b087fa3ed/receiver/kafkareceiver/encoding.go#L131) have the same problem?

**Comment by axw** [comment]
@andrzej-stencel yes, I'll open issues for them.
