### PR TITLE
[receiver/sqlqueryreceiver] Fix tracking results by timestamp column

### LINKED ISSUE #35194: [receiver/sqlquery] Log signals reprocessed when tracking_column type is timestamp, and value has milliseconds precision
### Component(s)

internal/sqlquery, receiver/sqlquery

## Description

Milliseconds from timestamp column is trimmed during processing, when it's used as a tracking column. As a result, when `tracking_column` has timestamp type and value **has** milliseconds precision, rows are re-processed.

## Steps to Reproduce

Here is setup:
https://github.com/Grandys/otel-collector-sqlqueryreceiver-setup, branch `reporocess-ts-column `

```bash
git clone git@github.com:Grandys/otel-collector-sqlqueryreceiver-setup.git
cd otel-collector-sqlqueryreceiver-setup/
git checkout reporocess-ts-column
# Build custom otel collector with OCB
make run_rebuild
````

Verify collector output or check local LGTM (http://localhost:3000 admin/admin).

For example, when tracking has value `2024-09-15 16:45:16.222464`
And executed sql is:
```sql
select 'Datapoint value for ' || log_type || ' is ' || datapoint as datapoint, log_type, created_at
from logs_data
where created_at > $$1 order by created_at
```

`2024-09-15 16:45:16` is taken as a parameter (without `.222464`). As a result, the same rows are reprocessed.

## Expected Result

For my setup, I'd expect 4 log entries generated in total

## Actual Result

Log signals are generated every 10 seconds, for the same records, ex:

 Timestamp               | Log body                     | 
-------------------------|------------------------------| 
| 2024-09-15 19:05:13.244 | Datapoint value for db is 1  | 
| 2024-09-15 19:05:13.244 | Datapoint value for app is 4 | 
| 2024-09-15 19:05:13.244 | Datapoint value for web is 2 | 
| 2024-09-15 19:05:03.244 | Datapoint value for web is 2 | 
| 2024-09-15 19:05:03.244 | Datapoint value for app is 4 | 
| 2024-09-15 19:05:03.244 | Datapoint value for db is 1  | 
| 2024-09-15 19:04:53.244 | Datapoint value for web is 2 | 
| 2024-09-15 19:04:53.244 | Datapoint value for db is 1  | 
| 2024-09-15 19:04:53.244 | Datapoint value for app is 4 | 
| 2024-09-15 19:04:43.244 | Datapoint value for web is 2 | 
| 2024-09-15 19:04:43.244 | Datapoint value for app is 4 | 
| 2024-09-15 19:04:43.244 | Datapoint value for db is 1  | 
| 2024-09-15 19:04:33.245 | Datapoint value for web is 2 | 
| 2024-09-15 19:04:33.245 | Datapoint value for db is 1  | 
| 2024-09-15 19:04:33.245 | Datapoint value for app is 4 | 
| 2024-09-15 19:04:23.245 | Datapoint value for web is 2 | 
| 2024-09-15 19:04:23.245 | Datapoint value for app is 4 | 
| 2024-09-15 19:04:23.245 | Datapoint value for db is 1  | 
| 2024-09-15 19:04:13.245 | Datapoint value for db is 1  | 
| 2024-09-15 19:04:13.245 | Datapoint value for app is 4 | 
| 2024-09-15 19:04:13.245 | Datapoint value for web is 2 | 
| 2024-09-15 19:04:03.246 | Datapoint value for web is 2 | 
| 2024-09-15 19:04:03.246 | Datapoint value for app is 4 | 
| 2024-09-15 19:04:03.246 | Datapoint value for db is 1  |

### Collector version

v0.109.0

## Environment
OS: macOS Monterey
Compiler:  go1.22.6 darwin/amd64

### OpenTelemetry Collector configuration

```yaml
receivers:
  sqlquery:
    driver: postgres
    datasource: "host=localhost port=5432 user=otel password=otel database=otel sslmode=disable"
    queries:
      - sql: "select 'Datapoint value for ' || log_type || ' is ' || datapoint as datapoint, log_type, created_at from logs_data where created_at > $$1 order by created_at"
        tracking_column: created_at
        tracking_start_value: '2024-09-15 00:00:00'
        logs:
          - body_column: datapoint
            attribute_columns: [ "log_type" ]

exporters:
  debug:
    verbosity: detailed
  otlp/lgtm:
    endpoint: localhost:4317
    tls:
      insecure: true

processors:
  batch:
  resource:
    attributes:
      - key: service.name
        value: "sql-query-reader"
        action: insert

service:
  pipelines:
    metrics/sqlquery:
      receivers: [ sqlquery ]
      processors: [ resource, batch ]
      exporters: [ otlp/lgtm ]
    logs/sqlquery:
      receivers: [ sqlquery ]
      processors: [ resource, batch ]
      exporters: [ debug,otlp/lgtm ]
```

### Log output

_No response_

### Additional context

Table definition:
```sql
create table logs_data
(
    id         serial
        primary key,
    created_at timestamp,
    datapoint  integer,
    log_type   text
);
```

### PR DESCRIPTION
**Pull request by Grandys**
**Description:**

Formats retrieved time columns with milliseconds precision, so they are not reprocessed when used as a tracking_column

**Link to tracking Issue:** #35194

**Testing:** Added integration test, updated test data

**Documentation:** n/a

Closes #35194

### CODE REVIEW

File: internal/sqlquery/row_scanner.go [hunk 1]
```diff
@@ -32,7 +32,7 @@ func newRowScanner(colTypes []colType) *rowScanner {
 			}
 			format := "%v"
 			if t, isTime := v.(time.Time); isTime {
-				return t.Format(time.RFC3339), nil
+				return t.Format(time.RFC3339Nano), nil
```
Comment (crobert-1) [inline internal/sqlquery/row_scanner.go:35]: Is this a breaking change? From what you're describing, it looks like this bug only impacts users when timestamps are in `RFC3339Nano`, but it works as expected when timestamps are in `RFC3339`. Is that correct?

Is there some way to test which format the timestamp is in, and format accordingly? Or is there a reason we should always use `RFC3339Nano` instead of `RFC3339`?

Comment (Grandys) [reply internal/sqlquery/row_scanner.go:35]: > Is this a breaking change? 

It's not a breaking change - I marked this PR as `bug_fix` in the changelog. My other PR #35189 - is a breaking change.

> From what you're describing, it looks like this bug only impacts users when timestamps are in RFC3339Nano, but it works as expected when timestamps are in RFC3339. Is that correct?

If by timestamp in `RFC3339` format you mean that timestamp records in database don't have millisecond precision (ex. `2022-06-03 21:59:26.000000+00`, `2022-06-03 21:59:31.000000`) - then yes, error would not appear. 

But just by type inspection we can't know if client used `.000000` intentionally to avoid MS precision, or it's intended point in time.

> Is there some way to test which format the timestamp is in, and format accordingly? Or is there a reason we should always use RFC3339Nano instead of RFC3339?

`RFC3339Nano` is safer, `RFC3339` causes data loss for timestamp.

Comment (crobert-1) [reply internal/sqlquery/row_scanner.go:35]: I'm pretty ignorant on timestamp formats, so I'm clarifying to make sure I understand how this change will impact behavior for users.

My main question here is if a database is using the RFC3339 format for timestamps, will RFC3339Nano be able to properly process the timestamp?

Comment (Grandys) [reply internal/sqlquery/row_scanner.go:35]: Ok, I think I see your concern. To verify if `RFC3339Nano` is able to process data, I changed test data to have mix of `RFC3339Nano` and `RFC3339` [9b50140](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/35195/commits/9b50140bef21bbf0315e02fb829f7e51c9b4a269). 

My test still success, and so do other tests.

Here I checked in the debugger, how timestamp is formatted to string, depending which format is used

| Postgres timestamp | t.Format(time.RFC3339Nano) |t.Format(time.RFC3339) |
| ---- | ----- | ----|
| 2022-06-03 21:59:26+00 | 2022-06-03T21:59:26Z | 2022-06-03T21:59:26Z | 
| 2022-06-03 21:59:26.692991+00 | 2022-06-03T21:59:26.692991Z | 2022-06-03T21:59:26Z |
| 2022-06-03 21:59:29.212212+00 | 2022-06-03T21:59:29.212212Z | 2022-06-03T21:59:29Z |
| 2022-06-03 21:59:31+00 | 2022-06-03T21:59:31Z | 2022-06-03T21:59:31Z | 
| 2022-06-03 21:59:31.332121+00 | 2022-06-03T21:59:31.332121Z | 2022-06-03T21:59:31Z |

File: receiver/sqlqueryreceiver/integration_test.go [hunk 2]
```diff
@@ -125,6 +125,53 @@ func TestPostgresIntegrationLogsTrackingWithoutStorage(t *testing.T) {
...
+	require.NoError(t, err)
+
+	// Verify there's 5 logs received.
+	require.Eventuallyf(
+		t,
+		func() bool {
+			return consumer.LogRecordCount() > 0
+		},
+		1*time.Minute,
+		5*time.Second,
```
Comment (crobert-1) [inline receiver/sqlqueryreceiver/integration_test.go:164]:
```suggestion
		100*time.Milliseconds,
```
Minor nit: We don't need to wait 5 seconds between checks here, it may just make the test take longer than necessary.

File: internal/sqlquery/row_scanner.go (hunk 1 above)
Comment (crobert-1) [reply internal/sqlquery/row_scanner.go:35]: Thanks for clarifying, that's exactly what I was wondering!

**Review by crobert-1 — APPROVED** [review]
One minor nit, but it looks good. Thanks for making this change!

File: receiver/sqlqueryreceiver/integration_test.go (hunk 2 above)
Comment (Grandys) [reply receiver/sqlqueryreceiver/integration_test.go]: When tick == collection interval (which is also 100ms), problem with records reprocessing may not be detected by this test.
I agree, waiting for 5s is redundant, [I decreased it to 500ms](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/35195/commits/dc1924571d74b9d5a7a3fc0e23792fd5481f2d5e)

**Review by andrzej-stencel — APPROVED** [review]
Thank you for this fix @Grandys.

I'm only worried that we don't have test coverage for logs tracking for database engines other than PostgreSQL. This means that we're treading in the dark with this feature and changes to it like this valuable fix. As a result, there's a risk that this fix breaks the logs tracking feature for one of the untested engines (e.g. because the RFC3939Nano format is not supported).

I'm supportive of merging this fix, given that  the logs stability is currently `development`. We should have integrations tests for all supported database engines before we move logs support out of `development` into `alpha` stability or further.
