### PR TITLE
[chore][exporter/datadogexporter] fix data race in tests again

### LINKED ISSUE #39519: [exporter/datadog] Failing test: TestIntegrationLogs timing out
### Component(s)

exporter/datadog

### Describe the issue you're reporting

[Failing CI/CD link](https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/14570197648/job/40866048604?pr=39508)

<details open>
<summary>Full failure output</summary>
<br>

```
=== FAIL: .  (0.00s)
panic: test timed out after 10m0s
	running tests:
		TestIntegrationLogs (9m0s)

=== FAIL: . TestIntegrationLogs (unknown)
2025-04-21T08:33:04.039Z	info	datadogconnector/connector_native.go:115	Shutting down datadog connector
2025-04-21T08:33:04.039Z	info	datadog/zaplogger.go:39	Exiting...
2025-04-21T08:33:04.039Z	info	datadogconnector/connector_native.go:116	Stopping obfuscator and concentrator
2025-04-21T08:33:04.039Z	info	datadog/zaplogger.go:39	Exiting concentrator, computing remaining stats
2025-04-21T08:33:04.039Z	info	datadog/zaplogger.go:39	Exiting concentrator, computing remaining stats
2025-04-21T08:33:04.039Z	info	datadog/zaplogger.go:44	stopping the Forwarder
2025-04-21T08:33:04.039Z	info	datadog/zaplogger.go:39	domainForwarder stopped
2025-04-21T08:33:04.040Z	info	extensions/extensions.go:69	Stopping extensions...
2025-04-21T08:33:04.040Z	info	service@v0.124.0/service.go:345	Shutdown complete.
2025-04-21T08:33:04.069Z	info	service@v0.124.0/service.go:199	Setting up own telemetry...
2025-04-21T08:33:04.110Z	info	provider/provider.go:72	Resolved source	{"provider": "azure", "source": {"Kind":"host","Identifier":"c4955aa1-96b7-4bec-a5e0-2696e5c84cdd"}}
2025-04-21T08:33:04.110Z	info	datadogexporter/traces_exporter.go:241	Please enable feature gate datadog.EnableOperationAndResourceNameV2 for improved operation and resource name logic. This feature will be enabled by default in the future - if you have Datadog monitors or alerts set on operation/resource names, you may need to migrate them to the new convention.
2025-04-21T08:33:04.110Z	info	clientutil/api.go:41	Validating API key.
2025-04-21T08:33:04.111Z	info	clientutil/api.go:45	API key validation successful.
2025-04-21T08:33:04.112Z	info	service@v0.124.0/service.go:266	Starting otelcol...	{"Version": "tests", "NumCPU": 4}
2025-04-21T08:33:04.113Z	info	extensions/extensions.go:41	Starting extensions...
2025-04-21T08:33:04.114Z	info	prometheusreceiver/metrics_receiver.go:154	Starting discovery manager
2025-04-21T08:33:04.115Z	info	targetallocator/manager.go:184	Scrape job added	{"jobName": "otelcol"}
2025-04-21T08:33:04.115Z	info	prometheusreceiver/metrics_receiver.go:224	Starting scrape manager
2025-04-21T08:33:04.115Z	info	otlpreceiver@v0.124.0/otlp.go:116	Starting GRPC server	{"endpoint": "127.0.0.1:42791"}
2025-04-21T08:33:04.116Z	info	otlpreceiver@v0.124.0/otlp.go:173	Starting HTTP server	{"endpoint": "127.0.0.1:42791"}
2025-04-21T08:33:04.116Z	error	graph/graph.go:438	Failed to start component	{"error": "listen tcp 127.0.0.1:42791: bind: address already in use", "type": "Receiver", "id": "otlp"}
2025-04-21T08:33:04.116Z	info	service@v0.124.0/service.go:331	Starting shutdown...
2025-04-21T08:33:04.119Z	info	extensions/extensions.go:69	Stopping extensions...
2025-04-21T08:33:04.119Z	info	service@v0.124.0/service.go:345	Shutdown complete.
    integration_test.go:501: 
        	Error Trace:	/home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/exporter/datadogexporter/integrationtest/integration_test.go:501
        	            				/opt/hostedtoolcache/go/1.23.8/x64/src/runtime/asm_amd64.s:1700
        	Error:      	Received unexpected error:
        	            	cannot start pipelines: failed to start "otlp" receiver: listen tcp 127.0.0.1:42791: bind: address already in use
        	Test:       	TestIntegrationLogs
2025-04-21T08:33:04.134Z	warn	grpc@v1.71.1/clientconn.go:1406	[core] [Channel #21 SubChannel #22]grpc: addrConn.createTransport failed to connect to {Addr: "127.0.0.1:42791", ServerName: "127.0.0.1:42791", }. Err: connection error: desc = "transport: Error while dialing: dial tcp 127.0.0.1:42791: connect: connection refused"	{"grpc_log": true}
2025-04-21T08:33:05.135Z	warn	grpc@v1.71.1/clientconn.go:1406	[core] [Channel #21 SubChannel #22]grpc: addrConn.createTransport failed to connect to {Addr: "127.0.0.1:42791", ServerName: "127.0.0.1:42791", }. Err: connection error: desc = "transport: Error while dialing: dial tcp 127.0.0.1:42791: connect: connection refused"	{"grpc_log": true}
2025-04-21T08:33:06.440Z	warn	grpc@v1.71.1/clientconn.go:1406	[core] [Channel #21 SubChannel #22]grpc: addrConn.createTransport failed to connect to {Addr: "127.0.0.1:42791", ServerName: "127.0.0.1:42791", }. Err: connection error: desc = "transport: Error while dialing: dial tcp 127.0.0.1:42791: connect: connection refused"	{"grpc_log": true}
2025-04-21T08:33:09.164Z	warn	grpc@v1.71.1/clientconn.go:1406	[core] [Channel #21 SubChannel #22]grpc: addrConn.createTransport failed to connect to {Addr: "127.0.0.1:42791", ServerName: "127.0.0.1:42791", }. Err: connection error: desc = "transport: Error while dialing: dial tcp 127.0.0.1:42791: connect: connection refused"	{"grpc_log": true}
2025-04-21T08:33:12.562Z	warn	grpc@v1.71.1/clientconn.go:1406	[core] [Channel #21 SubChannel #22]grpc: addrConn.createTransport failed to connect to {Addr: "127.0.0.1:42791", ServerName: "127.0.0.1:42791", }. Err: connection error: desc = "transport: Error while dialing: dial tcp 127.0.0.1:42791: connect: connection refused"	{"grpc_log": true}
    integration_test.go:557: 
        	Error Trace:	/home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/exporter/datadogexporter/integrationtest/integration_test.go:557
        	            				/home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/exporter/datadogexporter/integrationtest/integration_test.go:508
        	Error:      	Received unexpected error:
        	            	context deadline exceeded: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing: dial tcp 127.0.0.1:42791: connect: connection refused"
        	Test:       	TestIntegrationLogs
2025-04-21T08:33:19.484Z	warn	grpc@v1.71.1/clientconn.go:1406	[core] [Channel #21 SubChannel #22]grpc: addrConn.createTransport failed to connect to {Addr: "127.0.0.1:42791", ServerName: "127.0.0.1:42791", }. Err: connection error: desc = "transport: Error while dialing: dial tcp 127.0.0.1:42791: connect: connection refused"	{"grpc_log": true}
2025-04-21T08:33:30.566Z	warn	grpc@v1.71.1/clientconn.go:1406	[core] [Channel #21 SubChannel #22]grpc: addrConn.createTransport failed to connect to {Addr: "127.0.0.1:42791", ServerName: "127.0.0.1:42791", }. Err: connection error: desc = "transport: Error while dialing: dial tcp 127.0.0.1:42791: connect: connection refused"	{"grpc_log": true}
2025-04-21T08:33:47.187Z	warn	grpc@v1.71.1/clientconn.go:1406	[core] [Channel #21 SubChannel #22]grpc: addrConn.createTransport failed to connect to {Addr: "127.0.0.1:42791", ServerName: "127.0.0.1:42791", }. Err: connection error: desc = "transport: Error while dialing: dial tcp 127.0.0.1:42791: connect: connection refused"	{"grpc_log": true}
2025-04-21T08:34:12.004Z	warn	grpc@v1.71.1/clientconn.go:1406	[core] [Channel #21 SubChannel #22]grpc: addrConn.createTransport failed to connect to {Addr: "127.0.0.1:42791", ServerName: "127.0.0.1:42791", }. Err: connection error: desc = "transport: Error while dialing: dial tcp 127.0.0.1:42791: connect: connection refused"	{"grpc_log": true}
2025-04-21T08:34:54.779Z	warn	grpc@v1.71.1/clientconn.go:1406	[core] [Channel #21 SubChannel #22]grpc: addrConn.createTransport failed to connect to {Addr: "127.0.0.1:42791", ServerName: "127.0.0.1:42791", }. Err: connection error: desc = "transport: Error while dialing: dial tcp 127.0.0.1:42791: connect: connection refused"	{"grpc_log": true}
2025-04-21T08:36:01.243Z	warn	grpc@v1.71.1/clientconn.go:1406	[core] [Channel #21 SubChannel #22]grpc: addrConn.createTransport failed to connect to {Addr: "127.0.0.1:42791", ServerName: "127.0.0.1:42791", }. Err: connection error: desc = "transport: Error while dialing: dial tcp 127.0.0.1:42791: connect: connection refused"	{"grpc_log": true}
2025-04-21T08:37:56.123Z	warn	grpc@v1.71.1/clientconn.go:1406	[core] [Channel #21 SubChannel #22]grpc: addrConn.createTransport failed to connect to {Addr: "127.0.0.1:42791", ServerName: "127.0.0.1:42791", }. Err: connection error: desc = "transport: Error while dialing: dial tcp 127.0.0.1:42791: connect: connection refused"	{"grpc_log": true}
2025-04-21T08:40:14.901Z	warn	grpc@v1.71.1/clientconn.go:1406	[core] [Channel #21 SubChannel #22]grpc: addrConn.createTransport failed to connect to {Addr: "127.0.0.1:42791", ServerName: "127.0.0.1:42791", }. Err: connection error: desc = "transport: Error while dialing: dial tcp 127.0.0.1:42791: connect: connection refused"	{"grpc_log": true}
2025-04-21T08:41:58.[403](https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/14570197648/job/40866048604?pr=39508#step:8:404)Z	warn	grpc@v1.71.1/clientconn.go:1406	[core] [Channel #21 SubChannel #22]grpc: addrConn.createTransport failed to connect to {Addr: "127.0.0.1:42791", ServerName: "127.0.0.1:42791", }. Err: connection error: desc = "transport: Error while dialing: dial tcp 127.0.0.1:42791: connect: connection refused"	{"grpc_log": true}
```

DONE 4 tests, 2 failures in 607.008s
</details>

I've attached a text file with the full test dump as it was too many characters for an issue description.

### LINKED ISSUE #39780: [github.com/open-telemetry/opentelemetry-collector-contrib/exporter/datadogexporter/integrationtest]: Report for failed tests on main
Auto-generated report for `__run_3` job build.

Link to failed build: https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/14754645510

#### Test Failures
-  `TestIntegrationHostMetrics_WithRemapping_Serializer`

**Note**: Information about any subsequent build failures that happen while
this issue is open, will be added as comments with more information to this issue.

### LINKED ISSUE #39782: [github.com/open-telemetry/opentelemetry-collector-contrib/exporter/datadogexporter/integrationtest]: Report for failed tests on main
Auto-generated report for `__run_3` job build.

Link to failed build: https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/14754883727

#### Test Failures
-  `TestIntegrationHostMetrics_WithRemapping_LegacyMetricClient`

**Note**: Information about any subsequent build failures that happen while
this issue is open, will be added as comments with more information to this issue.

### PR DESCRIPTION
**Pull request by songy23**
#### Description
Having both the otlp grpc exporter & otlp grpc recevier in the tests introduces data race, so move all tests to use HTTP instead. Also make sure to properly close all go routines before tests complete.

#### Link to tracking issue
Fixes https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/39782
Fixes https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/39780
Fixes https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/39519
Fixes http://github.com/open-telemetry/opentelemetry-collector-contrib/issues/39804

### CODE REVIEW

File: exporter/datadogexporter/integrationtest/integration_test.go [hunk 1]
```diff
@@ -730,3 +729,95 @@ func seriesFromAPIClient(t *testing.T, metricsBytes []byte, expectedMetrics map[
 	}
 	return metricMap, nil
 }
+
+func TestIntegrationInternalMetrics(t *testing.T) {
```
Comment (songy23) [inline exporter/datadogexporter/integrationtest/integration_test.go:733]: This is moved from no_race_integration_test

File: exporter/datadogexporter/integrationtest/integration_test.go [hunk 2]
```diff
@@ -642,10 +635,16 @@ func testIntegrationHostMetrics(t *testing.T, expectedMetrics map[string]struct{
 	// 2. Start in-process collector
 	factories := getIntegrationTestComponents(t)
 	app := getIntegrationTestCollector(t, "integration_test_host_metrics_config.yaml", factories)
+	var wg sync.WaitGroup
+	wg.Add(1)
 	go func() {
-		assert.NoError(t, app.Run(context.Background()))
+		_ = app.Run(context.Background()) // ignore shutdown error
```
Comment (mx-psi) [inline exporter/datadogexporter/integrationtest/integration_test.go:641]: I think this needs some explanation in the code as to why this error is being ignored

Comment (songy23) [reply exporter/datadogexporter/integrationtest/integration_test.go]: Done. This is https://github.com/open-telemetry/opentelemetry-collector/issues/12944

**Review by mx-psi — APPROVED** [review]
