### PR TITLE
[processor/routing] Do not err on failure to build exporters

### LINKED ISSUE #6920: Issue with routing processor
**Describe the bug**
Processor says exporter is not found for `default_exporters`.

**Steps to reproduce**
Create an OpenTelemetryCollector resource with the following config:
```
receivers:
  otlp:
    protocols:
      grpc:
processors:
  routing:
    from_attribute: X-OTLP-Tenant
    default_exporters: [otlp/prod]
    table:
    - value: dev
      exporters: [otlp/dev]
exporters:
  otlp/prod:
    endpoint: internal.tracing.svc.cluster.local
  otlp/dev:
    endpoint: internal-dev.tracing.svc.cluster.local
service:
  pipelines:
    traces/otlp:
      receivers: [otlp]
      processors: [routing]
      exporters: [otlp/prod, otlp/dev]
```

**What did you expect to see?**
Successfully created container

**What did you see instead?**
Crashlooping container

```
Error: cannot start processors: error registering default exporter "otlp/prod": exporter not found
2021/12/20 19:28:34 collector server run finished with error: cannot start processors: error registering default exporter "otlp/prod": exporter not found
```

**What version did you use?**
0.40.0

**Environment**
EKS bottlerocket k8s 1.20

Also, I _believe_ the documented example for this processor is wrong. It shows `default_exporters` as a string, but I think it is supposed to be a list of strings. Based off [this](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/processor/routingprocessor/config.go#L29).

### PR DESCRIPTION
**Pull request by jpkrohling**
When registering the exporters, it is possible that an error is returned when the default exporter isn't found, which is the case when the processor is specified only for one pipeline type for multiple exists.

Given that we can't check in which pipelines the processor is active, we can't do much more than just ignore a possible configuration error.

Fixes #6920

Signed-off-by: Juraci Paixão Kröhling <juraci@kroehling.de>

### CODE REVIEW

**Comment by jpkrohling** [comment]
@codeboten, could you please review this one?

File: processor/routingprocessor/router.go [hunk 1]
```diff
@@ -418,7 +439,7 @@ func (r *router) registerExportersForDefaultRoute(available ExporterMap) error {
 		v, ok := available[exp]
 		if !ok {
 			return fmt.Errorf("error registering default exporter %q: %w",
-				exp, errExporterNotFound,
+				exp, errDefaultExporterNotFound,
```
Comment (pmm-sumo) [inline processor/routingprocessor/router.go:442]: I'm wondering if instead of returning the error, warning could be logged in this function and the whole block in `registerExports` could be kept much simpler?

Comment (jpkrohling) [reply processor/routingprocessor/router.go:442]: Sounds reasonable. Let me try that.

Comment (jpkrohling) [reply processor/routingprocessor/router.go:442]: The advantage of doing it as part of `registerExporters` is that we can tell the user what's the pipeline type that is being affected. I think this better user experience is worth the extra complexity, which isn't that complex anyway. What do you think?

Comment (pmm-sumo) [reply processor/routingprocessor/router.go:442]: I agree. As another option, the signal could be provided as argument for this function. It adds some extra code as well though (maybe it's a bit simpler, but the change is in more places, so I am not convinced if it's really better)

**Review by pmm-sumo — APPROVED** [review]

File: processor/routingprocessor/router.go (hunk 1 above)
Comment (jpkrohling) [reply processor/routingprocessor/router.go:442]: I thought about it as well, but it doesn't feel right to pass it only for logging purposes.

**Review by codeboten — APPROVED** [review]
