### PR TITLE
[receiver/datadog] Support 128 bits TraceID coming from Datadog

### LINKED ISSUE #36926: Broken trace context propagation: OTel `Trace ID` of DD agent spans converted by OTel Col Datadog Receiver are wrong
### Component(s)

receiver/datadog

## Description

When doing W3C Trace Context Propagation from an app instrumented with OTel to an app instrumented with the Datadog agent and the Datadog agent sending spans to the OTel Collector Datadog Receiver, the Trace Id reported by the OTel Collector Datadog
Receiver is different from the Trace ID of the parent spans, breaking the trace.

I can't confirm but I suspect that this is caused by the logic in the OTel Col Datadog 
Receiver to produce the OTel Trace ID from the Datadog ids.

Architecture:

```
                                                                   
 ┌──────────┐                               ┌───────────┐───┐      
 │OTel Java ┼──────┐                        │           │   │      
 └─────┬────┘      │                        │Receiver   │ O │      
       │           │                        │           │ T │      
       │           │                        │───────────│ e │      
       │           └───────────────────────►│ OTLP      │ l │      
       │                                    │           │   │      
       │traceparent: trace=xyz, parent=abc  │           │ C │      
       │                                    │───────────│ o │      
       │                                    │           │ l │      
 ┌─────▼──────┐ ┌──────────────────────────►┤Datadog    │   │      
 │Datadog Java┼─┘                           └───────────┘───┘      
 └────────────┘                             span:                  
                                              spanId=...           
                                              parent=abc <--CORRECT
                                              traceId=uvw <--WRONG 
```

OTel Collector debug log.
* First span: HTTP client call span emitted by a Java Spring Boot app instrumented by the OTel Java Agent v1.44.1 with 
   * `traceId=37940834c74a2dfc11835c979eca1433`
   * `spanId=bb4331d223d59950`
* Second span: HTTP Server span emitted by a Spring Boot app instrumented by the Datadog Java Agent v1.44.1 with
   * `parentId=bb4331d223d59950` as expected
   * `traceId=000000000000000011835c979eca1433` which is NOT expected, we expect `37940834c74a2dfc11835c979eca1433`

```
Resource SchemaURL: https://opentelemetry.io/schemas/1.24.0
Resource attributes:
     -> deployment.environment.name: Str(staging)
     -> host.arch: Str(aarch64)
     -> host.name: Str(cyrille-le-clerc-macbook.local)
     -> os.description: Str(Mac OS X 15.2)
     -> os.type: Str(darwin)
     -> process.command_args: Slice([...,"-jar","target/checkout-1.1-SNAPSHOT.jar"])
     -> process.executable.path: Str(.../bin/java)
     -> process.pid: Int(14768)
     -> process.runtime.description: Str(Homebrew OpenJDK 64-Bit Server VM 17.0.13+0)
     -> process.runtime.name: Str(OpenJDK Runtime Environment)
     -> process.runtime.version: Str(17.0.13+0)
     -> service.instance.id: Str(ccad3c44-aebc-4f8b-96b9-c4ed6a5433c4)
     -> service.name: Str(checkout)
     -> service.namespace: Str(shop)
     -> service.version: Str(1.1)
     -> telemetry.distro.name: Str(opentelemetry-java-instrumentation)
     -> telemetry.distro.version: Str(2.10.0)
     -> telemetry.sdk.language: Str(java)
     -> telemetry.sdk.name: Str(opentelemetry)
     -> telemetry.sdk.version: Str(1.44.1)
ScopeSpans #0
ScopeSpans SchemaURL:
InstrumentationScope io.opentelemetry.java-http-client 2.10.0-alpha
Span #0
    Trace ID       : 37940834c74a2dfc11835c979eca1433
    Parent ID      : 179ce2ee48649594
    ID             : bb4331d223d59950
    Name           : POST
    Kind           : Client
    Start time     : 2024-12-23 17:34:54.397226541 +0000 UTC
    End time       : 2024-12-23 17:34:54.63652375 +0000 UTC
    Status code    : Unset
    Status message :
Attributes:
     -> server.address: Str(shipping.local)
     -> tenant_id: Str(tenant-1)
     -> http.request.method: Str(POST)
     -> network.protocol.version: Str(1.1)
     -> http.response.status_code: Int(200)
     -> thread.id: Int(160)
     -> server.port: Int(8088)
     -> thread.name: Str(grpc-default-executor-36)
     -> url.full: Str(http://shipping.local:8088/shipOrder)

ResourceSpans #1
Resource SchemaURL: https://opentelemetry.io/schemas/1.16.0
Resource attributes:
     -> telemetry.sdk.language: Str(java)
     -> process.runtime.version: Str(17.0.13)
     -> service.version: Str(1.1)
     -> telemetry.sdk.version: Str(Datadog-1.44.1~13a9a2d011)
     -> telemetry.sdk.name: Str(Datadog)
     -> service.name: Str(shipping)
     -> host.name: Str(localhost)
     -> os.type: Str(darwin)
ScopeSpans #0
ScopeSpans SchemaURL:
InstrumentationScope Datadog 1.44.1~13a9a2d011
Span #0
    Trace ID       : 000000000000000011835c979eca1433
    Parent ID      : bb4331d223d59950
    ID             : 6176a9d3ea94c1f7
    Name           : servlet.request
    Kind           : Server
    Start time     : 2024-12-23 17:34:54.453192875 +0000 UTC
    End time       : 2024-12-23 17:34:54.638774084 +0000 UTC
    Status code    : Ok
    Status message :
Attributes:
     -> dd.span.Resource: Str(POST /shipOrder)
     -> sampling.priority: Str(1.000000)
     -> datadog.span.id: Str(7022987396569678327)
     -> datadog.trace.id: Str(1261954126867731507)
     -> servlet.path: Str(/shipOrder)
     -> deployment.environment: Str(production)
     -> peer.ipv4: Str(127.0.0.1)
     -> thread.name: Str(http-nio-8088-exec-1)
     -> language: Str(jvm)
     -> service.version: Str(1.1)
     -> span.kind: Str(server)
     -> http.method: Str(POST)
     -> _dd.p.dm: Str(-0)
     -> http.status_code: Str(200)
     -> _dd.tracer_host: Str(cyrille-le-clerc-macbook.local)
     -> http.url: Str(http://shipping.local:8088/shipOrder)
     -> http.hostname: Str(shipping.local)
     -> _dd.p.tid: Str(37940834c74a2dfc)
     -> servlet.context: Str(/)
     -> http.route: Str(/shipOrder)
     -> runtime-id: Str(8265563a-4256-4741-ba0c-ebbb676d4473)
     -> http.useragent: Str(Java-http-client/17.0.13)
     -> component: Str(tomcat-server)
     -> thread.id: Double(37)
     -> process.pid: Double(73021)
     -> _dd.profiling.enabled: Double(0)
     -> peer.port: Double(64145)
     -> _dd.trace_span_attribute_schema: Double(0)
     -> _sampling_priority_v1: Double(1)
     -> _dd.measured: Double(1)
     -> _dd.top_level: Double(1)
```

## Steps to Reproduce

* Setup an OTel Col with both OTLP and Datadog receivers and the debug exporter
* Create two Spring Boot apps, one "upstream_app" calling the "downstream_app" through an HTTP call
   * On the HTTP handler of the "downstream_app", dump the `traceparent` http header to verify the context is propagated
* Instrument the upstream app with OTel Java Auto Instr v2.10.0
* Instrument the downstream app with dd-trace-java v1.44.1

```
export DD_TRACE_AGENT_URL="http://localhost:8126"
# disabling remote config to ensure no weird behavior 
export DD_REMOTE_CONFIGURATION_ENABLED=false

java \
     -javaagent:"$DATADOG_AGENT_JAR" \
     -Dserver.port=8088 \
     -jar target/shipping-1.1-SNAPSHOT.jar
```

* Invoke the "upstream_app" to trigger an http call to the "downstream_app"
* Inspect the produced spans in the OTel collector logs

## Expected Result

* The spans in the otel collector logs show that the trace context is properly propagated: there is just one `traceID` and the `parentId` of the HTTP handler of the "downstream_app" matches the `spanId` of th HTTP call of the "upstream_App".

## Actual Result

The `parentId` is properly propagated by the `TraceId` is wrong.

### Collector version

v0.116.0

## Environment
MacOS 15.2

Demo app:
* http client call: https://github.com/cyrille-leclerc/my-shopping-cart/blob/934ff3c0aa99af9c92e8a80ea51cb9a833ef6e1a/checkout/src/main/java/com/mycompany/checkout/CheckoutServiceServer.java#L112-L115
* http server handler: https://github.com/cyrille-leclerc/my-shopping-cart/blob/934ff3c0aa99af9c92e8a80ea51cb9a833ef6e1a/shipping/src/main/java/com/mycompany/shipping/ShippingController.java#L31-L49

### OpenTelemetry Collector configuration

```yaml
receivers:
  datadog:
    endpoint: localhost:8126
    read_timeout: 60s
exporters:
  debug:
    verbosity: detailed
service:
  pipelines:
    traces:
      receivers: [datadog]
      processors: 
      exporters: [debug]
```

### Log output

```shell
See bug description
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by xiu**
#### Description
With this commit, we add support for 128 bits TraceIDs coming from Datadog instrumented services. This can happen when an OTel instrumented service calls a downstream Datadog instrumented one. Datadog instrumentation libraries store the 128 bits TraceID into two different fields:
* TraceID: lower 64 bits of the 128 bits TraceID 
* _dd.p.tid: upper 64 bits of the 128 bits TraceID

This commit adds logic that reconstructs the 128 bits TraceID. Before this commit, only the lower 64 bits were used as TraceID.

#### Link to tracking issue
Fixes #36926

#### Testing
Tested the setup with the following chain: OTel Instrumented Service --> Datadog Instrumented Service -> OTel Instrumented Service. The TraceID was maintained on the whole chain.

Also added a unit test (`TestToTraces64to128bits`).

#### Documentation
Updated README.md in [58129d5](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/39654/commits/58129d562a1302e849e95f9a4ad98446e35cc5a1)

### CODE REVIEW

File: receiver/datadogreceiver/internal/translator/traces_translator.go [hunk 1]
```diff
@@ -90,6 +90,13 @@ func ToTraces(payload *pb.TracerPayload, req *http.Request) ptrace.Traces {
 	// now instead of being a span level attribute.
 	groupByService := make(map[string]ptrace.SpanSlice)
 
+	// Datadog traces split a 128 bits trace id in two parts: TraceID and Tags._dd_p_tid. This happens if the
+	// instrumented service received a TraceContext from an OTel instrumented service. When it happens, we need
+	// to concatenate the two into newSpan.TraceID.
+	// The following map keeps track of the TraceIDs we process as only the first span has the upper 64 bits from the
+	// 128 bits trace ID.
+	map64to128 := make(map[uint64]pcommon.TraceID)
```
Comment (dehaansa) [inline receiver/datadogreceiver/internal/translator/traces_translator.go:98]: I'm concerned about an unbounded cache. While each entry is small, this is just unbounded memory growth.

It looks like the `spanmetricsconnector` uses a LRU (least recently used) cache from hashicorp `"github.com/hashicorp/golang-lru/v2/simplelru"` that would be a good candidate to use here to ensure there is a limit to the size of this cache.

**Review by dehaansa — COMMENTED** [review]
Thanks for taking the time to dig in to this issue!

This seems like a very useful fix, but would probably constitute a breaking change for existing users of the component. As such I think we'll need to make it opt-in using a featuregate.

You can check for examples of using featuregates in other components, but they're relatively easy to set up. If you have one set to StageAlpha, it will be disabled by default, and then in later versions we will move it to Beta (enabled by default) and then the gate can later be removed. The gate will then need to be configured at runtime using a flag like `--feature-gates=receiver.datadogreceiver.Enable128BitTraceID`

Here's an example of what defining the gate looks like in code, copied and modified slightly from another component

```
var FullTraceIDFeatureGate = featuregate.GlobalRegistry().MustRegister(
	"receiver.datadogreceiver.Enable128BitTraceID",
	featuregate.StageAlpha,
	featuregate.WithRegisterDescription("<description."),
	featuregate.WithRegisterFromVersion("v0.125.0"),
)

...

if FullTraceIDFeatureGate.Enabled() {
...

File: receiver/datadogreceiver/internal/translator/traces_translator.go (hunk 1 above)
Comment (xiu) [reply receiver/datadogreceiver/internal/translator/traces_translator.go:98]: This is a good point, the cache would just be bound to that one `ToTraces` run, but I'm not sure what a good size for it would be. Should it be configurable? If not, what would a good value be?

Comment (xiu) [reply receiver/datadogreceiver/internal/translator/traces_translator.go:98]: Actually it seems fairly easy to add such a config, I'll add that.

Comment (xiu) [reply receiver/datadogreceiver/internal/translator/traces_translator.go]: Done in [90eb40c](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/39654/commits/90eb40ca0f6cbf2cb734dfbe863e78f0b97a6387)

**Comment by xiu** [comment]
> Thanks for taking the time to dig in to this issue!
> 
> This seems like a very useful fix, but would probably constitute a breaking change for existing users of the component. As such I think we'll need to make it opt-in using a featuregate.
> 
> You can check for examples of using featuregates in other components, but they're relatively easy to set up. If you have one set to StageAlpha, it will be disabled by default, and then in later versions we will move it to Beta (enabled by default) and then the gate can later be removed. The gate will then need to be configured at runtime using a flag like `--feature-gates=receiver.datadogreceiver.Enable128BitTraceID`
> 
> Here's an example of what defining the gate looks like in code, copied and modified slightly from another component
> 
> ```
> var FullTraceIDFeatureGate = featuregate.GlobalRegistry().MustRegister(
> 	"receiver.datadogreceiver.Enable128BitTraceID",
> 	featuregate.StageAlpha,
> 	featuregate.WithRegisterDescription("<description."),
> 	featuregate.WithRegisterFromVersion("v0.125.0"),
> )
> 
> ...
> 
> if FullTraceIDFeatureGate.Enabled() {
> ...
> ```

@dehaansa Thanks for reviewing! 

I've added a featuregate in [af83cf2](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/39654/commits/af83cf2a47688423e45f81c683413fc6e3c9fe68), let me know if anything.

**Review by dehaansa — APPROVED** [review]
LGTM, will try to get codeowner review before marking ready for merge.

**Comment by cyrille-leclerc** [comment]
When testing activating `--feature-gates=receiver.datadogreceiver.Enable128BitTraceID`, I get the following failure. I'll capture the trace id to better understand:

```
2025-05-03T17:17:06.934+0200    error   datadogreceiver@v0.125.0/receiver.go:254        Error converting traces {"otelcol.component.id": "datadog", "otelcol.component.kind": "receiver", "otelcol.signal": "traces", "error": "hex encoded trace-id must have length equals to 32"}
github.com/open-telemetry/opentelemetry-collector-contrib/receiver/datadogreceiver.(*datadogReceiver).handleTraces
        github.com/open-telemetry/opentelemetry-collector-contrib/receiver/datadogreceiver@v0.125.0/receiver.go:254
net/http.HandlerFunc.ServeHTTP
        net/http/server.go:2294
net/http.(*ServeMux).ServeHTTP
        net/http/server.go:2822
go.opentelemetry.io/collector/config/confighttp.(*decompressor).ServeHTTP
        go.opentelemetry.io/collector/config/confighttp@v0.125.1-0.20250430101735-2ecd0b7f95cd/compression.go:183
go.opentelemetry.io/collector/config/confighttp.(*ServerConfig).ToServer.maxRequestBodySizeInterceptor.func2
        go.opentelemetry.io/collector/config/confighttp@v0.125.1-0.20250430101735-2ecd0b7f95cd/confighttp.go:615
net/http.HandlerFunc.ServeHTTP
        net/http/server.go:2294
go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp.(*middleware).serveHTTP
        go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp@v0.60.0/handler.go:179
go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp.NewMiddleware.func1.1
        go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp@v0.60.0/handler.go:67
net/http.HandlerFunc.ServeHTTP
        net/http/server.go:2294
go.opentelemetry.io/collector/config/confighttp.(*clientInfoHandler).ServeHTTP
        go.opentelemetry.io/collector/config/confighttp@v0.125.1-0.20250430101735-2ecd0b7f95cd/clientinfohandler.go:26
net/http.serverHandler.ServeHTTP
        net/http/server.go:3301
net/http.(*conn).serve
        net/http/server.go:2102
2025-05-03T17:17:09.015+0200    error   datadogreceiver@v0.125.0/receiver.go:254        Error converting traces {"otelcol.component.id": "datadog", "otelcol.component.kind": "receiver", "otelcol.signal": "traces", "error": "hex encoded trace-id must have length equals to 32"}
github.com/open-telemetry/opentelemetry-collector-contrib/receiver/datadogreceiver.(*datadogReceiver).handleTraces
        github.com/open-telemetry/opentelemetry-collector-contrib/receiver/datadogreceiver@v0.125.0/receiver.go:254
net/http.HandlerFunc.ServeHTTP
        net/http/server.go:2294
net/http.(*ServeMux).ServeHTTP
        net/http/server.go:2822
go.opentelemetry.io/collector/config/confighttp.(*decompressor).ServeHTTP
        go.opentelemetry.io/collector/config/confighttp@v0.125.1-0.20250430101735-2ecd0b7f95cd/compression.go:183
go.opentelemetry.io/collector/config/confighttp.(*ServerConfig).ToServer.maxRequestBodySizeInterceptor.func2
        go.opentelemetry.io/collector/config/confighttp@v0.125.1-0.20250430101735-2ecd0b7f95cd/confighttp.go:615
net/http.HandlerFunc.ServeHTTP
        net/http/server.go:2294
go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp.(*middleware).serveHTTP
        go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp@v0.60.0/handler.go:179
go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp.NewMiddleware.func1.1
        go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp@v0.60.0/handler.go:67
net/http.HandlerFunc.ServeHTTP
        net/http/server.go:2294
go.opentelemetry.io/collector/config/confighttp.(*clientInfoHandler).ServeHTTP
        go.opentelemetry.io/collector/config/confighttp@v0.125.1-0.20250430101735-2ecd0b7f95cd/clientinfohandler.go:26
net/http.serverHandler.ServeHTTP
        net/http/server.go:3301
net/http.(*conn).serve
        net/http/server.go:2102
^C2025-05-03T17:17:09.866+0200  info    otelcol@v0.125.1-0.20250430101735-2ecd0b7f95cd/collector.go:358 Received signal from OS {"signal": "interrupt"}
2025-05-03T17:17:09.866+0200    info    service@v0.125.1-0.20250430101735-2ecd0b7f95cd/service.go:331   Starting shutdown...
2025-05-03T17:17:09.866+0200    info    healthcheck/handler.go:132      Health Check state change       {"otelcol.component.id": "health_check", "otelcol.component.kind": "extension", "status": "unavailable"}
2025-05-03T17:17:09.867+0200    info    spanmetricsconnector@v0.125.0/connector.go:219  Shutting down spanmetrics connector     {"otelcol.component.id": "spanmetrics", "otelcol.component.kind": "connector", "otelcol.signal": "traces", "otelcol.signal.output": "metrics"}
2025-05-03T17:17:09.867+0200    info    spanmetricsconnector@v0.125.0/connector.go:221  Stopping ticker {"otelcol.component.id": "spanmetrics", "otelcol.component.kind": "connector", "otelcol.signal": "traces", "otelcol.signal.output": "metrics"}
2025-05-03T17:17:09.867+0200    info    grafanacloudconnector@v0.125.0/connector.go:114 Stopping Grafana Cloud connector        {"otelcol.component.id": "grafanacloud", "otelcol.component.kind": "connector", "otelcol.signal": "traces", "otelcol.signal.output": "metrics"}
2025-05-03T17:17:10.485+0200    info    extensions/extensions.go:69     Stopping extensions...
2025-05-03T17:17:10.485+0200    info    service@v0.125.1-0.20250430101735-2ecd0b7f95cd/service.go:345   Shutdown complete.
```

File: receiver/datadogreceiver/internal/translator/traces_translator.go [hunk 2]
```diff
@@ -102,6 +103,33 @@ func ToTraces(payload *pb.TracerPayload, req *http.Request) ptrace.Traces {
...
+			//
+			// Reconstructing the 128 bits TraceID, if available or cached.
+			// Note: This may not be resilient to related spans being flushed separately in datadog's tracing libraries.
+			//       It might also not work if multiple datadog instrumented services are chained.
+			//
+			// This is currently gated by a feature gate. If we don't get a cache here, we don't enable this behavior.
+			if traceIDCache != nil {
+				if val, ok := span.Meta["_dd.p.tid"]; ok {
+					hexTraceID := val + strconv.FormatUint(span.TraceID, 16)
+					traceID, err := oteltrace.TraceIDFromHex(hexTraceID)
```
Comment (cyrille-leclerc) [inline receiver/datadogreceiver/internal/translator/traces_translator.go:121]: Shall we enrich the error message with the provided `hexTraceID` to troubleshoot the error `hex encoded trace-id must have length equals to 32`?

File: receiver/datadogreceiver/internal/translator/traces_translator.go [hunk 3]
```diff
@@ -195,14 +223,14 @@ func tagsToSpanLinks(tags map[string]string, dest ptrace.SpanLinkSlice) error {
 		link := dest.AppendEmpty()
 
 		// Convert trace id.
-		rawTrace, errTrace := trace.TraceIDFromHex(span.TraceID)
+		rawTrace, errTrace := oteltrace.TraceIDFromHex(span.TraceID)
 		if errTrace != nil {
```
Comment (cyrille-leclerc) [inline receiver/datadogreceiver/internal/translator/traces_translator.go:227]: Ditto, shall we enrich the error message with the provided `hexTraceID` to troubleshoot the error `hex encoded trace-id must have length equals to 32`?

Comment (xiu) [reply receiver/datadogreceiver/internal/translator/traces_translator.go:227]: Added a wrapping here and on the call to SpanIDFromHex below as well (not related to this PR). This gets me to wonder whether span links will work with the reconstructed spanIDs, I'll need to test that.

File: receiver/datadogreceiver/internal/translator/traces_translator.go (hunk 2 above)
Comment (xiu) [reply receiver/datadogreceiver/internal/translator/traces_translator.go:121]: Added

**Comment by cyrille-leclerc** [comment]
```
2025-05-04T14:46:39.095+0200    error   datadogreceiver@v0.125.0/receiver.go:254        Error converting traces {"otelcol.component.id": "datadog", "otelcol.component.kind": "receiver", "otelcol.signal": "traces", "error": "error converting to a 128bit traceid (_dd.p.tid: 681761ae00000000 - span.TraceID: 531758935570545189): hex encoded trace-id must have length equals to 32"}
```

<details>
<summary>OTel Col stack trace</summary>
```
2025-05-04T14:46:39.095+0200    error   datadogreceiver@v0.125.0/receiver.go:254        Error converting traces {"otelcol.component.id": "datadog", "otelcol.component.kind": "receiver", "otelcol.signal": "traces", "error": "error converting to a 128bit traceid (_dd.p.tid: 681761ae00000000 - span.TraceID: 531758935570545189): hex encoded trace-id must have length equals to 32"}
github.com/open-telemetry/opentelemetry-collector-contrib/receiver/datadogreceiver.(*datadogReceiver).handleTraces
        github.com/open-telemetry/opentelemetry-collector-contrib/receiver/datadogreceiver@v0.125.0/receiver.go:254
net/http.HandlerFunc.ServeHTTP
        net/http/server.go:2294
net/http.(*ServeMux).ServeHTTP
        net/http/server.go:2822
go.opentelemetry.io/collector/config/confighttp.(*decompressor).ServeHTTP
        go.opentelemetry.io/collector/config/confighttp@v0.125.1-0.20250430101735-2ecd0b7f95cd/compression.go:183
go.opentelemetry.io/collector/config/confighttp.(*ServerConfig).ToServer.maxRequestBodySizeInterceptor.func2
        go.opentelemetry.io/collector/config/confighttp@v0.125.1-0.20250430101735-2ecd0b7f95cd/confighttp.go:615
net/http.HandlerFunc.ServeHTTP
        net/http/server.go:2294
go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp.(*middleware).serveHTTP
        go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp@v0.60.0/handler.go:179
go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp.NewMiddleware.func1.1
        go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp@v0.60.0/handler.go:67
net/http.HandlerFunc.ServeHTTP
        net/http/server.go:2294
go.opentelemetry.io/collector/config/confighttp.(*clientInfoHandler).ServeHTTP
        go.opentelemetry.io/collector/config/confighttp@v0.125.1-0.20250430101735-2ecd0b7f95cd/clientinfohandler.go:26
net/http.serverHandler.ServeHTTP
        net/http/server.go:3301
net/http.(*conn).serve
        net/http/server.go:2102
```
</details>

**Comment by xiu** [comment]
Thanks for testing and the help debugging the issue! 
I believe I've fixed the issue with https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/39654/commits/b3f8d1d25533cce14398f726fbf1d205f9572d1a, it was due to a naive string concatenation rather than working at the byte level through `uInt64ToTraceID`. 

I've also improved error handling so as not to reject the whole `ToTraces` run when an error in encountered but rather keep the 64-bit trace id.

**Comment by cyrille-leclerc** [comment]
I could successfully test the fix:
* Upstream service called `frontend` instrumented with otel java auto-instr
* Downstream service `shipping`  instrumented with dd-trace-java emitting telemetry to the otelcol datadog receiver

With otelcol 0.125.0, the traces of the `frontend` service don't connect the `shipping` service which is an error.
With otelcol `--feature-gates=receiver.datadogreceiver.Enable128BitTraceID`, the  the traces of the `frontend` service don't connect the `shipping` service which is the desired behaviour.

**Comment by xiu** [comment]
Vulnerability addressed in https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/39852

**Comment by dehaansa** [comment]
Could we get a codeowner review? @boostchicken @gouthamve @MovieStoreGuy

**Review by MovieStoreGuy — APPROVED** [review]

**Comment by MovieStoreGuy** [comment]
Please resolve the conflicts :)

**Comment by xiu** [comment]
@MovieStoreGuy done!
