### PR TITLE
[pkg/stanza] propagate globbing io errors for logging

### LINKED ISSUE #23768: [receiver/filelog]: Log glob IO errors
### Component(s)

receiver/filelog

### Describe the issue you're reporting

Currently, we are globbing and ignoring any IO errors, which is the default behavior of the [glob library](https://github.com/bmatcuk/doublestar) we are using. However, this means that any errors that are gotten here are swallowed silently by the receiver.

https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/c15794f8b3ad8bdf1bbf5abfba8486df4ad1b7c9/pkg/stanza/fileconsumer/finder.go#L21C2-L21C2

Instead, I think it would be ideal if we used the `WithFailOnIOErrors` option (https://pkg.go.dev/github.com/bmatcuk/doublestar/v4#WithFailOnIOErrors) initially, and if fails, log a warning (or maybe even just a debug level log?), and fall back to using the current behavior. 

This would help to debug instances where globbing is actually failing (can't access dir because of permissions, for instance), and silently leads to files not being picked up by the receiver.

### PR DESCRIPTION
**Pull request by haoqixu**
**Description:**
Set `WithFailOnIOErrors` option and propagate the globbing io errors for logging.

**Link to tracking Issue:**
resolve #23768

### CODE REVIEW

**Review by atoulme — APPROVED** [review]

File: pkg/stanza/fileconsumer/matcher/internal/finder/finder_test.go [hunk 1]
```diff
@@ -177,14 +177,17 @@ func TestFindFiles(t *testing.T) {
...
+				file, err = os.OpenFile(f, os.O_CREATE|os.O_RDWR, 0600)
 				require.NoError(t, err)
 
 				_, err = file.WriteString(filepath.Base(f))
 				require.NoError(t, err)
 				require.NoError(t, file.Close())
 			}
-			assert.Equal(t, tc.expected, FindFiles(tc.include, tc.exclude))
+			files, err := FindFiles(tc.include, tc.exclude)
+			assert.NoError(t, err)
```
Comment (atoulme) [inline pkg/stanza/fileconsumer/matcher/internal/finder/finder_test.go:189]: can you add a test where an error is returned maybe?

**Comment by haoqixu** [comment]
I make some changes becase I noticed that the globbing errors was returned too early and the behavior was changed.
The globbing error is used for warning and the finder shoud still try its best to find as many valid paths as possible. When an error is returned with the `WithFailOnIOErrors` option, we shoud do the glob again without `WithFailOnIOErrors`.

File: pkg/stanza/fileconsumer/matcher/internal/finder/finder_test.go (hunk 1 above)
Comment (haoqixu) [reply pkg/stanza/fileconsumer/matcher/internal/finder/finder_test.go:189]: Added.

File: pkg/stanza/fileconsumer/matcher/internal/finder/finder.go [hunk 2]
```diff
@@ -20,10 +21,15 @@ func Validate(globs []string) error {
...
-func FindFiles(includes []string, excludes []string) []string {
+func FindFiles(includes []string, excludes []string) ([]string, error) {
+	var errs error
 	all := make([]string, 0, len(includes))
 	for _, include := range includes {
-		matches, _ := doublestar.FilepathGlob(include, doublestar.WithFilesOnly()) // compile error checked in build
+		matches, err := doublestar.FilepathGlob(include, doublestar.WithFilesOnly(), doublestar.WithFailOnIOErrors())
+		if err != nil {
+			errs = errors.Join(errs, fmt.Errorf("find files with '%s' pattern: %w", include, err))
+			matches, _ = doublestar.FilepathGlob(include, doublestar.WithFilesOnly())
```
Comment (djaglowski) [inline pkg/stanza/fileconsumer/matcher/internal/finder/finder.go:31]: Just making sure I understand correctly:  The reason to do this is because the same pattern could cause an IO error due to one file or directory, but also could still find files if we do not provide the option. 

If this is right, can we just have a comment here to explain this? It can be very brief but I think it's worth noting so that future refactoring does not miss this nuance.

Comment (djaglowski) [reply pkg/stanza/fileconsumer/matcher/internal/finder/finder.go:31]: I see the test case you added shows this quite nicely. Still I think a comment is worthwhile.

File: pkg/stanza/fileconsumer/matcher/matcher.go [hunk 3]
```diff
@@ -109,20 +110,24 @@ type Matcher struct {
...
 func (m Matcher) MatchFiles() ([]string, error) {
-	files := finder.FindFiles(m.include, m.exclude)
+	var errs error
+	files, err := finder.FindFiles(m.include, m.exclude)
+	if err != nil {
+		errs = errors.Join(errs, err)
+	}
 	if len(files) == 0 {
-		return files, fmt.Errorf("no files match the configured criteria")
+		return files, errors.Join(errs, fmt.Errorf("no files match the configured criteria"))
```
Comment (djaglowski) [inline pkg/stanza/fileconsumer/matcher/matcher.go:119]: Nit: Probably makes more sense to start with the high level err and then show detailed errors.
```suggestion
		return files, errors.Join(fmt.Errorf("no files match the configured criteria"), errs)
```

File: pkg/stanza/fileconsumer/matcher/matcher.go [hunk 4]
```diff
@@ -109,20 +110,24 @@ type Matcher struct {
...
 	}
 	if len(m.filterOpts) == 0 {
-		return files, nil
+		return files, errs
 	}
 
 	result, err := filter.Filter(files, m.regex, m.filterOpts...)
 	if len(result) == 0 {
-		return result, err
+		return result, errors.Join(errs, err)
```
Comment (djaglowski) [inline pkg/stanza/fileconsumer/matcher/matcher.go:127]:
```suggestion
		return result, errors.Join(err, errs)
```

File: pkg/stanza/fileconsumer/matcher/matcher.go [hunk 5]
```diff
@@ -109,20 +110,24 @@ type Matcher struct {
...
 	}
 
 	// Return only the first item.
 	// See https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/23788
-	return result[:1], err
+	return result[:1], errors.Join(errs, err)
```
Comment (djaglowski) [inline pkg/stanza/fileconsumer/matcher/matcher.go:132]:
```suggestion
	return result[:1], errors.Join(err, errs)
```

**Review by djaglowski — APPROVED** [review]
Thanks for the improvement @haoqixu
