### PR TITLE
[receiver/prometheus] Add fallback_scrape_protocol during config validation

### LINKED ISSUE #37902: [receiver/prometheus] Investigate if we can relax usage of fallback_scrape_protocol
### Component(s)

receiver/prometheus

### Describe the issue you're reporting

During https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/36873, we faced a lot of failing tests because of content type negotiation failures. To update things quickly, we ended up adding a fallback_scrape_protocol option everywhere, but it's not clear to us if that's the best option.

Let's investigate and clean up where we can

### PR DESCRIPTION
**Pull request by ArthurSens**
#### Description
During the release process, we noticed a breaking change in the Prometheus receiver caused by https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/36873.

In that PR, I tried adding a fallback scrape protocol by default everytime the PrometheusReceiver was built, but it turned out that config validation happened even before the component was created. And the collector fails startup with invalid configuration

This PR moves the addition of scrape protocol to the validation step.

#### Link to tracking issue
Fixes #37902

### CODE REVIEW

File: receiver/prometheusreceiver/config.go [hunk 1]
```diff
@@ -103,6 +103,15 @@ func (cfg *PromConfig) Validate() error {
 	if err != nil {
 		return err
 	}
+	// Since Prometheus 3.0, the scrape manager started to fail scrapes that don't have proper
+	// Content-Type headers, but they provided an extra configuration option to fallback to the
+	// previous behavior. We need to make sure that this option is set for all scrape configs
+	// to avoid introducing a breaking change.
+	for _, sc := range scrapeConfigs {
+		if sc.ScrapeFallbackProtocol == "" {
+			sc.ScrapeFallbackProtocol = promconfig.PrometheusText0_0_4
```
Comment (ArthurSens) [inline receiver/prometheusreceiver/config.go:112]: I've also noticed that my choice of default scrape protocol was wrong 🤦 The previous default is Prometheus 0.0.4

**Review by dashpole — APPROVED** [review]

**Comment by ArthurSens** [comment]
> nice. we can also revert your change to prometheus/common after this, right?

yes!

**Review by songy23 — APPROVED** [review]

**Comment by mx-psi** [comment]
Please make sure we follow https://github.com/open-telemetry/opentelemetry-collector/blob/main/docs/release.md#bugfix-release-procedure if we are doing a bugfix release for this!

**Comment by ArthurSens** [comment]
> Please make sure we follow https://github.com/open-telemetry/opentelemetry-collector/blob/main/docs/release.md#bugfix-release-procedure if we are doing a bugfix release for this!

Thanks for pointing that out. Base branch changes and commits rebased

**Comment by songy23** [comment]
I think we want this PR to be merged to mainline first, then do a cherry-pick to the release branch, no?

**Comment by ArthurSens** [comment]
[From the documented process](https://github.com/open-telemetry/opentelemetry-collector/blob/main/docs/release.md#bugfix-release-procedure), I understood that we create a PR to the release branch as the first step. Third step is to merge the release branch back to main 🤔

**Comment by songy23** [comment]
Got it, now I remember - thanks for the pointers

**Review by jpkrohling — APPROVED** [review]
