### PR TITLE
[exporter/file] Add support for rotation when group_by is enabled

### LINKED ISSUE #43143: fileexporter/rotation does not work with group_by enabled
### Component(s)

exporter/file

## Description

The fileexporter rotation propery does not seems to work if group by resoruce attribute is enabled. The files are divided properly following the group by setting, but never rotated even after going beyond the max MB limits several times over.

## Steps to Reproduce

```
      file/rotation_with_custom_settings:
        format: json
        group_by:
          enabled: true
          max_open_files: 1000
          resource_attribute: service.name
        path: /data/*
        rotation:
          localtime: true
          max_backups: 100
          max_days: 2
```

## Expected Result
Invididual files are rotated.

## Actual Result
Individua files just keep growing.

### Collector version

opentelemetry-collector-contrib:0.136.0

### Environment information

_No response_

### OpenTelemetry Collector configuration

```yaml

```

### Log output

```shell

```

### Additional context

_No response_

### Tip

<sub>[React](https://github.blog/news-insights/product-news/add-reactions-to-pull-requests-issues-and-comments/) with 👍 to help prioritize this issue. Please use comments to provide useful context, avoiding `+1` or `me too`, to help us triage it. Learn more [here](https://opentelemetry.io/community/end-user/issue-participation/).</sub>

### PR DESCRIPTION
**Pull request by paulojmdias**
#### Description

This PR adds support for rotation when `group_by` is enabled on the file exporter.

Previously, this was not supported by design due to a bug [in the lumberjack library](https://github.com/natefinch/lumberjack/issues/56). As it seems the lumberjack is being unmaintained, we can replace it with [timberjack](https://github.com/DeRuina/timberjack), which is an enhanced fork of lumberjack. With it, we can keep the same features we have, and also take advantage of the lumberjack issue being fixed there and of being maintained.

#### Link to tracking issue
Fixes #43143

#### Testing

Besides adding a unit test to validate the rotation behaviour when `group_by` is enabled, I tested locally multiple times using the collector and `telemetrygen` to generate the data.

Below it is the config I used, the `telemetrygen` command, and the files output with rotated files.

Collector configuration:

```yaml
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

exporters:
  file:
    path: /tmp/otel-test/*.json
    format: json
    rotation:
      max_megabytes: 1
      max_backups: 3
      localtime: true
    group_by:
      enabled: true
      resource_attribute: service.name
      max_open_files: 100

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [file]
```

TelemetryGen loop command:

```sh
for service in alpha beta gamma delta epsilon; do
 telemetrygen traces --otlp-insecure --traces 50000 --workers 8 --rate 0 --service "service-$service" &
done
wait
```

Files output:

```sh
❯ du -h /tmp/otel-test/*

1.0M	/tmp/otel-test/service-alpha-2026-02-05T10-17-09.338-size.json
1.0M	/tmp/otel-test/service-alpha-2026-02-05T10-17-09.374-size.json
1.0M	/tmp/otel-test/service-alpha-2026-02-05T10-17-09.393-size.json
720K	/tmp/otel-test/service-alpha.json
1.0M	/tmp/otel-test/service-beta-2026-02-05T10-17-09.253-size.json
1.0M	/tmp/otel-test/service-beta-2026-02-05T10-17-09.321-size.json
1.0M	/tmp/otel-test/service-beta-2026-02-05T10-17-09.348-size.json
944K	/tmp/otel-test/service-beta.json
1.0M	/tmp/otel-test/service-delta-2026-02-05T10-17-09.255-size.json
1.0M	/tmp/otel-test/service-delta-2026-02-05T10-17-09.351-size.json
1.0M	/tmp/otel-test/service-delta-2026-02-05T10-17-09.375-size.json
464K	/tmp/otel-test/service-delta.json
1.0M	/tmp/otel-test/service-epsilon-2026-02-05T10-17-09.375-size.json
1.0M	/tmp/otel-test/service-epsilon-2026-02-05T10-17-09.393-size.json
1.0M	/tmp/otel-test/service-epsilon-2026-02-05T10-17-09.403-size.json
676K	/tmp/otel-test/service-epsilon.json
1.0M	/tmp/otel-test/service-gamma-2026-02-05T10-17-09.295-size.json
1.0M	/tmp/otel-test/service-gamma-2026-02-05T10-17-09.348-size.json
1.0M	/tmp/otel-test/service-gamma-2026-02-05T10-17-09.366-size.json
684K	/tmp/otel-test/service-gamma.json
```

#### Documentation

Updated documentation, removing the references to being unsupported.

### CODE REVIEW

File: exporter/fileexporter/grouping_file_exporter.go [hunk 1]
```diff
@@ -302,7 +302,7 @@ func (e *groupingFileExporter) Start(_ context.Context, host component.Host) err
 	e.pathSuffix = pathParts[1]
 	e.maxOpenFiles = e.conf.GroupBy.MaxOpenFiles
 	e.newFileWriter = func(path string) (*fileWriter, error) {
-		return newFileWriter(path, e.conf.Append, nil, e.conf.FlushInterval, export)
+		return newFileWriter(path, e.conf.Append, e.conf.Rotation, e.conf.FlushInterval, export)
```
Comment (VihasMakwana) [inline exporter/fileexporter/grouping_file_exporter.go:305]: Nice!

**Review by VihasMakwana — APPROVED** [review]

**Review by iblancasa — COMMENTED** [review]
Can't we do this in two steps?
1. Replace `lumberjack`
2. Implement the new feature

I'm asking this because not sure if there could be any derived issues that we are not seeing (maybe something untested). And, to help narrow possible issues, I think this can be good.

**Comment by paulojmdias** [comment]
> Can't we do this in two steps?
> 1. Replace `lumberjack`
> 2. Implement the new feature
> 
> I'm asking this because not sure if there could be any derived issues that we are not seeing (maybe something untested). And, to help narrow possible issues, I think this can be good.

Yes, but the 2 will always depends on 1. So if we need to revert 1, we will also need to revert 2 unless you are meaning to make both changes available under a feature gate.

I can split in different PRs, I'm just sharing dependency concerns in case of 1 needs to be reverted.

Thoughts ?

File: exporter/fileexporter/grouping_file_exporter_test.go [hunk 2]
```diff
@@ -507,3 +510,91 @@ func BenchmarkExporters(b *testing.B) {
...
+	td := ptrace.NewTraces()
+	rs := td.ResourceSpans().AppendEmpty()
+	rs.Resource().Attributes().PutStr("service.name", "test-service")
+	span := rs.ScopeSpans().AppendEmpty().Spans().AppendEmpty()
+	span.SetName("test-span")
+
+	require.NoError(t, gfe.consumeTraces(t.Context(), td))
+
+	gfe.mutex.Lock()
+	writer, ok := gfe.writers.Get(tmpDir + "/test-service.log")
```
Comment (MovieStoreGuy) [inline exporter/fileexporter/grouping_file_exporter_test.go:552]: Is there test data cleanup assured here?

Comment (paulojmdias) [reply exporter/fileexporter/grouping_file_exporter_test.go:552]: Are you talking about ensuring the `MaxBackups` are respected? If yes, I added it now in the following [commit](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/45900/changes/1ffdca337d8078603e74ffcc398d5dac39357372). PTAL

**Review by atoulme — APPROVED** [review]

**Comment by atoulme** [comment]
Need another look from @MovieStoreGuy and then we can get this in.

**Review by MovieStoreGuy — APPROVED** [review]
