### PR TITLE
[receiver/awsxray] Set cloudwatch logs metadata in attributes

### LINKED ISSUE #31784: [receiver/awsxray] Does not retain CloudWatch Log Group information
### Component(s)

receiver/awsxray

## Description
X-Ray segments have a few [optional fields](https://docs.aws.amazon.com/xray/latest/devguide/xray-api-segmentdocuments.html#api-segmentdocuments-aws) that carry AWS resource data. As part of the translation of X-Ray segments to spans, the translator [extracts AWS data](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/receiver/awsxrayreceiver/internal/translator/aws.go#L15) and puts them in the resource attributes. It does this for EC2, ECS, Beanstalk, and EKS, but not for CloudWatch Logs. So, by the time the span [reaches the exporter](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/exporter/awsxrayexporter/internal/translator/aws.go#L109), that information is lost.

## Steps to Reproduce
Use the AWS X-Ray SDK and include CloudWatch Logs resource data.

## Expected Result
The resource data gets forwarded to the exporter and passed along to X-Ray Frontend. This allows the logs to be correlated with the traces.

## Actual Result
The logs information is not sent to the X-Ray Frontend and it is unavailable in the console.

### Collector version

v0.89.0

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

### OpenTelemetry Collector configuration

_No response_

### Log output

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by jefchien**
**Description:**

From the issue:

> X-Ray segments have a few [optional fields](https://docs.aws.amazon.com/xray/latest/devguide/xray-api-segmentdocuments.html#api-segmentdocuments-aws) that carry AWS resource data. As part of the translation of X-Ray segments to spans, the translator [extracts AWS data](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/receiver/awsxrayreceiver/internal/translator/aws.go#L15) and puts them in the resource attributes. It does this for EC2, ECS, Beanstalk, and EKS, but not for CloudWatch Logs. So, by the time the span [reaches the exporter](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/exporter/awsxrayexporter/internal/translator/aws.go#L109), that information is lost.

This change adds the cloudwatch logs metadata to the attributes with the keys `conventions.AttributeAWSLogGroupARNs` and `conventions.AttributeAWSLogGroupNames`. Both of these are used by the awsxrayexporter to restore the `LogGroupMetadata`.

https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/decc66f276b9bb3ca7b775d59a93340503668641/exporter/awsxrayexporter/internal/translator/aws.go#L109-L112

https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/decc66f276b9bb3ca7b775d59a93340503668641/exporter/awsxrayexporter/internal/translator/aws.go#L293-L295

**Link to tracking Issue:** Fixes https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/31784

**Testing:** Added unit tests to validate the translation to attributes.

**Documentation:** N/A

### CODE REVIEW

**Comment by crobert-1** [comment]
I've filed https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/32275 for the failing integration test, it doesn't appear to be related to your changes.

File: receiver/awsxrayreceiver/internal/translator/aws.go [hunk 1]
```diff
@@ -25,7 +25,14 @@ func addAWSToResource(aws *awsxray.AWSData, attrs pcommon.Map) {
 	addString(aws.AccountID, conventions.AttributeCloudAccountID, attrs)
 
 	// based on https://docs.aws.amazon.com/xray/latest/devguide/xray-api-segmentdocuments.html#api-segmentdocuments-aws
-	// it's possible to have all ec2, ecs and beanstalk fields at the same time.
+	// it's possible to have all cloudwatch_logs, ec2, ecs and beanstalk fields at the same time.
+	if cwl := aws.CWLogs; cwl != nil {
```
Comment (crobert-1) [inline receiver/awsxrayreceiver/internal/translator/aws.go:29]: Is there a reason `cwl` is necessary here (and we can't directly refer to `aws.CWLogs`)?

File: receiver/awsxrayreceiver/internal/translator/addtoattrs.go [hunk 2]
```diff
@@ -22,3 +22,15 @@ func addInt64(val *int64, attrKey string, attrs pcommon.Map) {
 		attrs.PutInt(attrKey, *val)
 	}
 }
+
+func addStringSlice(val *string, attrKey string, attrs pcommon.Map) {
+	if val != nil {
```
Comment (crobert-1) [inline receiver/awsxrayreceiver/internal/translator/addtoattrs.go:27]: It's generally a little easier to follow if we return if val is nil. This will allow the method functionality to be outside of the if statement.

I see other methods in this file follow the format you're using here though, so this isn't required.

**Review by crobert-1 — APPROVED** [review]
This looks good to me, but I'd like a code owner or someone with more AWS experience to review as well, I'm not very familiar here 👍

File: receiver/awsxrayreceiver/internal/translator/aws.go (hunk 1 above)
Comment (jefchien) [reply receiver/awsxrayreceiver/internal/translator/aws.go:29]: Just trying to follow the format of the others in the file. I don't think it's necessary either.

**Review by codeboten — COMMENTED** [review]
Pinging code owners @wangzlei @srprash for review

**Review by srprash — APPROVED** [review]

File: receiver/awsxrayreceiver/internal/translator/addtoattrs.go (hunk 2 above)
Comment (jefchien) [reply receiver/awsxrayreceiver/internal/translator/addtoattrs.go:27]: I agree. I didn't want to make too many unnecessary changes and ended up choosing to follow the same format as the other functions.

**Review by codeboten — APPROVED** [review]
