### PR TITLE
[exporter/kafka]validate topic_from_metadata_key is included in metadata keys

### LINKED ISSUE #46711: Topic routing from metadata key is broken with sending queue based batching
### Component(s)

_No response_

## Description
`kafkaexporter` can fall back to default topics (`otlp_logs`, `otlp_metrics`, `otlp_spans`) even when `<signal>.topic_from_metadata_key` is configured and present in incoming client metadata, when `sending_queue.batch` is enabled and `include_metadata_keys` does not include the same topic metadata key.
Root cause appears to be an implicit coupling: `include_metadata_keys` is used not only for header propagation, but also as the batch partition key set. With batching enabled, requests with different metadata can be merged if they share the same partition key, and merged batch context may not retain the metadata key required by `topic_from_metadata_key`, causing topic resolution to fall back to defaults.
This is surprising and error-prone because topic routing correctness depends on a header-related setting.

## Steps to Reproduce
1. Configure `kafkaexporter` with:
   - `traces.topic_from_metadata_key: kafka_topic` (same for logs/metrics as needed)
   - `sending_queue.enabled: true`
   - `sending_queue.batch` enabled (for example: `sizer: bytes`, with min/max/flush settings)
2. Set `include_metadata_keys` to a list that does **not** include `kafka_topic`.
3. Send telemetry with client metadata containing `kafka_topic: xxx`.
4. Observe produced records under load where batching/merging occurs.

## Expected Result
When `<signal>.topic_from_metadata_key` is set and metadata key is present on incoming requests, records should always be produced to that metadata-derived topic, regardless of `include_metadata_keys` (which should only control header propagation, or at least not break topic routing semantics).

## Actual Result
With `sending_queue.batch` enabled and `include_metadata_keys` excluding the topic metadata key, records can be produced to default signal topics (`otlp_logs`, `otlp_metrics`, `otlp_spans`) instead of the metadata-derived topic.

### Collector version

v0.146.0, main

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

### OpenTelemetry Collector configuration

```yaml

```

### Log output

```shell

```

### Additional context

_No response_

### Tip

<sub>[React](https://github.blog/news-insights/product-news/add-reactions-to-pull-requests-issues-and-comments/) with 👍 to help prioritize this issue. Please use comments to provide useful context, avoiding `+1` or `me too`, to help us triage it. Learn more [here](https://opentelemetry.io/community/end-user/issue-participation/).</sub>

### PR DESCRIPTION
**Pull request by lahsivjar**
#### Description
Fixes a kafkaexporter batching regression where metadata used by `include_metadata_keys` could be lost during queue batch context merge.  
This change ensures metadata-based behavior remains consistent by wiring `MergeCtx` for metadata partitioning and adding config validation so `topic_from_metadata_key` must be included in `include_metadata_keys` when configured.  
Also adds regression coverage for metadata merge behavior and config validation failure cases.

#### Link to tracking issue
Fixes #46711 

#### Testing
Added tests

#### Documentation
- Added changelog entry:
  - `.chloggen/kafkaexporter-topic-from-metadata-key-validation.yaml`

### CODE REVIEW

**Review by paulojmdias — APPROVED** [review]
LGTM, thank you!

Let's wait for @axw review as he suggested this approach 👍

File: exporter/kafkaexporter/config.go [hunk 1]
```diff
@@ -86,11 +91,38 @@ type Config struct {
...
+	}
+	if err := validateTopicFromMetadataKey(c.Metrics.TopicFromMetadataKey, c.IncludeMetadataKeys); err != nil {
+		return fmt.Errorf("metrics.topic_from_metadata_key: %w", err)
+	}
+	if err := validateTopicFromMetadataKey(c.Traces.TopicFromMetadataKey, c.IncludeMetadataKeys); err != nil {
+		return fmt.Errorf("traces.topic_from_metadata_key: %w", err)
+	}
+	if err := validateTopicFromMetadataKey(c.Profiles.TopicFromMetadataKey, c.IncludeMetadataKeys); err != nil {
+		return fmt.Errorf("profiles.topic_from_metadata_key: %w", err)
+	}
```
Comment (axw) [inline exporter/kafkaexporter/config.go:110]:
```suggestion
	if err := validateTopicFromMetadataKey(c.Logs.TopicFromMetadataKey, c.IncludeMetadataKeys); err != nil {
		return fmt.Errorf("logs::topic_from_metadata_key: %w", err)
	}
	if err := validateTopicFromMetadataKey(c.Metrics.TopicFromMetadataKey, c.IncludeMetadataKeys); err != nil {
		return fmt.Errorf("metrics::topic_from_metadata_key: %w", err)
	}
	if err := validateTopicFromMetadataKey(c.Traces.TopicFromMetadataKey, c.IncludeMetadataKeys); err != nil {
		return fmt.Errorf("traces::topic_from_metadata_key: %w", err)
	}
	if err := validateTopicFromMetadataKey(c.Profiles.TopicFromMetadataKey, c.IncludeMetadataKeys); err != nil {
		return fmt.Errorf("profiles::topic_from_metadata_key: %w", err)
	}
```

We use this syntax elsewhere IIANM.

**Review by axw — APPROVED** [review]
LGTM, just a nit about syntax

File: exporter/kafkaexporter/config.go (hunk 1 above)
Comment (lahsivjar) [reply exporter/kafkaexporter/config.go:110]: Sounds good, thanks! Updated now.
