### PR TITLE
[extension/sumologic] Skip zombie processes on Windows

### LINKED ISSUE #36481: [broken test][sumologicextension] several tests failed on Windows
### Component(s)

extension/sumologic

### Describe the issue you're reporting

E.g. https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/11937483258/job/33273579980

```
=== Failed
=== FAIL: .  (0.00s)
panic: test timed out after 10m0s
running tests:
	TestCollectorCheckingCredentialsFoundInLocalStorage (10m0s)
	TestCollectorCheckingCredentialsFoundInLocalStorage/collector_checks_found_credentials_via_heartbeat_call_-_no_registration_is_done (10m0s)
	TestCollectorReregistersAfterHTTPUnathorizedFromHeartbeat (10m0s)
	TestCollectorSendsBasicAuthHeadersOnRegistration (10m0s)
	TestRegisterEmptyCollectorName (10m0s)
...

=== FAIL: . TestRegistrationRequestPayload (unknown)

=== FAIL: . TestCollectorCheckingCredentialsFoundInLocalStorage/collector_checks_found_credentials_via_heartbeat_call_-_no_registration_is_done (unknown)
    extension_test.go:749: Storing collector credentials in temp dir: C:\Users\RUNNER~1\AppData\Local\Temp\otelcol-sumo-store-credentials-test-3707712072

=== FAIL: . TestLocalFSCredentialsStore_WorkCorrectlyForMultipleExtensions (unknown)

=== FAIL: . TestCollectorSendsBasicAuthHeadersOnRegistration (unknown)

=== FAIL: . TestRegisterEmptyCollectorNameWithBackoff (unknown)

=== FAIL: . TestRegisterEmptyCollectorNameUnrecoverableError (unknown)

=== FAIL: . TestUpdateMetadataRequestPayload (unknown)
```

### PR DESCRIPTION
**Pull request by pjanotti**
#### Description
On Windows it consistently fails to get the name of certain processes, likely zombie process, reporting: "A device attached to the system is not functioning."

My long term recommendation will be for the owners to directly use the Win32 API to get process information instead of the library: while it uses the correct permissions to get the process name it is not using the flag that allows to get the device name path which should avoid this issue even for zombie processes, I'm not sure if that is desirable or not.

#### Link to tracking issue
Fixes #36481

#### Testing
Repro the failure locally and checked that the test passed locally with the change. 
I couldn't lint it locally on Windows (tool crash, will use CI to check that)

#### Documentation

Added changelog

### CODE REVIEW

**Comment by pjanotti** [comment]
Failing check is #36764 - https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/12262901594/job/34213584856#step:8:791

**Comment by pjanotti** [comment]
One possibility that I didn't investigate is if these zombie processes are being created by the test itself. That can happen if the test somehow opens a handle to the process and the process ends, but the handle was not closed yet.

**Review by mx-psi — APPROVED** [review]

**Review by codeboten — COMMENTED** [review]
this looks ok to me, pinging code owners @rnishtala-sumo @chan-tim-sumo for review

File: extension/sumologicextension/extension.go [hunk 1]
```diff
@@ -739,6 +740,15 @@ func filteredProcessList() ([]string, error) {
 	for _, v := range processes {
 		e, err := v.Name()
 		if err != nil {
+			if runtime.GOOS == "windows" {
```
Comment (chan-tim-sumo) [inline extension/sumologicextension/extension.go:743]: Not sure if this would be the correct place to skip windows processes. This section of the code is to filter processes for auto discovery products (supports mac + linux).

Comment (pjanotti) [reply extension/sumologicextension/extension.go:743]: I'm sure if I am understanding what you meant. What this is doing is handling the case of failure to get the process name on Windows by not aborting the function and continuing with the remaing processes. 

Why is that reasonable on Windows? Because zombie processes are a relatively common ocurrence on Windows: any 3rd party process can create one by opening a handle to a process and not closing it when the other process terminates.

Why the check for Windows? Because I want to change as little as possible on the other platforms that as far as I know are not having the same issue. In principle, I don't see a problem doing the same for the other OSes the intent was to change as little as possible the current behavior. That said removing the if and just logging the error and continuing is also fine.

Comment (dmitryax) [reply extension/sumologicextension/extension.go:743]: @chan-tim-sumo, this PR is intended to stabilize and fix CI pipeline on Windows. If you think it's not the right fix, please suggest your solution as another PR. In the meantime, since there is no agreement with the codeowners, we need to disable this test to unblock CI.

Comment (rnishtala-sumo) [reply extension/sumologicextension/extension.go:743]: > Because zombie processes are a relatively common ocurrence on Windows: any 3rd party process can create one by opening a handle to a process and not closing it when the other process terminates

This makes sense. I think its reasonable to limit the scope of this change to windows machines.

**Review by rnishtala-sumo — APPROVED** [review]
