### PR TITLE
[internal/aws]: respect NO_PROXY env var in awsutil HTTP client

### LINKED ISSUE #46892: "/internal/aws/awsutil/conn.go" should support "NO_PROXY/no_proxy" logical support
### Component(s)

internal/aws

## Description
- Send logs to Cloudwatch failed, because there is a  https proxy like mitmproxy replace the certificate.

## Steps to Reproduce
helm install with values.yaml
```yaml
opentelemetry-collector:
  mode: deployment

  serviceAccount:
    create: true
    name: otel-demo-collector
    annotations:
      eks.amazonaws.com/role-arn: arn:aws:iam::112233445566:role/CloudWatchLogsFullAccess-Role-Pod-Identity

  config:
    exporters:
      awscloudwatchlogs:
        region: eu-west-1
        log_group_name: /eks/otel-demo/logs
        log_stream_name: otel-demo-collector

    service:
      pipelines:
        logs:
          exporters: [awscloudwatchlogs]
```

```yaml
        env:
        - name: HTTP_PXORY
          value: http://mitmproxy:8080
        - name: HTTPS_PROXY 
          value: http://mitmproxy:8080
        - name: http_proxy
          value: http://mitmproxy:8080
        - name: https_proxy
          value: http://mitmproxy:8080
        - name: NO_PROXY
          value: logs.eu-west-1.amazonaws.com,127.0.0.1,localhost,svc.cluster.local,.cluster.local,169.254.169.254,.amazonaws.com
        - name: no_proxy
          value:  logs.eu-west-1.amazonaws.com,127.0.0.1,localhost,svc.cluster.local,.cluster.local,169.254.169.254,.amazonaws.com
```

```log
2026-03-13T10:23:10.141Z    info    internal/retry_sender.go:133    Exporting failed. Will retry the request after interval.    {"resou
rce": {"service.instance.id": "980d4370-080b-44d7-8e6d-9e5065fc9f60", "service.name": "otelcol-contrib", "service.version": "0.142.0"},
 "otelcol.component.id": "awscloudwatchlogs", "otelcol.component.kind": "exporter", "otelcol.signal": "logs", "error": "error flushing 
logs: operation error CloudWatch Logs: PutLogEvents, exceeded maximum number of attempts, 2, https response error StatusCode: 0, Reques
tID: , request send failed, Post \"https://logs.eu-west-1.amazonaws.com/\": tls: failed to verify certificate: x509: certificate signed
 by unknown authority", "interval": "18.298104877s"}
```

## Expected Result
provide a "insecure" flag, or support "no_proxy/NO_PROXY" options in:
- https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/internal/aws/awsutil/conn.go#L61-L85

```golang
    func getProxyAddress(proxyAddress string) string {
      var finalProxyAddress string
      switch {
      case proxyAddress != "":
        finalProxyAddress = proxyAddress

      case proxyAddress == "" && os.Getenv("HTTPS_PROXY") != "":
        finalProxyAddress = os.Getenv("HTTPS_PROXY")
      default:
        finalProxyAddress = ""
      }
      return finalProxyAddress
    }

    func getProxyURL(finalProxyAddress string) (*url.URL, error) {
      var proxyURL *url.URL
      var err error
      if finalProxyAddress != "" {
        proxyURL, err = url.Parse(finalProxyAddress)
      } else {
        proxyURL = nil
        err = nil
      }
      return proxyURL, err
    }


```

## Actual Result
access aws logs endpoints failed.

### Collector version

v0.147.0

## Environment
OS: kubernetes 1.33

### OpenTelemetry Collector configuration

```yaml

```

### Log output

```shell
2026-03-13T10:23:10.141Z    info    internal/retry_sender.go:133    Exporting failed. Will retry the request after interval.    {"resou
rce": {"service.instance.id": "980d4370-080b-44d7-8e6d-9e5065fc9f60", "service.name": "otelcol-contrib", "service.version": "0.142.0"},
 "otelcol.component.id": "awscloudwatchlogs", "otelcol.component.kind": "exporter", "otelcol.signal": "logs", "error": "error flushing 
logs: operation error CloudWatch Logs: PutLogEvents, exceeded maximum number of attempts, 2, https response error StatusCode: 0, Reques
tID: , request send failed, Post \"https://logs.eu-west-1.amazonaws.com/\": tls: failed to verify certificate: x509: certificate signed
 by unknown authority", "interval": "18.298104877s"}
```

### Additional context

_No response_

### Tip

<sub>[React](https://github.blog/news-insights/product-news/add-reactions-to-pull-requests-issues-and-comments/) with 👍 to help prioritize this issue. Please use comments to provide useful context, avoiding `+1` or `me too`, to help us triage it. Learn more [here](https://opentelemetry.io/community/end-user/issue-participation/).</sub>

### PR DESCRIPTION
**Pull request by 57Ajay**
fixes #46892

When no explicit `proxy_address` is configured, `newHTTPClient` in `internal/aws/awsutil/conn.go` manually reads `HTTPS_PROXY` via `getProxyAddress` and passes it to `http.ProxyURL`. This unconditionally routes **all** requests through the proxy, completely ignoring `NO_PROXY`/`no_proxy` environment variables.

This causes TLS failures for users running behind intercepting proxies (e.g. mitmproxy) who rely on `NO_PROXY` to bypass the proxy for AWS endpoints:
```
tls: failed to verify certificate: x509: certificate signed by unknown authority
```

## Fix

Introduced `getProxyFunc` which:
- **Empty `proxy_address` (env-based proxy):** returns `http.ProxyFromEnvironment`, Go's stdlib function that correctly handles `HTTPS_PROXY`, `HTTP_PROXY`, `NO_PROXY`, and their lowercase variants.
- **Explicit `proxy_address` (config-based proxy):** returns `http.ProxyURL` as before — no behavior change.

## Tests

Added three tests to `conn_test.go`:
- `TestNoProxyIsRespectedWhenUsingEnvProxy` -- verifies proxy is bypassed for hosts matching `NO_PROXY`
- `TestProxyIsUsedForNonExcludedHosts` -- verifies proxy is still used for non-excluded hosts
- `TestExplicitProxyAddressStillWorks` -- verifies backward compatibility with explicit `proxy_address` config

## Note

`internal/aws/proxy/conn.go` has a similar pattern (its own `getProxyAddress`/`getProxyURL` with the same `http.ProxyURL` usage). Happy to fix that in this PR as well.

The old `getProxyAddress` and `getProxyURL` in `awsutil/conn.go` are now unused by production code (only their existing tests reference them). Happy to remove them too in this PR if preferred.

### CODE REVIEW

File: internal/aws/awsutil/conn_test.go [hunk 1]
```diff
@@ -266,3 +267,63 @@ func TestGetProxyURL(t *testing.T) {
...
+
+	transport, ok := client.Transport.(*http.Transport)
+	require.True(t, ok)
+
+	req, err := http.NewRequest(http.MethodGet, "https://example.com/something", http.NoBody)
+	require.NoError(t, err)
+
+	proxyURL, err := transport.Proxy(req)
+	assert.NoError(t, err)
+	assert.NotNil(t, proxyURL,
```
Comment (Aneurysm9) [inline internal/aws/awsutil/conn_test.go]: Can this assert the expected proxy URL is actually used?

File: internal/aws/awsutil/conn_test.go [hunk 2]
```diff
@@ -266,3 +267,63 @@ func TestGetProxyURL(t *testing.T) {
...
+	transport, ok := client.Transport.(*http.Transport)
+	require.True(t, ok)
+
+	req, err := http.NewRequest(http.MethodGet, "https://example.com/", http.NoBody)
+	require.NoError(t, err)
+
+	proxyURL, err := transport.Proxy(req)
+	assert.NoError(t, err)
+	assert.NotNil(t, proxyURL)
+	assert.Equal(t, "http://explicit.proxy:9090", proxyURL.String())
```
Comment (Aneurysm9) [inline internal/aws/awsutil/conn_test.go:240]: Should this test (or another similar test) have `HTTPS_PROXY` set to validate the precedence of the explicit configuration?

**Review by Aneurysm9 — COMMENTED** [review]
This seems reasonable.  Please clean up any now-unused functions.

File: internal/aws/awsutil/conn_test.go (hunk 1 above)
Comment (57Ajay) [reply internal/aws/awsutil/conn_test.go]: Added -- now asserts assert.Equal(t, "http://mitmproxy:8080", proxyURL.String()).

File: internal/aws/awsutil/conn_test.go (hunk 2 above)
Comment (57Ajay) [reply internal/aws/awsutil/conn_test.go:240]: Thanks @Aneurysm9  - now sets HTTPS_PROXY to a different value and asserts the explicit proxy_address config takes precedence over the environment variable.

**Comment by 57Ajay** [comment]
> This seems reasonable. Please clean up any now-unused functions.

I have removed getProxyAddress, getProxyURL, and their tests.

**Review by Aneurysm9 — APPROVED** [review]

**Review by crobert-1 — APPROVED** [review]

**Comment by ccieliu** [comment]
thanks for your quickly fix,
may I know which release will cherry-pick this fix code?
many thanks!
