### PR TITLE
[exporter/awsemf] Drop metrics with NaN values

### LINKED ISSUE #26267: [exporter/awsemf] NaN values are not handled properly
### Component(s)

exporter/awsemf

## Description
Metrics with NaN values will cause EMF Exporter JSON Marshaling to fail. This will cause the entire EMF Log to be discarded along with any other metrics it contains. This is not a desirable behavior and EMF Exporter should handle NaN values gracefully. Cloudwatch EMF does not support NaN values. 

I would suggest as solution that metrics with a NaN value are dropped. 

## Steps to Reproduce
Scrape a prometheus endpoint that exports a NaN Value

Here is a unit test to confirm that an error is thrown during JSON Marshalling. This test belongs in `emf_exporter_test.go`
```
    func TestConsumeMetricsWithOutputDestinationNaN(t *testing.T) {
    	ctx, cancel := context.WithCancel(context.Background())
    	defer cancel()
    	factory := NewFactory()
    	expCfg := factory.CreateDefaultConfig().(*Config)
    	expCfg.Region = "us-west-2"
    	expCfg.MaxRetries = 0
    	expCfg.OutputDestination = "stdout"
    	exp, err := newEmfExporter(expCfg, exportertest.NewNopCreateSettings())
    	assert.Nil(t, err)
    	assert.NotNil(t, exp)
     
    	md := generateTestMetrics(testMetric{
    		metricNames:  []string{"metric_1"},
    		metricValues: [][]float64{{math.NaN()}},
    	})
    	require.NoError(t, exp.pushMetricsData(ctx, md))
    	require.NoError(t, exp.shutdown(ctx))
    }
```
## Expected Result
All valid metrics are exported in EMF log.
## Actual Result
Entire EMF log is discareded. 

### Collector version

v0.83.0

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

### OpenTelemetry Collector configuration

_No response_

### Log output

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by bryan-aguilar**
**Description:** Metrics with NaN values for float types would cause the EMF Exporter to error out during JSON Marshaling. This PR introduces a change to drop metric values that contain NaN. 

**Link to tracking Issue:** Fixes #26267 

**Testing:** Added unit tests at several different points with varying levels of specificity. Unit tests are quite verbose in this example but I have followed the format of existing tests while doing very little refactoring. 

**Documentation:** Update README

### CODE REVIEW

File: exporter/awsemfexporter/datapoint_test.go [hunk 1]
```diff
@@ -491,11 +682,59 @@ func TestCalculateDeltaDatapoints_ExponentialHistogramDataPointSlice(t *testing.
...
+	}
+
+}
+
 func TestCalculateDeltaDatapoints_SummaryDataPointSlice(t *testing.T) {
 	emfCalcs := setupEmfCalculators()
 	defer require.NoError(t, shutdownEmfCalculators(emfCalcs))
 	for _, retainInitialValueOfDeltaMetric := range []bool{true, false} {
-		deltaMetricMetadata := generateDeltaMetricMetadata(true, "foo", retainInitialValueOfDeltaMetric)
+		dmd := generateDeltaMetricMetadata(true, "foo", retainInitialValueOfDeltaMetric)
```
Comment (bryan-aguilar) [inline exporter/awsemfexporter/datapoint_test.go:737]: renamed many of these variables to avoid shadowing which caused linting fails.

File: exporter/awsemfexporter/emf_exporter_test.go [hunk 2]
```diff
@@ -24,11 +24,6 @@ import (
 
 const defaultRetryCount = 1
 
-func init() {
-	os.Setenv("AWS_ACCESS_KEY_ID", "test")
-	os.Setenv("AWS_SECRET_ACCESS_KEY", "test")
-}
-
```
Comment (bryan-aguilar) [inline exporter/awsemfexporter/emf_exporter_test.go:31]: These weren't required anymore and were causing warnings for unchecked error. Opted to remove dead code.

File: exporter/awsemfexporter/grouped_metric.go [hunk 3]
```diff
@@ -35,6 +35,13 @@ func addToGroupedMetric(pmd pmetric.Metric, groupedMetrics map[interface{}]*grou
 	}
 
 	for i := 0; i < dps.Len(); i++ {
+		// Drop stale or NaN metric values
+		if dps.IsStaleOrNaN(i) {
+			if config != nil && config.logger != nil {
+				config.logger.Debug("dropped metric with nan value", zap.String("metric.name", pmd.Name()))
```
Comment (Aneurysm9) [inline exporter/awsemfexporter/grouped_metric.go:41]: Should this include the metric attributes?  The name alone is not identifying.

Comment (bryan-aguilar) [reply exporter/awsemfexporter/grouped_metric.go:41]: Is there a consistent way to log this without being too verbose? Or should we just log all metric attributes along with the name?

Comment (bryan-aguilar) [reply exporter/awsemfexporter/grouped_metric.go]: I've updated the `IsStaleOrNaN` function signature to also return the attributes for each data point. I don't love this but it seemed like the cleanest way to ensure only one log line had to be added. I chose this over adding the logger as an function parameter to `IsStaleOrNaN`.

File: exporter/awsemfexporter/datapoint.go [hunk 4]
```diff
@@ -164,6 +179,17 @@ func (dps histogramDataPointSlice) CalculateDeltaDatapoints(i int, instrumentati
 	}}, true
 }
 
+func (dps histogramDataPointSlice) IsStaleOrNaN(i int) (bool, pcommon.Map) {
+	metric := dps.HistogramDataPointSlice.At(i)
+	if metric.Flags().NoRecordedValue() {
+		return true, metric.Attributes()
+	}
+	if math.IsNaN(metric.Max()) || math.IsNaN(metric.Sum()) || math.IsNaN(metric.Min()) {
```
Comment (mxiamxia) [inline exporter/awsemfexporter/datapoint.go:187]: q: do we also need to check on `count` as well?

**Review by mxiamxia — APPROVED** [review]

File: exporter/awsemfexporter/datapoint.go (hunk 4 above)
Comment (bryan-aguilar) [reply exporter/awsemfexporter/datapoint.go:187]: Could should be an integer and thus we don't need to check it. https://github.com/open-telemetry/opentelemetry-proto/blob/main/opentelemetry/proto/metrics/v1/metrics.proto#L412-L415

**Review by Aneurysm9 — APPROVED** [review]
