### PR TITLE
Emit every n seconds

### LINKED ISSUE #9018: metricKeyToDimensions cache is printing many stack traces
**Describe the bug**

https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/6503 the additions of this LRU cache treats the missing key as an error, and prints a big stacktrace in the logs.

**Steps to reproduce**

Have either high dimensions or small `dimensions_cache_size`


**What did you expect to see?**

Either a metric for cache/hit ratio or a much lower log level, such as debug.

**What did you see instead?**

A lot of stacktraces

```
2022-04-04T03:10:26.171Z        error   spanmetricsprocessor@v0.47.0/processor.go:330   value not found in metricKeyToDimensions cache by key "copernic\x00getUserInfo\x00SPAN_KIND_SERVER\x00STATUS_CODE_UNSET"      {"kind": "processor", "name": "spanmetrics", "pipeline": "traces"}                                                                                     
github.com/open-telemetry/opentelemetry-collector-contrib/processor/spanmetricsprocessor.(*processorImp).collectCallMetrics                                                                                                                                                                                                                                                  
        github.com/open-telemetry/opentelemetry-collector-contrib/processor/spanmetricsprocessor@v0.47.0/processor.go:330                                                                                                                                                                                                                                                    
github.com/open-telemetry/opentelemetry-collector-contrib/processor/spanmetricsprocessor.(*processorImp).buildMetrics                                                                                                                                                                                                                                                        
        github.com/open-telemetry/opentelemetry-collector-contrib/processor/spanmetricsprocessor@v0.47.0/processor.go:258                                                                                                                                                                                                                                                    
github.com/open-telemetry/opentelemetry-collector-contrib/processor/spanmetricsprocessor.(*processorImp).ConsumeTraces                                                                                                                                                                                                                                                       
        github.com/open-telemetry/opentelemetry-collector-contrib/processor/spanmetricsprocessor@v0.47.0/processor.go:232                                                                                                                                                                                                                                                    
go.opentelemetry.io/collector/processor/processorhelper.NewTracesProcessor.func1                                                                                                                                                                                                                                                                                             
        go.opentelemetry.io/collector@v0.47.0/processor/processorhelper/traces.go:70                                                                                                                                                                                                                                                                                         
go.opentelemetry.io/collector/consumer.ConsumeTracesFunc.ConsumeTraces                                                                                                                                                                                                                                                                                                       
        go.opentelemetry.io/collector@v0.47.0/consumer/traces.go:36                                                                                                                                                                                                                                                                                                          
github.com/open-telemetry/opentelemetry-collector-contrib/receiver/jaegerreceiver.(*jReceiver).PostSpans                                                                                                                                                                                                                                                                     
        github.com/open-telemetry/opentelemetry-collector-contrib/receiver/jaegerreceiver@v0.47.0/trace_receiver.go:290                                                                                                                                                                                                                                                      
github.com/jaegertracing/jaeger/proto-gen/api_v2._CollectorService_PostSpans_Handler.func1                                                                                                                                                                                                                                                                                   
        github.com/jaegertracing/jaeger@v1.32.0/proto-gen/api_v2/collector.pb.go:208                                                                                                                                                                                                                                                                                         
go.opentelemetry.io/collector/config/configgrpc.enhanceWithClientInformation.func1                                                                                                                                                                                                                                                                                           
        go.opentelemetry.io/collector@v0.47.0/config/configgrpc/configgrpc.go:382                                                                                                     
google.golang.org/grpc.chainUnaryInterceptors.func1.1                                                                                                                                 
        google.golang.org/grpc@v1.45.0/server.go:1116                                                                                                                                                                                                                                                                                                                        
go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc.UnaryServerInterceptor.func1                                                                              
        go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc@v0.29.0/interceptor.go:325                                                                                                                                                                                                                                                               
google.golang.org/grpc.chainUnaryInterceptors.func1.1                                                                                                                                 
        google.golang.org/grpc@v1.45.0/server.go:1119                                                                                                                                 
google.golang.org/grpc.chainUnaryInterceptors.func1                                                                                                                                   
        google.golang.org/grpc@v1.45.0/server.go:1121                                                                                                                                 
github.com/jaegertracing/jaeger/proto-gen/api_v2._CollectorService_PostSpans_Handler                                                                                                  
        github.com/jaegertracing/jaeger@v1.32.0/proto-gen/api_v2/collector.pb.go:210                                                                                                  
google.golang.org/grpc.(*Server).processUnaryRPC                                                                                                                                      
        google.golang.org/grpc@v1.45.0/server.go:1282                                                                                                                                 
google.golang.org/grpc.(*Server).handleStream                                                                                                                                         
        google.golang.org/grpc@v1.45.0/server.go:1619                                                                                                                                 
google.golang.org/grpc.(*Server).serveStreams.func1.2                                                                                                                                 
        google.golang.org/grpc@v1.45.0/server.go:921  
```

**What version did you use?**
Version: v0.48.0

**What config did you use?**
Config: (e.g. the yaml config file)

**Environment**
OS: Debian 11
Compiler(if manually compiled): vanilla docker image

**Additional context**

:blue_heart:

### LINKED ISSUE #15688: [processor/spanmetrics] getting key from cache error
## Description

I get an error in my app when it sent span to a otel collector which configed a  spanmetrics processor with `defaultDimensionsCacheSize`:
```
2022/10/27 02:37:46 rpc error: code = Unknown desc = value not found in metricKeyToDimensions cache by key "amamba\x00amamba.io.api.pipeline.v1alpha1.Pipelines/ReplayPipelineRun\x00SPAN_KIND_SERVER\x00STATUS_CODE_OK\x00cd7b102e-fbc5-4556-a0fd-718298df3de9\x00amamba-system\x00demo-dev-worker-03\x00amamba-apiserver-66c9486b55-5l4n8"
```

I trick the error to:
https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/92ad54f707a967386b764b6fdaea5a2ba4377319/processor/spanmetricsprocessor/processor.go#L335-L344

### Collector version

v0.61.0

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

### OpenTelemetry Collector configuration

_No response_

### Log output

_No response_

### Additional context

resolve by #15687

### PR DESCRIPTION
**Pull request by albertteoh**
(Resubmitting PR as per: https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/17063#issuecomment-1353869053)

**Description:** 
Fixes the `value not found in metricKeyToDimensions` error that appears after the metrics key cache is full.

This is achieved by emitting all metrics with cached dimension keys at configurable intervals (defaulting to `15s`) as suggested by @bogdandrutu in [this comment](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/16311#pullrequestreview-1188519807). 

This also aims to address a problem reported by users where CPU utilisation gradually increases over time, particularly with high cardinality dimensions. See: https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/9018#issuecomment-1252476417.

As the metrics are emitted at regular intervals, a separate goroutine is dedicated to out-of-band building and emitting of metrics to downstream metrics consumers; metrics aggregation is still performed in-band. 

Prior to this PR, if the dimension keys are not in cache (removed from eviction list), the `value not found in metricKeyToDimensions` would be returned. What also exacerbated this problem was that accesses to evicted items did not revive those keys back into the LRU cache.

**Link to tracking Issue:** 
Fixes #9018
Fixes #15688

Continues from #16024, #16311 and #16601

**Testing:** 

- Bug was easily reproducible by reducing the configurable dimensions key cache size down to a small value e.g. `2`.
- Wrote a unit test that reproduces the bug and implement the fix to pass the test.
- This has been exercised in a production environment with real data and confirmed it appears to have resolved the high CPU utilisation problem.

### CODE REVIEW

File: processor/spanmetricsprocessor/processor.go [hunk 1]
```diff
@@ -308,6 +328,12 @@ func (p *processorImp) collectLatencyMetrics(ilm pmetric.ScopeMetrics) error {
 	dps.EnsureCapacity(len(p.histograms))
 	timestamp := pcommon.NewTimestampFromTime(time.Now())
 	for key, hist := range p.histograms {
+		// If the key is not in the cache, simply don't publish it because it's likely
+		// the metric has expired (or the cache size is too small).
+		dimensions, ok := p.metricKeyToDimensions.Get(key)
+		if !ok {
+			continue
+		}
```
Comment (srikanthccv) [inline processor/spanmetricsprocessor/processor.go:336]: Isn't this silently ignoring the error? Wouldn't we still want to log the error message that the key was not found? Otherwise, how would one know why some metrics are missing from the collection?

File: processor/spanmetricsprocessor/processor.go [hunk 2]
```diff
@@ -85,6 +83,12 @@ type processorImp struct {
 	// An LRU cache of dimension key-value maps keyed by a unique identifier formed by a concatenation of its values:
 	// e.g. { "foo/barOK": { "serviceName": "foo", "operation": "/bar", "status_code": "OK" }}
 	metricKeyToDimensions *cache.Cache[metricKey, pcommon.Map]
+
+	ticker  *clock.Ticker
+	done    chan bool
```
[the remark this answers is not in the document]
Comment (albertteoh) [reply processor/spanmetricsprocessor/processor.go]: Yup, thanks, done in: [44699f3](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/17307/commits/44699f3dbac1d10abc632c2ec4fbf483a1834edf).

File: processor/spanmetricsprocessor/processor.go (hunk 1 above)
Comment (albertteoh) [reply processor/spanmetricsprocessor/processor.go]: Yup, good point, thanks for pointing this out. I've added a warning log message and removed the ineffectual comment because I think the log message should document the cause of the issue well enough. Done in: [8c66291](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/17307/commits/8c662917005db89ca868339d841fbaf88e52bb3c).

**Comment by albertteoh** [comment]
I noticed the [failing tests](https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/3819937914/jobs/6497928788#step:9:7275) were from `TestParser/RFC3164`, and doesn't appear to be caused by this PR.

File: processor/spanmetricsprocessor/factory.go [hunk 3]
```diff
@@ -44,9 +46,10 @@ func createDefaultConfig() component.Config {
 		AggregationTemporality: "AGGREGATION_TEMPORALITY_CUMULATIVE",
 		DimensionsCacheSize:    defaultDimensionsCacheSize,
 		skipSanitizeLabel:      featuregate.GetRegistry().IsEnabled(dropSanitizationGateID),
+		MetricsFlushInterval:   15 * time.Second,
 	}
 }
 
 func createTracesProcessor(_ context.Context, params processor.CreateSettings, cfg component.Config, nextConsumer consumer.Traces) (processor.Traces, error) {
-	return newProcessor(params.Logger, cfg, nextConsumer)
+	return newProcessor(params.Logger, cfg, nextConsumer, clock.Realtime().NewTicker(cfg.(*Config).MetricsFlushInterval))
```
Comment (MovieStoreGuy) [inline processor/spanmetricsprocessor/factory.go:54]: To allow for using this within testing, you can use:

```suggestion
func createTracesProcessor(ctx context.Context, params processor.CreateSettings, cfg component.Config, nextConsumer consumer.Traces) (processor.Traces, error) {
	return newProcessor(params.Logger, cfg, nextConsumer, clock.FromContext(ctx).NewTicker(cfg.(*Config).MetricsFlushInterval))
```

File: processor/spanmetricsprocessor/processor.go [hunk 4]
```diff
@@ -260,31 +290,21 @@ func (p *processorImp) tracesToMetrics(ctx context.Context, traces ptrace.Traces
...
 	p.lock.Unlock()
 
-	if err != nil {
-		return err
-	}
-
-	if err = p.metricsExporter.ConsumeMetrics(ctx, m); err != nil {
-		return err
+	if err := p.metricsExporter.ConsumeMetrics(ctx, m); err != nil {
+		p.logger.Error("Failed ConsumeMetrics: " + err.Error())
```
Comment (MovieStoreGuy) [inline processor/spanmetricsprocessor/processor.go:294]: Use structured logs to make it easier to search in logging platforms:

```suggestion
		p.logger.Error("Failed ConsumeMetrics", zap.Error(err))
```

**Review by MovieStoreGuy — COMMENTED** [review]
Happy new year! 🎆 

Only couple comments from me.

**Review by srikanthccv — APPROVED** [review]

File: processor/spanmetricsprocessor/factory.go (hunk 3 above)
Comment (albertteoh) [reply processor/spanmetricsprocessor/factory.go]: Good suggestion, done in: [75ddc2b](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/17307/commits/75ddc2bfbbdd81f14716fa6b1adf9f62c7b06031)

File: processor/spanmetricsprocessor/processor.go (hunk 4 above)
Comment (albertteoh) [reply processor/spanmetricsprocessor/processor.go]: Thanks, addressed in: [261ebbb](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/17307/commits/261ebbb816f031a9f4cfdd5a432a87a7f40a53e9)

**Comment by albertteoh** [comment]
> Happy new year! 🎆
> 
> Only couple comments from me.

Happy new year to you too, @MovieStoreGuy! Thanks for the review, I have addressed your comments.

**Comment by albertteoh** [comment]
Hi 👋🏼 , friendly nudge to see if an approver could please take a look? Thanks!

**Review by MovieStoreGuy — APPROVED** [review]
These changes make sense to me, and I am not too concerned with the breaking change since this component is highlighted as `InDevelopment` so there is warnings that are shown on collector start up that it can change.
