### PR TITLE
[cmd/opampsupervisor] Fix windows support

### LINKED ISSUE #34570: [cmd/opampsupervisor]: Fix supervisor on Windows
### Component(s)

cmd/opampsupervisor

## Description
Currently, the supervisor doesn't work on windows, nor do our e2e tests work.

The main culprit is the way signals are handled; go does not support sending `os.Interrupt` on Windows. So instead, we'll have to try and send a graceful shutdown signal on windows a different way.

### Collector version

9a04c69 

## Environment
Windows

### OpenTelemetry Collector configuration

_No response_

### Log output

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by BinaryFissionGames**
**Description:** <Describe what has changed.>
* Fixed windows improper signalling for the agent to shutdown.
* Fixed not closing files in e2e tests (windows will error if a file is not closed when it attempts to delete the temp directory said file is in)
* Fixed test config templates quoting (windows filepaths would have trouble since the backslash acts like a character escape)
* Added a workflow to allow running e2e tests for windows

**Link to tracking Issue:** Closes #34570

**Testing:** 
* Existing e2e tests cover this.
* I've manually tested remotely configuring a windows supervisor with BindPlane.

### CODE REVIEW

**Comment by BinaryFissionGames** [comment]
This needs the Run Windows label to test out the new workflow for the supervisor windows e2e tests.

File: cmd/opampsupervisor/supervisor/commander/commander_others.go [hunk 1]
```diff
@@ -0,0 +1,17 @@
+//go:build !windows
```
Comment (evan-bradley) [inline cmd/opampsupervisor/supervisor/commander/commander_others.go:1]:
```suggestion
// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

//go:build !windows
```

File: cmd/opampsupervisor/supervisor/commander/commander_windows.go [hunk 2]
```diff
@@ -0,0 +1,37 @@
+//go:build windows
```
Comment (evan-bradley) [inline cmd/opampsupervisor/supervisor/commander/commander_windows.go:1]:
```suggestion
// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

//go:build windows
```

File: cmd/opampsupervisor/supervisor/supervisor.go [hunk 3]
```diff
@@ -459,17 +459,11 @@ func (s *Supervisor) startOpAMPClient() error {
 func (s *Supervisor) startOpAMPServer() error {
 	s.opampServer = server.New(newLoggerFromZap(s.logger))
 
-	var err error
-	s.opampServerPort, err = s.findRandomPort()
```
Comment (evan-bradley) [inline cmd/opampsupervisor/supervisor/supervisor.go:463]: Can you explain this change?

Comment (BinaryFissionGames) [reply cmd/opampsupervisor/supervisor/supervisor.go:463]: When I was debugging issues on windows, it seemed like the agent wasn't able to connect because the server port in the agent config wasn't matching the port the supervisor was listening on. That's because the config is already constructed before the opamp server starts.

Basically the flow was:
1. getBootstrapInfo determines opamp port -> generate initial config -> startOpAMPServer determines opamp port.

It feels like we should only determine the opamp server port once initially, which is what this change is.

Comment (evan-bradley) [reply cmd/opampsupervisor/supervisor/supervisor.go:463]: Nice catch. You're right, we're setting it twice. I'm good with this, thanks for the explanation.

File: cmd/opampsupervisor/supervisor/commander/commander_others.go [hunk 4]
```diff
@@ -0,0 +1,20 @@
...
+
+package commander
+
+import (
+	"os"
+	"syscall"
+)
+
+func sendShutdownSignal(process *os.Process) error {
+	return process.Signal(os.Interrupt)
```
Comment (tigrannajaryan) [inline cmd/opampsupervisor/supervisor/commander/commander_others.go:14]: I think `os.Interrupt` is defined as `SIGINT`. Previously we were sending `SIGTEM`. Does this matter?

Comment (BinaryFissionGames) [reply cmd/opampsupervisor/supervisor/commander/commander_others.go:14]: Good question. I switched to using os.Interrupt/SIGINT here because os.Interrupt and os.Kill are the only signals guaranteed to be present across all systems (https://pkg.go.dev/os#Signal) - in practice, it might be that SIGTERM is defined for all the platforms we care to support, but I figured it doesn't hurt to use the more ubiquitous option here.

The collector treats both these [signals the same](https://github.com/open-telemetry/opentelemetry-collector/blob/ef07ea073562c4eb4d63a9032e84a802d8424fe2/otelcol/collector.go#L298), so I figured it'd be better if we used the more "cross-platform" version.

Comment (tigrannajaryan) [reply cmd/opampsupervisor/supervisor/commander/commander_others.go:14]: SGTM.

**Review by tigrannajaryan — APPROVED** [review]
Code LGTM (I don't have a way to verify this on Windows).

**Review by pjanotti — APPROVED** [review]

**Review by djaglowski — APPROVED** [review]
