### PR TITLE
[receiver/prometheusreceiver] fix prom receiver config reload

### LINKED ISSUE #40520: [receiver/prometheusreceiver] basic authentication for urls stopped working
### Component(s)

_No response_

## Description
The Prometheus receiver fails to scrape and endpoint with basic authentication enabled.

## Steps to Reproduce

* Set up basic authentication for a Prometheus endpoint, in this case 192.168.0.8:5572/metrics 
* Configure basic_auth in the scrape config
* Start collector

## Expected Result

Prometheus receiver is able to scrape the endpoint.

## Actual Result

Scrape fails with 401 Unauthorized

### Collector version

v0.127.0

## Environment
OS:   Ubuntu 24.04.2 LTS

### OpenTelemetry Collector configuration

```yaml
receivers:
  prometheus:
    config:
      scrape_configs:
        - job_name: integrations/rclone
          metrics_path: /metrics
          scrape_interval: 30s
          static_configs:
            - targets: ['192.168.0.8:5572']
          basic_auth:
            username: "USR"
            password: "PWD"
          relabel_configs:
            - source_labels: [__address__]
              action: replace
              target_label: instance
          metric_relabel_configs:
            - source_labels: [__name__]
              action: keep
              regex: "up|rclone_.*"

processors:
  cumulativetodelta:
  resourcedetection/dynatrace:
   override: false
   detectors: [dynatrace]
```

### Log output

```shell
2025-06-06T09:48:43.196Z        debug   Scrape failed   {"resource": {}, "otelcol.component.id": "prometheus", "otelcol.component.kind": "receiver", "otelcol.signal": "metrics", "scrape_pool": "integrations/rclone", "target": "http://192.168.0.8:5572/metrics", "err": "server returned HTTP status 401 Unauthorized"}

2025-06-06T09:48:43.196Z        warn    internal/transaction.go:150     Failed to scrape Prometheus endpoint    {"resource": {}, "otelcol.component.id": "prometheus", "otelcol.component.kind": "receiver", "otelcol.signal": "metrics", "scrape_timestamp": 1749203323194, "target_labels": "{__name__=\"up\", instance=\"192.168.0.8:5572\", job=\"integrations/rclone\"}"}
```

### Additional context

* Verified that the enpoint is reachable 
* Verified that enpont returns 401 Unauthorized without providing basic authentication using curl 192.168.0.8:5572/metrics 
* Verified that the endpoint returns the Prometheus metrics using curl -u USER:PWD 192.168.0.8:5572/metrics

### PR DESCRIPTION
**Pull request by erikburt**
#### Description

Fixing a bug where reloading the Prometheus config, caused config entries of type [Secret](https://github.com/prometheus/common/blob/95acce133ca2c07a966a71d475fb936fc282db18/config/config.go#L36-L44) to be replaced with the literal value of `<secret>`.

- Switches to new yaml library which allows for custom marshaling (shoutout to @ridwanmsharif)
- Adds unit test to ensure reloading promreceiver config doesn't mask secrets

#### Link to tracking issue

Fixes #40520, #40916

#### Testing

- I've added a unit test, validating the `Reload()` method doesn't mask secrets for existing `scrape_configs`
- Pointed a local instance at a simple http server to ensure the credentials are not affected (https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/40520#issuecomment-2978371920)
- Tested locally it with a `target_allocator` config, which was the original reason for the `Reload()` method, which introduced the bug (https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/40103/files#r2097520578)

#### Documentation

N/A

### CODE REVIEW

File: receiver/prometheusreceiver/config.go [hunk 1]
```diff
@@ -72,6 +72,12 @@ func (cfg *PromConfig) ContainsScrapeConfigs() bool {
 }
 
 func (cfg *PromConfig) Reload() error {
+	if cfg.ContainsScrapeConfigs() {
+		return nil
+	}
+
+	// only reload if there are no scrape configs, implying that there is a target_allocator.
+	// reloading existing scrape configs corrupts authentication configurations
```
Comment (krajorama) [inline receiver/prometheusreceiver/config.go]:
```suggestion
```

TL;DR;

Add these lines to reloadPromConfig before Marshal call instead at the top:
```
origMarshalSecretValue := commonconfig.MarshalSecretValue
commonconfig.MarshalSecretValue = true
defer func() {
	commonconfig.MarshalSecretValue = origMarshalSecretValue
}()
```

Longer:

I've tried to understand what's going on here and in the failing simplreprometheusreceiver.

The reason why reloadPromConfig fails on reload is that it's taking the already UnMarshaled [Prometheus config](https://github.com/prometheus/prometheus/blob/964bd7d1a9f8df51f15707273b6cc2775729e96c/config/config.go#L265), Marshals it and that Marshal replaces sensitive information with `<secret>`. So when it then loads the config again, the secret is wrong. So by commenting out this line we fix that.

And I tested that start/reload of the collector does work even if I have static scrape configs, since start/reload unmarshalls the whole collector config into a more generic collector config, which unmarshalls and loads the Prometheus config in it in a generic way. And the difference is that in that case reloadPromConfig takes a generic  `map[string]any` as input , not the Prometheus config type, so the Prometheus marshalling doesn't kick in, meaning the secrets aren't covered up.

In the simpleprometheusreceiver case we are giving Prometheus config to the receiver directly without it being loaded from marshalled text, so it would be reloadPromConfig's job to load it, but that never happens.

The most dumb thing I can think of is to not create the Prometheus config in the [simpleprometheusreceiver](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/7782fa008b5d6c283474559436bef736c43555ba/receiver/simpleprometheusreceiver/receiver.go#L145) as a struct, but as a string and load it with Prometheus config [load](https://github.com/prometheus/prometheus/blob/964bd7d1a9f8df51f15707273b6cc2775729e96c/config/config.go#L77). Basically avoid having to use Marshal on the Prometheus config since that scrambles the secrets.

By the way, this means that currently secrets don't work at all in the simpleprometheusreceiver. 

However I then realized that there's a global variable you can set to turn off marshalling secrets to `secret`

**Review by krajorama — CHANGES_REQUESTED** [review]

File: receiver/prometheusreceiver/config.go (hunk 1 above)
Comment (krajorama) [reply receiver/prometheusreceiver/config.go]: I'm not sure if we can have multiple receivers at the same time, maybe it's simpler to just set that variable to true all the time.

Comment (krajorama) [reply receiver/prometheusreceiver/config.go]: We've discussed this in the OTEL Prometheus WG meeting. 
The problem with using the global variable to not scramble the secrets is that concurrent goroutines might expose the secrets by mistake (e.g. /api/v1/status/config of Prometheus API). So we need to come up with a different solution here or in the simpleprometheusreceiver.

Comment (krajorama) [reply receiver/prometheusreceiver/config.go]: I've tested the current solution in the PR (early return) with the simpleprometheusreceiver for real (not in unit test), and I get the same error I we get in CI:
```
2025/06/19 14:42:21 collector server run finished with error: cannot start pipelines: failed to start "prometheus_simple" receiver: could not get scrape configs: scrape config cannot be fetched, main config was not validated and loaded correctly; should not happen
```

Comment (krajorama) [reply receiver/prometheusreceiver/config.go]: I've started to implement rendering YAML via basic types in the simpleprometheusreceiver so that I can use prometheus/[config.Load](https://github.com/prometheus/prometheus/blob/f69c83f5f1dce5f0b2f90172d5f6f9e2bda91fec/config/config.go#L77) on it, but it becomes complicated very fast when it comes to http config:
```
// Make a dumb representation so we can render the Prometheus
	// config into YAML without secrets being replaced with
	// <secret>. After that we can use the Prometheus code to load
	// the YAML properly.
	rawConfig := map[string]any{}
	rawConfig["global"] = config.DefaultGlobalConfig

	rawScrapeConfig := map[string]any{}
	rawScrapeConfig["scrape_interval"] = model.Duration(cfg.CollectionInterval)
	rawScrapeConfig["scrape_timeout"] = model.Duration(cfg.CollectionInterval)
	rawScrapeConfig["job_name"] = jobName
	rawScrapeConfig["honor_timestamps"] = true
	rawScrapeConfig["scheme"] = scheme
	rawScrapeConfig["metrics_path"] = cfg.MetricsPath
	rawScrapeConfig["params"] = cfg.Params
	rawScrapeConfig["static_configs"] = []map[string]any{
		{
			"targets": []string{cfg.Endpoint},
			"labels": labels,
		},
	}

	rawConfig["scrape_configs"] = []any{rawScrapeConfig}
	renderedConfig, err := yaml.Marshal(rawConfig)
	if err != nil {
		return nil, err
	}
```

Comment (krajorama) [reply receiver/prometheusreceiver/config.go]: I have a working workaround, but it's a bit crazy. It renders the global defaults and the scrape config with the normal marshaling of Prometheus (these bits don't have secrets). Then loads it to have it validated, then overwrites the http config.

Inserted [here](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/f3acb5e455ca9be51ef47228e2da44446b92c569/receiver/simpleprometheusreceiver/receiver.go#L137)
```go
	// Create a partial config without secrets to marshal, then
	// load the config from YAML to have it validated.
	rawConfig := config.Config{
		GlobalConfig: config.DefaultGlobalConfig,
		ScrapeConfigs: []*config.ScrapeConfig{
				scrapeConfig,
		},
	}
	
	renderedConfig, err := yaml.Marshal(rawConfig)
	if err != nil {
		return nil, err
	}

	logger := slog.New(zapslog.NewHandler(params.Logger.Core()))
	loadedConfig, err := config.Load(string(renderedConfig), logger)
	if err != nil {
		return nil, err
	}

	loadedConfig.ScrapeConfigs[0].HTTPClientConfig = httpConfig

	scrapeConfig.HTTPClientConfig = httpConfig
	out.PrometheusConfig = (*prometheusreceiver.PromConfig)(loadedConfig)

	return out, nil
```

Comment (krajorama) [reply receiver/prometheusreceiver/config.go]: Created issue in Prometheus for a long term solution: https://github.com/prometheus/prometheus/issues/16756

Comment (erikburt) [reply receiver/prometheusreceiver/config.go]: Thank you for taking the lead on this, I am well out of my depth here.

Feel free to close this PR.

Comment (erikburt) [reply receiver/prometheusreceiver/config.go]: From what I understood about the problem which could very well be wrong:

The issue is when marshalling the config, the fields of type [`Secret`](https://github.com/prometheus/common/blob/95acce133ca2c07a966a71d475fb936fc282db18/config/config.go#L28) are replaced with a placeholder value, so they're not leaked. 

The `Reload()` method was responsible for marshalling the config and then loading it again. This seems to not effect configs if they didn't contain credentials backed as type `Secret`. If the initial initial load works fine, is it possible to detect whether a config will obfuscate credentials during marshalling, and skip reloading/marshalling in those cases?

Comment (erikburt) [reply receiver/prometheusreceiver/config.go]: Attempted this solution in c8322a660e1f39f8db04ca5accceda074251bc27

(It does fix the simpleprometheusreceiver unit tests)

Comment (erikburt) [reply receiver/prometheusreceiver/config.go]: Your workaround seems more elegant than mine, but I'm not sure if there's more usages of type `Secret` that haven't been accounted for.

File: receiver/prometheusreceiver/config.go [hunk 2]
```diff
@@ -71,7 +72,77 @@ func (cfg *PromConfig) ContainsScrapeConfigs() bool {
...
+	return false // No field of type commonconfig.Secret with a non-empty string was found.
+}
+
 func (cfg *PromConfig) Reload() error {
+	if cfg.ContainsSecrets() {
+		return nil
+	}
+
+	// only reload if there are no scrape configs, implying that there is a target_allocator.
+	// reloading existing scrape configs corrupts authentication configurations
```
Comment (krajorama) [inline receiver/prometheusreceiver/config.go]:
```suggestion
	// Only reload if there are no secrets in the scrape configs, implying that there is
	// either a target_allocator or a simpleprometheusreceiver creating the config.
	// Reloading existing scrape configs corrupts authentication configurations.
	// TODO: undo when https://github.com/prometheus/prometheus/issues/16756
	// is solved.
```

File: receiver/prometheusreceiver/config.go (hunk 1 above)
Comment (krajorama) [reply receiver/prometheusreceiver/config.go]: I thought your workaround wouldn't work for simpleprometheusreceiver due to `basic_auth` or similar, but actually simpleprometheusreceiver is very restrictive. So I think maybe this is fine.

I think we need a test with target allocator or review from someone with target allocator knowledge.
In the mean time I suggested to update the doc string.

File: receiver/prometheusreceiver/config.go [hunk 3]
```diff
@@ -71,7 +72,77 @@ func (cfg *PromConfig) ContainsScrapeConfigs() bool {
...
+				return true
+			}
+		}
+		return false
+	}
+
+	// 3. We only care about structs for field iteration from this point.
+	if v.Kind() != reflect.Struct {
+		return false
+	}
```
Comment (erikburt) [inline receiver/prometheusreceiver/config.go]: There's technically a bug here, if a field is an array of `Secret`. Will fix this.

**Comment by erikburt** [comment]
Still trying to work at this but I'm having some troubles with my devenv, i have failing unit tests even on trunk. @krajorama if you want to open a new PR and take this to the finish line, feel free.

File: receiver/prometheusreceiver/config.go (hunk 1 above)
Comment (ridwanmsharif) [reply receiver/prometheusreceiver/config.go]: (drive by comment - sorry)

> The reason why reloadPromConfig fails on reload is that it's taking the already UnMarshaled [Prometheus config](https://github.com/prometheus/prometheus/blob/964bd7d1a9f8df51f15707273b6cc2775729e96c/config/config.go#L265), Marshals it and that Marshal replaces sensitive information with <secret>. So when it then loads the config again, the secret is wrong. So by commenting out this line we fix that.

Can we not use a custom marshaller here so this doesn't happen on reload. For example, see: https://github.com/GoogleCloudPlatform/ops-agent/blob/1c8f5801ca9e65e9e45dcdb90e570fc6d86fd908/confgenerator/prometheus.go#L137-L153

File: receiver/prometheusreceiver/config_test.go [hunk 4]
```diff
@@ -399,3 +402,81 @@ func TestLoadPrometheusAPIServerExtensionConfig(t *testing.T) {
...
+			checkFn: func(t *testing.T, dst *PromConfig) {
+				require.Len(t, dst.ScrapeConfigs, 1)
+				scrapeConfig := dst.ScrapeConfigs[0]
+				assert.Equal(t, "test-basic-auth", scrapeConfig.JobName)
+
+				// The critical check: ensure the password is not "<secret>"
+				require.NotNil(t, scrapeConfig.HTTPClientConfig.BasicAuth, "basic auth should be configured")
+				password := string(scrapeConfig.HTTPClientConfig.BasicAuth.Password)
+				assert.NotEqual(t, "<secret>", password, "password should not be marshaled as '<secret>'")
+				assert.Equal(t, "mysecretpassword", password, "password should preserve original value")
```
Comment (ArthurSens) [inline receiver/prometheusreceiver/config_test.go]: If password is equal to `mysecretpassword`, do we really need to assert not equal to `<secret>`? 🤔

File: receiver/prometheusreceiver/config_test.go [hunk 5]
```diff
@@ -399,3 +402,81 @@ func TestLoadPrometheusAPIServerExtensionConfig(t *testing.T) {
...
+			checkFn: func(t *testing.T, dst *PromConfig) {
+				require.Len(t, dst.ScrapeConfigs, 1)
+				scrapeConfig := dst.ScrapeConfigs[0]
+				assert.Equal(t, "test-bearer-token", scrapeConfig.JobName)
+
+				// Check that bearer token is preserved
+				require.NotNil(t, scrapeConfig.HTTPClientConfig.Authorization, "authorization should be configured")
+				credentials := string(scrapeConfig.HTTPClientConfig.Authorization.Credentials)
+				assert.NotEqual(t, "<secret>", credentials, "credentials should not be marshaled as '<secret>'")
+				assert.Equal(t, "mySecretBearerToken123", credentials, "credentials should preserve original value")
```
Comment (ArthurSens) [inline receiver/prometheusreceiver/config_test.go]: same here

**Review by ArthurSens — COMMENTED** [review]
LGTM, just some very small comments to make tests smaller. They are non-blocking of course!

I'd like to see another review from David or Krajo about the strategy as well, maybe they see something that I couldn't

File: receiver/prometheusreceiver/config_test.go (hunk 4 above)
Comment (erikburt) [reply receiver/prometheusreceiver/config_test.go]: 16381c91284311e7f58cfdd338e6b8d09aca9c59

File: receiver/prometheusreceiver/config_test.go (hunk 5 above)
Comment (erikburt) [reply receiver/prometheusreceiver/config_test.go]: 16381c91284311e7f58cfdd338e6b8d09aca9c59

**Review by ArthurSens — APPROVED** [review]

**Review by krajorama — APPROVED** [review]
LGTM, I'm kicking myself for not finding this solution even though I thought of it and did some search on the current lib :( Nice job!

I've tested this locally with a simple target that uses basic auth.

**Review by dashpole — APPROVED** [review]
