### PR TITLE
[pkg/ottl] Fix bug where function names were allowed in comparison

### LINKED ISSUE #33048: Filtering expression involving comparison with unknown symbol generates "This is a bug in the OpenTelemetry Transformation Language"
### Component(s)

processor/filter

## Description

Using the `filter` processor with an expression involving a comparison against an undefined symbol starting with an upper-case letter generates an error message the wording of which suggests a bug in the collector

```
Error: invalid configuration: processors::filter: unable to parse OTTL condition [...]: no value field set.
This is a bug in the OpenTelemetry Transformation Language
```

## Steps to Reproduce

Run the collector with a filter comparing against an undefined symbol, such as `value_double != NaN` (`NaN` is undefined at the time of writing), `value_int == IAmUndefined`, or `IAmUndefined == IAmUndefined`.

Note that the behaviour is different for symbols not starting with upper-case letters (which generate either parsing errors or `is not a valid path` errors).

See attached config for full example.

## Expected Result

Error message not indicating the error is a bug in the collector, such the one generated for lower-case symbols
```
[...] is not a valid path nor a valid OTTL keyword [...]
```
or mixed case symbols
```
[...] invalid syntax: 1:29: unexpected token [...]
```

## Actual Result

An error message indicating the issue is due to a bug in the collector
```
This is a bug in the OpenTelemetry Transformation Language
```

### Collector version

v0.100.0

## Environment

Precompiled binary with md5sum
```
41a4690a6ec5834a05a6615a8fdf1494  otelcol-contrib_0.100.0_linux_amd64.tar.gz
```

OS: Gentoo Linux

### OpenTelemetry Collector configuration

```yaml
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

exporters:
  debug:
    verbosity: detailed

processors:
  filter:
    metrics:
      datapoint:
          - 'value_double != NaN'

service:
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [filter]
      exporters: [debug]
```

### Log output

```shell
Error: invalid configuration: processors::filter: unable to parse OTTL condition "value_double != NaN": no value field set. This is a bug in the OpenTelemetry Transformation Language
2024/05/14 16:38:05 collector server run finished with error: invalid configuration: processors::filter: unable to parse OTTL condition "value_double != NaN": no value field set. This is a bug in the OpenTelemetry Transformation Language
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by TylerHelmuth**
**Description:** 
Fix a bug where a condition like `"foo" = Bar` resulted in the error `no value field set. This is a bug in the OpenTelemetry Transformation Language`.

**Link to tracking Issue:** <Issue number if applicable>
Closes https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/33048

**Testing:** <Describe what testing was performed and which tests were added.>
Updated unit tests

### CODE REVIEW

**Review by atoulme — APPROVED** [review]

File: pkg/ottl/parser_test.go [hunk 1]
```diff
@@ -1952,6 +1950,7 @@ func Test_parseCondition(t *testing.T) {
 		{`One() == 1`, false},
 		{`test(fail())`, true},
 		{`Test()`, false},
+		{`"test" == Foo`, true},
```
Comment (evan-bradley) [inline pkg/ottl/parser_test.go:1953]: What does the error look like now?

**Review by evan-bradley — APPROVED** [review]
Great catch.

File: pkg/ottl/parser_test.go (hunk 1 above)
Comment (TylerHelmuth) [reply pkg/ottl/parser_test.go:1953]: It looks like 

```
statement has invalid syntax: 1:50: unexpected token "<EOF>" (expected "(" (Argument ("," Argument)*)? ")" Key*)
```

Which isn't the best, but at least it gives you hints where the issue is.  I played around with keeping `FunctionName` in `value` and then doing a custom error when it is set, but that caused parsing issues bc `value` is checked before `FunctionName` in `arguments`.  It might be possible with some fancy negative lookaheads

Comment (michalpristas) [reply pkg/ottl/parser_test.go:1953]: was playing with this today, mainly to understand it better and did some more or less crazy/dumb ideas but didn't managed to get any better error message than this one

**Review by michalpristas — APPROVED** [review]

File: pkg/ottl/parser_test.go (hunk 1 above)
Comment (evan-bradley) [reply pkg/ottl/parser_test.go:1953]: I think overall we should try to avoid any grammar parsing errors since I think to most users they're incredibly cryptic. That said, this is still better than an error with "This is a bug in the OpenTelemetry Transformation Language" in it. I'd say let's get this in for now and circle back later.
