### PR TITLE
[cmd/opampsupervisor] Conditionally use TLS config

### LINKED ISSUE #35283: [cmd/opampsupervisor] TLS should only be used for 'wss' and 'https'
### Component(s)

cmd/opampsupervisor

## Description
When connecting to an OpAMP management server using `ws` or `http` protocols, `server.tls.insecure` needs to be configured as `true`. This should not be necessary since it should be implied with those protocols that it is insecure.

## Steps to Reproduce
Run the supervisor configured to connect to an OpAMP management server using `ws` or `http`. My server config is below:
```yaml
server:
  endpoint: ws://localhost:3001/v1/opamp
  headers:
    Authorization: "Secret-Key <secret-key>"
```

## Expected Result
I expected the supervisor to connect successfully without error.

## Actual Result
The supervisor fails with this message and enters a retry loop that continually fails with the same error.
```
2024-09-18T13:50:48.573-0400	ERROR	supervisor/supervisor.go:411	Failed to connect to the server	{"error": "tls: first record does not look like a TLS handshake"}
```
Only once the supervisor config is updated with `server.tls.insecure: true` does the supervisor manage to successfully connect to the server.

### Collector version

main (present in current commit 292f291)

## Environment
OS: macOS Sequoia 15.0
Compiler: go 1.23

### OpenTelemetry Collector configuration

```yaml
server:
  endpoint: ws://localhost:3001/v1/opamp
  headers:
    Authorization: "Secret-Key <secret key>"

capabilities:
  accepts_remote_config: true
  reports_remote_config: true

agent:
  executable: ./dist/collector_darwin_arm64

storage:
  directory: "./local/supervisor_storage"
```

### Log output

```shell
2024-09-18T13:50:48.573-0400	ERROR	supervisor/supervisor.go:411	Failed to connect to the server	{"error": "tls: first record does not look like a TLS handshake"}
2024-09-18T13:50:48.573-0400	ERROR	supervisor/logger.go:26	Connection failed (tls: first record does not look like a TLS handshake), will retry.
2024-09-18T13:50:48.978-0400	ERROR	supervisor/supervisor.go:411	Failed to connect to the server	{"error": "tls: first record does not look like a TLS handshake"}
2024-09-18T13:50:48.979-0400	ERROR	supervisor/logger.go:26	Connection failed (tls: first record does not look like a TLS handshake), will retry.


This continues until I stop the process.
```

### Additional context

I believe the relevant code is [here](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/cmd/opampsupervisor/supervisor/supervisor.go#L395). `LoadTLSConfig()` is always called when creating the OpAMP client and it does not consider the protocol being used. I have a fix in progress that will skip calling `LoadTLSConfig()` if we're using `ws` or `http`.

### PR DESCRIPTION
**Pull request by dpaasman00**
**Description:** <Describe what has changed.>

Fixes an issue where TLS would be used despite the opamp server using `ws` or `http` protocols. 

Before a TLS config would always get created, causing the connection to always use TLS settings. This change first checks which protocol we're using before creating a TLS config.

**Link to tracking Issue:** <Issue number if applicable> Fixes #35283 

**Testing:** <Describe what testing was performed and which tests were added.>
Removed `tls.insecure_skip_verify: true` from e2e test configs which were using `ws` protocol since they are no longer needed.

**Documentation:** <Describe the documentation added.>

### CODE REVIEW

File: cmd/opampsupervisor/supervisor/supervisor.go [hunk 1]
```diff
@@ -392,9 +394,17 @@ func (s *Supervisor) startOpAMP() error {
 func (s *Supervisor) startOpAMPClient() error {
 	s.opampClient = client.NewWebSocket(newLoggerFromZap(s.logger))
 
-	tlsConfig, err := s.config.Server.TLSSetting.LoadTLSConfig(context.Background())
+	// determine if we need to load a TLS config or not
+	var tlsConfig *tls.Config
+	url, err := url.Parse(s.config.Server.Endpoint)
```
Comment (bacherfl) [inline cmd/opampsupervisor/supervisor/supervisor.go:399]: nit: to avoid colliding with the `url` package name
```suggestion
	parsedUrl, err := url.Parse(s.config.Server.Endpoint)
```

**Review by BinaryFissionGames — APPROVED** [review]
This is working well for me (tested both ws and wss against BPOP), seems good after Florian's comment is addressed.

**Comment by BinaryFissionGames** [comment]
@tigrannajaryan PTAL when you get a chance

**Review by djaglowski — APPROVED** [review]

**Review by evan-bradley — APPROVED** [review]
Thanks @dpaasman00!

**Comment by priyeshsingh550** [comment]
@dpaasman00 Is this addressed i am still getting the same tls handshake error while using ws protocol

2024/10/24 07:23:38 Failed to connect to the server: tls: first record does not look like a TLS handshake
2024/10/24 07:23:38 Connection failed (tls: first record does not look like a TLS handshake), will retry.
