### PR TITLE
[exporter/clickhouse] Update default logs table schema

### LINKED ISSUE #32215: ClickHouse Logs table sub-optimal primary key (SeverityNumber vs SeverityText)
### Component(s)

exporter/clickhouse

## Description

The `otel_logs` table definition in the ClickHouse exporter uses `SeverityText` as part of the primary key.

And `SeverityNumber` is not even listed at all in the primary key.

https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/25e300afa69ce35f01e62d376a50f6115c1b6d70/exporter/clickhouseexporter/exporter_logs.go#L158

## Steps to Reproduce

N/A. Primarily raising this as a design issue for now. There might be implications to insert and query performance.

## Expected Result

`SeverityNumber` should be part of the primary key, since it is the field that the source system's severities are mapped to when translating from an external log model into OTEL Logs data model. And `SeverityText` comes from the external log source and is not a representation of severity as it is defined in OTEL's Log data model.

## Actual Result

`SeverityText` is part of the primary key.

### Collector version

v0.97.0

## Environment
OS: "Ubuntu 22.04"

### OpenTelemetry Collector configuration

_No response_

### Log output

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by SpencerTorres**
**Description:**

Closes #32215 

This PR updates the default `otel_logs` table schema.
The intent of this change is to provide a good starting point for users to [***create their own schema***](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/exporter/clickhouseexporter#schema-management). This schema works as-is, but should be tuned to fit the final workflow when querying (specifically the indices, `TTL`, and `ORDER BY`).

There are no breaking changes, this schema is compatible with the previous `INSERT` statement. This does not affect existing users, only new users that have `create_schema` enabled in the config.

Notable changes:
- 2 new Timestamp columns have been added for `Date` and `DateTime` types. Nanoseconds `Timestamp` is preserved. This does not affect the `INSERT` since these are derived by `DEFAULT` from `Timestamp`.
- Partitioning has been optimized to use a larger time range, based on the new `TimestampDate` time
- `TTL` is now based on `TimestampTime`
- Data types for `TraceFlags` and `SeverityNumber` have been reduced to a `UInt8`, since this is all that is required by the OTel specification.
- String-like columns have been changed to `LowCardinality` where appropriate
- `ORDER BY` has been reduced to only `TimestampDate` and `TimestampTime`. This offers good performance as-is, but if you have a specific workflow that depends on `ServiceName` for example, feel free to add it at as the first column.
- Updated the TTL expression generator, dependent functions will need to convert to DateTime type manually (dependent code has been updated for this)

**Link to tracking Issue:** <Issue number if applicable>

**Testing:**
- Updated integration tests to include new timestamp columns
Integration tests are disabled, but I fixed them locally to test that this change works as intended.
Unit tests are passing as well.

**Documentation:**
- Updated README quick-start queries to use the more efficient `TimestampTime` column
- Example DDL has been updated

### CODE REVIEW

File: exporter/clickhouseexporter/exporter_logs.go [hunk 1]
```diff
@@ -133,34 +133,37 @@ const (
...
+	INDEX idx_res_attr_key mapKeys(ResourceAttributes) TYPE bloom_filter(0.01) GRANULARITY 1,
+	INDEX idx_res_attr_value mapValues(ResourceAttributes) TYPE bloom_filter(0.01) GRANULARITY 1,
+	INDEX idx_scope_attr_key mapKeys(ScopeAttributes) TYPE bloom_filter(0.01) GRANULARITY 1,
+	INDEX idx_scope_attr_value mapValues(ScopeAttributes) TYPE bloom_filter(0.01) GRANULARITY 1,
+	INDEX idx_log_attr_key mapKeys(LogAttributes) TYPE bloom_filter(0.01) GRANULARITY 1,
+	INDEX idx_log_attr_value mapValues(LogAttributes) TYPE bloom_filter(0.01) GRANULARITY 1,
+	INDEX idx_body Body TYPE tokenbf_v1(32768, 3, 0) GRANULARITY 1
 ) ENGINE = %s
+PARTITION BY toYYYYMM(TimestampDate)
+ORDER BY (TimestampDate, TimestampTime)
```
Comment (hanjm) [inline exporter/clickhouseexporter/exporter_logs.go:164]: general LGTM.  just wondering `ORDER BY (TimestampDate, TimestampTime)` may not better than ORDER BY ServiceName, SeverityText, toUnixTimestamp(Timestamp), beacause [ServiceName](https://opentelemetry.io/docs/specs/semconv/resource/#service) and SeverityText( also as well-known logLevel) is the most common filter when query service log, can you write more text explain why remove them? thanks.

Comment (SpencerTorres) [reply exporter/clickhouseexporter/exporter_logs.go:164]: It can be difficult to model a decent table that works for everyone (consider issues like https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/32215)

The idea behind this change is to simply make time range queries work as best they can. Every log has a timestamp, but not always a proper `ServiceName` or `Severity*`. Some OTel data isn't composed very well. `SeverityText` might not be as good as `SeverityNumber`, and if we try to add all of these to `ORDER BY` then it starts to lose its purpose as a primary index.

For those who will be using this exporter in production, the goal is to have them use this as a starting point, and then add the appropriate columns to the `ORDER BY` depending on their primary column. For example, look at how [this blog post](https://clickhouse.com/blog/building-a-logging-platform-with-clickhouse-and-saving-millions-over-datadog#schema) chooses to use `PodName` and `Timestamp`:
```sql
ORDER BY (PodName, Timestamp)
```

What we've found is that a lot of these values are not necessary in the order by, especially ones after the `Timestamp*` columns (such as `TraceId` in the current version). Most log queries are going to be in a tight range of time (5, 15, 30, 60 minutes) and these smaller `ORDER BY` clauses favor this. Again, you can always go a step further by adding your preferred column to the start of it, such as `ServiceName`, `SeverityText`, `PodName`, or some combination of these.

The goal is to have a good default that is easy for others to expand on for their own deployment, while also still giving a good default for those who *don't* bother to configure one. If you're at the scale where this schema becomes a problem, you would already be using your own schema.

Comment (hanjm) [reply exporter/clickhouseexporter/exporter_logs.go:164]: ServiceName is a required in spec.  https://opentelemetry.io/docs/specs/semconv/resource/#service. to say the least, ServiceName is needed. see also as https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/31670

in `PodName` blog case , i think most common usage query pattern is `PodName like xxx%`, not `PodName= xxx`, mostly we query a workload log, not the specific pod log. actually, use a serviceName as workload name will be more reasonaly.

Comment (SpencerTorres) [reply exporter/clickhouseexporter/exporter_logs.go]: This is reasonable enough since it is a default schema, and if someone needs to change it they're free to do so for their deployment.

As you suggested, I have added `ServiceName` to the default schema.

**Review by Frapschen — APPROVED** [review]

**Review by hanjm — APPROVED** [review]

**Review by dmitryax — APPROVED** [review]
Should we similarly update other metrics/traces tables?

**Comment by SpencerTorres** [comment]
> Should we similarly update other metrics/traces tables?

Absolutely, but they will need to be evaluated separately (especially metrics)
