### PR TITLE
[pkg/stanza] Allow 'parse_to' fields to accept 'attributes' and 'resource'

### LINKED ISSUE #14002: regex_parser: resource cannot be referenced without subfield
**Describe the bug**
regex_parser: resource cannot be referenced without subfield

**Steps to reproduce**
```
operators:
      - type: regex_parser
        parse_from: attributes["log.file.path"]
        parse_to: resource
        regex: 'vcslogs/(?P<service>.+?)/'
```

**What did you expect to see?**
set resource.service

**What did you see instead?**
regex_parser: resource cannot be referenced without subfield

I have to set `parse_to: resource.xxx`, and the `service` will be a property of `xxx`, and i want the `service` be a property of `resource`

### PR DESCRIPTION
**Pull request by djaglowski**
This change enables parsers to parse directly to 'attributes' or 'resource'.

In order to allow alternate validation behavior while unmarshaling, a new RootableField struct was introduced, which wraps the Field struct.

See https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/10280

Resolves https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/14002

### CODE REVIEW

File: pkg/stanza/entry/field.go [hunk 1]
```diff
@@ -33,6 +33,11 @@ type Field struct {
 	FieldInterface
 }
 
+// RootableField is a Field that may refer directly to "attributes" or "resource"
+type RootableField struct {
```
Comment (TylerHelmuth) [inline pkg/stanza/entry/field.go:37]: @djaglowski is `RootableField` essentially a wrapper for `Field` that gets used in `ParserConfig` to help determine if a subfield is necessary or not?  The primary business logic happening in `newField`'s if statements?

**Review by TylerHelmuth — COMMENTED** [review]
One question.

File: pkg/stanza/entry/field.go (hunk 1 above)
Comment (djaglowski) [reply pkg/stanza/entry/field.go:37]: Yes, that's correct. The motivation for wrapping `Field` is to 1) implement `FieldInterface` easily and consistently, while 2) allowing for slightly different unmarshal/validation logic based on the type.

**Review by TylerHelmuth — APPROVED** [review]
