### PR TITLE
[receiver/windowseventlog]: If remote.domain is configured, pass it into EvtRPCLogin

### LINKED ISSUE #41950: pkg/stanza remote collection appears to ignore domain
### Component(s)

receiver/windowseventlog, pkg/stanza

## Description

While setting up the remote collection on the `windowseventlogreceiver` we were encountering this error:

Image

Which made us look into the path from windowseventlogreceiver => pkg/stanza/operator/input/windows and we  believe that we're exposing configuration for Domain. 

## Steps to Reproduce

- Windows Server with Active Directory
- Domain controller (e.g., CORP.LOCAL)  
- Domain user account (e.g., CORP\eventreader)
- Target machine with Windows Event Log service
- OpenTelemetry Collector with stanza Windows input

## Expected Result

Our provider would not error the connection based off domain rules.

## Actual Result

Our provider errors with `Provider Rejection`

### Collector version

v0.132.0

## Environment
OS: Windows 10

### OpenTelemetry Collector configuration

```yaml
receivers:
  windowseventlog:
    channel: Application
    remote:
      server: "target-server.corp.local"
      username: "eventreader"          # Just username, no domain
      password: "SecurePassword123"
      domain: "CORP"
```

### Log output

```shell

```

### Additional context

Original Feature PR: https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/33601

### Tip

<sub>[React](https://github.blog/news-insights/product-news/add-reactions-to-pull-requests-issues-and-comments/) with 👍 to help prioritize this issue. Please use comments to provide useful context, avoiding `+1` or `me too`, to help us triage it. Learn more [here](https://opentelemetry.io/community/end-user/issue-participation/).</sub>

### PR DESCRIPTION
**Pull request by schmikei**
#### Description

Fixing what appears to be a bug/miss from the remote windows event log collection. It appears to myself that we're passing down from windowseventlogreceiver to the pkg/stanza but the actual syscall for `evtOpenSession` does not actually pass the `domain` field. 

Please let me know if I'm missing anything!

Docs for context of the structures being updated to pass the value into.

https://learn.microsoft.com/en-us/windows/win32/api/winevt/ns-winevt-evt_rpc_login

https://learn.microsoft.com/en-us/windows/win32/api/winevt/nf-winevt-evtopensession

#### Link to tracking issue
Fixes #41950

#### Testing

Added small unit test to ensure we are passing the value using the existing test framework.

#### Documentation

Changelog

### CODE REVIEW

File: pkg/stanza/operator/input/windows/input.go [hunk 1]
```diff
@@ -75,6 +75,9 @@ func (i *Input) defaultStartRemoteSession() error {
 		User:     windows.StringToUTF16Ptr(i.remote.Username),
 		Password: windows.StringToUTF16Ptr(i.remote.Password),
 	}
+	if i.remote.Domain != "" {
```
Comment (pjanotti) [inline pkg/stanza/operator/input/windows/input.go:78]: It should be ok to add it above since and empty string should produce the same output. This way we don't need the `if` test

**Review by pjanotti — COMMENTED** [review]
Nice @schmikei! Thanks for the investigation and PR!

**Review by atoulme — APPROVED** [review]

**Comment by atoulme** [comment]
Approved by codeowner, merging.
