### PR TITLE
[fileconsumer] Add `compression:auto` to support ingesting mixed file types 

### LINKED ISSUE #37772: Filelog receiver does not support mixed compression use case
### Component(s)

receiver/filelog

## Description

A common use-case is to read a live uncompressed log, which is typically rotated on a daily basis into a compressed version with some date suffix.

Now, to support outages of the collector (e.g. let's say the service was stopped for 3 days) we'd like to have a wildcard entry on the `include` statement to pick up all the logs, and backfill them across the duration of the outage.

As far as I can tell, it is not currently possible to support this use-case in the filelog receiver. We could potentially support the use case with two separate filelog receivers, however, this is actually a bad approach as every time the file is rotated, the entire batch of logs will be shipped again by the second scraper.

## Steps to Reproduce

```yaml
filelog/frr:
    # wildcard to scoop up raw log `test.log` and rotated logs `test.log.0.gz
    include: [ "/var/logs/test.log*" ]
    start_at: beginning
    # persistent storage for positions file
    storage: file_storage/frr
```

Setup a receiver like this, and observe how it can happily ingest `test.logs`. But when we rotate (mv to test.logs.0, then gzip) the new log is shipped, but with binary content in the string. So it is recognized as a new file and shipped twice (but with gzipped data).

Setting `compression: gzip` results in the raw log not being ingester, and the following errors:

```json
{"level":"error","ts":"2025-02-07T14:50:45.977+0100","caller":"reader/reader.go:82","msg":"failed to create gzip reader","service.name":"otelcol-osag","kind":"receiver","name":"filelog/test","data_type":"logs","component":"fileconsumer","path":"/tmp/test.log","error":"gzip: invalid header"}
```

## Expected Result

I would expect this use-case to be supported. When the log is rotated and compressed, the compressed data should not be shipped again.

## Actual Result

We cannot watch compressed and uncompressed logs at the same time.

### Collector version

0.118.0

## Environment
Running on K8s. 1.30

### OpenTelemetry Collector configuration

```yaml

```

### Log output

```shell

```

### Additional context

This could probably be solved by inspecting the file MIME type, and inspecting the uncompressed fingerprint to determine if the file has been seen before.

### PR DESCRIPTION
**Pull request by khushijain21**
#### Description
This PR supports the use case of reading from mixed file types.  To support reading from both compressed and uncompressed file - configure 
```
compression: auto
```

#### Link to tracking issue
Fixes https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/37772

#### Testing
Start otelcollector-contrib with following config file
```
receivers:
  filelog:
    include: [ "./test.log*" ]  # Path to log file
    start_at: beginning              # Read from the start of the file
    include_file_path: true
    include_file_name: true
    compression: auto
  

exporters:
  debug/1:
    verbosity: detailed

service:
  telemetry:
    logs: 
      level: debug
  pipelines:
    logs:
      receivers: [filelog]
      exporters: [debug/1]
```

Have `test.log` and `test.log.gz` in your path. We have two readers - one for plain text and other for gzipped file.

### CODE REVIEW

File: pkg/stanza/fileconsumer/internal/reader/reader.go [hunk 1]
```diff
@@ -66,33 +68,40 @@ func (r *Reader) ReadToEnd(ctx context.Context) {
...
-		info, err := r.file.Stat()
-		if err != nil {
-			r.set.Logger.Error("failed to stat", zap.Error(err))
-			return
-		}
-		currentEOF := info.Size()
+	// if compression is set, we support mixed compression use case
+	if len(r.compression) != 0 {
+		// Identifying a filename by its extension may not always be correct. We could have compressed file without the .gz extension
+		if filepath.Ext(r.fileName) == ".gz" && slices.Contains(r.compression, "gzip") {
```
Comment (khushijain21) [inline pkg/stanza/fileconsumer/internal/reader/reader.go:73]: this could be breaking change for users if they are reading from a gzip compressed file that does not include `.gz` extension in its filename.

File: pkg/stanza/fileconsumer/config.go [hunk 2]
```diff
@@ -87,7 +87,7 @@ type Config struct {
 	Header                  *HeaderConfig   `mapstructure:"header,omitempty"`
 	DeleteAfterRead         bool            `mapstructure:"delete_after_read,omitempty"`
 	IncludeFileRecordNumber bool            `mapstructure:"include_file_record_number,omitempty"`
-	Compression             string          `mapstructure:"compression,omitempty"`
+	Compression             []string        `mapstructure:"compression,omitempty"`
```
Comment (VihasMakwana) [inline pkg/stanza/fileconsumer/config.go:90]: Instead of changing this, can we add a new config `Compressions` (plural) indicating a mixed use case.
Simultaneously, we can deprecate `Compression` and remove it in future releases. https://github.com/open-telemetry/opentelemetry-collector/blob/main/docs/coding-guidelines.md#api-breaking-changes highlights the deprecation process.

File: .chloggen/support-mixed-compression-use-case.yaml [hunk 3]
```diff
@@ -0,0 +1,27 @@
+# Use this changelog template to create an entry for release notes.
+
+# One of 'breaking', 'deprecation', 'new_component', 'enhancement', 'bug_fix'
+change_type: enhancement
```
[the remark this answers is not in the document]
Comment (VihasMakwana) [reply .chloggen/support-mixed-compression-use-case.yaml:4]: `breaking` is not applicable if we decide to go with https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/38510#discussion_r1998709726

**Comment by khushijain21** [comment]
@atoulme any reason you converted this to draft? 🤔

File: pkg/stanza/fileconsumer/config.go (hunk 2 above)
Comment (khushijain21) [reply pkg/stanza/fileconsumer/config.go:90]: We could do that, will wait for others to +1 this before I go ahead and make this change

Comment (khushijain21) [reply pkg/stanza/fileconsumer/config.go:90]: @atoulme can you provide your feedback here?

Comment (andrzej-stencel) [reply pkg/stanza/fileconsumer/config.go:90]: We should not change the type of the `compression` option, definitely not without a deprecation period, but ideally not at all.

Another option is to add `auto` option as a value for `compression`, which would then decide whether to uncompress the file or not based on the file's extension.

This is with the caveat that I'm not sure that deciding on compression solely based on the file's extension is the right approach.

**Review by andrzej-stencel — COMMENTED** [review]
In general I tend to support the idea to be able to read logs from both uncompressed and compressed files in one File Log receiver instance. This can be currently done by configuring two separate File Log receivers, one matching only `*.gz` files with compression configured and another excluding `*.gz` files, configured without compression.

I don't think we should be changing the type of the `compression` option, it would be a breaking change and we want to avoid those as much as possible in a beta-stability component that is as widely used as the File Log receiver.

**Comment by atoulme** [comment]
> @atoulme any reason you converted this to draft? 🤔

I moved it to draft as @VihasMakwana asked you to edit the changelog. Please move it back to ready for review when all feedback is addressed and the CI passes.

File: pkg/stanza/fileconsumer/config.go (hunk 2 above)
Comment (atoulme) [reply pkg/stanza/fileconsumer/config.go:90]: I agree with what @andrzej-stencel wrote.

**Comment by atoulme** [comment]
Please attend to the failing lint check:
```
Error: stanza/fileconsumer/internal/reader/reader.go:73:3: ifElseChain: rewrite if-else to switch statement (gocritic)
		if filepath.Ext(r.fileName) == ".gz" && slices.Contains(r.compression, "gzip") {
		^
```

**Comment by atoulme** [comment]
@djaglowski please review as codeowner

**Review by VihasMakwana — APPROVED** [review]

File: pkg/stanza/fileconsumer/internal/fingerprint/fingerprint_test.go [hunk 4]
```diff
@@ -308,3 +312,28 @@ func TestMarshalUnmarshal(t *testing.T) {
...
+	defer gzipWriter.Close()
+
+	data := []byte("this is a first test line")
+	// Write data
+	n, err := gzipWriter.Write(data)
+	require.NoError(t, err)
+	require.NoError(t, gzipWriter.Close())
+	require.NotZero(t, n, "gzip file should not be empty")
+
+	// set seek to the start of the file``
```
Comment (mauri870) [inline pkg/stanza/fileconsumer/internal/fingerprint/fingerprint_test.go:330]:
```suggestion
	// set seek to the start of the file
```

File: receiver/filelogreceiver/README.md [hunk 5]
```diff
@@ -62,7 +62,7 @@ Tails and parses logs from files.
...
 | `ordering_criteria.sort_by.ascending` |                                      | Sort direction                                                                                                                                                                                                                                                  |
-| `compression`                         |                                      | Indicate the compression format of input files. If set accordingly, files will be read using a reader that uncompresses the file before scanning its content. Options are `` or `gzip`                                                                          |
+| `compression`                         |                                      | Indicate the compression format of input files. If set accordingly, files will be read using a reader that uncompresses the file before scanning its content. Options are  `gzip` or `auto`. `auto` auto-detects file compression type.                                                                          |
```
[the remark this answers is not in the document]
Comment (khushijain21) [reply receiver/filelogreceiver/README.md]: I updates the docs

File: pkg/stanza/fileconsumer/internal/fingerprint/fingerprint.go [hunk 6]
```diff
@@ -26,8 +28,27 @@ func New(first []byte) *Fingerprint {
 	return &Fingerprint{firstBytes: first}
 }
 
+func hasGzipExtension(filename string) bool {
+	return filepath.Ext(filename) == ".gz"
+}
+
 func NewFromFile(file *os.File, size int) (*Fingerprint, error) {
 	buf := make([]byte, size)
+	if hasGzipExtension(file.Name()) {
```
[the remark this answers is not in the document]
Comment (khushijain21) [reply pkg/stanza/fileconsumer/internal/fingerprint/fingerprint.go:37]: I added two changelog entries. One with the breaking change -for the new way of computing fingerprint for compressed files.

And the other entry is an enhancement - for  `compression:auto`.
wdyt?

File: pkg/stanza/fileconsumer/internal/reader/reader.go [hunk 7]
```diff
@@ -69,30 +70,31 @@ func (r *Reader) ReadToEnd(ctx context.Context) {
...
-		r.reader = gzipReader
 		// Offset tracking in an uncompressed file is based on the length of emitted tokens, but in this case
 		// we need to set the offset to the end of the file.
 		defer func() {
 			r.Offset = currentEOF
 		}()
+	case "auto":
+		// TODO: Find a better solution
+		// Identifying a filename by its extension may not always be correct. We could have a compressed file without the .gz extension
+		if filepath.Ext(r.fileName) == ".gz" {
```
Comment (djaglowski) [inline pkg/stanza/fileconsumer/internal/reader/reader.go:85]: I think we should consider storing the "file type" in the `reader.Metadata` so we have a faster way to evaluate this in the hot path.

File: pkg/stanza/fileconsumer/internal/reader/reader.go [hunk 8]
```diff
@@ -69,30 +70,31 @@ func (r *Reader) ReadToEnd(ctx context.Context) {
...
+			currentEOF, err := r.createGzipReader()
+			if err != nil {
+				return
+			}
+			// Offset tracking in an uncompressed file is based on the length of emitted tokens, but in this case
+			// we need to set the offset to the end of the file.
```
[the remark this answers is not in the document]
Comment (khushijain21) [reply pkg/stanza/fileconsumer/internal/reader/reader.go:91]: > Does this rely on an assumption that every gzip section is fully consumed every time?

Yes, it does not handle graceful shutdown. If the process is killed while ingesting a gzip file, it would re-ingest the file when it starts again. 

I agree the original implementation has bugs in how it handles the offset. I think it is better to defer it to a separate issue since this is not trivial.

> I think all this complexity hints that reader.Reader should be an interface with multiple implementations.

I like the idea that every reader can decide on its implementation

File: pkg/stanza/fileconsumer/internal/reader/reader.go [hunk 9]
```diff
@@ -69,30 +70,31 @@ func (r *Reader) ReadToEnd(ctx context.Context) {
...
-		}
-		r.reader = gzipReader
 		// Offset tracking in an uncompressed file is based on the length of emitted tokens, but in this case
 		// we need to set the offset to the end of the file.
 		defer func() {
 			r.Offset = currentEOF
 		}()
+	case "auto":
+		// TODO: Find a better solution
+		// Identifying a filename by its extension may not always be correct. We could have a compressed file without the .gz extension
```
[the remark this answers is not in the document]
Comment (khushijain21) [reply pkg/stanza/fileconsumer/internal/reader/reader.go:84]: https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/39682

**Review by djaglowski — APPROVED** [review]

File: pkg/stanza/fileconsumer/internal/fingerprint/fingerprint.go (hunk 6 above)
[the remark this answers is not in the document]
Comment (andrzej-stencel) [reply pkg/stanza/fileconsumer/internal/fingerprint/fingerprint.go:37]: Can we extract this change to a separate pull request?

I'm worried that adding a breaking change note that describes the problem may not be enough. We should at least describe what users can do to prevent ingesting duplicate data. Ideally, this change should only work for new `.gz` files - those that haven't been already ingested and fingerprinted using the previous method. Do you think that's possible?

File: pkg/stanza/fileconsumer/internal/reader/reader.go [hunk 10]
```diff
@@ -69,30 +70,30 @@ func (r *Reader) ReadToEnd(ctx context.Context) {
...
-		}
-		r.reader = gzipReader
 		// Offset tracking in an uncompressed file is based on the length of emitted tokens, but in this case
 		// we need to set the offset to the end of the file.
 		defer func() {
 			r.Offset = currentEOF
 		}()
+	case "auto":
+		// Identifying a filename by its extension may not always be correct. We could have a compressed file without the .gz extension
+		if r.FileType == ".gz" {
```
Comment (andrzej-stencel) [inline pkg/stanza/fileconsumer/internal/reader/reader.go:84]: `".gz"` should be a constant?

File: pkg/stanza/fileconsumer/internal/reader/reader.go [hunk 11]
```diff
@@ -33,6 +33,7 @@ type Metadata struct {
 	HeaderFinalized bool
 	FlushState      flush.State
 	TokenLenState   tokenlen.State
+	FileType        string
```
Comment (andrzej-stencel) [inline pkg/stanza/fileconsumer/internal/reader/reader.go:36]: Should this be a string of a custom type, perhaps based on string? Does this affect serialization?

File: pkg/stanza/fileconsumer/internal/fingerprint/fingerprint.go (hunk 6 above)
[the remark this answers is not in the document]
Comment (khushijain21) [reply pkg/stanza/fileconsumer/internal/fingerprint/fingerprint.go:37]: yes, I removed the breaking change from this PR and updated the description

File: pkg/stanza/fileconsumer/internal/reader/reader.go (hunk 11 above)
Comment (khushijain21) [reply pkg/stanza/fileconsumer/internal/reader/reader.go:36]: I think it is ok to keep it as string type.

**Comment by khushijain21** [comment]
Computing fingerprint for compressed files by decompressing its data will come in a follow up PR

**Review by atoulme — APPROVED** [review]

**Review by andrzej-stencel — APPROVED** [review]
