### PR TITLE
[exporter/elasticsearch] Fix data stream attributes in none mapping mode

### LINKED ISSUE #42454: [exporter/elasticsearch] `none` mapping mode incorrectly applies `Attributes` prefix to `data_stream.*` attributes.
### Component(s)

exporter/elasticsearch

## Description
When using `none` mapping mode on the `elasticsearch` exporter, attributes should appear in the final document as fields with `Attributes.` prepended to them. This usually works fine, but for the `data_stream.*` attributes that direct the document to the appropriate data stream, they appear without the "." (e.g. `Attributesdata_stream.*` instead of `Attributes.data_stream.*`).

I believe this is due to these lines:
https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/00f33e90da8885d458a8f84796b3601a46fc7b5e/exporter/elasticsearchexporter/model.go#L444

Current: `key+"data_stream.type"` = "Attributesdata_stream.type"
Fixed: `key+".data_stream.type"` = "Attributes.data_stream.type"

## Steps to Reproduce

1. Use an OpenTelemetry Collector configuration with an `elasticsearch` exporter that has `mapping.mode` set to `none`.
2. Send telemetry with `Resource.data_stream.*` attributes.

## Expected Result
```
{
  "_index": ".ds-logs-monocle.periscope.admiral.api-production-2025.09.03-000001",
  "_id": "rlHdDpkBl47pedJ-K7sA",
  "_version": 1,
  "_source": {
    "Attributes.data_stream.type": "logs",
    "Attributes.data_stream.namespace": "production",
    "Attributes.data_stream.dataset": "monocle.periscope.admiral.api"
  },
  "fields": {
    "Attributes.data_stream.type": [
      "logs"
    ],
    "Attributes.data_stream.namespace": [
      "production"
    ],
    "Attributes.data_stream.dataset": [
      "monocle.periscope.admiral.api"
    ]
  }
}
```

## Actual Result
```
{
  "_index": ".ds-logs-monocle.periscope.admiral.api-production-2025.09.03-000001",
  "_id": "rlHdDpkBl47pedJ-K7sA",
  "_version": 1,
  "_source": {
    "Attributesdata_stream.type": "logs",
    "Attributesdata_stream.namespace": "production",
    "Attributesdata_stream.dataset": "monocle.periscope.admiral.api"
  },
  "fields": {
    "Attributesdata_stream.type": [
      "logs"
    ],
    "Attributesdata_stream.namespace": [
      "production"
    ],
    "Attributesdata_stream.dataset": [
      "monocle.periscope.admiral.api"
    ]
  }
}
```

### Collector version

0.133.0

## Environment
OS: Ubuntu 24.04.1 LTS (WSL2)
Elasticsearch: 8.19.2

### OpenTelemetry Collector configuration

```yaml
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:

exporters:
  elasticsearch/logs:
    endpoints: ["http://elasticsearch:9200"]
    tls:
      insecure: true
    mapping:
      mode: none

  debug:
    verbosity: detailed

service:
  pipelines:
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [elasticsearch/logs, debug]
```

### Log output

```shell

```

### Additional context

_No response_

### Tip

<sub>[React](https://github.blog/news-insights/product-news/add-reactions-to-pull-requests-issues-and-comments/) with 👍 to help prioritize this issue. Please use comments to provide useful context, avoiding `+1` or `me too`, to help us triage it. Learn more [here](https://opentelemetry.io/community/end-user/issue-participation/).</sub>

### PR DESCRIPTION
**Pull request by ericywl**
## Description
Fix a bug where the data stream attributes in `none` mapping mode is incorrectly prefixed.

## Link to tracking issue
Fixes https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/42454.

## Testing
Unit tests.

### CODE REVIEW

**Review by carsonip — APPROVED** [review]
perfect, thanks!

**Review by carsonip — COMMENTED** [review]
missing a changelog

**Review by carsonip — APPROVED** [review]

File: exporter/elasticsearchexporter/model.go [hunk 1]
```diff
@@ -443,9 +443,13 @@ func (ecsDataPointsEncoder) encodeMetrics(
...
-		document.AddString(key+"data_stream.type", idx.Type)
-		document.AddString(key+"data_stream.dataset", idx.Dataset)
-		document.AddString(key+"data_stream.namespace", idx.Namespace)
+		prefix := ""
+		if key != "" {
+			prefix = key + "."
+		}
+		document.AddString(prefix+elasticsearch.DataStreamType, idx.Type)
+		document.AddString(prefix+elasticsearch.DataStreamDataset, idx.Dataset)
+		document.AddString(prefix+elasticsearch.DataStreamNamespace, idx.Namespace)
```
Comment (lahsivjar) [inline exporter/elasticsearchexporter/model.go]:
```suggestion
		if key != "" {
			key = key + "."
		}
		document.AddString(key+elasticsearch.DataStreamType, idx.Type)
		document.AddString(key+elasticsearch.DataStreamDataset, idx.Dataset)
		document.AddString(key+elasticsearch.DataStreamNamespace, idx.Namespace)
```

Nit, feel free to ignore.

**Review by lahsivjar — APPROVED** [review]
Minor nit.

**Review by ChrsMark — APPROVED** [review]

**Comment by ChrsMark** [comment]
@ericywl thank's for fixing this! Please consider the nit suggestion from https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/42510#discussion_r2329802899 and if you agree update the branch. Then I will mark it as `ready-to-merge`.

File: exporter/elasticsearchexporter/model.go [hunk 2]
```diff
@@ -443,9 +443,12 @@ func (ecsDataPointsEncoder) encodeMetrics(
 
 func addDataStreamAttributes(document *objmodel.Document, key string, idx elasticsearch.Index) {
 	if idx.IsDataStream() {
-		document.AddString(key+"data_stream.type", idx.Type)
-		document.AddString(key+"data_stream.dataset", idx.Dataset)
-		document.AddString(key+"data_stream.namespace", idx.Namespace)
+		if key != "" {
+			key = key + "."
```
Comment (carsonip) [inline exporter/elasticsearchexporter/model.go]:
```suggestion
			key += "."
```

**Review by carsonip — APPROVED** [review]
