### PR TITLE
[processor/k8sattribute] fix e2e flaky test

### LINKED ISSUE #18676: Flaky test: TestTraceE2E/statefulset
### Component(s)

processor/k8sattributes, testbed

### What happened?

See https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/4181235503/jobs/7242982697
```
=== RUN   TestTraceE2E/statefulset
    e2e_test.go:179: 
        	Error Trace:	/home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/processor/k8sattributesprocessor/e2e_test.go:179
        	            				/home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/processor/k8sattributesprocessor/e2e_test.go:[14](https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/4181235503/jobs/7242982697#step:24:15)6
        	Error:      	Received unexpected error:
        	            	the following errors occurred:
        	            	 -  k8s.annotations.workload attribute not found
        	            	 -  k8s.statefulset.uid attribute not found
        	            	 -  container.id attribute not found
        	            	 -  k8s.pod.name attribute not found
        	            	 -  k8s.node.name attribute not found
        	            	 -  container.image.tag attribute not found
        	            	 -  k8s.labels.app attribute not found
        	            	 -  k8s.pod.uid attribute not found
        	            	 -  k8s.pod.start_time attribute not found
        	            	 -  k8s.statefulset.name attribute not found
        	            	 -  k8s.namespace.name attribute not found
        	            	 -  container.image.name attribute not found
        	Test:       	TestTraceE2E/statefulset
```

### Collector version

0.71.0

### Environment information

_No response_

### OpenTelemetry Collector configuration

_No response_

### Log output

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by fatsheep9146**
**Description:** 
fix #18676

### CODE REVIEW

File: processor/k8sattributesprocessor/e2e_test.go [hunk 1]
```diff
@@ -175,10 +176,10 @@ func scanSpanForAttributes(t *testing.T, expectedService string, kvs map[string]
 			if service.AsString() != expectedService {
 				continue
 			}
-
-			assert.NoError(t, resourceHasAttributes(resourceSpans.Resource(), kvs))
+			err = resourceHasAttributes(resourceSpans.Resource(), kvs)
```
Comment (codeboten) [inline processor/k8sattributesprocessor/e2e_test.go:179]: should this check if the return from resourceHasAttribute is `nil` before assigning it? Otherwise I would expect this test to continue being flaky

Comment (fatsheep9146) [reply processor/k8sattributesprocessor/e2e_test.go:179]: I wrote like this, because, assume that there exist N lines of trace data,

the successful test case may be like following 2 

- the first M lines do not have the attributes appended, but the following N-M lines do have
- all the N lines do have the attributes appended

In those two cases, the `err` will all finally be nil.

the failed case must be 

- all the N lines  do not have the attributes appended 

so the `err` will be not nil.

I am not sure I explain my thinking clearly. :)

Comment (dmitryax) [reply processor/k8sattributesprocessor/e2e_test.go:179]: It's an appropriate remediation for the test flakiness, but it doesn't solve the root cause which is in the k8s attribute processor that doesn't enrich all the traces from the beginning as expected. @fatsheep9146, can you please file an issue so someone can follow up later on?

File: .chloggen/k8sattributes-e2e-flaky-test.yaml [hunk 2]
```diff
@@ -0,0 +1,16 @@
...
+# A brief description of the change.  Surround your text with quotes ("") if it needs to start with a backtick (`).
+note: fix flaky e2e test 
+
+# One or more tracking issues related to the change
+issues: [18676]
+
+# (Optional) One or more lines of additional information to render under the primary note.
+# These lines will be padded with 2 spaces and then inserted directly into the document.
+# Use pipe (|) for multiline entries.
+subtext:
```
Comment (dmitryax) [inline .chloggen/k8sattributes-e2e-flaky-test.yaml:16]: Don't need a changelog item for fixing a test

File: processor/k8sattributesprocessor/e2e_test.go (hunk 1 above)
Comment (fatsheep9146) [reply processor/k8sattributesprocessor/e2e_test.go:179]: ok, the issue is created. #18892
@dmitryax

**Review by codeboten — APPROVED** [review]
