### PR TITLE
[pkg/pdatautil] Fixed panic in nested map hashing

### LINKED ISSUE #18910: [pkg/pdatautil] Hashing Maps can panic with nested maps
### Component(s)

pkg/pdatautil

## Description
[writeMapHash](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/pkg/pdatautil/hash.go#L85-L100) can panic when iterating through nested maps as `hw.keysBuf` is overwritten every iteration. If a nested map key is not alphabetically last of all the keys in the map and it has at least one more key than its index in the parent map it'll cause the next iteration of the parent keys to try and find a child key instead.

## Steps to Reproduce

I created this test in `hash_test.go` that replicates the issue

```go
func TestMapHashPanic(t *testing.T) {
	m := pcommon.NewMap()
	m.PutInt("a", 1)
	m.PutInt("c", 1)
	m.PutInt("d", 1)
	m.PutInt("e", 1)
       
        // nestedMap is alphabetically second in parent map
	nestedMap := m.PutEmptyMap("b")

        // nestedMap is index 1 in parent when keys are sorted so we need at least 3 keys in this to ensure the next iteration of parent tries to find a key at "a3"
	nestedMap.PutInt("a1", 1)
	nestedMap.PutInt("a2", 1)
	nestedMap.PutInt("a3", 1)

	assert.NotPanics(t, func() { MapHash(m) })
}
```

## Expected Result
No Panic

## Actual Result
Panic due to invalid key access

Panic stack from test:

```
func (assert.PanicTestFunc)(0x10514e600) should not panic
Panic value:	runtime error: invalid memory address or nil pointer dereference
Panic stack:	goroutine 34 [running]:
runtime/debug.Stack()
	/usr/local/go/src/runtime/debug/stack.go:24 +0x64
github.com/stretchr/testify/assert.didPanic.func1()
	/Users/cphelps/go/pkg/mod/github.com/stretchr/testify@v1.8.1/assert/assertions.go:1050 +0x74
panic({0x1052ab4e0, 0x10570c4a0})
	/usr/local/go/src/runtime/panic.go:884 +0x1f4
go.opentelemetry.io/collector/pdata/pcommon.Value.Type(...)
	/Users/cphelps/go/pkg/mod/go.opentelemetry.io/collector/pdata@v1.0.0-rc6/pcommon/value.go:178
github.com/open-telemetry/opentelemetry-collector-contrib/pkg/pdatautil.(*hashWriter).writeValueHash(0x140001285a0?, {0x1400013c380?})
	/Users/cphelps/git/opentelemetry-collector-contrib/pkg/pdatautil/hash.go:109 +0x54
github.com/open-telemetry/opentelemetry-collector-contrib/pkg/pdatautil.(*hashWriter).writeMapHash(0x140001edf80, {0x100019798?})
	/Users/cphelps/git/opentelemetry-collector-contrib/pkg/pdatautil/hash.go:98 +0xe8
github.com/open-telemetry/opentelemetry-collector-contrib/pkg/pdatautil.MapHash({0x1052a7f80?})
	/Users/cphelps/git/opentelemetry-collector-contrib/pkg/pdatautil/hash.go:72 +0xd0
github.com/open-telemetry/opentelemetry-collector-contrib/pkg/pdatautil.TestMapHashPanic.func1()
	/Users/cphelps/git/opentelemetry-collector-contrib/pkg/pdatautil/hash_test.go:150 +0x20
github.com/stretchr/testify/assert.didPanic(0x140001a0600?)
	/Users/cphelps/go/pkg/mod/github.com/stretchr/testify@v1.8.1/assert/assertions.go:1055 +0x7c
github.com/stretchr/testify/assert.NotPanics({0x105357468, 0x1400011f520}, 0x1400010b010, {0x0, 0x0, 0x0})
	/Users/cphelps/go/pkg/mod/github.com/stretchr/testify@v1.8.1/assert/assertions.go:1126 +0x64
github.com/open-telemetry/opentelemetry-collector-contrib/pkg/pdatautil.TestMapHashPanic(0x0?)
	/Users/cphelps/git/opentelemetry-collector-contrib/pkg/pdatautil/hash_test.go:150 +0x144
testing.tRunner(0x1400011f520, 0x105352998)
	/usr/local/go/src/testing/testing.go:1576 +0x104
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:1629 +0x370
```

### Collector version

v0.72.0

## Environment
OS: macOS 13.2.1
Compiler(if manually compiled): go 1.20.1

### OpenTelemetry Collector configuration

_No response_

### Log output

_No response_

### Additional context

I think the keyset that's iterated through likely needs to be stored in a variable that's local to the `writeMapHash` function. Every nested map will overwrite that keyset for it's parent.

### PR DESCRIPTION
**Pull request by cpheps**
**Description:**
Fixes #18910

Changed how the `keysBuf` works so that nested maps will append their keys to the buffer for that recursion then they will be removed before the recursion exist.  This allows keeping a single buffer while also protecting ensure recursion doesn't pollute the buffer order.

**Link to tracking Issue:** #18910

**Testing:** Added a unit test that could replicate the panic in the old code.

### CODE REVIEW

**Comment by cpheps** [comment]
I don't think PR failures are related to my changes.

**Review by djaglowski — COMMENTED** [review]
Rather than throw out the optimization altogether, can we find a way to handle recursion correctly?

At a minimum, I think we could pass a bool to `writeMapHash` that indicates whether it is a recursive call or not. `MapHash` can pass `false`, while `writeValueHash` passes `true`. Then at least we keep the optimization for non-recursive maps, which is likely the majority of cases.

Possibly an even better solution would have nested maps request their own `hashWriter` from the pool and use that, rather than polluting the existing one. This would require a bit more work, so maybe can be a separate issue.

**Comment by cpheps** [comment]
@djaglowski I reworked this to use a single buffer and some slice tricks to only focus on the current recursions key set. Let me know if this seems like a better solution.

File: pkg/pdatautil/hash_test.go [hunk 1]
```diff
@@ -136,6 +136,26 @@ func TestMapHash(t *testing.T) {
 	}
 }
 
+// TestMapHashPanic tests a very specific case where a panic can occur with nested maps.
+// Outlined in https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/18910
+func TestMapHashPanic(t *testing.T) {
```
Comment (djaglowski) [inline pkg/pdatautil/hash_test.go:141]: Can this be converted into a case in the above test? The test won't pass if it panics, right? I think the comment w/ link is useful for context, but it can be noted along with the case.

File: pkg/pdatautil/hash.go [hunk 2]
```diff
@@ -83,20 +83,26 @@ func ValueHash(v pcommon.Value) [16]byte {
 }
 
 func (hw *hashWriter) writeMapHash(m pcommon.Map) {
-	hw.keysBuf = hw.keysBuf[:0]
+	nextIndex := len(hw.keysBuf)
```
Comment (djaglowski) [inline pkg/pdatautil/hash.go:86]: I was stuck on thinking that this wouldn't work because buffers are reused. However, I see that ultimately the buffer is wiped before returning to the pool. It only retains values so long as it's processing a map and its nested maps. Clever, but I think this warrants an explanatory comment.

Comment (djaglowski) [reply pkg/pdatautil/hash.go:89]: Can you have the comment address why this works in the non-recursive case as well? e.g. reused buffers are guaranteed to be cleared because the buffer is always cleared before it is returned to the pool.

**Review by djaglowski — APPROVED** [review]
LGTM

**Review by dmitryax — APPROVED** [review]
