### PR TITLE
[processor/k8sattributeprocessor] fix: only set pod ip when explicitl…

### LINKED ISSUE #43862: [processor/k8sattributes] `k8s.pod.ip` attribute is always set when connection association applied
### Component(s)

processor/k8sattributes

## Description

The k8sattributes processor always set k8s.pod.ip even if it's not requested by the user when connection association is applied

## Steps to Reproduce

```yaml
      k8sattributes/node_uid:
        extract:
          metadata:
          - k8s.pod.name
        pod_association:
        - sources:
          - from: connection     
```

## Expected Result

Telemetry with only one `k8s.pod.name` attribute added

## Actual Result

`k8s.pod.name` and `k8s.pod.ip` are added

### Tip

<sub>[React](https://github.blog/news-insights/product-news/add-reactions-to-pull-requests-issues-and-comments/) with 👍 to help prioritize this issue. Please use comments to provide useful context, avoiding `+1` or `me too`, to help us triage it. Learn more [here](https://opentelemetry.io/community/end-user/issue-participation/).</sub>

### PR DESCRIPTION
**Pull request by LeonLow97**
#### Description

- `k8s.pod.ip` was always set when connection association was applied, even if not requested by user.
- The fix is on k8sattributes processor to only set `k8s.pod.ip` attribute when it is requested in the `extract.metadata` configuration.

#### Link to tracking issue
Fixes #43862 

#### Testing

- Added unit test `TestProcessorDoesNotSetPodIPWhenNotRequested` to verify that `k8s.pod.ip` is only set when included in `extract.metadata`.

### CODE REVIEW

File: processor/k8sattributesprocessor/processor.go [hunk 1]
```diff
@@ -144,7 +144,9 @@ func (kp *kubernetesprocessor) processResource(ctx context.Context, resource pco
 
 	for i := range podIdentifierValue {
 		if podIdentifierValue[i].Source.From == kube.ConnectionSource && podIdentifierValue[i].Value != "" {
-			setResourceAttribute(resource.Attributes(), kube.K8sIPLabelName, podIdentifierValue[i].Value)
+			if kp.rules.PodIP {
+				setResourceAttribute(resource.Attributes(), kube.K8sIPLabelName, podIdentifierValue[i].Value)
+			}
```
Comment (TylerHelmuth) [inline processor/k8sattributesprocessor/processor.go:149]: Can you confirm that the pod ip is still extracted by default if the user supplies no specific `extract` config?

Comment (LeonLow97) [reply processor/k8sattributesprocessor/processor.go:149]: @TylerHelmuth Currently, k8s.pod.ip is not extracted by default as shown in metadata.yaml (`processor/k8sattributesprocessor/metadata.yaml`) which has `enabled: false`.

It’s only set when the user explicitly includes `k8s.pod.ip` in the `extract.metadata` configuration.
So by default, if the user supplies no extract config, the processor will not extract the Pod IP.

Hope that answers your question 🙏🏻

Comment (TylerHelmuth) [reply processor/k8sattributesprocessor/processor.go:149]: You're right thank you

**Review by TylerHelmuth — APPROVED** [review]

**Comment by TylerHelmuth** [comment]
Please add a changelog entry

**Comment by LeonLow97** [comment]
> Please add a changelog entry

@TylerHelmuth I will add a changelog entry soon! I noticed some E2E tests are failing too, will be fixing those as well 👍🏻

**Comment by LeonLow97** [comment]
@TylerHelmuth I have added a CHANGELOG and also fixed the failing E2E tests, can I have a review please? 🙏🏻

File: processor/k8sattributesprocessor/e2e_test.go [hunk 2]
```diff
@@ -137,7 +137,6 @@ func TestE2E_ClusterRBAC(t *testing.T) {
 			service:  "test-traces-cronjob",
 			attrs: map[string]*expectedValue{
 				"k8s.pod.name":                 newExpectedValue(regex, "telemetrygen-"+testID+"-traces-cronjob-[a-z0-9-]*"),
-				"k8s.pod.ip":                   newExpectedValue(exist, ""),
```
Comment (ChrsMark) [inline processor/k8sattributesprocessor/e2e_test.go:140]: Can we keep at least one e2e test that explicitly enables this attribute so as to cover both cases?

File: .chloggen/bugfix_k8sattributeprocessor-only-set-pod-ip-if-requested.yaml [hunk 3]
```diff
@@ -4,13 +4,13 @@
 change_type: bug_fix
```
Comment (ChrsMark) [inline .chloggen/bugfix_k8sattributeprocessor-only-set-pod-ip-if-requested.yaml:4]: Probably that might break users that wrongly rely on this buggy behavior. But I think that's fine since we explicitly consider this as a bug.

Comment (LeonLow97) [reply .chloggen/bugfix_k8sattributeprocessor-only-set-pod-ip-if-requested.yaml:4]: Yeah that's true, I added a subtext to add some information on this change, maybe that will help !

File: processor/k8sattributesprocessor/e2e_test.go (hunk 2 above)
Comment (LeonLow97) [reply processor/k8sattributesprocessor/e2e_test.go:140]: Yeap let's add that! I have added it in `TestE2E_MixRBAC` and also in the respective config file `processor/k8sattributesprocessor/testdata/e2e/mixrbac/collector/configmap.yaml`

**Review by ChrsMark — APPROVED** [review]

**Comment by LeonLow97** [comment]
@TylerHelmuth @ChrsMark Hi, are there any other comments? If not, can we merge this please? ☺️

File: .chloggen/bugfix_k8sattributeprocessor-only-set-pod-ip-if-requested.yaml (hunk 3 above)
Comment (asweet-confluent) [reply .chloggen/bugfix_k8sattributeprocessor-only-set-pod-ip-if-requested.yaml:4]: This was definitely a breaking a change, and marking it as such would have been very helpful.
