### PR TITLE
[exporter/loadbalancing] drop resources if the service routing key does not exist

### LINKED ISSUE #41550: [exporter/loadbalacingexporter] missing service.name leads to blocked exporter when using resilience options
### Component(s)

_No response_

## Description
When metric data with missing routing_key attribute `service.name` is about to be routed to a backend at an load balacing otel collector with enabled resilience options (retries) then this situation can lead to a blocked otel otel collector.

## Steps to Reproduce
otel-collector-config for loadbalacing:
````
receivers:
  otlp:
    protocols:
      grpc:
      http:
exporters:
  debug:
    verbosity: detailed
  loadbalancing:
    timeout: 10s
    retry_on_failure:
      enabled: true
    sending_queue:
      enabled: true
      num_consumers: 10
      queue_size: 1000
      sizer: requests
    protocol:
      otlp:
        tls:
          insecure: true
    resolver:
      static:
        hostnames:
          - localhost:5317
          - localhost:6317

service:
  telemetry:
    metrics:
      level: none
  pipelines:
    metrics:
      receivers: [otlp]
      processors: []
      exporters:
        - debug
        - loadbalancing
````

Test-Ingest with missing `service.name`:
````
cat demo-metrics.json
{
    "resourceMetrics": [
        {
            "resource": {
                "attributes": [
                    {
                        "key": "service.name.bla",
                        "value": {
                            "stringValue": "basic-metric-service"
                        }
                    }
                ],
                "droppedAttributesCount": 0
            },
            "scopeMetrics": [
                {
                    "metrics": [
                        {
                            "description": "Example of a Counter",
                            "name": "requests",
                            "sum": {
                                "aggregationTemporality": 2,
                                "dataPoints": [
                                    {
                                        "asDouble": 1,
                                        "attributes": [],
                                        "startTimeUnixNano": 1651578664709780000,
                                        "timeUnixNano": 1651578666712823600
                                    }
                                ],
                                "isMonotonic": true
                            },
                            "unit": "1"
                        }
                    ],
                    "scope": {
                        "name": "example-exporter-collector",
                        "version": "",
                        "extraKey": "value"
                    }
                }
            ]
        }
    ]
}

# Ingest 100 metric points with missing service.name
for i in $(seq 1 100); do curl -d @demo-metrics.json -H "Content-Type: application/json" http://localhost:4318/v1/metrics ; done

# Now try to ingest regular metric data with service.name
bin/telemetrygen metrics --otlp-http --otlp-insecure --service "bla"

````

## Expected Result
metrics created from telemetrygen should arrive at one of the two backend collectors.

## Actual Result
The loadbalacing otel-collector is logging this constantly:
````
2025-07-25T07:20:16.427+0200	info	internal/retry_sender.go:133	Exporting failed. Will retry the request after interval.	{"error": "unable to get service name", "interval": "0s"}
````

The collector is trying to resend the metric data indefinitely. 
In my optioion this is a bug. Data which got rejected because of a missing attribute should not be retried but dropped.

### Collector version

0.124

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

### OpenTelemetry Collector configuration

```yaml

```

### Log output

```shell

```

### Additional context

_No response_

### Tip

<sub>[React](https://github.blog/news-insights/product-news/add-reactions-to-pull-requests-issues-and-comments/) with 👍 to help prioritize this issue. Please use comments to provide useful context, avoiding `+1` or `me too`, to help us triage it. Learn more [here](https://opentelemetry.io/community/end-user/issue-participation/).</sub>

### PR DESCRIPTION
**Pull request by odubajDT**
#### Description

Drop metric resources, which do not have service.name defined to avoid blocking behavior when retry resilience option 1 is enabled

#### Link to tracking issue
Fixes #41550

### CODE REVIEW

**Review by rlankfo — APPROVED** [review]

File: exporter/loadbalancingexporter/metrics_exporter.go [hunk 1]
```diff
@@ -98,10 +97,12 @@ func (e *metricExporterImp) ConsumeMetrics(ctx context.Context, md pmetric.Metri
...
-		var err error
-		batches, err = splitMetricsByResourceServiceName(md)
-		if err != nil {
-			return err
+		var errs []error
+		batches, errs = splitMetricsByResourceServiceName(md)
+		if len(errs) > 0 {
+			for _, ee := range errs {
+				e.logger.Error("failed to export metric", zap.Error(ee))
+			}
```
Comment (evan-bradley) [inline exporter/loadbalancingexporter/metrics_exporter.go:107]:
```suggestion
			}
			if len(batches) == 0 {
				return consumererror.NewPermanent(errors.Join(ee))
			}
```
This may be an uncommon case, but if we hit a "full failure" as opposed to a partial success/"partial failure", we should still return an error back up the pipeline. Wrapping an error with `consumererror.NewPermanent` ensures that data isn't retried.

This won't _generally_ matter, but in the case where the load balancing Collector is synchronous, it will return the error to the network caller.

**Review by evan-bradley — APPROVED** [review]
