### PR TITLE
Remove high-cardinality attribute from AWS Container Insight metrics

### LINKED ISSUE #35861: [receiver/awscontainerinsight] High cardinality with default configuration
### Component(s)

receiver/awscontainerinsight

## Description
Enabling the receiver generates high cardinality metrics since, by default, it adds `Timestamp` to the published metrics resource. 

## Steps to Reproduce
Enable the receiver in an AWS ECS EC2 cluster.

## Expected Result
No high cardinality metrics from enabling the receiver.

## Actual Result
High cardinality metrics.

### Collector version

v0.111.0

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

### OpenTelemetry Collector configuration

_No response_

### Log output

_No response_

### Additional context

The `Timestamp` may be useful for some post processing by some AWS service, however, per general recommendation on OTel high-cardinality metrics should be avoided on the default configuration, even if a workaround using the resource attribute processor is relatively easy. It seems to me that this attribute should be disabled by default and possibly enabled by some specific configuration.

### PR DESCRIPTION
**Pull request by pjanotti**
#### Description
Per code inspection it looks like `tags` was being used as a convenience feature to pass the timestamp when converting the metrics to OTLP. However, timestamp should not be a resource attribute due to causing high-cardinality time series.

This change keeps the current usage of `tags`, but, ensures that timestamp is not added as a resource attribute. Code owners should consider if later the timestamp should be passed outside the `tags` map - a change much larger than the current one.

#### Link to tracking issue
Fixes #35861

#### Testing
Updated respective tests.

#### Documentation
Changelog added.

### CODE REVIEW

File: internal/aws/containerinsight/utils.go [hunk 1]
```diff
@@ -166,8 +167,9 @@ func ConvertToOTLPMetrics(fields map[string]any, tags map[string]string, logger
 		if tagKey == Timestamp {
 			timeNs, _ := strconv.ParseUint(tagValue, 10, 64)
 			timestamp = pcommon.Timestamp(timeNs)
```
Comment (pjanotti) [inline internal/aws/containerinsight/utils.go:169]: `timestamp` is added to the data point itself, so it still needs to be calculated

**Review by atoulme — APPROVED** [review]

File: internal/aws/containerinsight/utils.go (hunk 1 above)
Comment (pxaws) [reply internal/aws/containerinsight/utils.go:169]: I am a little worried that this will break the use cases for AWS Container Insights. Have you tested it with AWS Container Insights?

Comment (pjanotti) [reply internal/aws/containerinsight/utils.go:169]: Thanks @pxaws - besides the tests in the repo I deployed it, but, in my case I consume the metrics via the OTLP exporter. Do you have a specific test in mind to validate that?

Comment (pjanotti) [reply internal/aws/containerinsight/utils.go:169]: A second thought: we remove it, if it causes problems, I can quickly add an option to make it configurable.

Comment (pxaws) [reply internal/aws/containerinsight/utils.go:169]: OK. In this case, you can go ahead.

**Review by pxaws — APPROVED** [review]
