### PR TITLE
[exporter/azureblob] Fix Azure Blob Storage name to avoid breaking file extension

### LINKED ISSUE #39593: Azureblob Exporter: Blob names include serial number after .json instead of before, breaking file extension
### Component(s)

exporter/azureblob

## Description

When using the Azure Blob Exporter, the generated blob names append the serial number after the file extension (e.g. .json_3535), resulting in an invalid or misleading file extension.

## Steps to Reproduce

1. Use opentelemetry-collector-contrib:0.124.1 as the base image.
2. Add the below azureblob exporter configuration.

## Expected Result

`logs/2024/04/15/logs_15_04_05_3742.json`

## Actual Result

`logs/2024/04/15/logs_15_04_05.json_3742`

### Collector version

0.124.1

### OpenTelemetry Collector configuration

```yaml
exporters:
  azureblob:
    auth:
      type: "connection_string"
      connection_string: "DefaultEndpointsProtocol=https;AccountName=$(AZURE_STORAGE_ACCOUNT);AccountKey=$(AZURE_STORAGE_ACCESS_KEY);EndpointSuffix=core.windows.net"
```

### Log output

```shell

```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by petern48**
#### Description
Add Fix Azure Blob Storage name to avoid breaking file extension. Previously the final blob names looked like the following:
```
2025/04/24/traces_00_59_20.json_6651
```
^(this is the actual result I took from one of the raw logs generated from running the unit test)

Now they properly append the random number before the file extension:
```
2025/04/24/traces_00_59_49_4913.json
```

EDIT: This logic has now been made configurable instead of the default.

#### Link to tracking issue
Fixes #39593

#### Testing
Added a new test `TestGenerateBlobNameSerialNumBefore`

#### Documentation
Updated the `README.md` with the new config option

### CODE REVIEW

File: exporter/azureblobexporter/exporter.go [hunk 1]
```diff
@@ -202,6 +209,7 @@ func (e *azureBlobExporter) ConsumeTraces(ctx context.Context, td ptrace.Traces)
 func (e *azureBlobExporter) consumeData(ctx context.Context, data []byte, signal pipeline.Signal) error {
 	// Generate a unique blob name
 	blobName, err := e.generateBlobName(signal)
+	fmt.Println("BLOB NAME: ", blobName, " config name", e.config.BlobNameFormat.MetricsFormat)
```
Comment (hgaol) [inline exporter/azureblobexporter/exporter.go:212]: pls use logger instead of Println

File: .chloggen/fix_azure_blob_name.yaml [hunk 2]
```diff
@@ -0,0 +1,27 @@
+# Use this changelog template to create an entry for release notes.
+
+# One of 'breaking', 'deprecation', 'new_component', 'enhancement', 'bug_fix'
+change_type: 'bug_fix'
```
Comment (hgaol) [inline .chloggen/fix_azure_blob_name.yaml:4]: I think it's an enhancement instead of bug_fix

**Review by hgaol — COMMENTED** [review]
Pls add a switch setting for this enhancement.

File: exporter/azureblobexporter/exporter.go (hunk 1 above)
Comment (petern48) [reply exporter/azureblobexporter/exporter.go:212]: Left in my accident, whoops.

File: exporter/azureblobexporter/README.md [hunk 3]
```diff
@@ -36,6 +36,7 @@ The following settings can be optionally configured and have default values:
   - logs_format (default `2006/01/02/logs_15_04_05.json`): blob name format.
   - traces_format (default `2006/01/02/traces_15_04_05.json`): blob name format.
   - serial_num_range (default `10000`): a range of random number to be appended after blob_name. e.g. `blob_name_{serial_num}`.
+  - serial_num_before_extension (default `false`): places the serial number before the file extension if there is one. e.g `blob_name{serial_num}.json` instead of `blob_name_{serial_num}.json`
```
Comment (hgaol) [inline exporter/azureblobexporter/README.md:39]: instead of `blob_name_{serial_num}`?

**Comment by hgaol** [comment]
LGTM after the NIT fix.

File: exporter/azureblobexporter/README.md (hunk 3 above)
Comment (petern48) [reply exporter/azureblobexporter/README.md]: Great catch thanks.

**Review by hgaol — APPROVED** [review]

**Review by atoulme — APPROVED** [review]
